.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */


glabel WaitEvent
    /* 7DFB0 8008D7B0 B0000A24 */  addiu      $t2, $zero, 0xB0
    /* 7DFB4 8008D7B4 08004001 */  jr         $t2
    /* 7DFB8 8008D7B8 0A000924 */   addiu     $t1, $zero, 0xA
endlabel WaitEvent
