#define ROOMLIB_UPDATE_DAMPED_PARTICLE_NAME func_80192C8C
#define ROOMLIB_DAMPED_PARTICLE_SEED D_8018F1D8
#define ROOMLIB_DAMPED_PARTICLE_TABLE D_80194844
#include "../room_lib/RoomLib_UpdateDampedParticle.inc"
