/* MASPSX_FLAGS: --expand-div */
#define ROOMEFFECT_SEEKING_TRAIL_FUNC func_80192500
#define ROOMEFFECT_SEEKING_TRAIL_COLOR_A D_8018F1CC
#define ROOMEFFECT_SEEKING_TRAIL_COLOR_B D_8018F1D0
#define ROOMEFFECT_SEEKING_TRAIL_ROTATION D_8018F1D4
#define ROOMEFFECT_SEEKING_TRAIL_HISTORY D_8019581C
#include "../room_lib/RoomEffect_SeekingTrailController.inc"
