.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.4 */

nonmatching Akao_ClearVoiceBank, 0x260

glabel Akao_ClearVoiceBank
    /* 5AE74 8006A674 21280000 */  addu       $a1, $zero, $zero
    /* 5AE78 8006A678 0B80063C */  lui        $a2, %hi(g_GameState)
    /* 5AE7C 8006A67C D80CC624 */  addiu      $a2, $a2, %lo(g_GameState)
    /* 5AE80 8006A680 2120C000 */  addu       $a0, $a2, $zero
    /* 5AE84 8006A684 03000224 */  addiu      $v0, $zero, 0x3
    /* 5AE88 8006A688 0000C2AC */  sw         $v0, 0x0($a2)
    /* 5AE8C 8006A68C 0A000224 */  addiu      $v0, $zero, 0xA
    /* 5AE90 8006A690 0B80013C */  lui        $at, %hi(D_800B0CDC)
    /* 5AE94 8006A694 DC0C22A4 */  sh         $v0, %lo(D_800B0CDC)($at)
    /* 5AE98 8006A698 FFFF0224 */  addiu      $v0, $zero, -0x1
    /* 5AE9C 8006A69C 0B80013C */  lui        $at, %hi(D_800B0CDE)
    /* 5AEA0 8006A6A0 DE0C22A4 */  sh         $v0, %lo(D_800B0CDE)($at)
    /* 5AEA4 8006A6A4 02000224 */  addiu      $v0, $zero, 0x2
    /* 5AEA8 8006A6A8 FFFF0324 */  addiu      $v1, $zero, -0x1
    /* 5AEAC 8006A6AC 0B80013C */  lui        $at, %hi(D_800B0CE0)
    /* 5AEB0 8006A6B0 E00C22A0 */  sb         $v0, %lo(D_800B0CE0)($at)
    /* 5AEB4 8006A6B4 0B000224 */  addiu      $v0, $zero, 0xB
    /* 5AEB8 8006A6B8 0B80013C */  lui        $at, %hi(D_800B0CE2)
    /* 5AEBC 8006A6BC E20C22A0 */  sb         $v0, %lo(D_800B0CE2)($at)
    /* 5AEC0 8006A6C0 01000224 */  addiu      $v0, $zero, 0x1
    /* 5AEC4 8006A6C4 0B80013C */  lui        $at, %hi(D_800B0CE1)
    /* 5AEC8 8006A6C8 E10C23A0 */  sb         $v1, %lo(D_800B0CE1)($at)
    /* 5AECC 8006A6CC 0B80013C */  lui        $at, %hi(D_800B0CE3)
    /* 5AED0 8006A6D0 E30C20A0 */  sb         $zero, %lo(D_800B0CE3)($at)
    /* 5AED4 8006A6D4 0B80013C */  lui        $at, %hi(D_800B0CE4)
    /* 5AED8 8006A6D8 E40C23A0 */  sb         $v1, %lo(D_800B0CE4)($at)
    /* 5AEDC 8006A6DC 0B80013C */  lui        $at, %hi(D_800B0CE5)
    /* 5AEE0 8006A6E0 E50C22A0 */  sb         $v0, %lo(D_800B0CE5)($at)
    /* 5AEE4 8006A6E4 0B80013C */  lui        $at, %hi(D_800B0CE6)
    /* 5AEE8 8006A6E8 E60C20A0 */  sb         $zero, %lo(D_800B0CE6)($at)
    /* 5AEEC 8006A6EC 0B80013C */  lui        $at, %hi(D_800B0CE7)
    /* 5AEF0 8006A6F0 E70C20A0 */  sb         $zero, %lo(D_800B0CE7)($at)
    /* 5AEF4 8006A6F4 0B80013C */  lui        $at, %hi(D_800B0CE8)
    /* 5AEF8 8006A6F8 E80C20A0 */  sb         $zero, %lo(D_800B0CE8)($at)
    /* 5AEFC 8006A6FC 0B80013C */  lui        $at, %hi(D_800B0CE9)
    /* 5AF00 8006A700 E90C20A0 */  sb         $zero, %lo(D_800B0CE9)($at)
    /* 5AF04 8006A704 0B80013C */  lui        $at, %hi(D_800B0CEA)
    /* 5AF08 8006A708 EA0C20A0 */  sb         $zero, %lo(D_800B0CEA)($at)
    /* 5AF0C 8006A70C 0B80013C */  lui        $at, %hi(D_800B0CEB)
    /* 5AF10 8006A710 EB0C20A0 */  sb         $zero, %lo(D_800B0CEB)($at)
  .L8006A714:
    /* 5AF14 8006A714 140080AC */  sw         $zero, 0x14($a0)
    /* 5AF18 8006A718 0100A524 */  addiu      $a1, $a1, 0x1
    /* 5AF1C 8006A71C 3100A22C */  sltiu      $v0, $a1, 0x31
    /* 5AF20 8006A720 FCFF4014 */  bnez       $v0, .L8006A714
    /* 5AF24 8006A724 04008424 */   addiu     $a0, $a0, 0x4
    /* 5AF28 8006A728 21280000 */  addu       $a1, $zero, $zero
    /* 5AF2C 8006A72C FFFF0424 */  addiu      $a0, $zero, -0x1
    /* 5AF30 8006A730 2118C000 */  addu       $v1, $a2, $zero
    /* 5AF34 8006A734 08000224 */  addiu      $v0, $zero, 0x8
    /* 5AF38 8006A738 D900C2A0 */  sb         $v0, 0xD9($a2)
    /* 5AF3C 8006A73C FFFF0224 */  addiu      $v0, $zero, -0x1
    /* 5AF40 8006A740 D800C0A0 */  sb         $zero, 0xD8($a2)
    /* 5AF44 8006A744 DB00C2A0 */  sb         $v0, 0xDB($a2)
    /* 5AF48 8006A748 DA00C2A0 */  sb         $v0, 0xDA($a2)
  .L8006A74C:
    /* 5AF4C 8006A74C DD0064A0 */  sb         $a0, 0xDD($v1)
    /* 5AF50 8006A750 DC0064A0 */  sb         $a0, 0xDC($v1)
    /* 5AF54 8006A754 0100A524 */  addiu      $a1, $a1, 0x1
    /* 5AF58 8006A758 0200A228 */  slti       $v0, $a1, 0x2
    /* 5AF5C 8006A75C FBFF4014 */  bnez       $v0, .L8006A74C
    /* 5AF60 8006A760 02006324 */   addiu     $v1, $v1, 0x2
    /* 5AF64 8006A764 0980053C */  lui        $a1, %hi(D_80094488)
    /* 5AF68 8006A768 8844A524 */  addiu      $a1, $a1, %lo(D_80094488)
    /* 5AF6C 8006A76C 21200000 */  addu       $a0, $zero, $zero
    /* 5AF70 8006A770 7F000224 */  addiu      $v0, $zero, 0x7F
    /* 5AF74 8006A774 FF00C2A0 */  sb         $v0, 0xFF($a2)
    /* 5AF78 8006A778 FE00C2A0 */  sb         $v0, 0xFE($a2)
    /* 5AF7C 8006A77C 27000224 */  addiu      $v0, $zero, 0x27
    /* 5AF80 8006A780 E000C2A0 */  sb         $v0, 0xE0($a2)
    /* 5AF84 8006A784 0D000224 */  addiu      $v0, $zero, 0xD
    /* 5AF88 8006A788 E100C2A0 */  sb         $v0, 0xE1($a2)
    /* 5AF8C 8006A78C 01000224 */  addiu      $v0, $zero, 0x1
    /* 5AF90 8006A790 FFFF0324 */  addiu      $v1, $zero, -0x1
    /* 5AF94 8006A794 E300C2A0 */  sb         $v0, 0xE3($a2)
    /* 5AF98 8006A798 98000224 */  addiu      $v0, $zero, 0x98
    /* 5AF9C 8006A79C E600C2A0 */  sb         $v0, 0xE6($a2)
    /* 5AFA0 8006A7A0 FFFF0224 */  addiu      $v0, $zero, -0x1
    /* 5AFA4 8006A7A4 E200C0A0 */  sb         $zero, 0xE2($a2)
    /* 5AFA8 8006A7A8 E400C3A4 */  sh         $v1, 0xE4($a2)
    /* 5AFAC 8006A7AC E700C2A0 */  sb         $v0, 0xE7($a2)
    /* 5AFB0 8006A7B0 E800C3A4 */  sh         $v1, 0xE8($a2)
    /* 5AFB4 8006A7B4 EB00C0A0 */  sb         $zero, 0xEB($a2)
    /* 5AFB8 8006A7B8 EA00C0A0 */  sb         $zero, 0xEA($a2)
  .L8006A7BC:
    /* 5AFBC 8006A7BC 0600A0A4 */  sh         $zero, 0x6($a1)
    /* 5AFC0 8006A7C0 0980013C */  lui        $at, %hi(D_8009448C)
    /* 5AFC4 8006A7C4 21082400 */  addu       $at, $at, $a0
    /* 5AFC8 8006A7C8 8C4420A4 */  sh         $zero, %lo(D_8009448C)($at)
    /* 5AFCC 8006A7CC 08008424 */  addiu      $a0, $a0, 0x8
    /* 5AFD0 8006A7D0 20008228 */  slti       $v0, $a0, 0x20
    /* 5AFD4 8006A7D4 F9FF4014 */  bnez       $v0, .L8006A7BC
    /* 5AFD8 8006A7D8 0800A524 */   addiu     $a1, $a1, 0x8
    /* 5AFDC 8006A7DC 00E1043C */  lui        $a0, (0xE1000440 >> 16)
    /* 5AFE0 8006A7E0 40048434 */  ori        $a0, $a0, (0xE1000440 & 0xFFFF)
    /* 5AFE4 8006A7E4 02000524 */  addiu      $a1, $zero, 0x2
    /* 5AFE8 8006A7E8 30000224 */  addiu      $v0, $zero, 0x30
    /* 5AFEC 8006A7EC F600C2A0 */  sb         $v0, 0xF6($a2)
    /* 5AFF0 8006A7F0 7F000224 */  addiu      $v0, $zero, 0x7F
    /* 5AFF4 8006A7F4 F700C2A0 */  sb         $v0, 0xF7($a2)
    /* 5AFF8 8006A7F8 00010224 */  addiu      $v0, $zero, 0x100
    /* 5AFFC 8006A7FC F800C2A4 */  sh         $v0, 0xF8($a2)
    /* 5B000 8006A800 00080224 */  addiu      $v0, $zero, 0x800
    /* 5B004 8006A804 FA00C2A4 */  sh         $v0, 0xFA($a2)
    /* 5B008 8006A808 03000224 */  addiu      $v0, $zero, 0x3
    /* 5B00C 8006A80C 0701C2A0 */  sb         $v0, 0x107($a2)
    /* 5B010 8006A810 60000224 */  addiu      $v0, $zero, 0x60
    /* 5B014 8006A814 0B01C2A0 */  sb         $v0, 0x10B($a2)
    /* 5B018 8006A818 40010224 */  addiu      $v0, $zero, 0x140
    /* 5B01C 8006A81C 1001C2A4 */  sh         $v0, 0x110($a2)
    /* 5B020 8006A820 E0000224 */  addiu      $v0, $zero, 0xE0
    /* 5B024 8006A824 1201C2A4 */  sh         $v0, 0x112($a2)
    /* 5B028 8006A828 01000224 */  addiu      $v0, $zero, 0x1
    /* 5B02C 8006A82C 1701C2A0 */  sb         $v0, 0x117($a2)
    /* 5B030 8006A830 0B01C290 */  lbu        $v0, 0x10B($a2)
    /* 5B034 8006A834 20000324 */  addiu      $v1, $zero, 0x20
    /* 5B038 8006A838 ED00C3A0 */  sb         $v1, 0xED($a2)
    /* 5B03C 8006A83C 0801C3A0 */  sb         $v1, 0x108($a2)
    /* 5B040 8006A840 0901C3A0 */  sb         $v1, 0x109($a2)
    /* 5B044 8006A844 0A01C3A0 */  sb         $v1, 0x10A($a2)
    /* 5B048 8006A848 5001C38C */  lw         $v1, 0x150($a2)
    /* 5B04C 8006A84C 0800C724 */  addiu      $a3, $a2, 0x8
    /* 5B050 8006A850 EC00C0A0 */  sb         $zero, 0xEC($a2)
    /* 5B054 8006A854 EE00C0A0 */  sb         $zero, 0xEE($a2)
    /* 5B058 8006A858 EF00C0A0 */  sb         $zero, 0xEF($a2)
    /* 5B05C 8006A85C F000C0A0 */  sb         $zero, 0xF0($a2)
    /* 5B060 8006A860 F100C0A0 */  sb         $zero, 0xF1($a2)
    /* 5B064 8006A864 F400C0A0 */  sb         $zero, 0xF4($a2)
    /* 5B068 8006A868 F200C0A0 */  sb         $zero, 0xF2($a2)
    /* 5B06C 8006A86C F400C0A0 */  sb         $zero, 0xF4($a2)
    /* 5B070 8006A870 0C01C0A4 */  sh         $zero, 0x10C($a2)
    /* 5B074 8006A874 0E01C0A4 */  sh         $zero, 0x10E($a2)
    /* 5B078 8006A878 1801C4AC */  sw         $a0, 0x118($a2)
    /* 5B07C 8006A87C 1C01C0AC */  sw         $zero, 0x11C($a2)
    /* 5B080 8006A880 2001C0AC */  sw         $zero, 0x120($a2)
    /* 5B084 8006A884 2401C0AC */  sw         $zero, 0x124($a2)
    /* 5B088 8006A888 02004234 */  ori        $v0, $v0, 0x2
    /* 5B08C 8006A88C 0B01C2A0 */  sb         $v0, 0x10B($a2)
    /* 5B090 8006A890 00146224 */  addiu      $v0, $v1, 0x1400
    /* 5B094 8006A894 2801C3AC */  sw         $v1, 0x128($a2)
    /* 5B098 8006A898 00286324 */  addiu      $v1, $v1, 0x2800
    /* 5B09C 8006A89C 2C01C2AC */  sw         $v0, 0x12C($a2)
    /* 5B0A0 8006A8A0 3001C3AC */  sw         $v1, 0x130($a2)
  .L8006A8A4:
    /* 5B0A4 8006A8A4 3401E0AC */  sw         $zero, 0x134($a3)
    /* 5B0A8 8006A8A8 FFFFA524 */  addiu      $a1, $a1, -0x1
    /* 5B0AC 8006A8AC FDFFA104 */  bgez       $a1, .L8006A8A4
    /* 5B0B0 8006A8B0 FCFFE724 */   addiu     $a3, $a3, -0x4
    /* 5B0B4 8006A8B4 01000524 */  addiu      $a1, $zero, 0x1
    /* 5B0B8 8006A8B8 0400C224 */  addiu      $v0, $a2, 0x4
  .L8006A8BC:
    /* 5B0BC 8006A8BC 400140AC */  sw         $zero, 0x140($v0)
    /* 5B0C0 8006A8C0 FFFFA524 */  addiu      $a1, $a1, -0x1
    /* 5B0C4 8006A8C4 FDFFA104 */  bgez       $a1, .L8006A8BC
    /* 5B0C8 8006A8C8 FCFF4224 */   addiu     $v0, $v0, -0x4
    /* 5B0CC 8006A8CC 0800E003 */  jr         $ra
    /* 5B0D0 8006A8D0 4801C0AC */   sw        $zero, 0x148($a2)
endlabel Akao_ClearVoiceBank
