.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.4 */

nonmatching Akao_SetVoicePitch, 0x1DC

glabel Akao_SetVoicePitch
    /* 79F84 80089784 0A80083C */  lui        $t0, %hi(g_AkaoCurTrack)
    /* 79F88 80089788 C8D2088D */  lw         $t0, %lo(g_AkaoCurTrack)($t0)
    /* 79F8C 8008978C 0C80033C */  lui        $v1, %hi(D_800BCD50)
    /* 79F90 80089790 50CD638C */  lw         $v1, %lo(D_800BCD50)($v1)
    /* 79F94 80089794 0C80043C */  lui        $a0, %hi(D_800BCD60)
    /* 79F98 80089798 60CD848C */  lw         $a0, %lo(D_800BCD60)($a0)
    /* 79F9C 8008979C D8FFBD27 */  addiu      $sp, $sp, -0x28
    /* 79FA0 800897A0 2400BFAF */  sw         $ra, 0x24($sp)
    /* 79FA4 800897A4 2000B2AF */  sw         $s2, 0x20($sp)
    /* 79FA8 800897A8 1C00B1AF */  sw         $s1, 0x1C($sp)
    /* 79FAC 800897AC 1800B0AF */  sw         $s0, 0x18($sp)
    /* 79FB0 800897B0 1000A0AF */  sw         $zero, 0x10($sp)
    /* 79FB4 800897B4 6C00058D */  lw         $a1, 0x6C($t0)
    /* 79FB8 800897B8 8000028D */  lw         $v0, 0x80($t0)
    /* 79FBC 800897BC 25186400 */  or         $v1, $v1, $a0
    /* 79FC0 800897C0 2488A200 */  and        $s1, $a1, $v0
    /* 79FC4 800897C4 7000028D */  lw         $v0, 0x70($t0)
    /* 79FC8 800897C8 00000000 */  nop
    /* 79FCC 800897CC 24102202 */  and        $v0, $s1, $v0
    /* 79FD0 800897D0 19004010 */  beqz       $v0, .L80089838
    /* 79FD4 800897D4 27900300 */   nor       $s2, $zero, $v1
    /* 79FD8 800897D8 0C80043C */  lui        $a0, %hi(D_800BA560)
    /* 79FDC 800897DC 60A58424 */  addiu      $a0, $a0, %lo(D_800BA560)
    /* 79FE0 800897E0 1000A527 */  addiu      $a1, $sp, 0x10
    /* 79FE4 800897E4 21384002 */  addu       $a3, $s2, $zero
    /* 79FE8 800897E8 7000068D */  lw         $a2, 0x70($t0)
    /* 79FEC 800897EC 68000225 */  addiu      $v0, $t0, 0x68
    /* 79FF0 800897F0 0A80013C */  lui        $at, %hi(g_AkaoCurTrack)
    /* 79FF4 800897F4 C8D222AC */  sw         $v0, %lo(g_AkaoCurTrack)($at)
    /* 79FF8 800897F8 C925020C */  jal        Spu_VoiceMaskCompose
    /* 79FFC 800897FC 24302602 */   and       $a2, $s1, $a2
    /* 7A000 80089800 0A80043C */  lui        $a0, %hi(g_AkaoCurTrack)
    /* 7A004 80089804 C8D2848C */  lw         $a0, %lo(g_AkaoCurTrack)($a0)
    /* 7A008 80089808 00000000 */  nop
    /* 7A00C 8008980C 0800828C */  lw         $v0, 0x8($a0)
    /* 7A010 80089810 98FF8324 */  addiu      $v1, $a0, -0x68
    /* 7A014 80089814 0A80013C */  lui        $at, %hi(g_AkaoCurTrack)
    /* 7A018 80089818 C8D223AC */  sw         $v1, %lo(g_AkaoCurTrack)($at)
    /* 7A01C 8008981C 27100200 */  nor        $v0, $zero, $v0
    /* 7A020 80089820 24882202 */  and        $s1, $s1, $v0
    /* 7A024 80089824 0800828C */  lw         $v0, 0x8($a0)
    /* 7A028 80089828 1800838C */  lw         $v1, 0x18($a0)
    /* 7A02C 8008982C 27100200 */  nor        $v0, $zero, $v0
    /* 7A030 80089830 24186200 */  and        $v1, $v1, $v0
    /* 7A034 80089834 180083AC */  sw         $v1, 0x18($a0)
  .L80089838:
    /* 7A038 80089838 0A80023C */  lui        $v0, %hi(g_AkaoCurTrack)
    /* 7A03C 8008983C C8D2428C */  lw         $v0, %lo(g_AkaoCurTrack)($v0)
    /* 7A040 80089840 00000000 */  nop
    /* 7A044 80089844 0400448C */  lw         $a0, 0x4($v0)
    /* 7A048 80089848 1800438C */  lw         $v1, 0x18($v0)
    /* 7A04C 8008984C 0800428C */  lw         $v0, 0x8($v0)
    /* 7A050 80089850 24808300 */  and        $s0, $a0, $v1
    /* 7A054 80089854 24300202 */  and        $a2, $s0, $v0
    /* 7A058 80089858 1100C010 */  beqz       $a2, .L800898A0
    /* 7A05C 8008985C 1000A527 */   addiu     $a1, $sp, 0x10
    /* 7A060 80089860 0C80043C */  lui        $a0, %hi(D_800B8AC0)
    /* 7A064 80089864 C08A8424 */  addiu      $a0, $a0, %lo(D_800B8AC0)
    /* 7A068 80089868 C925020C */  jal        Spu_VoiceMaskCompose
    /* 7A06C 8008986C 21384002 */   addu      $a3, $s2, $zero
    /* 7A070 80089870 0A80043C */  lui        $a0, %hi(g_AkaoCurTrack)
    /* 7A074 80089874 C8D2848C */  lw         $a0, %lo(g_AkaoCurTrack)($a0)
    /* 7A078 80089878 00000000 */  nop
    /* 7A07C 8008987C 0800828C */  lw         $v0, 0x8($a0)
    /* 7A080 80089880 00000000 */  nop
    /* 7A084 80089884 27100200 */  nor        $v0, $zero, $v0
    /* 7A088 80089888 24800202 */  and        $s0, $s0, $v0
    /* 7A08C 8008988C 0800828C */  lw         $v0, 0x8($a0)
    /* 7A090 80089890 1800838C */  lw         $v1, 0x18($a0)
    /* 7A094 80089894 27100200 */  nor        $v0, $zero, $v0
    /* 7A098 80089898 24186200 */  and        $v1, $v1, $v0
    /* 7A09C 8008989C 180083AC */  sw         $v1, 0x18($a0)
  .L800898A0:
    /* 7A0A0 800898A0 13002012 */  beqz       $s1, .L800898F0
    /* 7A0A4 800898A4 1000A527 */   addiu     $a1, $sp, 0x10
    /* 7A0A8 800898A8 0C80043C */  lui        $a0, %hi(D_800BA560)
    /* 7A0AC 800898AC 60A58424 */  addiu      $a0, $a0, %lo(D_800BA560)
    /* 7A0B0 800898B0 21302002 */  addu       $a2, $s1, $zero
    /* 7A0B4 800898B4 0A80023C */  lui        $v0, %hi(g_AkaoCurTrack)
    /* 7A0B8 800898B8 C8D2428C */  lw         $v0, %lo(g_AkaoCurTrack)($v0)
    /* 7A0BC 800898BC 00000000 */  nop
    /* 7A0C0 800898C0 68004224 */  addiu      $v0, $v0, 0x68
    /* 7A0C4 800898C4 0A80013C */  lui        $at, %hi(g_AkaoCurTrack)
    /* 7A0C8 800898C8 C8D222AC */  sw         $v0, %lo(g_AkaoCurTrack)($at)
    /* 7A0CC 800898CC C925020C */  jal        Spu_VoiceMaskCompose
    /* 7A0D0 800898D0 21384002 */   addu      $a3, $s2, $zero
    /* 7A0D4 800898D4 0A80023C */  lui        $v0, %hi(g_AkaoCurTrack)
    /* 7A0D8 800898D8 C8D2428C */  lw         $v0, %lo(g_AkaoCurTrack)($v0)
    /* 7A0DC 800898DC 00000000 */  nop
    /* 7A0E0 800898E0 180040AC */  sw         $zero, 0x18($v0)
    /* 7A0E4 800898E4 98FF4224 */  addiu      $v0, $v0, -0x68
    /* 7A0E8 800898E8 0A80013C */  lui        $at, %hi(g_AkaoCurTrack)
    /* 7A0EC 800898EC C8D222AC */  sw         $v0, %lo(g_AkaoCurTrack)($at)
  .L800898F0:
    /* 7A0F0 800898F0 0A000012 */  beqz       $s0, .L8008991C
    /* 7A0F4 800898F4 1000A527 */   addiu     $a1, $sp, 0x10
    /* 7A0F8 800898F8 0C80043C */  lui        $a0, %hi(D_800B8AC0)
    /* 7A0FC 800898FC C08A8424 */  addiu      $a0, $a0, %lo(D_800B8AC0)
    /* 7A100 80089900 21300002 */  addu       $a2, $s0, $zero
    /* 7A104 80089904 C925020C */  jal        Spu_VoiceMaskCompose
    /* 7A108 80089908 21384002 */   addu      $a3, $s2, $zero
    /* 7A10C 8008990C 0A80023C */  lui        $v0, %hi(g_AkaoCurTrack)
    /* 7A110 80089910 C8D2428C */  lw         $v0, %lo(g_AkaoCurTrack)($v0)
    /* 7A114 80089914 00000000 */  nop
    /* 7A118 80089918 180040AC */  sw         $zero, 0x18($v0)
  .L8008991C:
    /* 7A11C 8008991C 1000A38F */  lw         $v1, 0x10($sp)
    /* 7A120 80089920 0C80023C */  lui        $v0, %hi(D_800BCD5C)
    /* 7A124 80089924 5CCD428C */  lw         $v0, %lo(D_800BCD5C)($v0)
    /* 7A128 80089928 0C80013C */  lui        $at, %hi(D_800BCD5C)
    /* 7A12C 8008992C 5CCD20AC */  sw         $zero, %lo(D_800BCD5C)($at)
    /* 7A130 80089930 25206200 */  or         $a0, $v1, $v0
    /* 7A134 80089934 03008010 */  beqz       $a0, .L80089944
    /* 7A138 80089938 1000A4AF */   sw        $a0, 0x10($sp)
    /* 7A13C 8008993C CA1D020C */  jal        Spu_WriteKeyOff
    /* 7A140 80089940 00000000 */   nop
  .L80089944:
    /* 7A144 80089944 2400BF8F */  lw         $ra, 0x24($sp)
    /* 7A148 80089948 2000B28F */  lw         $s2, 0x20($sp)
    /* 7A14C 8008994C 1C00B18F */  lw         $s1, 0x1C($sp)
    /* 7A150 80089950 1800B08F */  lw         $s0, 0x18($sp)
    /* 7A154 80089954 2800BD27 */  addiu      $sp, $sp, 0x28
    /* 7A158 80089958 0800E003 */  jr         $ra
    /* 7A15C 8008995C 00000000 */   nop
endlabel Akao_SetVoicePitch
