.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.4 */

nonmatching Battle_Init, 0x13C

glabel Battle_Init
    /* 11718 80020F18 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 1171C 80020F1C 1000BFAF */  sw         $ra, 0x10($sp)
    /* 11720 80020F20 19C0010C */  jal        Pm_StopAll
    /* 11724 80020F24 00000000 */   nop
    /* 11728 80020F28 21200000 */  addu       $a0, $zero, $zero
    /* 1172C 80020F2C 0C80053C */  lui        $a1, %hi(D_800BE830)
    /* 11730 80020F30 30E8A524 */  addiu      $a1, $a1, %lo(D_800BE830)
    /* 11734 80020F34 FFFF0224 */  addiu      $v0, $zero, -0x1
    /* 11738 80020F38 900482AF */  sw         $v0, %gp_rel(D_8009D200)($gp)
    /* 1173C 80020F3C 0A80013C */  lui        $at, %hi(D_8009D2FC)
    /* 11740 80020F40 FCD222AC */  sw         $v0, %lo(D_8009D2FC)($at)
    /* 11744 80020F44 E80482AF */  sw         $v0, %gp_rel(D_8009D258)($gp)
    /* 11748 80020F48 980482AF */  sw         $v0, %gp_rel(D_8009D208)($gp)
    /* 1174C 80020F4C FF008330 */  andi       $v1, $a0, 0xFF
  .L80020F50:
    /* 11750 80020F50 01008424 */  addiu      $a0, $a0, 0x1
    /* 11754 80020F54 C0180300 */  sll        $v1, $v1, 3
    /* 11758 80020F58 21106500 */  addu       $v0, $v1, $a1
    /* 1175C 80020F5C 0C80013C */  lui        $at, %hi(D_800BE830)
    /* 11760 80020F60 21082300 */  addu       $at, $at, $v1
    /* 11764 80020F64 30E820AC */  sw         $zero, %lo(D_800BE830)($at)
    /* 11768 80020F68 060040A4 */  sh         $zero, 0x6($v0)
    /* 1176C 80020F6C FF008230 */  andi       $v0, $a0, 0xFF
    /* 11770 80020F70 2D00422C */  sltiu      $v0, $v0, 0x2D
    /* 11774 80020F74 0C80013C */  lui        $at, %hi(D_800BE834)
    /* 11778 80020F78 21082300 */  addu       $at, $at, $v1
    /* 1177C 80020F7C 34E820A4 */  sh         $zero, %lo(D_800BE834)($at)
    /* 11780 80020F80 F3FF4014 */  bnez       $v0, .L80020F50
    /* 11784 80020F84 FF008330 */   andi      $v1, $a0, 0xFF
    /* 11788 80020F88 0A80043C */  lui        $a0, %hi(g_ActiveActor)
    /* 1178C 80020F8C 78D2848C */  lw         $a0, %lo(g_ActiveActor)($a0)
    /* 11790 80020F90 00000000 */  nop
    /* 11794 80020F94 6800828C */  lw         $v0, 0x68($a0)
    /* 11798 80020F98 D40080A3 */  sb         $zero, %gp_rel(D_8009CE44)($gp)
    /* 1179C 80020F9C D00080A3 */  sb         $zero, %gp_rel(D_8009CE40)($gp)
    /* 117A0 80020FA0 240580A3 */  sb         $zero, %gp_rel(D_8009D294)($gp)
    /* 117A4 80020FA4 1000428C */  lw         $v0, 0x10($v0)
    /* 117A8 80020FA8 6800838C */  lw         $v1, 0x68($a0)
    /* 117AC 80020FAC 02110200 */  srl        $v0, $v0, 4
    /* 117B0 80020FB0 03004230 */  andi       $v0, $v0, 0x3
    /* 117B4 80020FB4 680582A3 */  sb         $v0, %gp_rel(D_8009D2D8)($gp)
    /* 117B8 80020FB8 1000628C */  lw         $v0, 0x10($v1)
    /* 117BC 80020FBC 6800838C */  lw         $v1, 0x68($a0)
    /* 117C0 80020FC0 0F004230 */  andi       $v0, $v0, 0xF
    /* 117C4 80020FC4 6C0482A3 */  sb         $v0, %gp_rel(D_8009D1DC)($gp)
    /* 117C8 80020FC8 14006290 */  lbu        $v0, 0x14($v1)
    /* 117CC 80020FCC 00000000 */  nop
    /* 117D0 80020FD0 C80082A3 */  sb         $v0, %gp_rel(D_8009CE38)($gp)
    /* 117D4 80020FD4 6800828C */  lw         $v0, 0x68($a0)
    /* 117D8 80020FD8 00000000 */  nop
    /* 117DC 80020FDC 15004290 */  lbu        $v0, 0x15($v0)
    /* 117E0 80020FE0 00000000 */  nop
    /* 117E4 80020FE4 C90082A3 */  sb         $v0, %gp_rel(D_8009CE39)($gp)
    /* 117E8 80020FE8 6800828C */  lw         $v0, 0x68($a0)
    /* 117EC 80020FEC 00000000 */  nop
    /* 117F0 80020FF0 16004290 */  lbu        $v0, 0x16($v0)
    /* 117F4 80020FF4 00000000 */  nop
    /* 117F8 80020FF8 CA0082A3 */  sb         $v0, %gp_rel(D_8009CE3A)($gp)
    /* 117FC 80020FFC 6800828C */  lw         $v0, 0x68($a0)
    /* 11800 80021000 00000000 */  nop
    /* 11804 80021004 17004290 */  lbu        $v0, 0x17($v0)
    /* 11808 80021008 00000000 */  nop
    /* 1180C 8002100C CB0082A3 */  sb         $v0, %gp_rel(D_8009CE3B)($gp)
    /* 11810 80021010 3ADD000C */  jal        Tbl_ResetAll
    /* 11814 80021014 00000000 */   nop
    /* 11818 80021018 0A80023C */  lui        $v0, %hi(D_8009D1AC)
    /* 1181C 8002101C ACD1428C */  lw         $v0, %lo(D_8009D1AC)($v0)
    /* 11820 80021020 FFFC0324 */  addiu      $v1, $zero, -0x301
    /* 11824 80021024 0A80013C */  lui        $at, %hi(D_8009D1CE)
    /* 11828 80021028 CED120A0 */  sb         $zero, %lo(D_8009D1CE)($at)
    /* 1182C 8002102C 24104300 */  and        $v0, $v0, $v1
    /* 11830 80021030 0A80013C */  lui        $at, %hi(D_8009D1AC)
    /* 11834 80021034 ACD122AC */  sw         $v0, %lo(D_8009D1AC)($at)
    /* 11838 80021038 F49B000C */  jal        Battle_InitFadeVars
    /* 1183C 8002103C 00000000 */   nop
    /* 11840 80021040 F00080A3 */  sb         $zero, %gp_rel(D_8009CE60)($gp)
    /* 11844 80021044 1000BF8F */  lw         $ra, 0x10($sp)
    /* 11848 80021048 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 1184C 8002104C 0800E003 */  jr         $ra
    /* 11850 80021050 00000000 */   nop
endlabel Battle_Init
