.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.4 */

nonmatching Battle_ApplyPlayerHit, 0x184

glabel Battle_ApplyPlayerHit
    /* 12A10 80022210 0A80023C */  lui        $v0, %hi(g_ActiveActor)
    /* 12A14 80022214 78D2428C */  lw         $v0, %lo(g_ActiveActor)($v0)
    /* 12A18 80022218 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 12A1C 8002221C 1C00BFAF */  sw         $ra, 0x1C($sp)
    /* 12A20 80022220 1800B0AF */  sw         $s0, 0x18($sp)
    /* 12A24 80022224 4C00428C */  lw         $v0, 0x4C($v0)
    /* 12A28 80022228 2000103C */  lui        $s0, (0x200000 >> 16)
    /* 12A2C 8002222C 24105000 */  and        $v0, $v0, $s0
    /* 12A30 80022230 1A004010 */  beqz       $v0, .L8002229C
    /* 12A34 80022234 00000000 */   nop
    /* 12A38 80022238 0A80043C */  lui        $a0, %hi(g_PlayerEntity)
    /* 12A3C 8002223C 54D2848C */  lw         $a0, %lo(g_PlayerEntity)($a0)
    /* 12A40 80022240 A069000C */  jal        Entity_SetActionMode
    /* 12A44 80022244 0E000524 */   addiu     $a1, $zero, 0xE
    /* 12A48 80022248 0A80023C */  lui        $v0, %hi(g_PlayerEntity)
    /* 12A4C 8002224C 54D2428C */  lw         $v0, %lo(g_PlayerEntity)($v0)
    /* 12A50 80022250 B3040424 */  addiu      $a0, $zero, 0x4B3
    /* 12A54 80022254 2A004684 */  lh         $a2, 0x2A($v0)
    /* 12A58 80022258 2E004784 */  lh         $a3, 0x2E($v0)
    /* 12A5C 8002225C 32004284 */  lh         $v0, 0x32($v0)
    /* 12A60 80022260 21280000 */  addu       $a1, $zero, $zero
    /* 12A64 80022264 A0B7010C */  jal        Asset_Find08Alt
    /* 12A68 80022268 1000A2AF */   sw        $v0, 0x10($sp)
    /* 12A6C 8002226C DFFF053C */  lui        $a1, (0xFFDFFFFF >> 16)
    /* 12A70 80022270 FFFFA534 */  ori        $a1, $a1, (0xFFDFFFFF & 0xFFFF)
    /* 12A74 80022274 0A80043C */  lui        $a0, %hi(g_ActiveActor)
    /* 12A78 80022278 78D2848C */  lw         $a0, %lo(g_ActiveActor)($a0)
    /* 12A7C 8002227C 0A80023C */  lui        $v0, %hi(g_GameStateFlags)
    /* 12A80 80022280 A0D1428C */  lw         $v0, %lo(g_GameStateFlags)($v0)
    /* 12A84 80022284 4C00838C */  lw         $v1, 0x4C($a0)
    /* 12A88 80022288 00014234 */  ori        $v0, $v0, 0x100
    /* 12A8C 8002228C 0A80013C */  lui        $at, %hi(g_GameStateFlags)
    /* 12A90 80022290 A0D122AC */  sw         $v0, %lo(g_GameStateFlags)($at)
    /* 12A94 80022294 24186500 */  and        $v1, $v1, $a1
    /* 12A98 80022298 4C0083AC */  sw         $v1, 0x4C($a0)
  .L8002229C:
    /* 12A9C 8002229C 0A80043C */  lui        $a0, %hi(g_PlayerEntity)
    /* 12AA0 800222A0 54D2848C */  lw         $a0, %lo(g_PlayerEntity)($a0)
    /* 12AA4 800222A4 00000000 */  nop
    /* 12AA8 800222A8 0F008390 */  lbu        $v1, 0xF($a0)
    /* 12AAC 800222AC 1A008294 */  lhu        $v0, 0x1A($a0)
    /* 12AB0 800222B0 00000000 */  nop
    /* 12AB4 800222B4 32006214 */  bne        $v1, $v0, .L80022380
    /* 12AB8 800222B8 00000000 */   nop
    /* 12ABC 800222BC 0A80023C */  lui        $v0, %hi(g_ActiveActor)
    /* 12AC0 800222C0 78D2428C */  lw         $v0, %lo(g_ActiveActor)($v0)
    /* 12AC4 800222C4 00000000 */  nop
    /* 12AC8 800222C8 12004590 */  lbu        $a1, 0x12($v0)
    /* 12ACC 800222CC A069000C */  jal        Entity_SetActionMode
    /* 12AD0 800222D0 00000000 */   nop
    /* 12AD4 800222D4 0A80043C */  lui        $a0, %hi(g_ActiveActor)
    /* 12AD8 800222D8 78D2848C */  lw         $a0, %lo(g_ActiveActor)($a0)
    /* 12ADC 800222DC 64048393 */  lbu        $v1, %gp_rel(D_8009D1D4)($gp)
    /* 12AE0 800222E0 4C00828C */  lw         $v0, 0x4C($a0)
    /* 12AE4 800222E4 C0180300 */  sll        $v1, $v1, 3
    /* 12AE8 800222E8 25105000 */  or         $v0, $v0, $s0
    /* 12AEC 800222EC 4C0082AC */  sw         $v0, 0x4C($a0)
    /* 12AF0 800222F0 0C80013C */  lui        $at, %hi(D_800BE834)
    /* 12AF4 800222F4 21082300 */  addu       $at, $at, $v1
    /* 12AF8 800222F8 34E82484 */  lh         $a0, %lo(D_800BE834)($at)
    /* 12AFC 800222FC 858F000C */  jal        Battle_ApplyDamage
    /* 12B00 80022300 FDFF8424 */   addiu     $a0, $a0, -0x3
    /* 12B04 80022304 0A80053C */  lui        $a1, %hi(g_PlayerEntity)
    /* 12B08 80022308 54D2A58C */  lw         $a1, %lo(g_PlayerEntity)($a1)
    /* 12B0C 8002230C E7BC010C */  jal        Scene_LoadRoomAssets
    /* 12B10 80022310 55000424 */   addiu     $a0, $zero, 0x55
    /* 12B14 80022314 64048393 */  lbu        $v1, %gp_rel(D_8009D1D4)($gp)
    /* 12B18 80022318 00000000 */  nop
    /* 12B1C 8002231C 01006324 */  addiu      $v1, $v1, 0x1
    /* 12B20 80022320 FF006230 */  andi       $v0, $v1, 0xFF
    /* 12B24 80022324 C0100200 */  sll        $v0, $v0, 3
    /* 12B28 80022328 0C80013C */  lui        $at, %hi(D_800BE834)
    /* 12B2C 8002232C 21082200 */  addu       $at, $at, $v0
    /* 12B30 80022330 34E82294 */  lhu        $v0, %lo(D_800BE834)($at)
    /* 12B34 80022334 640483A3 */  sb         $v1, %gp_rel(D_8009D1D4)($gp)
    /* 12B38 80022338 FDFF4224 */  addiu      $v0, $v0, -0x3
    /* 12B3C 8002233C 9401422C */  sltiu      $v0, $v0, 0x194
    /* 12B40 80022340 09004010 */  beqz       $v0, .L80022368
    /* 12B44 80022344 00000000 */   nop
    /* 12B48 80022348 0A80023C */  lui        $v0, %hi(g_PlayerEntity)
    /* 12B4C 8002234C 54D2428C */  lw         $v0, %lo(g_PlayerEntity)($v0)
    /* 12B50 80022350 00000000 */  nop
    /* 12B54 80022354 0E004290 */  lbu        $v0, 0xE($v0)
    /* 12B58 80022358 00000000 */  nop
    /* 12B5C 8002235C 0400422C */  sltiu      $v0, $v0, 0x4
    /* 12B60 80022360 07004010 */  beqz       $v0, .L80022380
    /* 12B64 80022364 00000000 */   nop
  .L80022368:
    /* 12B68 80022368 0A80023C */  lui        $v0, %hi(g_GameStateFlags)
    /* 12B6C 8002236C A0D1428C */  lw         $v0, %lo(g_GameStateFlags)($v0)
    /* 12B70 80022370 FFFE0324 */  addiu      $v1, $zero, -0x101
    /* 12B74 80022374 24104300 */  and        $v0, $v0, $v1
    /* 12B78 80022378 0A80013C */  lui        $at, %hi(g_GameStateFlags)
    /* 12B7C 8002237C A0D122AC */  sw         $v0, %lo(g_GameStateFlags)($at)
  .L80022380:
    /* 12B80 80022380 1C00BF8F */  lw         $ra, 0x1C($sp)
    /* 12B84 80022384 1800B08F */  lw         $s0, 0x18($sp)
    /* 12B88 80022388 2000BD27 */  addiu      $sp, $sp, 0x20
    /* 12B8C 8002238C 0800E003 */  jr         $ra
    /* 12B90 80022390 00000000 */   nop
endlabel Battle_ApplyPlayerHit
