.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.4 */

nonmatching Battle_StepLevelUp, 0x1B4

glabel Battle_StepLevelUp
    /* 1B8E8 8002B0E8 04018593 */  lbu        $a1, %gp_rel(D_8009CE74)($gp)
    /* 1B8EC 8002B0EC E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 1B8F0 8002B0F0 1000B0AF */  sw         $s0, 0x10($sp)
    /* 1B8F4 8002B0F4 01001024 */  addiu      $s0, $zero, 0x1
    /* 1B8F8 8002B0F8 FF00A330 */  andi       $v1, $a1, 0xFF
    /* 1B8FC 8002B0FC 2B007010 */  beq        $v1, $s0, .L8002B1AC
    /* 1B900 8002B100 1400BFAF */   sw        $ra, 0x14($sp)
    /* 1B904 8002B104 02006228 */  slti       $v0, $v1, 0x2
    /* 1B908 8002B108 05004010 */  beqz       $v0, .L8002B120
    /* 1B90C 8002B10C 00000000 */   nop
    /* 1B910 8002B110 0A006010 */  beqz       $v1, .L8002B13C
    /* 1B914 8002B114 0A000224 */   addiu     $v0, $zero, 0xA
    /* 1B918 8002B118 A2AC0008 */  j          .L8002B288
    /* 1B91C 8002B11C 00000000 */   nop
  .L8002B120:
    /* 1B920 8002B120 02000224 */  addiu      $v0, $zero, 0x2
    /* 1B924 8002B124 2D006210 */  beq        $v1, $v0, .L8002B1DC
    /* 1B928 8002B128 03000224 */   addiu     $v0, $zero, 0x3
    /* 1B92C 8002B12C 47006210 */  beq        $v1, $v0, .L8002B24C
    /* 1B930 8002B130 00000000 */   nop
    /* 1B934 8002B134 A2AC0008 */  j          .L8002B288
    /* 1B938 8002B138 00000000 */   nop
  .L8002B13C:
    /* 1B93C 8002B13C 0A80043C */  lui        $a0, %hi(g_PlayerEntity)
    /* 1B940 8002B140 54D2848C */  lw         $a0, %lo(g_PlayerEntity)($a0)
    /* 1B944 8002B144 00000000 */  nop
    /* 1B948 8002B148 16008394 */  lhu        $v1, 0x16($a0)
    /* 1B94C 8002B14C 00000000 */  nop
    /* 1B950 8002B150 07006210 */  beq        $v1, $v0, .L8002B170
    /* 1B954 8002B154 00000000 */   nop
    /* 1B958 8002B158 0A80023C */  lui        $v0, %hi(g_GameStateFlags)
    /* 1B95C 8002B15C A0D1428C */  lw         $v0, %lo(g_GameStateFlags)($v0)
    /* 1B960 8002B160 00000000 */  nop
    /* 1B964 8002B164 00084230 */  andi       $v0, $v0, 0x800
    /* 1B968 8002B168 47004010 */  beqz       $v0, .L8002B288
    /* 1B96C 8002B16C 00000000 */   nop
  .L8002B170:
    /* 1B970 8002B170 9800828C */  lw         $v0, 0x98($a0)
    /* 1B974 8002B174 00000000 */  nop
    /* 1B978 8002B178 00014234 */  ori        $v0, $v0, 0x100
    /* 1B97C 8002B17C FDC0010C */  jal        Pm_StopAllBoth
    /* 1B980 8002B180 980082AC */   sw        $v0, 0x98($a0)
    /* 1B984 8002B184 9405848F */  lw         $a0, %gp_rel(D_8009D304)($gp)
    /* 1B988 8002B188 AC048597 */  lhu        $a1, %gp_rel(D_8009D21C)($gp)
    /* 1B98C 8002B18C 0A80063C */  lui        $a2, %hi(D_800A7FF0)
    /* 1B990 8002B190 F07FC624 */  addiu      $a2, $a2, %lo(D_800A7FF0)
    /* 1B994 8002B194 C32D010C */  jal        Aya_SetTotalExp
    /* 1B998 8002B198 00000000 */   nop
    /* 1B99C 8002B19C 2F9F010C */  jal        Render_BeginSceneLoad
    /* 1B9A0 8002B1A0 00000000 */   nop
    /* 1B9A4 8002B1A4 8DAC0008 */  j          .L8002B234
    /* 1B9A8 8002B1A8 00000000 */   nop
  .L8002B1AC:
    /* 1B9AC 8002B1AC 34058387 */  lh         $v1, %gp_rel(D_8009D2A4)($gp)
    /* 1B9B0 8002B1B0 E8030224 */  addiu      $v0, $zero, 0x3E8
    /* 1B9B4 8002B1B4 34006214 */  bne        $v1, $v0, .L8002B288
    /* 1B9B8 8002B1B8 0100A224 */   addiu     $v0, $a1, 0x1
    /* 1B9BC 8002B1BC 0A80043C */  lui        $a0, %hi(g_PlayerEntity)
    /* 1B9C0 8002B1C0 54D2848C */  lw         $a0, %lo(g_PlayerEntity)($a0)
    /* 1B9C4 8002B1C4 040182A3 */  sb         $v0, %gp_rel(D_8009CE74)($gp)
    /* 1B9C8 8002B1C8 9800828C */  lw         $v0, 0x98($a0)
    /* 1B9CC 8002B1CC FFFE0324 */  addiu      $v1, $zero, -0x101
    /* 1B9D0 8002B1D0 24104300 */  and        $v0, $v0, $v1
    /* 1B9D4 8002B1D4 A2AC0008 */  j          .L8002B288
    /* 1B9D8 8002B1D8 980082AC */   sw        $v0, 0x98($a0)
  .L8002B1DC:
    /* 1B9DC 8002B1DC 0A80043C */  lui        $a0, %hi(g_PlayerEntity)
    /* 1B9E0 8002B1E0 54D2848C */  lw         $a0, %lo(g_PlayerEntity)($a0)
    /* 1B9E4 8002B1E4 00000000 */  nop
    /* 1B9E8 8002B1E8 0F008390 */  lbu        $v1, 0xF($a0)
    /* 1B9EC 8002B1EC 1A008294 */  lhu        $v0, 0x1A($a0)
    /* 1B9F0 8002B1F0 00000000 */  nop
    /* 1B9F4 8002B1F4 24006214 */  bne        $v1, $v0, .L8002B288
    /* 1B9F8 8002B1F8 00000000 */   nop
    /* 1B9FC 8002B1FC 0A80033C */  lui        $v1, %hi(g_GameStateFlags)
    /* 1BA00 8002B200 A0D1638C */  lw         $v1, %lo(g_GameStateFlags)($v1)
    /* 1BA04 8002B204 00000000 */  nop
    /* 1BA08 8002B208 00186230 */  andi       $v0, $v1, 0x1800
    /* 1BA0C 8002B20C 03004014 */  bnez       $v0, .L8002B21C
    /* 1BA10 8002B210 FFE70224 */   addiu     $v0, $zero, -0x1801
    /* 1BA14 8002B214 8BAC0008 */  j          .L8002B22C
    /* 1BA18 8002B218 15000524 */   addiu     $a1, $zero, 0x15
  .L8002B21C:
    /* 1BA1C 8002B21C 24106200 */  and        $v0, $v1, $v0
    /* 1BA20 8002B220 0A80013C */  lui        $at, %hi(g_GameStateFlags)
    /* 1BA24 8002B224 A0D122AC */  sw         $v0, %lo(g_GameStateFlags)($at)
    /* 1BA28 8002B228 18000524 */  addiu      $a1, $zero, 0x18
  .L8002B22C:
    /* 1BA2C 8002B22C A069000C */  jal        Entity_SetActionMode
    /* 1BA30 8002B230 00000000 */   nop
  .L8002B234:
    /* 1BA34 8002B234 04018293 */  lbu        $v0, %gp_rel(D_8009CE74)($gp)
    /* 1BA38 8002B238 00000000 */  nop
    /* 1BA3C 8002B23C 01004224 */  addiu      $v0, $v0, 0x1
    /* 1BA40 8002B240 040182A3 */  sb         $v0, %gp_rel(D_8009CE74)($gp)
    /* 1BA44 8002B244 A2AC0008 */  j          .L8002B288
    /* 1BA48 8002B248 00000000 */   nop
  .L8002B24C:
    /* 1BA4C 8002B24C 83B5010C */  jal        CD_StepReadState
    /* 1BA50 8002B250 21200000 */   addu      $a0, $zero, $zero
    /* 1BA54 8002B254 0C005010 */  beq        $v0, $s0, .L8002B288
    /* 1BA58 8002B258 00000000 */   nop
    /* 1BA5C 8002B25C 79A5000C */  jal        Battle_SetupPlayerPalette
    /* 1BA60 8002B260 00000000 */   nop
    /* 1BA64 8002B264 FFFF053C */  lui        $a1, (0xFFFF7FFF >> 16)
    /* 1BA68 8002B268 FF7FA534 */  ori        $a1, $a1, (0xFFFF7FFF & 0xFFFF)
    /* 1BA6C 8002B26C 0B80043C */  lui        $a0, %hi(g_GameState)
    /* 1BA70 8002B270 D80C8424 */  addiu      $a0, $a0, %lo(g_GameState)
    /* 1BA74 8002B274 0000828C */  lw         $v0, 0x0($a0)
    /* 1BA78 8002B278 09000324 */  addiu      $v1, $zero, 0x9
    /* 1BA7C 8002B27C 1C0583AF */  sw         $v1, %gp_rel(D_8009D28C)($gp)
    /* 1BA80 8002B280 24104500 */  and        $v0, $v0, $a1
    /* 1BA84 8002B284 000082AC */  sw         $v0, 0x0($a0)
  .L8002B288:
    /* 1BA88 8002B288 1400BF8F */  lw         $ra, 0x14($sp)
    /* 1BA8C 8002B28C 1000B08F */  lw         $s0, 0x10($sp)
    /* 1BA90 8002B290 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 1BA94 8002B294 0800E003 */  jr         $ra
    /* 1BA98 8002B298 00000000 */   nop
endlabel Battle_StepLevelUp
