.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.4 */

nonmatching Battle_ApplyDamage, 0x43C

glabel Battle_ApplyDamage
    /* 14614 80023E14 0A80023C */  lui        $v0, %hi(g_GameStateFlags)
    /* 14618 80023E18 A0D1428C */  lw         $v0, %lo(g_GameStateFlags)($v0)
    /* 1461C 80023E1C D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* 14620 80023E20 2000B0AF */  sw         $s0, 0x20($sp)
    /* 14624 80023E24 21808000 */  addu       $s0, $a0, $zero
    /* 14628 80023E28 2400B1AF */  sw         $s1, 0x24($sp)
    /* 1462C 80023E2C FFFF1124 */  addiu      $s1, $zero, -0x1
    /* 14630 80023E30 02004230 */  andi       $v0, $v0, 0x2
    /* 14634 80023E34 10004014 */  bnez       $v0, .L80023E78
    /* 14638 80023E38 2800BFAF */   sw        $ra, 0x28($sp)
    /* 1463C 80023E3C 0A80033C */  lui        $v1, %hi(g_PlayerEntity)
    /* 14640 80023E40 54D2638C */  lw         $v1, %lo(g_PlayerEntity)($v1)
    /* 14644 80023E44 00000000 */  nop
    /* 14648 80023E48 0000628C */  lw         $v0, 0x0($v1)
    /* 1464C 80023E4C 0A80013C */  lui        $at, %hi(g_ActiveActor)
    /* 14650 80023E50 78D222AC */  sw         $v0, %lo(g_ActiveActor)($at)
    /* 14654 80023E54 0D00022A */  slti       $v0, $s0, 0xD
    /* 14658 80023E58 02004010 */  beqz       $v0, .L80023E64
    /* 1465C 80023E5C B5040424 */   addiu     $a0, $zero, 0x4B5
    /* 14660 80023E60 B4040424 */  addiu      $a0, $zero, 0x4B4
  .L80023E64:
    /* 14664 80023E64 2A006684 */  lh         $a2, 0x2A($v1)
    /* 14668 80023E68 2E006784 */  lh         $a3, 0x2E($v1)
    /* 1466C 80023E6C 32006284 */  lh         $v0, 0x32($v1)
    /* 14670 80023E70 A98F0008 */  j          .L80023EA4
    /* 14674 80023E74 01000524 */   addiu     $a1, $zero, 0x1
  .L80023E78:
    /* 14678 80023E78 0D00022A */  slti       $v0, $s0, 0xD
    /* 1467C 80023E7C 02004010 */  beqz       $v0, .L80023E88
    /* 14680 80023E80 B5040424 */   addiu     $a0, $zero, 0x4B5
    /* 14684 80023E84 B4040424 */  addiu      $a0, $zero, 0x4B4
  .L80023E88:
    /* 14688 80023E88 0A80023C */  lui        $v0, %hi(g_PlayerEntity)
    /* 1468C 80023E8C 54D2428C */  lw         $v0, %lo(g_PlayerEntity)($v0)
    /* 14690 80023E90 00000000 */  nop
    /* 14694 80023E94 2A004684 */  lh         $a2, 0x2A($v0)
    /* 14698 80023E98 2E004784 */  lh         $a3, 0x2E($v0)
    /* 1469C 80023E9C 32004284 */  lh         $v0, 0x32($v0)
    /* 146A0 80023EA0 21280000 */  addu       $a1, $zero, $zero
  .L80023EA4:
    /* 146A4 80023EA4 A0B7010C */  jal        Asset_Find08Alt
    /* 146A8 80023EA8 1000A2AF */   sw        $v0, 0x10($sp)
    /* 146AC 80023EAC FAFF0426 */  addiu      $a0, $s0, -0x6
    /* 146B0 80023EB0 0C00822C */  sltiu      $v0, $a0, 0xC
    /* 146B4 80023EB4 C8004010 */  beqz       $v0, .L800241D8
    /* 146B8 80023EB8 80100400 */   sll       $v0, $a0, 2
    /* 146BC 80023EBC 0180013C */  lui        $at, %hi(jtbl_800107A4)
    /* 146C0 80023EC0 21082200 */  addu       $at, $at, $v0
    /* 146C4 80023EC4 A407228C */  lw         $v0, %lo(jtbl_800107A4)($at)
    /* 146C8 80023EC8 00000000 */  nop
    /* 146CC 80023ECC 08004000 */  jr         $v0
    /* 146D0 80023ED0 00000000 */   nop
  jlabel .L80023ED4
    /* 146D4 80023ED4 0A80033C */  lui        $v1, %hi(g_ActiveActor)
    /* 146D8 80023ED8 78D2638C */  lw         $v1, %lo(g_ActiveActor)($v1)
    /* 146DC 80023EDC 00000000 */  nop
    /* 146E0 80023EE0 0C006294 */  lhu        $v0, 0xC($v1)
    /* 146E4 80023EE4 00000000 */  nop
    /* 146E8 80023EE8 2D004224 */  addiu      $v0, $v0, 0x2D
    /* 146EC 80023EEC 76900008 */  j          .L800241D8
    /* 146F0 80023EF0 0C0062A4 */   sh        $v0, 0xC($v1)
  jlabel .L80023EF4
    /* 146F4 80023EF4 0A80033C */  lui        $v1, %hi(g_ActiveActor)
    /* 146F8 80023EF8 78D2638C */  lw         $v1, %lo(g_ActiveActor)($v1)
    /* 146FC 80023EFC 00000000 */  nop
    /* 14700 80023F00 0C006294 */  lhu        $v0, 0xC($v1)
    /* 14704 80023F04 00000000 */  nop
    /* 14708 80023F08 5A004224 */  addiu      $v0, $v0, 0x5A
    /* 1470C 80023F0C 76900008 */  j          .L800241D8
    /* 14710 80023F10 0C0062A4 */   sh        $v0, 0xC($v1)
  jlabel .L80023F14
    /* 14714 80023F14 0A80033C */  lui        $v1, %hi(g_ActiveActor)
    /* 14718 80023F18 78D2638C */  lw         $v1, %lo(g_ActiveActor)($v1)
    /* 1471C 80023F1C 00000000 */  nop
    /* 14720 80023F20 0C006294 */  lhu        $v0, 0xC($v1)
    /* 14724 80023F24 00000000 */  nop
    /* 14728 80023F28 B4004224 */  addiu      $v0, $v0, 0xB4
    /* 1472C 80023F2C 76900008 */  j          .L800241D8
    /* 14730 80023F30 0C0062A4 */   sh        $v0, 0xC($v1)
  jlabel .L80023F34
    /* 14734 80023F34 0A80033C */  lui        $v1, %hi(g_ActiveActor)
    /* 14738 80023F38 78D2638C */  lw         $v1, %lo(g_ActiveActor)($v1)
    /* 1473C 80023F3C 00000000 */  nop
    /* 14740 80023F40 0C006294 */  lhu        $v0, 0xC($v1)
    /* 14744 80023F44 00000000 */  nop
    /* 14748 80023F48 90014224 */  addiu      $v0, $v0, 0x190
    /* 1474C 80023F4C 76900008 */  j          .L800241D8
    /* 14750 80023F50 0C0062A4 */   sh        $v0, 0xC($v1)
  jlabel .L80023F54
    /* 14754 80023F54 0A80033C */  lui        $v1, %hi(g_ActiveActor)
    /* 14758 80023F58 78D2638C */  lw         $v1, %lo(g_ActiveActor)($v1)
    /* 1475C 80023F5C 00000000 */  nop
    /* 14760 80023F60 1C006294 */  lhu        $v0, 0x1C($v1)
    /* 14764 80023F64 76900008 */  j          .L800241D8
    /* 14768 80023F68 0C0062A4 */   sh        $v0, 0xC($v1)
  jlabel .L80023F6C
    /* 1476C 80023F6C 0A80043C */  lui        $a0, %hi(g_ActiveActor)
    /* 14770 80023F70 78D2848C */  lw         $a0, %lo(g_ActiveActor)($a0)
    /* 14774 80023F74 00000000 */  nop
    /* 14778 80023F78 2800838C */  lw         $v1, 0x28($a0)
    /* 1477C 80023F7C 00000000 */  nop
    /* 14780 80023F80 02006104 */  bgez       $v1, .L80023F8C
    /* 14784 80023F84 00000000 */   nop
    /* 14788 80023F88 03006324 */  addiu      $v1, $v1, 0x3
  .L80023F8C:
    /* 1478C 80023F8C 0800828C */  lw         $v0, 0x8($a0)
    /* 14790 80023F90 83180300 */  sra        $v1, $v1, 2
    /* 14794 80023F94 21104300 */  addu       $v0, $v0, $v1
    /* 14798 80023F98 76900008 */  j          .L800241D8
    /* 1479C 80023F9C 080082AC */   sw        $v0, 0x8($a0)
  jlabel .L80023FA0
    /* 147A0 80023FA0 0A80043C */  lui        $a0, %hi(g_ActiveActor)
    /* 147A4 80023FA4 78D2848C */  lw         $a0, %lo(g_ActiveActor)($a0)
    /* 147A8 80023FA8 00000000 */  nop
    /* 147AC 80023FAC 2800828C */  lw         $v0, 0x28($a0)
    /* 147B0 80023FB0 00000000 */  nop
    /* 147B4 80023FB4 C21F0200 */  srl        $v1, $v0, 31
    /* 147B8 80023FB8 21104300 */  addu       $v0, $v0, $v1
    /* 147BC 80023FBC 0800838C */  lw         $v1, 0x8($a0)
    /* 147C0 80023FC0 43100200 */  sra        $v0, $v0, 1
    /* 147C4 80023FC4 21186200 */  addu       $v1, $v1, $v0
    /* 147C8 80023FC8 76900008 */  j          .L800241D8
    /* 147CC 80023FCC 080083AC */   sw        $v1, 0x8($a0)
  jlabel .L80023FD0
    /* 147D0 80023FD0 0A80053C */  lui        $a1, %hi(g_ActiveActor)
    /* 147D4 80023FD4 78D2A58C */  lw         $a1, %lo(g_ActiveActor)($a1)
    /* 147D8 80023FD8 00000000 */  nop
    /* 147DC 80023FDC 4C00A38C */  lw         $v1, 0x4C($a1)
    /* 147E0 80023FE0 00000000 */  nop
    /* 147E4 80023FE4 03006430 */  andi       $a0, $v1, 0x3
    /* 147E8 80023FE8 03008014 */  bnez       $a0, .L80023FF8
    /* 147EC 80023FEC 03000224 */   addiu     $v0, $zero, 0x3
    /* 147F0 80023FF0 01900008 */  j          .L80024004
    /* 147F4 80023FF4 03006234 */   ori       $v0, $v1, 0x3
  .L80023FF8:
    /* 147F8 80023FF8 03008210 */  beq        $a0, $v0, .L80024008
    /* 147FC 80023FFC FCFF0224 */   addiu     $v0, $zero, -0x4
    /* 14800 80024000 24106200 */  and        $v0, $v1, $v0
  .L80024004:
    /* 14804 80024004 4C00A2AC */  sw         $v0, 0x4C($a1)
  .L80024008:
    /* 14808 80024008 76900008 */  j          .L800241D8
    /* 1480C 8002400C 07001124 */   addiu     $s1, $zero, 0x7
  jlabel .L80024010
    /* 14810 80024010 0A80053C */  lui        $a1, %hi(g_ActiveActor)
    /* 14814 80024014 78D2A58C */  lw         $a1, %lo(g_ActiveActor)($a1)
    /* 14818 80024018 00000000 */  nop
    /* 1481C 8002401C 4C00A38C */  lw         $v1, 0x4C($a1)
    /* 14820 80024020 00000000 */  nop
    /* 14824 80024024 30006430 */  andi       $a0, $v1, 0x30
    /* 14828 80024028 03008014 */  bnez       $a0, .L80024038
    /* 1482C 8002402C 30000224 */   addiu     $v0, $zero, 0x30
    /* 14830 80024030 11900008 */  j          .L80024044
    /* 14834 80024034 30006234 */   ori       $v0, $v1, 0x30
  .L80024038:
    /* 14838 80024038 03008210 */  beq        $a0, $v0, .L80024048
    /* 1483C 8002403C CFFF0224 */   addiu     $v0, $zero, -0x31
    /* 14840 80024040 24106200 */  and        $v0, $v1, $v0
  .L80024044:
    /* 14844 80024044 4C00A2AC */  sw         $v0, 0x4C($a1)
  .L80024048:
    /* 14848 80024048 76900008 */  j          .L800241D8
    /* 1484C 8002404C 05001124 */   addiu     $s1, $zero, 0x5
  jlabel .L80024050
    /* 14850 80024050 0A80053C */  lui        $a1, %hi(g_ActiveActor)
    /* 14854 80024054 78D2A58C */  lw         $a1, %lo(g_ActiveActor)($a1)
    /* 14858 80024058 00000000 */  nop
    /* 1485C 8002405C 4C00A38C */  lw         $v1, 0x4C($a1)
    /* 14860 80024060 00000000 */  nop
    /* 14864 80024064 0C006430 */  andi       $a0, $v1, 0xC
    /* 14868 80024068 04008014 */  bnez       $a0, .L8002407C
    /* 1486C 8002406C 0C000224 */   addiu     $v0, $zero, 0xC
    /* 14870 80024070 0C006234 */  ori        $v0, $v1, 0xC
    /* 14874 80024074 29900008 */  j          .L800240A4
    /* 14878 80024078 4C00A2AC */   sw        $v0, 0x4C($a1)
  .L8002407C:
    /* 1487C 8002407C 09008210 */  beq        $a0, $v0, .L800240A4
    /* 14880 80024080 F3FF0224 */   addiu     $v0, $zero, -0xD
    /* 14884 80024084 24106200 */  and        $v0, $v1, $v0
    /* 14888 80024088 4C00A2AC */  sw         $v0, 0x4C($a1)
    /* 1488C 8002408C 0A80023C */  lui        $v0, %hi(g_FieldMoveLock)
    /* 14890 80024090 E8D2428C */  lw         $v0, %lo(g_FieldMoveLock)($v0)
    /* 14894 80024094 EFFF0324 */  addiu      $v1, $zero, -0x11
    /* 14898 80024098 24104300 */  and        $v0, $v0, $v1
    /* 1489C 8002409C 0A80013C */  lui        $at, %hi(g_FieldMoveLock)
    /* 148A0 800240A0 E8D222AC */  sw         $v0, %lo(g_FieldMoveLock)($at)
  .L800240A4:
    /* 148A4 800240A4 76900008 */  j          .L800241D8
    /* 148A8 800240A8 04001124 */   addiu     $s1, $zero, 0x4
  jlabel .L800240AC
    /* 148AC 800240AC 0A80053C */  lui        $a1, %hi(g_ActiveActor)
    /* 148B0 800240B0 78D2A58C */  lw         $a1, %lo(g_ActiveActor)($a1)
    /* 148B4 800240B4 00000000 */  nop
    /* 148B8 800240B8 4C00A38C */  lw         $v1, 0x4C($a1)
    /* 148BC 800240BC 00000000 */  nop
    /* 148C0 800240C0 C0006430 */  andi       $a0, $v1, 0xC0
    /* 148C4 800240C4 03008014 */  bnez       $a0, .L800240D4
    /* 148C8 800240C8 C0000224 */   addiu     $v0, $zero, 0xC0
    /* 148CC 800240CC 38900008 */  j          .L800240E0
    /* 148D0 800240D0 C0006234 */   ori       $v0, $v1, 0xC0
  .L800240D4:
    /* 148D4 800240D4 03008210 */  beq        $a0, $v0, .L800240E4
    /* 148D8 800240D8 3FFF0224 */   addiu     $v0, $zero, -0xC1
    /* 148DC 800240DC 24106200 */  and        $v0, $v1, $v0
  .L800240E0:
    /* 148E0 800240E0 4C00A2AC */  sw         $v0, 0x4C($a1)
  .L800240E4:
    /* 148E4 800240E4 76900008 */  j          .L800241D8
    /* 148E8 800240E8 06001124 */   addiu     $s1, $zero, 0x6
  jlabel .L800240EC
    /* 148EC 800240EC 0A80053C */  lui        $a1, %hi(g_ActiveActor)
    /* 148F0 800240F0 78D2A58C */  lw         $a1, %lo(g_ActiveActor)($a1)
    /* 148F4 800240F4 00000000 */  nop
    /* 148F8 800240F8 2C00A424 */  addiu      $a0, $a1, 0x2C
    /* 148FC 800240FC FE48010C */  jal        Aya_DeriveStats
    /* 14900 80024100 3000A524 */   addiu     $a1, $a1, 0x30
    /* 14904 80024104 0A80053C */  lui        $a1, %hi(g_ActiveActor)
    /* 14908 80024108 78D2A58C */  lw         $a1, %lo(g_ActiveActor)($a1)
    /* 1490C 8002410C 00000000 */  nop
    /* 14910 80024110 4C00A48C */  lw         $a0, 0x4C($a1)
    /* 14914 80024114 03000224 */  addiu      $v0, $zero, 0x3
    /* 14918 80024118 03008330 */  andi       $v1, $a0, 0x3
    /* 1491C 8002411C 07006210 */  beq        $v1, $v0, .L8002413C
    /* 14920 80024120 FCFF0224 */   addiu     $v0, $zero, -0x4
    /* 14924 80024124 24108200 */  and        $v0, $a0, $v0
    /* 14928 80024128 4C00A2AC */  sw         $v0, 0x4C($a1)
    /* 1492C 8002412C 0A80053C */  lui        $a1, %hi(g_ActiveActor)
    /* 14930 80024130 78D2A58C */  lw         $a1, %lo(g_ActiveActor)($a1)
    /* 14934 80024134 00000000 */  nop
    /* 14938 80024138 4C00A48C */  lw         $a0, 0x4C($a1)
  .L8002413C:
    /* 1493C 8002413C 0C000224 */  addiu      $v0, $zero, 0xC
    /* 14940 80024140 0C008330 */  andi       $v1, $a0, 0xC
    /* 14944 80024144 09006210 */  beq        $v1, $v0, .L8002416C
    /* 14948 80024148 F3FF0224 */   addiu     $v0, $zero, -0xD
    /* 1494C 8002414C 24108200 */  and        $v0, $a0, $v0
    /* 14950 80024150 4C00A2AC */  sw         $v0, 0x4C($a1)
    /* 14954 80024154 0A80023C */  lui        $v0, %hi(g_FieldMoveLock)
    /* 14958 80024158 E8D2428C */  lw         $v0, %lo(g_FieldMoveLock)($v0)
    /* 1495C 8002415C EFFF0324 */  addiu      $v1, $zero, -0x11
    /* 14960 80024160 24104300 */  and        $v0, $v0, $v1
    /* 14964 80024164 0A80013C */  lui        $at, %hi(g_FieldMoveLock)
    /* 14968 80024168 E8D222AC */  sw         $v0, %lo(g_FieldMoveLock)($at)
  .L8002416C:
    /* 1496C 8002416C 0A80053C */  lui        $a1, %hi(g_ActiveActor)
    /* 14970 80024170 78D2A58C */  lw         $a1, %lo(g_ActiveActor)($a1)
    /* 14974 80024174 00000000 */  nop
    /* 14978 80024178 4C00A48C */  lw         $a0, 0x4C($a1)
    /* 1497C 8002417C 30000224 */  addiu      $v0, $zero, 0x30
    /* 14980 80024180 30008330 */  andi       $v1, $a0, 0x30
    /* 14984 80024184 07006210 */  beq        $v1, $v0, .L800241A4
    /* 14988 80024188 CFFF0224 */   addiu     $v0, $zero, -0x31
    /* 1498C 8002418C 24108200 */  and        $v0, $a0, $v0
    /* 14990 80024190 4C00A2AC */  sw         $v0, 0x4C($a1)
    /* 14994 80024194 0A80053C */  lui        $a1, %hi(g_ActiveActor)
    /* 14998 80024198 78D2A58C */  lw         $a1, %lo(g_ActiveActor)($a1)
    /* 1499C 8002419C 00000000 */  nop
    /* 149A0 800241A0 4C00A48C */  lw         $a0, 0x4C($a1)
  .L800241A4:
    /* 149A4 800241A4 C0000224 */  addiu      $v0, $zero, 0xC0
    /* 149A8 800241A8 C0008330 */  andi       $v1, $a0, 0xC0
    /* 149AC 800241AC 03006210 */  beq        $v1, $v0, .L800241BC
    /* 149B0 800241B0 3FFF0224 */   addiu     $v0, $zero, -0xC1
    /* 149B4 800241B4 24108200 */  and        $v0, $a0, $v0
    /* 149B8 800241B8 4C00A2AC */  sw         $v0, 0x4C($a1)
  .L800241BC:
    /* 149BC 800241BC 0A80023C */  lui        $v0, %hi(g_ActiveActor)
    /* 149C0 800241C0 78D2428C */  lw         $v0, %lo(g_ActiveActor)($v0)
    /* 149C4 800241C4 00000000 */  nop
    /* 149C8 800241C8 4C00438C */  lw         $v1, 0x4C($v0)
    /* 149CC 800241CC FFEF0424 */  addiu      $a0, $zero, -0x1001
    /* 149D0 800241D0 24186400 */  and        $v1, $v1, $a0
    /* 149D4 800241D4 4C0043AC */  sw         $v1, 0x4C($v0)
  .L800241D8:
    /* 149D8 800241D8 0A80043C */  lui        $a0, %hi(g_ActiveActor)
    /* 149DC 800241DC 78D2848C */  lw         $a0, %lo(g_ActiveActor)($a0)
    /* 149E0 800241E0 00000000 */  nop
    /* 149E4 800241E4 1C008284 */  lh         $v0, 0x1C($a0)
    /* 149E8 800241E8 0C008384 */  lh         $v1, 0xC($a0)
    /* 149EC 800241EC 21284000 */  addu       $a1, $v0, $zero
    /* 149F0 800241F0 2A104300 */  slt        $v0, $v0, $v1
    /* 149F4 800241F4 02004010 */  beqz       $v0, .L80024200
    /* 149F8 800241F8 00161100 */   sll       $v0, $s1, 24
    /* 149FC 800241FC 0C0085A4 */  sh         $a1, 0xC($a0)
  .L80024200:
    /* 14A00 80024200 03160200 */  sra        $v0, $v0, 24
    /* 14A04 80024204 FFFF0324 */  addiu      $v1, $zero, -0x1
    /* 14A08 80024208 0B004310 */  beq        $v0, $v1, .L80024238
    /* 14A0C 8002420C 00000000 */   nop
    /* 14A10 80024210 0A80023C */  lui        $v0, %hi(g_GameStateFlags)
    /* 14A14 80024214 A0D1428C */  lw         $v0, %lo(g_GameStateFlags)($v0)
    /* 14A18 80024218 00000000 */  nop
    /* 14A1C 8002421C 02004230 */  andi       $v0, $v0, 0x2
    /* 14A20 80024220 05004010 */  beqz       $v0, .L80024238
    /* 14A24 80024224 21280000 */   addu      $a1, $zero, $zero
    /* 14A28 80024228 0A80043C */  lui        $a0, %hi(g_PlayerEntity)
    /* 14A2C 8002422C 54D2848C */  lw         $a0, %lo(g_PlayerEntity)($a0)
    /* 14A30 80024230 D7CC000C */  jal        Gpu_SetupSprites
    /* 14A34 80024234 FF002632 */   andi      $a2, $s1, 0xFF
  .L80024238:
    /* 14A38 80024238 2800BF8F */  lw         $ra, 0x28($sp)
    /* 14A3C 8002423C 2400B18F */  lw         $s1, 0x24($sp)
    /* 14A40 80024240 2000B08F */  lw         $s0, 0x20($sp)
    /* 14A44 80024244 3000BD27 */  addiu      $sp, $sp, 0x30
    /* 14A48 80024248 0800E003 */  jr         $ra
    /* 14A4C 8002424C 00000000 */   nop
endlabel Battle_ApplyDamage
