.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.4 */

nonmatching Battle_StartEncounter, 0x1BC

glabel Battle_StartEncounter
    /* 1A010 80029810 0A80023C */  lui        $v0, %hi(g_PlayerEntity)
    /* 1A014 80029814 54D2428C */  lw         $v0, %lo(g_PlayerEntity)($v0)
    /* 1A018 80029818 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 1A01C 8002981C 1400BFAF */  sw         $ra, 0x14($sp)
    /* 1A020 80029820 1000B0AF */  sw         $s0, 0x10($sp)
    /* 1A024 80029824 0000428C */  lw         $v0, 0x0($v0)
    /* 1A028 80029828 780480AF */  sw         $zero, %gp_rel(D_8009D1E8)($gp)
    /* 1A02C 8002982C 0A80013C */  lui        $at, %hi(D_8009D290)
    /* 1A030 80029830 90D220AC */  sw         $zero, %lo(D_8009D290)($at)
    /* 1A034 80029834 1C0580AF */  sw         $zero, %gp_rel(D_8009D28C)($gp)
    /* 1A038 80029838 0C0180A3 */  sb         $zero, %gp_rel(D_8009CE7C)($gp)
    /* 1A03C 8002983C 080180A3 */  sb         $zero, %gp_rel(D_8009CE78)($gp)
    /* 1A040 80029840 180580A3 */  sb         $zero, %gp_rel(D_8009D288)($gp)
    /* 1A044 80029844 040180A3 */  sb         $zero, %gp_rel(D_8009CE74)($gp)
    /* 1A048 80029848 080582AF */  sw         $v0, %gp_rel(g_ActiveActor)($gp)
    /* 1A04C 8002984C BF83000C */  jal        Save_ResetGlobalFlags
    /* 1A050 80029850 21808000 */   addu      $s0, $a0, $zero
    /* 1A054 80029854 21200000 */  addu       $a0, $zero, $zero
    /* 1A058 80029858 FFFF0524 */  addiu      $a1, $zero, -0x1
    /* 1A05C 8002985C 0A80013C */  lui        $at, %hi(D_8009D1AC)
    /* 1A060 80029860 ACD120A0 */  sb         $zero, %lo(D_8009D1AC)($at)
    /* 1A064 80029864 0A80033C */  lui        $v1, %hi(D_8009D1AC)
    /* 1A068 80029868 ACD1638C */  lw         $v1, %lo(D_8009D1AC)($v1)
    /* 1A06C 8002986C FFFC0224 */  addiu      $v0, $zero, -0x301
    /* 1A070 80029870 0A80013C */  lui        $at, %hi(D_8009D1A8)
    /* 1A074 80029874 A8D120AC */  sw         $zero, %lo(D_8009D1A8)($at)
    /* 1A078 80029878 0A80013C */  lui        $at, %hi(D_8009D1CE)
    /* 1A07C 8002987C CED120A0 */  sb         $zero, %lo(D_8009D1CE)($at)
    /* 1A080 80029880 0A80013C */  lui        $at, %hi(D_8009D235)
    /* 1A084 80029884 35D220A0 */  sb         $zero, %lo(D_8009D235)($at)
    /* 1A088 80029888 940580AF */  sw         $zero, %gp_rel(D_8009D304)($gp)
    /* 1A08C 8002988C AC0480A7 */  sh         $zero, %gp_rel(D_8009D21C)($gp)
    /* 1A090 80029890 24186200 */  and        $v1, $v1, $v0
    /* 1A094 80029894 0A80013C */  lui        $at, %hi(D_8009D1AC)
    /* 1A098 80029898 ACD123AC */  sw         $v1, %lo(D_8009D1AC)($at)
    /* 1A09C 8002989C FF008230 */  andi       $v0, $a0, 0xFF
  .L800298A0:
    /* 1A0A0 800298A0 01008424 */  addiu      $a0, $a0, 0x1
    /* 1A0A4 800298A4 80100200 */  sll        $v0, $v0, 2
    /* 1A0A8 800298A8 0A80013C */  lui        $at, %hi(D_800A7FF0)
    /* 1A0AC 800298AC 21082200 */  addu       $at, $at, $v0
    /* 1A0B0 800298B0 F07F20A4 */  sh         $zero, %lo(D_800A7FF0)($at)
    /* 1A0B4 800298B4 0A80013C */  lui        $at, %hi(D_800A7FF2)
    /* 1A0B8 800298B8 21082200 */  addu       $at, $at, $v0
    /* 1A0BC 800298BC F27F25A4 */  sh         $a1, %lo(D_800A7FF2)($at)
    /* 1A0C0 800298C0 FF008230 */  andi       $v0, $a0, 0xFF
    /* 1A0C4 800298C4 0A00422C */  sltiu      $v0, $v0, 0xA
    /* 1A0C8 800298C8 F5FF4014 */  bnez       $v0, .L800298A0
    /* 1A0CC 800298CC FF008230 */   andi      $v0, $a0, 0xFF
    /* 1A0D0 800298D0 21200000 */  addu       $a0, $zero, $zero
    /* 1A0D4 800298D4 0C80033C */  lui        $v1, %hi(D_800B8A90)
    /* 1A0D8 800298D8 908A6324 */  addiu      $v1, $v1, %lo(D_800B8A90)
    /* 1A0DC 800298DC FF008230 */  andi       $v0, $a0, 0xFF
  .L800298E0:
    /* 1A0E0 800298E0 80100200 */  sll        $v0, $v0, 2
    /* 1A0E4 800298E4 21104300 */  addu       $v0, $v0, $v1
    /* 1A0E8 800298E8 000040AC */  sw         $zero, 0x0($v0)
    /* 1A0EC 800298EC 01008424 */  addiu      $a0, $a0, 0x1
    /* 1A0F0 800298F0 FF008230 */  andi       $v0, $a0, 0xFF
    /* 1A0F4 800298F4 0700422C */  sltiu      $v0, $v0, 0x7
    /* 1A0F8 800298F8 F9FF4014 */  bnez       $v0, .L800298E0
    /* 1A0FC 800298FC FF008230 */   andi      $v0, $a0, 0xFF
    /* 1A100 80029900 0A80043C */  lui        $a0, %hi(D_8009D250)
    /* 1A104 80029904 50D2848C */  lw         $a0, %lo(D_8009D250)($a0)
    /* 1A108 80029908 99C6010C */  jal        srand
    /* 1A10C 8002990C 00000000 */   nop
    /* 1A110 80029910 FDA4000C */  jal        Battle_ResetEnemyStats
    /* 1A114 80029914 21200000 */   addu      $a0, $zero, $zero
    /* 1A118 80029918 7C82000C */  jal        Battle_SetupEnemyAnims
    /* 1A11C 8002991C 00000000 */   nop
    /* 1A120 80029920 0805838F */  lw         $v1, %gp_rel(g_ActiveActor)($gp)
    /* 1A124 80029924 00000000 */  nop
    /* 1A128 80029928 0800628C */  lw         $v0, 0x8($v1)
    /* 1A12C 8002992C 00000000 */  nop
    /* 1A130 80029930 0400401C */  bgtz       $v0, .L80029944
    /* 1A134 80029934 00000000 */   nop
    /* 1A138 80029938 0100023C */  lui        $v0, (0x10000 >> 16)
    /* 1A13C 8002993C 58A60008 */  j          .L80029960
    /* 1A140 80029940 080062AC */   sw        $v0, 0x8($v1)
  .L80029944:
    /* 1A144 80029944 2800648C */  lw         $a0, 0x28($v1)
    /* 1A148 80029948 00000000 */  nop
    /* 1A14C 8002994C 2A104400 */  slt        $v0, $v0, $a0
    /* 1A150 80029950 03004014 */  bnez       $v0, .L80029960
    /* 1A154 80029954 F0000224 */   addiu     $v0, $zero, 0xF0
    /* 1A158 80029958 080064AC */  sw         $a0, 0x8($v1)
    /* 1A15C 8002995C 340062AC */  sw         $v0, 0x34($v1)
  .L80029960:
    /* 1A160 80029960 90C1000C */  jal        Battle_CheckDropChance
    /* 1A164 80029964 00000000 */   nop
    /* 1A168 80029968 0A80033C */  lui        $v1, %hi(g_PlayerEntity)
    /* 1A16C 8002996C 54D2638C */  lw         $v1, %lo(g_PlayerEntity)($v1)
    /* 1A170 80029970 00000000 */  nop
    /* 1A174 80029974 3802648C */  lw         $a0, 0x238($v1)
    /* 1A178 80029978 0280023C */  lui        $v0, %hi(Entity_CheckActionIdMatch)
    /* 1A17C 8002997C 68D24224 */  addiu      $v0, $v0, %lo(Entity_CheckActionIdMatch)
    /* 1A180 80029980 940162AC */  sw         $v0, 0x194($v1)
    /* 1A184 80029984 1800828C */  lw         $v0, 0x18($a0)
    /* 1A188 80029988 00000000 */  nop
    /* 1A18C 8002998C 9CFF4224 */  addiu      $v0, $v0, -0x64
    /* 1A190 80029990 0A80013C */  lui        $at, %hi(D_8009D27C)
    /* 1A194 80029994 7CD222A4 */  sh         $v0, %lo(D_8009D27C)($at)
    /* 1A198 80029998 68CE000C */  jal        Window_SetBoundsByMode
    /* 1A19C 8002999C FF000432 */   andi      $a0, $s0, 0xFF
    /* 1A1A0 800299A0 0805828F */  lw         $v0, %gp_rel(g_ActiveActor)($gp)
    /* 1A1A4 800299A4 0A80043C */  lui        $a0, %hi(g_PlayerEntity)
    /* 1A1A8 800299A8 54D2848C */  lw         $a0, %lo(g_PlayerEntity)($a0)
    /* 1A1AC 800299AC 12004590 */  lbu        $a1, 0x12($v0)
    /* 1A1B0 800299B0 A069000C */  jal        Entity_SetActionMode
    /* 1A1B4 800299B4 00000000 */   nop
    /* 1A1B8 800299B8 1400BF8F */  lw         $ra, 0x14($sp)
    /* 1A1BC 800299BC 1000B08F */  lw         $s0, 0x10($sp)
    /* 1A1C0 800299C0 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 1A1C4 800299C4 0800E003 */  jr         $ra
    /* 1A1C8 800299C8 00000000 */   nop
endlabel Battle_StartEncounter
