.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.4 */

nonmatching CD_LoadBootAudio, 0x1E0

glabel CD_LoadBootAudio
    /* 5F844 8006F044 D8FFBD27 */  addiu      $sp, $sp, -0x28
    /* 5F848 8006F048 FFFF0224 */  addiu      $v0, $zero, -0x1
    /* 5F84C 8006F04C 0B80013C */  lui        $at, %hi(D_800B0DB5)
    /* 5F850 8006F050 B50D22A0 */  sb         $v0, %lo(D_800B0DB5)($at)
    /* 5F854 8006F054 0B80013C */  lui        $at, %hi(D_800B0DB4)
    /* 5F858 8006F058 B40D22A0 */  sb         $v0, %lo(D_800B0DB4)($at)
    /* 5F85C 8006F05C 0B80013C */  lui        $at, %hi(D_800B0DB7)
    /* 5F860 8006F060 B70D22A0 */  sb         $v0, %lo(D_800B0DB7)($at)
    /* 5F864 8006F064 0B80013C */  lui        $at, %hi(D_800B0DB6)
    /* 5F868 8006F068 B60D22A0 */  sb         $v0, %lo(D_800B0DB6)($at)
    /* 5F86C 8006F06C 0B80013C */  lui        $at, %hi(D_800B0DB3)
    /* 5F870 8006F070 B30D22A0 */  sb         $v0, %lo(D_800B0DB3)($at)
    /* 5F874 8006F074 0B80013C */  lui        $at, %hi(D_800B0DB2)
    /* 5F878 8006F078 B20D22A0 */  sb         $v0, %lo(D_800B0DB2)($at)
    /* 5F87C 8006F07C 0B80023C */  lui        $v0, %hi(g_GameState)
    /* 5F880 8006F080 D80C428C */  lw         $v0, %lo(g_GameState)($v0)
    /* 5F884 8006F084 0FFF0324 */  addiu      $v1, $zero, -0xF1
    /* 5F888 8006F088 2000BFAF */  sw         $ra, 0x20($sp)
    /* 5F88C 8006F08C 1C00B1AF */  sw         $s1, 0x1C($sp)
    /* 5F890 8006F090 1800B0AF */  sw         $s0, 0x18($sp)
    /* 5F894 8006F094 24104300 */  and        $v0, $v0, $v1
    /* 5F898 8006F098 0B80013C */  lui        $at, %hi(g_GameState)
    /* 5F89C 8006F09C D80C22AC */  sw         $v0, %lo(g_GameState)($at)
    /* 5F8A0 8006F0A0 FE1B020C */  jal        Akao_Cmd_F0
    /* 5F8A4 8006F0A4 00000000 */   nop
  .L8006F0A8:
    /* 5F8A8 8006F0A8 0980103C */  lui        $s0, %hi(g_SceneInitLbaTbl0)
    /* 5F8AC 8006F0AC 5E311026 */  addiu      $s0, $s0, %lo(g_SceneInitLbaTbl0)
    /* 5F8B0 8006F0B0 FFFF1124 */  addiu      $s1, $zero, -0x1
    /* 5F8B4 8006F0B4 21280000 */  addu       $a1, $zero, $zero
  .L8006F0B8:
    /* 5F8B8 8006F0B8 0180063C */  lui        $a2, %hi(D_8001160C)
    /* 5F8BC 8006F0BC 0C16C68C */  lw         $a2, %lo(D_8001160C)($a2)
    /* 5F8C0 8006F0C0 00000796 */  lhu        $a3, 0x0($s0)
    /* 5F8C4 8006F0C4 0B80043C */  lui        $a0, %hi(g_PeImageBaseLba)
    /* 5F8C8 8006F0C8 D80D848C */  lw         $a0, %lo(g_PeImageBaseLba)($a0)
    /* 5F8CC 8006F0CC 02000296 */  lhu        $v0, 0x2($s0)
    /* 5F8D0 8006F0D0 21208700 */  addu       $a0, $a0, $a3
    /* 5F8D4 8006F0D4 B5B9010C */  jal        CdRom_ReadSectors
    /* 5F8D8 8006F0D8 23384700 */   subu      $a3, $v0, $a3
    /* 5F8DC 8006F0DC F6FF5110 */  beq        $v0, $s1, .L8006F0B8
    /* 5F8E0 8006F0E0 21280000 */   addu      $a1, $zero, $zero
    /* 5F8E4 8006F0E4 FFFE103C */  lui        $s0, (0xFEFFBFFF >> 16)
    /* 5F8E8 8006F0E8 FFBF1036 */  ori        $s0, $s0, (0xFEFFBFFF & 0xFFFF)
    /* 5F8EC 8006F0EC FFFF1124 */  addiu      $s1, $zero, -0x1
  .L8006F0F0:
    /* 5F8F0 8006F0F0 7904020C */  jal        Sys_VSyncTimeout
    /* 5F8F4 8006F0F4 1000A427 */   addiu     $a0, $sp, 0x10
    /* 5F8F8 8006F0F8 21184000 */  addu       $v1, $v0, $zero
    /* 5F8FC 8006F0FC 01006224 */  addiu      $v0, $v1, 0x1
    /* 5F900 8006F100 0200422C */  sltiu      $v0, $v0, 0x2
    /* 5F904 8006F104 08004010 */  beqz       $v0, .L8006F128
    /* 5F908 8006F108 21106000 */   addu      $v0, $v1, $zero
    /* 5F90C 8006F10C 0B80023C */  lui        $v0, %hi(g_GameState)
    /* 5F910 8006F110 D80C428C */  lw         $v0, %lo(g_GameState)($v0)
    /* 5F914 8006F114 00000000 */  nop
    /* 5F918 8006F118 24105000 */  and        $v0, $v0, $s0
    /* 5F91C 8006F11C 0B80013C */  lui        $at, %hi(g_GameState)
    /* 5F920 8006F120 D80C22AC */  sw         $v0, %lo(g_GameState)($at)
    /* 5F924 8006F124 21106000 */  addu       $v0, $v1, $zero
  .L8006F128:
    /* 5F928 8006F128 05004010 */  beqz       $v0, .L8006F140
    /* 5F92C 8006F12C 00000000 */   nop
    /* 5F930 8006F130 DDFF5110 */  beq        $v0, $s1, .L8006F0A8
    /* 5F934 8006F134 00000000 */   nop
    /* 5F938 8006F138 3CBC0108 */  j          .L8006F0F0
    /* 5F93C 8006F13C 00000000 */   nop
  .L8006F140:
    /* 5F940 8006F140 C5C9010C */  jal        EnterCriticalSection
    /* 5F944 8006F144 00000000 */   nop
    /* 5F948 8006F148 B1C9010C */  jal        FlushCache
    /* 5F94C 8006F14C 00000000 */   nop
    /* 5F950 8006F150 C9C9010C */  jal        ExitCriticalSection
    /* 5F954 8006F154 00000000 */   nop
  .L8006F158:
    /* 5F958 8006F158 0980103C */  lui        $s0, %hi(D_80093166)
    /* 5F95C 8006F15C 66311026 */  addiu      $s0, $s0, %lo(D_80093166)
    /* 5F960 8006F160 FFFF1124 */  addiu      $s1, $zero, -0x1
    /* 5F964 8006F164 21280000 */  addu       $a1, $zero, $zero
  .L8006F168:
    /* 5F968 8006F168 0180063C */  lui        $a2, %hi(D_80011610)
    /* 5F96C 8006F16C 1016C68C */  lw         $a2, %lo(D_80011610)($a2)
    /* 5F970 8006F170 00000796 */  lhu        $a3, 0x0($s0)
    /* 5F974 8006F174 0B80043C */  lui        $a0, %hi(g_PeImageBaseLba)
    /* 5F978 8006F178 D80D848C */  lw         $a0, %lo(g_PeImageBaseLba)($a0)
    /* 5F97C 8006F17C 02000296 */  lhu        $v0, 0x2($s0)
    /* 5F980 8006F180 21208700 */  addu       $a0, $a0, $a3
    /* 5F984 8006F184 B5B9010C */  jal        CdRom_ReadSectors
    /* 5F988 8006F188 23384700 */   subu      $a3, $v0, $a3
    /* 5F98C 8006F18C F6FF5110 */  beq        $v0, $s1, .L8006F168
    /* 5F990 8006F190 21280000 */   addu      $a1, $zero, $zero
    /* 5F994 8006F194 FFFE103C */  lui        $s0, (0xFEFFBFFF >> 16)
    /* 5F998 8006F198 FFBF1036 */  ori        $s0, $s0, (0xFEFFBFFF & 0xFFFF)
    /* 5F99C 8006F19C FFFF1124 */  addiu      $s1, $zero, -0x1
  .L8006F1A0:
    /* 5F9A0 8006F1A0 7904020C */  jal        Sys_VSyncTimeout
    /* 5F9A4 8006F1A4 1000A427 */   addiu     $a0, $sp, 0x10
    /* 5F9A8 8006F1A8 21184000 */  addu       $v1, $v0, $zero
    /* 5F9AC 8006F1AC 01006224 */  addiu      $v0, $v1, 0x1
    /* 5F9B0 8006F1B0 0200422C */  sltiu      $v0, $v0, 0x2
    /* 5F9B4 8006F1B4 08004010 */  beqz       $v0, .L8006F1D8
    /* 5F9B8 8006F1B8 21106000 */   addu      $v0, $v1, $zero
    /* 5F9BC 8006F1BC 0B80023C */  lui        $v0, %hi(g_GameState)
    /* 5F9C0 8006F1C0 D80C428C */  lw         $v0, %lo(g_GameState)($v0)
    /* 5F9C4 8006F1C4 00000000 */  nop
    /* 5F9C8 8006F1C8 24105000 */  and        $v0, $v0, $s0
    /* 5F9CC 8006F1CC 0B80013C */  lui        $at, %hi(g_GameState)
    /* 5F9D0 8006F1D0 D80C22AC */  sw         $v0, %lo(g_GameState)($at)
    /* 5F9D4 8006F1D4 21106000 */  addu       $v0, $v1, $zero
  .L8006F1D8:
    /* 5F9D8 8006F1D8 05004010 */  beqz       $v0, .L8006F1F0
    /* 5F9DC 8006F1DC 00000000 */   nop
    /* 5F9E0 8006F1E0 DDFF5110 */  beq        $v0, $s1, .L8006F158
    /* 5F9E4 8006F1E4 00000000 */   nop
    /* 5F9E8 8006F1E8 68BC0108 */  j          .L8006F1A0
    /* 5F9EC 8006F1EC 00000000 */   nop
  .L8006F1F0:
    /* 5F9F0 8006F1F0 C5C9010C */  jal        EnterCriticalSection
    /* 5F9F4 8006F1F4 00000000 */   nop
    /* 5F9F8 8006F1F8 B1C9010C */  jal        FlushCache
    /* 5F9FC 8006F1FC 00000000 */   nop
    /* 5FA00 8006F200 C9C9010C */  jal        ExitCriticalSection
    /* 5FA04 8006F204 00000000 */   nop
    /* 5FA08 8006F208 21100000 */  addu       $v0, $zero, $zero
    /* 5FA0C 8006F20C 2000BF8F */  lw         $ra, 0x20($sp)
    /* 5FA10 8006F210 1C00B18F */  lw         $s1, 0x1C($sp)
    /* 5FA14 8006F214 1800B08F */  lw         $s0, 0x18($sp)
    /* 5FA18 8006F218 2800BD27 */  addiu      $sp, $sp, 0x28
    /* 5FA1C 8006F21C 0800E003 */  jr         $ra
    /* 5FA20 8006F220 00000000 */   nop
endlabel CD_LoadBootAudio
