.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.4 */

nonmatching CD_StepReadState, 0x53C

glabel CD_StepReadState
    /* 5DE0C 8006D60C D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* 5DE10 8006D610 2800B2AF */  sw         $s2, 0x28($sp)
    /* 5DE14 8006D614 21908000 */  addu       $s2, $a0, $zero
    /* 5DE18 8006D618 2400B1AF */  sw         $s1, 0x24($sp)
    /* 5DE1C 8006D61C 0B80113C */  lui        $s1, %hi(g_GameState)
    /* 5DE20 8006D620 D80C3126 */  addiu      $s1, $s1, %lo(g_GameState)
    /* 5DE24 8006D624 2C00BFAF */  sw         $ra, 0x2C($sp)
    /* 5DE28 8006D628 2000B0AF */  sw         $s0, 0x20($sp)
  .L8006D62C:
    /* 5DE2C 8006D62C F2002392 */  lbu        $v1, 0xF2($s1)
    /* 5DE30 8006D630 00000000 */  nop
    /* 5DE34 8006D634 4100622C */  sltiu      $v0, $v1, 0x41
    /* 5DE38 8006D638 3B014010 */  beqz       $v0, .L8006DB28
    /* 5DE3C 8006D63C 80100300 */   sll       $v0, $v1, 2
    /* 5DE40 8006D640 0180013C */  lui        $at, %hi(jtbl_80011508)
    /* 5DE44 8006D644 21082200 */  addu       $at, $at, $v0
    /* 5DE48 8006D648 0815228C */  lw         $v0, %lo(jtbl_80011508)($at)
    /* 5DE4C 8006D64C 00000000 */  nop
    /* 5DE50 8006D650 08004000 */  jr         $v0
    /* 5DE54 8006D654 00000000 */   nop
  jlabel .L8006D658
    /* 5DE58 8006D658 180480AF */  sw         $zero, %gp_rel(D_8009D188)($gp)
    /* 5DE5C 8006D65C 091C020C */  jal        Akao_Cmd_F1
    /* 5DE60 8006D660 00000000 */   nop
    /* 5DE64 8006D664 21004012 */  beqz       $s2, .L8006D6EC
    /* 5DE68 8006D668 4000033C */   lui       $v1, (0x400000 >> 16)
    /* 5DE6C 8006D66C 0B80023C */  lui        $v0, %hi(g_GameState)
    /* 5DE70 8006D670 D80C428C */  lw         $v0, %lo(g_GameState)($v0)
    /* 5DE74 8006D674 00000000 */  nop
    /* 5DE78 8006D678 24104300 */  and        $v0, $v0, $v1
    /* 5DE7C 8006D67C 19004014 */  bnez       $v0, .L8006D6E4
    /* 5DE80 8006D680 2C000224 */   addiu     $v0, $zero, 0x2C
    /* 5DE84 8006D684 0B80023C */  lui        $v0, %hi(D_800B0E08)
    /* 5DE88 8006D688 080E428C */  lw         $v0, %lo(D_800B0E08)($v0)
    /* 5DE8C 8006D68C 00000000 */  nop
    /* 5DE90 8006D690 13004010 */  beqz       $v0, .L8006D6E0
    /* 5DE94 8006D694 51040524 */   addiu     $a1, $zero, 0x451
    /* 5DE98 8006D698 21300000 */  addu       $a2, $zero, $zero
    /* 5DE9C 8006D69C 80000724 */  addiu      $a3, $zero, 0x80
    /* 5DEA0 8006D6A0 0B80043C */  lui        $a0, %hi(D_800B0E08)
    /* 5DEA4 8006D6A4 080E848C */  lw         $a0, %lo(D_800B0E08)($a0)
    /* 5DEA8 8006D6A8 7F001024 */  addiu      $s0, $zero, 0x7F
    /* 5DEAC 8006D6AC D4B7010C */  jal        Akao_SendTableCommand
    /* 5DEB0 8006D6B0 1000B0AF */   sw        $s0, 0x10($sp)
    /* 5DEB4 8006D6B4 0B80023C */  lui        $v0, %hi(D_800B0E08)
    /* 5DEB8 8006D6B8 080E428C */  lw         $v0, %lo(D_800B0E08)($v0)
    /* 5DEBC 8006D6BC 00000000 */  nop
    /* 5DEC0 8006D6C0 07004010 */  beqz       $v0, .L8006D6E0
    /* 5DEC4 8006D6C4 52040524 */   addiu     $a1, $zero, 0x452
    /* 5DEC8 8006D6C8 21300000 */  addu       $a2, $zero, $zero
    /* 5DECC 8006D6CC 0B80043C */  lui        $a0, %hi(D_800B0E08)
    /* 5DED0 8006D6D0 080E848C */  lw         $a0, %lo(D_800B0E08)($a0)
    /* 5DED4 8006D6D4 80000724 */  addiu      $a3, $zero, 0x80
    /* 5DED8 8006D6D8 D4B7010C */  jal        Akao_SendTableCommand
    /* 5DEDC 8006D6DC 1000B0AF */   sw        $s0, 0x10($sp)
  .L8006D6E0:
    /* 5DEE0 8006D6E0 2C000224 */  addiu      $v0, $zero, 0x2C
  .L8006D6E4:
    /* 5DEE4 8006D6E4 8BB50108 */  j          .L8006D62C
    /* 5DEE8 8006D6E8 F20022A2 */   sb        $v0, 0xF2($s1)
  .L8006D6EC:
    /* 5DEEC 8006D6EC 0000228E */  lw         $v0, 0x0($s1)
    /* 5DEF0 8006D6F0 00000000 */  nop
    /* 5DEF4 8006D6F4 04004230 */  andi       $v0, $v0, 0x4
    /* 5DEF8 8006D6F8 08004010 */  beqz       $v0, .L8006D71C
    /* 5DEFC 8006D6FC 21200000 */   addu      $a0, $zero, $zero
    /* 5DF00 8006D700 3C000524 */  addiu      $a1, $zero, 0x3C
    /* 5DF04 8006D704 0A80023C */  lui        $v0, %hi(D_8009CDA4)
    /* 5DF08 8006D708 A4CD428C */  lw         $v0, %lo(D_8009CDA4)($v0)
    /* 5DF0C 8006D70C 00000000 */  nop
    /* 5DF10 8006D710 1C0482AF */  sw         $v0, %gp_rel(D_8009D18C)($gp)
    /* 5DF14 8006D714 171B020C */  jal        Akao_Cmd_C1_WithSlot
    /* 5DF18 8006D718 21300000 */   addu      $a2, $zero, $zero
  .L8006D71C:
    /* 5DF1C 8006D71C 2D000224 */  addiu      $v0, $zero, 0x2D
    /* 5DF20 8006D720 8BB50108 */  j          .L8006D62C
    /* 5DF24 8006D724 F20022A2 */   sb        $v0, 0xF2($s1)
  jlabel .L8006D728
    /* 5DF28 8006D728 E0002382 */  lb         $v1, 0xE0($s1)
    /* 5DF2C 8006D72C DC002282 */  lb         $v0, 0xDC($s1)
    /* 5DF30 8006D730 00000000 */  nop
    /* 5DF34 8006D734 12006210 */  beq        $v1, $v0, .L8006D780
    /* 5DF38 8006D738 2E000224 */   addiu     $v0, $zero, 0x2E
    /* 5DF3C 8006D73C 0000228E */  lw         $v0, 0x0($s1)
    /* 5DF40 8006D740 00000000 */  nop
    /* 5DF44 8006D744 40004230 */  andi       $v0, $v0, 0x40
    /* 5DF48 8006D748 08004010 */  beqz       $v0, .L8006D76C
    /* 5DF4C 8006D74C 21200000 */   addu      $a0, $zero, $zero
    /* 5DF50 8006D750 3C000524 */  addiu      $a1, $zero, 0x3C
    /* 5DF54 8006D754 0A80023C */  lui        $v0, %hi(D_8009CDA4)
    /* 5DF58 8006D758 A4CD428C */  lw         $v0, %lo(D_8009CDA4)($v0)
    /* 5DF5C 8006D75C 00000000 */  nop
    /* 5DF60 8006D760 1C0482AF */  sw         $v0, %gp_rel(D_8009D18C)($gp)
    /* 5DF64 8006D764 171B020C */  jal        Akao_Cmd_C1_WithSlot
    /* 5DF68 8006D768 21300000 */   addu      $a2, $zero, $zero
  .L8006D76C:
    /* 5DF6C 8006D76C 0000228E */  lw         $v0, 0x0($s1)
    /* 5DF70 8006D770 00000000 */  nop
    /* 5DF74 8006D774 04004234 */  ori        $v0, $v0, 0x4
    /* 5DF78 8006D778 000022AE */  sw         $v0, 0x0($s1)
    /* 5DF7C 8006D77C 2E000224 */  addiu      $v0, $zero, 0x2E
  .L8006D780:
    /* 5DF80 8006D780 8BB50108 */  j          .L8006D62C
    /* 5DF84 8006D784 F20022A2 */   sb        $v0, 0xF2($s1)
  jlabel .L8006D788
    /* 5DF88 8006D788 1EB4010C */  jal        CD_FindNextDataSector
    /* 5DF8C 8006D78C 00000000 */   nop
    /* 5DF90 8006D790 01000324 */  addiu      $v1, $zero, 0x1
    /* 5DF94 8006D794 E5004310 */  beq        $v0, $v1, .L8006DB2C
    /* 5DF98 8006D798 01000224 */   addiu     $v0, $zero, 0x1
    /* 5DF9C 8006D79C 0000238E */  lw         $v1, 0x0($s1)
    /* 5DFA0 8006D7A0 00000000 */  nop
    /* 5DFA4 8006D7A4 04006230 */  andi       $v0, $v1, 0x4
    /* 5DFA8 8006D7A8 18004010 */  beqz       $v0, .L8006D80C
    /* 5DFAC 8006D7AC 40006230 */   andi      $v0, $v1, 0x40
    /* 5DFB0 8006D7B0 17004010 */  beqz       $v0, .L8006D810
    /* 5DFB4 8006D7B4 3F000224 */   addiu     $v0, $zero, 0x3F
    /* 5DFB8 8006D7B8 0A80023C */  lui        $v0, %hi(D_8009CDA4)
    /* 5DFBC 8006D7BC A4CD428C */  lw         $v0, %lo(D_8009CDA4)($v0)
    /* 5DFC0 8006D7C0 1C04838F */  lw         $v1, %gp_rel(D_8009D18C)($gp)
    /* 5DFC4 8006D7C4 00000000 */  nop
    /* 5DFC8 8006D7C8 23104300 */  subu       $v0, $v0, $v1
    /* 5DFCC 8006D7CC 3C000324 */  addiu      $v1, $zero, 0x3C
    /* 5DFD0 8006D7D0 23186200 */  subu       $v1, $v1, $v0
    /* 5DFD4 8006D7D4 09006228 */  slti       $v0, $v1, 0x9
    /* 5DFD8 8006D7D8 200483AF */  sw         $v1, %gp_rel(D_8009D190)($gp)
    /* 5DFDC 8006D7DC 08004014 */  bnez       $v0, .L8006D800
    /* 5DFE0 8006D7E0 08000224 */   addiu     $v0, $zero, 0x8
    /* 5DFE4 8006D7E4 200482AF */  sw         $v0, %gp_rel(D_8009D190)($gp)
    /* 5DFE8 8006D7E8 21200000 */  addu       $a0, $zero, $zero
    /* 5DFEC 8006D7EC 10000524 */  addiu      $a1, $zero, 0x10
    /* 5DFF0 8006D7F0 171B020C */  jal        Akao_Cmd_C1_WithSlot
    /* 5DFF4 8006D7F4 21300000 */   addu      $a2, $zero, $zero
    /* 5DFF8 8006D7F8 04B60108 */  j          .L8006D810
    /* 5DFFC 8006D7FC 3F000224 */   addiu     $v0, $zero, 0x3F
  .L8006D800:
    /* 5E000 8006D800 03006104 */  bgez       $v1, .L8006D810
    /* 5E004 8006D804 3F000224 */   addiu     $v0, $zero, 0x3F
    /* 5E008 8006D808 200480AF */  sw         $zero, %gp_rel(D_8009D190)($gp)
  .L8006D80C:
    /* 5E00C 8006D80C 3F000224 */  addiu      $v0, $zero, 0x3F
  .L8006D810:
    /* 5E010 8006D810 8BB50108 */  j          .L8006D62C
    /* 5E014 8006D814 F20022A2 */   sb        $v0, 0xF2($s1)
  jlabel .L8006D818
    /* 5E018 8006D818 0000238E */  lw         $v1, 0x0($s1)
    /* 5E01C 8006D81C 00000000 */  nop
    /* 5E020 8006D820 04006230 */  andi       $v0, $v1, 0x4
    /* 5E024 8006D824 19004010 */  beqz       $v0, .L8006D88C
    /* 5E028 8006D828 40006230 */   andi      $v0, $v1, 0x40
    /* 5E02C 8006D82C 0A004010 */  beqz       $v0, .L8006D858
    /* 5E030 8006D830 2F000224 */   addiu     $v0, $zero, 0x2F
    /* 5E034 8006D834 2004828F */  lw         $v0, %gp_rel(D_8009D190)($gp)
    /* 5E038 8006D838 00000000 */  nop
    /* 5E03C 8006D83C 7300401C */  bgtz       $v0, .L8006DA0C
    /* 5E040 8006D840 FFFF4224 */   addiu     $v0, $v0, -0x1
    /* 5E044 8006D844 3319020C */  jal        Akao_Cmd_40
    /* 5E048 8006D848 00000000 */   nop
    /* 5E04C 8006D84C FE1B020C */  jal        Akao_Cmd_F0
    /* 5E050 8006D850 00000000 */   nop
    /* 5E054 8006D854 2F000224 */  addiu      $v0, $zero, 0x2F
  .L8006D858:
    /* 5E058 8006D858 8BB50108 */  j          .L8006D62C
    /* 5E05C 8006D85C F20022A2 */   sb        $v0, 0xF2($s1)
  jlabel .L8006D860
    /* 5E060 8006D860 21200000 */  addu       $a0, $zero, $zero
    /* 5E064 8006D864 21300000 */  addu       $a2, $zero, $zero
    /* 5E068 8006D868 9401278E */  lw         $a3, 0x194($s1)
    /* 5E06C 8006D86C E1002582 */  lb         $a1, 0xE1($s1)
    /* 5E070 8006D870 21000224 */  addiu      $v0, $zero, 0x21
    /* 5E074 8006D874 1000A2AF */  sw         $v0, 0x10($sp)
    /* 5E078 8006D878 69B3010C */  jal        CD_ReadSectors
    /* 5E07C 8006D87C 1400A0AF */   sw        $zero, 0x14($sp)
    /* 5E080 8006D880 01000324 */  addiu      $v1, $zero, 0x1
    /* 5E084 8006D884 A9004310 */  beq        $v0, $v1, .L8006DB2C
    /* 5E088 8006D888 01000224 */   addiu     $v0, $zero, 0x1
  .L8006D88C:
    /* 5E08C 8006D88C 30000224 */  addiu      $v0, $zero, 0x30
    /* 5E090 8006D890 8BB50108 */  j          .L8006D62C
    /* 5E094 8006D894 F20022A2 */   sb        $v0, 0xF2($s1)
  jlabel .L8006D898
    /* 5E098 8006D898 2401248E */  lw         $a0, 0x124($s1)
    /* 5E09C 8006D89C 1919020C */  jal        Akao_Cmd_10
    /* 5E0A0 8006D8A0 00000000 */   nop
    /* 5E0A4 8006D8A4 21200000 */  addu       $a0, $zero, $zero
    /* 5E0A8 8006D8A8 071B020C */  jal        Akao_Cmd_C0_WithSlot
    /* 5E0AC 8006D8AC 7F000524 */   addiu     $a1, $zero, 0x7F
    /* 5E0B0 8006D8B0 21100000 */  addu       $v0, $zero, $zero
    /* 5E0B4 8006D8B4 CBB60108 */  j          .L8006DB2C
    /* 5E0B8 8006D8B8 F20020A2 */   sb        $zero, 0xF2($s1)
  jlabel .L8006D8BC
    /* 5E0BC 8006D8BC 1804838F */  lw         $v1, %gp_rel(D_8009D188)($gp)
    /* 5E0C0 8006D8C0 00000000 */  nop
    /* 5E0C4 8006D8C4 02006228 */  slti       $v0, $v1, 0x2
    /* 5E0C8 8006D8C8 09004010 */  beqz       $v0, .L8006D8F0
    /* 5E0CC 8006D8CC 21102302 */   addu      $v0, $s1, $v1
    /* 5E0D0 8006D8D0 EA004290 */  lbu        $v0, 0xEA($v0)
    /* 5E0D4 8006D8D4 00000000 */  nop
    /* 5E0D8 8006D8D8 03004010 */  beqz       $v0, .L8006D8E8
    /* 5E0DC 8006D8DC 31000224 */   addiu     $v0, $zero, 0x31
    /* 5E0E0 8006D8E0 8BB50108 */  j          .L8006D62C
    /* 5E0E4 8006D8E4 F20022A2 */   sb        $v0, 0xF2($s1)
  .L8006D8E8:
    /* 5E0E8 8006D8E8 01006224 */  addiu      $v0, $v1, 0x1
    /* 5E0EC 8006D8EC 180482AF */  sw         $v0, %gp_rel(D_8009D188)($gp)
  .L8006D8F0:
    /* 5E0F0 8006D8F0 32000224 */  addiu      $v0, $zero, 0x32
    /* 5E0F4 8006D8F4 8BB50108 */  j          .L8006D62C
    /* 5E0F8 8006D8F8 F20022A2 */   sb        $v0, 0xF2($s1)
  jlabel .L8006D8FC
    /* 5E0FC 8006D8FC 02000424 */  addiu      $a0, $zero, 0x2
    /* 5E100 8006D900 1804868F */  lw         $a2, %gp_rel(D_8009D188)($gp)
    /* 5E104 8006D904 9401278E */  lw         $a3, 0x194($s1)
    /* 5E108 8006D908 21102602 */  addu       $v0, $s1, $a2
    /* 5E10C 8006D90C EA004590 */  lbu        $a1, 0xEA($v0)
    /* 5E110 8006D910 21000224 */  addiu      $v0, $zero, 0x21
    /* 5E114 8006D914 1000A2AF */  sw         $v0, 0x10($sp)
    /* 5E118 8006D918 69B3010C */  jal        CD_ReadSectors
    /* 5E11C 8006D91C 1400A0AF */   sw        $zero, 0x14($sp)
    /* 5E120 8006D920 01000324 */  addiu      $v1, $zero, 0x1
    /* 5E124 8006D924 3A004310 */  beq        $v0, $v1, .L8006DA10
    /* 5E128 8006D928 2D000324 */   addiu     $v1, $zero, 0x2D
    /* 5E12C 8006D92C 1804828F */  lw         $v0, %gp_rel(D_8009D188)($gp)
    /* 5E130 8006D930 F20023A2 */  sb         $v1, 0xF2($s1)
    /* 5E134 8006D934 01004224 */  addiu      $v0, $v0, 0x1
    /* 5E138 8006D938 180482AF */  sw         $v0, %gp_rel(D_8009D188)($gp)
    /* 5E13C 8006D93C 8BB50108 */  j          .L8006D62C
    /* 5E140 8006D940 00000000 */   nop
  jlabel .L8006D944
    /* 5E144 8006D944 E8002586 */  lh         $a1, 0xE8($s1)
    /* 5E148 8006D948 FFFF0224 */  addiu      $v0, $zero, -0x1
    /* 5E14C 8006D94C 0A00A210 */  beq        $a1, $v0, .L8006D978
    /* 5E150 8006D950 01000424 */   addiu     $a0, $zero, 0x1
    /* 5E154 8006D954 21300000 */  addu       $a2, $zero, $zero
    /* 5E158 8006D958 9401278E */  lw         $a3, 0x194($s1)
    /* 5E15C 8006D95C 21000224 */  addiu      $v0, $zero, 0x21
    /* 5E160 8006D960 1000A2AF */  sw         $v0, 0x10($sp)
    /* 5E164 8006D964 69B3010C */  jal        CD_ReadSectors
    /* 5E168 8006D968 1400A0AF */   sw        $zero, 0x14($sp)
    /* 5E16C 8006D96C 01000324 */  addiu      $v1, $zero, 0x1
    /* 5E170 8006D970 6E004310 */  beq        $v0, $v1, .L8006DB2C
    /* 5E174 8006D974 01000224 */   addiu     $v0, $zero, 0x1
  .L8006D978:
    /* 5E178 8006D978 0000228E */  lw         $v0, 0x0($s1)
    /* 5E17C 8006D97C 00000000 */  nop
    /* 5E180 8006D980 04004230 */  andi       $v0, $v0, 0x4
    /* 5E184 8006D984 16004010 */  beqz       $v0, .L8006D9E0
    /* 5E188 8006D988 40000224 */   addiu     $v0, $zero, 0x40
    /* 5E18C 8006D98C 0A80023C */  lui        $v0, %hi(D_8009CDA4)
    /* 5E190 8006D990 A4CD428C */  lw         $v0, %lo(D_8009CDA4)($v0)
    /* 5E194 8006D994 1C04838F */  lw         $v1, %gp_rel(D_8009D18C)($gp)
    /* 5E198 8006D998 00000000 */  nop
    /* 5E19C 8006D99C 23104300 */  subu       $v0, $v0, $v1
    /* 5E1A0 8006D9A0 3C000324 */  addiu      $v1, $zero, 0x3C
    /* 5E1A4 8006D9A4 23186200 */  subu       $v1, $v1, $v0
    /* 5E1A8 8006D9A8 09006228 */  slti       $v0, $v1, 0x9
    /* 5E1AC 8006D9AC 200483AF */  sw         $v1, %gp_rel(D_8009D190)($gp)
    /* 5E1B0 8006D9B0 08004014 */  bnez       $v0, .L8006D9D4
    /* 5E1B4 8006D9B4 08000224 */   addiu     $v0, $zero, 0x8
    /* 5E1B8 8006D9B8 200482AF */  sw         $v0, %gp_rel(D_8009D190)($gp)
    /* 5E1BC 8006D9BC 21200000 */  addu       $a0, $zero, $zero
    /* 5E1C0 8006D9C0 10000524 */  addiu      $a1, $zero, 0x10
    /* 5E1C4 8006D9C4 171B020C */  jal        Akao_Cmd_C1_WithSlot
    /* 5E1C8 8006D9C8 21300000 */   addu      $a2, $zero, $zero
    /* 5E1CC 8006D9CC 78B60108 */  j          .L8006D9E0
    /* 5E1D0 8006D9D0 40000224 */   addiu     $v0, $zero, 0x40
  .L8006D9D4:
    /* 5E1D4 8006D9D4 02006104 */  bgez       $v1, .L8006D9E0
    /* 5E1D8 8006D9D8 40000224 */   addiu     $v0, $zero, 0x40
    /* 5E1DC 8006D9DC 200480AF */  sw         $zero, %gp_rel(D_8009D190)($gp)
  .L8006D9E0:
    /* 5E1E0 8006D9E0 8BB50108 */  j          .L8006D62C
    /* 5E1E4 8006D9E4 F20022A2 */   sb        $v0, 0xF2($s1)
  jlabel .L8006D9E8
    /* 5E1E8 8006D9E8 0000228E */  lw         $v0, 0x0($s1)
    /* 5E1EC 8006D9EC 00000000 */  nop
    /* 5E1F0 8006D9F0 04004230 */  andi       $v0, $v0, 0x4
    /* 5E1F4 8006D9F4 15004010 */  beqz       $v0, .L8006DA4C
    /* 5E1F8 8006D9F8 21100000 */   addu      $v0, $zero, $zero
    /* 5E1FC 8006D9FC 2004828F */  lw         $v0, %gp_rel(D_8009D190)($gp)
    /* 5E200 8006DA00 00000000 */  nop
    /* 5E204 8006DA04 04004018 */  blez       $v0, .L8006DA18
    /* 5E208 8006DA08 FFFF4224 */   addiu     $v0, $v0, -0x1
  .L8006DA0C:
    /* 5E20C 8006DA0C 200482AF */  sw         $v0, %gp_rel(D_8009D190)($gp)
  .L8006DA10:
    /* 5E210 8006DA10 CBB60108 */  j          .L8006DB2C
    /* 5E214 8006DA14 01000224 */   addiu     $v0, $zero, 0x1
  .L8006DA18:
    /* 5E218 8006DA18 FE1B020C */  jal        Akao_Cmd_F0
    /* 5E21C 8006DA1C 00000000 */   nop
    /* 5E220 8006DA20 0000238E */  lw         $v1, 0x0($s1)
    /* 5E224 8006DA24 00000000 */  nop
    /* 5E228 8006DA28 40006230 */  andi       $v0, $v1, 0x40
    /* 5E22C 8006DA2C 06004010 */  beqz       $v0, .L8006DA48
    /* 5E230 8006DA30 BFFF0224 */   addiu     $v0, $zero, -0x41
    /* 5E234 8006DA34 24106200 */  and        $v0, $v1, $v0
    /* 5E238 8006DA38 000022AE */  sw         $v0, 0x0($s1)
    /* 5E23C 8006DA3C 3E000224 */  addiu      $v0, $zero, 0x3E
    /* 5E240 8006DA40 8BB50108 */  j          .L8006D62C
    /* 5E244 8006DA44 F20022A2 */   sb        $v0, 0xF2($s1)
  .L8006DA48:
    /* 5E248 8006DA48 21100000 */  addu       $v0, $zero, $zero
  .L8006DA4C:
    /* 5E24C 8006DA4C 0000238E */  lw         $v1, 0x0($s1)
    /* 5E250 8006DA50 FBFF0424 */  addiu      $a0, $zero, -0x5
    /* 5E254 8006DA54 F20020A2 */  sb         $zero, 0xF2($s1)
    /* 5E258 8006DA58 24186400 */  and        $v1, $v1, $a0
    /* 5E25C 8006DA5C CBB60108 */  j          .L8006DB2C
    /* 5E260 8006DA60 000023AE */   sw        $v1, 0x0($s1)
  jlabel .L8006DA64
    /* 5E264 8006DA64 21200000 */  addu       $a0, $zero, $zero
    /* 5E268 8006DA68 21300000 */  addu       $a2, $zero, $zero
    /* 5E26C 8006DA6C 9401278E */  lw         $a3, 0x194($s1)
    /* 5E270 8006DA70 DA002582 */  lb         $a1, 0xDA($s1)
    /* 5E274 8006DA74 21000224 */  addiu      $v0, $zero, 0x21
    /* 5E278 8006DA78 1000A2AF */  sw         $v0, 0x10($sp)
    /* 5E27C 8006DA7C 69B3010C */  jal        CD_ReadSectors
    /* 5E280 8006DA80 1400A0AF */   sw        $zero, 0x14($sp)
    /* 5E284 8006DA84 01000324 */  addiu      $v1, $zero, 0x1
    /* 5E288 8006DA88 E1FF4310 */  beq        $v0, $v1, .L8006DA10
    /* 5E28C 8006DA8C 33000224 */   addiu     $v0, $zero, 0x33
    /* 5E290 8006DA90 8BB50108 */  j          .L8006D62C
    /* 5E294 8006DA94 F20022A2 */   sb        $v0, 0xF2($s1)
  jlabel .L8006DA98
    /* 5E298 8006DA98 01000524 */  addiu      $a1, $zero, 0x1
    /* 5E29C 8006DA9C 21300000 */  addu       $a2, $zero, $zero
    /* 5E2A0 8006DAA0 DC002482 */  lb         $a0, 0xDC($s1)
    /* 5E2A4 8006DAA4 1800A727 */  addiu      $a3, $sp, 0x18
    /* 5E2A8 8006DAA8 AEB4010C */  jal        CD_SeekToTrack
    /* 5E2AC 8006DAAC 1000A0AF */   sw        $zero, 0x10($sp)
    /* 5E2B0 8006DAB0 01000324 */  addiu      $v1, $zero, 0x1
    /* 5E2B4 8006DAB4 1D004310 */  beq        $v0, $v1, .L8006DB2C
    /* 5E2B8 8006DAB8 01000224 */   addiu     $v0, $zero, 0x1
    /* 5E2BC 8006DABC 2801248E */  lw         $a0, 0x128($s1)
    /* 5E2C0 8006DAC0 1919020C */  jal        Akao_Cmd_10
    /* 5E2C4 8006DAC4 00000000 */   nop
    /* 5E2C8 8006DAC8 21804000 */  addu       $s0, $v0, $zero
    /* 5E2CC 8006DACC FFFF0224 */  addiu      $v0, $zero, -0x1
    /* 5E2D0 8006DAD0 04000216 */  bne        $s0, $v0, .L8006DAE4
    /* 5E2D4 8006DAD4 21200002 */   addu      $a0, $s0, $zero
    /* 5E2D8 8006DAD8 3E000224 */  addiu      $v0, $zero, 0x3E
    /* 5E2DC 8006DADC 84B60108 */  j          .L8006DA10
    /* 5E2E0 8006DAE0 F20022A2 */   sb        $v0, 0xF2($s1)
  .L8006DAE4:
    /* 5E2E4 8006DAE4 FE002692 */  lbu        $a2, 0xFE($s1)
    /* 5E2E8 8006DAE8 171B020C */  jal        Akao_Cmd_C1_WithSlot
    /* 5E2EC 8006DAEC 3C000524 */   addiu     $a1, $zero, 0x3C
    /* 5E2F0 8006DAF0 05000012 */  beqz       $s0, .L8006DB08
    /* 5E2F4 8006DAF4 21200000 */   addu      $a0, $zero, $zero
    /* 5E2F8 8006DAF8 DC002582 */  lb         $a1, 0xDC($s1)
    /* 5E2FC 8006DAFC FE002792 */  lbu        $a3, 0xFE($s1)
    /* 5E300 8006DB00 D2B6010C */  jal        Overlay_RegisterAudioSlot
    /* 5E304 8006DB04 21300002 */   addu      $a2, $s0, $zero
  .L8006DB08:
    /* 5E308 8006DB08 21100000 */  addu       $v0, $zero, $zero
    /* 5E30C 8006DB0C 0000238E */  lw         $v1, 0x0($s1)
    /* 5E310 8006DB10 FBFF0424 */  addiu      $a0, $zero, -0x5
    /* 5E314 8006DB14 F20020A2 */  sb         $zero, 0xF2($s1)
    /* 5E318 8006DB18 24186400 */  and        $v1, $v1, $a0
    /* 5E31C 8006DB1C 40006334 */  ori        $v1, $v1, 0x40
    /* 5E320 8006DB20 CBB60108 */  j          .L8006DB2C
    /* 5E324 8006DB24 000023AE */   sw        $v1, 0x0($s1)
  jlabel .L8006DB28
    /* 5E328 8006DB28 21100000 */  addu       $v0, $zero, $zero
  .L8006DB2C:
    /* 5E32C 8006DB2C 2C00BF8F */  lw         $ra, 0x2C($sp)
    /* 5E330 8006DB30 2800B28F */  lw         $s2, 0x28($sp)
    /* 5E334 8006DB34 2400B18F */  lw         $s1, 0x24($sp)
    /* 5E338 8006DB38 2000B08F */  lw         $s0, 0x20($sp)
    /* 5E33C 8006DB3C 3000BD27 */  addiu      $sp, $sp, 0x30
    /* 5E340 8006DB40 0800E003 */  jr         $ra
    /* 5E344 8006DB44 00000000 */   nop
endlabel CD_StepReadState
