.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.4 */

nonmatching Draw_SwapPrimBuffers, 0x188

glabel Draw_SwapPrimBuffers
    /* 55508 80064D08 D8FFBD27 */  addiu      $sp, $sp, -0x28
    /* 5550C 80064D0C 1400B1AF */  sw         $s1, 0x14($sp)
    /* 55510 80064D10 21888000 */  addu       $s1, $a0, $zero
    /* 55514 80064D14 E403858F */  lw         $a1, %gp_rel(g_MenuWidgetActiveListHead)($gp)
    /* 55518 80064D18 21300000 */  addu       $a2, $zero, $zero
    /* 5551C 80064D1C 2000BFAF */  sw         $ra, 0x20($sp)
    /* 55520 80064D20 1C00B3AF */  sw         $s3, 0x1C($sp)
    /* 55524 80064D24 1800B2AF */  sw         $s2, 0x18($sp)
    /* 55528 80064D28 1200A010 */  beqz       $a1, .L80064D74
    /* 5552C 80064D2C 1000B0AF */   sw        $s0, 0x10($sp)
    /* 55530 80064D30 21200000 */  addu       $a0, $zero, $zero
  .L80064D34:
    /* 55534 80064D34 2118A000 */  addu       $v1, $a1, $zero
  .L80064D38:
    /* 55538 80064D38 0800628C */  lw         $v0, 0x8($v1)
    /* 5553C 80064D3C 00000000 */  nop
    /* 55540 80064D40 06005110 */  beq        $v0, $s1, .L80064D5C
    /* 55544 80064D44 04008228 */   slti      $v0, $a0, 0x4
    /* 55548 80064D48 01008424 */  addiu      $a0, $a0, 0x1
    /* 5554C 80064D4C 04008228 */  slti       $v0, $a0, 0x4
    /* 55550 80064D50 F9FF4014 */  bnez       $v0, .L80064D38
    /* 55554 80064D54 04006324 */   addiu     $v1, $v1, 0x4
    /* 55558 80064D58 04008228 */  slti       $v0, $a0, 0x4
  .L80064D5C:
    /* 5555C 80064D5C 2F004014 */  bnez       $v0, .L80064E1C
    /* 55560 80064D60 00000000 */   nop
    /* 55564 80064D64 0000A58C */  lw         $a1, 0x0($a1)
    /* 55568 80064D68 00000000 */  nop
    /* 5556C 80064D6C F1FFA014 */  bnez       $a1, .L80064D34
    /* 55570 80064D70 21200000 */   addu      $a0, $zero, $zero
  .L80064D74:
    /* 55574 80064D74 E803908F */  lw         $s0, %gp_rel(g_MenuWidgetFreeListHead)($gp)
    /* 55578 80064D78 0400338E */  lw         $s3, 0x4($s1)
    /* 5557C 80064D7C 03000016 */  bnez       $s0, .L80064D8C
    /* 55580 80064D80 2190C000 */   addu      $s2, $a2, $zero
    /* 55584 80064D84 F049010C */  jal        BoundsCheck_AssertStub
    /* 55588 80064D88 0A000424 */   addiu     $a0, $zero, 0xA
  .L80064D8C:
    /* 5558C 80064D8C 03000424 */  addiu      $a0, $zero, 0x3
    /* 55590 80064D90 0000028E */  lw         $v0, 0x0($s0)
    /* 55594 80064D94 E403838F */  lw         $v1, %gp_rel(g_MenuWidgetActiveListHead)($gp)
    /* 55598 80064D98 0C000526 */  addiu      $a1, $s0, 0xC
    /* 5559C 80064D9C E40390AF */  sw         $s0, %gp_rel(g_MenuWidgetActiveListHead)($gp)
    /* 555A0 80064DA0 040013AE */  sw         $s3, 0x4($s0)
    /* 555A4 80064DA4 2C0000AE */  sw         $zero, 0x2C($s0)
    /* 555A8 80064DA8 300000AE */  sw         $zero, 0x30($s0)
    /* 555AC 80064DAC E80382AF */  sw         $v0, %gp_rel(g_MenuWidgetFreeListHead)($gp)
    /* 555B0 80064DB0 000003AE */  sw         $v1, 0x0($s0)
  .L80064DB4:
    /* 555B4 80064DB4 0800A0AC */  sw         $zero, 0x8($a1)
    /* 555B8 80064DB8 FFFF8424 */  addiu      $a0, $a0, -0x1
    /* 555BC 80064DBC FDFF8104 */  bgez       $a0, .L80064DB4
    /* 555C0 80064DC0 FCFFA524 */   addiu     $a1, $a1, -0x4
    /* 555C4 80064DC4 1C0000AE */  sw         $zero, 0x1C($s0)
    /* 555C8 80064DC8 180000AE */  sw         $zero, 0x18($s0)
    /* 555CC 80064DCC 240000AE */  sw         $zero, 0x24($s0)
    /* 555D0 80064DD0 200000AE */  sw         $zero, 0x20($s0)
    /* 555D4 80064DD4 15004012 */  beqz       $s2, .L80064E2C
    /* 555D8 80064DD8 280000AE */   sw        $zero, 0x28($s0)
    /* 555DC 80064DDC 21200000 */  addu       $a0, $zero, $zero
    /* 555E0 80064DE0 21184002 */  addu       $v1, $s2, $zero
  .L80064DE4:
    /* 555E4 80064DE4 0800628C */  lw         $v0, 0x8($v1)
    /* 555E8 80064DE8 00000000 */  nop
    /* 555EC 80064DEC 06004010 */  beqz       $v0, .L80064E08
    /* 555F0 80064DF0 04008228 */   slti      $v0, $a0, 0x4
    /* 555F4 80064DF4 01008424 */  addiu      $a0, $a0, 0x1
    /* 555F8 80064DF8 04008228 */  slti       $v0, $a0, 0x4
    /* 555FC 80064DFC F9FF4014 */  bnez       $v0, .L80064DE4
    /* 55600 80064E00 04006324 */   addiu     $v1, $v1, 0x4
    /* 55604 80064E04 04008228 */  slti       $v0, $a0, 0x4
  .L80064E08:
    /* 55608 80064E08 06004010 */  beqz       $v0, .L80064E24
    /* 5560C 80064E0C 80100400 */   sll       $v0, $a0, 2
    /* 55610 80064E10 21105200 */  addu       $v0, $v0, $s2
    /* 55614 80064E14 8B930108 */  j          .L80064E2C
    /* 55618 80064E18 080050AC */   sw        $s0, 0x8($v0)
  .L80064E1C:
    /* 5561C 80064E1C 5D930108 */  j          .L80064D74
    /* 55620 80064E20 2130A000 */   addu      $a2, $a1, $zero
  .L80064E24:
    /* 55624 80064E24 F049010C */  jal        BoundsCheck_AssertStub
    /* 55628 80064E28 0B000424 */   addiu     $a0, $zero, 0xB
  .L80064E2C:
    /* 5562C 80064E2C 04000016 */  bnez       $s0, .L80064E40
    /* 55630 80064E30 03000224 */   addiu     $v0, $zero, 0x3
    /* 55634 80064E34 F049010C */  jal        BoundsCheck_AssertStub
    /* 55638 80064E38 10000424 */   addiu     $a0, $zero, 0x10
    /* 5563C 80064E3C 03000224 */  addiu      $v0, $zero, 0x3
  .L80064E40:
    /* 55640 80064E40 200002AE */  sw         $v0, 0x20($s0)
    /* 55644 80064E44 0680023C */  lui        $v0, %hi(Draw_FlushFrontBuffer)
    /* 55648 80064E48 B44E4224 */  addiu      $v0, $v0, %lo(Draw_FlushFrontBuffer)
    /* 5564C 80064E4C 300002AE */  sw         $v0, 0x30($s0)
    /* 55650 80064E50 0680023C */  lui        $v0, %hi(Menu_StepListNavigate)
    /* 55654 80064E54 E0504224 */  addiu      $v0, $v0, %lo(Menu_StepListNavigate)
    /* 55658 80064E58 2C0002AE */  sw         $v0, 0x2C($s0)
    /* 5565C 80064E5C 340011AE */  sw         $s1, 0x34($s0)
    /* 55660 80064E60 6400228E */  lw         $v0, 0x64($s1)
    /* 55664 80064E64 00000000 */  nop
    /* 55668 80064E68 400002AE */  sw         $v0, 0x40($s0)
    /* 5566C 80064E6C 800030AE */  sw         $s0, 0x80($s1)
    /* 55670 80064E70 2000BF8F */  lw         $ra, 0x20($sp)
    /* 55674 80064E74 1C00B38F */  lw         $s3, 0x1C($sp)
    /* 55678 80064E78 1800B28F */  lw         $s2, 0x18($sp)
    /* 5567C 80064E7C 1400B18F */  lw         $s1, 0x14($sp)
    /* 55680 80064E80 1000B08F */  lw         $s0, 0x10($sp)
    /* 55684 80064E84 2800BD27 */  addiu      $sp, $sp, 0x28
    /* 55688 80064E88 0800E003 */  jr         $ra
    /* 5568C 80064E8C 00000000 */   nop
endlabel Draw_SwapPrimBuffers
