.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.4 */

nonmatching Geo_PointInTri, 0x1C8

glabel Geo_PointInTri
    /* CE14 8001C614 6804828F */  lw         $v0, %gp_rel(g_CollisionPlaneTable)($gp)
    /* CE18 8001C618 00000000 */  nop
    /* CE1C 8001C61C 0C004010 */  beqz       $v0, .L8001C650
    /* CE20 8001C620 21588000 */   addu      $t3, $a0, $zero
    /* CE24 8001C624 0C006395 */  lhu        $v1, 0xC($t3)
    /* CE28 8001C628 8C04848F */  lw         $a0, %gp_rel(g_CollisionDb)($gp)
    /* CE2C 8001C62C 40100300 */  sll        $v0, $v1, 1
    /* CE30 8001C630 21104300 */  addu       $v0, $v0, $v1
    /* CE34 8001C634 1800838C */  lw         $v1, 0x18($a0)
    /* CE38 8001C638 40100200 */  sll        $v0, $v0, 1
    /* CE3C 8001C63C 21104300 */  addu       $v0, $v0, $v1
    /* CE40 8001C640 04004994 */  lhu        $t1, 0x4($v0)
    /* CE44 8001C644 00004794 */  lhu        $a3, 0x0($v0)
    /* CE48 8001C648 9C710008 */  j          .L8001C670
    /* CE4C 8001C64C 21680000 */   addu      $t5, $zero, $zero
  .L8001C650:
    /* CE50 8001C650 8C04828F */  lw         $v0, %gp_rel(g_CollisionDb)($gp)
    /* CE54 8001C654 06006395 */  lhu        $v1, 0x6($t3)
    /* CE58 8001C658 1800428C */  lw         $v0, 0x18($v0)
    /* CE5C 8001C65C 80180300 */  sll        $v1, $v1, 2
    /* CE60 8001C660 21186200 */  addu       $v1, $v1, $v0
    /* CE64 8001C664 02006994 */  lhu        $t1, 0x2($v1)
    /* CE68 8001C668 00006794 */  lhu        $a3, 0x0($v1)
    /* CE6C 8001C66C 21680000 */  addu       $t5, $zero, $zero
  .L8001C670:
    /* CE70 8001C670 21400000 */  addu       $t0, $zero, $zero
    /* CE74 8001C674 8C048E8F */  lw         $t6, %gp_rel(g_CollisionDb)($gp)
    /* CE78 8001C678 00140600 */  sll        $v0, $a2, 16
    /* CE7C 8001C67C 03640200 */  sra        $t4, $v0, 16
    /* CE80 8001C680 00140500 */  sll        $v0, $a1, 16
    /* CE84 8001C684 03540200 */  sra        $t2, $v0, 16
  .L8001C688:
    /* CE88 8001C688 2130E000 */  addu       $a2, $a3, $zero
    /* CE8C 8001C68C 6804828F */  lw         $v0, %gp_rel(g_CollisionPlaneTable)($gp)
    /* CE90 8001C690 00000000 */  nop
    /* CE94 8001C694 0C004010 */  beqz       $v0, .L8001C6C8
    /* CE98 8001C698 21202001 */   addu      $a0, $t1, $zero
    /* CE9C 8001C69C 08006295 */  lhu        $v0, 0x8($t3)
    /* CEA0 8001C6A0 00000000 */  nop
    /* CEA4 8001C6A4 40180200 */  sll        $v1, $v0, 1
    /* CEA8 8001C6A8 21186200 */  addu       $v1, $v1, $v0
    /* CEAC 8001C6AC 1800C28D */  lw         $v0, 0x18($t6)
    /* CEB0 8001C6B0 40180300 */  sll        $v1, $v1, 1
    /* CEB4 8001C6B4 21186200 */  addu       $v1, $v1, $v0
    /* CEB8 8001C6B8 04006994 */  lhu        $t1, 0x4($v1)
    /* CEBC 8001C6BC 00006794 */  lhu        $a3, 0x0($v1)
    /* CEC0 8001C6C0 B9710008 */  j          .L8001C6E4
    /* CEC4 8001C6C4 00140900 */   sll       $v0, $t1, 16
  .L8001C6C8:
    /* CEC8 8001C6C8 02006295 */  lhu        $v0, 0x2($t3)
    /* CECC 8001C6CC 1800C38D */  lw         $v1, 0x18($t6)
    /* CED0 8001C6D0 80100200 */  sll        $v0, $v0, 2
    /* CED4 8001C6D4 21104300 */  addu       $v0, $v0, $v1
    /* CED8 8001C6D8 02004994 */  lhu        $t1, 0x2($v0)
    /* CEDC 8001C6DC 00004794 */  lhu        $a3, 0x0($v0)
    /* CEE0 8001C6E0 00140900 */  sll        $v0, $t1, 16
  .L8001C6E4:
    /* CEE4 8001C6E4 03140200 */  sra        $v0, $v0, 16
    /* CEE8 8001C6E8 2A188201 */  slt        $v1, $t4, $v0
    /* CEEC 8001C6EC 07006014 */  bnez       $v1, .L8001C70C
    /* CEF0 8001C6F0 00140400 */   sll       $v0, $a0, 16
    /* CEF4 8001C6F4 03140200 */  sra        $v0, $v0, 16
    /* CEF8 8001C6F8 2A108201 */  slt        $v0, $t4, $v0
    /* CEFC 8001C6FC 07004014 */  bnez       $v0, .L8001C71C
    /* CF00 8001C700 00000000 */   nop
    /* CF04 8001C704 2F006010 */  beqz       $v1, .L8001C7C4
    /* CF08 8001C708 00140400 */   sll       $v0, $a0, 16
  .L8001C70C:
    /* CF0C 8001C70C 03140200 */  sra        $v0, $v0, 16
    /* CF10 8001C710 2A108201 */  slt        $v0, $t4, $v0
    /* CF14 8001C714 2B004014 */  bnez       $v0, .L8001C7C4
    /* CF18 8001C718 00000000 */   nop
  .L8001C71C:
    /* CF1C 8001C71C 00140700 */  sll        $v0, $a3, 16
    /* CF20 8001C720 03140200 */  sra        $v0, $v0, 16
    /* CF24 8001C724 2A184201 */  slt        $v1, $t2, $v0
    /* CF28 8001C728 07006010 */  beqz       $v1, .L8001C748
    /* CF2C 8001C72C 00140600 */   sll       $v0, $a2, 16
    /* CF30 8001C730 03140200 */  sra        $v0, $v0, 16
    /* CF34 8001C734 2A104201 */  slt        $v0, $t2, $v0
    /* CF38 8001C738 21004014 */  bnez       $v0, .L8001C7C0
    /* CF3C 8001C73C 00000000 */   nop
    /* CF40 8001C740 06006014 */  bnez       $v1, .L8001C75C
    /* CF44 8001C744 00140400 */   sll       $v0, $a0, 16
  .L8001C748:
    /* CF48 8001C748 00140600 */  sll        $v0, $a2, 16
    /* CF4C 8001C74C 03140200 */  sra        $v0, $v0, 16
    /* CF50 8001C750 2A104201 */  slt        $v0, $t2, $v0
    /* CF54 8001C754 1B004010 */  beqz       $v0, .L8001C7C4
    /* CF58 8001C758 00140400 */   sll       $v0, $a0, 16
  .L8001C75C:
    /* CF5C 8001C75C 03140200 */  sra        $v0, $v0, 16
    /* CF60 8001C760 00240900 */  sll        $a0, $t1, 16
    /* CF64 8001C764 03240400 */  sra        $a0, $a0, 16
    /* CF68 8001C768 23284400 */  subu       $a1, $v0, $a0
    /* CF6C 8001C76C 001C0600 */  sll        $v1, $a2, 16
    /* CF70 8001C770 031C0300 */  sra        $v1, $v1, 16
    /* CF74 8001C774 00140700 */  sll        $v0, $a3, 16
    /* CF78 8001C778 03140200 */  sra        $v0, $v0, 16
    /* CF7C 8001C77C 23186200 */  subu       $v1, $v1, $v0
    /* CF80 8001C780 23208401 */  subu       $a0, $t4, $a0
    /* CF84 8001C784 18006400 */  mult       $v1, $a0
    /* CF88 8001C788 12180000 */  mflo       $v1
    /* CF8C 8001C78C 0600A104 */  bgez       $a1, .L8001C7A8
    /* CF90 8001C790 00000000 */   nop
    /* CF94 8001C794 23104201 */  subu       $v0, $t2, $v0
    /* CF98 8001C798 1800A200 */  mult       $a1, $v0
    /* CF9C 8001C79C 12280000 */  mflo       $a1
    /* CFA0 8001C7A0 EE710008 */  j          .L8001C7B8
    /* CFA4 8001C7A4 2A106500 */   slt       $v0, $v1, $a1
  .L8001C7A8:
    /* CFA8 8001C7A8 23104201 */  subu       $v0, $t2, $v0
    /* CFAC 8001C7AC 1800A200 */  mult       $a1, $v0
    /* CFB0 8001C7B0 12280000 */  mflo       $a1
    /* CFB4 8001C7B4 2A10A300 */  slt        $v0, $a1, $v1
  .L8001C7B8:
    /* CFB8 8001C7B8 02004010 */  beqz       $v0, .L8001C7C4
    /* CFBC 8001C7BC 00000000 */   nop
  .L8001C7C0:
    /* CFC0 8001C7C0 0100082D */  sltiu      $t0, $t0, 0x1
  .L8001C7C4:
    /* CFC4 8001C7C4 0100AD25 */  addiu      $t5, $t5, 0x1
    /* CFC8 8001C7C8 0300A22D */  sltiu      $v0, $t5, 0x3
    /* CFCC 8001C7CC AEFF4014 */  bnez       $v0, .L8001C688
    /* CFD0 8001C7D0 02006B25 */   addiu     $t3, $t3, 0x2
    /* CFD4 8001C7D4 0800E003 */  jr         $ra
    /* CFD8 8001C7D8 21100001 */   addu      $v0, $t0, $zero
endlabel Geo_PointInTri
