.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.4 */

nonmatching Inv_SetupSlotDisplay, 0x33C

glabel Inv_SetupSlotDisplay
    /* 44D20 80054520 C8FFBD27 */  addiu      $sp, $sp, -0x38
    /* 44D24 80054524 2800B2AF */  sw         $s2, 0x28($sp)
    /* 44D28 80054528 21908000 */  addu       $s2, $a0, $zero
    /* 44D2C 8005452C 2000B0AF */  sw         $s0, 0x20($sp)
    /* 44D30 80054530 21800000 */  addu       $s0, $zero, $zero
    /* 44D34 80054534 2400B1AF */  sw         $s1, 0x24($sp)
    /* 44D38 80054538 21880000 */  addu       $s1, $zero, $zero
    /* 44D3C 8005453C D802828F */  lw         $v0, %gp_rel(g_InvItemPtr)($gp)
    /* 44D40 80054540 0C80033C */  lui        $v1, %hi(g_AyaInventoryItems)
    /* 44D44 80054544 480E6324 */  addiu      $v1, $v1, %lo(g_AyaInventoryItems)
    /* 44D48 80054548 3000BFAF */  sw         $ra, 0x30($sp)
    /* 44D4C 8005454C 2C00B3AF */  sw         $s3, 0x2C($sp)
    /* 44D50 80054550 D80283AF */  sw         $v1, %gp_rel(g_InvItemPtr)($gp)
    /* 44D54 80054554 26104300 */  xor        $v0, $v0, $v1
    /* 44D58 80054558 DC4B010C */  jal        Inv_GetAyaSlotLimit
    /* 44D5C 8005455C 2B980200 */   sltu      $s3, $zero, $v0
    /* 44D60 80054560 0A80033C */  lui        $v1, %hi(D_8009D05C)
    /* 44D64 80054564 5CD06324 */  addiu      $v1, $v1, %lo(D_8009D05C)
    /* 44D68 80054568 E80283AF */  sw         $v1, %gp_rel(D_8009D058)($gp)
    /* 44D6C 8005456C 02000324 */  addiu      $v1, $zero, 0x2
    /* 44D70 80054570 E00282AF */  sw         $v0, %gp_rel(g_InvSlotLimit)($gp)
    /* 44D74 80054574 F40283AF */  sw         $v1, %gp_rel(D_8009D064)($gp)
    /* 44D78 80054578 39004018 */  blez       $v0, .L80054660
    /* 44D7C 8005457C 00000000 */   nop
  .L80054580:
    /* 44D80 80054580 27000006 */  bltz       $s0, .L80054620
    /* 44D84 80054584 21180000 */   addu      $v1, $zero, $zero
    /* 44D88 80054588 E002828F */  lw         $v0, %gp_rel(g_InvSlotLimit)($gp)
    /* 44D8C 8005458C 00000000 */  nop
    /* 44D90 80054590 2A100202 */  slt        $v0, $s0, $v0
    /* 44D94 80054594 21004010 */  beqz       $v0, .L8005461C
    /* 44D98 80054598 40181000 */   sll       $v1, $s0, 1
    /* 44D9C 8005459C D802828F */  lw         $v0, %gp_rel(g_InvItemPtr)($gp)
    /* 44DA0 800545A0 00000000 */  nop
    /* 44DA4 800545A4 21186200 */  addu       $v1, $v1, $v0
    /* 44DA8 800545A8 00006384 */  lh         $v1, 0x0($v1)
    /* 44DAC 800545AC 00000000 */  nop
    /* 44DB0 800545B0 00FF6224 */  addiu      $v0, $v1, -0x100
    /* 44DB4 800545B4 8000422C */  sltiu      $v0, $v0, 0x80
    /* 44DB8 800545B8 06004010 */  beqz       $v0, .L800545D4
    /* 44DBC 800545BC 21286000 */   addu      $a1, $v1, $zero
    /* 44DC0 800545C0 40190300 */  sll        $v1, $v1, 5
    /* 44DC4 800545C4 0C80023C */  lui        $v0, %hi(D_800BEEAC)
    /* 44DC8 800545C8 ACEE4224 */  addiu      $v0, $v0, %lo(D_800BEEAC)
    /* 44DCC 800545CC 85510108 */  j          .L80054614
    /* 44DD0 800545D0 21106200 */   addu      $v0, $v1, $v0
  .L800545D4:
    /* 44DD4 800545D4 FFFF6424 */  addiu      $a0, $v1, -0x1
    /* 44DD8 800545D8 FF00822C */  sltiu      $v0, $a0, 0xFF
    /* 44DDC 800545DC 05004010 */  beqz       $v0, .L800545F4
    /* 44DE0 800545E0 00FEA224 */   addiu     $v0, $a1, -0x200
    /* 44DE4 800545E4 D176010C */  jal        Item_LookupBaseData
    /* 44DE8 800545E8 00000000 */   nop
    /* 44DEC 800545EC 88510108 */  j          .L80054620
    /* 44DF0 800545F0 21184000 */   addu      $v1, $v0, $zero
  .L800545F4:
    /* 44DF4 800545F4 0900422C */  sltiu      $v0, $v0, 0x9
    /* 44DF8 800545F8 05004010 */  beqz       $v0, .L80054610
    /* 44DFC 800545FC 40190500 */   sll       $v1, $a1, 5
    /* 44E00 80054600 0A80023C */  lui        $v0, %hi(D_8009DE64)
    /* 44E04 80054604 64DE4224 */  addiu      $v0, $v0, %lo(D_8009DE64)
    /* 44E08 80054608 85510108 */  j          .L80054614
    /* 44E0C 8005460C 21106200 */   addu      $v0, $v1, $v0
  .L80054610:
    /* 44E10 80054610 21100000 */  addu       $v0, $zero, $zero
  .L80054614:
    /* 44E14 80054614 88510108 */  j          .L80054620
    /* 44E18 80054618 21184000 */   addu      $v1, $v0, $zero
  .L8005461C:
    /* 44E1C 8005461C 21180000 */  addu       $v1, $zero, $zero
  .L80054620:
    /* 44E20 80054620 0A006010 */  beqz       $v1, .L8005464C
    /* 44E24 80054624 21200000 */   addu      $a0, $zero, $zero
    /* 44E28 80054628 06006290 */  lbu        $v0, 0x6($v1)
    /* 44E2C 8005462C 00000000 */  nop
    /* 44E30 80054630 07105200 */  srav       $v0, $s2, $v0
    /* 44E34 80054634 01004230 */  andi       $v0, $v0, 0x1
    /* 44E38 80054638 04004010 */  beqz       $v0, .L8005464C
    /* 44E3C 8005463C 00000000 */   nop
    /* 44E40 80054640 14006290 */  lbu        $v0, 0x14($v1)
    /* 44E44 80054644 00000000 */  nop
    /* 44E48 80054648 2B200200 */  sltu       $a0, $zero, $v0
  .L8005464C:
    /* 44E4C 8005464C E002828F */  lw         $v0, %gp_rel(g_InvSlotLimit)($gp)
    /* 44E50 80054650 01001026 */  addiu      $s0, $s0, 0x1
    /* 44E54 80054654 2A100202 */  slt        $v0, $s0, $v0
    /* 44E58 80054658 C9FF4014 */  bnez       $v0, .L80054580
    /* 44E5C 8005465C 21882402 */   addu      $s1, $s1, $a0
  .L80054660:
    /* 44E60 80054660 DC02838F */  lw         $v1, %gp_rel(D_8009D04C)($gp)
    /* 44E64 80054664 00000000 */  nop
    /* 44E68 80054668 02006010 */  beqz       $v1, .L80054674
    /* 44E6C 8005466C 01000224 */   addiu     $v0, $zero, 0x1
    /* 44E70 80054670 02000224 */  addiu      $v0, $zero, 0x2
  .L80054674:
    /* 44E74 80054674 02004228 */  slti       $v0, $v0, 0x2
    /* 44E78 80054678 53004014 */  bnez       $v0, .L800547C8
    /* 44E7C 8005467C 00014232 */   andi      $v0, $s2, 0x100
    /* 44E80 80054680 51004014 */  bnez       $v0, .L800547C8
    /* 44E84 80054684 00000000 */   nop
    /* 44E88 80054688 0B006010 */  beqz       $v1, .L800546B8
    /* 44E8C 8005468C 00000000 */   nop
    /* 44E90 80054690 D80283AF */  sw         $v1, %gp_rel(g_InvItemPtr)($gp)
    /* 44E94 80054694 E402838F */  lw         $v1, %gp_rel(D_8009D054)($gp)
    /* 44E98 80054698 0A80023C */  lui        $v0, %hi(D_800A1F84)
    /* 44E9C 8005469C 841F4224 */  addiu      $v0, $v0, %lo(D_800A1F84)
    /* 44EA0 800546A0 E80282AF */  sw         $v0, %gp_rel(D_8009D058)($gp)
    /* 44EA4 800546A4 04000224 */  addiu      $v0, $zero, 0x4
    /* 44EA8 800546A8 F40282AF */  sw         $v0, %gp_rel(D_8009D064)($gp)
    /* 44EAC 800546AC E00283AF */  sw         $v1, %gp_rel(g_InvSlotLimit)($gp)
    /* 44EB0 800546B0 B9510108 */  j          .L800546E4
    /* 44EB4 800546B4 00000000 */   nop
  .L800546B8:
    /* 44EB8 800546B8 0C80023C */  lui        $v0, %hi(g_AyaInventoryItems)
    /* 44EBC 800546BC 480E4224 */  addiu      $v0, $v0, %lo(g_AyaInventoryItems)
    /* 44EC0 800546C0 D80282AF */  sw         $v0, %gp_rel(g_InvItemPtr)($gp)
    /* 44EC4 800546C4 DC4B010C */  jal        Inv_GetAyaSlotLimit
    /* 44EC8 800546C8 00000000 */   nop
    /* 44ECC 800546CC E00282AF */  sw         $v0, %gp_rel(g_InvSlotLimit)($gp)
    /* 44ED0 800546D0 0A80023C */  lui        $v0, %hi(D_8009D05C)
    /* 44ED4 800546D4 5CD04224 */  addiu      $v0, $v0, %lo(D_8009D05C)
    /* 44ED8 800546D8 E80282AF */  sw         $v0, %gp_rel(D_8009D058)($gp)
    /* 44EDC 800546DC 02000224 */  addiu      $v0, $zero, 0x2
    /* 44EE0 800546E0 F40282AF */  sw         $v0, %gp_rel(D_8009D064)($gp)
  .L800546E4:
    /* 44EE4 800546E4 E002838F */  lw         $v1, %gp_rel(g_InvSlotLimit)($gp)
    /* 44EE8 800546E8 00000000 */  nop
    /* 44EEC 800546EC 36006018 */  blez       $v1, .L800547C8
    /* 44EF0 800546F0 21800000 */   addu      $s0, $zero, $zero
  .L800546F4:
    /* 44EF4 800546F4 23000006 */  bltz       $s0, .L80054784
    /* 44EF8 800546F8 2A100302 */   slt       $v0, $s0, $v1
    /* 44EFC 800546FC 21004010 */  beqz       $v0, .L80054784
    /* 44F00 80054700 40181000 */   sll       $v1, $s0, 1
    /* 44F04 80054704 D802828F */  lw         $v0, %gp_rel(g_InvItemPtr)($gp)
    /* 44F08 80054708 00000000 */  nop
    /* 44F0C 8005470C 21186200 */  addu       $v1, $v1, $v0
    /* 44F10 80054710 00006384 */  lh         $v1, 0x0($v1)
    /* 44F14 80054714 00000000 */  nop
    /* 44F18 80054718 00FF6224 */  addiu      $v0, $v1, -0x100
    /* 44F1C 8005471C 8000422C */  sltiu      $v0, $v0, 0x80
    /* 44F20 80054720 06004010 */  beqz       $v0, .L8005473C
    /* 44F24 80054724 21286000 */   addu      $a1, $v1, $zero
    /* 44F28 80054728 40190300 */  sll        $v1, $v1, 5
    /* 44F2C 8005472C 0C80023C */  lui        $v0, %hi(D_800BEEAC)
    /* 44F30 80054730 ACEE4224 */  addiu      $v0, $v0, %lo(D_800BEEAC)
    /* 44F34 80054734 DF510108 */  j          .L8005477C
    /* 44F38 80054738 21106200 */   addu      $v0, $v1, $v0
  .L8005473C:
    /* 44F3C 8005473C FFFF6424 */  addiu      $a0, $v1, -0x1
    /* 44F40 80054740 FF00822C */  sltiu      $v0, $a0, 0xFF
    /* 44F44 80054744 05004010 */  beqz       $v0, .L8005475C
    /* 44F48 80054748 00FEA224 */   addiu     $v0, $a1, -0x200
    /* 44F4C 8005474C D176010C */  jal        Item_LookupBaseData
    /* 44F50 80054750 00000000 */   nop
    /* 44F54 80054754 E2510108 */  j          .L80054788
    /* 44F58 80054758 21184000 */   addu      $v1, $v0, $zero
  .L8005475C:
    /* 44F5C 8005475C 0900422C */  sltiu      $v0, $v0, 0x9
    /* 44F60 80054760 05004010 */  beqz       $v0, .L80054778
    /* 44F64 80054764 40190500 */   sll       $v1, $a1, 5
    /* 44F68 80054768 0A80023C */  lui        $v0, %hi(D_8009DE64)
    /* 44F6C 8005476C 64DE4224 */  addiu      $v0, $v0, %lo(D_8009DE64)
    /* 44F70 80054770 DF510108 */  j          .L8005477C
    /* 44F74 80054774 21106200 */   addu      $v0, $v1, $v0
  .L80054778:
    /* 44F78 80054778 21100000 */  addu       $v0, $zero, $zero
  .L8005477C:
    /* 44F7C 8005477C E2510108 */  j          .L80054788
    /* 44F80 80054780 21184000 */   addu      $v1, $v0, $zero
  .L80054784:
    /* 44F84 80054784 21180000 */  addu       $v1, $zero, $zero
  .L80054788:
    /* 44F88 80054788 0A006010 */  beqz       $v1, .L800547B4
    /* 44F8C 8005478C 21200000 */   addu      $a0, $zero, $zero
    /* 44F90 80054790 06006290 */  lbu        $v0, 0x6($v1)
    /* 44F94 80054794 00000000 */  nop
    /* 44F98 80054798 07105200 */  srav       $v0, $s2, $v0
    /* 44F9C 8005479C 01004230 */  andi       $v0, $v0, 0x1
    /* 44FA0 800547A0 04004010 */  beqz       $v0, .L800547B4
    /* 44FA4 800547A4 00000000 */   nop
    /* 44FA8 800547A8 14006290 */  lbu        $v0, 0x14($v1)
    /* 44FAC 800547AC 00000000 */  nop
    /* 44FB0 800547B0 2B200200 */  sltu       $a0, $zero, $v0
  .L800547B4:
    /* 44FB4 800547B4 E002838F */  lw         $v1, %gp_rel(g_InvSlotLimit)($gp)
    /* 44FB8 800547B8 01001026 */  addiu      $s0, $s0, 0x1
    /* 44FBC 800547BC 2A100302 */  slt        $v0, $s0, $v1
    /* 44FC0 800547C0 CCFF4014 */  bnez       $v0, .L800546F4
    /* 44FC4 800547C4 21882402 */   addu      $s1, $s1, $a0
  .L800547C8:
    /* 44FC8 800547C8 0F006012 */  beqz       $s3, .L80054808
    /* 44FCC 800547CC 00000000 */   nop
    /* 44FD0 800547D0 DC02828F */  lw         $v0, %gp_rel(D_8009D04C)($gp)
    /* 44FD4 800547D4 00000000 */  nop
    /* 44FD8 800547D8 0B004010 */  beqz       $v0, .L80054808
    /* 44FDC 800547DC 00000000 */   nop
    /* 44FE0 800547E0 E402838F */  lw         $v1, %gp_rel(D_8009D054)($gp)
    /* 44FE4 800547E4 D80282AF */  sw         $v0, %gp_rel(g_InvItemPtr)($gp)
    /* 44FE8 800547E8 0A80023C */  lui        $v0, %hi(D_800A1F84)
    /* 44FEC 800547EC 841F4224 */  addiu      $v0, $v0, %lo(D_800A1F84)
    /* 44FF0 800547F0 E80282AF */  sw         $v0, %gp_rel(D_8009D058)($gp)
    /* 44FF4 800547F4 04000224 */  addiu      $v0, $zero, 0x4
    /* 44FF8 800547F8 F40282AF */  sw         $v0, %gp_rel(D_8009D064)($gp)
    /* 44FFC 800547FC E00283AF */  sw         $v1, %gp_rel(g_InvSlotLimit)($gp)
    /* 45000 80054800 0E520108 */  j          .L80054838
    /* 45004 80054804 0200222A */   slti      $v0, $s1, 0x2
  .L80054808:
    /* 45008 80054808 0C80023C */  lui        $v0, %hi(g_AyaInventoryItems)
    /* 4500C 8005480C 480E4224 */  addiu      $v0, $v0, %lo(g_AyaInventoryItems)
    /* 45010 80054810 D80282AF */  sw         $v0, %gp_rel(g_InvItemPtr)($gp)
    /* 45014 80054814 DC4B010C */  jal        Inv_GetAyaSlotLimit
    /* 45018 80054818 00000000 */   nop
    /* 4501C 8005481C E00282AF */  sw         $v0, %gp_rel(g_InvSlotLimit)($gp)
    /* 45020 80054820 0A80023C */  lui        $v0, %hi(D_8009D05C)
    /* 45024 80054824 5CD04224 */  addiu      $v0, $v0, %lo(D_8009D05C)
    /* 45028 80054828 E80282AF */  sw         $v0, %gp_rel(D_8009D058)($gp)
    /* 4502C 8005482C 02000224 */  addiu      $v0, $zero, 0x2
    /* 45030 80054830 F40282AF */  sw         $v0, %gp_rel(D_8009D064)($gp)
    /* 45034 80054834 0200222A */  slti       $v0, $s1, 0x2
  .L80054838:
    /* 45038 80054838 01004238 */  xori       $v0, $v0, 0x1
    /* 4503C 8005483C 3000BF8F */  lw         $ra, 0x30($sp)
    /* 45040 80054840 2C00B38F */  lw         $s3, 0x2C($sp)
    /* 45044 80054844 2800B28F */  lw         $s2, 0x28($sp)
    /* 45048 80054848 2400B18F */  lw         $s1, 0x24($sp)
    /* 4504C 8005484C 2000B08F */  lw         $s0, 0x20($sp)
    /* 45050 80054850 3800BD27 */  addiu      $sp, $sp, 0x38
    /* 45054 80054854 0800E003 */  jr         $ra
    /* 45058 80054858 00000000 */   nop
endlabel Inv_SetupSlotDisplay
