.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.4 */

nonmatching Inv_TransferToStorage, 0x1B8

glabel Inv_TransferToStorage
    /* 4D2EC 8005CAEC D8FFBD27 */  addiu      $sp, $sp, -0x28
    /* 4D2F0 8005CAF0 0C80023C */  lui        $v0, %hi(g_AyaInventoryItems)
    /* 4D2F4 8005CAF4 480E4224 */  addiu      $v0, $v0, %lo(g_AyaInventoryItems)
    /* 4D2F8 8005CAF8 2000BFAF */  sw         $ra, 0x20($sp)
    /* 4D2FC 8005CAFC 1C00B1AF */  sw         $s1, 0x1C($sp)
    /* 4D300 8005CB00 1800B0AF */  sw         $s0, 0x18($sp)
    /* 4D304 8005CB04 D80282AF */  sw         $v0, %gp_rel(g_InvItemPtr)($gp)
    /* 4D308 8005CB08 DC4B010C */  jal        Inv_GetAyaSlotLimit
    /* 4D30C 8005CB0C 00000000 */   nop
    /* 4D310 8005CB10 E00282AF */  sw         $v0, %gp_rel(g_InvSlotLimit)($gp)
    /* 4D314 8005CB14 0A80023C */  lui        $v0, %hi(D_8009D05C)
    /* 4D318 8005CB18 5CD04224 */  addiu      $v0, $v0, %lo(D_8009D05C)
    /* 4D31C 8005CB1C E80282AF */  sw         $v0, %gp_rel(D_8009D058)($gp)
    /* 4D320 8005CB20 02000224 */  addiu      $v0, $zero, 0x2
    /* 4D324 8005CB24 F40282AF */  sw         $v0, %gp_rel(D_8009D064)($gp)
    /* 4D328 8005CB28 A850010C */  jal        Inv_BuildFilteredPackedList
    /* 4D32C 8005CB2C FE030424 */   addiu     $a0, $zero, 0x3FE
    /* 4D330 8005CB30 F402858F */  lw         $a1, %gp_rel(D_8009D064)($gp)
    /* 4D334 8005CB34 00000000 */  nop
    /* 4D338 8005CB38 0800A018 */  blez       $a1, .L8005CB5C
    /* 4D33C 8005CB3C 21180000 */   addu      $v1, $zero, $zero
    /* 4D340 8005CB40 E802848F */  lw         $a0, %gp_rel(D_8009D058)($gp)
  .L8005CB44:
    /* 4D344 8005CB44 00000000 */  nop
    /* 4D348 8005CB48 000080AC */  sw         $zero, 0x0($a0)
    /* 4D34C 8005CB4C 01006324 */  addiu      $v1, $v1, 0x1
    /* 4D350 8005CB50 2A106500 */  slt        $v0, $v1, $a1
    /* 4D354 8005CB54 FBFF4014 */  bnez       $v0, .L8005CB44
    /* 4D358 8005CB58 04008424 */   addiu     $a0, $a0, 0x4
  .L8005CB5C:
    /* 4D35C 8005CB5C 21880000 */  addu       $s1, $zero, $zero
    /* 4D360 8005CB60 21800000 */  addu       $s0, $zero, $zero
  .L8005CB64:
    /* 4D364 8005CB64 D002828F */  lw         $v0, %gp_rel(g_InvPackedListCount)($gp)
    /* 4D368 8005CB68 00000000 */  nop
    /* 4D36C 8005CB6C 2A100202 */  slt        $v0, $s0, $v0
    /* 4D370 8005CB70 45004010 */  beqz       $v0, .L8005CC88
    /* 4D374 8005CB74 00000000 */   nop
    /* 4D378 8005CB78 08000006 */  bltz       $s0, .L8005CB9C
    /* 4D37C 8005CB7C 00000000 */   nop
    /* 4D380 8005CB80 06004010 */  beqz       $v0, .L8005CB9C
    /* 4D384 8005CB84 40101000 */   sll       $v0, $s0, 1
    /* 4D388 8005CB88 0A80013C */  lui        $at, %hi(D_800A1D9C)
    /* 4D38C 8005CB8C 21082200 */  addu       $at, $at, $v0
    /* 4D390 8005CB90 9C1D2384 */  lh         $v1, %lo(D_800A1D9C)($at)
    /* 4D394 8005CB94 E8720108 */  j          .L8005CBA0
    /* 4D398 8005CB98 00000000 */   nop
  .L8005CB9C:
    /* 4D39C 8005CB9C 21180000 */  addu       $v1, $zero, $zero
  .L8005CBA0:
    /* 4D3A0 8005CBA0 26006004 */  bltz       $v1, .L8005CC3C
    /* 4D3A4 8005CBA4 00000000 */   nop
    /* 4D3A8 8005CBA8 E002828F */  lw         $v0, %gp_rel(g_InvSlotLimit)($gp)
    /* 4D3AC 8005CBAC 00000000 */  nop
    /* 4D3B0 8005CBB0 2A106200 */  slt        $v0, $v1, $v0
    /* 4D3B4 8005CBB4 21004010 */  beqz       $v0, .L8005CC3C
    /* 4D3B8 8005CBB8 40180300 */   sll       $v1, $v1, 1
    /* 4D3BC 8005CBBC D802828F */  lw         $v0, %gp_rel(g_InvItemPtr)($gp)
    /* 4D3C0 8005CBC0 00000000 */  nop
    /* 4D3C4 8005CBC4 21186200 */  addu       $v1, $v1, $v0
    /* 4D3C8 8005CBC8 00006384 */  lh         $v1, 0x0($v1)
    /* 4D3CC 8005CBCC 00000000 */  nop
    /* 4D3D0 8005CBD0 00FF6224 */  addiu      $v0, $v1, -0x100
    /* 4D3D4 8005CBD4 8000422C */  sltiu      $v0, $v0, 0x80
    /* 4D3D8 8005CBD8 06004010 */  beqz       $v0, .L8005CBF4
    /* 4D3DC 8005CBDC 21286000 */   addu      $a1, $v1, $zero
    /* 4D3E0 8005CBE0 40190300 */  sll        $v1, $v1, 5
    /* 4D3E4 8005CBE4 0C80023C */  lui        $v0, %hi(D_800BEEAC)
    /* 4D3E8 8005CBE8 ACEE4224 */  addiu      $v0, $v0, %lo(D_800BEEAC)
    /* 4D3EC 8005CBEC 0D730108 */  j          .L8005CC34
    /* 4D3F0 8005CBF0 21106200 */   addu      $v0, $v1, $v0
  .L8005CBF4:
    /* 4D3F4 8005CBF4 FFFF6424 */  addiu      $a0, $v1, -0x1
    /* 4D3F8 8005CBF8 FF00822C */  sltiu      $v0, $a0, 0xFF
    /* 4D3FC 8005CBFC 05004010 */  beqz       $v0, .L8005CC14
    /* 4D400 8005CC00 00FEA224 */   addiu     $v0, $a1, -0x200
    /* 4D404 8005CC04 D176010C */  jal        Item_LookupBaseData
    /* 4D408 8005CC08 00000000 */   nop
    /* 4D40C 8005CC0C 10730108 */  j          .L8005CC40
    /* 4D410 8005CC10 21184000 */   addu      $v1, $v0, $zero
  .L8005CC14:
    /* 4D414 8005CC14 0900422C */  sltiu      $v0, $v0, 0x9
    /* 4D418 8005CC18 05004010 */  beqz       $v0, .L8005CC30
    /* 4D41C 8005CC1C 40190500 */   sll       $v1, $a1, 5
    /* 4D420 8005CC20 0A80023C */  lui        $v0, %hi(D_8009DE64)
    /* 4D424 8005CC24 64DE4224 */  addiu      $v0, $v0, %lo(D_8009DE64)
    /* 4D428 8005CC28 0D730108 */  j          .L8005CC34
    /* 4D42C 8005CC2C 21106200 */   addu      $v0, $v1, $v0
  .L8005CC30:
    /* 4D430 8005CC30 21100000 */  addu       $v0, $zero, $zero
  .L8005CC34:
    /* 4D434 8005CC34 10730108 */  j          .L8005CC40
    /* 4D438 8005CC38 21184000 */   addu      $v1, $v0, $zero
  .L8005CC3C:
    /* 4D43C 8005CC3C 21180000 */  addu       $v1, $zero, $zero
  .L8005CC40:
    /* 4D440 8005CC40 14006290 */  lbu        $v0, 0x14($v1)
    /* 4D444 8005CC44 01006390 */  lbu        $v1, 0x1($v1)
    /* 4D448 8005CC48 00000000 */  nop
    /* 4D44C 8005CC4C 2B104300 */  sltu       $v0, $v0, $v1
    /* 4D450 8005CC50 0B004010 */  beqz       $v0, .L8005CC80
    /* 4D454 8005CC54 43211000 */   sra       $a0, $s0, 5
    /* 4D458 8005CC58 01003126 */  addiu      $s1, $s1, 0x1
    /* 4D45C 8005CC5C 80200400 */  sll        $a0, $a0, 2
    /* 4D460 8005CC60 E802828F */  lw         $v0, %gp_rel(D_8009D058)($gp)
    /* 4D464 8005CC64 1F000532 */  andi       $a1, $s0, 0x1F
    /* 4D468 8005CC68 21208200 */  addu       $a0, $a0, $v0
    /* 4D46C 8005CC6C 01000224 */  addiu      $v0, $zero, 0x1
    /* 4D470 8005CC70 0000838C */  lw         $v1, 0x0($a0)
    /* 4D474 8005CC74 0410A200 */  sllv       $v0, $v0, $a1
    /* 4D478 8005CC78 25186200 */  or         $v1, $v1, $v0
    /* 4D47C 8005CC7C 000083AC */  sw         $v1, 0x0($a0)
  .L8005CC80:
    /* 4D480 8005CC80 D9720108 */  j          .L8005CB64
    /* 4D484 8005CC84 01001026 */   addiu     $s0, $s0, 0x1
  .L8005CC88:
    /* 4D488 8005CC88 21102002 */  addu       $v0, $s1, $zero
    /* 4D48C 8005CC8C 2000BF8F */  lw         $ra, 0x20($sp)
    /* 4D490 8005CC90 1C00B18F */  lw         $s1, 0x1C($sp)
    /* 4D494 8005CC94 1800B08F */  lw         $s0, 0x18($sp)
    /* 4D498 8005CC98 2800BD27 */  addiu      $sp, $sp, 0x28
    /* 4D49C 8005CC9C 0800E003 */  jr         $ra
    /* 4D4A0 8005CCA0 00000000 */   nop
endlabel Inv_TransferToStorage
