.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.4 */

nonmatching Inv_BuildDisplayFromList, 0x378

glabel Inv_BuildDisplayFromList
    /* 47440 80056C40 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 47444 80056C44 1000B0AF */  sw         $s0, 0x10($sp)
    /* 47448 80056C48 2180A000 */  addu       $s0, $a1, $zero
    /* 4744C 80056C4C 1800B2AF */  sw         $s2, 0x18($sp)
    /* 47450 80056C50 2190C000 */  addu       $s2, $a2, $zero
    /* 47454 80056C54 1400B1AF */  sw         $s1, 0x14($sp)
    /* 47458 80056C58 2188E000 */  addu       $s1, $a3, $zero
    /* 4745C 80056C5C 0F008010 */  beqz       $a0, .L80056C9C
    /* 47460 80056C60 1C00BFAF */   sw        $ra, 0x1C($sp)
    /* 47464 80056C64 DC02828F */  lw         $v0, %gp_rel(D_8009D04C)($gp)
    /* 47468 80056C68 00000000 */  nop
    /* 4746C 80056C6C 0B004010 */  beqz       $v0, .L80056C9C
    /* 47470 80056C70 00000000 */   nop
    /* 47474 80056C74 E402838F */  lw         $v1, %gp_rel(D_8009D054)($gp)
    /* 47478 80056C78 D80282AF */  sw         $v0, %gp_rel(g_InvItemPtr)($gp)
    /* 4747C 80056C7C 0A80023C */  lui        $v0, %hi(D_800A1F84)
    /* 47480 80056C80 841F4224 */  addiu      $v0, $v0, %lo(D_800A1F84)
    /* 47484 80056C84 E80282AF */  sw         $v0, %gp_rel(D_8009D058)($gp)
    /* 47488 80056C88 04000224 */  addiu      $v0, $zero, 0x4
    /* 4748C 80056C8C F40282AF */  sw         $v0, %gp_rel(D_8009D064)($gp)
    /* 47490 80056C90 E00283AF */  sw         $v1, %gp_rel(g_InvSlotLimit)($gp)
    /* 47494 80056C94 325B0108 */  j          .L80056CC8
    /* 47498 80056C98 00000000 */   nop
  .L80056C9C:
    /* 4749C 80056C9C 0C80023C */  lui        $v0, %hi(g_AyaInventoryItems)
    /* 474A0 80056CA0 480E4224 */  addiu      $v0, $v0, %lo(g_AyaInventoryItems)
    /* 474A4 80056CA4 D80282AF */  sw         $v0, %gp_rel(g_InvItemPtr)($gp)
    /* 474A8 80056CA8 DC4B010C */  jal        Inv_GetAyaSlotLimit
    /* 474AC 80056CAC 00000000 */   nop
    /* 474B0 80056CB0 E00282AF */  sw         $v0, %gp_rel(g_InvSlotLimit)($gp)
    /* 474B4 80056CB4 0A80023C */  lui        $v0, %hi(D_8009D05C)
    /* 474B8 80056CB8 5CD04224 */  addiu      $v0, $v0, %lo(D_8009D05C)
    /* 474BC 80056CBC E80282AF */  sw         $v0, %gp_rel(D_8009D058)($gp)
    /* 474C0 80056CC0 02000224 */  addiu      $v0, $zero, 0x2
    /* 474C4 80056CC4 F40282AF */  sw         $v0, %gp_rel(D_8009D064)($gp)
  .L80056CC8:
    /* 474C8 80056CC8 24000006 */  bltz       $s0, .L80056D5C
    /* 474CC 80056CCC 21100000 */   addu      $v0, $zero, $zero
    /* 474D0 80056CD0 E002828F */  lw         $v0, %gp_rel(g_InvSlotLimit)($gp)
    /* 474D4 80056CD4 00000000 */  nop
    /* 474D8 80056CD8 2A100202 */  slt        $v0, $s0, $v0
    /* 474DC 80056CDC 1E004010 */  beqz       $v0, .L80056D58
    /* 474E0 80056CE0 40181000 */   sll       $v1, $s0, 1
    /* 474E4 80056CE4 D802828F */  lw         $v0, %gp_rel(g_InvItemPtr)($gp)
    /* 474E8 80056CE8 00000000 */  nop
    /* 474EC 80056CEC 21186200 */  addu       $v1, $v1, $v0
    /* 474F0 80056CF0 00006384 */  lh         $v1, 0x0($v1)
    /* 474F4 80056CF4 00000000 */  nop
    /* 474F8 80056CF8 00FF6224 */  addiu      $v0, $v1, -0x100
    /* 474FC 80056CFC 8000422C */  sltiu      $v0, $v0, 0x80
    /* 47500 80056D00 06004010 */  beqz       $v0, .L80056D1C
    /* 47504 80056D04 21286000 */   addu      $a1, $v1, $zero
    /* 47508 80056D08 40190300 */  sll        $v1, $v1, 5
    /* 4750C 80056D0C 0C80023C */  lui        $v0, %hi(D_800BEEAC)
    /* 47510 80056D10 ACEE4224 */  addiu      $v0, $v0, %lo(D_800BEEAC)
    /* 47514 80056D14 575B0108 */  j          .L80056D5C
    /* 47518 80056D18 21106200 */   addu      $v0, $v1, $v0
  .L80056D1C:
    /* 4751C 80056D1C FFFF6424 */  addiu      $a0, $v1, -0x1
    /* 47520 80056D20 FF00822C */  sltiu      $v0, $a0, 0xFF
    /* 47524 80056D24 05004010 */  beqz       $v0, .L80056D3C
    /* 47528 80056D28 00FEA224 */   addiu     $v0, $a1, -0x200
    /* 4752C 80056D2C D176010C */  jal        Item_LookupBaseData
    /* 47530 80056D30 00000000 */   nop
    /* 47534 80056D34 575B0108 */  j          .L80056D5C
    /* 47538 80056D38 00000000 */   nop
  .L80056D3C:
    /* 4753C 80056D3C 0900422C */  sltiu      $v0, $v0, 0x9
    /* 47540 80056D40 05004010 */  beqz       $v0, .L80056D58
    /* 47544 80056D44 40190500 */   sll       $v1, $a1, 5
    /* 47548 80056D48 0A80023C */  lui        $v0, %hi(D_8009DE64)
    /* 4754C 80056D4C 64DE4224 */  addiu      $v0, $v0, %lo(D_8009DE64)
    /* 47550 80056D50 575B0108 */  j          .L80056D5C
    /* 47554 80056D54 21106200 */   addu      $v0, $v1, $v0
  .L80056D58:
    /* 47558 80056D58 21100000 */  addu       $v0, $zero, $zero
  .L80056D5C:
    /* 4755C 80056D5C 000382AF */  sw         $v0, %gp_rel(D_8009D070)($gp)
    /* 47560 80056D60 0F004012 */  beqz       $s2, .L80056DA0
    /* 47564 80056D64 00000000 */   nop
    /* 47568 80056D68 DC02828F */  lw         $v0, %gp_rel(D_8009D04C)($gp)
    /* 4756C 80056D6C 00000000 */  nop
    /* 47570 80056D70 0B004010 */  beqz       $v0, .L80056DA0
    /* 47574 80056D74 00000000 */   nop
    /* 47578 80056D78 E402838F */  lw         $v1, %gp_rel(D_8009D054)($gp)
    /* 4757C 80056D7C D80282AF */  sw         $v0, %gp_rel(g_InvItemPtr)($gp)
    /* 47580 80056D80 0A80023C */  lui        $v0, %hi(D_800A1F84)
    /* 47584 80056D84 841F4224 */  addiu      $v0, $v0, %lo(D_800A1F84)
    /* 47588 80056D88 E80282AF */  sw         $v0, %gp_rel(D_8009D058)($gp)
    /* 4758C 80056D8C 04000224 */  addiu      $v0, $zero, 0x4
    /* 47590 80056D90 F40282AF */  sw         $v0, %gp_rel(D_8009D064)($gp)
    /* 47594 80056D94 E00283AF */  sw         $v1, %gp_rel(g_InvSlotLimit)($gp)
    /* 47598 80056D98 735B0108 */  j          .L80056DCC
    /* 4759C 80056D9C 00000000 */   nop
  .L80056DA0:
    /* 475A0 80056DA0 0C80023C */  lui        $v0, %hi(g_AyaInventoryItems)
    /* 475A4 80056DA4 480E4224 */  addiu      $v0, $v0, %lo(g_AyaInventoryItems)
    /* 475A8 80056DA8 D80282AF */  sw         $v0, %gp_rel(g_InvItemPtr)($gp)
    /* 475AC 80056DAC DC4B010C */  jal        Inv_GetAyaSlotLimit
    /* 475B0 80056DB0 00000000 */   nop
    /* 475B4 80056DB4 E00282AF */  sw         $v0, %gp_rel(g_InvSlotLimit)($gp)
    /* 475B8 80056DB8 0A80023C */  lui        $v0, %hi(D_8009D05C)
    /* 475BC 80056DBC 5CD04224 */  addiu      $v0, $v0, %lo(D_8009D05C)
    /* 475C0 80056DC0 E80282AF */  sw         $v0, %gp_rel(D_8009D058)($gp)
    /* 475C4 80056DC4 02000224 */  addiu      $v0, $zero, 0x2
    /* 475C8 80056DC8 F40282AF */  sw         $v0, %gp_rel(D_8009D064)($gp)
  .L80056DCC:
    /* 475CC 80056DCC 24002006 */  bltz       $s1, .L80056E60
    /* 475D0 80056DD0 21100000 */   addu      $v0, $zero, $zero
    /* 475D4 80056DD4 E002828F */  lw         $v0, %gp_rel(g_InvSlotLimit)($gp)
    /* 475D8 80056DD8 00000000 */  nop
    /* 475DC 80056DDC 2A102202 */  slt        $v0, $s1, $v0
    /* 475E0 80056DE0 1E004010 */  beqz       $v0, .L80056E5C
    /* 475E4 80056DE4 40181100 */   sll       $v1, $s1, 1
    /* 475E8 80056DE8 D802828F */  lw         $v0, %gp_rel(g_InvItemPtr)($gp)
    /* 475EC 80056DEC 00000000 */  nop
    /* 475F0 80056DF0 21186200 */  addu       $v1, $v1, $v0
    /* 475F4 80056DF4 00006384 */  lh         $v1, 0x0($v1)
    /* 475F8 80056DF8 00000000 */  nop
    /* 475FC 80056DFC 00FF6224 */  addiu      $v0, $v1, -0x100
    /* 47600 80056E00 8000422C */  sltiu      $v0, $v0, 0x80
    /* 47604 80056E04 06004010 */  beqz       $v0, .L80056E20
    /* 47608 80056E08 21286000 */   addu      $a1, $v1, $zero
    /* 4760C 80056E0C 40190300 */  sll        $v1, $v1, 5
    /* 47610 80056E10 0C80023C */  lui        $v0, %hi(D_800BEEAC)
    /* 47614 80056E14 ACEE4224 */  addiu      $v0, $v0, %lo(D_800BEEAC)
    /* 47618 80056E18 985B0108 */  j          .L80056E60
    /* 4761C 80056E1C 21106200 */   addu      $v0, $v1, $v0
  .L80056E20:
    /* 47620 80056E20 FFFF6424 */  addiu      $a0, $v1, -0x1
    /* 47624 80056E24 FF00822C */  sltiu      $v0, $a0, 0xFF
    /* 47628 80056E28 05004010 */  beqz       $v0, .L80056E40
    /* 4762C 80056E2C 00FEA224 */   addiu     $v0, $a1, -0x200
    /* 47630 80056E30 D176010C */  jal        Item_LookupBaseData
    /* 47634 80056E34 00000000 */   nop
    /* 47638 80056E38 985B0108 */  j          .L80056E60
    /* 4763C 80056E3C 00000000 */   nop
  .L80056E40:
    /* 47640 80056E40 0900422C */  sltiu      $v0, $v0, 0x9
    /* 47644 80056E44 05004010 */  beqz       $v0, .L80056E5C
    /* 47648 80056E48 40190500 */   sll       $v1, $a1, 5
    /* 4764C 80056E4C 0A80023C */  lui        $v0, %hi(D_8009DE64)
    /* 47650 80056E50 64DE4224 */  addiu      $v0, $v0, %lo(D_8009DE64)
    /* 47654 80056E54 985B0108 */  j          .L80056E60
    /* 47658 80056E58 21106200 */   addu      $v0, $v1, $v0
  .L80056E5C:
    /* 4765C 80056E5C 21100000 */  addu       $v0, $zero, $zero
  .L80056E60:
    /* 47660 80056E60 040382AF */  sw         $v0, %gp_rel(D_8009D074)($gp)
    /* 47664 80056E64 0003828F */  lw         $v0, %gp_rel(D_8009D070)($gp)
    /* 47668 80056E68 0403838F */  lw         $v1, %gp_rel(D_8009D074)($gp)
    /* 4766C 80056E6C 0A80073C */  lui        $a3, %hi(D_800A1F94)
    /* 47670 80056E70 941FE724 */  addiu      $a3, $a3, %lo(D_800A1F94)
    /* 47674 80056E74 03004488 */  lwl        $a0, 0x3($v0)
    /* 47678 80056E78 00004498 */  lwr        $a0, 0x0($v0)
    /* 4767C 80056E7C 07004588 */  lwl        $a1, 0x7($v0)
    /* 47680 80056E80 04004598 */  lwr        $a1, 0x4($v0)
    /* 47684 80056E84 0B004688 */  lwl        $a2, 0xB($v0)
    /* 47688 80056E88 08004698 */  lwr        $a2, 0x8($v0)
    /* 4768C 80056E8C 0300E4A8 */  swl        $a0, 0x3($a3)
    /* 47690 80056E90 0000E4B8 */  swr        $a0, 0x0($a3)
    /* 47694 80056E94 0700E5A8 */  swl        $a1, 0x7($a3)
    /* 47698 80056E98 0400E5B8 */  swr        $a1, 0x4($a3)
    /* 4769C 80056E9C 0B00E6A8 */  swl        $a2, 0xB($a3)
    /* 476A0 80056EA0 0800E6B8 */  swr        $a2, 0x8($a3)
    /* 476A4 80056EA4 0F004488 */  lwl        $a0, 0xF($v0)
    /* 476A8 80056EA8 0C004498 */  lwr        $a0, 0xC($v0)
    /* 476AC 80056EAC 13004588 */  lwl        $a1, 0x13($v0)
    /* 476B0 80056EB0 10004598 */  lwr        $a1, 0x10($v0)
    /* 476B4 80056EB4 17004688 */  lwl        $a2, 0x17($v0)
    /* 476B8 80056EB8 14004698 */  lwr        $a2, 0x14($v0)
    /* 476BC 80056EBC 0F00E4A8 */  swl        $a0, 0xF($a3)
    /* 476C0 80056EC0 0C00E4B8 */  swr        $a0, 0xC($a3)
    /* 476C4 80056EC4 1300E5A8 */  swl        $a1, 0x13($a3)
    /* 476C8 80056EC8 1000E5B8 */  swr        $a1, 0x10($a3)
    /* 476CC 80056ECC 1700E6A8 */  swl        $a2, 0x17($a3)
    /* 476D0 80056ED0 1400E6B8 */  swr        $a2, 0x14($a3)
    /* 476D4 80056ED4 1B004488 */  lwl        $a0, 0x1B($v0)
    /* 476D8 80056ED8 18004498 */  lwr        $a0, 0x18($v0)
    /* 476DC 80056EDC 1F004588 */  lwl        $a1, 0x1F($v0)
    /* 476E0 80056EE0 1C004598 */  lwr        $a1, 0x1C($v0)
    /* 476E4 80056EE4 1B00E4A8 */  swl        $a0, 0x1B($a3)
    /* 476E8 80056EE8 1800E4B8 */  swr        $a0, 0x18($a3)
    /* 476EC 80056EEC 1F00E5A8 */  swl        $a1, 0x1F($a3)
    /* 476F0 80056EF0 1C00E5B8 */  swr        $a1, 0x1C($a3)
    /* 476F4 80056EF4 0A80063C */  lui        $a2, %hi(D_800A1FB4)
    /* 476F8 80056EF8 B41FC624 */  addiu      $a2, $a2, %lo(D_800A1FB4)
    /* 476FC 80056EFC 03006288 */  lwl        $v0, 0x3($v1)
    /* 47700 80056F00 00006298 */  lwr        $v0, 0x0($v1)
    /* 47704 80056F04 07006488 */  lwl        $a0, 0x7($v1)
    /* 47708 80056F08 04006498 */  lwr        $a0, 0x4($v1)
    /* 4770C 80056F0C 0B006588 */  lwl        $a1, 0xB($v1)
    /* 47710 80056F10 08006598 */  lwr        $a1, 0x8($v1)
    /* 47714 80056F14 0300C2A8 */  swl        $v0, 0x3($a2)
    /* 47718 80056F18 0000C2B8 */  swr        $v0, 0x0($a2)
    /* 4771C 80056F1C 0700C4A8 */  swl        $a0, 0x7($a2)
    /* 47720 80056F20 0400C4B8 */  swr        $a0, 0x4($a2)
    /* 47724 80056F24 0B00C5A8 */  swl        $a1, 0xB($a2)
    /* 47728 80056F28 0800C5B8 */  swr        $a1, 0x8($a2)
    /* 4772C 80056F2C 0F006288 */  lwl        $v0, 0xF($v1)
    /* 47730 80056F30 0C006298 */  lwr        $v0, 0xC($v1)
    /* 47734 80056F34 13006488 */  lwl        $a0, 0x13($v1)
    /* 47738 80056F38 10006498 */  lwr        $a0, 0x10($v1)
    /* 4773C 80056F3C 17006588 */  lwl        $a1, 0x17($v1)
    /* 47740 80056F40 14006598 */  lwr        $a1, 0x14($v1)
    /* 47744 80056F44 0F00C2A8 */  swl        $v0, 0xF($a2)
    /* 47748 80056F48 0C00C2B8 */  swr        $v0, 0xC($a2)
    /* 4774C 80056F4C 1300C4A8 */  swl        $a0, 0x13($a2)
    /* 47750 80056F50 1000C4B8 */  swr        $a0, 0x10($a2)
    /* 47754 80056F54 1700C5A8 */  swl        $a1, 0x17($a2)
    /* 47758 80056F58 1400C5B8 */  swr        $a1, 0x14($a2)
    /* 4775C 80056F5C 1B006288 */  lwl        $v0, 0x1B($v1)
    /* 47760 80056F60 18006298 */  lwr        $v0, 0x18($v1)
    /* 47764 80056F64 1F006488 */  lwl        $a0, 0x1F($v1)
    /* 47768 80056F68 1C006498 */  lwr        $a0, 0x1C($v1)
    /* 4776C 80056F6C 1B00C2A8 */  swl        $v0, 0x1B($a2)
    /* 47770 80056F70 1800C2B8 */  swr        $v0, 0x18($a2)
    /* 47774 80056F74 1F00C4A8 */  swl        $a0, 0x1F($a2)
    /* 47778 80056F78 1C00C4B8 */  swr        $a0, 0x1C($a2)
    /* 4777C 80056F7C 0A80013C */  lui        $at, %hi(D_800A1FD3)
    /* 47780 80056F80 D31F20A0 */  sb         $zero, %lo(D_800A1FD3)($at)
    /* 47784 80056F84 0A80013C */  lui        $at, %hi(D_800A1FB3)
    /* 47788 80056F88 B31F20A0 */  sb         $zero, %lo(D_800A1FB3)($at)
    /* 4778C 80056F8C 0A80013C */  lui        $at, %hi(D_800A1FC0)
    /* 47790 80056F90 C01F20A4 */  sh         $zero, %lo(D_800A1FC0)($at)
    /* 47794 80056F94 0A80013C */  lui        $at, %hi(D_800A1FA0)
    /* 47798 80056F98 A01F20A4 */  sh         $zero, %lo(D_800A1FA0)($at)
    /* 4779C 80056F9C 1C00BF8F */  lw         $ra, 0x1C($sp)
    /* 477A0 80056FA0 1800B28F */  lw         $s2, 0x18($sp)
    /* 477A4 80056FA4 1400B18F */  lw         $s1, 0x14($sp)
    /* 477A8 80056FA8 1000B08F */  lw         $s0, 0x10($sp)
    /* 477AC 80056FAC 2000BD27 */  addiu      $sp, $sp, 0x20
    /* 477B0 80056FB0 0800E003 */  jr         $ra
    /* 477B4 80056FB4 00000000 */   nop
endlabel Inv_BuildDisplayFromList
