.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.4 */

nonmatching Menu_StepInventoryRoot, 0x60C

glabel Menu_StepInventoryRoot
    /* 39118 80048918 C8FFBD27 */  addiu      $sp, $sp, -0x38
    /* 3911C 8004891C 2C00B7AF */  sw         $s7, 0x2C($sp)
    /* 39120 80048920 21B88000 */  addu       $s7, $a0, $zero
    /* 39124 80048924 1000B0AF */  sw         $s0, 0x10($sp)
    /* 39128 80048928 2180A000 */  addu       $s0, $a1, $zero
    /* 3912C 8004892C 1800B2AF */  sw         $s2, 0x18($sp)
    /* 39130 80048930 2190C000 */  addu       $s2, $a2, $zero
    /* 39134 80048934 21200002 */  addu       $a0, $s0, $zero
    /* 39138 80048938 3000BFAF */  sw         $ra, 0x30($sp)
    /* 3913C 8004893C 2800B6AF */  sw         $s6, 0x28($sp)
    /* 39140 80048940 2400B5AF */  sw         $s5, 0x24($sp)
    /* 39144 80048944 2000B4AF */  sw         $s4, 0x20($sp)
    /* 39148 80048948 1C00B3AF */  sw         $s3, 0x1C($sp)
    /* 3914C 8004894C CB4C010C */  jal        Inv_LookupActiveListData
    /* 39150 80048950 1400B1AF */   sw        $s1, 0x14($sp)
    /* 39154 80048954 9C01838F */  lw         $v1, %gp_rel(g_MenuEquipMode)($gp)
    /* 39158 80048958 00000000 */  nop
    /* 3915C 8004895C 1C006010 */  beqz       $v1, .L800489D0
    /* 39160 80048960 21B04000 */   addu      $s6, $v0, $zero
    /* 39164 80048964 318B010C */  jal        MenuWidget_GetCurrentNode
    /* 39168 80048968 00000000 */   nop
    /* 3916C 8004896C 36000424 */  addiu      $a0, $zero, 0x36
    /* 39170 80048970 21284000 */  addu       $a1, $v0, $zero
    /* 39174 80048974 21300000 */  addu       $a2, $zero, $zero
    /* 39178 80048978 4B8B010C */  jal        MenuWidget_CreateSimpleNode
    /* 3917C 8004897C 21380000 */   addu      $a3, $zero, $zero
    /* 39180 80048980 21884000 */  addu       $s1, $v0, $zero
    /* 39184 80048984 36000424 */  addiu      $a0, $zero, 0x36
    /* 39188 80048988 21282002 */  addu       $a1, $s1, $zero
    /* 3918C 8004898C 8B8C010C */  jal        MenuWidget_CreateNode
    /* 39190 80048990 21302002 */   addu      $a2, $s1, $zero
    /* 39194 80048994 21A04000 */  addu       $s4, $v0, $zero
    /* 39198 80048998 C001838F */  lw         $v1, %gp_rel(D_8009CF30)($gp)
    /* 3919C 8004899C 0580023C */  lui        $v0, %hi(Menu_InventoryPageNavHandler)
    /* 391A0 800489A0 58EF4224 */  addiu      $v0, $v0, %lo(Menu_InventoryPageNavHandler)
    /* 391A4 800489A4 05006010 */  beqz       $v1, .L800489BC
    /* 391A8 800489A8 2C0022AE */   sw        $v0, 0x2C($s1)
    /* 391AC 800489AC 21202002 */  addu       $a0, $s1, $zero
    /* 391B0 800489B0 21280000 */  addu       $a1, $zero, $zero
    /* 391B4 800489B4 568C010C */  jal        MenuWidget_OffsetPosition
    /* 391B8 800489B8 14000624 */   addiu     $a2, $zero, 0x14
  .L800489BC:
    /* 391BC 800489BC 0580023C */  lui        $v0, %hi(Menu_DrawBattleCommandList)
    /* 391C0 800489C0 30EF4224 */  addiu      $v0, $v0, %lo(Menu_DrawBattleCommandList)
    /* 391C4 800489C4 300082AE */  sw         $v0, 0x30($s4)
    /* 391C8 800489C8 2E8B010C */  jal        MenuWidget_SetCurrentNode
    /* 391CC 800489CC 21208002 */   addu      $a0, $s4, $zero
  .L800489D0:
    /* 391D0 800489D0 318B010C */  jal        MenuWidget_GetCurrentNode
    /* 391D4 800489D4 00000000 */   nop
    /* 391D8 800489D8 0D000424 */  addiu      $a0, $zero, 0xD
    /* 391DC 800489DC 21284000 */  addu       $a1, $v0, $zero
    /* 391E0 800489E0 21300000 */  addu       $a2, $zero, $zero
    /* 391E4 800489E4 4B8B010C */  jal        MenuWidget_CreateSimpleNode
    /* 391E8 800489E8 21380000 */   addu      $a3, $zero, $zero
    /* 391EC 800489EC 21884000 */  addu       $s1, $v0, $zero
    /* 391F0 800489F0 C001828F */  lw         $v0, %gp_rel(D_8009CF30)($gp)
    /* 391F4 800489F4 00000000 */  nop
    /* 391F8 800489F8 02004010 */  beqz       $v0, .L80048A04
    /* 391FC 800489FC 0D000424 */   addiu     $a0, $zero, 0xD
    /* 39200 80048A00 10000424 */  addiu      $a0, $zero, 0x10
  .L80048A04:
    /* 39204 80048A04 21282002 */  addu       $a1, $s1, $zero
    /* 39208 80048A08 8B8C010C */  jal        MenuWidget_CreateNode
    /* 3920C 80048A0C 21302002 */   addu      $a2, $s1, $zero
    /* 39210 80048A10 21A04000 */  addu       $s4, $v0, $zero
    /* 39214 80048A14 AC01838F */  lw         $v1, %gp_rel(D_8009CF1C)($gp)
    /* 39218 80048A18 0580023C */  lui        $v0, %hi(Menu_ItemListInputHandler)
    /* 3921C 80048A1C AC944224 */  addiu      $v0, $v0, %lo(Menu_ItemListInputHandler)
    /* 39220 80048A20 2C0022AE */  sw         $v0, 0x2C($s1)
    /* 39224 80048A24 01000224 */  addiu      $v0, $zero, 0x1
    /* 39228 80048A28 400022AE */  sw         $v0, 0x40($s1)
    /* 3922C 80048A2C 0580023C */  lui        $v0, %hi(Menu_DrawEquipSelectionList)
    /* 39230 80048A30 48FB4224 */  addiu      $v0, $v0, %lo(Menu_DrawEquipSelectionList)
    /* 39234 80048A34 0B006010 */  beqz       $v1, .L80048A64
    /* 39238 80048A38 300082AE */   sw        $v0, 0x30($s4)
    /* 3923C 80048A3C 21208002 */  addu       $a0, $s4, $zero
    /* 39240 80048A40 DD92010C */  jal        MenuWidget_SetColumnLayout
    /* 39244 80048A44 15000524 */   addiu     $a1, $zero, 0x15
    /* 39248 80048A48 4400828E */  lw         $v0, 0x44($s4)
    /* 3924C 80048A4C 00000000 */  nop
    /* 39250 80048A50 02004104 */  bgez       $v0, .L80048A5C
    /* 39254 80048A54 00000000 */   nop
    /* 39258 80048A58 440080AE */  sw         $zero, 0x44($s4)
  .L80048A5C:
    /* 3925C 80048A5C 4C8F010C */  jal        MenuWidget_ClampScroll
    /* 39260 80048A60 21208002 */   addu      $a0, $s4, $zero
  .L80048A64:
    /* 39264 80048A64 9C01828F */  lw         $v0, %gp_rel(g_MenuEquipMode)($gp)
    /* 39268 80048A68 00000000 */  nop
    /* 3926C 80048A6C 0B004010 */  beqz       $v0, .L80048A9C
    /* 39270 80048A70 00000000 */   nop
    /* 39274 80048A74 C001828F */  lw         $v0, %gp_rel(D_8009CF30)($gp)
    /* 39278 80048A78 00000000 */  nop
    /* 3927C 80048A7C 02004010 */  beqz       $v0, .L80048A88
    /* 39280 80048A80 14000624 */   addiu     $a2, $zero, 0x14
    /* 39284 80048A84 F0FF0624 */  addiu      $a2, $zero, -0x10
  .L80048A88:
    /* 39288 80048A88 21202002 */  addu       $a0, $s1, $zero
    /* 3928C 80048A8C 568C010C */  jal        MenuWidget_OffsetPosition
    /* 39290 80048A90 21280000 */   addu      $a1, $zero, $zero
    /* 39294 80048A94 FFFF0224 */  addiu      $v0, $zero, -0x1
    /* 39298 80048A98 440082AE */  sw         $v0, 0x44($s4)
  .L80048A9C:
    /* 3929C 80048A9C C34B010C */  jal        Inv_IsActiveListOverrideSelected
    /* 392A0 80048AA0 00000000 */   nop
    /* 392A4 80048AA4 640282AF */  sw         $v0, %gp_rel(D_8009CFD4)($gp)
    /* 392A8 80048AA8 8C4B010C */  jal        Inv_SelectActiveList
    /* 392AC 80048AAC 21200000 */   addu      $a0, $zero, $zero
    /* 392B0 80048AB0 FEFF0324 */  addiu      $v1, $zero, -0x2
    /* 392B4 80048AB4 26180302 */  xor        $v1, $s0, $v1
    /* 392B8 80048AB8 0100632C */  sltiu      $v1, $v1, 0x1
    /* 392BC 80048ABC FDFF0224 */  addiu      $v0, $zero, -0x3
    /* 392C0 80048AC0 26100202 */  xor        $v0, $s0, $v0
    /* 392C4 80048AC4 0100422C */  sltiu      $v0, $v0, 0x1
    /* 392C8 80048AC8 540290AF */  sw         $s0, %gp_rel(D_8009CFC4)($gp)
    /* 392CC 80048ACC C40183AF */  sw         $v1, %gp_rel(D_8009CF34)($gp)
    /* 392D0 80048AD0 C80182AF */  sw         $v0, %gp_rel(D_8009CF38)($gp)
    /* 392D4 80048AD4 04006010 */  beqz       $v1, .L80048AE8
    /* 392D8 80048AD8 00000000 */   nop
    /* 392DC 80048ADC 0893010C */  jal        MenuWidget_ClearColumnLayout
    /* 392E0 80048AE0 21208002 */   addu      $a0, $s4, $zero
    /* 392E4 80048AE4 440080AE */  sw         $zero, 0x44($s4)
  .L80048AE8:
    /* 392E8 80048AE8 AC01828F */  lw         $v0, %gp_rel(D_8009CF1C)($gp)
    /* 392EC 80048AEC 00000000 */  nop
    /* 392F0 80048AF0 05004010 */  beqz       $v0, .L80048B08
    /* 392F4 80048AF4 2120E002 */   addu      $a0, $s7, $zero
    /* 392F8 80048AF8 F350010C */  jal        Inv_BuildFilteredPackedListExcluding
    /* 392FC 80048AFC FFFF0524 */   addiu     $a1, $zero, -0x1
    /* 39300 80048B00 CC220108 */  j          .L80048B30
    /* 39304 80048B04 00000000 */   nop
  .L80048B08:
    /* 39308 80048B08 C401828F */  lw         $v0, %gp_rel(D_8009CF34)($gp)
    /* 3930C 80048B0C 00000000 */  nop
    /* 39310 80048B10 07004014 */  bnez       $v0, .L80048B30
    /* 39314 80048B14 00000000 */   nop
    /* 39318 80048B18 C801828F */  lw         $v0, %gp_rel(D_8009CF38)($gp)
    /* 3931C 80048B1C 00000000 */  nop
    /* 39320 80048B20 03004014 */  bnez       $v0, .L80048B30
    /* 39324 80048B24 00000000 */   nop
    /* 39328 80048B28 A850010C */  jal        Inv_BuildFilteredPackedList
    /* 3932C 80048B2C 2120E002 */   addu      $a0, $s7, $zero
  .L80048B30:
    /* 39330 80048B30 A250010C */  jal        Inv_GetPackedListCount
    /* 39334 80048B34 00000000 */   nop
    /* 39338 80048B38 21208002 */  addu       $a0, $s4, $zero
    /* 3933C 80048B3C F491010C */  jal        Draw_SetPrimCallback
    /* 39340 80048B40 21284000 */   addu      $a1, $v0, $zero
    /* 39344 80048B44 14004006 */  bltz       $s2, .L80048B98
    /* 39348 80048B48 21800000 */   addu      $s0, $zero, $zero
  .L80048B4C:
    /* 3934C 80048B4C A250010C */  jal        Inv_GetPackedListCount
    /* 39350 80048B50 00000000 */   nop
    /* 39354 80048B54 2A100202 */  slt        $v0, $s0, $v0
    /* 39358 80048B58 07004010 */  beqz       $v0, .L80048B78
    /* 3935C 80048B5C 00000000 */   nop
    /* 39360 80048B60 BA55010C */  jal        Inv_GetPackedListItem
    /* 39364 80048B64 21200002 */   addu      $a0, $s0, $zero
    /* 39368 80048B68 03005210 */  beq        $v0, $s2, .L80048B78
    /* 3936C 80048B6C 00000000 */   nop
    /* 39370 80048B70 D3220108 */  j          .L80048B4C
    /* 39374 80048B74 01001026 */   addiu     $s0, $s0, 0x1
  .L80048B78:
    /* 39378 80048B78 A250010C */  jal        Inv_GetPackedListCount
    /* 3937C 80048B7C 00000000 */   nop
    /* 39380 80048B80 2A100202 */  slt        $v0, $s0, $v0
    /* 39384 80048B84 04004010 */  beqz       $v0, .L80048B98
    /* 39388 80048B88 00000000 */   nop
    /* 3938C 80048B8C 480090AE */  sw         $s0, 0x48($s4)
    /* 39390 80048B90 4C8F010C */  jal        MenuWidget_ClampScroll
    /* 39394 80048B94 21208002 */   addu      $a0, $s4, $zero
  .L80048B98:
    /* 39398 80048B98 4400828E */  lw         $v0, 0x44($s4)
    /* 3939C 80048B9C 00000000 */  nop
    /* 393A0 80048BA0 07004004 */  bltz       $v0, .L80048BC0
    /* 393A4 80048BA4 00000000 */   nop
    /* 393A8 80048BA8 9C01828F */  lw         $v0, %gp_rel(g_MenuEquipMode)($gp)
    /* 393AC 80048BAC 00000000 */  nop
    /* 393B0 80048BB0 03004014 */  bnez       $v0, .L80048BC0
    /* 393B4 80048BB4 00000000 */   nop
    /* 393B8 80048BB8 2E8B010C */  jal        MenuWidget_SetCurrentNode
    /* 393BC 80048BBC 21208002 */   addu      $a0, $s4, $zero
  .L80048BC0:
    /* 393C0 80048BC0 C001828F */  lw         $v0, %gp_rel(D_8009CF30)($gp)
    /* 393C4 80048BC4 00000000 */  nop
    /* 393C8 80048BC8 5F004010 */  beqz       $v0, .L80048D48
    /* 393CC 80048BCC 21280000 */   addu      $a1, $zero, $zero
    /* 393D0 80048BD0 21202002 */  addu       $a0, $s1, $zero
    /* 393D4 80048BD4 568C010C */  jal        MenuWidget_OffsetPosition
    /* 393D8 80048BD8 38000624 */   addiu     $a2, $zero, 0x38
    /* 393DC 80048BDC 18000424 */  addiu      $a0, $zero, 0x18
    /* 393E0 80048BE0 21280000 */  addu       $a1, $zero, $zero
    /* 393E4 80048BE4 21300000 */  addu       $a2, $zero, $zero
    /* 393E8 80048BE8 3800228E */  lw         $v0, 0x38($s1)
    /* 393EC 80048BEC 21380000 */  addu       $a3, $zero, $zero
    /* 393F0 80048BF0 D0FF4224 */  addiu      $v0, $v0, -0x30
    /* 393F4 80048BF4 4B8B010C */  jal        MenuWidget_CreateSimpleNode
    /* 393F8 80048BF8 380022AE */   sw        $v0, 0x38($s1)
    /* 393FC 80048BFC 21884000 */  addu       $s1, $v0, $zero
    /* 39400 80048C00 21202002 */  addu       $a0, $s1, $zero
    /* 39404 80048C04 78FF0524 */  addiu      $a1, $zero, -0x88
    /* 39408 80048C08 21300000 */  addu       $a2, $zero, $zero
    /* 3940C 80048C0C 3400828C */  lw         $v0, 0x34($a0)
    /* 39410 80048C10 0580033C */  lui        $v1, %hi(Menu_DrawBonusPointSlotValue)
    /* 39414 80048C14 5C906324 */  addiu      $v1, $v1, %lo(Menu_DrawBonusPointSlotValue)
    /* 39418 80048C18 300083AC */  sw         $v1, 0x30($a0)
    /* 3941C 80048C1C 14004224 */  addiu      $v0, $v0, 0x14
    /* 39420 80048C20 568C010C */  jal        MenuWidget_OffsetPosition
    /* 39424 80048C24 340082AC */   sw        $v0, 0x34($a0)
    /* 39428 80048C28 9C01828F */  lw         $v0, %gp_rel(g_MenuEquipMode)($gp)
    /* 3942C 80048C2C 00000000 */  nop
    /* 39430 80048C30 1F004014 */  bnez       $v0, .L80048CB0
    /* 39434 80048C34 02000424 */   addiu     $a0, $zero, 0x2
    /* 39438 80048C38 4400908E */  lw         $s0, 0x44($s4)
    /* 3943C 80048C3C 21280000 */  addu       $a1, $zero, $zero
    /* 39440 80048C40 8D8A010C */  jal        MenuWidget_FindByModeAndSelectedBase
    /* 39444 80048C44 C2871000 */   srl       $s0, $s0, 31
    /* 39448 80048C48 30000424 */  addiu      $a0, $zero, 0x30
    /* 3944C 80048C4C 21284000 */  addu       $a1, $v0, $zero
    /* 39450 80048C50 21300000 */  addu       $a2, $zero, $zero
    /* 39454 80048C54 4B8B010C */  jal        MenuWidget_CreateSimpleNode
    /* 39458 80048C58 21380000 */   addu      $a3, $zero, $zero
    /* 3945C 80048C5C 21884000 */  addu       $s1, $v0, $zero
    /* 39460 80048C60 30000424 */  addiu      $a0, $zero, 0x30
    /* 39464 80048C64 21282002 */  addu       $a1, $s1, $zero
    /* 39468 80048C68 8B8C010C */  jal        MenuWidget_CreateNode
    /* 3946C 80048C6C 21302002 */   addu      $a2, $s1, $zero
    /* 39470 80048C70 21A04000 */  addu       $s4, $v0, $zero
    /* 39474 80048C74 0580023C */  lui        $v0, %hi(Menu_StatSlotInputHandler)
    /* 39478 80048C78 C8914224 */  addiu      $v0, $v0, %lo(Menu_StatSlotInputHandler)
    /* 3947C 80048C7C 2C0022AE */  sw         $v0, 0x2C($s1)
    /* 39480 80048C80 0580023C */  lui        $v0, %hi(Menu_DrawParasiteAbilityList)
    /* 39484 80048C84 60004224 */  addiu      $v0, $v0, %lo(Menu_DrawParasiteAbilityList)
    /* 39488 80048C88 03000012 */  beqz       $s0, .L80048C98
    /* 3948C 80048C8C 300082AE */   sw        $v0, 0x30($s4)
    /* 39490 80048C90 480080AE */  sw         $zero, 0x48($s4)
    /* 39494 80048C94 440080AE */  sw         $zero, 0x44($s4)
  .L80048C98:
    /* 39498 80048C98 4400828E */  lw         $v0, 0x44($s4)
    /* 3949C 80048C9C 00000000 */  nop
    /* 394A0 80048CA0 03004004 */  bltz       $v0, .L80048CB0
    /* 394A4 80048CA4 00000000 */   nop
    /* 394A8 80048CA8 2E8B010C */  jal        MenuWidget_SetCurrentNode
    /* 394AC 80048CAC 21208002 */   addu      $a0, $s4, $zero
  .L80048CB0:
    /* 394B0 80048CB0 0C80153C */  lui        $s5, %hi(g_AyaStatAgility)
    /* 394B4 80048CB4 280EB526 */  addiu      $s5, $s5, %lo(g_AyaStatAgility)
    /* 394B8 80048CB8 21880000 */  addu       $s1, $zero, $zero
    /* 394BC 80048CBC 0A80103C */  lui        $s0, %hi(D_800A18D8)
    /* 394C0 80048CC0 D8181026 */  addiu      $s0, $s0, %lo(D_800A18D8)
    /* 394C4 80048CC4 0A80133C */  lui        $s3, %hi(D_800A18B4)
    /* 394C8 80048CC8 B4187326 */  addiu      $s3, $s3, %lo(D_800A18B4)
    /* 394CC 80048CCC 0A80123C */  lui        $s2, %hi(D_800A18FC)
    /* 394D0 80048CD0 FC185226 */  addiu      $s2, $s2, %lo(D_800A18FC)
  .L80048CD4:
    /* 394D4 80048CD4 0000A296 */  lhu        $v0, 0x0($s5)
    /* 394D8 80048CD8 0200B526 */  addiu      $s5, $s5, 0x2
    /* 394DC 80048CDC 21202002 */  addu       $a0, $s1, $zero
    /* 394E0 80048CE0 21306002 */  addu       $a2, $s3, $zero
    /* 394E4 80048CE4 21380000 */  addu       $a3, $zero, $zero
    /* 394E8 80048CE8 04007326 */  addiu      $s3, $s3, 0x4
    /* 394EC 80048CEC 01003126 */  addiu      $s1, $s1, 0x1
    /* 394F0 80048CF0 000002AE */  sw         $v0, 0x0($s0)
    /* 394F4 80048CF4 000040AE */  sw         $zero, 0x0($s2)
    /* 394F8 80048CF8 0000058E */  lw         $a1, 0x0($s0)
    /* 394FC 80048CFC 04001026 */  addiu      $s0, $s0, 0x4
    /* 39500 80048D00 476E010C */  jal        Stat_QueryLevelAndSubLevel
    /* 39504 80048D04 04005226 */   addiu     $s2, $s2, 0x4
    /* 39508 80048D08 0700222A */  slti       $v0, $s1, 0x7
    /* 3950C 80048D0C F1FF4014 */  bnez       $v0, .L80048CD4
    /* 39510 80048D10 06000424 */   addiu     $a0, $zero, 0x6
    /* 39514 80048D14 0C80023C */  lui        $v0, %hi(g_AyaBonusPoints)
    /* 39518 80048D18 100E428C */  lw         $v0, %lo(g_AyaBonusPoints)($v0)
    /* 3951C 80048D1C 0A80033C */  lui        $v1, %hi(D_800A18B0)
    /* 39520 80048D20 B0186324 */  addiu      $v1, $v1, %lo(D_800A18B0)
    /* 39524 80048D24 100280AF */  sw         $zero, %gp_rel(D_8009CF80)($gp)
    /* 39528 80048D28 D00180AF */  sw         $zero, %gp_rel(D_8009CF40)($gp)
    /* 3952C 80048D2C F80182AF */  sw         $v0, %gp_rel(D_8009CF68)($gp)
  .L80048D30:
    /* 39530 80048D30 000060AC */  sw         $zero, 0x0($v1)
    /* 39534 80048D34 FFFF8424 */  addiu      $a0, $a0, -0x1
    /* 39538 80048D38 FDFF8104 */  bgez       $a0, .L80048D30
    /* 3953C 80048D3C FCFF6324 */   addiu     $v1, $v1, -0x4
    /* 39540 80048D40 C22F010C */  jal        Menu_InitStateTables
    /* 39544 80048D44 00000000 */   nop
  .L80048D48:
    /* 39548 80048D48 01000424 */  addiu      $a0, $zero, 0x1
    /* 3954C 80048D4C 8D8A010C */  jal        MenuWidget_FindByModeAndSelectedBase
    /* 39550 80048D50 01000524 */   addiu     $a1, $zero, 0x1
    /* 39554 80048D54 6B8C010C */  jal        MenuWidget_SetCursorY
    /* 39558 80048D58 21204000 */   addu      $a0, $v0, $zero
    /* 3955C 80048D5C 01000424 */  addiu      $a0, $zero, 0x1
    /* 39560 80048D60 8D8A010C */  jal        MenuWidget_FindByModeAndSelectedBase
    /* 39564 80048D64 1B000524 */   addiu     $a1, $zero, 0x1B
    /* 39568 80048D68 6B8C010C */  jal        MenuWidget_SetCursorY
    /* 3956C 80048D6C 21204000 */   addu      $a0, $v0, $zero
    /* 39570 80048D70 AC01828F */  lw         $v0, %gp_rel(D_8009CF1C)($gp)
    /* 39574 80048D74 00000000 */  nop
    /* 39578 80048D78 0D004010 */  beqz       $v0, .L80048DB0
    /* 3957C 80048D7C 01000424 */   addiu     $a0, $zero, 0x1
    /* 39580 80048D80 8D8A010C */  jal        MenuWidget_FindByModeAndSelectedBase
    /* 39584 80048D84 2F000524 */   addiu     $a1, $zero, 0x2F
    /* 39588 80048D88 0A004014 */  bnez       $v0, .L80048DB4
    /* 3958C 80048D8C 0B000424 */   addiu     $a0, $zero, 0xB
    /* 39590 80048D90 2F000424 */  addiu      $a0, $zero, 0x2F
    /* 39594 80048D94 21280000 */  addu       $a1, $zero, $zero
    /* 39598 80048D98 21300000 */  addu       $a2, $zero, $zero
    /* 3959C 80048D9C 4B8B010C */  jal        MenuWidget_CreateSimpleNode
    /* 395A0 80048DA0 21380000 */   addu      $a3, $zero, $zero
    /* 395A4 80048DA4 0480033C */  lui        $v1, %hi(Menu_DrawItemDetailPanel)
    /* 395A8 80048DA8 A45F6324 */  addiu      $v1, $v1, %lo(Menu_DrawItemDetailPanel)
    /* 395AC 80048DAC 300043AC */  sw         $v1, 0x30($v0)
  .L80048DB0:
    /* 395B0 80048DB0 0B000424 */  addiu      $a0, $zero, 0xB
  .L80048DB4:
    /* 395B4 80048DB4 21288002 */  addu       $a1, $s4, $zero
    /* 395B8 80048DB8 21300000 */  addu       $a2, $zero, $zero
    /* 395BC 80048DBC 4B8B010C */  jal        MenuWidget_CreateSimpleNode
    /* 395C0 80048DC0 21380000 */   addu      $a3, $zero, $zero
    /* 395C4 80048DC4 21884000 */  addu       $s1, $v0, $zero
    /* 395C8 80048DC8 0B000424 */  addiu      $a0, $zero, 0xB
    /* 395CC 80048DCC 21282002 */  addu       $a1, $s1, $zero
    /* 395D0 80048DD0 8B8C010C */  jal        MenuWidget_CreateNode
    /* 395D4 80048DD4 21302002 */   addu      $a2, $s1, $zero
    /* 395D8 80048DD8 21A04000 */  addu       $s4, $v0, $zero
    /* 395DC 80048DDC 21208002 */  addu       $a0, $s4, $zero
    /* 395E0 80048DE0 01000224 */  addiu      $v0, $zero, 0x1
    /* 395E4 80048DE4 400022AE */  sw         $v0, 0x40($s1)
    /* 395E8 80048DE8 0580023C */  lui        $v0, %hi(Menu_DrawUsableItemActionList)
    /* 395EC 80048DEC A0F94224 */  addiu      $v0, $v0, %lo(Menu_DrawUsableItemActionList)
    /* 395F0 80048DF0 0893010C */  jal        MenuWidget_ClearColumnLayout
    /* 395F4 80048DF4 300082AE */   sw        $v0, 0x30($s4)
    /* 395F8 80048DF8 21202002 */  addu       $a0, $s1, $zero
    /* 395FC 80048DFC 06000524 */  addiu      $a1, $zero, 0x6
    /* 39600 80048E00 568C010C */  jal        MenuWidget_OffsetPosition
    /* 39604 80048E04 21300000 */   addu      $a2, $zero, $zero
    /* 39608 80048E08 0F000424 */  addiu      $a0, $zero, 0xF
    /* 3960C 80048E0C 21288002 */  addu       $a1, $s4, $zero
    /* 39610 80048E10 21300000 */  addu       $a2, $zero, $zero
    /* 39614 80048E14 4B8B010C */  jal        MenuWidget_CreateSimpleNode
    /* 39618 80048E18 21380000 */   addu      $a3, $zero, $zero
    /* 3961C 80048E1C C001838F */  lw         $v1, %gp_rel(D_8009CF30)($gp)
    /* 39620 80048E20 00000000 */  nop
    /* 39624 80048E24 10006010 */  beqz       $v1, .L80048E68
    /* 39628 80048E28 21884000 */   addu      $s1, $v0, $zero
    /* 3962C 80048E2C 1D000424 */  addiu      $a0, $zero, 0x1D
    /* 39630 80048E30 21282002 */  addu       $a1, $s1, $zero
    /* 39634 80048E34 8B8C010C */  jal        MenuWidget_CreateNode
    /* 39638 80048E38 21302002 */   addu      $a2, $s1, $zero
    /* 3963C 80048E3C 21A04000 */  addu       $s4, $v0, $zero
    /* 39640 80048E40 0580023C */  lui        $v0, %hi(Menu_BonusPointCancelHandler)
    /* 39644 80048E44 54934224 */  addiu      $v0, $v0, %lo(Menu_BonusPointCancelHandler)
    /* 39648 80048E48 2C0022AE */  sw         $v0, 0x2C($s1)
    /* 3964C 80048E4C 0580023C */  lui        $v0, %hi(Menu_DrawEmptyList)
    /* 39650 80048E50 88004224 */  addiu      $v0, $v0, %lo(Menu_DrawEmptyList)
    /* 39654 80048E54 300082AE */  sw         $v0, 0x30($s4)
    /* 39658 80048E58 FFFF0224 */  addiu      $v0, $zero, -0x1
    /* 3965C 80048E5C 440082AE */  sw         $v0, 0x44($s4)
    /* 39660 80048E60 0A80013C */  lui        $at, %hi(D_800A1960)
    /* 39664 80048E64 601920A0 */  sb         $zero, %lo(D_800A1960)($at)
  .L80048E68:
    /* 39668 80048E68 0580023C */  lui        $v0, %hi(Menu_StepEquipSlotSelect2)
    /* 3966C 80048E6C C8A04224 */  addiu      $v0, $v0, %lo(Menu_StepEquipSlotSelect2)
    /* 39670 80048E70 0700C012 */  beqz       $s6, .L80048E90
    /* 39674 80048E74 300022AE */   sw        $v0, 0x30($s1)
    /* 39678 80048E78 0E00C292 */  lbu        $v0, 0xE($s6)
    /* 3967C 80048E7C 00000000 */  nop
    /* 39680 80048E80 03004230 */  andi       $v0, $v0, 0x3
    /* 39684 80048E84 580282AF */  sw         $v0, %gp_rel(D_8009CFC8)($gp)
    /* 39688 80048E88 A5230108 */  j          .L80048E94
    /* 3968C 80048E8C 00000000 */   nop
  .L80048E90:
    /* 39690 80048E90 580280AF */  sw         $zero, %gp_rel(D_8009CFC8)($gp)
  .L80048E94:
    /* 39694 80048E94 0600C012 */  beqz       $s6, .L80048EB0
    /* 39698 80048E98 0002E23A */   xori      $v0, $s7, 0x200
    /* 3969C 80048E9C 0C00C296 */  lhu        $v0, 0xC($s6)
    /* 396A0 80048EA0 00000000 */  nop
    /* 396A4 80048EA4 5C0282AF */  sw         $v0, %gp_rel(D_8009CFCC)($gp)
    /* 396A8 80048EA8 AD230108 */  j          .L80048EB4
    /* 396AC 80048EAC 0002E23A */   xori      $v0, $s7, 0x200
  .L80048EB0:
    /* 396B0 80048EB0 5C0280AF */  sw         $zero, %gp_rel(D_8009CFCC)($gp)
  .L80048EB4:
    /* 396B4 80048EB4 2B100200 */  sltu       $v0, $zero, $v0
    /* 396B8 80048EB8 A80182AF */  sw         $v0, %gp_rel(D_8009CF18)($gp)
    /* 396BC 80048EBC 318B010C */  jal        MenuWidget_GetCurrentNode
    /* 396C0 80048EC0 00000000 */   nop
    /* 396C4 80048EC4 2400438C */  lw         $v1, 0x24($v0)
    /* 396C8 80048EC8 30000224 */  addiu      $v0, $zero, 0x30
    /* 396CC 80048ECC 03006210 */  beq        $v1, $v0, .L80048EDC
    /* 396D0 80048ED0 36000224 */   addiu     $v0, $zero, 0x36
    /* 396D4 80048ED4 05006214 */  bne        $v1, $v0, .L80048EEC
    /* 396D8 80048ED8 00000000 */   nop
  .L80048EDC:
    /* 396DC 80048EDC 0224010C */  jal        Menu_SetEquipPanelsCursorY
    /* 396E0 80048EE0 00000000 */   nop
    /* 396E4 80048EE4 BD230108 */  j          .L80048EF4
    /* 396E8 80048EE8 00000000 */   nop
  .L80048EEC:
    /* 396EC 80048EEC C923010C */  jal        Menu_AlignEquipPanels
    /* 396F0 80048EF0 00000000 */   nop
  .L80048EF4:
    /* 396F4 80048EF4 3000BF8F */  lw         $ra, 0x30($sp)
    /* 396F8 80048EF8 2C00B78F */  lw         $s7, 0x2C($sp)
    /* 396FC 80048EFC 2800B68F */  lw         $s6, 0x28($sp)
    /* 39700 80048F00 2400B58F */  lw         $s5, 0x24($sp)
    /* 39704 80048F04 2000B48F */  lw         $s4, 0x20($sp)
    /* 39708 80048F08 1C00B38F */  lw         $s3, 0x1C($sp)
    /* 3970C 80048F0C 1800B28F */  lw         $s2, 0x18($sp)
    /* 39710 80048F10 1400B18F */  lw         $s1, 0x14($sp)
    /* 39714 80048F14 1000B08F */  lw         $s0, 0x10($sp)
    /* 39718 80048F18 3800BD27 */  addiu      $sp, $sp, 0x38
    /* 3971C 80048F1C 0800E003 */  jr         $ra
    /* 39720 80048F20 00000000 */   nop
endlabel Menu_StepInventoryRoot
