.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.4 */

nonmatching Render_StepParticleNode, 0x224

glabel Render_StepParticleNode
    /* 6F164 8007E964 D8FFBD27 */  addiu      $sp, $sp, -0x28
    /* 6F168 8007E968 21308000 */  addu       $a2, $a0, $zero
    /* 6F16C 8007E96C 1400B1AF */  sw         $s1, 0x14($sp)
    /* 6F170 8007E970 2188A000 */  addu       $s1, $a1, $zero
    /* 6F174 8007E974 1800B2AF */  sw         $s2, 0x18($sp)
    /* 6F178 8007E978 0A80123C */  lui        $s2, %hi(D_800A3604)
    /* 6F17C 8007E97C 04365226 */  addiu      $s2, $s2, %lo(D_800A3604)
    /* 6F180 8007E980 2400BFAF */  sw         $ra, 0x24($sp)
    /* 6F184 8007E984 2000B4AF */  sw         $s4, 0x20($sp)
    /* 6F188 8007E988 1C00B3AF */  sw         $s3, 0x1C($sp)
    /* 6F18C 8007E98C 1000B0AF */  sw         $s0, 0x10($sp)
    /* 6F190 8007E990 0000438E */  lw         $v1, 0x0($s2)
    /* 6F194 8007E994 3CFF5326 */  addiu      $s3, $s2, -0xC4
    /* 6F198 8007E998 40100300 */  sll        $v0, $v1, 1
    /* 6F19C 8007E99C 21104300 */  addu       $v0, $v0, $v1
    /* 6F1A0 8007E9A0 C0100200 */  sll        $v0, $v0, 3
    /* 6F1A4 8007E9A4 21805300 */  addu       $s0, $v0, $s3
    /* 6F1A8 8007E9A8 0000038E */  lw         $v1, 0x0($s0)
    /* 6F1AC 8007E9AC 00000000 */  nop
    /* 6F1B0 8007E9B0 46006010 */  beqz       $v1, .L8007EACC
    /* 6F1B4 8007E9B4 21A0C000 */   addu      $s4, $a2, $zero
    /* 6F1B8 8007E9B8 0A80023C */  lui        $v0, %hi(D_800A3510)
    /* 6F1BC 8007E9BC 10354224 */  addiu      $v0, $v0, %lo(D_800A3510)
    /* 6F1C0 8007E9C0 05004424 */  addiu      $a0, $v0, 0x5
    /* 6F1C4 8007E9C4 000043AC */  sw         $v1, 0x0($v0)
    /* 6F1C8 8007E9C8 6602020C */  jal        Util_Copy8
    /* 6F1CC 8007E9CC 040046A0 */   sb        $a2, 0x4($v0)
    /* 6F1D0 8007E9D0 FF008332 */  andi       $v1, $s4, 0xFF
    /* 6F1D4 8007E9D4 02000224 */  addiu      $v0, $zero, 0x2
    /* 6F1D8 8007E9D8 05006210 */  beq        $v1, $v0, .L8007E9F0
    /* 6F1DC 8007E9DC 05000224 */   addiu     $v0, $zero, 0x5
    /* 6F1E0 8007E9E0 20006210 */  beq        $v1, $v0, .L8007EA64
    /* 6F1E4 8007E9E4 00000000 */   nop
    /* 6F1E8 8007E9E8 B3FA0108 */  j          .L8007EACC
    /* 6F1EC 8007E9EC 00000000 */   nop
  .L8007E9F0:
    /* 6F1F0 8007E9F0 0000428E */  lw         $v0, 0x0($s2)
    /* 6F1F4 8007E9F4 00000000 */  nop
    /* 6F1F8 8007E9F8 01004524 */  addiu      $a1, $v0, 0x1
    /* 6F1FC 8007E9FC 0800A628 */  slti       $a2, $a1, 0x8
    /* 6F200 8007EA00 0200C014 */  bnez       $a2, .L8007EA0C
    /* 6F204 8007EA04 2118A000 */   addu      $v1, $a1, $zero
    /* 6F208 8007EA08 21180000 */  addu       $v1, $zero, $zero
  .L8007EA0C:
    /* 6F20C 8007EA0C 40100300 */  sll        $v0, $v1, 1
    /* 6F210 8007EA10 21104300 */  addu       $v0, $v0, $v1
    /* 6F214 8007EA14 C0100200 */  sll        $v0, $v0, 3
    /* 6F218 8007EA18 21105300 */  addu       $v0, $v0, $s3
    /* 6F21C 8007EA1C 0000428C */  lw         $v0, 0x0($v0)
    /* 6F220 8007EA20 0000048E */  lw         $a0, 0x0($s0)
    /* 6F224 8007EA24 00000000 */  nop
    /* 6F228 8007EA28 0A004410 */  beq        $v0, $a0, .L8007EA54
    /* 6F22C 8007EA2C 00000000 */   nop
    /* 6F230 8007EA30 02000524 */  addiu      $a1, $zero, 0x2
    /* 6F234 8007EA34 E2FA010C */  jal        CdRom_EnqueueCmd
    /* 6F238 8007EA38 21302002 */   addu      $a2, $s1, $zero
    /* 6F23C 8007EA3C 1000028E */  lw         $v0, 0x10($s0)
    /* 6F240 8007EA40 00000000 */  nop
    /* 6F244 8007EA44 1F004010 */  beqz       $v0, .L8007EAC4
    /* 6F248 8007EA48 02000424 */   addiu     $a0, $zero, 0x2
    /* 6F24C 8007EA4C AFFA0108 */  j          .L8007EABC
    /* 6F250 8007EA50 00000000 */   nop
  .L8007EA54:
    /* 6F254 8007EA54 1D00C014 */  bnez       $a2, .L8007EACC
    /* 6F258 8007EA58 000045AE */   sw        $a1, 0x0($s2)
    /* 6F25C 8007EA5C B3FA0108 */  j          .L8007EACC
    /* 6F260 8007EA60 000040AE */   sw        $zero, 0x0($s2)
  .L8007EA64:
    /* 6F264 8007EA64 1400038E */  lw         $v1, 0x14($s0)
    /* 6F268 8007EA68 00000000 */  nop
    /* 6F26C 8007EA6C 0300601C */  bgtz       $v1, .L8007EA7C
    /* 6F270 8007EA70 FFFF0224 */   addiu     $v0, $zero, -0x1
    /* 6F274 8007EA74 0A006214 */  bne        $v1, $v0, .L8007EAA0
    /* 6F278 8007EA78 05000524 */   addiu     $a1, $zero, 0x5
  .L8007EA7C:
    /* 6F27C 8007EA7C C000628E */  lw         $v0, 0xC0($s3)
    /* 6F280 8007EA80 00000000 */  nop
    /* 6F284 8007EA84 000042AE */  sw         $v0, 0x0($s2)
    /* 6F288 8007EA88 1400038E */  lw         $v1, 0x14($s0)
    /* 6F28C 8007EA8C FFFF0224 */  addiu      $v0, $zero, -0x1
    /* 6F290 8007EA90 0E006210 */  beq        $v1, $v0, .L8007EACC
    /* 6F294 8007EA94 FFFF6224 */   addiu     $v0, $v1, -0x1
    /* 6F298 8007EA98 B3FA0108 */  j          .L8007EACC
    /* 6F29C 8007EA9C 140002AE */   sw        $v0, 0x14($s0)
  .L8007EAA0:
    /* 6F2A0 8007EAA0 0000048E */  lw         $a0, 0x0($s0)
    /* 6F2A4 8007EAA4 E2FA010C */  jal        CdRom_EnqueueCmd
    /* 6F2A8 8007EAA8 21302002 */   addu      $a2, $s1, $zero
    /* 6F2AC 8007EAAC 1000028E */  lw         $v0, 0x10($s0)
    /* 6F2B0 8007EAB0 00000000 */  nop
    /* 6F2B4 8007EAB4 03004010 */  beqz       $v0, .L8007EAC4
    /* 6F2B8 8007EAB8 05000424 */   addiu     $a0, $zero, 0x5
  .L8007EABC:
    /* 6F2BC 8007EABC 09F84000 */  jalr       $v0
    /* 6F2C0 8007EAC0 21282002 */   addu      $a1, $s1, $zero
  .L8007EAC4:
    /* 6F2C4 8007EAC4 71F9010C */  jal        Spu_DrainQueueEntry
    /* 6F2C8 8007EAC8 00000000 */   nop
  .L8007EACC:
    /* 6F2CC 8007EACC 0C80023C */  lui        $v0, %hi(D_800B8AB0)
    /* 6F2D0 8007EAD0 B08A428C */  lw         $v0, %lo(D_800B8AB0)($v0)
    /* 6F2D4 8007EAD4 00000000 */  nop
    /* 6F2D8 8007EAD8 03004010 */  beqz       $v0, .L8007EAE8
    /* 6F2DC 8007EADC FF008432 */   andi      $a0, $s4, 0xFF
    /* 6F2E0 8007EAE0 09F84000 */  jalr       $v0
    /* 6F2E4 8007EAE4 21282002 */   addu      $a1, $s1, $zero
  .L8007EAE8:
    /* 6F2E8 8007EAE8 FCFE010C */  jal        DsSync
    /* 6F2EC 8007EAEC 21200000 */   addu      $a0, $zero, $zero
    /* 6F2F0 8007EAF0 21804000 */  addu       $s0, $v0, $zero
    /* 6F2F4 8007EAF4 01000224 */  addiu      $v0, $zero, 0x1
    /* 6F2F8 8007EAF8 1B000216 */  bne        $s0, $v0, .L8007EB68
    /* 6F2FC 8007EAFC 00000000 */   nop
    /* 6F300 8007EB00 0A80113C */  lui        $s1, %hi(g_CdPendingReadCount)
    /* 6F304 8007EB04 08363126 */  addiu      $s1, $s1, %lo(g_CdPendingReadCount)
    /* 6F308 8007EB08 0000228E */  lw         $v0, 0x0($s1)
    /* 6F30C 8007EB0C 00000000 */  nop
    /* 6F310 8007EB10 15004018 */  blez       $v0, .L8007EB68
    /* 6F314 8007EB14 00000000 */   nop
    /* 6F318 8007EB18 FCFE010C */  jal        DsSync
    /* 6F31C 8007EB1C 21200000 */   addu      $a0, $zero, $zero
    /* 6F320 8007EB20 11005014 */  bne        $v0, $s0, .L8007EB68
    /* 6F324 8007EB24 00000000 */   nop
    /* 6F328 8007EB28 0A80033C */  lui        $v1, %hi(D_800A3604)
    /* 6F32C 8007EB2C 0436638C */  lw         $v1, %lo(D_800A3604)($v1)
    /* 6F330 8007EB30 00000000 */  nop
    /* 6F334 8007EB34 40100300 */  sll        $v0, $v1, 1
    /* 6F338 8007EB38 21104300 */  addu       $v0, $v0, $v1
    /* 6F33C 8007EB3C C0100200 */  sll        $v0, $v0, 3
    /* 6F340 8007EB40 38FF2326 */  addiu      $v1, $s1, -0xC8
    /* 6F344 8007EB44 21184300 */  addu       $v1, $v0, $v1
    /* 6F348 8007EB48 0000628C */  lw         $v0, 0x0($v1)
    /* 6F34C 8007EB4C 00000000 */  nop
    /* 6F350 8007EB50 05004010 */  beqz       $v0, .L8007EB68
    /* 6F354 8007EB54 00000000 */   nop
    /* 6F358 8007EB58 04006490 */  lbu        $a0, 0x4($v1)
    /* 6F35C 8007EB5C 0C00658C */  lw         $a1, 0xC($v1)
    /* 6F360 8007EB60 D1FE010C */  jal        CdRom_TryIssueCmd
    /* 6F364 8007EB64 00000000 */   nop
  .L8007EB68:
    /* 6F368 8007EB68 2400BF8F */  lw         $ra, 0x24($sp)
    /* 6F36C 8007EB6C 2000B48F */  lw         $s4, 0x20($sp)
    /* 6F370 8007EB70 1C00B38F */  lw         $s3, 0x1C($sp)
    /* 6F374 8007EB74 1800B28F */  lw         $s2, 0x18($sp)
    /* 6F378 8007EB78 1400B18F */  lw         $s1, 0x14($sp)
    /* 6F37C 8007EB7C 1000B08F */  lw         $s0, 0x10($sp)
    /* 6F380 8007EB80 0800E003 */  jr         $ra
    /* 6F384 8007EB84 2800BD27 */   addiu     $sp, $sp, 0x28
endlabel Render_StepParticleNode
