.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.4 */

nonmatching Render_LoadFontGlyph, 0x1E4

glabel Render_LoadFontGlyph
    /* 291DC 800389DC D8FFBD27 */  addiu      $sp, $sp, -0x28
    /* 291E0 800389E0 1C00B3AF */  sw         $s3, 0x1C($sp)
    /* 291E4 800389E4 21988000 */  addu       $s3, $a0, $zero
    /* 291E8 800389E8 2000BFAF */  sw         $ra, 0x20($sp)
    /* 291EC 800389EC 1800B2AF */  sw         $s2, 0x18($sp)
    /* 291F0 800389F0 1400B1AF */  sw         $s1, 0x14($sp)
    /* 291F4 800389F4 1000B0AF */  sw         $s0, 0x10($sp)
  .L800389F8:
    /* 291F8 800389F8 0B80113C */  lui        $s1, %hi(g_PeImageBaseLba)
    /* 291FC 800389FC D80D3126 */  addiu      $s1, $s1, %lo(g_PeImageBaseLba)
    /* 29200 80038A00 0980103C */  lui        $s0, %hi(g_FontGlyphLbaTbl)
    /* 29204 80038A04 76311026 */  addiu      $s0, $s0, %lo(g_FontGlyphLbaTbl)
    /* 29208 80038A08 FFFF1224 */  addiu      $s2, $zero, -0x1
  .L80038A0C:
    /* 2920C 80038A0C 00000696 */  lhu        $a2, 0x0($s0)
    /* 29210 80038A10 0000248E */  lw         $a0, 0x0($s1)
    /* 29214 80038A14 02000296 */  lhu        $v0, 0x2($s0)
    /* 29218 80038A18 9400258E */  lw         $a1, 0x94($s1)
    /* 2921C 80038A1C 21208600 */  addu       $a0, $a0, $a2
    /* 29220 80038A20 AAB9010C */  jal        CdRom_ReadSectorsFromLba
    /* 29224 80038A24 23304600 */   subu      $a2, $v0, $a2
    /* 29228 80038A28 F8FF5210 */  beq        $v0, $s2, .L80038A0C
    /* 2922C 80038A2C 00000000 */   nop
    /* 29230 80038A30 FFFF1024 */  addiu      $s0, $zero, -0x1
  .L80038A34:
    /* 29234 80038A34 FAB9010C */  jal        CdRom_PollReady
    /* 29238 80038A38 00000000 */   nop
    /* 2923C 80038A3C 05004010 */  beqz       $v0, .L80038A54
    /* 29240 80038A40 FF006332 */   andi      $v1, $s3, 0xFF
    /* 29244 80038A44 ECFF5010 */  beq        $v0, $s0, .L800389F8
    /* 29248 80038A48 00000000 */   nop
    /* 2924C 80038A4C 8DE20008 */  j          .L80038A34
    /* 29250 80038A50 00000000 */   nop
  .L80038A54:
    /* 29254 80038A54 80100300 */  sll        $v0, $v1, 2
    /* 29258 80038A58 21104300 */  addu       $v0, $v0, $v1
    /* 2925C 80038A5C C0100200 */  sll        $v0, $v0, 3
    /* 29260 80038A60 21104300 */  addu       $v0, $v0, $v1
    /* 29264 80038A64 C0100200 */  sll        $v0, $v0, 3
    /* 29268 80038A68 01004624 */  addiu      $a2, $v0, 0x1
    /* 2926C 80038A6C 0B80043C */  lui        $a0, %hi(D_800B0E6C)
    /* 29270 80038A70 6C0E848C */  lw         $a0, %lo(D_800B0E6C)($a0)
    /* 29274 80038A74 21280000 */  addu       $a1, $zero, $zero
    /* 29278 80038A78 21188600 */  addu       $v1, $a0, $a2
    /* 2927C 80038A7C 00006390 */  lbu        $v1, 0x0($v1)
    /* 29280 80038A80 02004624 */  addiu      $a2, $v0, 0x2
    /* 29284 80038A84 0A80013C */  lui        $at, %hi(D_8009ECD9)
    /* 29288 80038A88 D9EC23A0 */  sb         $v1, %lo(D_8009ECD9)($at)
    /* 2928C 80038A8C 21188600 */  addu       $v1, $a0, $a2
    /* 29290 80038A90 03004624 */  addiu      $a2, $v0, 0x3
    /* 29294 80038A94 00006390 */  lbu        $v1, 0x0($v1)
    /* 29298 80038A98 21208600 */  addu       $a0, $a0, $a2
    /* 2929C 80038A9C 0A80013C */  lui        $at, %hi(D_8009ECDA)
    /* 292A0 80038AA0 DAEC23A0 */  sb         $v1, %lo(D_8009ECDA)($at)
    /* 292A4 80038AA4 00008390 */  lbu        $v1, 0x0($a0)
    /* 292A8 80038AA8 04004624 */  addiu      $a2, $v0, 0x4
    /* 292AC 80038AAC 0A80013C */  lui        $at, %hi(D_8009ECDB)
    /* 292B0 80038AB0 DBEC23A0 */  sb         $v1, %lo(D_8009ECDB)($at)
  .L80038AB4:
    /* 292B4 80038AB4 0B80023C */  lui        $v0, %hi(D_800B0E6C)
    /* 292B8 80038AB8 6C0E428C */  lw         $v0, %lo(D_800B0E6C)($v0)
    /* 292BC 80038ABC 00000000 */  nop
    /* 292C0 80038AC0 21104600 */  addu       $v0, $v0, $a2
    /* 292C4 80038AC4 00004290 */  lbu        $v0, 0x0($v0)
    /* 292C8 80038AC8 0A80013C */  lui        $at, %hi(D_8009ECDC)
    /* 292CC 80038ACC 21082500 */  addu       $at, $at, $a1
    /* 292D0 80038AD0 DCEC22A0 */  sb         $v0, %lo(D_8009ECDC)($at)
    /* 292D4 80038AD4 0100A524 */  addiu      $a1, $a1, 0x1
    /* 292D8 80038AD8 1800A228 */  slti       $v0, $a1, 0x18
    /* 292DC 80038ADC F5FF4014 */  bnez       $v0, .L80038AB4
    /* 292E0 80038AE0 0100C624 */   addiu     $a2, $a2, 0x1
    /* 292E4 80038AE4 0B80023C */  lui        $v0, %hi(D_800B0E6C)
    /* 292E8 80038AE8 6C0E428C */  lw         $v0, %lo(D_800B0E6C)($v0)
    /* 292EC 80038AEC 21280000 */  addu       $a1, $zero, $zero
    /* 292F0 80038AF0 21104600 */  addu       $v0, $v0, $a2
    /* 292F4 80038AF4 00004290 */  lbu        $v0, 0x0($v0)
    /* 292F8 80038AF8 0100C624 */  addiu      $a2, $a2, 0x1
    /* 292FC 80038AFC 0A80013C */  lui        $at, %hi(D_8009ECF4)
    /* 29300 80038B00 F4EC22A0 */  sb         $v0, %lo(D_8009ECF4)($at)
  .L80038B04:
    /* 29304 80038B04 0B80023C */  lui        $v0, %hi(D_800B0E6C)
    /* 29308 80038B08 6C0E428C */  lw         $v0, %lo(D_800B0E6C)($v0)
    /* 2930C 80038B0C 00000000 */  nop
    /* 29310 80038B10 21104600 */  addu       $v0, $v0, $a2
    /* 29314 80038B14 00004290 */  lbu        $v0, 0x0($v0)
    /* 29318 80038B18 0A80013C */  lui        $at, %hi(D_8009ECF5)
    /* 2931C 80038B1C 21082500 */  addu       $at, $at, $a1
    /* 29320 80038B20 F5EC22A0 */  sb         $v0, %lo(D_8009ECF5)($at)
    /* 29324 80038B24 0100A524 */  addiu      $a1, $a1, 0x1
    /* 29328 80038B28 6400A228 */  slti       $v0, $a1, 0x64
    /* 2932C 80038B2C F5FF4014 */  bnez       $v0, .L80038B04
    /* 29330 80038B30 0100C624 */   addiu     $a2, $a2, 0x1
    /* 29334 80038B34 21280000 */  addu       $a1, $zero, $zero
  .L80038B38:
    /* 29338 80038B38 0B80023C */  lui        $v0, %hi(D_800B0E6C)
    /* 2933C 80038B3C 6C0E428C */  lw         $v0, %lo(D_800B0E6C)($v0)
    /* 29340 80038B40 00000000 */  nop
    /* 29344 80038B44 21104600 */  addu       $v0, $v0, $a2
    /* 29348 80038B48 00004290 */  lbu        $v0, 0x0($v0)
    /* 2934C 80038B4C 0A80013C */  lui        $at, %hi(D_8009ED59)
    /* 29350 80038B50 21082500 */  addu       $at, $at, $a1
    /* 29354 80038B54 59ED22A0 */  sb         $v0, %lo(D_8009ED59)($at)
    /* 29358 80038B58 0100A524 */  addiu      $a1, $a1, 0x1
    /* 2935C 80038B5C 6400A228 */  slti       $v0, $a1, 0x64
    /* 29360 80038B60 F5FF4014 */  bnez       $v0, .L80038B38
    /* 29364 80038B64 0100C624 */   addiu     $a2, $a2, 0x1
    /* 29368 80038B68 21280000 */  addu       $a1, $zero, $zero
  .L80038B6C:
    /* 2936C 80038B6C 0B80023C */  lui        $v0, %hi(D_800B0E6C)
    /* 29370 80038B70 6C0E428C */  lw         $v0, %lo(D_800B0E6C)($v0)
    /* 29374 80038B74 00000000 */  nop
    /* 29378 80038B78 21104600 */  addu       $v0, $v0, $a2
    /* 2937C 80038B7C 00004290 */  lbu        $v0, 0x0($v0)
    /* 29380 80038B80 0A80013C */  lui        $at, %hi(D_8009EDBD)
    /* 29384 80038B84 21082500 */  addu       $at, $at, $a1
    /* 29388 80038B88 BDED22A0 */  sb         $v0, %lo(D_8009EDBD)($at)
    /* 2938C 80038B8C 0100A524 */  addiu      $a1, $a1, 0x1
    /* 29390 80038B90 6400A228 */  slti       $v0, $a1, 0x64
    /* 29394 80038B94 F5FF4014 */  bnez       $v0, .L80038B6C
    /* 29398 80038B98 0100C624 */   addiu     $a2, $a2, 0x1
    /* 2939C 80038B9C 21100000 */  addu       $v0, $zero, $zero
    /* 293A0 80038BA0 2000BF8F */  lw         $ra, 0x20($sp)
    /* 293A4 80038BA4 1C00B38F */  lw         $s3, 0x1C($sp)
    /* 293A8 80038BA8 1800B28F */  lw         $s2, 0x18($sp)
    /* 293AC 80038BAC 1400B18F */  lw         $s1, 0x14($sp)
    /* 293B0 80038BB0 1000B08F */  lw         $s0, 0x10($sp)
    /* 293B4 80038BB4 2800BD27 */  addiu      $sp, $sp, 0x28
    /* 293B8 80038BB8 0800E003 */  jr         $ra
    /* 293BC 80038BBC 00000000 */   nop
endlabel Render_LoadFontGlyph
