.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.4 */

nonmatching Render_DrawEntity, 0x230

glabel Render_DrawEntity
    /* 2B714 8003AF14 D8FFBD27 */  addiu      $sp, $sp, -0x28
    /* 2B718 8003AF18 1800B0AF */  sw         $s0, 0x18($sp)
    /* 2B71C 8003AF1C 21808000 */  addu       $s0, $a0, $zero
    /* 2B720 8003AF20 2000BFAF */  sw         $ra, 0x20($sp)
    /* 2B724 8003AF24 1C00B1AF */  sw         $s1, 0x1C($sp)
    /* 2B728 8003AF28 0000028E */  lw         $v0, 0x0($s0)
    /* 2B72C 8003AF2C 00000000 */  nop
    /* 2B730 8003AF30 7E004010 */  beqz       $v0, .L8003B12C
    /* 2B734 8003AF34 2188A000 */   addu      $s1, $a1, $zero
    /* 2B738 8003AF38 BA000286 */  lh         $v0, 0xBA($s0)
    /* 2B73C 8003AF3C 00000000 */  nop
    /* 2B740 8003AF40 7A004010 */  beqz       $v0, .L8003B12C
    /* 2B744 8003AF44 00000000 */   nop
    /* 2B748 8003AF48 9C000296 */  lhu        $v0, 0x9C($s0)
    /* 2B74C 8003AF4C 00000000 */  nop
    /* 2B750 8003AF50 00084230 */  andi       $v0, $v0, 0x800
    /* 2B754 8003AF54 0A004010 */  beqz       $v0, .L8003AF80
    /* 2B758 8003AF58 00000000 */   nop
    /* 2B75C 8003AF5C BEF3000C */  jal        Field_GetMapEntry
    /* 2B760 8003AF60 21280000 */   addu      $a1, $zero, $zero
    /* 2B764 8003AF64 21200002 */  addu       $a0, $s0, $zero
    /* 2B768 8003AF68 2CF3000C */  jal        Render_SetEntityBlendMode
    /* 2B76C 8003AF6C 21280000 */   addu      $a1, $zero, $zero
    /* 2B770 8003AF70 9C000296 */  lhu        $v0, 0x9C($s0)
    /* 2B774 8003AF74 00000000 */  nop
    /* 2B778 8003AF78 FFF74230 */  andi       $v0, $v0, 0xF7FF
    /* 2B77C 8003AF7C 9C0002A6 */  sh         $v0, 0x9C($s0)
  .L8003AF80:
    /* 2B780 8003AF80 9C000296 */  lhu        $v0, 0x9C($s0)
    /* 2B784 8003AF84 00000000 */  nop
    /* 2B788 8003AF88 10004230 */  andi       $v0, $v0, 0x10
    /* 2B78C 8003AF8C 04004010 */  beqz       $v0, .L8003AFA0
    /* 2B790 8003AF90 21200002 */   addu      $a0, $s0, $zero
    /* 2B794 8003AF94 9A000586 */  lh         $a1, 0x9A($s0)
    /* 2B798 8003AF98 B8F0000C */  jal        Render_DrawObjectVariant
    /* 2B79C 8003AF9C 21302002 */   addu      $a2, $s1, $zero
  .L8003AFA0:
    /* 2B7A0 8003AFA0 9E000392 */  lbu        $v1, 0x9E($s0)
    /* 2B7A4 8003AFA4 01000224 */  addiu      $v0, $zero, 0x1
    /* 2B7A8 8003AFA8 03006214 */  bne        $v1, $v0, .L8003AFB8
    /* 2B7AC 8003AFAC 00000000 */   nop
    /* 2B7B0 8003AFB0 51EC000C */  jal        Render_DrawTexturedQuads
    /* 2B7B4 8003AFB4 21200002 */   addu      $a0, $s0, $zero
  .L8003AFB8:
    /* 2B7B8 8003AFB8 9C000396 */  lhu        $v1, 0x9C($s0)
    /* 2B7BC 8003AFBC 00000000 */  nop
    /* 2B7C0 8003AFC0 20006230 */  andi       $v0, $v1, 0x20
    /* 2B7C4 8003AFC4 0E004010 */  beqz       $v0, .L8003B000
    /* 2B7C8 8003AFC8 40006230 */   andi      $v0, $v1, 0x40
    /* 2B7CC 8003AFCC 0A80053C */  lui        $a1, %hi(g_ActiveDrawSlot)
    /* 2B7D0 8003AFD0 DCCDA584 */  lh         $a1, %lo(g_ActiveDrawSlot)($a1)
    /* 2B7D4 8003AFD4 C2ED000C */  jal        Render_BuildEntityMatrix
    /* 2B7D8 8003AFD8 21200002 */   addu      $a0, $s0, $zero
    /* 2B7DC 8003AFDC 0A80023C */  lui        $v0, %hi(g_ActiveDrawSlot)
    /* 2B7E0 8003AFE0 DCCD428C */  lw         $v0, %lo(g_ActiveDrawSlot)($v0)
    /* 2B7E4 8003AFE4 9C000396 */  lhu        $v1, 0x9C($s0)
    /* 2B7E8 8003AFE8 0100422C */  sltiu      $v0, $v0, 0x1
    /* 2B7EC 8003AFEC DFFF6330 */  andi       $v1, $v1, 0xFFDF
    /* 2B7F0 8003AFF0 40006334 */  ori        $v1, $v1, 0x40
    /* 2B7F4 8003AFF4 9F0002A2 */  sb         $v0, 0x9F($s0)
    /* 2B7F8 8003AFF8 09EC0008 */  j          .L8003B024
    /* 2B7FC 8003AFFC 9C0003A6 */   sh        $v1, 0x9C($s0)
  .L8003B000:
    /* 2B800 8003B000 08004010 */  beqz       $v0, .L8003B024
    /* 2B804 8003B004 00000000 */   nop
    /* 2B808 8003B008 9F000592 */  lbu        $a1, 0x9F($s0)
    /* 2B80C 8003B00C C2ED000C */  jal        Render_BuildEntityMatrix
    /* 2B810 8003B010 21200002 */   addu      $a0, $s0, $zero
    /* 2B814 8003B014 9C000296 */  lhu        $v0, 0x9C($s0)
    /* 2B818 8003B018 00000000 */  nop
    /* 2B81C 8003B01C BFFF4230 */  andi       $v0, $v0, 0xFFBF
    /* 2B820 8003B020 9C0002A6 */  sh         $v0, 0x9C($s0)
  .L8003B024:
    /* 2B824 8003B024 9C000396 */  lhu        $v1, 0x9C($s0)
    /* 2B828 8003B028 00000000 */  nop
    /* 2B82C 8003B02C 02006230 */  andi       $v0, $v1, 0x2
    /* 2B830 8003B030 12004010 */  beqz       $v0, .L8003B07C
    /* 2B834 8003B034 04006230 */   andi      $v0, $v1, 0x4
    /* 2B838 8003B038 06F2000C */  jal        Render_ColorEntity
    /* 2B83C 8003B03C 21200002 */   addu      $a0, $s0, $zero
    /* 2B840 8003B040 00140200 */  sll        $v0, $v0, 16
    /* 2B844 8003B044 06004010 */  beqz       $v0, .L8003B060
    /* 2B848 8003B048 00000000 */   nop
    /* 2B84C 8003B04C 9C000296 */  lhu        $v0, 0x9C($s0)
    /* 2B850 8003B050 00000000 */  nop
    /* 2B854 8003B054 FDFF4230 */  andi       $v0, $v0, 0xFFFD
    /* 2B858 8003B058 00024234 */  ori        $v0, $v0, 0x200
    /* 2B85C 8003B05C 9C0002A6 */  sh         $v0, 0x9C($s0)
  .L8003B060:
    /* 2B860 8003B060 9C000296 */  lhu        $v0, 0x9C($s0)
    /* 2B864 8003B064 00000000 */  nop
    /* 2B868 8003B068 08004230 */  andi       $v0, $v0, 0x8
    /* 2B86C 8003B06C 2F004010 */  beqz       $v0, .L8003B12C
    /* 2B870 8003B070 21200002 */   addu      $a0, $s0, $zero
    /* 2B874 8003B074 38EC0008 */  j          .L8003B0E0
    /* 2B878 8003B078 00000000 */   nop
  .L8003B07C:
    /* 2B87C 8003B07C 11004010 */  beqz       $v0, .L8003B0C4
    /* 2B880 8003B080 08006230 */   andi      $v0, $v1, 0x8
    /* 2B884 8003B084 8EF1000C */  jal        Render_TickObject
    /* 2B888 8003B088 21200002 */   addu      $a0, $s0, $zero
    /* 2B88C 8003B08C 00140200 */  sll        $v0, $v0, 16
    /* 2B890 8003B090 05004010 */  beqz       $v0, .L8003B0A8
    /* 2B894 8003B094 00000000 */   nop
    /* 2B898 8003B098 9C000296 */  lhu        $v0, 0x9C($s0)
    /* 2B89C 8003B09C 00000000 */  nop
    /* 2B8A0 8003B0A0 FBFF4230 */  andi       $v0, $v0, 0xFFFB
    /* 2B8A4 8003B0A4 9C0002A6 */  sh         $v0, 0x9C($s0)
  .L8003B0A8:
    /* 2B8A8 8003B0A8 9C000296 */  lhu        $v0, 0x9C($s0)
    /* 2B8AC 8003B0AC 00000000 */  nop
    /* 2B8B0 8003B0B0 08004230 */  andi       $v0, $v0, 0x8
    /* 2B8B4 8003B0B4 1D004010 */  beqz       $v0, .L8003B12C
    /* 2B8B8 8003B0B8 21200002 */   addu      $a0, $s0, $zero
    /* 2B8BC 8003B0BC 38EC0008 */  j          .L8003B0E0
    /* 2B8C0 8003B0C0 00000000 */   nop
  .L8003B0C4:
    /* 2B8C4 8003B0C4 0E004010 */  beqz       $v0, .L8003B100
    /* 2B8C8 8003B0C8 01006230 */   andi      $v0, $v1, 0x1
    /* 2B8CC 8003B0CC 0C80053C */  lui        $a1, %hi(D_800BEA40)
    /* 2B8D0 8003B0D0 40EAA524 */  addiu      $a1, $a1, %lo(D_800BEA40)
    /* 2B8D4 8003B0D4 5FEE000C */  jal        Render_DrawObject
    /* 2B8D8 8003B0D8 21200002 */   addu      $a0, $s0, $zero
    /* 2B8DC 8003B0DC 21200002 */  addu       $a0, $s0, $zero
  .L8003B0E0:
    /* 2B8E0 8003B0E0 99008290 */  lbu        $v0, 0x99($a0)
    /* 2B8E4 8003B0E4 9A008584 */  lh         $a1, 0x9A($a0)
    /* 2B8E8 8003B0E8 97008690 */  lbu        $a2, 0x97($a0)
    /* 2B8EC 8003B0EC 98008790 */  lbu        $a3, 0x98($a0)
    /* 2B8F0 8003B0F0 2DF0000C */  jal        Render_DrawObjectAlt
    /* 2B8F4 8003B0F4 1000A2AF */   sw        $v0, 0x10($sp)
    /* 2B8F8 8003B0F8 4BEC0008 */  j          .L8003B12C
    /* 2B8FC 8003B0FC 00000000 */   nop
  .L8003B100:
    /* 2B900 8003B100 0A004010 */  beqz       $v0, .L8003B12C
    /* 2B904 8003B104 00000000 */   nop
    /* 2B908 8003B108 0C80053C */  lui        $a1, %hi(D_800BEA40)
    /* 2B90C 8003B10C 40EAA524 */  addiu      $a1, $a1, %lo(D_800BEA40)
    /* 2B910 8003B110 5FEE000C */  jal        Render_DrawObject
    /* 2B914 8003B114 21200002 */   addu      $a0, $s0, $zero
    /* 2B918 8003B118 21200002 */  addu       $a0, $s0, $zero
    /* 2B91C 8003B11C 0A80063C */  lui        $a2, %hi(g_ActiveDrawSlot)
    /* 2B920 8003B120 DCCDC684 */  lh         $a2, %lo(g_ActiveDrawSlot)($a2)
    /* 2B924 8003B124 38EF000C */  jal        Render_UpdateClutTable
    /* 2B928 8003B128 21280000 */   addu      $a1, $zero, $zero
  .L8003B12C:
    /* 2B92C 8003B12C 2000BF8F */  lw         $ra, 0x20($sp)
    /* 2B930 8003B130 1C00B18F */  lw         $s1, 0x1C($sp)
    /* 2B934 8003B134 1800B08F */  lw         $s0, 0x18($sp)
    /* 2B938 8003B138 2800BD27 */  addiu      $sp, $sp, 0x28
    /* 2B93C 8003B13C 0800E003 */  jr         $ra
    /* 2B940 8003B140 00000000 */   nop
endlabel Render_DrawEntity
