.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.4 */

nonmatching Render_SetupColorTable, 0x284

glabel Render_SetupColorTable
    /* 27DE0 800375E0 2160C000 */  addu       $t4, $a2, $zero
    /* 27DE4 800375E4 21488000 */  addu       $t1, $a0, $zero
    /* 27DE8 800375E8 21380000 */  addu       $a3, $zero, $zero
    /* 27DEC 800375EC 01000824 */  addiu      $t0, $zero, 0x1
    /* 27DF0 800375F0 FFFF0E24 */  addiu      $t6, $zero, -0x1
    /* 27DF4 800375F4 66660D3C */  lui        $t5, (0x66666667 >> 16)
    /* 27DF8 800375F8 6766AD35 */  ori        $t5, $t5, (0x66666667 & 0xFFFF)
    /* 27DFC 800375FC 0C800F3C */  lui        $t7, %hi(D_800BCEC2)
    /* 27E00 80037600 C2CEEF25 */  addiu      $t7, $t7, %lo(D_800BCEC2)
    /* 27E04 80037604 FF00E230 */  andi       $v0, $a3, 0xFF
  .L80037608:
    /* 27E08 80037608 C0180200 */  sll        $v1, $v0, 3
    /* 27E0C 8003760C 23186200 */  subu       $v1, $v1, $v0
    /* 27E10 80037610 C0300300 */  sll        $a2, $v1, 3
    /* 27E14 80037614 0C80013C */  lui        $at, %hi(g_TextboxEntries)
    /* 27E18 80037618 21082600 */  addu       $at, $at, $a2
    /* 27E1C 8003761C A8CE2290 */  lbu        $v0, %lo(g_TextboxEntries)($at)
    /* 27E20 80037620 00000000 */  nop
    /* 27E24 80037624 88004014 */  bnez       $v0, .L80037848
    /* 27E28 80037628 EFFF043C */   lui       $a0, (0xFFEFFFFF >> 16)
    /* 27E2C 8003762C FFFF8434 */  ori        $a0, $a0, (0xFFEFFFFF & 0xFFFF)
    /* 27E30 80037630 DFFF033C */  lui        $v1, (0xFFDFFFFF >> 16)
    /* 27E34 80037634 0C80013C */  lui        $at, %hi(D_800BCEB4)
    /* 27E38 80037638 21082600 */  addu       $at, $at, $a2
    /* 27E3C 8003763C B4CE228C */  lw         $v0, %lo(D_800BCEB4)($at)
    /* 27E40 80037640 FFFF6334 */  ori        $v1, $v1, (0xFFDFFFFF & 0xFFFF)
    /* 27E44 80037644 0C80013C */  lui        $at, %hi(g_TextboxEntries)
    /* 27E48 80037648 21082600 */  addu       $at, $at, $a2
    /* 27E4C 8003764C A8CE28A0 */  sb         $t0, %lo(g_TextboxEntries)($at)
    /* 27E50 80037650 0C80013C */  lui        $at, %hi(D_800BCEB1)
    /* 27E54 80037654 21082600 */  addu       $at, $at, $a2
    /* 27E58 80037658 B1CE20A0 */  sb         $zero, %lo(D_800BCEB1)($at)
    /* 27E5C 8003765C 0C80013C */  lui        $at, %hi(D_800BCEB8)
    /* 27E60 80037660 21082600 */  addu       $at, $at, $a2
    /* 27E64 80037664 B8CE29A4 */  sh         $t1, %lo(D_800BCEB8)($at)
    /* 27E68 80037668 300180A3 */  sb         $zero, %gp_rel(g_DialogueChoiceCursor)($gp)
    /* 27E6C 8003766C 34018EA3 */  sb         $t6, %gp_rel(g_MenuEquipSlotIndex)($gp)
    /* 27E70 80037670 0C80013C */  lui        $at, %hi(D_800BCEB0)
    /* 27E74 80037674 21082600 */  addu       $at, $at, $a2
    /* 27E78 80037678 B0CE25A0 */  sb         $a1, %lo(D_800BCEB0)($at)
    /* 27E7C 8003767C 24104400 */  and        $v0, $v0, $a0
    /* 27E80 80037680 24104300 */  and        $v0, $v0, $v1
    /* 27E84 80037684 0C80013C */  lui        $at, %hi(D_800BCEB4)
    /* 27E88 80037688 21082600 */  addu       $at, $at, $a2
    /* 27E8C 8003768C B4CE22AC */  sw         $v0, %lo(D_800BCEB4)($at)
    /* 27E90 80037690 FF00A230 */  andi       $v0, $a1, 0xFF
    /* 27E94 80037694 21004010 */  beqz       $v0, .L8003771C
    /* 27E98 80037698 00000000 */   nop
    /* 27E9C 8003769C 28018297 */  lhu        $v0, %gp_rel(D_8009CE98)($gp)
    /* 27EA0 800376A0 0C80013C */  lui        $at, %hi(D_800BCEB0)
    /* 27EA4 800376A4 21082600 */  addu       $at, $at, $a2
    /* 27EA8 800376A8 B0CE2390 */  lbu        $v1, %lo(D_800BCEB0)($at)
    /* 27EAC 800376AC 0C80013C */  lui        $at, %hi(D_800BCEBA)
    /* 27EB0 800376B0 21082600 */  addu       $at, $at, $a2
    /* 27EB4 800376B4 BACE22A4 */  sh         $v0, %lo(D_800BCEBA)($at)
    /* 27EB8 800376B8 2A018297 */  lhu        $v0, %gp_rel(D_8009CE9A)($gp)
    /* 27EBC 800376BC 0C80013C */  lui        $at, %hi(D_800BCEBC)
    /* 27EC0 800376C0 21082600 */  addu       $at, $at, $a2
    /* 27EC4 800376C4 BCCE22A4 */  sh         $v0, %lo(D_800BCEBC)($at)
    /* 27EC8 800376C8 2C018297 */  lhu        $v0, %gp_rel(D_8009CE9C)($gp)
    /* 27ECC 800376CC 0C80013C */  lui        $at, %hi(D_800BCEBE)
    /* 27ED0 800376D0 21082600 */  addu       $at, $at, $a2
    /* 27ED4 800376D4 BECE22A4 */  sh         $v0, %lo(D_800BCEBE)($at)
    /* 27ED8 800376D8 2E018297 */  lhu        $v0, %gp_rel(D_8009CE9E)($gp)
    /* 27EDC 800376DC 0C80013C */  lui        $at, %hi(D_800BCEC0)
    /* 27EE0 800376E0 21082600 */  addu       $at, $at, $a2
    /* 27EE4 800376E4 C0CE22A4 */  sh         $v0, %lo(D_800BCEC0)($at)
    /* 27EE8 800376E8 03000224 */  addiu      $v0, $zero, 0x3
    /* 27EEC 800376EC 12006214 */  bne        $v1, $v0, .L80037738
    /* 27EF0 800376F0 21480000 */   addu      $t1, $zero, $zero
    /* 27EF4 800376F4 0C80013C */  lui        $at, %hi(D_800BCEB4)
    /* 27EF8 800376F8 21082600 */  addu       $at, $at, $a2
    /* 27EFC 800376FC B4CE228C */  lw         $v0, %lo(D_800BCEB4)($at)
    /* 27F00 80037700 1000033C */  lui        $v1, (0x100000 >> 16)
    /* 27F04 80037704 25104300 */  or         $v0, $v0, $v1
    /* 27F08 80037708 0C80013C */  lui        $at, %hi(D_800BCEB4)
    /* 27F0C 8003770C 21082600 */  addu       $at, $at, $a2
    /* 27F10 80037710 B4CE22AC */  sw         $v0, %lo(D_800BCEB4)($at)
    /* 27F14 80037714 CFDD0008 */  j          .L8003773C
    /* 27F18 80037718 FF00E330 */   andi      $v1, $a3, 0xFF
  .L8003771C:
    /* 27F1C 8003771C 60018293 */  lbu        $v0, %gp_rel(D_8009CED0)($gp)
    /* 27F20 80037720 00000000 */  nop
    /* 27F24 80037724 04004010 */  beqz       $v0, .L80037738
    /* 27F28 80037728 21480000 */   addu      $t1, $zero, $zero
    /* 27F2C 8003772C 0C80013C */  lui        $at, %hi(D_800BCEB1)
    /* 27F30 80037730 21082600 */  addu       $at, $at, $a2
    /* 27F34 80037734 B1CE28A0 */  sb         $t0, %lo(D_800BCEB1)($at)
  .L80037738:
    /* 27F38 80037738 FF00E330 */  andi       $v1, $a3, 0xFF
  .L8003773C:
    /* 27F3C 8003773C C0100300 */  sll        $v0, $v1, 3
    /* 27F40 80037740 23104300 */  subu       $v0, $v0, $v1
    /* 27F44 80037744 C0580200 */  sll        $t3, $v0, 3
  .L80037748:
    /* 27F48 80037748 00008795 */  lhu        $a3, 0x0($t4)
    /* 27F4C 8003774C 00000000 */  nop
    /* 27F50 80037750 002C0700 */  sll        $a1, $a3, 16
    /* 27F54 80037754 03240500 */  sra        $a0, $a1, 16
    /* 27F58 80037758 40008E10 */  beq        $a0, $t6, .L8003785C
    /* 27F5C 8003775C 02008C25 */   addiu     $t4, $t4, 0x2
    /* 27F60 80037760 18008D00 */  mult       $a0, $t5
    /* 27F64 80037764 21400000 */  addu       $t0, $zero, $zero
    /* 27F68 80037768 FF002331 */  andi       $v1, $t1, 0xFF
    /* 27F6C 8003776C 40100300 */  sll        $v0, $v1, 1
    /* 27F70 80037770 21104300 */  addu       $v0, $v0, $v1
    /* 27F74 80037774 40100200 */  sll        $v0, $v0, 1
    /* 27F78 80037778 21104B00 */  addu       $v0, $v0, $t3
    /* 27F7C 8003777C 21504F00 */  addu       $t2, $v0, $t7
    /* 27F80 80037780 C3170500 */  sra        $v0, $a1, 31
    /* 27F84 80037784 10C00000 */  mfhi       $t8
    /* 27F88 80037788 83201800 */  sra        $a0, $t8, 2
    /* 27F8C 8003778C 23208200 */  subu       $a0, $a0, $v0
    /* 27F90 80037790 21288000 */  addu       $a1, $a0, $zero
    /* 27F94 80037794 FFFFA330 */  andi       $v1, $a1, 0xFFFF
    /* 27F98 80037798 80100300 */  sll        $v0, $v1, 2
    /* 27F9C 8003779C 21104300 */  addu       $v0, $v0, $v1
    /* 27FA0 800377A0 40100200 */  sll        $v0, $v0, 1
    /* 27FA4 800377A4 2310E200 */  subu       $v0, $a3, $v0
    /* 27FA8 800377A8 000042A1 */  sb         $v0, 0x0($t2)
    /* 27FAC 800377AC 00240400 */  sll        $a0, $a0, 16
    /* 27FB0 800377B0 15008010 */  beqz       $a0, .L80037808
    /* 27FB4 800377B4 2138A000 */   addu      $a3, $a1, $zero
  .L800377B8:
    /* 27FB8 800377B8 001C0700 */  sll        $v1, $a3, 16
    /* 27FBC 800377BC 03140300 */  sra        $v0, $v1, 16
    /* 27FC0 800377C0 18004D00 */  mult       $v0, $t5
    /* 27FC4 800377C4 01000825 */  addiu      $t0, $t0, 0x1
    /* 27FC8 800377C8 C31F0300 */  sra        $v1, $v1, 31
    /* 27FCC 800377CC FF000431 */  andi       $a0, $t0, 0xFF
    /* 27FD0 800377D0 21204401 */  addu       $a0, $t2, $a0
    /* 27FD4 800377D4 10C00000 */  mfhi       $t8
    /* 27FD8 800377D8 83281800 */  sra        $a1, $t8, 2
    /* 27FDC 800377DC 2328A300 */  subu       $a1, $a1, $v1
    /* 27FE0 800377E0 2130A000 */  addu       $a2, $a1, $zero
    /* 27FE4 800377E4 FFFFC330 */  andi       $v1, $a2, 0xFFFF
    /* 27FE8 800377E8 80100300 */  sll        $v0, $v1, 2
    /* 27FEC 800377EC 21104300 */  addu       $v0, $v0, $v1
    /* 27FF0 800377F0 40100200 */  sll        $v0, $v0, 1
    /* 27FF4 800377F4 2310E200 */  subu       $v0, $a3, $v0
    /* 27FF8 800377F8 000082A0 */  sb         $v0, 0x0($a0)
    /* 27FFC 800377FC 002C0500 */  sll        $a1, $a1, 16
    /* 28000 80037800 EDFFA014 */  bnez       $a1, .L800377B8
    /* 28004 80037804 2138C000 */   addu      $a3, $a2, $zero
  .L80037808:
    /* 28008 80037808 FF002331 */  andi       $v1, $t1, 0xFF
    /* 2800C 8003780C 40100300 */  sll        $v0, $v1, 1
    /* 28010 80037810 21104300 */  addu       $v0, $v0, $v1
    /* 28014 80037814 40100200 */  sll        $v0, $v0, 1
    /* 28018 80037818 21104B00 */  addu       $v0, $v0, $t3
    /* 2801C 8003781C 01000325 */  addiu      $v1, $t0, 0x1
    /* 28020 80037820 0C80013C */  lui        $at, %hi(D_800BCEC7)
    /* 28024 80037824 21082200 */  addu       $at, $at, $v0
    /* 28028 80037828 C7CE23A0 */  sb         $v1, %lo(D_800BCEC7)($at)
    /* 2802C 8003782C 01002925 */  addiu      $t1, $t1, 0x1
    /* 28030 80037830 FF002231 */  andi       $v0, $t1, 0xFF
    /* 28034 80037834 0500422C */  sltiu      $v0, $v0, 0x5
    /* 28038 80037838 08004010 */  beqz       $v0, .L8003785C
    /* 2803C 8003783C 00000000 */   nop
    /* 28040 80037840 D2DD0008 */  j          .L80037748
    /* 28044 80037844 00000000 */   nop
  .L80037848:
    /* 28048 80037848 0100E724 */  addiu      $a3, $a3, 0x1
    /* 2804C 8003784C FF00E230 */  andi       $v0, $a3, 0xFF
    /* 28050 80037850 0400422C */  sltiu      $v0, $v0, 0x4
    /* 28054 80037854 6CFF4014 */  bnez       $v0, .L80037608
    /* 28058 80037858 FF00E230 */   andi      $v0, $a3, 0xFF
  .L8003785C:
    /* 2805C 8003785C 0800E003 */  jr         $ra
    /* 28060 80037860 00000000 */   nop
endlabel Render_SetupColorTable
