.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.4 */

nonmatching Save_DeserializeTail, 0x3D4

glabel Save_DeserializeTail
    /* 303D8 8003FBD8 0A80063C */  lui        $a2, %hi(g_SaveIoCursor)
    /* 303DC 8003FBDC D00EC68C */  lw         $a2, %lo(g_SaveIoCursor)($a2)
    /* 303E0 8003FBE0 0A80073C */  lui        $a3, %hi(D_800A77F0)
    /* 303E4 8003FBE4 F077E724 */  addiu      $a3, $a3, %lo(D_800A77F0)
    /* 303E8 8003FBE8 2510C700 */  or         $v0, $a2, $a3
    /* 303EC 8003FBEC 03004230 */  andi       $v0, $v0, 0x3
    /* 303F0 8003FBF0 16004010 */  beqz       $v0, .L8003FC4C
    /* 303F4 8003FBF4 0008C824 */   addiu     $t0, $a2, 0x800
  .L8003FBF8:
    /* 303F8 8003FBF8 0300C288 */  lwl        $v0, 0x3($a2)
    /* 303FC 8003FBFC 0000C298 */  lwr        $v0, 0x0($a2)
    /* 30400 8003FC00 0700C388 */  lwl        $v1, 0x7($a2)
    /* 30404 8003FC04 0400C398 */  lwr        $v1, 0x4($a2)
    /* 30408 8003FC08 0B00C488 */  lwl        $a0, 0xB($a2)
    /* 3040C 8003FC0C 0800C498 */  lwr        $a0, 0x8($a2)
    /* 30410 8003FC10 0F00C588 */  lwl        $a1, 0xF($a2)
    /* 30414 8003FC14 0C00C598 */  lwr        $a1, 0xC($a2)
    /* 30418 8003FC18 0300E2A8 */  swl        $v0, 0x3($a3)
    /* 3041C 8003FC1C 0000E2B8 */  swr        $v0, 0x0($a3)
    /* 30420 8003FC20 0700E3A8 */  swl        $v1, 0x7($a3)
    /* 30424 8003FC24 0400E3B8 */  swr        $v1, 0x4($a3)
    /* 30428 8003FC28 0B00E4A8 */  swl        $a0, 0xB($a3)
    /* 3042C 8003FC2C 0800E4B8 */  swr        $a0, 0x8($a3)
    /* 30430 8003FC30 0F00E5A8 */  swl        $a1, 0xF($a3)
    /* 30434 8003FC34 0C00E5B8 */  swr        $a1, 0xC($a3)
    /* 30438 8003FC38 1000C624 */  addiu      $a2, $a2, 0x10
    /* 3043C 8003FC3C EEFFC814 */  bne        $a2, $t0, .L8003FBF8
    /* 30440 8003FC40 1000E724 */   addiu     $a3, $a3, 0x10
    /* 30444 8003FC44 1EFF0008 */  j          .L8003FC78
    /* 30448 8003FC48 00000000 */   nop
  .L8003FC4C:
    /* 3044C 8003FC4C 0000C28C */  lw         $v0, 0x0($a2)
    /* 30450 8003FC50 0400C38C */  lw         $v1, 0x4($a2)
    /* 30454 8003FC54 0800C48C */  lw         $a0, 0x8($a2)
    /* 30458 8003FC58 0C00C58C */  lw         $a1, 0xC($a2)
    /* 3045C 8003FC5C 0000E2AC */  sw         $v0, 0x0($a3)
    /* 30460 8003FC60 0400E3AC */  sw         $v1, 0x4($a3)
    /* 30464 8003FC64 0800E4AC */  sw         $a0, 0x8($a3)
    /* 30468 8003FC68 0C00E5AC */  sw         $a1, 0xC($a3)
    /* 3046C 8003FC6C 1000C624 */  addiu      $a2, $a2, 0x10
    /* 30470 8003FC70 F6FFC814 */  bne        $a2, $t0, .L8003FC4C
    /* 30474 8003FC74 1000E724 */   addiu     $a3, $a3, 0x10
  .L8003FC78:
    /* 30478 8003FC78 0A80033C */  lui        $v1, %hi(g_SaveIoCursor)
    /* 3047C 8003FC7C D00E638C */  lw         $v1, %lo(g_SaveIoCursor)($v1)
    /* 30480 8003FC80 0C80083C */  lui        $t0, %hi(g_AyaBattleState)
    /* 30484 8003FC84 208A0825 */  addiu      $t0, $t0, %lo(g_AyaBattleState)
    /* 30488 8003FC88 00086224 */  addiu      $v0, $v1, 0x800
    /* 3048C 8003FC8C 0A80013C */  lui        $at, %hi(g_SaveIoCursor)
    /* 30490 8003FC90 D00E22AC */  sw         $v0, %lo(g_SaveIoCursor)($at)
    /* 30494 8003FC94 0A80043C */  lui        $a0, %hi(g_SaveIoCursor)
    /* 30498 8003FC98 D00E848C */  lw         $a0, %lo(g_SaveIoCursor)($a0)
    /* 3049C 8003FC9C 0A80073C */  lui        $a3, %hi(g_FieldMoveLock)
    /* 304A0 8003FCA0 E8D2E724 */  addiu      $a3, $a3, %lo(g_FieldMoveLock)
    /* 304A4 8003FCA4 03086288 */  lwl        $v0, 0x803($v1)
    /* 304A8 8003FCA8 00086298 */  lwr        $v0, 0x800($v1)
    /* 304AC 8003FCAC 00000000 */  nop
    /* 304B0 8003FCB0 0300E2A8 */  swl        $v0, 0x3($a3)
    /* 304B4 8003FCB4 0000E2B8 */  swr        $v0, 0x0($a3)
    /* 304B8 8003FCB8 04008224 */  addiu      $v0, $a0, 0x4
    /* 304BC 8003FCBC 0A80013C */  lui        $at, %hi(g_SaveIoCursor)
    /* 304C0 8003FCC0 D00E22AC */  sw         $v0, %lo(g_SaveIoCursor)($at)
    /* 304C4 8003FCC4 0A80033C */  lui        $v1, %hi(g_SaveIoCursor)
    /* 304C8 8003FCC8 D00E638C */  lw         $v1, %lo(g_SaveIoCursor)($v1)
    /* 304CC 8003FCCC 0A80073C */  lui        $a3, %hi(g_SceneDispatchToken)
    /* 304D0 8003FCD0 80D2E724 */  addiu      $a3, $a3, %lo(g_SceneDispatchToken)
    /* 304D4 8003FCD4 07008288 */  lwl        $v0, 0x7($a0)
    /* 304D8 8003FCD8 04008298 */  lwr        $v0, 0x4($a0)
    /* 304DC 8003FCDC 00000000 */  nop
    /* 304E0 8003FCE0 0300E2A8 */  swl        $v0, 0x3($a3)
    /* 304E4 8003FCE4 0000E2B8 */  swr        $v0, 0x0($a3)
    /* 304E8 8003FCE8 04006224 */  addiu      $v0, $v1, 0x4
    /* 304EC 8003FCEC 0A80013C */  lui        $at, %hi(g_SaveIoCursor)
    /* 304F0 8003FCF0 D00E22AC */  sw         $v0, %lo(g_SaveIoCursor)($at)
    /* 304F4 8003FCF4 0A80043C */  lui        $a0, %hi(g_SaveIoCursor)
    /* 304F8 8003FCF8 D00E848C */  lw         $a0, %lo(g_SaveIoCursor)($a0)
    /* 304FC 8003FCFC 0A80073C */  lui        $a3, %hi(g_GameStateFlags)
    /* 30500 8003FD00 A0D1E724 */  addiu      $a3, $a3, %lo(g_GameStateFlags)
    /* 30504 8003FD04 07006288 */  lwl        $v0, 0x7($v1)
    /* 30508 8003FD08 04006298 */  lwr        $v0, 0x4($v1)
    /* 3050C 8003FD0C 00000000 */  nop
    /* 30510 8003FD10 0300E2A8 */  swl        $v0, 0x3($a3)
    /* 30514 8003FD14 0000E2B8 */  swr        $v0, 0x0($a3)
    /* 30518 8003FD18 04008224 */  addiu      $v0, $a0, 0x4
    /* 3051C 8003FD1C 0A80013C */  lui        $at, %hi(g_SaveIoCursor)
    /* 30520 8003FD20 D00E22AC */  sw         $v0, %lo(g_SaveIoCursor)($at)
    /* 30524 8003FD24 0A80033C */  lui        $v1, %hi(g_SaveIoCursor)
    /* 30528 8003FD28 D00E638C */  lw         $v1, %lo(g_SaveIoCursor)($v1)
    /* 3052C 8003FD2C 0B80073C */  lui        $a3, %hi(D_800B0CDC)
    /* 30530 8003FD30 DC0CE724 */  addiu      $a3, $a3, %lo(D_800B0CDC)
    /* 30534 8003FD34 07008288 */  lwl        $v0, 0x7($a0)
    /* 30538 8003FD38 04008298 */  lwr        $v0, 0x4($a0)
    /* 3053C 8003FD3C 00000000 */  nop
    /* 30540 8003FD40 0300E2A8 */  swl        $v0, 0x3($a3)
    /* 30544 8003FD44 0000E2B8 */  swr        $v0, 0x0($a3)
    /* 30548 8003FD48 04006224 */  addiu      $v0, $v1, 0x4
    /* 3054C 8003FD4C 0A80013C */  lui        $at, %hi(g_SaveIoCursor)
    /* 30550 8003FD50 D00E22AC */  sw         $v0, %lo(g_SaveIoCursor)($at)
    /* 30554 8003FD54 0A80043C */  lui        $a0, %hi(g_SaveIoCursor)
    /* 30558 8003FD58 D00E848C */  lw         $a0, %lo(g_SaveIoCursor)($a0)
    /* 3055C 8003FD5C 04006280 */  lb         $v0, 0x4($v1)
    /* 30560 8003FD60 05006580 */  lb         $a1, 0x5($v1)
    /* 30564 8003FD64 0B80013C */  lui        $at, %hi(D_800B0CE0)
    /* 30568 8003FD68 E00C22A0 */  sb         $v0, %lo(D_800B0CE0)($at)
    /* 3056C 8003FD6C 0B80013C */  lui        $at, %hi(D_800B0CE1)
    /* 30570 8003FD70 E10C25A0 */  sb         $a1, %lo(D_800B0CE1)($at)
    /* 30574 8003FD74 02008224 */  addiu      $v0, $a0, 0x2
    /* 30578 8003FD78 0A80013C */  lui        $at, %hi(g_SaveIoCursor)
    /* 3057C 8003FD7C D00E22AC */  sw         $v0, %lo(g_SaveIoCursor)($at)
    /* 30580 8003FD80 0A80033C */  lui        $v1, %hi(g_SaveIoCursor)
    /* 30584 8003FD84 D00E638C */  lw         $v1, %lo(g_SaveIoCursor)($v1)
    /* 30588 8003FD88 02008280 */  lb         $v0, 0x2($a0)
    /* 3058C 8003FD8C 03008580 */  lb         $a1, 0x3($a0)
    /* 30590 8003FD90 0B80013C */  lui        $at, %hi(D_800B0CE2)
    /* 30594 8003FD94 E20C22A0 */  sb         $v0, %lo(D_800B0CE2)($at)
    /* 30598 8003FD98 0B80013C */  lui        $at, %hi(D_800B0CE3)
    /* 3059C 8003FD9C E30C25A0 */  sb         $a1, %lo(D_800B0CE3)($at)
    /* 305A0 8003FDA0 02006224 */  addiu      $v0, $v1, 0x2
    /* 305A4 8003FDA4 0A80013C */  lui        $at, %hi(g_SaveIoCursor)
    /* 305A8 8003FDA8 D00E22AC */  sw         $v0, %lo(g_SaveIoCursor)($at)
    /* 305AC 8003FDAC 0A80073C */  lui        $a3, %hi(g_SaveIoCursor)
    /* 305B0 8003FDB0 D00EE78C */  lw         $a3, %lo(g_SaveIoCursor)($a3)
    /* 305B4 8003FDB4 02006280 */  lb         $v0, 0x2($v1)
    /* 305B8 8003FDB8 03006480 */  lb         $a0, 0x3($v1)
    /* 305BC 8003FDBC 0B80013C */  lui        $at, %hi(D_800B0CE4)
    /* 305C0 8003FDC0 E40C22A0 */  sb         $v0, %lo(D_800B0CE4)($at)
    /* 305C4 8003FDC4 0B80013C */  lui        $at, %hi(D_800B0CE5)
    /* 305C8 8003FDC8 E50C24A0 */  sb         $a0, %lo(D_800B0CE5)($at)
    /* 305CC 8003FDCC 0400E224 */  addiu      $v0, $a3, 0x4
    /* 305D0 8003FDD0 21304000 */  addu       $a2, $v0, $zero
    /* 305D4 8003FDD4 2518C800 */  or         $v1, $a2, $t0
    /* 305D8 8003FDD8 0200E224 */  addiu      $v0, $a3, 0x2
    /* 305DC 8003FDDC 0A80013C */  lui        $at, %hi(g_SaveIoCursor)
    /* 305E0 8003FDE0 D00E22AC */  sw         $v0, %lo(g_SaveIoCursor)($at)
    /* 305E4 8003FDE4 0200E490 */  lbu        $a0, 0x2($a3)
    /* 305E8 8003FDE8 0300E224 */  addiu      $v0, $a3, 0x3
    /* 305EC 8003FDEC 0A80013C */  lui        $at, %hi(g_SaveIoCursor)
    /* 305F0 8003FDF0 D00E22AC */  sw         $v0, %lo(g_SaveIoCursor)($at)
    /* 305F4 8003FDF4 0B80013C */  lui        $at, %hi(D_800B0CE6)
    /* 305F8 8003FDF8 E60C24A0 */  sb         $a0, %lo(D_800B0CE6)($at)
    /* 305FC 8003FDFC 0300E290 */  lbu        $v0, 0x3($a3)
    /* 30600 8003FE00 03006330 */  andi       $v1, $v1, 0x3
    /* 30604 8003FE04 0C80013C */  lui        $at, %hi(D_800BCFEE)
    /* 30608 8003FE08 EECF22A0 */  sb         $v0, %lo(D_800BCFEE)($at)
    /* 3060C 8003FE0C 0A80013C */  lui        $at, %hi(g_SaveIoCursor)
    /* 30610 8003FE10 D00E26AC */  sw         $a2, %lo(g_SaveIoCursor)($at)
    /* 30614 8003FE14 17006010 */  beqz       $v1, .L8003FE74
    /* 30618 8003FE18 00000000 */   nop
    /* 3061C 8003FE1C 7400E724 */  addiu      $a3, $a3, 0x74
  .L8003FE20:
    /* 30620 8003FE20 0300C288 */  lwl        $v0, 0x3($a2)
    /* 30624 8003FE24 0000C298 */  lwr        $v0, 0x0($a2)
    /* 30628 8003FE28 0700C388 */  lwl        $v1, 0x7($a2)
    /* 3062C 8003FE2C 0400C398 */  lwr        $v1, 0x4($a2)
    /* 30630 8003FE30 0B00C488 */  lwl        $a0, 0xB($a2)
    /* 30634 8003FE34 0800C498 */  lwr        $a0, 0x8($a2)
    /* 30638 8003FE38 0F00C588 */  lwl        $a1, 0xF($a2)
    /* 3063C 8003FE3C 0C00C598 */  lwr        $a1, 0xC($a2)
    /* 30640 8003FE40 030002A9 */  swl        $v0, 0x3($t0)
    /* 30644 8003FE44 000002B9 */  swr        $v0, 0x0($t0)
    /* 30648 8003FE48 070003A9 */  swl        $v1, 0x7($t0)
    /* 3064C 8003FE4C 040003B9 */  swr        $v1, 0x4($t0)
    /* 30650 8003FE50 0B0004A9 */  swl        $a0, 0xB($t0)
    /* 30654 8003FE54 080004B9 */  swr        $a0, 0x8($t0)
    /* 30658 8003FE58 0F0005A9 */  swl        $a1, 0xF($t0)
    /* 3065C 8003FE5C 0C0005B9 */  swr        $a1, 0xC($t0)
    /* 30660 8003FE60 1000C624 */  addiu      $a2, $a2, 0x10
    /* 30664 8003FE64 EEFFC714 */  bne        $a2, $a3, .L8003FE20
    /* 30668 8003FE68 10000825 */   addiu     $t0, $t0, 0x10
    /* 3066C 8003FE6C AAFF0008 */  j          .L8003FEA8
    /* 30670 8003FE70 FFFF053C */   lui       $a1, (0xFFFF2679 >> 16)
  .L8003FE74:
    /* 30674 8003FE74 7400E724 */  addiu      $a3, $a3, 0x74
  .L8003FE78:
    /* 30678 8003FE78 0000C28C */  lw         $v0, 0x0($a2)
    /* 3067C 8003FE7C 0400C38C */  lw         $v1, 0x4($a2)
    /* 30680 8003FE80 0800C48C */  lw         $a0, 0x8($a2)
    /* 30684 8003FE84 0C00C58C */  lw         $a1, 0xC($a2)
    /* 30688 8003FE88 000002AD */  sw         $v0, 0x0($t0)
    /* 3068C 8003FE8C 040003AD */  sw         $v1, 0x4($t0)
    /* 30690 8003FE90 080004AD */  sw         $a0, 0x8($t0)
    /* 30694 8003FE94 0C0005AD */  sw         $a1, 0xC($t0)
    /* 30698 8003FE98 1000C624 */  addiu      $a2, $a2, 0x10
    /* 3069C 8003FE9C F6FFC714 */  bne        $a2, $a3, .L8003FE78
    /* 306A0 8003FEA0 10000825 */   addiu     $t0, $t0, 0x10
    /* 306A4 8003FEA4 FFFF053C */  lui        $a1, (0xFFFF2679 >> 16)
  .L8003FEA8:
    /* 306A8 8003FEA8 0A80033C */  lui        $v1, %hi(g_SaveIoCursor)
    /* 306AC 8003FEAC D00E638C */  lw         $v1, %lo(g_SaveIoCursor)($v1)
    /* 306B0 8003FEB0 7926A534 */  ori        $a1, $a1, (0xFFFF2679 & 0xFFFF)
    /* 306B4 8003FEB4 70006224 */  addiu      $v0, $v1, 0x70
    /* 306B8 8003FEB8 0A80013C */  lui        $at, %hi(g_SaveIoCursor)
    /* 306BC 8003FEBC D00E22AC */  sw         $v0, %lo(g_SaveIoCursor)($at)
    /* 306C0 8003FEC0 0A80043C */  lui        $a0, %hi(g_SaveIoCursor)
    /* 306C4 8003FEC4 D00E848C */  lw         $a0, %lo(g_SaveIoCursor)($a0)
    /* 306C8 8003FEC8 0B80083C */  lui        $t0, %hi(D_800B0CB0)
    /* 306CC 8003FECC B00C0825 */  addiu      $t0, $t0, %lo(D_800B0CB0)
    /* 306D0 8003FED0 73006288 */  lwl        $v0, 0x73($v1)
    /* 306D4 8003FED4 70006298 */  lwr        $v0, 0x70($v1)
    /* 306D8 8003FED8 77006688 */  lwl        $a2, 0x77($v1)
    /* 306DC 8003FEDC 74006698 */  lwr        $a2, 0x74($v1)
    /* 306E0 8003FEE0 7B006788 */  lwl        $a3, 0x7B($v1)
    /* 306E4 8003FEE4 78006798 */  lwr        $a3, 0x78($v1)
    /* 306E8 8003FEE8 030002A9 */  swl        $v0, 0x3($t0)
    /* 306EC 8003FEEC 000002B9 */  swr        $v0, 0x0($t0)
    /* 306F0 8003FEF0 070006A9 */  swl        $a2, 0x7($t0)
    /* 306F4 8003FEF4 040006B9 */  swr        $a2, 0x4($t0)
    /* 306F8 8003FEF8 0B0007A9 */  swl        $a3, 0xB($t0)
    /* 306FC 8003FEFC 080007B9 */  swr        $a3, 0x8($t0)
    /* 30700 8003FF00 7F006288 */  lwl        $v0, 0x7F($v1)
    /* 30704 8003FF04 7C006298 */  lwr        $v0, 0x7C($v1)
    /* 30708 8003FF08 83006688 */  lwl        $a2, 0x83($v1)
    /* 3070C 8003FF0C 80006698 */  lwr        $a2, 0x80($v1)
    /* 30710 8003FF10 87006788 */  lwl        $a3, 0x87($v1)
    /* 30714 8003FF14 84006798 */  lwr        $a3, 0x84($v1)
    /* 30718 8003FF18 0F0002A9 */  swl        $v0, 0xF($t0)
    /* 3071C 8003FF1C 0C0002B9 */  swr        $v0, 0xC($t0)
    /* 30720 8003FF20 130006A9 */  swl        $a2, 0x13($t0)
    /* 30724 8003FF24 100006B9 */  swr        $a2, 0x10($t0)
    /* 30728 8003FF28 170007A9 */  swl        $a3, 0x17($t0)
    /* 3072C 8003FF2C 140007B9 */  swr        $a3, 0x14($t0)
    /* 30730 8003FF30 18008224 */  addiu      $v0, $a0, 0x18
    /* 30734 8003FF34 0A80013C */  lui        $at, %hi(g_SaveIoCursor)
    /* 30738 8003FF38 D00E22AC */  sw         $v0, %lo(g_SaveIoCursor)($at)
    /* 3073C 8003FF3C 0A80083C */  lui        $t0, %hi(D_8009D1B0)
    /* 30740 8003FF40 B0D10825 */  addiu      $t0, $t0, %lo(D_8009D1B0)
    /* 30744 8003FF44 1B008388 */  lwl        $v1, 0x1B($a0)
    /* 30748 8003FF48 18008398 */  lwr        $v1, 0x18($a0)
    /* 3074C 8003FF4C 1F008688 */  lwl        $a2, 0x1F($a0)
    /* 30750 8003FF50 1C008698 */  lwr        $a2, 0x1C($a0)
    /* 30754 8003FF54 030003A9 */  swl        $v1, 0x3($t0)
    /* 30758 8003FF58 000003B9 */  swr        $v1, 0x0($t0)
    /* 3075C 8003FF5C 070006A9 */  swl        $a2, 0x7($t0)
    /* 30760 8003FF60 040006B9 */  swr        $a2, 0x4($t0)
    /* 30764 8003FF64 F6FF0424 */  addiu      $a0, $zero, -0xA
    /* 30768 8003FF68 0A80023C */  lui        $v0, %hi(g_GameStateFlags)
    /* 3076C 8003FF6C A0D1428C */  lw         $v0, %lo(g_GameStateFlags)($v0)
    /* 30770 8003FF70 0A80033C */  lui        $v1, %hi(g_SaveIoCursor)
    /* 30774 8003FF74 D00E638C */  lw         $v1, %lo(g_SaveIoCursor)($v1)
    /* 30778 8003FF78 24104500 */  and        $v0, $v0, $a1
    /* 3077C 8003FF7C 0A80013C */  lui        $at, %hi(g_GameStateFlags)
    /* 30780 8003FF80 A0D122AC */  sw         $v0, %lo(g_GameStateFlags)($at)
    /* 30784 8003FF84 0A80023C */  lui        $v0, %hi(g_FieldMoveLock)
    /* 30788 8003FF88 E8D2428C */  lw         $v0, %lo(g_FieldMoveLock)($v0)
    /* 3078C 8003FF8C 08006324 */  addiu      $v1, $v1, 0x8
    /* 30790 8003FF90 0A80013C */  lui        $at, %hi(g_SaveIoCursor)
    /* 30794 8003FF94 D00E23AC */  sw         $v1, %lo(g_SaveIoCursor)($at)
    /* 30798 8003FF98 24104400 */  and        $v0, $v0, $a0
    /* 3079C 8003FF9C 0A80013C */  lui        $at, %hi(g_FieldMoveLock)
    /* 307A0 8003FFA0 E8D222AC */  sw         $v0, %lo(g_FieldMoveLock)($at)
    /* 307A4 8003FFA4 0800E003 */  jr         $ra
    /* 307A8 8003FFA8 00000000 */   nop
endlabel Save_DeserializeTail
