.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.4 */

nonmatching Scene_LoadEntityTextures, 0x6AC

glabel Scene_LoadEntityTextures
    /* 5CDBC 8006C5BC 0B80023C */  lui        $v0, %hi(D_800B0CE2)
    /* 5CDC0 8006C5C0 E20C4290 */  lbu        $v0, %lo(D_800B0CE2)($v0)
    /* 5CDC4 8006C5C4 78FFBD27 */  addiu      $sp, $sp, -0x88
    /* 5CDC8 8006C5C8 7C00B5AF */  sw         $s5, 0x7C($sp)
    /* 5CDCC 8006C5CC 0B80153C */  lui        $s5, %hi(D_800B0CE4)
    /* 5CDD0 8006C5D0 E40CB582 */  lb         $s5, %lo(D_800B0CE4)($s5)
    /* 5CDD4 8006C5D4 8000B6AF */  sw         $s6, 0x80($sp)
    /* 5CDD8 8006C5D8 0B80163C */  lui        $s6, %hi(g_PeImageBaseLba)
    /* 5CDDC 8006C5DC D80DD68E */  lw         $s6, %lo(g_PeImageBaseLba)($s6)
    /* 5CDE0 8006C5E0 7800B4AF */  sw         $s4, 0x78($sp)
    /* 5CDE4 8006C5E4 0B80143C */  lui        $s4, %hi(g_GameState)
    /* 5CDE8 8006C5E8 D80C9426 */  addiu      $s4, $s4, %lo(g_GameState)
    /* 5CDEC 8006C5EC 8400BFAF */  sw         $ra, 0x84($sp)
    /* 5CDF0 8006C5F0 7400B3AF */  sw         $s3, 0x74($sp)
    /* 5CDF4 8006C5F4 7000B2AF */  sw         $s2, 0x70($sp)
    /* 5CDF8 8006C5F8 6C00B1AF */  sw         $s1, 0x6C($sp)
    /* 5CDFC 8006C5FC F6FF4224 */  addiu      $v0, $v0, -0xA
    /* 5CE00 8006C600 0500422C */  sltiu      $v0, $v0, 0x5
    /* 5CE04 8006C604 8C014010 */  beqz       $v0, .L8006CC38
    /* 5CE08 8006C608 6800B0AF */   sw        $s0, 0x68($sp)
  .L8006C60C:
    /* 5CE0C 8006C60C EE008392 */  lbu        $v1, 0xEE($s4)
    /* 5CE10 8006C610 00000000 */  nop
    /* 5CE14 8006C614 0E00622C */  sltiu      $v0, $v1, 0xE
    /* 5CE18 8006C618 87014010 */  beqz       $v0, .L8006CC38
    /* 5CE1C 8006C61C 80100300 */   sll       $v0, $v1, 2
    /* 5CE20 8006C620 0180013C */  lui        $at, %hi(jtbl_800113F0)
    /* 5CE24 8006C624 21082200 */  addu       $at, $at, $v0
    /* 5CE28 8006C628 F013228C */  lw         $v0, %lo(jtbl_800113F0)($at)
    /* 5CE2C 8006C62C 00000000 */  nop
    /* 5CE30 8006C630 08004000 */  jr         $v0
    /* 5CE34 8006C634 00000000 */   nop
  jlabel .L8006C638
    /* 5CE38 8006C638 0E008392 */  lbu        $v1, 0xE($s4)
    /* 5CE3C 8006C63C 00000000 */  nop
    /* 5CE40 8006C640 01006230 */  andi       $v0, $v1, 0x1
    /* 5CE44 8006C644 03004010 */  beqz       $v0, .L8006C654
    /* 5CE48 8006C648 01000224 */   addiu     $v0, $zero, 0x1
    /* 5CE4C 8006C64C 83B10108 */  j          .L8006C60C
    /* 5CE50 8006C650 EE0082A2 */   sb        $v0, 0xEE($s4)
  .L8006C654:
    /* 5CE54 8006C654 02006230 */  andi       $v0, $v1, 0x2
    /* 5CE58 8006C658 DA004014 */  bnez       $v0, .L8006C9C4
    /* 5CE5C 8006C65C 0B000224 */   addiu     $v0, $zero, 0xB
    /* 5CE60 8006C660 1AB3010C */  jal        Scene_UpdateBgDraw
    /* 5CE64 8006C664 00000000 */   nop
    /* 5CE68 8006C668 0FB30108 */  j          .L8006CC3C
    /* 5CE6C 8006C66C 21100000 */   addu      $v0, $zero, $zero
  jlabel .L8006C670
    /* 5CE70 8006C670 FEFFA226 */  addiu      $v0, $s5, -0x2
    /* 5CE74 8006C674 0500422C */  sltiu      $v0, $v0, 0x5
    /* 5CE78 8006C678 3D004010 */  beqz       $v0, .L8006C770
    /* 5CE7C 8006C67C 2600A226 */   addiu     $v0, $s5, 0x26
    /* 5CE80 8006C680 9401858E */  lw         $a1, 0x194($s4)
    /* 5CE84 8006C684 2800A2AF */  sw         $v0, 0x28($sp)
    /* 5CE88 8006C688 40100200 */  sll        $v0, $v0, 1
    /* 5CE8C 8006C68C 0980013C */  lui        $at, %hi(g_EntityTexLbaStartTbl)
    /* 5CE90 8006C690 21082200 */  addu       $at, $at, $v0
    /* 5CE94 8006C694 D8302394 */  lhu        $v1, %lo(g_EntityTexLbaStartTbl)($at)
    /* 5CE98 8006C698 0980013C */  lui        $at, %hi(g_EntityTexLbaEndTbl)
    /* 5CE9C 8006C69C 21082200 */  addu       $at, $at, $v0
    /* 5CEA0 8006C6A0 DA302694 */  lhu        $a2, %lo(g_EntityTexLbaEndTbl)($at)
    /* 5CEA4 8006C6A4 2120C302 */  addu       $a0, $s6, $v1
    /* 5CEA8 8006C6A8 AAB9010C */  jal        CdRom_ReadSectorsFromLba
    /* 5CEAC 8006C6AC 2330C300 */   subu      $a2, $a2, $v1
    /* 5CEB0 8006C6B0 1AB3010C */  jal        Scene_UpdateBgDraw
    /* 5CEB4 8006C6B4 21804000 */   addu      $s0, $v0, $zero
    /* 5CEB8 8006C6B8 FFFF0224 */  addiu      $v0, $zero, -0x1
    /* 5CEBC 8006C6BC CC000212 */  beq        $s0, $v0, .L8006C9F0
    /* 5CEC0 8006C6C0 02000224 */   addiu     $v0, $zero, 0x2
    /* 5CEC4 8006C6C4 7CB20108 */  j          .L8006C9F0
    /* 5CEC8 8006C6C8 EE0082A2 */   sb        $v0, 0xEE($s4)
  jlabel .L8006C6CC
    /* 5CECC 8006C6CC FAB9010C */  jal        CdRom_PollReady
    /* 5CED0 8006C6D0 00000000 */   nop
    /* 5CED4 8006C6D4 21804000 */  addu       $s0, $v0, $zero
    /* 5CED8 8006C6D8 FFFF0224 */  addiu      $v0, $zero, -0x1
    /* 5CEDC 8006C6DC C3000212 */  beq        $s0, $v0, .L8006C9EC
    /* 5CEE0 8006C6E0 01000224 */   addiu     $v0, $zero, 0x1
    /* 5CEE4 8006C6E4 0B000012 */  beqz       $s0, .L8006C714
    /* 5CEE8 8006C6E8 03000224 */   addiu     $v0, $zero, 0x3
    /* 5CEEC 8006C6EC 0A80023C */  lui        $v0, %hi(g_GameStateFlags)
    /* 5CEF0 8006C6F0 A0D1428C */  lw         $v0, %lo(g_GameStateFlags)($v0)
    /* 5CEF4 8006C6F4 00000000 */  nop
    /* 5CEF8 8006C6F8 02004230 */  andi       $v0, $v0, 0x2
    /* 5CEFC 8006C6FC 4F014014 */  bnez       $v0, .L8006CC3C
    /* 5CF00 8006C700 01000224 */   addiu     $v0, $zero, 0x1
    /* 5CF04 8006C704 1AB3010C */  jal        Scene_UpdateBgDraw
    /* 5CF08 8006C708 00000000 */   nop
    /* 5CF0C 8006C70C 0FB30108 */  j          .L8006CC3C
    /* 5CF10 8006C710 01000224 */   addiu     $v0, $zero, 0x1
  .L8006C714:
    /* 5CF14 8006C714 83B10108 */  j          .L8006C60C
    /* 5CF18 8006C718 EE0082A2 */   sb        $v0, 0xEE($s4)
  jlabel .L8006C71C
    /* 5CF1C 8006C71C 9401928E */  lw         $s2, 0x194($s4)
    /* 5CF20 8006C720 3F00023C */  lui        $v0, (0x3FFFFF >> 16)
    /* 5CF24 8006C724 0400438E */  lw         $v1, 0x4($s2)
    /* 5CF28 8006C728 FFFF4234 */  ori        $v0, $v0, (0x3FFFFF & 0xFFFF)
    /* 5CF2C 8006C72C 21984302 */  addu       $s3, $s2, $v1
    /* 5CF30 8006C730 2800638E */  lw         $v1, 0x28($s3)
    /* 5CF34 8006C734 21800000 */  addu       $s0, $zero, $zero
    /* 5CF38 8006C738 24106200 */  and        $v0, $v1, $v0
    /* 5CF3C 8006C73C 821D0300 */  srl        $v1, $v1, 22
    /* 5CF40 8006C740 0B006010 */  beqz       $v1, .L8006C770
    /* 5CF44 8006C744 21204202 */   addu      $a0, $s2, $v0
    /* 5CF48 8006C748 21888000 */  addu       $s1, $a0, $zero
  .L8006C74C:
    /* 5CF4C 8006C74C 21202002 */  addu       $a0, $s1, $zero
    /* 5CF50 8006C750 70B8010C */  jal        Gpu_LoadTimAsset
    /* 5CF54 8006C754 21284002 */   addu      $a1, $s2, $zero
    /* 5CF58 8006C758 2800628E */  lw         $v0, 0x28($s3)
    /* 5CF5C 8006C75C 01001026 */  addiu      $s0, $s0, 0x1
    /* 5CF60 8006C760 82150200 */  srl        $v0, $v0, 22
    /* 5CF64 8006C764 2B100202 */  sltu       $v0, $s0, $v0
    /* 5CF68 8006C768 F8FF4014 */  bnez       $v0, .L8006C74C
    /* 5CF6C 8006C76C 14003126 */   addiu     $s1, $s1, 0x14
  .L8006C770:
    /* 5CF70 8006C770 04000224 */  addiu      $v0, $zero, 0x4
    /* 5CF74 8006C774 83B10108 */  j          .L8006C60C
    /* 5CF78 8006C778 EE0082A2 */   sb        $v0, 0xEE($s4)
  jlabel .L8006C77C
    /* 5CF7C 8006C77C 0A008292 */  lbu        $v0, 0xA($s4)
    /* 5CF80 8006C780 5801858E */  lw         $a1, 0x158($s4)
    /* 5CF84 8006C784 F6FF4224 */  addiu      $v0, $v0, -0xA
    /* 5CF88 8006C788 C21F0200 */  srl        $v1, $v0, 31
    /* 5CF8C 8006C78C 21104300 */  addu       $v0, $v0, $v1
    /* 5CF90 8006C790 43100200 */  sra        $v0, $v0, 1
    /* 5CF94 8006C794 C0100200 */  sll        $v0, $v0, 3
    /* 5CF98 8006C798 21105500 */  addu       $v0, $v0, $s5
    /* 5CF9C 8006C79C 16004224 */  addiu      $v0, $v0, 0x16
    /* 5CFA0 8006C7A0 2800A2AF */  sw         $v0, 0x28($sp)
    /* 5CFA4 8006C7A4 40100200 */  sll        $v0, $v0, 1
    /* 5CFA8 8006C7A8 0980013C */  lui        $at, %hi(g_EntityTexLbaStartTbl)
    /* 5CFAC 8006C7AC 21082200 */  addu       $at, $at, $v0
    /* 5CFB0 8006C7B0 D8302394 */  lhu        $v1, %lo(g_EntityTexLbaStartTbl)($at)
    /* 5CFB4 8006C7B4 0980013C */  lui        $at, %hi(g_EntityTexLbaEndTbl)
    /* 5CFB8 8006C7B8 21082200 */  addu       $at, $at, $v0
    /* 5CFBC 8006C7BC DA302694 */  lhu        $a2, %lo(g_EntityTexLbaEndTbl)($at)
    /* 5CFC0 8006C7C0 2120C302 */  addu       $a0, $s6, $v1
    /* 5CFC4 8006C7C4 AAB9010C */  jal        CdRom_ReadSectorsFromLba
    /* 5CFC8 8006C7C8 2330C300 */   subu      $a2, $a2, $v1
    /* 5CFCC 8006C7CC FFFF0324 */  addiu      $v1, $zero, -0x1
    /* 5CFD0 8006C7D0 02004310 */  beq        $v0, $v1, .L8006C7DC
    /* 5CFD4 8006C7D4 05000224 */   addiu     $v0, $zero, 0x5
    /* 5CFD8 8006C7D8 EE0082A2 */  sb         $v0, 0xEE($s4)
  .L8006C7DC:
    /* 5CFDC 8006C7DC 0A80023C */  lui        $v0, %hi(g_GameStateFlags)
    /* 5CFE0 8006C7E0 A0D1428C */  lw         $v0, %lo(g_GameStateFlags)($v0)
    /* 5CFE4 8006C7E4 00000000 */  nop
    /* 5CFE8 8006C7E8 02004230 */  andi       $v0, $v0, 0x2
    /* 5CFEC 8006C7EC 13014014 */  bnez       $v0, .L8006CC3C
    /* 5CFF0 8006C7F0 01000224 */   addiu     $v0, $zero, 0x1
    /* 5CFF4 8006C7F4 1AB3010C */  jal        Scene_UpdateBgDraw
    /* 5CFF8 8006C7F8 00000000 */   nop
    /* 5CFFC 8006C7FC 0FB30108 */  j          .L8006CC3C
    /* 5D000 8006C800 01000224 */   addiu     $v0, $zero, 0x1
  jlabel .L8006C804
    /* 5D004 8006C804 FAB9010C */  jal        CdRom_PollReady
    /* 5D008 8006C808 00000000 */   nop
    /* 5D00C 8006C80C 21804000 */  addu       $s0, $v0, $zero
    /* 5D010 8006C810 FFFF0224 */  addiu      $v0, $zero, -0x1
    /* 5D014 8006C814 75000212 */  beq        $s0, $v0, .L8006C9EC
    /* 5D018 8006C818 04000224 */   addiu     $v0, $zero, 0x4
    /* 5D01C 8006C81C 0B000012 */  beqz       $s0, .L8006C84C
    /* 5D020 8006C820 06000224 */   addiu     $v0, $zero, 0x6
    /* 5D024 8006C824 0A80023C */  lui        $v0, %hi(g_GameStateFlags)
    /* 5D028 8006C828 A0D1428C */  lw         $v0, %lo(g_GameStateFlags)($v0)
    /* 5D02C 8006C82C 00000000 */  nop
    /* 5D030 8006C830 02004230 */  andi       $v0, $v0, 0x2
    /* 5D034 8006C834 01014014 */  bnez       $v0, .L8006CC3C
    /* 5D038 8006C838 01000224 */   addiu     $v0, $zero, 0x1
    /* 5D03C 8006C83C 1AB3010C */  jal        Scene_UpdateBgDraw
    /* 5D040 8006C840 00000000 */   nop
    /* 5D044 8006C844 0FB30108 */  j          .L8006CC3C
    /* 5D048 8006C848 01000224 */   addiu     $v0, $zero, 0x1
  .L8006C84C:
    /* 5D04C 8006C84C 83B10108 */  j          .L8006C60C
    /* 5D050 8006C850 EE0082A2 */   sb        $v0, 0xEE($s4)
  jlabel .L8006C854
    /* 5D054 8006C854 5801928E */  lw         $s2, 0x158($s4)
    /* 5D058 8006C858 3F00023C */  lui        $v0, (0x3FFFFF >> 16)
    /* 5D05C 8006C85C 0400438E */  lw         $v1, 0x4($s2)
    /* 5D060 8006C860 FFFF4234 */  ori        $v0, $v0, (0x3FFFFF & 0xFFFF)
    /* 5D064 8006C864 21984302 */  addu       $s3, $s2, $v1
    /* 5D068 8006C868 1000638E */  lw         $v1, 0x10($s3)
    /* 5D06C 8006C86C 21800000 */  addu       $s0, $zero, $zero
    /* 5D070 8006C870 24106200 */  and        $v0, $v1, $v0
    /* 5D074 8006C874 821D0300 */  srl        $v1, $v1, 22
    /* 5D078 8006C878 11006010 */  beqz       $v1, .L8006C8C0
    /* 5D07C 8006C87C 21104202 */   addu      $v0, $s2, $v0
    /* 5D080 8006C880 FF00053C */  lui        $a1, (0xFFFFFF >> 16)
    /* 5D084 8006C884 FFFFA534 */  ori        $a1, $a1, (0xFFFFFF & 0xFFFF)
    /* 5D088 8006C888 21204000 */  addu       $a0, $v0, $zero
  .L8006C88C:
    /* 5D08C 8006C88C 07008390 */  lbu        $v1, 0x7($a0)
    /* 5D090 8006C890 0400828C */  lw         $v0, 0x4($a0)
    /* 5D094 8006C894 80180300 */  sll        $v1, $v1, 2
    /* 5D098 8006C898 21187400 */  addu       $v1, $v1, $s4
    /* 5D09C 8006C89C 24104500 */  and        $v0, $v0, $a1
    /* 5D0A0 8006C8A0 21104202 */  addu       $v0, $s2, $v0
    /* 5D0A4 8006C8A4 C00162AC */  sw         $v0, 0x1C0($v1)
    /* 5D0A8 8006C8A8 1000628E */  lw         $v0, 0x10($s3)
    /* 5D0AC 8006C8AC 01001026 */  addiu      $s0, $s0, 0x1
    /* 5D0B0 8006C8B0 82150200 */  srl        $v0, $v0, 22
    /* 5D0B4 8006C8B4 2B100202 */  sltu       $v0, $s0, $v0
    /* 5D0B8 8006C8B8 F4FF4014 */  bnez       $v0, .L8006C88C
    /* 5D0BC 8006C8BC 0C008424 */   addiu     $a0, $a0, 0xC
  .L8006C8C0:
    /* 5D0C0 8006C8C0 100080A2 */  sb         $zero, 0x10($s4)
    /* 5D0C4 8006C8C4 21800000 */  addu       $s0, $zero, $zero
    /* 5D0C8 8006C8C8 21188002 */  addu       $v1, $s4, $zero
  .L8006C8CC:
    /* 5D0CC 8006C8CC 340160AC */  sw         $zero, 0x134($v1)
    /* 5D0D0 8006C8D0 01001026 */  addiu      $s0, $s0, 0x1
    /* 5D0D4 8006C8D4 0300022E */  sltiu      $v0, $s0, 0x3
    /* 5D0D8 8006C8D8 FCFF4014 */  bnez       $v0, .L8006C8CC
    /* 5D0DC 8006C8DC 04006324 */   addiu     $v1, $v1, 0x4
    /* 5D0E0 8006C8E0 2C00638E */  lw         $v1, 0x2C($s3)
    /* 5D0E4 8006C8E4 C0FF023C */  lui        $v0, (0xFFC00000 >> 16)
    /* 5D0E8 8006C8E8 24106200 */  and        $v0, $v1, $v0
    /* 5D0EC 8006C8EC 1A004010 */  beqz       $v0, .L8006C958
    /* 5D0F0 8006C8F0 3F00023C */   lui       $v0, (0x3FFFFF >> 16)
    /* 5D0F4 8006C8F4 FFFF4234 */  ori        $v0, $v0, (0x3FFFFF & 0xFFFF)
    /* 5D0F8 8006C8F8 24106200 */  and        $v0, $v1, $v0
    /* 5D0FC 8006C8FC 21304202 */  addu       $a2, $s2, $v0
    /* 5D100 8006C900 82150300 */  srl        $v0, $v1, 22
    /* 5D104 8006C904 11004010 */  beqz       $v0, .L8006C94C
    /* 5D108 8006C908 21800000 */   addu      $s0, $zero, $zero
    /* 5D10C 8006C90C FF00053C */  lui        $a1, (0xFFFFFF >> 16)
    /* 5D110 8006C910 FFFFA534 */  ori        $a1, $a1, (0xFFFFFF & 0xFFFF)
    /* 5D114 8006C914 2120C000 */  addu       $a0, $a2, $zero
    /* 5D118 8006C918 21188002 */  addu       $v1, $s4, $zero
  .L8006C91C:
    /* 5D11C 8006C91C 0400828C */  lw         $v0, 0x4($a0)
    /* 5D120 8006C920 0C008424 */  addiu      $a0, $a0, 0xC
    /* 5D124 8006C924 01001026 */  addiu      $s0, $s0, 0x1
    /* 5D128 8006C928 24104500 */  and        $v0, $v0, $a1
    /* 5D12C 8006C92C 21104202 */  addu       $v0, $s2, $v0
    /* 5D130 8006C930 340162AC */  sw         $v0, 0x134($v1)
    /* 5D134 8006C934 2C00628E */  lw         $v0, 0x2C($s3)
    /* 5D138 8006C938 00000000 */  nop
    /* 5D13C 8006C93C 82150200 */  srl        $v0, $v0, 22
    /* 5D140 8006C940 2B100202 */  sltu       $v0, $s0, $v0
    /* 5D144 8006C944 F5FF4014 */  bnez       $v0, .L8006C91C
    /* 5D148 8006C948 04006324 */   addiu     $v1, $v1, 0x4
  .L8006C94C:
    /* 5D14C 8006C94C 0800C290 */  lbu        $v0, 0x8($a2)
    /* 5D150 8006C950 00000000 */  nop
    /* 5D154 8006C954 100082A2 */  sb         $v0, 0x10($s4)
  .L8006C958:
    /* 5D158 8006C958 0A80023C */  lui        $v0, %hi(g_GameStateFlags)
    /* 5D15C 8006C95C A0D1428C */  lw         $v0, %lo(g_GameStateFlags)($v0)
    /* 5D160 8006C960 00000000 */  nop
    /* 5D164 8006C964 02004230 */  andi       $v0, $v0, 0x2
    /* 5D168 8006C968 20004014 */  bnez       $v0, .L8006C9EC
    /* 5D16C 8006C96C 07000224 */   addiu     $v0, $zero, 0x7
    /* 5D170 8006C970 0E008292 */  lbu        $v0, 0xE($s4)
    /* 5D174 8006C974 00000000 */  nop
    /* 5D178 8006C978 02004230 */  andi       $v0, $v0, 0x2
    /* 5D17C 8006C97C 11004014 */  bnez       $v0, .L8006C9C4
    /* 5D180 8006C980 0B000224 */   addiu     $v0, $zero, 0xB
    /* 5D184 8006C984 1AB3010C */  jal        Scene_UpdateBgDraw
    /* 5D188 8006C988 00000000 */   nop
    /* 5D18C 8006C98C 0E008392 */  lbu        $v1, 0xE($s4)
    /* 5D190 8006C990 0AB30108 */  j          .L8006CC28
    /* 5D194 8006C994 21100000 */   addu      $v0, $zero, $zero
  jlabel .L8006C998
    /* 5D198 8006C998 01000424 */  addiu      $a0, $zero, 0x1
    /* 5D19C 8006C99C 21300000 */  addu       $a2, $zero, $zero
    /* 5D1A0 8006C9A0 9401878E */  lw         $a3, 0x194($s4)
    /* 5D1A4 8006C9A4 10008592 */  lbu        $a1, 0x10($s4)
    /* 5D1A8 8006C9A8 21000224 */  addiu      $v0, $zero, 0x21
    /* 5D1AC 8006C9AC 1000A2AF */  sw         $v0, 0x10($sp)
    /* 5D1B0 8006C9B0 69B3010C */  jal        CD_ReadSectors
    /* 5D1B4 8006C9B4 1400A0AF */   sw        $zero, 0x14($sp)
    /* 5D1B8 8006C9B8 A0004014 */  bnez       $v0, .L8006CC3C
    /* 5D1BC 8006C9BC 01000224 */   addiu     $v0, $zero, 0x1
    /* 5D1C0 8006C9C0 0B000224 */  addiu      $v0, $zero, 0xB
  .L8006C9C4:
    /* 5D1C4 8006C9C4 83B10108 */  j          .L8006C60C
    /* 5D1C8 8006C9C8 EE0082A2 */   sb        $v0, 0xEE($s4)
  jlabel .L8006C9CC
    /* 5D1CC 8006C9CC 01000224 */  addiu      $v0, $zero, 0x1
    /* 5D1D0 8006C9D0 0E008392 */  lbu        $v1, 0xE($s4)
    /* 5D1D4 8006C9D4 0C000424 */  addiu      $a0, $zero, 0xC
    /* 5D1D8 8006C9D8 EE0084A2 */  sb         $a0, 0xEE($s4)
    /* 5D1DC 8006C9DC 01006334 */  ori        $v1, $v1, 0x1
    /* 5D1E0 8006C9E0 0FB30108 */  j          .L8006CC3C
    /* 5D1E4 8006C9E4 0E0083A2 */   sb        $v1, 0xE($s4)
  jlabel .L8006C9E8
    /* 5D1E8 8006C9E8 0D000224 */  addiu      $v0, $zero, 0xD
  .L8006C9EC:
    /* 5D1EC 8006C9EC EE0082A2 */  sb         $v0, 0xEE($s4)
  .L8006C9F0:
    /* 5D1F0 8006C9F0 0FB30108 */  j          .L8006CC3C
    /* 5D1F4 8006C9F4 01000224 */   addiu     $v0, $zero, 0x1
  jlabel .L8006C9F8
    /* 5D1F8 8006C9F8 5801928E */  lw         $s2, 0x158($s4)
    /* 5D1FC 8006C9FC 3F00023C */  lui        $v0, (0x3FFFFF >> 16)
    /* 5D200 8006CA00 0400438E */  lw         $v1, 0x4($s2)
    /* 5D204 8006CA04 FFFF4234 */  ori        $v0, $v0, (0x3FFFFF & 0xFFFF)
    /* 5D208 8006CA08 21984302 */  addu       $s3, $s2, $v1
    /* 5D20C 8006CA0C 1000638E */  lw         $v1, 0x10($s3)
    /* 5D210 8006CA10 21800000 */  addu       $s0, $zero, $zero
    /* 5D214 8006CA14 24106200 */  and        $v0, $v1, $v0
    /* 5D218 8006CA18 821D0300 */  srl        $v1, $v1, 22
    /* 5D21C 8006CA1C 11006010 */  beqz       $v1, .L8006CA64
    /* 5D220 8006CA20 21104202 */   addu      $v0, $s2, $v0
    /* 5D224 8006CA24 FF00053C */  lui        $a1, (0xFFFFFF >> 16)
    /* 5D228 8006CA28 FFFFA534 */  ori        $a1, $a1, (0xFFFFFF & 0xFFFF)
    /* 5D22C 8006CA2C 21204000 */  addu       $a0, $v0, $zero
  .L8006CA30:
    /* 5D230 8006CA30 07008390 */  lbu        $v1, 0x7($a0)
    /* 5D234 8006CA34 0400828C */  lw         $v0, 0x4($a0)
    /* 5D238 8006CA38 80180300 */  sll        $v1, $v1, 2
    /* 5D23C 8006CA3C 21187400 */  addu       $v1, $v1, $s4
    /* 5D240 8006CA40 24104500 */  and        $v0, $v0, $a1
    /* 5D244 8006CA44 21104202 */  addu       $v0, $s2, $v0
    /* 5D248 8006CA48 C00162AC */  sw         $v0, 0x1C0($v1)
    /* 5D24C 8006CA4C 1000628E */  lw         $v0, 0x10($s3)
    /* 5D250 8006CA50 01001026 */  addiu      $s0, $s0, 0x1
    /* 5D254 8006CA54 82150200 */  srl        $v0, $v0, 22
    /* 5D258 8006CA58 2B100202 */  sltu       $v0, $s0, $v0
    /* 5D25C 8006CA5C F4FF4014 */  bnez       $v0, .L8006CA30
    /* 5D260 8006CA60 0C008424 */   addiu     $a0, $a0, 0xC
  .L8006CA64:
    /* 5D264 8006CA64 100080A2 */  sb         $zero, 0x10($s4)
    /* 5D268 8006CA68 21800000 */  addu       $s0, $zero, $zero
    /* 5D26C 8006CA6C 21188002 */  addu       $v1, $s4, $zero
  .L8006CA70:
    /* 5D270 8006CA70 340160AC */  sw         $zero, 0x134($v1)
    /* 5D274 8006CA74 01001026 */  addiu      $s0, $s0, 0x1
    /* 5D278 8006CA78 0300022E */  sltiu      $v0, $s0, 0x3
    /* 5D27C 8006CA7C FCFF4014 */  bnez       $v0, .L8006CA70
    /* 5D280 8006CA80 04006324 */   addiu     $v1, $v1, 0x4
    /* 5D284 8006CA84 2C00638E */  lw         $v1, 0x2C($s3)
    /* 5D288 8006CA88 C0FF023C */  lui        $v0, (0xFFC00000 >> 16)
    /* 5D28C 8006CA8C 24106200 */  and        $v0, $v1, $v0
    /* 5D290 8006CA90 1A004010 */  beqz       $v0, .L8006CAFC
    /* 5D294 8006CA94 3F00023C */   lui       $v0, (0x3FFFFF >> 16)
    /* 5D298 8006CA98 FFFF4234 */  ori        $v0, $v0, (0x3FFFFF & 0xFFFF)
    /* 5D29C 8006CA9C 24106200 */  and        $v0, $v1, $v0
    /* 5D2A0 8006CAA0 21304202 */  addu       $a2, $s2, $v0
    /* 5D2A4 8006CAA4 82150300 */  srl        $v0, $v1, 22
    /* 5D2A8 8006CAA8 11004010 */  beqz       $v0, .L8006CAF0
    /* 5D2AC 8006CAAC 21800000 */   addu      $s0, $zero, $zero
    /* 5D2B0 8006CAB0 FF00053C */  lui        $a1, (0xFFFFFF >> 16)
    /* 5D2B4 8006CAB4 FFFFA534 */  ori        $a1, $a1, (0xFFFFFF & 0xFFFF)
    /* 5D2B8 8006CAB8 2120C000 */  addu       $a0, $a2, $zero
    /* 5D2BC 8006CABC 21188002 */  addu       $v1, $s4, $zero
  .L8006CAC0:
    /* 5D2C0 8006CAC0 0400828C */  lw         $v0, 0x4($a0)
    /* 5D2C4 8006CAC4 0C008424 */  addiu      $a0, $a0, 0xC
    /* 5D2C8 8006CAC8 01001026 */  addiu      $s0, $s0, 0x1
    /* 5D2CC 8006CACC 24104500 */  and        $v0, $v0, $a1
    /* 5D2D0 8006CAD0 21104202 */  addu       $v0, $s2, $v0
    /* 5D2D4 8006CAD4 340162AC */  sw         $v0, 0x134($v1)
    /* 5D2D8 8006CAD8 2C00628E */  lw         $v0, 0x2C($s3)
    /* 5D2DC 8006CADC 00000000 */  nop
    /* 5D2E0 8006CAE0 82150200 */  srl        $v0, $v0, 22
    /* 5D2E4 8006CAE4 2B100202 */  sltu       $v0, $s0, $v0
    /* 5D2E8 8006CAE8 F5FF4014 */  bnez       $v0, .L8006CAC0
    /* 5D2EC 8006CAEC 04006324 */   addiu     $v1, $v1, 0x4
  .L8006CAF0:
    /* 5D2F0 8006CAF0 0800C290 */  lbu        $v0, 0x8($a2)
    /* 5D2F4 8006CAF4 00000000 */  nop
    /* 5D2F8 8006CAF8 100082A2 */  sb         $v0, 0x10($s4)
  .L8006CAFC:
    /* 5D2FC 8006CAFC 0A80023C */  lui        $v0, %hi(g_PlayerEntity)
    /* 5D300 8006CB00 54D2428C */  lw         $v0, %lo(g_PlayerEntity)($v0)
    /* 5D304 8006CB04 00000000 */  nop
    /* 5D308 8006CB08 06004014 */  bnez       $v0, .L8006CB24
    /* 5D30C 8006CB0C 00000000 */   nop
    /* 5D310 8006CB10 0000828E */  lw         $v0, 0x0($s4)
    /* 5D314 8006CB14 00000000 */  nop
    /* 5D318 8006CB18 02004230 */  andi       $v0, $v0, 0x2
    /* 5D31C 8006CB1C 0FB30108 */  j          .L8006CC3C
    /* 5D320 8006CB20 0100422C */   sltiu     $v0, $v0, 0x1
  .L8006CB24:
    /* 5D324 8006CB24 0A80023C */  lui        $v0, %hi(g_GameStateFlags)
    /* 5D328 8006CB28 A0D1428C */  lw         $v0, %lo(g_GameStateFlags)($v0)
    /* 5D32C 8006CB2C 00000000 */  nop
    /* 5D330 8006CB30 02004230 */  andi       $v0, $v0, 0x2
    /* 5D334 8006CB34 0B004010 */  beqz       $v0, .L8006CB64
    /* 5D338 8006CB38 3F00033C */   lui       $v1, (0x3FFFFF >> 16)
    /* 5D33C 8006CB3C FFFF6334 */  ori        $v1, $v1, (0x3FFFFF & 0xFFFF)
    /* 5D340 8006CB40 0C00628E */  lw         $v0, 0xC($s3)
    /* 5D344 8006CB44 FF00043C */  lui        $a0, (0xFFFFFF >> 16)
    /* 5D348 8006CB48 24104300 */  and        $v0, $v0, $v1
    /* 5D34C 8006CB4C 21104202 */  addu       $v0, $s2, $v0
    /* 5D350 8006CB50 0400428C */  lw         $v0, 0x4($v0)
    /* 5D354 8006CB54 FFFF8434 */  ori        $a0, $a0, (0xFFFFFF & 0xFFFF)
    /* 5D358 8006CB58 24104400 */  and        $v0, $v0, $a0
    /* 5D35C 8006CB5C DAB20108 */  j          .L8006CB68
    /* 5D360 8006CB60 21284202 */   addu      $a1, $s2, $v0
  .L8006CB64:
    /* 5D364 8006CB64 1C01858E */  lw         $a1, 0x11C($s4)
  .L8006CB68:
    /* 5D368 8006CB68 14008426 */  addiu      $a0, $s4, 0x14
    /* 5D36C 8006CB6C C0020724 */  addiu      $a3, $zero, 0x2C0
    /* 5D370 8006CB70 5C01868E */  lw         $a2, 0x15C($s4)
    /* 5D374 8006CB74 80000224 */  addiu      $v0, $zero, 0x80
    /* 5D378 8006CB78 1000A2AF */  sw         $v0, 0x10($sp)
    /* 5D37C 8006CB7C C2010224 */  addiu      $v0, $zero, 0x1C2
    /* 5D380 8006CB80 1800A2AF */  sw         $v0, 0x18($sp)
    /* 5D384 8006CB84 2800A227 */  addiu      $v0, $sp, 0x28
    /* 5D388 8006CB88 2000A2AF */  sw         $v0, 0x20($sp)
    /* 5D38C 8006CB8C 01000224 */  addiu      $v0, $zero, 0x1
    /* 5D390 8006CB90 1400A0AF */  sw         $zero, 0x14($sp)
    /* 5D394 8006CB94 1C00A0AF */  sw         $zero, 0x1C($sp)
    /* 5D398 8006CB98 14F4000C */  jal        Render_SetupEntityPrims
    /* 5D39C 8006CB9C 2400A2AF */   sw        $v0, 0x24($sp)
    /* 5D3A0 8006CBA0 3800828E */  lw         $v0, 0x38($s4)
    /* 5D3A4 8006CBA4 00000000 */  nop
    /* 5D3A8 8006CBA8 0C004014 */  bnez       $v0, .L8006CBDC
    /* 5D3AC 8006CBAC 14009026 */   addiu     $s0, $s4, 0x14
    /* 5D3B0 8006CBB0 0A80023C */  lui        $v0, %hi(g_PlayerEntity)
    /* 5D3B4 8006CBB4 54D2428C */  lw         $v0, %lo(g_PlayerEntity)($v0)
    /* 5D3B8 8006CBB8 00000000 */  nop
    /* 5D3BC 8006CBBC 07004010 */  beqz       $v0, .L8006CBDC
    /* 5D3C0 8006CBC0 B4014224 */   addiu     $v0, $v0, 0x1B4
    /* 5D3C4 8006CBC4 380082AE */  sw         $v0, 0x38($s4)
    /* 5D3C8 8006CBC8 03000224 */  addiu      $v0, $zero, 0x3
    /* 5D3CC 8006CBCC 3C0082A6 */  sh         $v0, 0x3C($s4)
    /* 5D3D0 8006CBD0 12000224 */  addiu      $v0, $zero, 0x12
    /* 5D3D4 8006CBD4 3E0082A6 */  sh         $v0, 0x3E($s4)
    /* 5D3D8 8006CBD8 14009026 */  addiu      $s0, $s4, 0x14
  .L8006CBDC:
    /* 5D3DC 8006CBDC 21200002 */  addu       $a0, $s0, $zero
    /* 5D3E0 8006CBE0 80000224 */  addiu      $v0, $zero, 0x80
    /* 5D3E4 8006CBE4 9C0082A2 */  sb         $v0, 0x9C($s4)
    /* 5D3E8 8006CBE8 0C000224 */  addiu      $v0, $zero, 0xC
    /* 5D3EC 8006CBEC 9D0082A2 */  sb         $v0, 0x9D($s4)
    /* 5D3F0 8006CBF0 18000224 */  addiu      $v0, $zero, 0x18
    /* 5D3F4 8006CBF4 639A010C */  jal        Render_InitRoomPrimState
    /* 5D3F8 8006CBF8 9E0082A2 */   sb        $v0, 0x9E($s4)
    /* 5D3FC 8006CBFC 21200002 */  addu       $a0, $s0, $zero
    /* 5D400 8006CC00 21280000 */  addu       $a1, $zero, $zero
    /* 5D404 8006CC04 21300000 */  addu       $a2, $zero, $zero
    /* 5D408 8006CC08 0C80073C */  lui        $a3, %hi(D_800BEA40)
    /* 5D40C 8006CC0C 40EAE724 */  addiu      $a3, $a3, %lo(D_800BEA40)
    /* 5D410 8006CC10 0C80023C */  lui        $v0, %hi(D_800B89F8)
    /* 5D414 8006CC14 F8894224 */  addiu      $v0, $v0, %lo(D_800B89F8)
    /* 5D418 8006CC18 0DF6000C */  jal        Render_DrawWithAnim
    /* 5D41C 8006CC1C 1000A2AF */   sw        $v0, 0x10($sp)
    /* 5D420 8006CC20 0E008392 */  lbu        $v1, 0xE($s4)
    /* 5D424 8006CC24 01000224 */  addiu      $v0, $zero, 0x1
  .L8006CC28:
    /* 5D428 8006CC28 EE0080A2 */  sb         $zero, 0xEE($s4)
    /* 5D42C 8006CC2C FC006330 */  andi       $v1, $v1, 0xFC
    /* 5D430 8006CC30 0FB30108 */  j          .L8006CC3C
    /* 5D434 8006CC34 0E0083A2 */   sb        $v1, 0xE($s4)
  jlabel .L8006CC38
    /* 5D438 8006CC38 21100000 */  addu       $v0, $zero, $zero
  .L8006CC3C:
    /* 5D43C 8006CC3C 8400BF8F */  lw         $ra, 0x84($sp)
    /* 5D440 8006CC40 8000B68F */  lw         $s6, 0x80($sp)
    /* 5D444 8006CC44 7C00B58F */  lw         $s5, 0x7C($sp)
    /* 5D448 8006CC48 7800B48F */  lw         $s4, 0x78($sp)
    /* 5D44C 8006CC4C 7400B38F */  lw         $s3, 0x74($sp)
    /* 5D450 8006CC50 7000B28F */  lw         $s2, 0x70($sp)
    /* 5D454 8006CC54 6C00B18F */  lw         $s1, 0x6C($sp)
    /* 5D458 8006CC58 6800B08F */  lw         $s0, 0x68($sp)
    /* 5D45C 8006CC5C 8800BD27 */  addiu      $sp, $sp, 0x88
    /* 5D460 8006CC60 0800E003 */  jr         $ra
    /* 5D464 8006CC64 00000000 */   nop
endlabel Scene_LoadEntityTextures
