.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.4 */

nonmatching SPU_StepReverbLoad, 0x338

glabel SPU_StepReverbLoad
    /* 7E044 8008D844 0A80023C */  lui        $v0, %hi(D_8009CDEC)
    /* 7E048 8008D848 ECCD4294 */  lhu        $v0, %lo(D_8009CDEC)($v0)
    /* 7E04C 8008D84C C0FFBD27 */  addiu      $sp, $sp, -0x40
    /* 7E050 8008D850 3C00BFAF */  sw         $ra, 0x3C($sp)
    /* 7E054 8008D854 3800B0AF */  sw         $s0, 0x38($sp)
    /* 7E058 8008D858 01004224 */  addiu      $v0, $v0, 0x1
    /* 7E05C 8008D85C 0A80013C */  lui        $at, %hi(D_8009CDEC)
    /* 7E060 8008D860 ECCD22A4 */  sh         $v0, %lo(D_8009CDEC)($at)
    /* 7E064 8008D864 03004230 */  andi       $v0, $v0, 0x3
    /* 7E068 8008D868 BF004014 */  bnez       $v0, .L8008DB68
    /* 7E06C 8008D86C 00000000 */   nop
    /* 7E070 8008D870 0A80023C */  lui        $v0, %hi(D_8009D2A2)
    /* 7E074 8008D874 A2D24284 */  lh         $v0, %lo(D_8009D2A2)($v0)
    /* 7E078 8008D878 00000000 */  nop
    /* 7E07C 8008D87C 0D004010 */  beqz       $v0, .L8008D8B4
    /* 7E080 8008D880 21184000 */   addu      $v1, $v0, $zero
    /* 7E084 8008D884 0A80023C */  lui        $v0, %hi(D_8009D2B4)
    /* 7E088 8008D888 B4D2428C */  lw         $v0, %lo(D_8009D2B4)($v0)
    /* 7E08C 8008D88C 0A80043C */  lui        $a0, %hi(D_8009D284)
    /* 7E090 8008D890 84D2848C */  lw         $a0, %lo(D_8009D284)($a0)
    /* 7E094 8008D894 FFFF6324 */  addiu      $v1, $v1, -0x1
    /* 7E098 8008D898 0A80013C */  lui        $at, %hi(D_8009D2A2)
    /* 7E09C 8008D89C A2D223A4 */  sh         $v1, %lo(D_8009D2A2)($at)
    /* 7E0A0 8008D8A0 21104400 */  addu       $v0, $v0, $a0
    /* 7E0A4 8008D8A4 0A80013C */  lui        $at, %hi(D_8009D2B4)
    /* 7E0A8 8008D8A8 B4D222AC */  sw         $v0, %lo(D_8009D2B4)($at)
    /* 7E0AC 8008D8AC F435020C */  jal        Seq_ApplyGlobalPitch
    /* 7E0B0 8008D8B0 00000000 */   nop
  .L8008D8B4:
    /* 7E0B4 8008D8B4 0A80023C */  lui        $v0, %hi(D_8009D220)
    /* 7E0B8 8008D8B8 20D24284 */  lh         $v0, %lo(D_8009D220)($v0)
    /* 7E0BC 8008D8BC 00000000 */  nop
    /* 7E0C0 8008D8C0 0B004010 */  beqz       $v0, .L8008D8F0
    /* 7E0C4 8008D8C4 21184000 */   addu      $v1, $v0, $zero
    /* 7E0C8 8008D8C8 0A80023C */  lui        $v0, %hi(D_8009D2D0)
    /* 7E0CC 8008D8CC D0D2428C */  lw         $v0, %lo(D_8009D2D0)($v0)
    /* 7E0D0 8008D8D0 0A80043C */  lui        $a0, %hi(D_8009D214)
    /* 7E0D4 8008D8D4 14D2848C */  lw         $a0, %lo(D_8009D214)($a0)
    /* 7E0D8 8008D8D8 FFFF6324 */  addiu      $v1, $v1, -0x1
    /* 7E0DC 8008D8DC 0A80013C */  lui        $at, %hi(D_8009D220)
    /* 7E0E0 8008D8E0 20D223A4 */  sh         $v1, %lo(D_8009D220)($at)
    /* 7E0E4 8008D8E4 21104400 */  addu       $v0, $v0, $a0
    /* 7E0E8 8008D8E8 0A80013C */  lui        $at, %hi(D_8009D2D0)
    /* 7E0EC 8008D8EC D0D222AC */  sw         $v0, %lo(D_8009D2D0)($at)
  .L8008D8F0:
    /* 7E0F0 8008D8F0 0A80023C */  lui        $v0, %hi(D_8009D21E)
    /* 7E0F4 8008D8F4 1ED24284 */  lh         $v0, %lo(D_8009D21E)($v0)
    /* 7E0F8 8008D8F8 00000000 */  nop
    /* 7E0FC 8008D8FC 19004010 */  beqz       $v0, .L8008D964
    /* 7E100 8008D900 21284000 */   addu      $a1, $v0, $zero
    /* 7E104 8008D904 0A80033C */  lui        $v1, %hi(D_8009D2CC)
    /* 7E108 8008D908 CCD2638C */  lw         $v1, %lo(D_8009D2CC)($v1)
    /* 7E10C 8008D90C 0A80043C */  lui        $a0, %hi(D_8009D210)
    /* 7E110 8008D910 10D2848C */  lw         $a0, %lo(D_8009D210)($a0)
    /* 7E114 8008D914 FFFFA224 */  addiu      $v0, $a1, -0x1
    /* 7E118 8008D918 0A80013C */  lui        $at, %hi(D_8009D21E)
    /* 7E11C 8008D91C 1ED222A4 */  sh         $v0, %lo(D_8009D21E)($at)
    /* 7E120 8008D920 FF00023C */  lui        $v0, (0xFF0000 >> 16)
    /* 7E124 8008D924 21806400 */  addu       $s0, $v1, $a0
    /* 7E128 8008D928 24200202 */  and        $a0, $s0, $v0
    /* 7E12C 8008D92C 24186200 */  and        $v1, $v1, $v0
    /* 7E130 8008D930 0A008310 */  beq        $a0, $v1, .L8008D95C
    /* 7E134 8008D934 00000000 */   nop
    /* 7E138 8008D938 18000624 */  addiu      $a2, $zero, 0x18
    /* 7E13C 8008D93C 0C80033C */  lui        $v1, %hi(D_800B8BB4)
    /* 7E140 8008D940 B48B6324 */  addiu      $v1, $v1, %lo(D_800B8BB4)
  .L8008D944:
    /* 7E144 8008D944 0000628C */  lw         $v0, 0x0($v1)
    /* 7E148 8008D948 FFFFC624 */  addiu      $a2, $a2, -0x1
    /* 7E14C 8008D94C 10004234 */  ori        $v0, $v0, 0x10
    /* 7E150 8008D950 000062AC */  sw         $v0, 0x0($v1)
    /* 7E154 8008D954 FBFFC014 */  bnez       $a2, .L8008D944
    /* 7E158 8008D958 1C016324 */   addiu     $v1, $v1, 0x11C
  .L8008D95C:
    /* 7E15C 8008D95C 0A80013C */  lui        $at, %hi(D_8009D2CC)
    /* 7E160 8008D960 CCD230AC */  sw         $s0, %lo(D_8009D2CC)($at)
  .L8008D964:
    /* 7E164 8008D964 0A80053C */  lui        $a1, %hi(g_AkaoCurTrack)
    /* 7E168 8008D968 C8D2A58C */  lw         $a1, %lo(g_AkaoCurTrack)($a1)
    /* 7E16C 8008D96C 00000000 */  nop
    /* 7E170 8008D970 0400A28C */  lw         $v0, 0x4($a1)
    /* 7E174 8008D974 00000000 */  nop
    /* 7E178 8008D978 19004010 */  beqz       $v0, .L8008D9E0
    /* 7E17C 8008D97C 00000000 */   nop
    /* 7E180 8008D980 5000A284 */  lh         $v0, 0x50($a1)
    /* 7E184 8008D984 00000000 */  nop
    /* 7E188 8008D988 15004010 */  beqz       $v0, .L8008D9E0
    /* 7E18C 8008D98C 21304000 */   addu      $a2, $v0, $zero
    /* 7E190 8008D990 4800A38C */  lw         $v1, 0x48($a1)
    /* 7E194 8008D994 4C00A48C */  lw         $a0, 0x4C($a1)
    /* 7E198 8008D998 FFFFC224 */  addiu      $v0, $a2, -0x1
    /* 7E19C 8008D99C 5000A2A4 */  sh         $v0, 0x50($a1)
    /* 7E1A0 8008D9A0 7F00023C */  lui        $v0, (0x7F0000 >> 16)
    /* 7E1A4 8008D9A4 21806400 */  addu       $s0, $v1, $a0
    /* 7E1A8 8008D9A8 24200202 */  and        $a0, $s0, $v0
    /* 7E1AC 8008D9AC 24186200 */  and        $v1, $v1, $v0
    /* 7E1B0 8008D9B0 05008310 */  beq        $a0, $v1, .L8008D9C8
    /* 7E1B4 8008D9B4 00000000 */   nop
    /* 7E1B8 8008D9B8 0C80043C */  lui        $a0, %hi(D_800B8AC0)
    /* 7E1BC 8008D9BC C08A8424 */  addiu      $a0, $a0, %lo(D_800B8AC0)
    /* 7E1C0 8008D9C0 E72A020C */  jal        func_8008AB9C
    /* 7E1C4 8008D9C4 00000000 */   nop
  .L8008D9C8:
    /* 7E1C8 8008D9C8 0A80023C */  lui        $v0, %hi(g_AkaoCurTrack)
    /* 7E1CC 8008D9CC C8D2428C */  lw         $v0, %lo(g_AkaoCurTrack)($v0)
    /* 7E1D0 8008D9D0 00000000 */  nop
    /* 7E1D4 8008D9D4 480050AC */  sw         $s0, 0x48($v0)
    /* 7E1D8 8008D9D8 0A80053C */  lui        $a1, %hi(g_AkaoCurTrack)
    /* 7E1DC 8008D9DC C8D2A58C */  lw         $a1, %lo(g_AkaoCurTrack)($a1)
  .L8008D9E0:
    /* 7E1E0 8008D9E0 00000000 */  nop
    /* 7E1E4 8008D9E4 6C00A38C */  lw         $v1, 0x6C($a1)
    /* 7E1E8 8008D9E8 6800A224 */  addiu      $v0, $a1, 0x68
    /* 7E1EC 8008D9EC 0A80013C */  lui        $at, %hi(g_AkaoCurTrack)
    /* 7E1F0 8008D9F0 C8D222AC */  sw         $v0, %lo(g_AkaoCurTrack)($at)
    /* 7E1F4 8008D9F4 17006010 */  beqz       $v1, .L8008DA54
    /* 7E1F8 8008D9F8 00000000 */   nop
    /* 7E1FC 8008D9FC B800A284 */  lh         $v0, 0xB8($a1)
    /* 7E200 8008DA00 00000000 */  nop
    /* 7E204 8008DA04 13004010 */  beqz       $v0, .L8008DA54
    /* 7E208 8008DA08 21304000 */   addu      $a2, $v0, $zero
    /* 7E20C 8008DA0C B000A38C */  lw         $v1, 0xB0($a1)
    /* 7E210 8008DA10 B400A48C */  lw         $a0, 0xB4($a1)
    /* 7E214 8008DA14 FFFFC224 */  addiu      $v0, $a2, -0x1
    /* 7E218 8008DA18 B800A2A4 */  sh         $v0, 0xB8($a1)
    /* 7E21C 8008DA1C 7F00023C */  lui        $v0, (0x7F0000 >> 16)
    /* 7E220 8008DA20 21806400 */  addu       $s0, $v1, $a0
    /* 7E224 8008DA24 24200202 */  and        $a0, $s0, $v0
    /* 7E228 8008DA28 24186200 */  and        $v1, $v1, $v0
    /* 7E22C 8008DA2C 05008310 */  beq        $a0, $v1, .L8008DA44
    /* 7E230 8008DA30 00000000 */   nop
    /* 7E234 8008DA34 0C80043C */  lui        $a0, %hi(D_800BA560)
    /* 7E238 8008DA38 60A58424 */  addiu      $a0, $a0, %lo(D_800BA560)
    /* 7E23C 8008DA3C E72A020C */  jal        func_8008AB9C
    /* 7E240 8008DA40 00000000 */   nop
  .L8008DA44:
    /* 7E244 8008DA44 0A80023C */  lui        $v0, %hi(g_AkaoCurTrack)
    /* 7E248 8008DA48 C8D2428C */  lw         $v0, %lo(g_AkaoCurTrack)($v0)
    /* 7E24C 8008DA4C 00000000 */  nop
    /* 7E250 8008DA50 480050AC */  sw         $s0, 0x48($v0)
  .L8008DA54:
    /* 7E254 8008DA54 0A80023C */  lui        $v0, %hi(g_AkaoCurTrack)
    /* 7E258 8008DA58 C8D2428C */  lw         $v0, %lo(g_AkaoCurTrack)($v0)
    /* 7E25C 8008DA5C 0C80073C */  lui        $a3, %hi(D_800BCD50)
    /* 7E260 8008DA60 50CDE78C */  lw         $a3, %lo(D_800BCD50)($a3)
    /* 7E264 8008DA64 98FF4224 */  addiu      $v0, $v0, -0x68
    /* 7E268 8008DA68 0A80013C */  lui        $at, %hi(g_AkaoCurTrack)
    /* 7E26C 8008DA6C C8D222AC */  sw         $v0, %lo(g_AkaoCurTrack)($at)
    /* 7E270 8008DA70 3D00E010 */  beqz       $a3, .L8008DB68
    /* 7E274 8008DA74 00100624 */   addiu     $a2, $zero, 0x1000
    /* 7E278 8008DA78 0C80053C */  lui        $a1, %hi(D_800BC03C)
    /* 7E27C 8008DA7C 3CC0A524 */  addiu      $a1, $a1, %lo(D_800BC03C)
  .L8008DA80:
    /* 7E280 8008DA80 2410E600 */  and        $v0, $a3, $a2
    /* 7E284 8008DA84 35004010 */  beqz       $v0, .L8008DB5C
    /* 7E288 8008DA88 00000000 */   nop
    /* 7E28C 8008DA8C 3800A294 */  lhu        $v0, 0x38($a1)
    /* 7E290 8008DA90 00000000 */  nop
    /* 7E294 8008DA94 0E004010 */  beqz       $v0, .L8008DAD0
    /* 7E298 8008DA98 FFFF4224 */   addiu     $v0, $v0, -0x1
    /* 7E29C 8008DA9C 9C00A384 */  lh         $v1, 0x9C($a1)
    /* 7E2A0 8008DAA0 9E00A484 */  lh         $a0, 0x9E($a1)
    /* 7E2A4 8008DAA4 3800A2A4 */  sh         $v0, 0x38($a1)
    /* 7E2A8 8008DAA8 21806400 */  addu       $s0, $v1, $a0
    /* 7E2AC 8008DAAC 00FF0232 */  andi       $v0, $s0, 0xFF00
    /* 7E2B0 8008DAB0 00FF6330 */  andi       $v1, $v1, 0xFF00
    /* 7E2B4 8008DAB4 05004310 */  beq        $v0, $v1, .L8008DACC
    /* 7E2B8 8008DAB8 00000000 */   nop
    /* 7E2BC 8008DABC B800A28C */  lw         $v0, 0xB8($a1)
    /* 7E2C0 8008DAC0 00000000 */  nop
    /* 7E2C4 8008DAC4 03004234 */  ori        $v0, $v0, 0x3
    /* 7E2C8 8008DAC8 B800A2AC */  sw         $v0, 0xB8($a1)
  .L8008DACC:
    /* 7E2CC 8008DACC 9C00B0A4 */  sh         $s0, 0x9C($a1)
  .L8008DAD0:
    /* 7E2D0 8008DAD0 3C00A294 */  lhu        $v0, 0x3C($a1)
    /* 7E2D4 8008DAD4 00000000 */  nop
    /* 7E2D8 8008DAD8 0E004010 */  beqz       $v0, .L8008DB14
    /* 7E2DC 8008DADC FFFF4224 */   addiu     $v0, $v0, -0x1
    /* 7E2E0 8008DAE0 3A00A394 */  lhu        $v1, 0x3A($a1)
    /* 7E2E4 8008DAE4 A000A484 */  lh         $a0, 0xA0($a1)
    /* 7E2E8 8008DAE8 3C00A2A4 */  sh         $v0, 0x3C($a1)
    /* 7E2EC 8008DAEC 21806400 */  addu       $s0, $v1, $a0
    /* 7E2F0 8008DAF0 00FF0232 */  andi       $v0, $s0, 0xFF00
    /* 7E2F4 8008DAF4 00FF6330 */  andi       $v1, $v1, 0xFF00
    /* 7E2F8 8008DAF8 05004310 */  beq        $v0, $v1, .L8008DB10
    /* 7E2FC 8008DAFC 00000000 */   nop
    /* 7E300 8008DB00 B800A28C */  lw         $v0, 0xB8($a1)
    /* 7E304 8008DB04 00000000 */  nop
    /* 7E308 8008DB08 03004234 */  ori        $v0, $v0, 0x3
    /* 7E30C 8008DB0C B800A2AC */  sw         $v0, 0xB8($a1)
  .L8008DB10:
    /* 7E310 8008DB10 3A00B0A4 */  sh         $s0, 0x3A($a1)
  .L8008DB14:
    /* 7E314 8008DB14 3400A294 */  lhu        $v0, 0x34($a1)
    /* 7E318 8008DB18 00000000 */  nop
    /* 7E31C 8008DB1C 0E004010 */  beqz       $v0, .L8008DB58
    /* 7E320 8008DB20 FFFF4224 */   addiu     $v0, $v0, -0x1
    /* 7E324 8008DB24 0000A38C */  lw         $v1, 0x0($a1)
    /* 7E328 8008DB28 0400A48C */  lw         $a0, 0x4($a1)
    /* 7E32C 8008DB2C 3400A2A4 */  sh         $v0, 0x34($a1)
    /* 7E330 8008DB30 21806400 */  addu       $s0, $v1, $a0
    /* 7E334 8008DB34 00FF0232 */  andi       $v0, $s0, 0xFF00
    /* 7E338 8008DB38 00FF6330 */  andi       $v1, $v1, 0xFF00
    /* 7E33C 8008DB3C 05004310 */  beq        $v0, $v1, .L8008DB54
    /* 7E340 8008DB40 00000000 */   nop
    /* 7E344 8008DB44 B800A28C */  lw         $v0, 0xB8($a1)
    /* 7E348 8008DB48 00000000 */  nop
    /* 7E34C 8008DB4C 10004234 */  ori        $v0, $v0, 0x10
    /* 7E350 8008DB50 B800A2AC */  sw         $v0, 0xB8($a1)
  .L8008DB54:
    /* 7E354 8008DB54 0000B0AC */  sw         $s0, 0x0($a1)
  .L8008DB58:
    /* 7E358 8008DB58 2638E600 */  xor        $a3, $a3, $a2
  .L8008DB5C:
    /* 7E35C 8008DB5C 40300600 */  sll        $a2, $a2, 1
    /* 7E360 8008DB60 C7FFE014 */  bnez       $a3, .L8008DA80
    /* 7E364 8008DB64 1C01A524 */   addiu     $a1, $a1, 0x11C
  .L8008DB68:
    /* 7E368 8008DB68 3C00BF8F */  lw         $ra, 0x3C($sp)
    /* 7E36C 8008DB6C 3800B08F */  lw         $s0, 0x38($sp)
    /* 7E370 8008DB70 4000BD27 */  addiu      $sp, $sp, 0x40
    /* 7E374 8008DB74 0800E003 */  jr         $ra
    /* 7E378 8008DB78 00000000 */   nop
endlabel SPU_StepReverbLoad
