.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_8018F1BC, 0x144

glabel func_8018F1BC
    /* 1D4 8018F1BC E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 1D8 8018F1C0 1400B1AF */  sw         $s1, 0x14($sp)
    /* 1DC 8018F1C4 21888000 */  addu       $s1, $a0, $zero
    /* 1E0 8018F1C8 1000B0AF */  sw         $s0, 0x10($sp)
    /* 1E4 8018F1CC 2180C000 */  addu       $s0, $a2, $zero
    /* 1E8 8018F1D0 1800BFAF */  sw         $ra, 0x18($sp)
    /* 1EC 8018F1D4 D00A030C */  jal        func_800C2B40
    /* 1F0 8018F1D8 21200002 */   addu      $a0, $s0, $zero
    /* 1F4 8018F1DC 06B7010C */  jal        func_8006DC18
    /* 1F8 8018F1E0 0A000424 */   addiu     $a0, $zero, 0xA
    /* 1FC 8018F1E4 2C0002AE */  sw         $v0, 0x2C($s0)
    /* 200 8018F1E8 0800228E */  lw         $v0, 0x8($s1)
    /* 204 8018F1EC 00000000 */  nop
    /* 208 8018F1F0 000002AE */  sw         $v0, 0x0($s0)
    /* 20C 8018F1F4 3802428C */  lw         $v0, 0x238($v0)
    /* 210 8018F1F8 06000424 */  addiu      $a0, $zero, 0x6
    /* 214 8018F1FC 0000438C */  lw         $v1, 0x0($v0)
    /* 218 8018F200 0400458C */  lw         $a1, 0x4($v0)
    /* 21C 8018F204 0800468C */  lw         $a2, 0x8($v0)
    /* 220 8018F208 0C00478C */  lw         $a3, 0xC($v0)
    /* 224 8018F20C 040003AE */  sw         $v1, 0x4($s0)
    /* 228 8018F210 080005AE */  sw         $a1, 0x8($s0)
    /* 22C 8018F214 0C0006AE */  sw         $a2, 0xC($s0)
    /* 230 8018F218 100007AE */  sw         $a3, 0x10($s0)
    /* 234 8018F21C 1000438C */  lw         $v1, 0x10($v0)
    /* 238 8018F220 1400458C */  lw         $a1, 0x14($v0)
    /* 23C 8018F224 1800468C */  lw         $a2, 0x18($v0)
    /* 240 8018F228 1C00478C */  lw         $a3, 0x1C($v0)
    /* 244 8018F22C 140003AE */  sw         $v1, 0x14($s0)
    /* 248 8018F230 180005AE */  sw         $a1, 0x18($s0)
    /* 24C 8018F234 1C0006AE */  sw         $a2, 0x1C($s0)
    /* 250 8018F238 200007AE */  sw         $a3, 0x20($s0)
    /* 254 8018F23C 260000A6 */  sh         $zero, 0x26($s0)
    /* 258 8018F240 CA0A030C */  jal        func_800C2B28
    /* 25C 8018F244 280000A6 */   sh        $zero, 0x28($s0)
    /* 260 8018F248 80000424 */  addiu      $a0, $zero, 0x80
    /* 264 8018F24C 0000428C */  lw         $v0, 0x0($v0)
    /* 268 8018F250 80000324 */  addiu      $v1, $zero, 0x80
    /* 26C 8018F254 240002A6 */  sh         $v0, 0x24($s0)
    /* 270 8018F258 9CFF0224 */  addiu      $v0, $zero, -0x64
    /* 274 8018F25C 1980013C */  lui        $at, %hi(D_801900A0)
    /* 278 8018F260 A00022A4 */  sh         $v0, %lo(D_801900A0)($at)
    /* 27C 8018F264 04000224 */  addiu      $v0, $zero, 0x4
    /* 280 8018F268 1980013C */  lui        $at, %hi(D_8019008C)
    /* 284 8018F26C 8C0022A0 */  sb         $v0, %lo(D_8019008C)($at)
    /* 288 8018F270 01000224 */  addiu      $v0, $zero, 0x1
    /* 28C 8018F274 1980013C */  lui        $at, %hi(D_8019008D)
    /* 290 8018F278 8D0022A0 */  sb         $v0, %lo(D_8019008D)($at)
    /* 294 8018F27C 32000224 */  addiu      $v0, $zero, 0x32
    /* 298 8018F280 1980013C */  lui        $at, %hi(D_8019009C)
    /* 29C 8018F284 9C0020A0 */  sb         $zero, %lo(D_8019009C)($at)
    /* 2A0 8018F288 1980013C */  lui        $at, %hi(D_8019009D)
    /* 2A4 8018F28C 9D0020A0 */  sb         $zero, %lo(D_8019009D)($at)
    /* 2A8 8018F290 1980013C */  lui        $at, %hi(D_801900A2)
    /* 2AC 8018F294 A20024A4 */  sh         $a0, %lo(D_801900A2)($at)
    /* 2B0 8018F298 1980013C */  lui        $at, %hi(D_80190098)
    /* 2B4 8018F29C 980023A0 */  sb         $v1, %lo(D_80190098)($at)
    /* 2B8 8018F2A0 1980013C */  lui        $at, %hi(D_80190099)
    /* 2BC 8018F2A4 990023A0 */  sb         $v1, %lo(D_80190099)($at)
    /* 2C0 8018F2A8 1980013C */  lui        $at, %hi(D_8019009A)
    /* 2C4 8018F2AC 9A0023A0 */  sb         $v1, %lo(D_8019009A)($at)
    /* 2C8 8018F2B0 1980013C */  lui        $at, %hi(D_8019009E)
    /* 2CC 8018F2B4 9E0020A0 */  sb         $zero, %lo(D_8019009E)($at)
    /* 2D0 8018F2B8 1980013C */  lui        $at, %hi(D_80190090)
    /* 2D4 8018F2BC 900022A4 */  sh         $v0, %lo(D_80190090)($at)
    /* 2D8 8018F2C0 1980013C */  lui        $at, %hi(D_80190092)
    /* 2DC 8018F2C4 920024A4 */  sh         $a0, %lo(D_80190092)($at)
    /* 2E0 8018F2C8 1980013C */  lui        $at, %hi(D_80190088)
    /* 2E4 8018F2CC 880023A0 */  sb         $v1, %lo(D_80190088)($at)
    /* 2E8 8018F2D0 1980013C */  lui        $at, %hi(D_80190089)
    /* 2EC 8018F2D4 890023A0 */  sb         $v1, %lo(D_80190089)($at)
    /* 2F0 8018F2D8 1980013C */  lui        $at, %hi(D_8019008A)
    /* 2F4 8018F2DC 8A0023A0 */  sb         $v1, %lo(D_8019008A)($at)
    /* 2F8 8018F2E0 1980013C */  lui        $at, %hi(D_8019008E)
    /* 2FC 8018F2E4 8E0020A0 */  sb         $zero, %lo(D_8019008E)($at)
    /* 300 8018F2E8 1800BF8F */  lw         $ra, 0x18($sp)
    /* 304 8018F2EC 1400B18F */  lw         $s1, 0x14($sp)
    /* 308 8018F2F0 1000B08F */  lw         $s0, 0x10($sp)
    /* 30C 8018F2F4 2000BD27 */  addiu      $sp, $sp, 0x20
    /* 310 8018F2F8 0800E003 */  jr         $ra
    /* 314 8018F2FC 00000000 */   nop
endlabel func_8018F1BC

nonmatching func_8018F300, 0x8

glabel func_8018F300
    /* 318 8018F300 0800E003 */  jr         $ra
    /* 31C 8018F304 00000000 */   nop
endlabel func_8018F300

nonmatching func_8018F308, 0x80

glabel func_8018F308
    /* 320 8018F308 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 324 8018F30C 1800B0AF */  sw         $s0, 0x18($sp)
    /* 328 8018F310 2180A000 */  addu       $s0, $a1, $zero
    /* 32C 8018F314 1C00BFAF */  sw         $ra, 0x1C($sp)
    /* 330 8018F318 2600C284 */  lh         $v0, 0x26($a2)
    /* 334 8018F31C 2128C000 */  addu       $a1, $a2, $zero
    /* 338 8018F320 03004010 */  beqz       $v0, .L8018F330
    /* 33C 8018F324 21184000 */   addu      $v1, $v0, $zero
    /* 340 8018F328 FFFF6224 */  addiu      $v0, $v1, -0x1
    /* 344 8018F32C 2600C2A4 */  sh         $v0, 0x26($a2)
  .L8018F330:
    /* 348 8018F330 2800A384 */  lh         $v1, 0x28($a1)
    /* 34C 8018F334 01000224 */  addiu      $v0, $zero, 0x1
    /* 350 8018F338 08006214 */  bne        $v1, $v0, .L8018F35C
    /* 354 8018F33C 00000000 */   nop
    /* 358 8018F340 2600A284 */  lh         $v0, 0x26($a1)
    /* 35C 8018F344 00000000 */  nop
    /* 360 8018F348 04004014 */  bnez       $v0, .L8018F35C
    /* 364 8018F34C 2800A0A4 */   sh        $zero, 0x28($a1)
    /* 368 8018F350 2400A294 */  lhu        $v0, 0x24($a1)
    /* 36C 8018F354 061B030C */  jal        func_800C6C18
    /* 370 8018F358 2600A2A4 */   sh        $v0, 0x26($a1)
  .L8018F35C:
    /* 374 8018F35C DA0A030C */  jal        func_800C2B68
    /* 378 8018F360 00000000 */   nop
    /* 37C 8018F364 01000324 */  addiu      $v1, $zero, 0x1
    /* 380 8018F368 02004314 */  bne        $v0, $v1, .L8018F374
    /* 384 8018F36C 02000224 */   addiu     $v0, $zero, 0x2
    /* 388 8018F370 010002A2 */  sb         $v0, 0x1($s0)
  .L8018F374:
    /* 38C 8018F374 1C00BF8F */  lw         $ra, 0x1C($sp)
    /* 390 8018F378 1800B08F */  lw         $s0, 0x18($sp)
    /* 394 8018F37C 2000BD27 */  addiu      $sp, $sp, 0x20
    /* 398 8018F380 0800E003 */  jr         $ra
    /* 39C 8018F384 00000000 */   nop
endlabel func_8018F308

/* Handwritten function */
nonmatching func_8018F388, 0x4A0

glabel func_8018F388
    /* 3A0 8018F388 70FFBD27 */  addiu      $sp, $sp, -0x90
    /* 3A4 8018F38C 8400B7AF */  sw         $s7, 0x84($sp)
    /* 3A8 8018F390 21B88000 */  addu       $s7, $a0, $zero
    /* 3AC 8018F394 7C00B5AF */  sw         $s5, 0x7C($sp)
    /* 3B0 8018F398 21A8C000 */  addu       $s5, $a2, $zero
    /* 3B4 8018F39C 8800BFAF */  sw         $ra, 0x88($sp)
    /* 3B8 8018F3A0 8000B6AF */  sw         $s6, 0x80($sp)
    /* 3BC 8018F3A4 7800B4AF */  sw         $s4, 0x78($sp)
    /* 3C0 8018F3A8 7400B3AF */  sw         $s3, 0x74($sp)
    /* 3C4 8018F3AC 7000B2AF */  sw         $s2, 0x70($sp)
    /* 3C8 8018F3B0 6C00B1AF */  sw         $s1, 0x6C($sp)
    /* 3CC 8018F3B4 D40A030C */  jal        func_800C2B50
    /* 3D0 8018F3B8 6800B0AF */   sw        $s0, 0x68($sp)
    /* 3D4 8018F3BC 03000424 */  addiu      $a0, $zero, 0x3
    /* 3D8 8018F3C0 21B04000 */  addu       $s6, $v0, $zero
    /* 3DC 8018F3C4 CA0A030C */  jal        func_800C2B28
    /* 3E0 8018F3C8 1800A0A7 */   sh        $zero, 0x18($sp)
    /* 3E4 8018F3CC 1800A427 */  addiu      $a0, $sp, 0x18
    /* 3E8 8018F3D0 2800B027 */  addiu      $s0, $sp, 0x28
    /* 3EC 8018F3D4 0000428C */  lw         $v0, 0x0($v0)
    /* 3F0 8018F3D8 21280002 */  addu       $a1, $s0, $zero
    /* 3F4 8018F3DC 1C00A0A7 */  sh         $zero, 0x1C($sp)
    /* 3F8 8018F3E0 23100200 */  negu       $v0, $v0
    /* 3FC 8018F3E4 D5E5010C */  jal        func_80079754
    /* 400 8018F3E8 1A00A2A7 */   sh        $v0, 0x1A($sp)
    /* 404 8018F3EC 03000424 */  addiu      $a0, $zero, 0x3
    /* 408 8018F3F0 CA0A030C */  jal        func_800C2B28
    /* 40C 8018F3F4 2000A0A7 */   sh        $zero, 0x20($sp)
    /* 410 8018F3F8 2000A427 */  addiu      $a0, $sp, 0x20
    /* 414 8018F3FC 4800B127 */  addiu      $s1, $sp, 0x48
    /* 418 8018F400 0000428C */  lw         $v0, 0x0($v0)
    /* 41C 8018F404 21282002 */  addu       $a1, $s1, $zero
    /* 420 8018F408 2400A0A7 */  sh         $zero, 0x24($sp)
    /* 424 8018F40C D5E5010C */  jal        func_80079754
    /* 428 8018F410 2200A2A7 */   sh        $v0, 0x22($sp)
    /* 42C 8018F414 00000C8E */  lw         $t4, 0x0($s0)
    /* 430 8018F418 04000D8E */  lw         $t5, 0x4($s0)
    /* 434 8018F41C 0000CC48 */  ctc2       $t4, $0 /* handwritten instruction */
    /* 438 8018F420 0008CD48 */  ctc2       $t5, $1 /* handwritten instruction */
    /* 43C 8018F424 08000C8E */  lw         $t4, 0x8($s0)
    /* 440 8018F428 0C000D8E */  lw         $t5, 0xC($s0)
    /* 444 8018F42C 10000E8E */  lw         $t6, 0x10($s0)
    /* 448 8018F430 0010CC48 */  ctc2       $t4, $2 /* handwritten instruction */
    /* 44C 8018F434 0018CD48 */  ctc2       $t5, $3 /* handwritten instruction */
    /* 450 8018F438 0020CE48 */  ctc2       $t6, $4 /* handwritten instruction */
    /* 454 8018F43C 0400C626 */  addiu      $a2, $s6, 0x4
    /* 458 8018F440 0000CC94 */  lhu        $t4, 0x0($a2)
    /* 45C 8018F444 0600CD94 */  lhu        $t5, 0x6($a2)
    /* 460 8018F448 0C00CE94 */  lhu        $t6, 0xC($a2)
    /* 464 8018F44C 00488C48 */  mtc2       $t4, $9 /* handwritten instruction */
    /* 468 8018F450 00508D48 */  mtc2       $t5, $10 /* handwritten instruction */
    /* 46C 8018F454 00588E48 */  mtc2       $t6, $11 /* handwritten instruction */
    /* 470 8018F458 00000000 */  nop
    /* 474 8018F45C 00000000 */  nop
    /* 478 8018F460 12E0494A */  mvmva      1, 0, 3, 3, 0
    /* 47C 8018F464 00480C48 */  mfc2       $t4, $9 /* handwritten instruction */
    /* 480 8018F468 00500D48 */  mfc2       $t5, $10 /* handwritten instruction */
    /* 484 8018F46C 00580E48 */  mfc2       $t6, $11 /* handwritten instruction */
    /* 488 8018F470 00000CA6 */  sh         $t4, 0x0($s0)
    /* 48C 8018F474 06000DA6 */  sh         $t5, 0x6($s0)
    /* 490 8018F478 0C000EA6 */  sh         $t6, 0xC($s0)
    /* 494 8018F47C 0600C526 */  addiu      $a1, $s6, 0x6
    /* 498 8018F480 0000AC94 */  lhu        $t4, 0x0($a1)
    /* 49C 8018F484 0600AD94 */  lhu        $t5, 0x6($a1)
    /* 4A0 8018F488 0C00AE94 */  lhu        $t6, 0xC($a1)
    /* 4A4 8018F48C 00488C48 */  mtc2       $t4, $9 /* handwritten instruction */
    /* 4A8 8018F490 00508D48 */  mtc2       $t5, $10 /* handwritten instruction */
    /* 4AC 8018F494 00588E48 */  mtc2       $t6, $11 /* handwritten instruction */
    /* 4B0 8018F498 00000000 */  nop
    /* 4B4 8018F49C 00000000 */  nop
    /* 4B8 8018F4A0 12E0494A */  mvmva      1, 0, 3, 3, 0
    /* 4BC 8018F4A4 2A00A227 */  addiu      $v0, $sp, 0x2A
    /* 4C0 8018F4A8 00480C48 */  mfc2       $t4, $9 /* handwritten instruction */
    /* 4C4 8018F4AC 00500D48 */  mfc2       $t5, $10 /* handwritten instruction */
    /* 4C8 8018F4B0 00580E48 */  mfc2       $t6, $11 /* handwritten instruction */
    /* 4CC 8018F4B4 00004CA4 */  sh         $t4, 0x0($v0)
    /* 4D0 8018F4B8 06004DA4 */  sh         $t5, 0x6($v0)
    /* 4D4 8018F4BC 0C004EA4 */  sh         $t6, 0xC($v0)
    /* 4D8 8018F4C0 0800C426 */  addiu      $a0, $s6, 0x8
    /* 4DC 8018F4C4 00008C94 */  lhu        $t4, 0x0($a0)
    /* 4E0 8018F4C8 06008D94 */  lhu        $t5, 0x6($a0)
    /* 4E4 8018F4CC 0C008E94 */  lhu        $t6, 0xC($a0)
    /* 4E8 8018F4D0 00488C48 */  mtc2       $t4, $9 /* handwritten instruction */
    /* 4EC 8018F4D4 00508D48 */  mtc2       $t5, $10 /* handwritten instruction */
    /* 4F0 8018F4D8 00588E48 */  mtc2       $t6, $11 /* handwritten instruction */
    /* 4F4 8018F4DC 00000000 */  nop
    /* 4F8 8018F4E0 00000000 */  nop
    /* 4FC 8018F4E4 12E0494A */  mvmva      1, 0, 3, 3, 0
    /* 500 8018F4E8 2C00A227 */  addiu      $v0, $sp, 0x2C
    /* 504 8018F4EC 00480C48 */  mfc2       $t4, $9 /* handwritten instruction */
    /* 508 8018F4F0 00500D48 */  mfc2       $t5, $10 /* handwritten instruction */
    /* 50C 8018F4F4 00580E48 */  mfc2       $t6, $11 /* handwritten instruction */
    /* 510 8018F4F8 00004CA4 */  sh         $t4, 0x0($v0)
    /* 514 8018F4FC 06004DA4 */  sh         $t5, 0x6($v0)
    /* 518 8018F500 0C004EA4 */  sh         $t6, 0xC($v0)
    /* 51C 8018F504 14000C8E */  lw         $t4, 0x14($s0)
    /* 520 8018F508 18000D8E */  lw         $t5, 0x18($s0)
    /* 524 8018F50C 0028CC48 */  ctc2       $t4, $5 /* handwritten instruction */
    /* 528 8018F510 1C000E8E */  lw         $t6, 0x1C($s0)
    /* 52C 8018F514 0030CD48 */  ctc2       $t5, $6 /* handwritten instruction */
    /* 530 8018F518 0038CE48 */  ctc2       $t6, $7 /* handwritten instruction */
    /* 534 8018F51C 1800C326 */  addiu      $v1, $s6, 0x18
    /* 538 8018F520 04006D94 */  lhu        $t5, 0x4($v1)
    /* 53C 8018F524 00006C94 */  lhu        $t4, 0x0($v1)
    /* 540 8018F528 006C0D00 */  sll        $t5, $t5, 16
    /* 544 8018F52C 25608D01 */  or         $t4, $t4, $t5
    /* 548 8018F530 00008C48 */  mtc2       $t4, $0 /* handwritten instruction */
    /* 54C 8018F534 080061C8 */  lwc2       $1, 0x8($v1)
    /* 550 8018F538 00000000 */  nop
    /* 554 8018F53C 00000000 */  nop
    /* 558 8018F540 1200484A */  mvmva      1, 0, 0, 0, 0
    /* 55C 8018F544 3C00A227 */  addiu      $v0, $sp, 0x3C
    /* 560 8018F548 000049E8 */  swc2       $9, 0x0($v0)
    /* 564 8018F54C 04004AE8 */  swc2       $10, 0x4($v0)
    /* 568 8018F550 08004BE8 */  swc2       $11, 0x8($v0)
    /* 56C 8018F554 00002C8E */  lw         $t4, 0x0($s1)
    /* 570 8018F558 04002D8E */  lw         $t5, 0x4($s1)
    /* 574 8018F55C 0000CC48 */  ctc2       $t4, $0 /* handwritten instruction */
    /* 578 8018F560 0008CD48 */  ctc2       $t5, $1 /* handwritten instruction */
    /* 57C 8018F564 08002C8E */  lw         $t4, 0x8($s1)
    /* 580 8018F568 0C002D8E */  lw         $t5, 0xC($s1)
    /* 584 8018F56C 10002E8E */  lw         $t6, 0x10($s1)
    /* 588 8018F570 0010CC48 */  ctc2       $t4, $2 /* handwritten instruction */
    /* 58C 8018F574 0018CD48 */  ctc2       $t5, $3 /* handwritten instruction */
    /* 590 8018F578 0020CE48 */  ctc2       $t6, $4 /* handwritten instruction */
    /* 594 8018F57C 0000CC94 */  lhu        $t4, 0x0($a2)
    /* 598 8018F580 0600CD94 */  lhu        $t5, 0x6($a2)
    /* 59C 8018F584 0C00CE94 */  lhu        $t6, 0xC($a2)
    /* 5A0 8018F588 00488C48 */  mtc2       $t4, $9 /* handwritten instruction */
    /* 5A4 8018F58C 00508D48 */  mtc2       $t5, $10 /* handwritten instruction */
    /* 5A8 8018F590 00588E48 */  mtc2       $t6, $11 /* handwritten instruction */
    /* 5AC 8018F594 00000000 */  nop
    /* 5B0 8018F598 00000000 */  nop
    /* 5B4 8018F59C 12E0494A */  mvmva      1, 0, 3, 3, 0
    /* 5B8 8018F5A0 00480C48 */  mfc2       $t4, $9 /* handwritten instruction */
    /* 5BC 8018F5A4 00500D48 */  mfc2       $t5, $10 /* handwritten instruction */
    /* 5C0 8018F5A8 00580E48 */  mfc2       $t6, $11 /* handwritten instruction */
    /* 5C4 8018F5AC 00002CA6 */  sh         $t4, 0x0($s1)
    /* 5C8 8018F5B0 06002DA6 */  sh         $t5, 0x6($s1)
    /* 5CC 8018F5B4 0C002EA6 */  sh         $t6, 0xC($s1)
    /* 5D0 8018F5B8 0000AC94 */  lhu        $t4, 0x0($a1)
    /* 5D4 8018F5BC 0600AD94 */  lhu        $t5, 0x6($a1)
    /* 5D8 8018F5C0 0C00AE94 */  lhu        $t6, 0xC($a1)
    /* 5DC 8018F5C4 00488C48 */  mtc2       $t4, $9 /* handwritten instruction */
    /* 5E0 8018F5C8 00508D48 */  mtc2       $t5, $10 /* handwritten instruction */
    /* 5E4 8018F5CC 00588E48 */  mtc2       $t6, $11 /* handwritten instruction */
    /* 5E8 8018F5D0 00000000 */  nop
    /* 5EC 8018F5D4 00000000 */  nop
    /* 5F0 8018F5D8 12E0494A */  mvmva      1, 0, 3, 3, 0
    /* 5F4 8018F5DC 4A00A227 */  addiu      $v0, $sp, 0x4A
    /* 5F8 8018F5E0 00480C48 */  mfc2       $t4, $9 /* handwritten instruction */
    /* 5FC 8018F5E4 00500D48 */  mfc2       $t5, $10 /* handwritten instruction */
    /* 600 8018F5E8 00580E48 */  mfc2       $t6, $11 /* handwritten instruction */
    /* 604 8018F5EC 00004CA4 */  sh         $t4, 0x0($v0)
    /* 608 8018F5F0 06004DA4 */  sh         $t5, 0x6($v0)
    /* 60C 8018F5F4 0C004EA4 */  sh         $t6, 0xC($v0)
    /* 610 8018F5F8 00008C94 */  lhu        $t4, 0x0($a0)
    /* 614 8018F5FC 06008D94 */  lhu        $t5, 0x6($a0)
    /* 618 8018F600 0C008E94 */  lhu        $t6, 0xC($a0)
    /* 61C 8018F604 00488C48 */  mtc2       $t4, $9 /* handwritten instruction */
    /* 620 8018F608 00508D48 */  mtc2       $t5, $10 /* handwritten instruction */
    /* 624 8018F60C 00588E48 */  mtc2       $t6, $11 /* handwritten instruction */
    /* 628 8018F610 00000000 */  nop
    /* 62C 8018F614 00000000 */  nop
    /* 630 8018F618 12E0494A */  mvmva      1, 0, 3, 3, 0
    /* 634 8018F61C 4C00A227 */  addiu      $v0, $sp, 0x4C
    /* 638 8018F620 00480C48 */  mfc2       $t4, $9 /* handwritten instruction */
    /* 63C 8018F624 00500D48 */  mfc2       $t5, $10 /* handwritten instruction */
    /* 640 8018F628 00580E48 */  mfc2       $t6, $11 /* handwritten instruction */
    /* 644 8018F62C 00004CA4 */  sh         $t4, 0x0($v0)
    /* 648 8018F630 06004DA4 */  sh         $t5, 0x6($v0)
    /* 64C 8018F634 0C004EA4 */  sh         $t6, 0xC($v0)
    /* 650 8018F638 14002C8E */  lw         $t4, 0x14($s1)
    /* 654 8018F63C 18002D8E */  lw         $t5, 0x18($s1)
    /* 658 8018F640 0028CC48 */  ctc2       $t4, $5 /* handwritten instruction */
    /* 65C 8018F644 1C002E8E */  lw         $t6, 0x1C($s1)
    /* 660 8018F648 0030CD48 */  ctc2       $t5, $6 /* handwritten instruction */
    /* 664 8018F64C 0038CE48 */  ctc2       $t6, $7 /* handwritten instruction */
    /* 668 8018F650 04006D94 */  lhu        $t5, 0x4($v1)
    /* 66C 8018F654 00006C94 */  lhu        $t4, 0x0($v1)
    /* 670 8018F658 006C0D00 */  sll        $t5, $t5, 16
    /* 674 8018F65C 25608D01 */  or         $t4, $t4, $t5
    /* 678 8018F660 00008C48 */  mtc2       $t4, $0 /* handwritten instruction */
    /* 67C 8018F664 080061C8 */  lwc2       $1, 0x8($v1)
    /* 680 8018F668 00000000 */  nop
    /* 684 8018F66C 00000000 */  nop
    /* 688 8018F670 1200484A */  mvmva      1, 0, 0, 0, 0
    /* 68C 8018F674 5C00A227 */  addiu      $v0, $sp, 0x5C
    /* 690 8018F678 000049E8 */  swc2       $9, 0x0($v0)
    /* 694 8018F67C 04004AE8 */  swc2       $10, 0x4($v0)
    /* 698 8018F680 08004BE8 */  swc2       $11, 0x8($v0)
    /* 69C 8018F684 21A00000 */  addu       $s4, $zero, $zero
    /* 6A0 8018F688 2190A002 */  addu       $s2, $s5, $zero
    /* 6A4 8018F68C 2188A002 */  addu       $s1, $s5, $zero
    /* 6A8 8018F690 2198A002 */  addu       $s3, $s5, $zero
  .L8018F694:
    /* 6AC 8018F694 95C6010C */  jal        func_80071A54
    /* 6B0 8018F698 2180B402 */   addu      $s0, $s5, $s4
    /* 6B4 8018F69C 6666033C */  lui        $v1, (0x66666667 >> 16)
    /* 6B8 8018F6A0 67666334 */  ori        $v1, $v1, (0x66666667 & 0xFFFF)
    /* 6BC 8018F6A4 18004300 */  mult       $v0, $v1
    /* 6C0 8018F6A8 02000424 */  addiu      $a0, $zero, 0x2
    /* 6C4 8018F6AC C31F0200 */  sra        $v1, $v0, 31
    /* 6C8 8018F6B0 1E0000A2 */  sb         $zero, 0x1E($s0)
    /* 6CC 8018F6B4 10380000 */  mfhi       $a3
    /* 6D0 8018F6B8 83280700 */  sra        $a1, $a3, 2
    /* 6D4 8018F6BC 2328A300 */  subu       $a1, $a1, $v1
    /* 6D8 8018F6C0 80180500 */  sll        $v1, $a1, 2
    /* 6DC 8018F6C4 21186500 */  addu       $v1, $v1, $a1
    /* 6E0 8018F6C8 40180300 */  sll        $v1, $v1, 1
    /* 6E4 8018F6CC 23104300 */  subu       $v0, $v0, $v1
    /* 6E8 8018F6D0 01004224 */  addiu      $v0, $v0, 0x1
    /* 6EC 8018F6D4 CA0A030C */  jal        func_800C2B28
    /* 6F0 8018F6D8 1A0002A2 */   sb        $v0, 0x1A($s0)
    /* 6F4 8018F6DC 0000428C */  lw         $v0, 0x0($v0)
    /* 6F8 8018F6E0 00000000 */  nop
    /* 6FC 8018F6E4 220062A6 */  sh         $v0, 0x22($s3)
    /* 700 8018F6E8 1800C28E */  lw         $v0, 0x18($s6)
    /* 704 8018F6EC 00000000 */  nop
    /* 708 8018F6F0 00140200 */  sll        $v0, $v0, 16
    /* 70C 8018F6F4 3C0022AE */  sw         $v0, 0x3C($s1)
    /* 710 8018F6F8 1C00C28E */  lw         $v0, 0x1C($s6)
    /* 714 8018F6FC 00000000 */  nop
    /* 718 8018F700 00140200 */  sll        $v0, $v0, 16
    /* 71C 8018F704 400022AE */  sw         $v0, 0x40($s1)
    /* 720 8018F708 2000C28E */  lw         $v0, 0x20($s6)
    /* 724 8018F70C 01009426 */  addiu      $s4, $s4, 0x1
    /* 728 8018F710 00140200 */  sll        $v0, $v0, 16
    /* 72C 8018F714 440022AE */  sw         $v0, 0x44($s1)
    /* 730 8018F718 6C0040A6 */  sh         $zero, 0x6C($s2)
    /* 734 8018F71C 6E0040A6 */  sh         $zero, 0x6E($s2)
    /* 738 8018F720 700040A6 */  sh         $zero, 0x70($s2)
    /* 73C 8018F724 08005226 */  addiu      $s2, $s2, 0x8
    /* 740 8018F728 10003126 */  addiu      $s1, $s1, 0x10
    /* 744 8018F72C 2A0060A6 */  sh         $zero, 0x2A($s3)
    /* 748 8018F730 02007326 */  addiu      $s3, $s3, 0x2
    /* 74C 8018F734 01000224 */  addiu      $v0, $zero, 0x1
    /* 750 8018F738 0E0002A2 */  sb         $v0, 0xE($s0)
    /* 754 8018F73C 0300822A */  slti       $v0, $s4, 0x3
    /* 758 8018F740 160000A2 */  sb         $zero, 0x16($s0)
    /* 75C 8018F744 D3FF4014 */  bnez       $v0, .L8018F694
    /* 760 8018F748 120000A2 */   sb        $zero, 0x12($s0)
    /* 764 8018F74C 21200000 */  addu       $a0, $zero, $zero
    /* 768 8018F750 03000224 */  addiu      $v0, $zero, 0x3
    /* 76C 8018F754 CA0A030C */  jal        func_800C2B28
    /* 770 8018F758 0000A2A6 */   sh        $v0, 0x0($s5)
    /* 774 8018F75C 0000428C */  lw         $v0, 0x0($v0)
    /* 778 8018F760 01000424 */  addiu      $a0, $zero, 0x1
    /* 77C 8018F764 CA0A030C */  jal        func_800C2B28
    /* 780 8018F768 0200A2A6 */   sh        $v0, 0x2($s5)
    /* 784 8018F76C 0000428C */  lw         $v0, 0x0($v0)
    /* 788 8018F770 05000424 */  addiu      $a0, $zero, 0x5
    /* 78C 8018F774 CA0A030C */  jal        func_800C2B28
    /* 790 8018F778 0400A2A6 */   sh        $v0, 0x4($s5)
    /* 794 8018F77C 0000428C */  lw         $v0, 0x0($v0)
    /* 798 8018F780 04000424 */  addiu      $a0, $zero, 0x4
    /* 79C 8018F784 CA0A030C */  jal        func_800C2B28
    /* 7A0 8018F788 0600A2A6 */   sh        $v0, 0x6($s5)
    /* 7A4 8018F78C 0000428C */  lw         $v0, 0x0($v0)
    /* 7A8 8018F790 01000424 */  addiu      $a0, $zero, 0x1
    /* 7AC 8018F794 C40A030C */  jal        func_800C2B10
    /* 7B0 8018F798 0A00A2A2 */   sb        $v0, 0xA($s5)
    /* 7B4 8018F79C 2800A427 */  addiu      $a0, $sp, 0x28
    /* 7B8 8018F7A0 1000A527 */  addiu      $a1, $sp, 0x10
    /* 7BC 8018F7A4 0000428C */  lw         $v0, 0x0($v0)
    /* 7C0 8018F7A8 9C00A626 */  addiu      $a2, $s5, 0x9C
    /* 7C4 8018F7AC 0800A2A6 */  sh         $v0, 0x8($s5)
    /* 7C8 8018F7B0 00100224 */  addiu      $v0, $zero, 0x1000
    /* 7CC 8018F7B4 1000A0A7 */  sh         $zero, 0x10($sp)
    /* 7D0 8018F7B8 1200A0A7 */  sh         $zero, 0x12($sp)
    /* 7D4 8018F7BC 0DE3010C */  jal        func_80078C34
    /* 7D8 8018F7C0 1400A2A7 */   sh        $v0, 0x14($sp)
    /* 7DC 8018F7C4 0400D026 */  addiu      $s0, $s6, 0x4
    /* 7E0 8018F7C8 21200002 */  addu       $a0, $s0, $zero
    /* 7E4 8018F7CC 1000A527 */  addiu      $a1, $sp, 0x10
    /* 7E8 8018F7D0 0DE3010C */  jal        func_80078C34
    /* 7EC 8018F7D4 A400A626 */   addiu     $a2, $s5, 0xA4
    /* 7F0 8018F7D8 4800A427 */  addiu      $a0, $sp, 0x48
    /* 7F4 8018F7DC 1000A527 */  addiu      $a1, $sp, 0x10
    /* 7F8 8018F7E0 0DE3010C */  jal        func_80078C34
    /* 7FC 8018F7E4 AC00A626 */   addiu     $a2, $s5, 0xAC
    /* 800 8018F7E8 2120E002 */  addu       $a0, $s7, $zero
    /* 804 8018F7EC 73050524 */  addiu      $a1, $zero, 0x573
    /* 808 8018F7F0 B219030C */  jal        func_800C66C8
    /* 80C 8018F7F4 21300002 */   addu      $a2, $s0, $zero
    /* 810 8018F7F8 8800BF8F */  lw         $ra, 0x88($sp)
    /* 814 8018F7FC 8400B78F */  lw         $s7, 0x84($sp)
    /* 818 8018F800 8000B68F */  lw         $s6, 0x80($sp)
    /* 81C 8018F804 7C00B58F */  lw         $s5, 0x7C($sp)
    /* 820 8018F808 7800B48F */  lw         $s4, 0x78($sp)
    /* 824 8018F80C 7400B38F */  lw         $s3, 0x74($sp)
    /* 828 8018F810 7000B28F */  lw         $s2, 0x70($sp)
    /* 82C 8018F814 6C00B18F */  lw         $s1, 0x6C($sp)
    /* 830 8018F818 6800B08F */  lw         $s0, 0x68($sp)
    /* 834 8018F81C 9000BD27 */  addiu      $sp, $sp, 0x90
    /* 838 8018F820 0800E003 */  jr         $ra
    /* 83C 8018F824 00000000 */   nop
endlabel func_8018F388

nonmatching func_8018F828, 0x3A4

glabel func_8018F828
    /* 840 8018F828 30FFBD27 */  addiu      $sp, $sp, -0xD0
    /* 844 8018F82C B000B2AF */  sw         $s2, 0xB0($sp)
    /* 848 8018F830 2190C000 */  addu       $s2, $a2, $zero
    /* 84C 8018F834 CC00BFAF */  sw         $ra, 0xCC($sp)
    /* 850 8018F838 C800BEAF */  sw         $fp, 0xC8($sp)
    /* 854 8018F83C C400B7AF */  sw         $s7, 0xC4($sp)
    /* 858 8018F840 C000B6AF */  sw         $s6, 0xC0($sp)
    /* 85C 8018F844 BC00B5AF */  sw         $s5, 0xBC($sp)
    /* 860 8018F848 B800B4AF */  sw         $s4, 0xB8($sp)
    /* 864 8018F84C B400B3AF */  sw         $s3, 0xB4($sp)
    /* 868 8018F850 AC00B1AF */  sw         $s1, 0xAC($sp)
    /* 86C 8018F854 A800B0AF */  sw         $s0, 0xA8($sp)
    /* 870 8018F858 D40A030C */  jal        func_800C2B50
    /* 874 8018F85C A000A5AF */   sw        $a1, 0xA0($sp)
    /* 878 8018F860 1980063C */  lui        $a2, %hi(D_8018EFF4)
    /* 87C 8018F864 F4EFC624 */  addiu      $a2, $a2, %lo(D_8018EFF4)
    /* 880 8018F868 0300C388 */  lwl        $v1, 0x3($a2)
    /* 884 8018F86C 0000C398 */  lwr        $v1, 0x0($a2)
    /* 888 8018F870 0700C488 */  lwl        $a0, 0x7($a2)
    /* 88C 8018F874 0400C498 */  lwr        $a0, 0x4($a2)
    /* 890 8018F878 5300A3AB */  swl        $v1, 0x53($sp)
    /* 894 8018F87C 5000A3BB */  swr        $v1, 0x50($sp)
    /* 898 8018F880 5700A4AB */  swl        $a0, 0x57($sp)
    /* 89C 8018F884 5400A4BB */  swr        $a0, 0x54($sp)
    /* 8A0 8018F888 21A00000 */  addu       $s4, $zero, $zero
    /* 8A4 8018F88C 7000BE27 */  addiu      $fp, $sp, 0x70
    /* 8A8 8018F890 3000B727 */  addiu      $s7, $sp, 0x30
    /* 8AC 8018F894 21984002 */  addu       $s3, $s2, $zero
    /* 8B0 8018F898 2C004490 */  lbu        $a0, 0x2C($v0)
    /* 8B4 8018F89C AB0B030C */  jal        func_800C2EAC
    /* 8B8 8018F8A0 21884002 */   addu      $s1, $s2, $zero
    /* 8BC 8018F8A4 260C030C */  jal        func_800C3098
    /* 8C0 8018F8A8 10000424 */   addiu     $a0, $zero, 0x10
  .L8018F8AC:
    /* 8C4 8018F8AC 21A85402 */  addu       $s5, $s2, $s4
    /* 8C8 8018F8B0 1600A282 */  lb         $v0, 0x16($s5)
    /* 8CC 8018F8B4 00000000 */  nop
    /* 8D0 8018F8B8 B2004004 */  bltz       $v0, .L8018FB84
    /* 8D4 8018F8BC C0B01400 */   sll       $s6, $s4, 3
    /* 8D8 8018F8C0 6C00C426 */  addiu      $a0, $s6, 0x6C
    /* 8DC 8018F8C4 21204402 */  addu       $a0, $s2, $a0
    /* 8E0 8018F8C8 D5E5010C */  jal        func_80079754
    /* 8E4 8018F8CC 1000A527 */   addiu     $a1, $sp, 0x10
    /* 8E8 8018F8D0 2120C003 */  addu       $a0, $fp, $zero
    /* 8EC 8018F8D4 21280000 */  addu       $a1, $zero, $zero
    /* 8F0 8018F8D8 91C6010C */  jal        func_80071A44
    /* 8F4 8018F8DC 10000624 */   addiu     $a2, $zero, 0x10
    /* 8F8 8018F8E0 2A002296 */  lhu        $v0, 0x2A($s1)
    /* 8FC 8018F8E4 00000000 */  nop
    /* 900 8018F8E8 42100200 */  srl        $v0, $v0, 1
    /* 904 8018F8EC 7000A2AF */  sw         $v0, 0x70($sp)
    /* 908 8018F8F0 2A002296 */  lhu        $v0, 0x2A($s1)
    /* 90C 8018F8F4 1000A427 */  addiu      $a0, $sp, 0x10
    /* 910 8018F8F8 42100200 */  srl        $v0, $v0, 1
    /* 914 8018F8FC 7400A2AF */  sw         $v0, 0x74($sp)
    /* 918 8018F900 2A002296 */  lhu        $v0, 0x2A($s1)
    /* 91C 8018F904 00000000 */  nop
    /* 920 8018F908 42100200 */  srl        $v0, $v0, 1
    /* 924 8018F90C 7800A2AF */  sw         $v0, 0x78($sp)
    /* 928 8018F910 7000A28F */  lw         $v0, 0x70($sp)
    /* 92C 8018F914 7400A38F */  lw         $v1, 0x74($sp)
    /* 930 8018F918 7800A68F */  lw         $a2, 0x78($sp)
    /* 934 8018F91C 7C00A78F */  lw         $a3, 0x7C($sp)
    /* 938 8018F920 6000A2AF */  sw         $v0, 0x60($sp)
    /* 93C 8018F924 6400A3AF */  sw         $v1, 0x64($sp)
    /* 940 8018F928 6800A6AF */  sw         $a2, 0x68($sp)
    /* 944 8018F92C 6C00A7AF */  sw         $a3, 0x6C($sp)
    /* 948 8018F930 31E3010C */  jal        func_80078CC4
    /* 94C 8018F934 6000A527 */   addiu     $a1, $sp, 0x60
    /* 950 8018F938 3E006286 */  lh         $v0, 0x3E($s3)
    /* 954 8018F93C 0B004382 */  lb         $v1, 0xB($s2)
    /* 958 8018F940 00000000 */  nop
    /* 95C 8018F944 21104300 */  addu       $v0, $v0, $v1
    /* 960 8018F948 2400A2AF */  sw         $v0, 0x24($sp)
    /* 964 8018F94C 42006286 */  lh         $v0, 0x42($s3)
    /* 968 8018F950 0C004382 */  lb         $v1, 0xC($s2)
    /* 96C 8018F954 00000000 */  nop
    /* 970 8018F958 21104300 */  addu       $v0, $v0, $v1
    /* 974 8018F95C 2800A2AF */  sw         $v0, 0x28($sp)
    /* 978 8018F960 46006286 */  lh         $v0, 0x46($s3)
    /* 97C 8018F964 0D004382 */  lb         $v1, 0xD($s2)
    /* 980 8018F968 A000A78F */  lw         $a3, 0xA0($sp)
    /* 984 8018F96C 21104300 */  addu       $v0, $v0, $v1
    /* 988 8018F970 2C00A2AF */  sw         $v0, 0x2C($sp)
    /* 98C 8018F974 1E00A292 */  lbu        $v0, 0x1E($s5)
    /* 990 8018F978 1980043C */  lui        $a0, %hi(D_80190078)
    /* 994 8018F97C 78008424 */  addiu      $a0, $a0, %lo(D_80190078)
    /* 998 8018F980 1980013C */  lui        $at, %hi(D_801900A2)
    /* 99C 8018F984 A20022A4 */  sh         $v0, %lo(D_801900A2)($at)
    /* 9A0 8018F988 0200E584 */  lh         $a1, 0x2($a3)
    /* 9A4 8018F98C 1980063C */  lui        $a2, %hi(D_80190098)
    /* 9A8 8018F990 9800C624 */  addiu      $a2, $a2, %lo(D_80190098)
    /* 9AC 8018F994 4D0C030C */  jal        func_800C3134
    /* 9B0 8018F998 00000000 */   nop
    /* 9B4 8018F99C 40000424 */  addiu      $a0, $zero, 0x40
    /* 9B8 8018F9A0 FC0B030C */  jal        func_800C2FF0
    /* 9BC 8018F9A4 40000524 */   addiu     $a1, $zero, 0x40
    /* 9C0 8018F9A8 8E0C030C */  jal        func_800C3238
    /* 9C4 8018F9AC 02000424 */   addiu     $a0, $zero, 0x2
    /* 9C8 8018F9B0 1980043C */  lui        $a0, %hi(D_80190098)
    /* 9CC 8018F9B4 98008424 */  addiu      $a0, $a0, %lo(D_80190098)
    /* 9D0 8018F9B8 1000A527 */  addiu      $a1, $sp, 0x10
    /* 9D4 8018F9BC A910030C */  jal        func_800C42A4
    /* 9D8 8018F9C0 01000624 */   addiu     $a2, $zero, 0x1
    /* 9DC 8018F9C4 08004386 */  lh         $v1, 0x8($s2)
    /* 9E0 8018F9C8 01000224 */  addiu      $v0, $zero, 0x1
    /* 9E4 8018F9CC 6D006214 */  bne        $v1, $v0, .L8018FB84
    /* 9E8 8018F9D0 00000000 */   nop
    /* 9EC 8018F9D4 A000A78F */  lw         $a3, 0xA0($sp)
    /* 9F0 8018F9D8 00000000 */  nop
    /* 9F4 8018F9DC 0200E484 */  lh         $a0, 0x2($a3)
    /* 9F8 8018F9E0 3DDF010C */  jal        func_80077CF4
    /* 9FC 8018F9E4 C0210400 */   sll       $a0, $a0, 7
    /* A00 8018F9E8 32002396 */  lhu        $v1, 0x32($s1)
    /* A04 8018F9EC C3100200 */  sra        $v0, $v0, 3
    /* A08 8018F9F0 21104300 */  addu       $v0, $v0, $v1
    /* A0C 8018F9F4 21804000 */  addu       $s0, $v0, $zero
    /* A10 8018F9F8 00140200 */  sll        $v0, $v0, 16
    /* A14 8018F9FC 2A002396 */  lhu        $v1, 0x2A($s1)
    /* A18 8018FA00 03140200 */  sra        $v0, $v0, 16
    /* A1C 8018FA04 2A106200 */  slt        $v0, $v1, $v0
    /* A20 8018FA08 02004010 */  beqz       $v0, .L8018FA14
    /* A24 8018FA0C 2110D202 */   addu      $v0, $s6, $s2
    /* A28 8018FA10 21806000 */  addu       $s0, $v1, $zero
  .L8018FA14:
    /* A2C 8018FA14 6F004388 */  lwl        $v1, 0x6F($v0)
    /* A30 8018FA18 6C004398 */  lwr        $v1, 0x6C($v0)
    /* A34 8018FA1C 73004488 */  lwl        $a0, 0x73($v0)
    /* A38 8018FA20 70004498 */  lwr        $a0, 0x70($v0)
    /* A3C 8018FA24 5B00A3AB */  swl        $v1, 0x5B($sp)
    /* A40 8018FA28 5800A3BB */  swr        $v1, 0x58($sp)
    /* A44 8018FA2C 5F00A4AB */  swl        $a0, 0x5F($sp)
    /* A48 8018FA30 5C00A4BB */  swr        $a0, 0x5C($sp)
    /* A4C 8018FA34 5800A427 */  addiu      $a0, $sp, 0x58
    /* A50 8018FA38 1000A527 */  addiu      $a1, $sp, 0x10
    /* A54 8018FA3C 00841000 */  sll        $s0, $s0, 16
    /* A58 8018FA40 43841000 */  sra        $s0, $s0, 17
    /* A5C 8018FA44 22002296 */  lhu        $v0, 0x22($s1)
    /* A60 8018FA48 5C00A397 */  lhu        $v1, 0x5C($sp)
    /* A64 8018FA4C 00110200 */  sll        $v0, $v0, 4
    /* A68 8018FA50 21186200 */  addu       $v1, $v1, $v0
    /* A6C 8018FA54 D5E5010C */  jal        func_80079754
    /* A70 8018FA58 5C00A3A7 */   sh        $v1, 0x5C($sp)
    /* A74 8018FA5C 2120C003 */  addu       $a0, $fp, $zero
    /* A78 8018FA60 21280000 */  addu       $a1, $zero, $zero
    /* A7C 8018FA64 91C6010C */  jal        func_80071A44
    /* A80 8018FA68 10000624 */   addiu     $a2, $zero, 0x10
    /* A84 8018FA6C 1000A427 */  addiu      $a0, $sp, 0x10
    /* A88 8018FA70 2128C003 */  addu       $a1, $fp, $zero
    /* A8C 8018FA74 7000B0AF */  sw         $s0, 0x70($sp)
    /* A90 8018FA78 7400B0AF */  sw         $s0, 0x74($sp)
    /* A94 8018FA7C 31E3010C */  jal        func_80078CC4
    /* A98 8018FA80 7800B0AF */   sw        $s0, 0x78($sp)
    /* A9C 8018FA84 3E006286 */  lh         $v0, 0x3E($s3)
    /* AA0 8018FA88 0B004382 */  lb         $v1, 0xB($s2)
    /* AA4 8018FA8C 1980043C */  lui        $a0, %hi(D_80190098)
    /* AA8 8018FA90 98008424 */  addiu      $a0, $a0, %lo(D_80190098)
    /* AAC 8018FA94 21104300 */  addu       $v0, $v0, $v1
    /* AB0 8018FA98 2400A2AF */  sw         $v0, 0x24($sp)
    /* AB4 8018FA9C 42006286 */  lh         $v0, 0x42($s3)
    /* AB8 8018FAA0 0C004382 */  lb         $v1, 0xC($s2)
    /* ABC 8018FAA4 1000A527 */  addiu      $a1, $sp, 0x10
    /* AC0 8018FAA8 21104300 */  addu       $v0, $v0, $v1
    /* AC4 8018FAAC 2800A2AF */  sw         $v0, 0x28($sp)
    /* AC8 8018FAB0 46006286 */  lh         $v0, 0x46($s3)
    /* ACC 8018FAB4 0D004382 */  lb         $v1, 0xD($s2)
    /* AD0 8018FAB8 01000624 */  addiu      $a2, $zero, 0x1
    /* AD4 8018FABC 21104300 */  addu       $v0, $v0, $v1
    /* AD8 8018FAC0 A910030C */  jal        func_800C42A4
    /* ADC 8018FAC4 2C00A2AF */   sw        $v0, 0x2C($sp)
    /* AE0 8018FAC8 5000A427 */  addiu      $a0, $sp, 0x50
    /* AE4 8018FACC 31E5010C */  jal        func_800794C4
    /* AE8 8018FAD0 2128E002 */   addu      $a1, $s7, $zero
    /* AEC 8018FAD4 9000A427 */  addiu      $a0, $sp, 0x90
    /* AF0 8018FAD8 21280000 */  addu       $a1, $zero, $zero
    /* AF4 8018FADC 91C6010C */  jal        func_80071A44
    /* AF8 8018FAE0 10000624 */   addiu     $a2, $zero, 0x10
    /* AFC 8018FAE4 2A002296 */  lhu        $v0, 0x2A($s1)
    /* B00 8018FAE8 00000000 */  nop
    /* B04 8018FAEC 9000A2AF */  sw         $v0, 0x90($sp)
    /* B08 8018FAF0 2A002296 */  lhu        $v0, 0x2A($s1)
    /* B0C 8018FAF4 2120E002 */  addu       $a0, $s7, $zero
    /* B10 8018FAF8 9400A2AF */  sw         $v0, 0x94($sp)
    /* B14 8018FAFC 2A002296 */  lhu        $v0, 0x2A($s1)
    /* B18 8018FB00 00000000 */  nop
    /* B1C 8018FB04 9800A2AF */  sw         $v0, 0x98($sp)
    /* B20 8018FB08 9000A28F */  lw         $v0, 0x90($sp)
    /* B24 8018FB0C 9400A38F */  lw         $v1, 0x94($sp)
    /* B28 8018FB10 9800A68F */  lw         $a2, 0x98($sp)
    /* B2C 8018FB14 9C00A78F */  lw         $a3, 0x9C($sp)
    /* B30 8018FB18 8000A2AF */  sw         $v0, 0x80($sp)
    /* B34 8018FB1C 8400A3AF */  sw         $v1, 0x84($sp)
    /* B38 8018FB20 8800A6AF */  sw         $a2, 0x88($sp)
    /* B3C 8018FB24 8C00A7AF */  sw         $a3, 0x8C($sp)
    /* B40 8018FB28 31E3010C */  jal        func_80078CC4
    /* B44 8018FB2C 8000A527 */   addiu     $a1, $sp, 0x80
    /* B48 8018FB30 3E006286 */  lh         $v0, 0x3E($s3)
    /* B4C 8018FB34 0980033C */  lui        $v1, %hi(D_800942EC)
    /* B50 8018FB38 EC426384 */  lh         $v1, %lo(D_800942EC)($v1)
    /* B54 8018FB3C 20000424 */  addiu      $a0, $zero, 0x20
    /* B58 8018FB40 4400A2AF */  sw         $v0, 0x44($sp)
    /* B5C 8018FB44 4800A3AF */  sw         $v1, 0x48($sp)
    /* B60 8018FB48 46006286 */  lh         $v0, 0x46($s3)
    /* B64 8018FB4C 20000524 */  addiu      $a1, $zero, 0x20
    /* B68 8018FB50 4C00A2AF */  sw         $v0, 0x4C($sp)
    /* B6C 8018FB54 1E00A292 */  lbu        $v0, 0x1E($s5)
    /* B70 8018FB58 1980103C */  lui        $s0, %hi(D_80190092)
    /* B74 8018FB5C 92001026 */  addiu      $s0, $s0, %lo(D_80190092)
    /* B78 8018FB60 42100200 */  srl        $v0, $v0, 1
    /* B7C 8018FB64 FC0B030C */  jal        func_800C2FF0
    /* B80 8018FB68 000002A6 */   sh        $v0, 0x0($s0)
    /* B84 8018FB6C 8E0C030C */  jal        func_800C3238
    /* B88 8018FB70 03000424 */   addiu     $a0, $zero, 0x3
    /* B8C 8018FB74 F6FF0426 */  addiu      $a0, $s0, -0xA
    /* B90 8018FB78 2128E002 */  addu       $a1, $s7, $zero
    /* B94 8018FB7C A910030C */  jal        func_800C42A4
    /* B98 8018FB80 21300000 */   addu      $a2, $zero, $zero
  .L8018FB84:
    /* B9C 8018FB84 10007326 */  addiu      $s3, $s3, 0x10
    /* BA0 8018FB88 01009426 */  addiu      $s4, $s4, 0x1
    /* BA4 8018FB8C 0300822E */  sltiu      $v0, $s4, 0x3
    /* BA8 8018FB90 46FF4014 */  bnez       $v0, .L8018F8AC
    /* BAC 8018FB94 02003126 */   addiu     $s1, $s1, 0x2
    /* BB0 8018FB98 CC00BF8F */  lw         $ra, 0xCC($sp)
    /* BB4 8018FB9C C800BE8F */  lw         $fp, 0xC8($sp)
    /* BB8 8018FBA0 C400B78F */  lw         $s7, 0xC4($sp)
    /* BBC 8018FBA4 C000B68F */  lw         $s6, 0xC0($sp)
    /* BC0 8018FBA8 BC00B58F */  lw         $s5, 0xBC($sp)
    /* BC4 8018FBAC B800B48F */  lw         $s4, 0xB8($sp)
    /* BC8 8018FBB0 B400B38F */  lw         $s3, 0xB4($sp)
    /* BCC 8018FBB4 B000B28F */  lw         $s2, 0xB0($sp)
    /* BD0 8018FBB8 AC00B18F */  lw         $s1, 0xAC($sp)
    /* BD4 8018FBBC A800B08F */  lw         $s0, 0xA8($sp)
    /* BD8 8018FBC0 D000BD27 */  addiu      $sp, $sp, 0xD0
    /* BDC 8018FBC4 0800E003 */  jr         $ra
    /* BE0 8018FBC8 00000000 */   nop
endlabel func_8018F828

nonmatching func_8018FBCC, 0x42C

glabel func_8018FBCC
    /* BE4 8018FBCC B0FFBD27 */  addiu      $sp, $sp, -0x50
    /* BE8 8018FBD0 4800BEAF */  sw         $fp, 0x48($sp)
    /* BEC 8018FBD4 21F0A000 */  addu       $fp, $a1, $zero
    /* BF0 8018FBD8 3400B3AF */  sw         $s3, 0x34($sp)
    /* BF4 8018FBDC 2198C000 */  addu       $s3, $a2, $zero
    /* BF8 8018FBE0 4C00BFAF */  sw         $ra, 0x4C($sp)
    /* BFC 8018FBE4 4400B7AF */  sw         $s7, 0x44($sp)
    /* C00 8018FBE8 4000B6AF */  sw         $s6, 0x40($sp)
    /* C04 8018FBEC 3C00B5AF */  sw         $s5, 0x3C($sp)
    /* C08 8018FBF0 3800B4AF */  sw         $s4, 0x38($sp)
    /* C0C 8018FBF4 3000B2AF */  sw         $s2, 0x30($sp)
    /* C10 8018FBF8 2C00B1AF */  sw         $s1, 0x2C($sp)
    /* C14 8018FBFC D40A030C */  jal        func_800C2B50
    /* C18 8018FC00 2800B0AF */   sw        $s0, 0x28($sp)
    /* C1C 8018FC04 21B00000 */  addu       $s6, $zero, $zero
    /* C20 8018FC08 6666173C */  lui        $s7, (0x66666667 >> 16)
    /* C24 8018FC0C 6766F736 */  ori        $s7, $s7, (0x66666667 & 0xFFFF)
    /* C28 8018FC10 8B2E153C */  lui        $s5, (0x2E8BA2E9 >> 16)
    /* C2C 8018FC14 E9A2B536 */  ori        $s5, $s5, (0x2E8BA2E9 & 0xFFFF)
    /* C30 8018FC18 21806002 */  addu       $s0, $s3, $zero
    /* C34 8018FC1C 21906002 */  addu       $s2, $s3, $zero
    /* C38 8018FC20 21886002 */  addu       $s1, $s3, $zero
    /* C3C 8018FC24 21A06002 */  addu       $s4, $s3, $zero
    /* C40 8018FC28 1800A2AF */  sw         $v0, 0x18($sp)
  .L8018FC2C:
    /* C44 8018FC2C 1A000282 */  lb         $v0, 0x1A($s0)
    /* C48 8018FC30 00000000 */  nop
    /* C4C 8018FC34 07004010 */  beqz       $v0, .L8018FC54
    /* C50 8018FC38 21184000 */   addu      $v1, $v0, $zero
    /* C54 8018FC3C FFFF6224 */  addiu      $v0, $v1, -0x1
    /* C58 8018FC40 1A0002A2 */  sb         $v0, 0x1A($s0)
    /* C5C 8018FC44 00160200 */  sll        $v0, $v0, 24
    /* C60 8018FC48 02004014 */  bnez       $v0, .L8018FC54
    /* C64 8018FC4C 00000000 */   nop
    /* C68 8018FC50 160000A2 */  sb         $zero, 0x16($s0)
  .L8018FC54:
    /* C6C 8018FC54 16000282 */  lb         $v0, 0x16($s0)
    /* C70 8018FC58 00000000 */  nop
    /* C74 8018FC5C 0B004014 */  bnez       $v0, .L8018FC8C
    /* C78 8018FC60 00000000 */   nop
    /* C7C 8018FC64 1E000392 */  lbu        $v1, 0x1E($s0)
    /* C80 8018FC68 00000000 */  nop
    /* C84 8018FC6C FF006230 */  andi       $v0, $v1, 0xFF
    /* C88 8018FC70 8000422C */  sltiu      $v0, $v0, 0x80
    /* C8C 8018FC74 03004010 */  beqz       $v0, .L8018FC84
    /* C90 8018FC78 04006224 */   addiu     $v0, $v1, 0x4
    /* C94 8018FC7C 233F0608 */  j          .L8018FC8C
    /* C98 8018FC80 1E0002A2 */   sb        $v0, 0x1E($s0)
  .L8018FC84:
    /* C9C 8018FC84 01000824 */  addiu      $t0, $zero, 0x1
    /* CA0 8018FC88 160008A2 */  sb         $t0, 0x16($s0)
  .L8018FC8C:
    /* CA4 8018FC8C 0E000292 */  lbu        $v0, 0xE($s0)
    /* CA8 8018FC90 01000924 */  addiu      $t1, $zero, 0x1
    /* CAC 8018FC94 1C004914 */  bne        $v0, $t1, .L8018FD08
    /* CB0 8018FC98 00000000 */   nop
    /* CB4 8018FC9C 9C008386 */  lh         $v1, 0x9C($s4)
    /* CB8 8018FCA0 02006286 */  lh         $v0, 0x2($s3)
    /* CBC 8018FCA4 00000000 */  nop
    /* CC0 8018FCA8 18006200 */  mult       $v1, $v0
    /* CC4 8018FCAC 3C00428E */  lw         $v0, 0x3C($s2)
    /* CC8 8018FCB0 12400000 */  mflo       $t0
    /* CCC 8018FCB4 03190800 */  sra        $v1, $t0, 4
    /* CD0 8018FCB8 21104300 */  addu       $v0, $v0, $v1
    /* CD4 8018FCBC 3C0042AE */  sw         $v0, 0x3C($s2)
    /* CD8 8018FCC0 9E008386 */  lh         $v1, 0x9E($s4)
    /* CDC 8018FCC4 02006286 */  lh         $v0, 0x2($s3)
    /* CE0 8018FCC8 00000000 */  nop
    /* CE4 8018FCCC 18006200 */  mult       $v1, $v0
    /* CE8 8018FCD0 4000428E */  lw         $v0, 0x40($s2)
    /* CEC 8018FCD4 12480000 */  mflo       $t1
    /* CF0 8018FCD8 03190900 */  sra        $v1, $t1, 4
    /* CF4 8018FCDC 21104300 */  addu       $v0, $v0, $v1
    /* CF8 8018FCE0 400042AE */  sw         $v0, 0x40($s2)
    /* CFC 8018FCE4 A0008386 */  lh         $v1, 0xA0($s4)
    /* D00 8018FCE8 02006286 */  lh         $v0, 0x2($s3)
    /* D04 8018FCEC 00000000 */  nop
    /* D08 8018FCF0 18006200 */  mult       $v1, $v0
    /* D0C 8018FCF4 4400428E */  lw         $v0, 0x44($s2)
    /* D10 8018FCF8 12400000 */  mflo       $t0
    /* D14 8018FCFC 03190800 */  sra        $v1, $t0, 4
    /* D18 8018FD00 21104300 */  addu       $v0, $v0, $v1
    /* D1C 8018FD04 440042AE */  sw         $v0, 0x44($s2)
  .L8018FD08:
    /* D20 8018FD08 2A002296 */  lhu        $v0, 0x2A($s1)
    /* D24 8018FD0C 06006386 */  lh         $v1, 0x6($s3)
    /* D28 8018FD10 00000000 */  nop
    /* D2C 8018FD14 2A104300 */  slt        $v0, $v0, $v1
    /* D30 8018FD18 22004010 */  beqz       $v0, .L8018FDA4
    /* D34 8018FD1C 00000000 */   nop
    /* D38 8018FD20 95C6010C */  jal        func_80071A54
    /* D3C 8018FD24 00000000 */   nop
    /* D40 8018FD28 18005700 */  mult       $v0, $s7
    /* D44 8018FD2C C31F0200 */  sra        $v1, $v0, 31
    /* D48 8018FD30 10480000 */  mfhi       $t1
    /* D4C 8018FD34 43210900 */  sra        $a0, $t1, 5
    /* D50 8018FD38 23208300 */  subu       $a0, $a0, $v1
    /* D54 8018FD3C 80180400 */  sll        $v1, $a0, 2
    /* D58 8018FD40 21186400 */  addu       $v1, $v1, $a0
    /* D5C 8018FD44 00190300 */  sll        $v1, $v1, 4
    /* D60 8018FD48 23104300 */  subu       $v0, $v0, $v1
    /* D64 8018FD4C 2A002396 */  lhu        $v1, 0x2A($s1)
    /* D68 8018FD50 14004224 */  addiu      $v0, $v0, 0x14
    /* D6C 8018FD54 21186200 */  addu       $v1, $v1, $v0
    /* D70 8018FD58 95C6010C */  jal        func_80071A54
    /* D74 8018FD5C 2A0023A6 */   sh        $v1, 0x2A($s1)
    /* D78 8018FD60 18005700 */  mult       $v0, $s7
    /* D7C 8018FD64 C31F0200 */  sra        $v1, $v0, 31
    /* D80 8018FD68 10400000 */  mfhi       $t0
    /* D84 8018FD6C 03210800 */  sra        $a0, $t0, 4
    /* D88 8018FD70 23208300 */  subu       $a0, $a0, $v1
    /* D8C 8018FD74 80180400 */  sll        $v1, $a0, 2
    /* D90 8018FD78 21186400 */  addu       $v1, $v1, $a0
    /* D94 8018FD7C C0180300 */  sll        $v1, $v1, 3
    /* D98 8018FD80 23104300 */  subu       $v0, $v0, $v1
    /* D9C 8018FD84 32002396 */  lhu        $v1, 0x32($s1)
    /* DA0 8018FD88 28004224 */  addiu      $v0, $v0, 0x28
    /* DA4 8018FD8C 21186200 */  addu       $v1, $v1, $v0
    /* DA8 8018FD90 320023A6 */  sh         $v1, 0x32($s1)
    /* DAC 8018FD94 4000428E */  lw         $v0, 0x40($s2)
    /* DB0 8018FD98 F6FF033C */  lui        $v1, (0xFFF60000 >> 16)
    /* DB4 8018FD9C 21104300 */  addu       $v0, $v0, $v1
    /* DB8 8018FDA0 400042AE */  sw         $v0, 0x40($s2)
  .L8018FDA4:
    /* DBC 8018FDA4 0200C487 */  lh         $a0, 0x2($fp)
    /* DC0 8018FDA8 3DDF010C */  jal        func_80077CF4
    /* DC4 8018FDAC 40210400 */   sll       $a0, $a0, 5
    /* DC8 8018FDB0 C3110200 */  sra        $v0, $v0, 7
    /* DCC 8018FDB4 2A002396 */  lhu        $v1, 0x2A($s1)
    /* DD0 8018FDB8 22002496 */  lhu        $a0, 0x22($s1)
    /* DD4 8018FDBC 21186200 */  addu       $v1, $v1, $v0
    /* DD8 8018FDC0 1400842C */  sltiu      $a0, $a0, 0x14
    /* DDC 8018FDC4 07008010 */  beqz       $a0, .L8018FDE4
    /* DE0 8018FDC8 2A0023A6 */   sh        $v1, 0x2A($s1)
    /* DE4 8018FDCC 1E000392 */  lbu        $v1, 0x1E($s0)
    /* DE8 8018FDD0 00000000 */  nop
    /* DEC 8018FDD4 0700622C */  sltiu      $v0, $v1, 0x7
    /* DF0 8018FDD8 02004014 */  bnez       $v0, .L8018FDE4
    /* DF4 8018FDDC FAFF6224 */   addiu     $v0, $v1, -0x6
    /* DF8 8018FDE0 1E0002A2 */  sb         $v0, 0x1E($s0)
  .L8018FDE4:
    /* DFC 8018FDE4 12000292 */  lbu        $v0, 0x12($s0)
    /* E00 8018FDE8 00000000 */  nop
    /* E04 8018FDEC 13004014 */  bnez       $v0, .L8018FE3C
    /* E08 8018FDF0 00000000 */   nop
    /* E0C 8018FDF4 3E004486 */  lh         $a0, 0x3E($s2)
    /* E10 8018FDF8 46004586 */  lh         $a1, 0x46($s2)
    /* E14 8018FDFC 0A80063C */  lui        $a2, %hi(D_8009D248)
    /* E18 8018FE00 48D2C68C */  lw         $a2, %lo(D_8009D248)($a2)
    /* E1C 8018FE04 0A80073C */  lui        $a3, %hi(D_8009D1CC)
    /* E20 8018FE08 CCD1E794 */  lhu        $a3, %lo(D_8009D1CC)($a3)
    /* E24 8018FE0C 00240400 */  sll        $a0, $a0, 16
    /* E28 8018FE10 AC72000C */  jal        func_8001CAB0
    /* E2C 8018FE14 002C0500 */   sll       $a1, $a1, 16
    /* E30 8018FE18 08004014 */  bnez       $v0, .L8018FE3C
    /* E34 8018FE1C 01000224 */   addiu     $v0, $zero, 0x1
    /* E38 8018FE20 120002A2 */  sb         $v0, 0x12($s0)
    /* E3C 8018FE24 0E0000A2 */  sb         $zero, 0xE($s0)
    /* E40 8018FE28 0A006292 */  lbu        $v0, 0xA($s3)
    /* E44 8018FE2C 00000000 */  nop
    /* E48 8018FE30 02004014 */  bnez       $v0, .L8018FE3C
    /* E4C 8018FE34 14000224 */   addiu     $v0, $zero, 0x14
    /* E50 8018FE38 220022A6 */  sh         $v0, 0x22($s1)
  .L8018FE3C:
    /* E54 8018FE3C 22002296 */  lhu        $v0, 0x22($s1)
    /* E58 8018FE40 00000000 */  nop
    /* E5C 8018FE44 FFFF4224 */  addiu      $v0, $v0, -0x1
    /* E60 8018FE48 220022A6 */  sh         $v0, 0x22($s1)
    /* E64 8018FE4C FFFF4230 */  andi       $v0, $v0, 0xFFFF
    /* E68 8018FE50 06004014 */  bnez       $v0, .L8018FE6C
    /* E6C 8018FE54 FFFF0224 */   addiu     $v0, $zero, -0x1
    /* E70 8018FE58 160002A2 */  sb         $v0, 0x16($s0)
    /* E74 8018FE5C 00006296 */  lhu        $v0, 0x0($s3)
    /* E78 8018FE60 00000000 */  nop
    /* E7C 8018FE64 FFFF4224 */  addiu      $v0, $v0, -0x1
    /* E80 8018FE68 000062A6 */  sh         $v0, 0x0($s3)
  .L8018FE6C:
    /* E84 8018FE6C 3E004286 */  lh         $v0, 0x3E($s2)
    /* E88 8018FE70 00000000 */  nop
    /* E8C 8018FE74 1000A2A7 */  sh         $v0, 0x10($sp)
    /* E90 8018FE78 42004286 */  lh         $v0, 0x42($s2)
    /* E94 8018FE7C 00000000 */  nop
    /* E98 8018FE80 1200A2A7 */  sh         $v0, 0x12($sp)
    /* E9C 8018FE84 46004286 */  lh         $v0, 0x46($s2)
    /* EA0 8018FE88 95C6010C */  jal        func_80071A54
    /* EA4 8018FE8C 1400A2A7 */   sh        $v0, 0x14($sp)
    /* EA8 8018FE90 18005500 */  mult       $v0, $s5
    /* EAC 8018FE94 C31F0200 */  sra        $v1, $v0, 31
    /* EB0 8018FE98 10480000 */  mfhi       $t1
    /* EB4 8018FE9C 43200900 */  sra        $a0, $t1, 1
    /* EB8 8018FEA0 23208300 */  subu       $a0, $a0, $v1
    /* EBC 8018FEA4 40180400 */  sll        $v1, $a0, 1
    /* EC0 8018FEA8 21186400 */  addu       $v1, $v1, $a0
    /* EC4 8018FEAC 80180300 */  sll        $v1, $v1, 2
    /* EC8 8018FEB0 23186400 */  subu       $v1, $v1, $a0
    /* ECC 8018FEB4 23104300 */  subu       $v0, $v0, $v1
    /* ED0 8018FEB8 FBFF4224 */  addiu      $v0, $v0, -0x5
    /* ED4 8018FEBC 95C6010C */  jal        func_80071A54
    /* ED8 8018FEC0 0B0062A2 */   sb        $v0, 0xB($s3)
    /* EDC 8018FEC4 18005500 */  mult       $v0, $s5
    /* EE0 8018FEC8 C31F0200 */  sra        $v1, $v0, 31
    /* EE4 8018FECC 10400000 */  mfhi       $t0
    /* EE8 8018FED0 43200800 */  sra        $a0, $t0, 1
    /* EEC 8018FED4 23208300 */  subu       $a0, $a0, $v1
    /* EF0 8018FED8 40180400 */  sll        $v1, $a0, 1
    /* EF4 8018FEDC 21186400 */  addu       $v1, $v1, $a0
    /* EF8 8018FEE0 80180300 */  sll        $v1, $v1, 2
    /* EFC 8018FEE4 23186400 */  subu       $v1, $v1, $a0
    /* F00 8018FEE8 23104300 */  subu       $v0, $v0, $v1
    /* F04 8018FEEC FBFF4224 */  addiu      $v0, $v0, -0x5
    /* F08 8018FEF0 95C6010C */  jal        func_80071A54
    /* F0C 8018FEF4 0C0062A2 */   sb        $v0, 0xC($s3)
    /* F10 8018FEF8 18005500 */  mult       $v0, $s5
    /* F14 8018FEFC C31F0200 */  sra        $v1, $v0, 31
    /* F18 8018FF00 10480000 */  mfhi       $t1
    /* F1C 8018FF04 43200900 */  sra        $a0, $t1, 1
    /* F20 8018FF08 23208300 */  subu       $a0, $a0, $v1
    /* F24 8018FF0C 40180400 */  sll        $v1, $a0, 1
    /* F28 8018FF10 21186400 */  addu       $v1, $v1, $a0
    /* F2C 8018FF14 80180300 */  sll        $v1, $v1, 2
    /* F30 8018FF18 23186400 */  subu       $v1, $v1, $a0
    /* F34 8018FF1C 23104300 */  subu       $v0, $v0, $v1
    /* F38 8018FF20 FBFF4224 */  addiu      $v0, $v0, -0x5
    /* F3C 8018FF24 0D0062A2 */  sb         $v0, 0xD($s3)
    /* F40 8018FF28 2A002596 */  lhu        $a1, 0x2A($s1)
    /* F44 8018FF2C 1000A427 */  addiu      $a0, $sp, 0x10
    /* F48 8018FF30 E41A030C */  jal        func_800C6B90
    /* F4C 8018FF34 02290500 */   srl       $a1, $a1, 4
    /* F50 8018FF38 0D004010 */  beqz       $v0, .L8018FF70
    /* F54 8018FF3C 00000000 */   nop
    /* F58 8018FF40 12000292 */  lbu        $v0, 0x12($s0)
    /* F5C 8018FF44 00000000 */  nop
    /* F60 8018FF48 08004014 */  bnez       $v0, .L8018FF6C
    /* F64 8018FF4C 01000224 */   addiu     $v0, $zero, 0x1
    /* F68 8018FF50 01000924 */  addiu      $t1, $zero, 0x1
    /* F6C 8018FF54 1800A88F */  lw         $t0, 0x18($sp)
    /* F70 8018FF58 14000224 */  addiu      $v0, $zero, 0x14
    /* F74 8018FF5C 280009A5 */  sh         $t1, 0x28($t0)
    /* F78 8018FF60 220022A6 */  sh         $v0, 0x22($s1)
    /* F7C 8018FF64 0E0000A2 */  sb         $zero, 0xE($s0)
    /* F80 8018FF68 01000224 */  addiu      $v0, $zero, 0x1
  .L8018FF6C:
    /* F84 8018FF6C 120002A2 */  sb         $v0, 0x12($s0)
  .L8018FF70:
    /* F88 8018FF70 01001026 */  addiu      $s0, $s0, 0x1
    /* F8C 8018FF74 10005226 */  addiu      $s2, $s2, 0x10
    /* F90 8018FF78 02003126 */  addiu      $s1, $s1, 0x2
    /* F94 8018FF7C 0100D626 */  addiu      $s6, $s6, 0x1
    /* F98 8018FF80 0300C22E */  sltiu      $v0, $s6, 0x3
    /* F9C 8018FF84 29FF4014 */  bnez       $v0, .L8018FC2C
    /* FA0 8018FF88 08009426 */   addiu     $s4, $s4, 0x8
    /* FA4 8018FF8C 02006296 */  lhu        $v0, 0x2($s3)
    /* FA8 8018FF90 04006396 */  lhu        $v1, 0x4($s3)
    /* FAC 8018FF94 00000000 */  nop
    /* FB0 8018FF98 21104300 */  addu       $v0, $v0, $v1
    /* FB4 8018FF9C 020062A6 */  sh         $v0, 0x2($s3)
    /* FB8 8018FFA0 00140200 */  sll        $v0, $v0, 16
    /* FBC 8018FFA4 02004104 */  bgez       $v0, .L8018FFB0
    /* FC0 8018FFA8 00000000 */   nop
    /* FC4 8018FFAC 020060A6 */  sh         $zero, 0x2($s3)
  .L8018FFB0:
    /* FC8 8018FFB0 00006286 */  lh         $v0, 0x0($s3)
    /* FCC 8018FFB4 00000000 */  nop
    /* FD0 8018FFB8 02004014 */  bnez       $v0, .L8018FFC4
    /* FD4 8018FFBC 02000224 */   addiu     $v0, $zero, 0x2
    /* FD8 8018FFC0 0100C2A3 */  sb         $v0, 0x1($fp)
  .L8018FFC4:
    /* FDC 8018FFC4 4C00BF8F */  lw         $ra, 0x4C($sp)
    /* FE0 8018FFC8 4800BE8F */  lw         $fp, 0x48($sp)
    /* FE4 8018FFCC 4400B78F */  lw         $s7, 0x44($sp)
    /* FE8 8018FFD0 4000B68F */  lw         $s6, 0x40($sp)
    /* FEC 8018FFD4 3C00B58F */  lw         $s5, 0x3C($sp)
    /* FF0 8018FFD8 3800B48F */  lw         $s4, 0x38($sp)
    /* FF4 8018FFDC 3400B38F */  lw         $s3, 0x34($sp)
    /* FF8 8018FFE0 3000B28F */  lw         $s2, 0x30($sp)
    /* FFC 8018FFE4 2C00B18F */  lw         $s1, 0x2C($sp)
    /* 1000 8018FFE8 2800B08F */  lw         $s0, 0x28($sp)
    /* 1004 8018FFEC 5000BD27 */  addiu      $sp, $sp, 0x50
    /* 1008 8018FFF0 0800E003 */  jr         $ra
    /* 100C 8018FFF4 00000000 */   nop
endlabel func_8018FBCC
