#include "common.h"

#define ROOMEFFECT_DROP_FIELD_DRAW_FUNC RoomEffect_DropFieldDraw_80190E98
#define ROOMEFFECT_DROP_FIELD_DRAW_SPIN D_8018F004
#define ROOMEFFECT_DROP_FIELD_DRAW_SHADOW_SPIN D_8018EFF4
#define ROOMEFFECT_DROP_FIELD_DRAW_SHADOW_SCALE D_8018F03C
#define ROOMEFFECT_DROP_FIELD_DRAW_SPRITE D_80192EB0
#include "../room_lib/RoomEffect_DropFieldDraw.inc"
