#define ROOMLIB_UPDATE_STAGED_MOTION_FUNC func_801907FC
#define ROOMLIB_STAGED_MOTION_SPAWN_CALLBACK D_801928F0
#define ROOMLIB_STAGED_MOTION_SPAWN_DATA D_80192848
#include "../room_lib/RoomLib_UpdateStagedMotion.inc"
