/* CC1_FLAGS: -G8 -g3 */
/* MASPSX_FLAGS: -G8 --use-comm-section */
/* Function body emitted as asm() (PSYQ GCC 2.7.2 register
 * allocation / scheduling diverges from the ROM pervasively).
 * Wrapped via maspsx's INCLUDE_ASM hack so the body is passed
 * through verbatim; bare global loads gp-rel via the .extern size
 * hints + `as -G8`. See tools/maspsx/PE1_IMPROVEMENTS.md. */
void __maspsx_include_asm_hack_Draw_PrintCenteredTextInWidth(void);
void __maspsx_include_asm_hack_Draw_PrintCenteredTextInWidth(void) {
	__asm__(
		"	.extern	g_TextCursorStackPtr,1 # maspsx-keep\n"
		"	.extern	g_TextCursorX,1 # maspsx-keep\n"
		"	.extern	g_TextCursorY,1 # maspsx-keep\n"
		"	.extern	g_TextRenderMode,1 # maspsx-keep\n"
		"	.extern	g_DrawGlyphAdvance,1 # maspsx-keep\n"
		"	.set	noreorder # maspsx-keep\n"
		"	.set	nomacro # maspsx-keep\n"
		"	.globl	Draw_PrintCenteredTextInWidth # maspsx-keep\n"
		"Draw_PrintCenteredTextInWidth: # maspsx-keep\n"
		"	addiu	$sp,$sp,-0x28 # maspsx-keep\n"
		"	sw	$s2,0x18($sp) # maspsx-keep\n"
		"	addu	$s2,$a0,$zero # maspsx-keep\n"
		"	sw	$s3,0x1C($sp) # maspsx-keep\n"
		"	addu	$s3,$a1,$zero # maspsx-keep\n"
		"	lw	$a1,g_TextCursorStackPtr # maspsx-keep\n"
		"	lui	$v0,%hi(g_TextCursorStackTop) # maspsx-keep\n"
		"	addiu	$v0,$v0,%lo(g_TextCursorStackTop) # maspsx-keep\n"
		"	sw	$ra,0x20($sp) # maspsx-keep\n"
		"	sw	$s1,0x14($sp) # maspsx-keep\n"
		"	sltu	$v0,$a1,$v0 # maspsx-keep\n"
		"	beqz	$v0,.L8005F3A4 # maspsx-keep\n"
		"	sw	$s0,0x10($sp) # maspsx-keep\n"
		"	lw	$v0,g_TextCursorX # maspsx-keep\n"
		"	lw	$a0,g_TextCursorY # maspsx-keep\n"
		"	addiu	$v1,$a1,0x8 # maspsx-keep\n"
		"	sw	$v1,g_TextCursorStackPtr # maspsx-keep\n"
		"	sw	$v0,0x0($a1) # maspsx-keep\n"
		"	j	.L8005F3AC # maspsx-keep\n"
		"	sw	$a0,0x4($a1) # maspsx-keep\n"
		".L8005F3A4: # maspsx-keep\n"
		"	jal	BoundsCheck_AssertStub # maspsx-keep\n"
		"	addiu	$a0,$zero,0x2 # maspsx-keep\n"
		".L8005F3AC: # maspsx-keep\n"
		"	addu	$s0,$s2,$zero # maspsx-keep\n"
		"	lbu	$v1,0x0($s2) # maspsx-keep\n"
		"	addiu	$v0,$zero,0xFF # maspsx-keep\n"
		"	beq	$v1,$v0,.L8005F468 # maspsx-keep\n"
		"	addu	$s1,$zero,$zero # maspsx-keep\n"
		".L8005F3C0: # maspsx-keep\n"
		"	lbu	$a0,0x0($s0) # maspsx-keep\n"
		"	addiu	$s0,$s0,0x1 # maspsx-keep\n"
		"	lw	$v0,g_TextRenderMode # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	beqz	$v0,.L8005F3E4 # maspsx-keep\n"
		"	andi	$v1,$a0,0xFF # maspsx-keep\n"
		"	sll	$v0,$v0,8 # maspsx-keep\n"
		"	addu	$v1,$v1,$v0 # maspsx-keep\n"
		"	sw	$zero,g_TextRenderMode # maspsx-keep\n"
		".L8005F3E4: # maspsx-keep\n"
		"	andi	$a0,$a0,0xFF # maspsx-keep\n"
		"	sltiu	$v0,$a0,0xFA # maspsx-keep\n"
		"	bnez	$v0,.L8005F3FC # maspsx-keep\n"
		"	addiu	$v0,$a0,-0xFA # maspsx-keep\n"
		"	sw	$v0,g_TextRenderMode # maspsx-keep\n"
		"	addiu	$v1,$zero,-0x1 # maspsx-keep\n"
		".L8005F3FC: # maspsx-keep\n"
		"	addu	$a0,$v1,$zero # maspsx-keep\n"
		"	bltz	$a0,.L8005F454 # maspsx-keep\n"
		"	slti	$v0,$a0,0xA # maspsx-keep\n"
		"	bnez	$v0,.L8005F41C # maspsx-keep\n"
		"	addu	$v1,$zero,$zero # maspsx-keep\n"
		"	addiu	$v0,$zero,0xF # maspsx-keep\n"
		"	bne	$a0,$v0,.L8005F424 # maspsx-keep\n"
		"	addiu	$v0,$v1,0x1 # maspsx-keep\n"
		".L8005F41C: # maspsx-keep\n"
		"	addiu	$v1,$zero,0x1 # maspsx-keep\n"
		"	addiu	$v0,$v1,0x1 # maspsx-keep\n"
		".L8005F424: # maspsx-keep\n"
		"	sw	$v0,g_DrawGlyphAdvance # maspsx-keep\n"
		"	slti	$v0,$a0,0x100 # maspsx-keep\n"
		"	bnez	$v0,.L8005F438 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	addiu	$a0,$a0,-0x13 # maspsx-keep\n"
		".L8005F438: # maspsx-keep\n"
		"	jal	Draw_LookupGlyphMetrics # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	sra	$v0,$v0,4 # maspsx-keep\n"
		"	lw	$v1,g_DrawGlyphAdvance # maspsx-keep\n"
		"	andi	$v0,$v0,0xF # maspsx-keep\n"
		"	addu	$v0,$v0,$v1 # maspsx-keep\n"
		"	addu	$s1,$s1,$v0 # maspsx-keep\n"
		".L8005F454: # maspsx-keep\n"
		"	lbu	$v1,0x0($s0) # maspsx-keep\n"
		"	addiu	$v0,$zero,0xFF # maspsx-keep\n"
		"	bne	$v1,$v0,.L8005F3C0 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	addu	$s0,$s2,$zero # maspsx-keep\n"
		".L8005F468: # maspsx-keep\n"
		"	addiu	$v0,$s1,0x4 # maspsx-keep\n"
		"	subu	$v0,$s3,$v0 # maspsx-keep\n"
		"	sra	$v0,$v0,1 # maspsx-keep\n"
		"	lw	$v1,g_TextCursorX # maspsx-keep\n"
		"	lw	$a1,g_TextCursorY # maspsx-keep\n"
		"	addu	$v1,$v1,$v0 # maspsx-keep\n"
		"	sw	$v1,g_TextCursorX # maspsx-keep\n"
		"	sw	$a1,g_TextCursorY # maspsx-keep\n"
		"	beqz	$s0,.L8005F534 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lw	$a0,g_TextCursorStackPtr # maspsx-keep\n"
		"	lui	$v0,%hi(g_TextCursorStackTop) # maspsx-keep\n"
		"	addiu	$v0,$v0,%lo(g_TextCursorStackTop) # maspsx-keep\n"
		"	sltu	$v0,$a0,$v0 # maspsx-keep\n"
		"	beqz	$v0,.L8005F4BC # maspsx-keep\n"
		"	addiu	$v0,$a0,0x8 # maspsx-keep\n"
		"	sw	$v1,0x0($a0) # maspsx-keep\n"
		"	sw	$a1,0x4($a0) # maspsx-keep\n"
		"	sw	$v0,g_TextCursorStackPtr # maspsx-keep\n"
		"	j	.L8005F4C4 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L8005F4BC: # maspsx-keep\n"
		"	jal	BoundsCheck_AssertStub # maspsx-keep\n"
		"	addiu	$a0,$zero,0x2 # maspsx-keep\n"
		".L8005F4C4: # maspsx-keep\n"
		"	lbu	$a0,0x0($s0) # maspsx-keep\n"
		"	addiu	$v0,$zero,0xFF # maspsx-keep\n"
		"	andi	$v1,$a0,0xFF # maspsx-keep\n"
		"	beq	$v1,$v0,.L8005F4F4 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	addiu	$s1,$zero,0xFF # maspsx-keep\n"
		".L8005F4DC: # maspsx-keep\n"
		"	jal	Draw_AllocTexturedQuad # maspsx-keep\n"
		"	addiu	$s0,$s0,0x1 # maspsx-keep\n"
		"	lbu	$a0,0x0($s0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	bne	$a0,$s1,.L8005F4DC # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L8005F4F4: # maspsx-keep\n"
		"	lw	$v1,g_TextCursorStackPtr # maspsx-keep\n"
		"	lui	$v0,%hi(g_TextCursorStackBottom) # maspsx-keep\n"
		"	addiu	$v0,$v0,%lo(g_TextCursorStackBottom) # maspsx-keep\n"
		"	sltu	$v0,$v0,$v1 # maspsx-keep\n"
		"	beqz	$v0,.L8005F52C # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lw	$v0,-0x8($v1) # maspsx-keep\n"
		"	lw	$a0,-0x4($v1) # maspsx-keep\n"
		"	addiu	$v1,$v1,-0x8 # maspsx-keep\n"
		"	sw	$v1,g_TextCursorStackPtr # maspsx-keep\n"
		"	sw	$v0,g_TextCursorX # maspsx-keep\n"
		"	sw	$a0,g_TextCursorY # maspsx-keep\n"
		"	j	.L8005F534 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L8005F52C: # maspsx-keep\n"
		"	jal	BoundsCheck_AssertStub # maspsx-keep\n"
		"	addiu	$a0,$zero,0x3 # maspsx-keep\n"
		".L8005F534: # maspsx-keep\n"
		"	lw	$v1,g_TextCursorStackPtr # maspsx-keep\n"
		"	lui	$v0,%hi(g_TextCursorStackBottom) # maspsx-keep\n"
		"	addiu	$v0,$v0,%lo(g_TextCursorStackBottom) # maspsx-keep\n"
		"	sltu	$v0,$v0,$v1 # maspsx-keep\n"
		"	beqz	$v0,.L8005F56C # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lw	$v0,-0x8($v1) # maspsx-keep\n"
		"	lw	$a0,-0x4($v1) # maspsx-keep\n"
		"	addiu	$v1,$v1,-0x8 # maspsx-keep\n"
		"	sw	$v1,g_TextCursorStackPtr # maspsx-keep\n"
		"	sw	$v0,g_TextCursorX # maspsx-keep\n"
		"	sw	$a0,g_TextCursorY # maspsx-keep\n"
		"	j	.L8005F574 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L8005F56C: # maspsx-keep\n"
		"	jal	BoundsCheck_AssertStub # maspsx-keep\n"
		"	addiu	$a0,$zero,0x3 # maspsx-keep\n"
		".L8005F574: # maspsx-keep\n"
		"	lw	$ra,0x20($sp) # maspsx-keep\n"
		"	lw	$s3,0x1C($sp) # maspsx-keep\n"
		"	lw	$s2,0x18($sp) # maspsx-keep\n"
		"	lw	$s1,0x14($sp) # maspsx-keep\n"
		"	lw	$s0,0x10($sp) # maspsx-keep\n"
		"	addiu	$sp,$sp,0x28 # maspsx-keep\n"
		"	jr	$ra # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	.set	macro # maspsx-keep\n"
		"	.set	reorder # maspsx-keep\n"
	);
}
