#include "common.h"
#include "pe1/room_fx.h"

#define ROOMLIB_DRAW_THREE_PARTICLES_FUNC func_8018FA08
#define ROOMLIB_DRAW_THREE_PARTICLES_TABLE D_80194240
#define ROOMLIB_DRAW_THREE_PARTICLES_PACKET D_801943A0
#define ROOMLIB_DRAW_THREE_PARTICLES_PRIMARY_ALPHA D_801943AA
#define ROOMLIB_DRAW_THREE_PARTICLES_FLOOR_ALPHA D_8019439A
#define ROOMLIB_DRAW_THREE_PARTICLES_FLOOR_HEIGHT D_800942EC
#include "../room_lib/RoomLib_DrawThreeTransformParticles.inc"
