#define ROOMLIB_UPDATE_TIMED_RENDER_NAME func_80193CE4
#define ROOMLIB_UPDATE_TIMED_RENDER_SEED D_8018F1D4
#define ROOMLIB_UPDATE_TIMED_RENDER_TABLE D_80194334
#include "../room_lib/RoomLib_UpdateTimedRender.inc"
