#include "common.h"
#include "pe1/gte.h"

#define ROOMEFFECT_MODEL_BURST_FUNC func_8019368C
#define ROOMEFFECT_MODEL_BURST_CALLBACK func_801933EC
#define ROOMEFFECT_MODEL_BURST_ROTATION D_8018F1D4
#define ROOMEFFECT_MODEL_BURST_SHADE D_8018F1E0
#define ROOMEFFECT_MODEL_BURST_COLOR_TABLE D_801956F8
#define ROOMEFFECT_MODEL_BURST_ASSET D_801959B4
#define ROOMEFFECT_MODEL_BURST_LAYER D_801959B8
#define ROOMEFFECT_MODEL_BURST_ANCHOR D_801959AC
#define ROOMEFFECT_MODEL_BURST_SLOT 7
#include "../room_lib/RoomEffect_ModelBurstController.inc"
