/* MASPSX_FLAGS: --expand-div */
#define ROOMEFFECT_SEEKING_TRAIL_FUNC func_80193D7C
#define ROOMEFFECT_SEEKING_TRAIL_COLOR_A D_8018F1CC
#define ROOMEFFECT_SEEKING_TRAIL_COLOR_B D_8018F1D0
#define ROOMEFFECT_SEEKING_TRAIL_ROTATION D_8018F1D4
#define ROOMEFFECT_SEEKING_TRAIL_HISTORY D_801959D8
#define ROOMEFFECT_SEEKING_TRAIL_SCATTER
#define ROOMEFFECT_SEEKING_TRAIL_ANCHOR 5
#define ROOMEFFECT_SEEKING_TRAIL_RADIUS 0x64
#define ROOMEFFECT_SEEKING_TRAIL_WIDTH 0x6E
#define ROOMEFFECT_SEEKING_TRAIL_PULSE 2
#include "../room_lib/RoomEffect_SeekingTrailController.inc"
