#include "pe1/gte_types.h"

/* Packed-word scaling preserves the original full-word padding overwrite.
 * The empty x -> l constraint binds the low word of the C unsigned product
 * to LO. It keeps MULTU instead of GCC's low-only MULT and emits no opcode.
 * Register pins and sequencing barriers are counted in crutch debt. */
GteMatrix *Gte_ScaleMatrix(GteMatrix *m, const GteVector *scale) {
    register s32 sx asm("$11");
    register s32 sy asm("$12");
    register s32 sz asm("$13");
    register u32 packed asm("$8");
    register s32 lo asm("$9");
    register s32 hi asm("$10");
    unsigned long long product;
    u32 low;
    register u32 *words asm("$4") = (u32 *)m;
    sx = scale->x;
    sy = scale->y;
    sz = scale->z;
    asm volatile("" : "=r"(sx), "=r"(sy), "=r"(sz) : "0"(sx), "1"(sy), "2"(sz));
    packed = words[0];
    lo = packed & 0xffff;
    asm volatile("" : "=r"(lo) : "0"(lo));
    lo = (u32)lo << 16;
    asm volatile("" : "=r"(lo) : "0"(lo));
    lo >>= 16;
    product = (unsigned long long)(u32)lo * (u32)sx;
    asm volatile("" : "=l"(low) : "x"(product));
    lo = low;
    asm volatile("" : "=r"(lo) : "0"(lo));
    lo >>= 12;
    lo &= 0xffff;
    asm volatile("" : "=r"(lo) : "0"(lo));
    hi = (s32)packed >> 16;
    product = (unsigned long long)(u32)hi * (u32)sy;
    asm volatile("" : "=l"(low) : "x"(product));
    hi = low;
    asm volatile("" : "=r"(hi) : "0"(hi));
    hi >>= 12;
    asm volatile("" : "=r"(hi) : "0"(hi));
    hi = (u32)hi << 16;
    lo |= hi;
    words[0] = lo;
    packed = words[1];
    lo = packed & 0xffff;
    asm volatile("" : "=r"(lo) : "0"(lo));
    lo = (u32)lo << 16;
    asm volatile("" : "=r"(lo) : "0"(lo));
    lo >>= 16;
    product = (unsigned long long)(u32)lo * (u32)sz;
    asm volatile("" : "=l"(low) : "x"(product));
    lo = low;
    asm volatile("" : "=r"(lo) : "0"(lo));
    lo >>= 12;
    lo &= 0xffff;
    asm volatile("" : "=r"(lo) : "0"(lo));
    hi = (s32)packed >> 16;
    product = (unsigned long long)(u32)hi * (u32)sx;
    asm volatile("" : "=l"(low) : "x"(product));
    hi = low;
    asm volatile("" : "=r"(hi) : "0"(hi));
    hi >>= 12;
    asm volatile("" : "=r"(hi) : "0"(hi));
    hi = (u32)hi << 16;
    lo |= hi;
    words[1] = lo;
    asm volatile("" : : : "memory");
    packed = words[2];
    lo = packed & 0xffff;
    asm volatile("" : "=r"(lo) : "0"(lo));
    lo = (u32)lo << 16;
    asm volatile("" : "=r"(lo) : "0"(lo));
    lo >>= 16;
    product = (unsigned long long)(u32)lo * (u32)sy;
    asm volatile("" : "=l"(low) : "x"(product));
    lo = low;
    asm volatile("" : "=r"(lo) : "0"(lo));
    lo >>= 12;
    lo &= 0xffff;
    asm volatile("" : "=r"(lo) : "0"(lo));
    hi = (s32)packed >> 16;
    product = (unsigned long long)(u32)hi * (u32)sz;
    asm volatile("" : "=l"(low) : "x"(product));
    hi = low;
    asm volatile("" : "=r"(hi) : "0"(hi));
    hi >>= 12;
    asm volatile("" : "=r"(hi) : "0"(hi));
    hi = (u32)hi << 16;
    lo |= hi;
    words[2] = lo;
    asm volatile("" : : : "memory");
    packed = words[3];
    lo = packed & 0xffff;
    asm volatile("" : "=r"(lo) : "0"(lo));
    lo = (u32)lo << 16;
    asm volatile("" : "=r"(lo) : "0"(lo));
    lo >>= 16;
    product = (unsigned long long)(u32)lo * (u32)sx;
    asm volatile("" : "=l"(low) : "x"(product));
    lo = low;
    asm volatile("" : "=r"(lo) : "0"(lo));
    lo >>= 12;
    lo &= 0xffff;
    asm volatile("" : "=r"(lo) : "0"(lo));
    hi = (s32)packed >> 16;
    product = (unsigned long long)(u32)hi * (u32)sy;
    asm volatile("" : "=l"(low) : "x"(product));
    hi = low;
    asm volatile("" : "=r"(hi) : "0"(hi));
    hi >>= 12;
    asm volatile("" : "=r"(hi) : "0"(hi));
    hi = (u32)hi << 16;
    lo |= hi;
    words[3] = lo;
    asm volatile("" : : : "memory");
    packed = words[4];
    asm volatile("" : "=r"(packed) : "0"(packed));
    lo = packed & 0xffff;
    asm volatile("" : "=r"(lo) : "0"(lo));
    lo = (u32)lo << 16;
    asm volatile("" : "=r"(lo) : "0"(lo));
    lo >>= 16;
    product = (unsigned long long)(u32)lo * (u32)sz;
    asm volatile("" : "=l"(low) : "x"(product));
    lo = low;
    asm volatile("" : "=r"(lo) : "0"(lo));
    lo >>= 12;
    words[4] = lo;
    asm volatile("" : : : "memory");
    return (GteMatrix *)words;
}
