/* MASPSX_FLAGS: --expand-div */
#define ROOMEFFECT_LINE_BURST_FUNC func_8018F3A4
#define ROOMEFFECT_LINE_BURST_CALLBACK func_8018F008
#define ROOMEFFECT_LINE_BURST_TEMPLATE D_8018EFF8
#define ROOMEFFECT_LINE_BURST_ROTATION D_8018F000
#include "../room_lib/RoomEffect_LineBurstController.inc"
