.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.4 */

nonmatching Scene_UpdateEntityFacingFromPad, 0x17C

glabel Scene_UpdateEntityFacingFromPad
    /* 61F54 80071754 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 61F58 80071758 1000B0AF */  sw         $s0, 0x10($sp)
    /* 61F5C 8007175C 21808000 */  addu       $s0, $a0, $zero
    /* 61F60 80071760 1400BFAF */  sw         $ra, 0x14($sp)
    /* 61F64 80071764 E169000C */  jal        Entity_SetAction
    /* 61F68 80071768 11000524 */   addiu     $a1, $zero, 0x11
    /* 61F6C 8007176C 0C80023C */  lui        $v0, %hi(g_AnalogStickState)
    /* 61F70 80071770 A0E94294 */  lhu        $v0, %lo(g_AnalogStickState)($v0)
    /* 61F74 80071774 00700324 */  addiu      $v1, $zero, 0x7000
    /* 61F78 80071778 00F04230 */  andi       $v0, $v0, 0xF000
    /* 61F7C 8007177C 10004314 */  bne        $v0, $v1, .L800717C0
    /* 61F80 80071780 00000000 */   nop
    /* 61F84 80071784 0C80043C */  lui        $a0, %hi(D_800BE9A7)
    /* 61F88 80071788 A7E98490 */  lbu        $a0, %lo(D_800BE9A7)($a0)
    /* 61F8C 8007178C 0C80053C */  lui        $a1, %hi(D_800BE9A6)
    /* 61F90 80071790 A6E9A590 */  lbu        $a1, %lo(D_800BE9A6)($a1)
    /* 61F94 80071794 80FF8424 */  addiu      $a0, $a0, -0x80
    /* 61F98 80071798 EDE7010C */  jal        Gte_Atan2
    /* 61F9C 8007179C 80FFA524 */   addiu     $a1, $a1, -0x80
    /* 61FA0 800717A0 00FC4324 */  addiu      $v1, $v0, -0x400
    /* 61FA4 800717A4 02006104 */  bgez       $v1, .L800717B0
    /* 61FA8 800717A8 00000000 */   nop
    /* 61FAC 800717AC 00106324 */  addiu      $v1, $v1, 0x1000
  .L800717B0:
    /* 61FB0 800717B0 0C80023C */  lui        $v0, %hi(g_CameraBaseAngleY)
    /* 61FB4 800717B4 22D04294 */  lhu        $v0, %lo(g_CameraBaseAngleY)($v0)
    /* 61FB8 800717B8 10C60108 */  j          .L80071840
    /* 61FBC 800717BC 00000000 */   nop
  .L800717C0:
    /* 61FC0 800717C0 0A80033C */  lui        $v1, %hi(g_FieldPadBits)
    /* 61FC4 800717C4 6CD2638C */  lw         $v1, %lo(g_FieldPadBits)($v1)
    /* 61FC8 800717C8 00000000 */  nop
    /* 61FCC 800717CC 08006230 */  andi       $v0, $v1, 0x8
    /* 61FD0 800717D0 08004010 */  beqz       $v0, .L800717F4
    /* 61FD4 800717D4 40006230 */   andi      $v0, $v1, 0x40
    /* 61FD8 800717D8 15004014 */  bnez       $v0, .L80071830
    /* 61FDC 800717DC 00060224 */   addiu     $v0, $zero, 0x600
    /* 61FE0 800717E0 10006230 */  andi       $v0, $v1, 0x10
    /* 61FE4 800717E4 12004014 */  bnez       $v0, .L80071830
    /* 61FE8 800717E8 000A0224 */   addiu     $v0, $zero, 0xA00
    /* 61FEC 800717EC 0CC60108 */  j          .L80071830
    /* 61FF0 800717F0 00080224 */   addiu     $v0, $zero, 0x800
  .L800717F4:
    /* 61FF4 800717F4 20006230 */  andi       $v0, $v1, 0x20
    /* 61FF8 800717F8 08004010 */  beqz       $v0, .L8007181C
    /* 61FFC 800717FC 40006230 */   andi      $v0, $v1, 0x40
    /* 62000 80071800 0B004014 */  bnez       $v0, .L80071830
    /* 62004 80071804 00020224 */   addiu     $v0, $zero, 0x200
    /* 62008 80071808 10006230 */  andi       $v0, $v1, 0x10
    /* 6200C 8007180C 08004014 */  bnez       $v0, .L80071830
    /* 62010 80071810 000E0224 */   addiu     $v0, $zero, 0xE00
    /* 62014 80071814 0DC60108 */  j          .L80071834
    /* 62018 80071818 3A0000A6 */   sh        $zero, 0x3A($s0)
  .L8007181C:
    /* 6201C 8007181C 04004014 */  bnez       $v0, .L80071830
    /* 62020 80071820 00040224 */   addiu     $v0, $zero, 0x400
    /* 62024 80071824 10006230 */  andi       $v0, $v1, 0x10
    /* 62028 80071828 02004010 */  beqz       $v0, .L80071834
    /* 6202C 8007182C 000C0224 */   addiu     $v0, $zero, 0xC00
  .L80071830:
    /* 62030 80071830 3A0002A6 */  sh         $v0, 0x3A($s0)
  .L80071834:
    /* 62034 80071834 3A000386 */  lh         $v1, 0x3A($s0)
    /* 62038 80071838 0C80023C */  lui        $v0, %hi(g_CameraBaseAngleX)
    /* 6203C 8007183C 20D04294 */  lhu        $v0, %lo(g_CameraBaseAngleX)($v0)
  .L80071840:
    /* 62040 80071840 0A80043C */  lui        $a0, %hi(g_PlayerEntity)
    /* 62044 80071844 54D2848C */  lw         $a0, %lo(g_PlayerEntity)($a0)
    /* 62048 80071848 00000000 */  nop
    /* 6204C 8007184C 0E008010 */  beqz       $a0, .L80071888
    /* 62050 80071850 21186200 */   addu      $v1, $v1, $v0
    /* 62054 80071854 0A80023C */  lui        $v0, %hi(g_FieldMoveLock)
    /* 62058 80071858 E8D2428C */  lw         $v0, %lo(g_FieldMoveLock)($v0)
    /* 6205C 8007185C 00000000 */  nop
    /* 62060 80071860 10004230 */  andi       $v0, $v0, 0x10
    /* 62064 80071864 08004010 */  beqz       $v0, .L80071888
    /* 62068 80071868 00000000 */   nop
    /* 6206C 8007186C 0000828C */  lw         $v0, 0x0($a0)
    /* 62070 80071870 00000000 */  nop
    /* 62074 80071874 4C00428C */  lw         $v0, 0x4C($v0)
    /* 62078 80071878 00086324 */  addiu      $v1, $v1, 0x800
    /* 6207C 8007187C C2110200 */  srl        $v0, $v0, 7
    /* 62080 80071880 000C4230 */  andi       $v0, $v0, 0xC00
    /* 62084 80071884 21186200 */  addu       $v1, $v1, $v0
  .L80071888:
    /* 62088 80071888 FF0F6330 */  andi       $v1, $v1, 0xFFF
    /* 6208C 8007188C 3A0003A6 */  sh         $v1, 0x3A($s0)
    /* 62090 80071890 0A80023C */  lui        $v0, %hi(g_FieldMoveLock)
    /* 62094 80071894 E8D2428C */  lw         $v0, %lo(g_FieldMoveLock)($v0)
    /* 62098 80071898 00000000 */  nop
    /* 6209C 8007189C 10004230 */  andi       $v0, $v0, 0x10
    /* 620A0 800718A0 06004010 */  beqz       $v0, .L800718BC
    /* 620A4 800718A4 00100224 */   addiu     $v0, $zero, 0x1000
    /* 620A8 800718A8 3A000396 */  lhu        $v1, 0x3A($s0)
    /* 620AC 800718AC 00000000 */  nop
    /* 620B0 800718B0 23104300 */  subu       $v0, $v0, $v1
    /* 620B4 800718B4 FF0F4230 */  andi       $v0, $v0, 0xFFF
    /* 620B8 800718B8 3A0002A6 */  sh         $v0, 0x3A($s0)
  .L800718BC:
    /* 620BC 800718BC 1400BF8F */  lw         $ra, 0x14($sp)
    /* 620C0 800718C0 1000B08F */  lw         $s0, 0x10($sp)
    /* 620C4 800718C4 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 620C8 800718C8 0800E003 */  jr         $ra
    /* 620CC 800718CC 00000000 */   nop
endlabel Scene_UpdateEntityFacingFromPad
