name: fx_field.bin
sha1: 6fd4df73085d5f93a32451a39e81ea673328bf77
options:
  basename: fx_field
  target_path: original/USA/overlays/fx_field.bin
  base_path: ../../..
  platform: psx
  compiler: GCC
  asm_path: asm/USA/overlays/fx_field
  src_path: src/overlays/fx_field
  build_path: build/USA/overlays/fx_field
  ld_script_path: linkers/USA/overlays/fx_field.ld
  undefined_funcs_auto_path: linkers/USA/overlays/undefined_funcs_auto.fx_field.txt
  undefined_syms_auto_path: linkers/USA/overlays/undefined_syms_auto.fx_field.txt
  find_file_boundaries: True
  disassemble_all: True
  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel
  generate_asm_macros_files: False
  section_order: [".rodata", ".text", ".data", ".sdata", ".sbss", ".bss"]
  subalign: 4
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: fx_field
    type: code
    start: 0x0
    vram: 0x8018EFF0
    align: 4
    subalign: 4
    bss_size: 0x0
    subsegments:
      - [0x0, asm, fx_field_header]
      - [0x1C, asm, func_8018F00C]
      - [0x224, asm, func_8018F214]
      - [0xC6C, c, func_8018FC5C]
      - [0xC90, asm, fx_field_data]
  - [0x1000]
