name: ovl_182.bin
sha1: ce88524fe29d95ec8be5f51c6bc366525def24e0
options:
  basename: ovl_182
  target_path: original/USA/overlays/ovl_182.bin
  base_path: ../../..
  platform: psx
  compiler: GCC
  asm_path: asm/USA/overlays/ovl_182
  src_path: src/overlays/ovl_182
  build_path: build/USA/overlays/ovl_182
  ld_script_path: linkers/USA/overlays/ovl_182.ld
  undefined_funcs_auto_path: linkers/USA/overlays/undefined_funcs_auto.ovl_182.txt
  undefined_syms_auto_path: linkers/USA/overlays/undefined_syms_auto.ovl_182.txt
  find_file_boundaries: True
  disassemble_all: True
  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel
  generate_asm_macros_files: False
  section_order: [".rodata", ".text", ".data", ".sdata", ".sbss", ".bss"]
  subalign: 4
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: ovl_182
    type: code
    start: 0x0
    vram: 0x8018EFF0
    align: 4
    subalign: 4
    bss_size: 0x0
    subsegments:
      - [0x0, asm, ovl_182]
  - [0x3000]
# source slice: scanner
# extract locally with: dd if=disc/extracted/PE.IMG of=original/USA/overlays/ovl_182.bin bs=2048 skip=96672 count=6
