name: ovl_176.bin
sha1: 6058134d30d9ed228e243407ce0d61cb779445f3
options:
  basename: ovl_176
  target_path: original/USA/overlays/ovl_176.bin
  base_path: ../../..
  platform: psx
  compiler: GCC
  asm_path: asm/USA/overlays/ovl_176
  src_path: src/overlays/ovl_176
  build_path: build/USA/overlays/ovl_176
  ld_script_path: linkers/USA/overlays/ovl_176.ld
  undefined_funcs_auto_path: linkers/USA/overlays/undefined_funcs_auto.ovl_176.txt
  symbol_addrs_path: configs/USA/overlays/sym.ovl_176.txt
  undefined_syms_auto_path: linkers/USA/overlays/undefined_syms_auto.ovl_176.txt
  find_file_boundaries: True
  disassemble_all: True
  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel
  generate_asm_macros_files: False
  section_order: [".rodata", ".text", ".data", ".sdata", ".sbss", ".bss"]
  subalign: 4
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: ovl_176
    type: code
    start: 0x0
    vram: 0x8018EFF0
    align: 4
    subalign: 4
    bss_size: 0x0
    subsegments:
      - [0x0, asm, ovl_176]
      - [0x204, c, RoomLib_InitB_8018F1F4]
      - [0x2A4, asm, ovl_176_2A4]
      - [0x528, c, func_8018F518]
      - [0x530, asm, ovl_176_2A4_530]
      - [0x5B8, c, RoomLib_NotifyArmB_8018F5A8]
      - [0x660, asm, ovl_176_2A4_660]
      - [0xBA0, c, RoomLib_FxNotify]
      - [0xBA8, asm, ovl_176_2A4_660_BA8]
      - [0xC80, c, func_8018FC70]
      - [0xC88, asm, ovl_176_2A4_660_BA8_C88]
      - [0xF74, c, RoomLib_InitD_8018FF64]
      - [0xFF0, asm, ovl_176_2A4_660_FF0]
      - [0x12F8, c, RoomLib_Notify2ArmB_801902E8]
      - [0x13A0, asm, ovl_176_2A4_660_FF0_13A0]
      - [0x192C, c, RoomLib_SteerToward_8019091C]
      - [0x19B0, c, RoomLib_ResetAndSignalB_801909A0]
      - [0x1A08, c, func_801909F8]
      - [0x1A10, c, func_80190A00]
      - [0x1A18, c, RoomLib_InitC_80190A08]
      - [0x1AB4, asm, ovl_176_2A4_660_FF0_13A0_19B0_1A08_1AB4]
      - [0x1CFC, c, func_80190CEC]
      - [0x1D04, c, RoomLib_InvokeCallbackC_80190CF4]
      - [0x1D2C, c, RoomLib_ArmWindowA_80190D1C]
      - [0x1D9C, asm, ovl_176_2A4_660_FF0_13A0_19B0_1A08_1AB4_1D2C_1D9C]
      - [0x2128, c, func_80191118]
      - [0x2130, asm, ovl_176_2A4_660_FF0_13A0_19B0_1A08_1AB4_1D2C_1D9C_2130]
      - [0x24D0, c, RoomLib_ResetAndSignal_801914C0]
      - [0x252C, c, func_8019151C]
      - [0x2534, c, func_80191524]
      - [0x253C, c, RoomLib_InitFull_8019152C]
      - [0x25CC, asm, ovl_176_2A4_660_FF0_13A0_19B0_1A08_1AB4_1D2C_1D9C_252C_25CC]
      - [0x2814, c, func_80191804]
      - [0x281C, c, RoomLib_InvokeCallbackC_8019180C]
      - [0x2844, c, RoomLib_ArmWindowB_80191834]
      - [0x28B4, asm, ovl_176_2A4_660_FF0_13A0_19B0_1A08_1AB4_1D2C_1D9C_252C_25CC_2844_28B4]
      - [0x2D30, c, func_80191D20]
      - [0x2D38, asm, ovl_176_2A4_660_FF0_13A0_19B0_1A08_1AB4_1D2C_1D9C_252C_25CC_2844_28B4_2D38]
      - [0x30B8, c, func_801920A8]
      - [0x30C0, c, RoomLib_ResetAndSignal_801920B0]
      - [0x311C, c, func_8019210C]
      - [0x3124, c, func_80192114]
      - [0x312C, c, RoomLib_InitTimers_8019211C]
      - [0x3168, asm, ovl_176_2A4_660_FF0_13A0_19B0_1A08_1AB4_1D2C_1D9C_252C_25CC_2844_28B4_311C_3168]
      - [0x3200, c, func_801921F0]
      - [0x3208, c, RoomLib_InvokeCallbackC_801921F8]
      - [0x3230, c, RoomLib_RearmOnMatch_80192220]
      - [0x3260, asm, ovl_176_2A4_660_FF0_13A0_19B0_1A08_1AB4_1D2C_1D9C_252C_25CC_2844_28B4_311C_3168_3230_3260]
      - [0x34F4, c, RoomLib_Set4ClearSignal_801924E4]
      - [0x3510, asm, ovl_176_2A4_660_FF0_13A0_19B0_1A08_1AB4_1D2C_1D9C_252C_25CC_2844_28B4_311C_3168_3230_3260_3510]
      - [0x3D8C, data]
  - [0x4000]
# source slice: scanner
# extract locally with: dd if=disc/extracted/PE.IMG of=original/USA/overlays/ovl_176.bin bs=2048 skip=95334 count=8
