name: room_m404.bin
sha1: c611bd599af3f8e0961c1dc5016e31d3d30e3971
options:
  basename: room_m404
  target_path: original/USA/overlays/room_m404.bin
  base_path: ../../..
  platform: psx
  compiler: GCC
  asm_path: asm/USA/overlays/room_m404
  src_path: src/overlays/room_m404
  build_path: build/USA/overlays/room_m404
  ld_script_path: linkers/USA/overlays/room_m404.ld
  undefined_funcs_auto_path: linkers/USA/overlays/undefined_funcs_auto.room_m404.txt
  symbol_addrs_path: configs/USA/overlays/sym.room_m404.txt
  undefined_syms_auto_path: linkers/USA/overlays/undefined_syms_auto.room_m404.txt
  find_file_boundaries: True
  disassemble_all: True
  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel
  generate_asm_macros_files: False
  section_order: [".rodata", ".text", ".data", ".sdata", ".sbss", ".bss"]
  subalign: 4
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: room_m404
    type: code
    start: 0x0
    vram: 0x80100000
    align: 4
    subalign: 4
    bss_size: 0x0
    subsegments:
      - [0x0, asm, room_m404]
      - [0x5F8, c, RoomLib_NotifyArmB_801005F8]
      - [0x6A0, asm, room_m404_6A0]
      - [0x19F0, c, RoomLib_ResetAndSignalB_801019F0]
      - [0x1A48, asm, room_m404_1A48]
      - [0x1D44, c, RoomLib_InvokeCallbackC_80101D44]
      - [0x1D6C, c, RoomLib_ArmWindowA_80101D6C]
      - [0x1DDC, asm, room_m404_1D6C_1DDC]
      - [0x2510, c, RoomLib_ResetAndSignal_80102510]
      - [0x256C, asm, room_m404_1D6C_256C]
      - [0x257C, c, RoomLib_InitFull_8010257C]
      - [0x260C, asm, room_m404_1D6C_256C_260C]
      - [0x285C, c, RoomLib_InvokeCallbackC_8010285C]
      - [0x2884, c, RoomLib_ArmWindowB_80102884]
      - [0x28F4, asm, room_m404_1D6C_2884_28F4]
      - [0x3100, c, RoomLib_ResetAndSignal_80103100]
      - [0x315C, asm, room_m404_1D6C_2884_315C]
      - [0x316C, c, RoomLib_InitTimers_8010316C]
      - [0x31A8, asm, room_m404_1D6C_2884_315C_31A8]
      - [0x3248, c, RoomLib_InvokeCallbackC_80103248]
      - [0x3270, c, RoomLib_RearmOnMatch_80103270]
      - [0x32A0, asm, room_m404_1D6C_2884_3270_32A0]
      - [0x3534, c, RoomLib_Set4ClearSignal_80103534]
      - [0x3550, asm, room_m404_1D6C_2884_3270_3550]
      - [0x4E4C, data]
  - [0x41800]
# room: m404, section3 sector 93050, scanner delta 0
# source slice: room-section3
# extract locally with: dd if=disc/extracted/PE.IMG of=original/USA/overlays/room_m404.bin bs=2048 skip=93050 count=131
