name: room_m116.bin
sha1: cfc9e33ffd9b52879626a01bac21366e462212f1
options:
  basename: room_m116
  target_path: original/USA/overlays/room_m116.bin
  base_path: ../../..
  platform: psx
  compiler: GCC
  asm_path: asm/USA/overlays/room_m116
  src_path: src/overlays/room_m116
  build_path: build/USA/overlays/room_m116
  ld_script_path: linkers/USA/overlays/room_m116.ld
  undefined_funcs_auto_path: linkers/USA/overlays/undefined_funcs_auto.room_m116.txt
  symbol_addrs_path: configs/USA/overlays/sym.room_m116.txt
  undefined_syms_auto_path: linkers/USA/overlays/undefined_syms_auto.room_m116.txt
  find_file_boundaries: True
  disassemble_all: True
  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel
  generate_asm_macros_files: False
  section_order: [".rodata", ".text", ".data", ".sdata", ".sbss", ".bss"]
  subalign: 4
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: room_m116
    type: code
    start: 0x0
    vram: 0x80100000
    align: 4
    subalign: 4
    bss_size: 0x0
    subsegments:
      - [0x0, asm, room_m116]
      - [0x5B4, c, RoomLib_NotifyArmB_801005B4]
      - [0x65C, asm, room_m116_65C]
      - [0x19AC, c, RoomLib_ResetAndSignalB_801019AC]
      - [0x1A04, asm, room_m116_1A04]
      - [0x1D00, c, RoomLib_InvokeCallbackC_80101D00]
      - [0x1D28, c, RoomLib_ArmWindowA_80101D28]
      - [0x1D98, asm, room_m116_1D28_1D98]
      - [0x24CC, c, RoomLib_ResetAndSignal_801024CC]
      - [0x2528, asm, room_m116_1D28_2528]
      - [0x2538, c, RoomLib_InitFull_80102538]
      - [0x25C8, asm, room_m116_1D28_2528_25C8]
      - [0x2818, c, RoomLib_InvokeCallbackC_80102818]
      - [0x2840, c, RoomLib_ArmWindowB_80102840]
      - [0x28B0, asm, room_m116_1D28_2840_28B0]
      - [0x30BC, c, RoomLib_ResetAndSignal_801030BC]
      - [0x3118, asm, room_m116_1D28_2840_3118]
      - [0x3128, c, RoomLib_InitTimers_80103128]
      - [0x3164, asm, room_m116_1D28_2840_3118_3164]
      - [0x3204, c, RoomLib_InvokeCallbackC_80103204]
      - [0x322C, c, RoomLib_RearmOnMatch_8010322C]
      - [0x325C, asm, room_m116_1D28_2840_322C_325C]
      - [0x34F0, c, RoomLib_Set4ClearSignal_801034F0]
      - [0x350C, asm, room_m116_1D28_2840_322C_350C]
      - [0x11E70, data]
  - [0x44800]
# room: m116, section3 sector 35921, scanner delta 0
# source slice: room-section3
# extract locally with: dd if=disc/extracted/PE.IMG of=original/USA/overlays/room_m116.bin bs=2048 skip=35921 count=137
