name: room_m390.bin
sha1: 4d02bd1bcfbaf4793f3e9a0662e47f0e846cfd53
options:
  basename: room_m390
  target_path: original/USA/overlays/room_m390.bin
  base_path: ../../..
  platform: psx
  compiler: GCC
  asm_path: asm/USA/overlays/room_m390
  src_path: src/overlays/room_m390
  build_path: build/USA/overlays/room_m390
  ld_script_path: linkers/USA/overlays/room_m390.ld
  undefined_funcs_auto_path: linkers/USA/overlays/undefined_funcs_auto.room_m390.txt
  symbol_addrs_path: configs/USA/overlays/sym.room_m390.txt
  undefined_syms_auto_path: linkers/USA/overlays/undefined_syms_auto.room_m390.txt
  find_file_boundaries: True
  disassemble_all: True
  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel
  generate_asm_macros_files: False
  section_order: [".rodata", ".text", ".data", ".sdata", ".sbss", ".bss"]
  subalign: 4
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: room_m390
    type: code
    start: 0x0
    vram: 0x80100000
    align: 4
    subalign: 4
    bss_size: 0x0
    subsegments:
      - [0x0, asm, room_m390]
      - [0x1D20, c, RoomLib_InvokeCallbackC_80101D20]
      - [0x1D48, asm, room_m390_1D48]
      - [0x24EC, c, RoomLib_ResetAndSignal_801024EC]
      - [0x2548, asm, room_m390_1D48_2548]
      - [0x2838, c, RoomLib_InvokeCallbackC_80102838]
      - [0x2860, asm, room_m390_1D48_2860]
      - [0x30DC, c, RoomLib_ResetAndSignal_801030DC]
      - [0x3138, asm, room_m390_1D48_2860_3138]
      - [0x3148, c, RoomLib_InitTimers_80103148]
      - [0x3184, asm, room_m390_1D48_2860_3138_3184]
      - [0x3224, c, RoomLib_InvokeCallbackC_80103224]
      - [0x324C, c, RoomLib_RearmOnMatch_8010324C]
      - [0x327C, asm, room_m390_1D48_2860_324C_327C]
      - [0x3510, c, RoomLib_Set4ClearSignal_80103510]
      - [0x352C, asm, room_m390_1D48_2860_324C_352C]
      - [0x6DB0, data]
  - [0x5B000]
# room: m390, section3 sector 89964, scanner delta 0
# source slice: room-section3
# extract locally with: dd if=disc/extracted/PE.IMG of=original/USA/overlays/room_m390.bin bs=2048 skip=89964 count=182
