name: room_m350.bin
sha1: e9597b000d287033f981cee44f3db65deb8696e1
options:
  basename: room_m350
  target_path: original/USA/overlays/room_m350.bin
  base_path: ../../..
  platform: psx
  compiler: GCC
  asm_path: asm/USA/overlays/room_m350
  src_path: src/overlays/room_m350
  build_path: build/USA/overlays/room_m350
  ld_script_path: linkers/USA/overlays/room_m350.ld
  undefined_funcs_auto_path: linkers/USA/overlays/undefined_funcs_auto.room_m350.txt
  symbol_addrs_path: configs/USA/overlays/sym.room_m350.txt
  undefined_syms_auto_path: linkers/USA/overlays/undefined_syms_auto.room_m350.txt
  find_file_boundaries: True
  disassemble_all: True
  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel
  generate_asm_macros_files: False
  section_order: [".rodata", ".text", ".data", ".sdata", ".sbss", ".bss"]
  subalign: 4
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: room_m350
    type: code
    start: 0x0
    vram: 0x80100000
    align: 4
    subalign: 4
    bss_size: 0x0
    subsegments:
      - [0x0, asm, room_m350]
      - [0x5C0, c, RoomLib_NotifyArmB_801005C0]
      - [0x668, asm, room_m350_668]
      - [0x19B8, c, RoomLib_ResetAndSignalB_801019B8]
      - [0x1A10, asm, room_m350_1A10]
      - [0x1D0C, c, RoomLib_InvokeCallbackC_80101D0C]
      - [0x1D34, c, RoomLib_ArmWindowA_80101D34]
      - [0x1DA4, asm, room_m350_1D34_1DA4]
      - [0x24D8, c, RoomLib_ResetAndSignal_801024D8]
      - [0x2534, asm, room_m350_1D34_2534]
      - [0x2544, c, RoomLib_InitFull_80102544]
      - [0x25D4, asm, room_m350_1D34_2534_25D4]
      - [0x2824, c, RoomLib_InvokeCallbackC_80102824]
      - [0x284C, c, RoomLib_ArmWindowB_8010284C]
      - [0x28BC, asm, room_m350_1D34_284C_28BC]
      - [0x30C8, c, RoomLib_ResetAndSignal_801030C8]
      - [0x3124, asm, room_m350_1D34_284C_3124]
      - [0x3134, c, RoomLib_InitTimers_80103134]
      - [0x3170, asm, room_m350_1D34_284C_3124_3170]
      - [0x3210, c, RoomLib_InvokeCallbackC_80103210]
      - [0x3238, c, RoomLib_RearmOnMatch_80103238]
      - [0x3268, asm, room_m350_1D34_284C_3238_3268]
      - [0x34FC, c, RoomLib_Set4ClearSignal_801034FC]
      - [0x3518, asm, room_m350_1D34_284C_3238_3518]
      - [0xB330, data]
  - [0x46000]
# room: m350, section3 sector 83539, scanner delta 0
# source slice: room-section3
# extract locally with: dd if=disc/extracted/PE.IMG of=original/USA/overlays/room_m350.bin bs=2048 skip=83539 count=140
