name: room_m394.bin
sha1: ca795705257ed6197cb83b70a9d3e4962b523689
options:
  basename: room_m394
  target_path: original/USA/overlays/room_m394.bin
  base_path: ../../..
  platform: psx
  compiler: GCC
  asm_path: asm/USA/overlays/room_m394
  src_path: src/overlays/room_m394
  build_path: build/USA/overlays/room_m394
  ld_script_path: linkers/USA/overlays/room_m394.ld
  undefined_funcs_auto_path: linkers/USA/overlays/undefined_funcs_auto.room_m394.txt
  symbol_addrs_path: configs/USA/overlays/sym.room_m394.txt
  undefined_syms_auto_path: linkers/USA/overlays/undefined_syms_auto.room_m394.txt
  find_file_boundaries: True
  disassemble_all: True
  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel
  generate_asm_macros_files: False
  section_order: [".rodata", ".text", ".data", ".sdata", ".sbss", ".bss"]
  subalign: 4
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: room_m394
    type: code
    start: 0x0
    vram: 0x80100000
    align: 4
    subalign: 4
    bss_size: 0x0
    subsegments:
      - [0x0, asm, room_m394]
      - [0x2D04, c, RoomLib_InvokeCallbackC_80102D04]
      - [0x2D2C, asm, room_m394_2D2C]
      - [0x34D0, c, RoomLib_ResetAndSignal_801034D0]
      - [0x352C, asm, room_m394_2D2C_352C]
      - [0x381C, c, RoomLib_InvokeCallbackC_8010381C]
      - [0x3844, asm, room_m394_2D2C_3844]
      - [0x40C0, c, RoomLib_ResetAndSignal_801040C0]
      - [0x411C, asm, room_m394_2D2C_3844_411C]
      - [0x412C, c, RoomLib_InitTimers_8010412C]
      - [0x4168, asm, room_m394_2D2C_3844_411C_4168]
      - [0x4208, c, RoomLib_InvokeCallbackC_80104208]
      - [0x4230, c, RoomLib_RearmOnMatch_80104230]
      - [0x4260, asm, room_m394_2D2C_3844_4230_4260]
      - [0x44F4, c, RoomLib_Set4ClearSignal_801044F4]
      - [0x4510, asm, room_m394_2D2C_3844_4230_4510]
      - [0x534C, data]
  - [0x2F800]
# room: m394, section3 sector 90870, scanner delta 0
# source slice: room-section3
# extract locally with: dd if=disc/extracted/PE.IMG of=original/USA/overlays/room_m394.bin bs=2048 skip=90870 count=95
