name: room_m263.bin
sha1: 02f1b9cdb8ebc50504b5622d1b663246c8427dea
options:
  basename: room_m263
  target_path: original/USA/overlays/room_m263.bin
  base_path: ../../..
  platform: psx
  compiler: GCC
  asm_path: asm/USA/overlays/room_m263
  src_path: src/overlays/room_m263
  build_path: build/USA/overlays/room_m263
  ld_script_path: linkers/USA/overlays/room_m263.ld
  undefined_funcs_auto_path: linkers/USA/overlays/undefined_funcs_auto.room_m263.txt
  symbol_addrs_path: configs/USA/overlays/sym.room_m263.txt
  undefined_syms_auto_path: linkers/USA/overlays/undefined_syms_auto.room_m263.txt
  find_file_boundaries: True
  disassemble_all: True
  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel
  generate_asm_macros_files: False
  section_order: [".rodata", ".text", ".data", ".sdata", ".sbss", ".bss"]
  subalign: 4
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: room_m263
    type: code
    start: 0x0
    vram: 0x80100000
    align: 4
    subalign: 4
    bss_size: 0x0
    subsegments:
      - [0x0, asm, room_m263]
      - [0x1D10, c, RoomLib_InvokeCallbackC_80101D10]
      - [0x1D38, asm, room_m263_1D38]
      - [0x2828, c, RoomLib_InvokeCallbackC_80102828]
      - [0x2850, asm, room_m263_1D38_2850]
      - [0x3214, c, RoomLib_InvokeCallbackC_80103214]
      - [0x323C, asm, room_m263_1D38_2850_323C]
      - [0x1C500, data]
  - [0x3E000]
# room: m263, section3 sector 67837, scanner delta 0
# source slice: room-section3
# extract locally with: dd if=disc/extracted/PE.IMG of=original/USA/overlays/room_m263.bin bs=2048 skip=67837 count=124
