name: room_m154.bin
sha1: c7c99e77f43dec7db821ae205a4895beb0114245
options:
  basename: room_m154
  target_path: original/USA/overlays/room_m154.bin
  base_path: ../../..
  platform: psx
  compiler: GCC
  asm_path: asm/USA/overlays/room_m154
  src_path: src/overlays/room_m154
  build_path: build/USA/overlays/room_m154
  ld_script_path: linkers/USA/overlays/room_m154.ld
  undefined_funcs_auto_path: linkers/USA/overlays/undefined_funcs_auto.room_m154.txt
  symbol_addrs_path: configs/USA/overlays/sym.room_m154.txt
  undefined_syms_auto_path: linkers/USA/overlays/undefined_syms_auto.room_m154.txt
  find_file_boundaries: True
  disassemble_all: True
  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel
  generate_asm_macros_files: False
  section_order: [".rodata", ".text", ".data", ".sdata", ".sbss", ".bss"]
  subalign: 4
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: room_m154
    type: code
    start: 0x0
    vram: 0x80100000
    align: 4
    subalign: 4
    bss_size: 0x0
    subsegments:
      - [0x0, asm, room_m154]
      - [0x3208, c, RoomLib_InvokeCallbackC_80103208]
      - [0x3230, asm, room_m154_3230]
      - [0x39D4, c, RoomLib_ResetAndSignal_801039D4]
      - [0x3A30, asm, room_m154_3230_3A30]
      - [0x3D20, c, RoomLib_InvokeCallbackC_80103D20]
      - [0x3D48, asm, room_m154_3230_3D48]
      - [0x45C4, c, RoomLib_ResetAndSignal_801045C4]
      - [0x4620, asm, room_m154_3230_3D48_4620]
      - [0x4630, c, RoomLib_InitTimers_80104630]
      - [0x466C, asm, room_m154_3230_3D48_4620_466C]
      - [0x470C, c, RoomLib_InvokeCallbackC_8010470C]
      - [0x4734, c, RoomLib_RearmOnMatch_80104734]
      - [0x4764, asm, room_m154_3230_3D48_4734_4764]
      - [0x49F8, c, RoomLib_Set4ClearSignal_801049F8]
      - [0x4A14, asm, room_m154_3230_3D48_4734_4A14]
      - [0x51E8, c, RoomLib_Set4ClearSignal_801051E8]
      - [0x5204, asm, room_m154_3230_3D48_4734_4A14_5204]
      - [0x64D4, data]
  - [0x4E800]
# room: m154, section3 sector 44380, scanner delta 0
# source slice: room-section3
# extract locally with: dd if=disc/extracted/PE.IMG of=original/USA/overlays/room_m154.bin bs=2048 skip=44380 count=157
