name: room_m030.bin
sha1: ac9c68a220a641bc36ae378d6f4d1fa4be50bded
options:
  basename: room_m030
  target_path: original/USA/overlays/room_m030.bin
  base_path: ../../..
  platform: psx
  compiler: GCC
  asm_path: asm/USA/overlays/room_m030
  src_path: src/overlays/room_m030
  build_path: build/USA/overlays/room_m030
  ld_script_path: linkers/USA/overlays/room_m030.ld
  undefined_funcs_auto_path: linkers/USA/overlays/undefined_funcs_auto.room_m030.txt
  symbol_addrs_path: configs/USA/overlays/sym.room_m030.txt
  undefined_syms_auto_path: linkers/USA/overlays/undefined_syms_auto.room_m030.txt
  find_file_boundaries: True
  disassemble_all: True
  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel
  generate_asm_macros_files: False
  section_order: [".rodata", ".text", ".data", ".sdata", ".sbss", ".bss"]
  subalign: 4
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: room_m030
    type: code
    start: 0x0
    vram: 0x80100000
    align: 4
    subalign: 4
    bss_size: 0x0
    subsegments:
      - [0x0, asm, room_m030]
      - [0xC6C, c, RoomLib_SetArgs3_80100C6C]
      - [0xC90, data]
  - [0x12800]
# room: m030, section3 sector 14403, scanner delta 0
# source slice: room-section3
# extract locally with: dd if=disc/extracted/PE.IMG of=original/USA/overlays/room_m030.bin bs=2048 skip=14403 count=37
