name: room_m398.bin
sha1: bb51c548138aa12de18c2373e71904f077438cbc
options:
  basename: room_m398
  target_path: original/USA/overlays/room_m398.bin
  base_path: ../../..
  platform: psx
  compiler: GCC
  asm_path: asm/USA/overlays/room_m398
  src_path: src/overlays/room_m398
  build_path: build/USA/overlays/room_m398
  ld_script_path: linkers/USA/overlays/room_m398.ld
  undefined_funcs_auto_path: linkers/USA/overlays/undefined_funcs_auto.room_m398.txt
  symbol_addrs_path: configs/USA/overlays/sym.room_m398.txt
  undefined_syms_auto_path: linkers/USA/overlays/undefined_syms_auto.room_m398.txt
  find_file_boundaries: True
  disassemble_all: True
  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel
  generate_asm_macros_files: False
  section_order: [".rodata", ".text", ".data", ".sdata", ".sbss", ".bss"]
  subalign: 4
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: room_m398
    type: code
    start: 0x0
    vram: 0x80100000
    align: 4
    subalign: 4
    bss_size: 0x0
    subsegments:
      - [0x0, asm, room_m398]
      - [0x1D00, c, RoomLib_InvokeCallbackC_80101D00]
      - [0x1D28, asm, room_m398_1D28]
      - [0x2818, c, RoomLib_InvokeCallbackC_80102818]
      - [0x2840, asm, room_m398_1D28_2840]
      - [0x3204, c, RoomLib_InvokeCallbackC_80103204]
      - [0x322C, asm, room_m398_1D28_2840_322C]
      - [0x4154, data]
  - [0x30800]
# room: m398, section3 sector 91759, scanner delta 0
# source slice: room-section3
# extract locally with: dd if=disc/extracted/PE.IMG of=original/USA/overlays/room_m398.bin bs=2048 skip=91759 count=97
