name: room_m273.bin
sha1: 692fdf1477e29d8eb1e2e6c8a7e1cc8ac51dda3a
options:
  basename: room_m273
  target_path: original/USA/overlays/room_m273.bin
  base_path: ../../..
  platform: psx
  compiler: GCC
  asm_path: asm/USA/overlays/room_m273
  src_path: src/overlays/room_m273
  build_path: build/USA/overlays/room_m273
  ld_script_path: linkers/USA/overlays/room_m273.ld
  undefined_funcs_auto_path: linkers/USA/overlays/undefined_funcs_auto.room_m273.txt
  symbol_addrs_path: configs/USA/overlays/sym.room_m273.txt
  undefined_syms_auto_path: linkers/USA/overlays/undefined_syms_auto.room_m273.txt
  find_file_boundaries: True
  disassemble_all: True
  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel
  generate_asm_macros_files: False
  section_order: [".rodata", ".text", ".data", ".sdata", ".sbss", ".bss"]
  subalign: 4
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: room_m273
    type: code
    start: 0x0
    vram: 0x80100000
    align: 4
    subalign: 4
    bss_size: 0x0
    subsegments:
      - [0x0, asm, room_m273]
      - [0x19B4, c, RoomLib_ResetAndSignalB_801019B4]
      - [0x1A0C, asm, room_m273_1A0C]
      - [0x1D08, c, RoomLib_InvokeCallbackC_80101D08]
      - [0x1D30, c, RoomLib_ArmWindowA_80101D30]
      - [0x1DA0, asm, room_m273_1D30_1DA0]
      - [0x24D4, c, RoomLib_ResetAndSignal_801024D4]
      - [0x2530, asm, room_m273_1D30_2530]
      - [0x2540, c, RoomLib_InitFull_80102540]
      - [0x25D0, asm, room_m273_1D30_2530_25D0]
      - [0x2820, c, RoomLib_InvokeCallbackC_80102820]
      - [0x2848, c, RoomLib_ArmWindowB_80102848]
      - [0x28B8, asm, room_m273_1D30_2848_28B8]
      - [0x30C4, c, RoomLib_ResetAndSignal_801030C4]
      - [0x3120, asm, room_m273_1D30_2848_3120]
      - [0x3130, c, RoomLib_InitTimers_80103130]
      - [0x316C, asm, room_m273_1D30_2848_3120_316C]
      - [0x320C, c, RoomLib_InvokeCallbackC_8010320C]
      - [0x3234, c, RoomLib_RearmOnMatch_80103234]
      - [0x3264, asm, room_m273_1D30_2848_3234_3264]
      - [0x34F8, c, RoomLib_Set4ClearSignal_801034F8]
      - [0x3514, asm, room_m273_1D30_2848_3234_3514]
      - [0x3628, c, RoomLib_InvokeCallbackC_80103628]
      - [0x3650, asm, room_m273_1D30_2848_3234_3650]
      - [0xB828, data]
  - [0x50800]
# room: m273, section3 sector 70012, scanner delta 0
# source slice: room-section3
# extract locally with: dd if=disc/extracted/PE.IMG of=original/USA/overlays/room_m273.bin bs=2048 skip=70012 count=161
