name: room_m385.bin
sha1: 9a77878b6604f7e6125f6d44100c8ae6139514f5
options:
  basename: room_m385
  target_path: original/USA/overlays/room_m385.bin
  base_path: ../../..
  platform: psx
  compiler: GCC
  asm_path: asm/USA/overlays/room_m385
  src_path: src/overlays/room_m385
  build_path: build/USA/overlays/room_m385
  ld_script_path: linkers/USA/overlays/room_m385.ld
  undefined_funcs_auto_path: linkers/USA/overlays/undefined_funcs_auto.room_m385.txt
  symbol_addrs_path: configs/USA/overlays/sym.room_m385.txt
  undefined_syms_auto_path: linkers/USA/overlays/undefined_syms_auto.room_m385.txt
  find_file_boundaries: True
  disassemble_all: True
  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel
  generate_asm_macros_files: False
  section_order: [".rodata", ".text", ".data", ".sdata", ".sbss", ".bss"]
  subalign: 4
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: room_m385
    type: code
    start: 0x0
    vram: 0x80100000
    align: 4
    subalign: 4
    bss_size: 0x0
    subsegments:
      - [0x0, asm, room_m385]
      - [0x393C, c, RoomLib_InvokeCallbackC_8010393C]
      - [0x3964, asm, room_m385_3964]
      - [0x4108, c, RoomLib_ResetAndSignal_80104108]
      - [0x4164, asm, room_m385_3964_4164]
      - [0x4454, c, RoomLib_InvokeCallbackC_80104454]
      - [0x447C, asm, room_m385_3964_447C]
      - [0x4CF8, c, RoomLib_ResetAndSignal_80104CF8]
      - [0x4D54, asm, room_m385_3964_447C_4D54]
      - [0x4D64, c, RoomLib_InitTimers_80104D64]
      - [0x4DA0, asm, room_m385_3964_447C_4D54_4DA0]
      - [0x4E40, c, RoomLib_InvokeCallbackC_80104E40]
      - [0x4E68, c, RoomLib_RearmOnMatch_80104E68]
      - [0x4E98, asm, room_m385_3964_447C_4E68_4E98]
      - [0x512C, c, RoomLib_Set4ClearSignal_8010512C]
      - [0x5148, asm, room_m385_3964_447C_4E68_5148]
      - [0x5150, data]
  - [0x29800]
# room: m385, section3 sector 89136, scanner delta 0
# source slice: room-section3
# extract locally with: dd if=disc/extracted/PE.IMG of=original/USA/overlays/room_m385.bin bs=2048 skip=89136 count=83
