name: room_m348.bin
sha1: 49478531f4b705ab248a8c2eb0a3b81c4cef9985
options:
  basename: room_m348
  target_path: original/USA/overlays/room_m348.bin
  base_path: ../../..
  platform: psx
  compiler: GCC
  asm_path: asm/USA/overlays/room_m348
  src_path: src/overlays/room_m348
  build_path: build/USA/overlays/room_m348
  ld_script_path: linkers/USA/overlays/room_m348.ld
  undefined_funcs_auto_path: linkers/USA/overlays/undefined_funcs_auto.room_m348.txt
  symbol_addrs_path: configs/USA/overlays/sym.room_m348.txt
  undefined_syms_auto_path: linkers/USA/overlays/undefined_syms_auto.room_m348.txt
  find_file_boundaries: True
  disassemble_all: True
  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel
  generate_asm_macros_files: False
  section_order: [".rodata", ".text", ".data", ".sdata", ".sbss", ".bss"]
  subalign: 4
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: room_m348
    type: code
    start: 0x0
    vram: 0x8018EFE8
    align: 4
    subalign: 4
    bss_size: 0x0
    subsegments:
      - [0x0, rodata, room_m348]
      - [0x7C, c, func_8018F064]
      - [0x84, c, RoomLib_PlantTable_8018F06C]
      - [0xB0, c, RoomLib_Spawn6_8018F098]
      - [0xDC, c, func_8018F0C4]
      - [0x140, c, func_8018F128]
      - [0x1CC, c, RoomLib_CloseTarget_8018F1B4]
      - [0x250, c, func_8018F238]
      - [0x258, c, func_8018F240]
      - [0x578, c, func_8018F560]
      - [0x580, c, func_8018F568]
      - [0x600, c, func_8018F5E8]
      - [0x608, c, func_8018F5F0]
      - [0x610, asm, func_8018F5F8]
      - [0x8B8, c, func_8018F8A0]
      - [0x8D8, c, func_8018F8C0]
      - [0x9C4, c, func_8018F9AC]
      - [0xA44, c, func_8018FA2C]
      - [0xA68, asm, func_8018FA50]
      - [0xC4C, c, func_8018FC34]
      - [0xCA4, asm, func_8018FC8C]
      - [0xDE4, asm, func_8018FDCC]
      - [0x1100, c, func_801900E8]
      - [0x1150, c, func_80190138]
      - [0x11E4, asm, func_801901CC]
      - [0x1814, asm, func_801907FC]
      - [0x1C3C, c, RoomLib_Set3Reset_80190C24]
      - [0x1C5C, c, func_80190C44]
      - [0x1D48, c, func_80190D30]
      - [0x1D88, c, func_80190D70]
      - [0x1D90, c, func_80190D78]
      - [0x1D98, c, func_80190D80]
      - [0x1DA0, c, func_80190D88]
      - [0x1EB0, asm, func_80190E98]
      - [0x24B8, asm, func_801914A0]
      - [0x2900, asm, func_801918E8]
      - [0x2AB0, asm, func_80191A98]
      - [0x2DC8, c, func_80191DB0]
      - [0x2E34, asm, func_80191E1C]
      - [0x2FF8, asm, func_80191FE0]
      - [0x32F8, c, func_801922E0]
      - [0x3388, c, func_80192370]
      - [0x3390, c, func_80192378]
      - [0x3398, c, func_80192380]
      - [0x33A0, c, func_80192388]
      - [0x33C8, asm, func_801923B0]
      - [0x3554, asm, func_8019253C]
      - [0x3860, data, D_80192848]
      - [0x3898, data, D_80192880]
      - [0x38D0, data, D_801928B8]
      - [0x3908, data, D_801928F0]
      - [0x3924, data, D_8019290C]
      - [0x3940, data, RoomLib_TableB_8018F06C]
      - [0x3A00, data, D_801929E8]
      - [0x3A18, data, D_80192A00]
      - [0x3C18, data, D_80192C00]
      - [0x3E18, data, D_80192E00]
      - [0x3E1C, data, D_80192E04]
      - [0x3E20, data, D_80192E08]
      - [0x3E28, data, D_80192E10]
      - [0x3E2C, data, D_80192E14]
      - [0x3E30, data, D_80192E18]
      - [0x3E34, data, D_80192E1C]
      - [0x3E38, data, D_80192E20]
      - [0x3E3C, data, D_80192E24]
      - [0x3E40, data, D_80192E28]
      - [0x3E4C, data, D_80192E34]
      - [0x3E50, data, D_80192E38]
      - [0x3E58, data, D_80192E40]
      - [0x3E5C, data, D_80192E44]
      - [0x3E60, data, D_80192E48]
      - [0x3E6C, data, D_80192E54]
      - [0x3E70, data, D_80192E58]
      - [0x3E74, data, D_80192E5C]
      - [0x3E78, data, D_80192E60]
      - [0x3E7C, data, D_80192E64]
      - [0x3E94, data, D_80192E7C]
      - [0x3E9C, data, D_80192E84]
      - [0x3EA0, data, D_80192E88]
      - [0x3EA4, data, D_80192E8C]
      - [0x3EA8, data, D_80192E90]
      - [0x3EAC, data, D_80192E94]
      - [0x3EB4, data, D_80192E9C]
      - [0x3EB8, data, D_80192EA0]
      - [0x3EBC, data, D_80192EA4]
      - [0x3EC0, data, D_80192EA8]
      - [0x3EC4, data, D_80192EAC]
      - [0x3EC8, data, D_80192EB0]
      - [0x3ECC, data, D_80192EB4]
      - [0x3ED0, data, D_80192EB8]
      - [0x3ED8, data, D_80192EC0]
      - [0x3EDC, data, D_80192EC4]
      - start: 0x3EE0
        type: databin
        name: D_80192EC8
        dir: room_m348
      - start: 0x19210
        type: databin
        name: D_801A81F8
        dir: room_m348
      - start: 0x291FC
        type: databin
        name: D_801B81E4
        dir: room_m348
  - [0x34000]
# room: m348, section3 sector 83089, scanner delta 0
# source slice: room-section3
# extract locally with: dd if=disc/extracted/PE.IMG of=original/USA/overlays/room_m348.bin bs=2048 skip=83089 count=104
# text-bank: Day 1 night: theater blaze aftermath
