name: room_m243.bin
sha1: 1908110800910d0bfc9b3e7d6620ad8627b7216d
options:
  basename: room_m243
  target_path: original/USA/overlays/room_m243.bin
  base_path: ../../..
  platform: psx
  compiler: GCC
  asm_path: asm/USA/overlays/room_m243
  src_path: src/overlays/room_m243
  build_path: build/USA/overlays/room_m243
  ld_script_path: linkers/USA/overlays/room_m243.ld
  undefined_funcs_auto_path: linkers/USA/overlays/undefined_funcs_auto.room_m243.txt
  symbol_addrs_path: configs/USA/overlays/sym.room_m243.txt
  undefined_syms_auto_path: linkers/USA/overlays/undefined_syms_auto.room_m243.txt
  find_file_boundaries: True
  disassemble_all: True
  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel
  generate_asm_macros_files: False
  section_order: [".rodata", ".text", ".data", ".sdata", ".sbss", ".bss"]
  subalign: 4
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: room_m243
    type: code
    start: 0x0
    vram: 0x80100000
    align: 4
    subalign: 4
    bss_size: 0x0
    subsegments:
      - [0x0, asm, room_m243]
      - [0x5AC, c, RoomLib_NotifyArmB_801005AC]
      - [0x654, asm, room_m243_654]
      - [0x19A4, c, RoomLib_ResetAndSignalB_801019A4]
      - [0x19FC, asm, room_m243_19FC]
      - [0x1CF8, c, RoomLib_InvokeCallbackC_80101CF8]
      - [0x1D20, c, RoomLib_ArmWindowA_80101D20]
      - [0x1D90, asm, room_m243_1D20_1D90]
      - [0x24C4, c, RoomLib_ResetAndSignal_801024C4]
      - [0x2520, asm, room_m243_1D20_2520]
      - [0x2530, c, RoomLib_InitFull_80102530]
      - [0x25C0, asm, room_m243_1D20_2520_25C0]
      - [0x2810, c, RoomLib_InvokeCallbackC_80102810]
      - [0x2838, c, RoomLib_ArmWindowB_80102838]
      - [0x28A8, asm, room_m243_1D20_2838_28A8]
      - [0x30B4, c, RoomLib_ResetAndSignal_801030B4]
      - [0x3110, asm, room_m243_1D20_2838_3110]
      - [0x3120, c, RoomLib_InitTimers_80103120]
      - [0x315C, asm, room_m243_1D20_2838_3110_315C]
      - [0x31FC, c, RoomLib_InvokeCallbackC_801031FC]
      - [0x3224, c, RoomLib_RearmOnMatch_80103224]
      - [0x3254, asm, room_m243_1D20_2838_3224_3254]
      - [0x34E8, c, RoomLib_Set4ClearSignal_801034E8]
      - [0x3504, asm, room_m243_1D20_2838_3224_3504]
      - [0x3C50, data]
  - [0x2B800]
# room: m243, section3 sector 63515, scanner delta 0
# source slice: room-section3
# extract locally with: dd if=disc/extracted/PE.IMG of=original/USA/overlays/room_m243.bin bs=2048 skip=63515 count=87
