name: room_m045.bin
sha1: 6300e1f1daa0ad17dd49396a51e62b6b11fcf7f6
options:
  basename: room_m045
  target_path: original/USA/overlays/room_m045.bin
  base_path: ../../..
  platform: psx
  compiler: GCC
  asm_path: asm/USA/overlays/room_m045
  src_path: src/overlays/room_m045
  build_path: build/USA/overlays/room_m045
  ld_script_path: linkers/USA/overlays/room_m045.ld
  undefined_funcs_auto_path: linkers/USA/overlays/undefined_funcs_auto.room_m045.txt
  symbol_addrs_path: configs/USA/overlays/sym.room_m045.txt
  undefined_syms_auto_path: linkers/USA/overlays/undefined_syms_auto.room_m045.txt
  find_file_boundaries: True
  disassemble_all: True
  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel
  generate_asm_macros_files: False
  section_order: [".rodata", ".text", ".data", ".sdata", ".sbss", ".bss"]
  subalign: 4
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: room_m045
    type: code
    start: 0x0
    vram: 0x8018EFE8
    align: 4
    subalign: 4
    bss_size: 0x0
    subsegments:
      - [0x0, rodata, room_m045]
      - [0xC, c, func_8018EFF4]
      - [0x14, c, RoomMdl_Reset_8018EFFC]
      - [0x38, c, RoomMdl_Select_8018F020]
      - [0x108, c, RoomMdl_Tick_8018F0F0]
      - [0x1BC, c, func_8018F1A4]
      - [0x1C4, c, RoomMdl_Kill_8018F1AC]
      - [0x1D4, c, func_8018F1BC]
      - [0x1DC, c, RoomEnt_Setup5_8018F1C4]
      - [0x210, asm, RoomFx_ModelUpdate]
      - [0x598, asm, RoomFx_ModelDraw]
      - [0xB5C, data]
  - [0x2D800]
# room: m045, section3 sector 19716, scanner delta 0
# source slice: room-section3
# extract locally with: dd if=disc/extracted/PE.IMG of=original/USA/overlays/room_m045.bin bs=2048 skip=19716 count=91
# text-bank: NYPD 28th Precinct: Day 2 (weapon dept)
