name: room_m146.bin
sha1: 72a6cf583e2916e84a5d452ae90a444d19688f68
options:
  basename: room_m146
  target_path: original/USA/overlays/room_m146.bin
  base_path: ../../..
  platform: psx
  compiler: GCC
  asm_path: asm/USA/overlays/room_m146
  src_path: src/overlays/room_m146
  build_path: build/USA/overlays/room_m146
  ld_script_path: linkers/USA/overlays/room_m146.ld
  undefined_funcs_auto_path: linkers/USA/overlays/undefined_funcs_auto.room_m146.txt
  symbol_addrs_path: configs/USA/overlays/sym.room_m146.txt
  undefined_syms_auto_path: linkers/USA/overlays/undefined_syms_auto.room_m146.txt
  find_file_boundaries: True
  disassemble_all: True
  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel
  generate_asm_macros_files: False
  section_order: [".rodata", ".text", ".data", ".sdata", ".sbss", ".bss"]
  subalign: 4
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: room_m146
    type: code
    start: 0x0
    vram: 0x8018EFE8
    align: 4
    subalign: 4
    bss_size: 0x0
    subsegments:
      - [0x0, asm, room_m146]
      - [0x9C, c, RoomLib_PlantTable_8018F084]
      - [0xC8, c, RoomLib_Spawn6_8018F0B0]
      - [0xF4, asm, room_m146_F4]
      - [0x1560, c, RoomLib_PlantTable_80190548]
      - [0x158C, c, RoomLib_Spawn6_80190574]
      - [0x15B8, c, RoomLib_RegisterTable_801905A0]
      - [0x1600, asm, room_m146_F4_15B8_1600]
      - [0x168C, c, RoomLib_CloseTarget_80190674]
      - [0x1710, asm, room_m146_F4_15B8_1710]
      - [0x1EFC, c, RoomLib_Set3Range_80190EE4]
      - [0x1F14, asm, room_m146_F4_15B8_1710_1F14]
      - [0x20C4, c, RoomLib_Set3Size_801910AC]
      - [0x20D8, asm, room_m146_F4_15B8_1710_20D8]
      - [0x3460, data]
  - [0x50000]
# room: m146, section3 sector 42308, scanner delta 0
# source slice: room-section3
# extract locally with: dd if=disc/extracted/PE.IMG of=original/USA/overlays/room_m146.bin bs=2048 skip=42308 count=160
