name: room_m107.bin
sha1: dcf6cf737f829adb79fad3ecb65a08d57cf6f664
options:
  basename: room_m107
  target_path: original/USA/overlays/room_m107.bin
  base_path: ../../..
  platform: psx
  compiler: GCC
  asm_path: asm/USA/overlays/room_m107
  src_path: src/overlays/room_m107
  build_path: build/USA/overlays/room_m107
  ld_script_path: linkers/USA/overlays/room_m107.ld
  undefined_funcs_auto_path: linkers/USA/overlays/undefined_funcs_auto.room_m107.txt
  symbol_addrs_path: configs/USA/overlays/sym.room_m107.txt
  undefined_syms_auto_path: linkers/USA/overlays/undefined_syms_auto.room_m107.txt
  find_file_boundaries: True
  disassemble_all: True
  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel
  generate_asm_macros_files: False
  section_order: [".rodata", ".text", ".data", ".sdata", ".sbss", ".bss"]
  subalign: 4
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: room_m107
    type: code
    start: 0x0
    vram: 0x80100000
    align: 4
    subalign: 4
    bss_size: 0x0
    subsegments:
      - [0x0, asm, room_m107]
      - [0x128C, c, RoomLib_InitB_8010128C]
      - [0x132C, asm, room_m107_132C]
      - [0x1640, c, RoomLib_NotifyArmB_80101640]
      - [0x16E8, asm, room_m107_16E8]
      - [0x2380, c, RoomLib_Notify2ArmB_80102380]
      - [0x2428, asm, room_m107_16E8_2428]
      - [0x2A38, c, RoomLib_ResetAndSignalB_80102A38]
      - [0x2A90, asm, room_m107_2A90]
      - [0x2AA0, c, RoomLib_InitC_80102AA0]
      - [0x2B3C, asm, room_m107_2A90_2B3C]
      - [0x2D8C, c, RoomLib_InvokeCallbackC_80102D8C]
      - [0x2DB4, c, RoomLib_ArmWindowA_80102DB4]
      - [0x2E24, asm, room_m107_2DB4_2E24]
      - [0x3558, c, RoomLib_ResetAndSignal_80103558]
      - [0x35B4, asm, room_m107_2DB4_35B4]
      - [0x35C4, c, RoomLib_InitFull_801035C4]
      - [0x3654, asm, room_m107_2DB4_35B4_3654]
      - [0x38A4, c, RoomLib_InvokeCallbackC_801038A4]
      - [0x38CC, c, RoomLib_ArmWindowB_801038CC]
      - [0x393C, asm, room_m107_2DB4_38CC_393C]
      - [0x4148, c, RoomLib_ResetAndSignal_80104148]
      - [0x41A4, asm, room_m107_2DB4_38CC_41A4]
      - [0x41B4, c, RoomLib_InitTimers_801041B4]
      - [0x41F0, asm, room_m107_2DB4_38CC_41A4_41F0]
      - [0x4290, c, RoomLib_InvokeCallbackC_80104290]
      - [0x42B8, c, RoomLib_RearmOnMatch_801042B8]
      - [0x42E8, asm, room_m107_2DB4_38CC_42B8_42E8]
      - [0x457C, c, RoomLib_Set4ClearSignal_8010457C]
      - [0x4598, asm, room_m107_2DB4_38CC_42B8_4598]
      - [0x45A0, data]
  - [0x33800]
# room: m107, section3 sector 34053, scanner delta 0
# source slice: room-section3
# extract locally with: dd if=disc/extracted/PE.IMG of=original/USA/overlays/room_m107.bin bs=2048 skip=34053 count=103
