name: room_m348.bin
sha1: 49478531f4b705ab248a8c2eb0a3b81c4cef9985
options:
  basename: room_m348
  target_path: original/USA/overlays/room_m348.bin
  base_path: ../../..
  platform: psx
  compiler: GCC
  asm_path: asm/USA/overlays/room_m348
  src_path: src/overlays/room_m348
  build_path: build/USA/overlays/room_m348
  ld_script_path: linkers/USA/overlays/room_m348.ld
  undefined_funcs_auto_path: linkers/USA/overlays/undefined_funcs_auto.room_m348.txt
  symbol_addrs_path: configs/USA/overlays/sym.room_m348.txt
  undefined_syms_auto_path: linkers/USA/overlays/undefined_syms_auto.room_m348.txt
  find_file_boundaries: True
  disassemble_all: True
  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel
  generate_asm_macros_files: False
  section_order: [".rodata", ".text", ".data", ".sdata", ".sbss", ".bss"]
  subalign: 4
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: room_m348
    type: code
    start: 0x0
    vram: 0x8018EFE8
    align: 4
    subalign: 4
    bss_size: 0x0
    subsegments:
      - [0x0, rodata, room_m348]
      - [0x7C, c, func_8018F064]
      - [0x84, c, RoomLib_PlantTable_8018F06C]
      - [0xB0, c, RoomLib_Spawn6_8018F098]
      - [0xDC, asm, func_8018F0C4]
      - [0x140, c, func_8018F128]
      - [0x1CC, c, RoomLib_CloseTarget_8018F1B4]
      - [0x250, c, func_8018F238]
      - [0x258, c, func_8018F240]
      - [0x578, c, func_8018F560]
      - [0x580, c, func_8018F568]
      - [0x600, c, func_8018F5E8]
      - [0x608, c, func_8018F5F0]
      - [0x610, asm, room_m348_DC_250_610]
      - [0x8B8, c, func_8018F8A0]
      - [0x8D8, c, func_8018F8C0]
      - [0x9C4, c, func_8018F9AC]
      - [0xA44, c, func_8018FA2C]
      - [0xA68, asm, room_m348_DC_250_610_8D8_A68]
      - [0xC4C, asm, func_8018FC34]
      - [0xCA4, asm, room_m348_DC_250_610_8D8_A68_CA4]
      - [0x1100, asm, func_801900E8]
      - [0x1150, asm, func_80190138]
      - [0x11E4, asm, room_m348_DC_250_610_8D8_A68_1150_11E4]
      - [0x1C3C, c, RoomLib_Set3Reset_80190C24]
      - [0x1C5C, c, func_80190C44]
      - [0x1D48, c, func_80190D30]
      - [0x1D88, c, func_80190D70]
      - [0x1D90, c, func_80190D78]
      - [0x1D98, c, func_80190D80]
      - [0x1DA0, asm, room_m348_DC_250_1C5C_1DA0]
      - [0x2DC8, c, func_80191DB0]
      - [0x2E34, asm, room_m348_DC_250_1C5C_1DA0_2E34]
      - [0x32F8, asm, func_801922E0]
      - [0x3388, c, func_80192370]
      - [0x3390, c, func_80192378]
      - [0x3398, c, func_80192380]
      - [0x33A0, c, func_80192388]
      - [0x33C8, asm, room_m348_DC_250_1C5C_1DA0_33C8]
      - [0x3860, data]
  - [0x34000]
# room: m348, section3 sector 83089, scanner delta 0
# source slice: room-section3
# extract locally with: dd if=disc/extracted/PE.IMG of=original/USA/overlays/room_m348.bin bs=2048 skip=83089 count=104
# text-bank: Day 1 night: theater blaze aftermath
