name: room_m159.bin
sha1: c13dd0cba30ed3212775339101e27a52f3a747b3
options:
  basename: room_m159
  target_path: original/USA/overlays/room_m159.bin
  base_path: ../../..
  platform: psx
  compiler: GCC
  asm_path: asm/USA/overlays/room_m159
  src_path: src/overlays/room_m159
  build_path: build/USA/overlays/room_m159
  ld_script_path: linkers/USA/overlays/room_m159.ld
  undefined_funcs_auto_path: linkers/USA/overlays/undefined_funcs_auto.room_m159.txt
  symbol_addrs_path: configs/USA/overlays/sym.room_m159.txt
  undefined_syms_auto_path: linkers/USA/overlays/undefined_syms_auto.room_m159.txt
  find_file_boundaries: True
  disassemble_all: True
  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel
  generate_asm_macros_files: False
  section_order: [".rodata", ".text", ".data", ".sdata", ".sbss", ".bss"]
  subalign: 4
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: room_m159
    type: code
    start: 0x0
    vram: 0x8018EFE8
    align: 4
    subalign: 4
    bss_size: 0x0
    subsegments:
      - [0x0, asm, room_m159]
      - [0xE10, c, RoomLib_SlotSet_8018FDF8]
      - [0xE54, data]
  - [0x1E800]
# room: m159, section3 sector 45529, scanner delta 0
# source slice: room-section3
# extract locally with: dd if=disc/extracted/PE.IMG of=original/USA/overlays/room_m159.bin bs=2048 skip=45529 count=61
