name: room_m100.bin
sha1: f8170ecb482a4367793c87c27fba462804a6506c
options:
  basename: room_m100
  target_path: original/USA/overlays/room_m100.bin
  base_path: ../../..
  platform: psx
  compiler: GCC
  asm_path: asm/USA/overlays/room_m100
  src_path: src/overlays/room_m100
  build_path: build/USA/overlays/room_m100
  ld_script_path: linkers/USA/overlays/room_m100.ld
  undefined_funcs_auto_path: linkers/USA/overlays/undefined_funcs_auto.room_m100.txt
  symbol_addrs_path: configs/USA/overlays/sym.room_m100.txt
  undefined_syms_auto_path: linkers/USA/overlays/undefined_syms_auto.room_m100.txt
  find_file_boundaries: True
  disassemble_all: True
  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel
  generate_asm_macros_files: False
  section_order: [".rodata", ".text", ".data", ".sdata", ".sbss", ".bss"]
  subalign: 4
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: room_m100
    type: code
    start: 0x0
    vram: 0x80100000
    align: 4
    subalign: 4
    bss_size: 0x0
    subsegments:
      - [0x0, asm, room_m100]
      - [0x1CFC, c, RoomLib_InvokeCallbackC_80101CFC]
      - [0x1D24, asm, room_m100_1D24]
      - [0x2814, c, RoomLib_InvokeCallbackC_80102814]
      - [0x283C, asm, room_m100_1D24_283C]
      - [0x3200, c, RoomLib_InvokeCallbackC_80103200]
      - [0x3228, asm, room_m100_1D24_283C_3228]
      - [0x4184, data]
  - [0x42800]
# room: m100, section3 sector 32985, scanner delta 0
# source slice: room-section3
# extract locally with: dd if=disc/extracted/PE.IMG of=original/USA/overlays/room_m100.bin bs=2048 skip=32985 count=133
