name: room_m399.bin
sha1: d05fc006543447f413ca8cd7c1c1f2de0335c6b2
options:
  basename: room_m399
  target_path: original/USA/overlays/room_m399.bin
  base_path: ../../..
  platform: psx
  compiler: GCC
  asm_path: asm/USA/overlays/room_m399
  src_path: src/overlays/room_m399
  build_path: build/USA/overlays/room_m399
  ld_script_path: linkers/USA/overlays/room_m399.ld
  undefined_funcs_auto_path: linkers/USA/overlays/undefined_funcs_auto.room_m399.txt
  symbol_addrs_path: configs/USA/overlays/sym.room_m399.txt
  undefined_syms_auto_path: linkers/USA/overlays/undefined_syms_auto.room_m399.txt
  find_file_boundaries: True
  disassemble_all: True
  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel
  generate_asm_macros_files: False
  section_order: [".rodata", ".text", ".data", ".sdata", ".sbss", ".bss"]
  subalign: 4
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: room_m399
    type: code
    start: 0x0
    vram: 0x80100000
    align: 4
    subalign: 4
    bss_size: 0x0
    subsegments:
      - [0x0, asm, room_m399]
      - [0x2CF8, c, RoomLib_InvokeCallbackC_80102CF8]
      - [0x2D20, asm, room_m399_2D20]
      - [0x34C4, c, RoomLib_ResetAndSignal_801034C4]
      - [0x3520, asm, room_m399_2D20_3520]
      - [0x3810, c, RoomLib_InvokeCallbackC_80103810]
      - [0x3838, asm, room_m399_2D20_3838]
      - [0x40B4, c, RoomLib_ResetAndSignal_801040B4]
      - [0x4110, asm, room_m399_2D20_3838_4110]
      - [0x41FC, c, RoomLib_InvokeCallbackC_801041FC]
      - [0x4224, asm, room_m399_2D20_3838_4224]
      - [0x44E8, c, RoomLib_Set4ClearSignal_801044E8]
      - [0x4504, asm, room_m399_2D20_3838_4224_4504]
      - [0x4CD8, c, RoomLib_Set4ClearSignal_80104CD8]
      - [0x4CF4, asm, room_m399_2D20_3838_4224_4504_4CF4]
      - [0x51D8, data]
  - [0x33800]
# room: m399, section3 sector 91971, scanner delta 0
# source slice: room-section3
# extract locally with: dd if=disc/extracted/PE.IMG of=original/USA/overlays/room_m399.bin bs=2048 skip=91971 count=103
