name: room_m075.bin
sha1: ca34d1321e158763e9ee8b3cc9df0b3d94d28978
options:
  basename: room_m075
  target_path: original/USA/overlays/room_m075.bin
  base_path: ../../..
  platform: psx
  compiler: GCC
  asm_path: asm/USA/overlays/room_m075
  src_path: src/overlays/room_m075
  build_path: build/USA/overlays/room_m075
  ld_script_path: linkers/USA/overlays/room_m075.ld
  undefined_funcs_auto_path: linkers/USA/overlays/undefined_funcs_auto.room_m075.txt
  symbol_addrs_path: configs/USA/overlays/sym.room_m075.txt
  undefined_syms_auto_path: linkers/USA/overlays/undefined_syms_auto.room_m075.txt
  find_file_boundaries: True
  disassemble_all: True
  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel
  generate_asm_macros_files: False
  section_order: [".rodata", ".text", ".data", ".sdata", ".sbss", ".bss"]
  subalign: 4
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: room_m075
    type: code
    start: 0x0
    vram: 0x80100000
    align: 4
    subalign: 4
    bss_size: 0x0
    subsegments:
      - [0x0, asm, room_m075]
      - [0x3724, c, RoomLib_InvokeCallbackC_80103724]
      - [0x374C, asm, room_m075_374C]
      - [0x3EF0, c, RoomLib_ResetAndSignal_80103EF0]
      - [0x3F4C, asm, room_m075_374C_3F4C]
      - [0x423C, c, RoomLib_InvokeCallbackC_8010423C]
      - [0x4264, asm, room_m075_374C_4264]
      - [0x4AE0, c, RoomLib_ResetAndSignal_80104AE0]
      - [0x4B3C, asm, room_m075_374C_4264_4B3C]
      - [0x4C28, c, RoomLib_InvokeCallbackC_80104C28]
      - [0x4C50, asm, room_m075_374C_4264_4C50]
      - [0x4F14, c, RoomLib_Set4ClearSignal_80104F14]
      - [0x4F30, asm, room_m075_374C_4264_4C50_4F30]
      - [0x4F38, data]
  - [0x2E800]
# room: m075, section3 sector 26617, scanner delta 0
# source slice: room-section3
# extract locally with: dd if=disc/extracted/PE.IMG of=original/USA/overlays/room_m075.bin bs=2048 skip=26617 count=93
