name: room_m198.bin
sha1: a19afe55b41b1650ff872b14bc66ac030e4e7828
options:
  basename: room_m198
  target_path: original/USA/overlays/room_m198.bin
  base_path: ../../..
  platform: psx
  compiler: GCC
  asm_path: asm/USA/overlays/room_m198
  src_path: src/overlays/room_m198
  build_path: build/USA/overlays/room_m198
  ld_script_path: linkers/USA/overlays/room_m198.ld
  undefined_funcs_auto_path: linkers/USA/overlays/undefined_funcs_auto.room_m198.txt
  symbol_addrs_path: configs/USA/overlays/sym.room_m198.txt
  undefined_syms_auto_path: linkers/USA/overlays/undefined_syms_auto.room_m198.txt
  find_file_boundaries: True
  disassemble_all: True
  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel
  generate_asm_macros_files: False
  section_order: [".rodata", ".text", ".data", ".sdata", ".sbss", ".bss"]
  subalign: 4
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: room_m198
    type: code
    start: 0x0
    vram: 0x80100000
    align: 4
    subalign: 4
    bss_size: 0x0
    subsegments:
      - [0x0, asm, room_m198]
      - [0x1CEC, c, RoomLib_InvokeCallbackC_80101CEC]
      - [0x1D14, asm, room_m198_1D14]
      - [0x24B8, c, RoomLib_ResetAndSignal_801024B8]
      - [0x2514, asm, room_m198_1D14_2514]
      - [0x2804, c, RoomLib_InvokeCallbackC_80102804]
      - [0x282C, asm, room_m198_1D14_282C]
      - [0x30A8, c, RoomLib_ResetAndSignal_801030A8]
      - [0x3104, asm, room_m198_1D14_282C_3104]
      - [0x3114, c, RoomLib_InitTimers_80103114]
      - [0x3150, asm, room_m198_1D14_282C_3104_3150]
      - [0x31F0, c, RoomLib_InvokeCallbackC_801031F0]
      - [0x3218, c, RoomLib_RearmOnMatch_80103218]
      - [0x3248, asm, room_m198_1D14_282C_3218_3248]
      - [0x34DC, c, RoomLib_Set4ClearSignal_801034DC]
      - [0x34F8, asm, room_m198_1D14_282C_3218_34F8]
      - [0xD6D0, data]
  - [0x37000]
# room: m198, section3 sector 53144, scanner delta 0
# source slice: room-section3
# extract locally with: dd if=disc/extracted/PE.IMG of=original/USA/overlays/room_m198.bin bs=2048 skip=53144 count=110
