name: room_m090.bin
sha1: 1d677a8ac3a527d9b9970df9e5bc33e23f6e114c
options:
  basename: room_m090
  target_path: original/USA/overlays/room_m090.bin
  base_path: ../../..
  platform: psx
  compiler: GCC
  asm_path: asm/USA/overlays/room_m090
  src_path: src/overlays/room_m090
  build_path: build/USA/overlays/room_m090
  ld_script_path: linkers/USA/overlays/room_m090.ld
  undefined_funcs_auto_path: linkers/USA/overlays/undefined_funcs_auto.room_m090.txt
  symbol_addrs_path: configs/USA/overlays/sym.room_m090.txt
  undefined_syms_auto_path: linkers/USA/overlays/undefined_syms_auto.room_m090.txt
  find_file_boundaries: True
  disassemble_all: True
  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel
  generate_asm_macros_files: False
  section_order: [".rodata", ".text", ".data", ".sdata", ".sbss", ".bss"]
  subalign: 4
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: room_m090
    type: code
    start: 0x0
    vram: 0x8018EFE8
    align: 4
    subalign: 4
    bss_size: 0x0
    subsegments:
      - [0x0, rodata, room_m090]
      - [0x4C, c, func_8018F034]
      - [0x54, c, RoomLib_PlantTable_8018F03C]
      - [0x80, c, RoomLib_Spawn6_8018F068]
      - [0xAC, c, func_8018F094]
      - [0xD4, c, func_8018F0BC]
      - [0x144, c, func_8018F12C]
      - [0x14C, c, func_8018F134]
      - [0x154, c, func_8018F13C]
      - [0x384, c, func_8018F36C]
      - [0x38C, asm, room_m090_38C]
      - [0x13C0, c, func_801903A8]
      - [0x1440, c, func_80190428]
      - [0x1880, asm, func_80190868]
      - [0x1C10, c, func_80190BF8]
      - [0x1CC8, c, func_80190CB0]
      - [0x2158, asm, func_80191140]
      - [0x2508, c, func_801914F0]
      - [0x25C0, c, func_801915A8]
      - [0x2970, asm, func_80191958]
      - [0x2CAC, c, func_80191C94]
      - [0x2D5C, c, func_80191D44]
      - [0x3190, asm, func_80192178]
      - [0x34AC, c, func_80192494]
      - [0x34B4, c, func_8019249C]
      - [0x3698, c, func_80192680]
      - [0x36A0, c, func_80192688]
      - [0x37AC, c, func_80192794]
      - [0x39C8, asm, func_801929B0]
      - [0x3B74, data]
  - [0x3C000]
# room: m090, section3 sector 30303, scanner delta 0
# source slice: room-section3
# extract locally with: dd if=disc/extracted/PE.IMG of=original/USA/overlays/room_m090.bin bs=2048 skip=30303 count=120
# text-bank: Day 3 morning (Daniel & Maeda)
