name: room_m169.bin
sha1: 1dc3c3fe3e3b2a3c55cf746157351a80919d5ab5
options:
  basename: room_m169
  target_path: original/USA/overlays/room_m169.bin
  base_path: ../../..
  platform: psx
  compiler: GCC
  asm_path: asm/USA/overlays/room_m169
  src_path: src/overlays/room_m169
  build_path: build/USA/overlays/room_m169
  ld_script_path: linkers/USA/overlays/room_m169.ld
  undefined_funcs_auto_path: linkers/USA/overlays/undefined_funcs_auto.room_m169.txt
  undefined_syms_auto_path: linkers/USA/overlays/undefined_syms_auto.room_m169.txt
  find_file_boundaries: True
  disassemble_all: True
  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel
  generate_asm_macros_files: False
  section_order: [".rodata", ".text", ".data", ".sdata", ".sbss", ".bss"]
  subalign: 4
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: room_m169
    type: code
    start: 0x0
    vram: 0x80100000
    align: 4
    subalign: 4
    bss_size: 0x0
    subsegments:
      - [0x0, asm, room_m169]
  - [0x2A000]
# room: m169, section3 sector 47781, scanner delta 0
# source slice: room-section3
# extract locally with: dd if=disc/extracted/PE.IMG of=original/USA/overlays/room_m169.bin bs=2048 skip=47781 count=84
