name: room_m406.bin
sha1: 7a81d019648d27f135ce93375533c5189cd33ea9
options:
  basename: room_m406
  target_path: original/USA/overlays/room_m406.bin
  base_path: ../../..
  platform: psx
  compiler: GCC
  asm_path: asm/USA/overlays/room_m406
  src_path: src/overlays/room_m406
  build_path: build/USA/overlays/room_m406
  ld_script_path: linkers/USA/overlays/room_m406.ld
  undefined_funcs_auto_path: linkers/USA/overlays/undefined_funcs_auto.room_m406.txt
  symbol_addrs_path: configs/USA/overlays/sym.room_m406.txt
  undefined_syms_auto_path: linkers/USA/overlays/undefined_syms_auto.room_m406.txt
  find_file_boundaries: True
  disassemble_all: True
  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel
  generate_asm_macros_files: False
  section_order: [".rodata", ".text", ".data", ".sdata", ".sbss", ".bss"]
  subalign: 4
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: room_m406
    type: code
    start: 0x0
    vram: 0x80100000
    align: 4
    subalign: 4
    bss_size: 0x0
    subsegments:
      - [0x0, asm, room_m406]
      - [0x1CF8, c, RoomLib_InvokeCallbackC_80101CF8]
      - [0x1D20, asm, room_m406_1D20]
      - [0x24C4, c, RoomLib_ResetAndSignal_801024C4]
      - [0x2520, asm, room_m406_1D20_2520]
      - [0x2810, c, RoomLib_InvokeCallbackC_80102810]
      - [0x2838, asm, room_m406_1D20_2838]
      - [0x30B4, c, RoomLib_ResetAndSignal_801030B4]
      - [0x3110, asm, room_m406_1D20_2838_3110]
      - [0x3120, c, RoomLib_InitTimers_80103120]
      - [0x315C, asm, room_m406_1D20_2838_3110_315C]
      - [0x31FC, c, RoomLib_InvokeCallbackC_801031FC]
      - [0x3224, c, RoomLib_RearmOnMatch_80103224]
      - [0x3254, asm, room_m406_1D20_2838_3224_3254]
      - [0x34E8, c, RoomLib_Set4ClearSignal_801034E8]
      - [0x3504, asm, room_m406_1D20_2838_3224_3504]
      - [0x3C50, data]
  - [0x2D800]
# room: m406, section3 sector 93497, scanner delta 0
# source slice: room-section3
# extract locally with: dd if=disc/extracted/PE.IMG of=original/USA/overlays/room_m406.bin bs=2048 skip=93497 count=91
