name: room_m387.bin
sha1: fab929c68f9c011186fa9cfbfbd48db6c63bb5cd
options:
  basename: room_m387
  target_path: original/USA/overlays/room_m387.bin
  base_path: ../../..
  platform: psx
  compiler: GCC
  asm_path: asm/USA/overlays/room_m387
  src_path: src/overlays/room_m387
  build_path: build/USA/overlays/room_m387
  ld_script_path: linkers/USA/overlays/room_m387.ld
  undefined_funcs_auto_path: linkers/USA/overlays/undefined_funcs_auto.room_m387.txt
  symbol_addrs_path: configs/USA/overlays/sym.room_m387.txt
  undefined_syms_auto_path: linkers/USA/overlays/undefined_syms_auto.room_m387.txt
  find_file_boundaries: True
  disassemble_all: True
  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel
  generate_asm_macros_files: False
  section_order: [".rodata", ".text", ".data", ".sdata", ".sbss", ".bss"]
  subalign: 4
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: room_m387
    type: code
    start: 0x0
    vram: 0x80100000
    align: 4
    subalign: 4
    bss_size: 0x0
    subsegments:
      - [0x0, asm, room_m387]
      - [0x1D4C, c, RoomLib_InvokeCallbackC_80101D4C]
      - [0x1D74, asm, room_m387_1D74]
      - [0x2518, c, RoomLib_ResetAndSignal_80102518]
      - [0x2574, asm, room_m387_1D74_2574]
      - [0x2864, c, RoomLib_InvokeCallbackC_80102864]
      - [0x288C, asm, room_m387_1D74_288C]
      - [0x3108, c, RoomLib_ResetAndSignal_80103108]
      - [0x3164, asm, room_m387_1D74_288C_3164]
      - [0x3174, c, RoomLib_InitTimers_80103174]
      - [0x31B0, asm, room_m387_1D74_288C_3164_31B0]
      - [0x3250, c, RoomLib_InvokeCallbackC_80103250]
      - [0x3278, c, RoomLib_RearmOnMatch_80103278]
      - [0x32A8, asm, room_m387_1D74_288C_3278_32A8]
      - [0x353C, c, RoomLib_Set4ClearSignal_8010353C]
      - [0x3558, asm, room_m387_1D74_288C_3278_3558]
      - [0x12680, data]
  - [0x22000]
# room: m387, section3 sector 89413, scanner delta 0
# source slice: room-section3
# extract locally with: dd if=disc/extracted/PE.IMG of=original/USA/overlays/room_m387.bin bs=2048 skip=89413 count=68
