name: room_m113.bin
sha1: f55e2fa3c9c13b158e03cbd30c9677b69e141422
options:
  basename: room_m113
  target_path: original/USA/overlays/room_m113.bin
  base_path: ../../..
  platform: psx
  compiler: GCC
  asm_path: asm/USA/overlays/room_m113
  src_path: src/overlays/room_m113
  build_path: build/USA/overlays/room_m113
  ld_script_path: linkers/USA/overlays/room_m113.ld
  undefined_funcs_auto_path: linkers/USA/overlays/undefined_funcs_auto.room_m113.txt
  symbol_addrs_path: configs/USA/overlays/sym.room_m113.txt
  undefined_syms_auto_path: linkers/USA/overlays/undefined_syms_auto.room_m113.txt
  find_file_boundaries: True
  disassemble_all: True
  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel
  generate_asm_macros_files: False
  section_order: [".rodata", ".text", ".data", ".sdata", ".sbss", ".bss"]
  subalign: 4
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: room_m113
    type: code
    start: 0x0
    vram: 0x8018EFE8
    align: 4
    subalign: 4
    bss_size: 0x0
    subsegments:
      - [0x0, asm, room_m113]
      - [0xC80, c, RoomLib_SetArgs3_8018FC68]
      - [0xCA4, asm, room_m113_CA4]
      - [0x1A94, c, RoomLib_SlotSet_80190A7C]
      - [0x1AD8, asm, room_m113_CA4_1AD8]
      - [0x16F90, data]
  - [0x2E000]
# room: m113, section3 sector 35200, scanner delta 0
# source slice: room-section3
# extract locally with: dd if=disc/extracted/PE.IMG of=original/USA/overlays/room_m113.bin bs=2048 skip=35200 count=92
# text-bank: Day 1 night: theater blaze aftermath
