name: room_m028.bin
sha1: 47a298d84aad055727271a924b9fb846c4dbb3cc
options:
  basename: room_m028
  target_path: original/USA/overlays/room_m028.bin
  base_path: ../../..
  platform: psx
  compiler: GCC
  asm_path: asm/USA/overlays/room_m028
  src_path: src/overlays/room_m028
  build_path: build/USA/overlays/room_m028
  ld_script_path: linkers/USA/overlays/room_m028.ld
  undefined_funcs_auto_path: linkers/USA/overlays/undefined_funcs_auto.room_m028.txt
  symbol_addrs_path: configs/USA/overlays/sym.room_m028.txt
  undefined_syms_auto_path: linkers/USA/overlays/undefined_syms_auto.room_m028.txt
  find_file_boundaries: True
  disassemble_all: True
  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel
  generate_asm_macros_files: False
  section_order: [".rodata", ".text", ".data", ".sdata", ".sbss", ".bss"]
  subalign: 4
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: room_m028
    type: code
    start: 0x0
    vram: 0x80100000
    align: 4
    subalign: 4
    bss_size: 0x0
    subsegments:
      - [0x0, asm, room_m028]
      - [0x1FC, c, RoomLib_InitB_801001FC]
      - [0x29C, asm, room_m028_29C]
      - [0x5B0, c, RoomLib_NotifyArmB_801005B0]
      - [0x658, asm, room_m028_658]
      - [0x12F0, c, RoomLib_Notify2ArmB_801012F0]
      - [0x1398, asm, room_m028_658_1398]
      - [0x19A8, c, RoomLib_ResetAndSignalB_801019A8]
      - [0x1A00, asm, room_m028_1A00]
      - [0x1A10, c, RoomLib_InitC_80101A10]
      - [0x1AAC, asm, room_m028_1A00_1AAC]
      - [0x1CFC, c, RoomLib_InvokeCallbackC_80101CFC]
      - [0x1D24, c, RoomLib_ArmWindowA_80101D24]
      - [0x1D94, asm, room_m028_1D24_1D94]
      - [0x24C8, c, RoomLib_ResetAndSignal_801024C8]
      - [0x2524, asm, room_m028_1D24_2524]
      - [0x2534, c, RoomLib_InitFull_80102534]
      - [0x25C4, asm, room_m028_1D24_2524_25C4]
      - [0x2814, c, RoomLib_InvokeCallbackC_80102814]
      - [0x283C, c, RoomLib_ArmWindowB_8010283C]
      - [0x28AC, asm, room_m028_1D24_283C_28AC]
      - [0x30B8, c, RoomLib_ResetAndSignal_801030B8]
      - [0x3114, asm, room_m028_1D24_283C_3114]
      - [0x3124, c, RoomLib_InitTimers_80103124]
      - [0x3160, asm, room_m028_1D24_283C_3114_3160]
      - [0x3200, c, RoomLib_InvokeCallbackC_80103200]
      - [0x3228, c, RoomLib_RearmOnMatch_80103228]
      - [0x3258, asm, room_m028_1D24_283C_3228_3258]
      - [0x34EC, c, RoomLib_Set4ClearSignal_801034EC]
      - [0x3508, asm, room_m028_1D24_283C_3228_3508]
      - [0x14F50, data]
  - [0x22800]
# room: m028, section3 sector 14003, scanner delta 0
# source slice: room-section3
# extract locally with: dd if=disc/extracted/PE.IMG of=original/USA/overlays/room_m028.bin bs=2048 skip=14003 count=69
