name: room_m233.bin
sha1: 5a05defb53820a98fa8917438eca265c9bbe3183
options:
  basename: room_m233
  target_path: original/USA/overlays/room_m233.bin
  base_path: ../../..
  platform: psx
  compiler: GCC
  asm_path: asm/USA/overlays/room_m233
  src_path: src/overlays/room_m233
  build_path: build/USA/overlays/room_m233
  ld_script_path: linkers/USA/overlays/room_m233.ld
  undefined_funcs_auto_path: linkers/USA/overlays/undefined_funcs_auto.room_m233.txt
  symbol_addrs_path: configs/USA/overlays/sym.room_m233.txt
  undefined_syms_auto_path: linkers/USA/overlays/undefined_syms_auto.room_m233.txt
  find_file_boundaries: True
  disassemble_all: True
  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel
  generate_asm_macros_files: False
  section_order: [".rodata", ".text", ".data", ".sdata", ".sbss", ".bss"]
  subalign: 4
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: room_m233
    type: code
    start: 0x0
    vram: 0x80100000
    align: 4
    subalign: 4
    bss_size: 0x0
    subsegments:
      - [0x0, asm, room_m233]
      - [0x240, c, RoomLib_InitB_80100240]
      - [0x2E0, asm, room_m233_2E0]
      - [0x5F4, c, RoomLib_NotifyArmB_801005F4]
      - [0x69C, asm, room_m233_69C]
      - [0xFB0, c, RoomLib_InitD_80100FB0]
      - [0x102C, asm, room_m233_69C_102C]
      - [0x1334, c, RoomLib_Notify2ArmB_80101334]
      - [0x13DC, asm, room_m233_69C_13DC]
      - [0x1968, c, RoomLib_SteerToward_80101968]
      - [0x19EC, c, RoomLib_ResetAndSignalB_801019EC]
      - [0x1A44, asm, room_m233_1A44]
      - [0x1A54, c, RoomLib_InitC_80101A54]
      - [0x1AF0, asm, room_m233_1A44_1AF0]
      - [0x1D40, c, RoomLib_InvokeCallbackC_80101D40]
      - [0x1D68, c, RoomLib_ArmWindowA_80101D68]
      - [0x1DD8, asm, room_m233_1D68_1DD8]
      - [0x250C, c, RoomLib_ResetAndSignal_8010250C]
      - [0x2568, asm, room_m233_1D68_2568]
      - [0x2578, c, RoomLib_InitFull_80102578]
      - [0x2608, asm, room_m233_1D68_2568_2608]
      - [0x2858, c, RoomLib_InvokeCallbackC_80102858]
      - [0x2880, c, RoomLib_ArmWindowB_80102880]
      - [0x28F0, asm, room_m233_1D68_2880_28F0]
      - [0x30FC, c, RoomLib_ResetAndSignal_801030FC]
      - [0x3158, asm, room_m233_1D68_2880_3158]
      - [0x3168, c, RoomLib_InitTimers_80103168]
      - [0x31A4, asm, room_m233_1D68_2880_3158_31A4]
      - [0x3244, c, RoomLib_InvokeCallbackC_80103244]
      - [0x326C, c, RoomLib_RearmOnMatch_8010326C]
      - [0x329C, asm, room_m233_1D68_2880_326C_329C]
      - [0x3530, c, RoomLib_Set4ClearSignal_80103530]
      - [0x354C, asm, room_m233_1D68_2880_326C_354C]
      - [0x4FE8, data]
  - [0x32800]
# room: m233, section3 sector 60943, scanner delta 0
# source slice: room-section3
# extract locally with: dd if=disc/extracted/PE.IMG of=original/USA/overlays/room_m233.bin bs=2048 skip=60943 count=101
