name: room_m308.bin
sha1: de69477b06888967afd62e9737781f4efa52ecd1
options:
  basename: room_m308
  target_path: original/USA/overlays/room_m308.bin
  base_path: ../../..
  platform: psx
  compiler: GCC
  asm_path: asm/USA/overlays/room_m308
  src_path: src/overlays/room_m308
  build_path: build/USA/overlays/room_m308
  ld_script_path: linkers/USA/overlays/room_m308.ld
  undefined_funcs_auto_path: linkers/USA/overlays/undefined_funcs_auto.room_m308.txt
  symbol_addrs_path: configs/USA/overlays/sym.room_m308.txt
  undefined_syms_auto_path: linkers/USA/overlays/undefined_syms_auto.room_m308.txt
  find_file_boundaries: True
  disassemble_all: True
  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel
  generate_asm_macros_files: False
  section_order: [".rodata", ".text", ".data", ".sdata", ".sbss", ".bss"]
  subalign: 4
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: room_m308
    type: code
    start: 0x0
    vram: 0x80100000
    align: 4
    subalign: 4
    bss_size: 0x0
    subsegments:
      - [0x0, asm, room_m308]
      - [0x1CFC, c, RoomLib_InvokeCallbackC_80101CFC]
      - [0x1D24, asm, room_m308_1D24]
      - [0x24C8, c, RoomLib_ResetAndSignal_801024C8]
      - [0x2524, asm, room_m308_1D24_2524]
      - [0x2814, c, RoomLib_InvokeCallbackC_80102814]
      - [0x283C, asm, room_m308_1D24_283C]
      - [0x30B8, c, RoomLib_ResetAndSignal_801030B8]
      - [0x3114, asm, room_m308_1D24_283C_3114]
      - [0x3124, c, RoomLib_InitTimers_80103124]
      - [0x3160, asm, room_m308_1D24_283C_3114_3160]
      - [0x3200, c, RoomLib_InvokeCallbackC_80103200]
      - [0x3228, c, RoomLib_RearmOnMatch_80103228]
      - [0x3258, asm, room_m308_1D24_283C_3228_3258]
      - [0x34EC, c, RoomLib_Set4ClearSignal_801034EC]
      - [0x3508, asm, room_m308_1D24_283C_3228_3508]
      - [0x4184, data]
  - [0x1D800]
# room: m308, section3 sector 75560, scanner delta 0
# source slice: room-section3
# extract locally with: dd if=disc/extracted/PE.IMG of=original/USA/overlays/room_m308.bin bs=2048 skip=75560 count=59
