name: room_m401.bin
sha1: 19d2caf765e89732886d5034b92d78fd12a3e441
options:
  basename: room_m401
  target_path: original/USA/overlays/room_m401.bin
  base_path: ../../..
  platform: psx
  compiler: GCC
  asm_path: asm/USA/overlays/room_m401
  src_path: src/overlays/room_m401
  build_path: build/USA/overlays/room_m401
  ld_script_path: linkers/USA/overlays/room_m401.ld
  undefined_funcs_auto_path: linkers/USA/overlays/undefined_funcs_auto.room_m401.txt
  symbol_addrs_path: configs/USA/overlays/sym.room_m401.txt
  undefined_syms_auto_path: linkers/USA/overlays/undefined_syms_auto.room_m401.txt
  find_file_boundaries: True
  disassemble_all: True
  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel
  generate_asm_macros_files: False
  section_order: [".rodata", ".text", ".data", ".sdata", ".sbss", ".bss"]
  subalign: 4
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: room_m401
    type: code
    start: 0x0
    vram: 0x80100000
    align: 4
    subalign: 4
    bss_size: 0x0
    subsegments:
      - [0x0, asm, room_m401]
      - [0x3AF8, c, RoomLib_ResetAndSignalB_80103AF8]
      - [0x3B50, asm, room_m401_3B50]
      - [0x3E4C, c, RoomLib_InvokeCallbackC_80103E4C]
      - [0x3E74, asm, room_m401_3E74]
      - [0x4618, c, RoomLib_ResetAndSignal_80104618]
      - [0x4674, asm, room_m401_3E74_4674]
      - [0x4684, c, RoomLib_InitFull_80104684]
      - [0x4714, asm, room_m401_3E74_4674_4714]
      - [0x4964, c, RoomLib_InvokeCallbackC_80104964]
      - [0x498C, asm, room_m401_3E74_498C]
      - [0x5208, c, RoomLib_ResetAndSignal_80105208]
      - [0x5264, asm, room_m401_3E74_498C_5264]
      - [0x5274, c, RoomLib_InitTimers_80105274]
      - [0x52B0, asm, room_m401_3E74_498C_5264_52B0]
      - [0x5350, c, RoomLib_InvokeCallbackC_80105350]
      - [0x5378, c, RoomLib_RearmOnMatch_80105378]
      - [0x53A8, asm, room_m401_3E74_498C_5378_53A8]
      - [0x563C, c, RoomLib_Set4ClearSignal_8010563C]
      - [0x5658, asm, room_m401_3E74_498C_5378_5658]
      - [0x5E2C, c, RoomLib_Set4ClearSignal_80105E2C]
      - [0x5E48, asm, room_m401_3E74_498C_5378_5658_5E48]
      - [0x632C, data]
  - [0x46800]
# room: m401, section3 sector 92367, scanner delta 0
# source slice: room-section3
# extract locally with: dd if=disc/extracted/PE.IMG of=original/USA/overlays/room_m401.bin bs=2048 skip=92367 count=141
