name: room_m163.bin
sha1: 80450a0f761b672d79ae914357ec5d202cae8059
options:
  basename: room_m163
  target_path: original/USA/overlays/room_m163.bin
  base_path: ../../..
  platform: psx
  compiler: GCC
  asm_path: asm/USA/overlays/room_m163
  src_path: src/overlays/room_m163
  build_path: build/USA/overlays/room_m163
  ld_script_path: linkers/USA/overlays/room_m163.ld
  undefined_funcs_auto_path: linkers/USA/overlays/undefined_funcs_auto.room_m163.txt
  symbol_addrs_path: configs/USA/overlays/sym.room_m163.txt
  undefined_syms_auto_path: linkers/USA/overlays/undefined_syms_auto.room_m163.txt
  find_file_boundaries: True
  disassemble_all: True
  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel
  generate_asm_macros_files: False
  section_order: [".rodata", ".text", ".data", ".sdata", ".sbss", ".bss"]
  subalign: 4
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: room_m163
    type: code
    start: 0x0
    vram: 0x80100000
    align: 4
    subalign: 4
    bss_size: 0x0
    subsegments:
      - [0x0, asm, room_m163]
      - [0x200, c, RoomLib_InitB_80100200]
      - [0x2A0, asm, room_m163_2A0]
      - [0x5B4, c, RoomLib_NotifyArmB_801005B4]
      - [0x65C, asm, room_m163_65C]
      - [0xF70, c, RoomLib_InitD_80100F70]
      - [0xFEC, asm, room_m163_65C_FEC]
      - [0x12F4, c, RoomLib_Notify2ArmB_801012F4]
      - [0x139C, asm, room_m163_65C_139C]
      - [0x1928, c, RoomLib_SteerToward_80101928]
      - [0x19AC, c, RoomLib_ResetAndSignalB_801019AC]
      - [0x1A04, asm, room_m163_1A04]
      - [0x1A14, c, RoomLib_InitC_80101A14]
      - [0x1AB0, asm, room_m163_1A04_1AB0]
      - [0x1D00, c, RoomLib_InvokeCallbackC_80101D00]
      - [0x1D28, c, RoomLib_ArmWindowA_80101D28]
      - [0x1D98, asm, room_m163_1D28_1D98]
      - [0x24CC, c, RoomLib_ResetAndSignal_801024CC]
      - [0x2528, asm, room_m163_1D28_2528]
      - [0x2538, c, RoomLib_InitFull_80102538]
      - [0x25C8, asm, room_m163_1D28_2528_25C8]
      - [0x2818, c, RoomLib_InvokeCallbackC_80102818]
      - [0x2840, c, RoomLib_ArmWindowB_80102840]
      - [0x28B0, asm, room_m163_1D28_2840_28B0]
      - [0x30BC, c, RoomLib_ResetAndSignal_801030BC]
      - [0x3118, asm, room_m163_1D28_2840_3118]
      - [0x3128, c, RoomLib_InitTimers_80103128]
      - [0x3164, asm, room_m163_1D28_2840_3118_3164]
      - [0x3204, c, RoomLib_InvokeCallbackC_80103204]
      - [0x322C, c, RoomLib_RearmOnMatch_8010322C]
      - [0x325C, asm, room_m163_1D28_2840_322C_325C]
      - [0x34F0, c, RoomLib_Set4ClearSignal_801034F0]
      - [0x350C, asm, room_m163_1D28_2840_322C_350C]
      - [0x4130, c, RoomLib_SetArgs3_80104130]
      - [0x4154, data]
  - [0x36000]
# room: m163, section3 sector 46406, scanner delta 0
# source slice: room-section3
# extract locally with: dd if=disc/extracted/PE.IMG of=original/USA/overlays/room_m163.bin bs=2048 skip=46406 count=108
