name: room_m396.bin
sha1: e506340919a93f75f6d51ae8ca874925cafa3be7
options:
  basename: room_m396
  target_path: original/USA/overlays/room_m396.bin
  base_path: ../../..
  platform: psx
  compiler: GCC
  asm_path: asm/USA/overlays/room_m396
  src_path: src/overlays/room_m396
  build_path: build/USA/overlays/room_m396
  ld_script_path: linkers/USA/overlays/room_m396.ld
  undefined_funcs_auto_path: linkers/USA/overlays/undefined_funcs_auto.room_m396.txt
  symbol_addrs_path: configs/USA/overlays/sym.room_m396.txt
  undefined_syms_auto_path: linkers/USA/overlays/undefined_syms_auto.room_m396.txt
  find_file_boundaries: True
  disassemble_all: True
  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel
  generate_asm_macros_files: False
  section_order: [".rodata", ".text", ".data", ".sdata", ".sbss", ".bss"]
  subalign: 4
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: room_m396
    type: code
    start: 0x0
    vram: 0x80100000
    align: 4
    subalign: 4
    bss_size: 0x0
    subsegments:
      - [0x0, asm, room_m396]
      - [0x26F8, c, RoomLib_NotifyArmB_801026F8]
      - [0x27A0, asm, room_m396_27A0]
      - [0x3AF0, c, RoomLib_ResetAndSignalB_80103AF0]
      - [0x3B48, asm, room_m396_3B48]
      - [0x3E44, c, RoomLib_InvokeCallbackC_80103E44]
      - [0x3E6C, c, RoomLib_ArmWindowA_80103E6C]
      - [0x3EDC, asm, room_m396_3E6C_3EDC]
      - [0x4610, c, RoomLib_ResetAndSignal_80104610]
      - [0x466C, asm, room_m396_3E6C_466C]
      - [0x467C, c, RoomLib_InitFull_8010467C]
      - [0x470C, asm, room_m396_3E6C_466C_470C]
      - [0x495C, c, RoomLib_InvokeCallbackC_8010495C]
      - [0x4984, c, RoomLib_ArmWindowB_80104984]
      - [0x49F4, asm, room_m396_3E6C_4984_49F4]
      - [0x5200, c, RoomLib_ResetAndSignal_80105200]
      - [0x525C, asm, room_m396_3E6C_4984_525C]
      - [0x526C, c, RoomLib_InitTimers_8010526C]
      - [0x52A8, asm, room_m396_3E6C_4984_525C_52A8]
      - [0x5348, c, RoomLib_InvokeCallbackC_80105348]
      - [0x5370, c, RoomLib_RearmOnMatch_80105370]
      - [0x53A0, asm, room_m396_3E6C_4984_5370_53A0]
      - [0x5634, c, RoomLib_Set4ClearSignal_80105634]
      - [0x5650, asm, room_m396_3E6C_4984_5370_5650]
      - [0x5658, data]
  - [0x35000]
# room: m396, section3 sector 91250, scanner delta 0
# source slice: room-section3
# extract locally with: dd if=disc/extracted/PE.IMG of=original/USA/overlays/room_m396.bin bs=2048 skip=91250 count=106
