name: room_m152.bin
sha1: 3f71f680b594ffbcb7a2f1364a8ef33152bda33d
options:
  basename: room_m152
  target_path: original/USA/overlays/room_m152.bin
  base_path: ../../..
  platform: psx
  compiler: GCC
  asm_path: asm/USA/overlays/room_m152
  src_path: src/overlays/room_m152
  build_path: build/USA/overlays/room_m152
  ld_script_path: linkers/USA/overlays/room_m152.ld
  undefined_funcs_auto_path: linkers/USA/overlays/undefined_funcs_auto.room_m152.txt
  symbol_addrs_path: configs/USA/overlays/sym.room_m152.txt
  undefined_syms_auto_path: linkers/USA/overlays/undefined_syms_auto.room_m152.txt
  find_file_boundaries: True
  disassemble_all: True
  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel
  generate_asm_macros_files: False
  section_order: [".rodata", ".text", ".data", ".sdata", ".sbss", ".bss"]
  subalign: 4
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: room_m152
    type: code
    start: 0x0
    vram: 0x80100000
    align: 4
    subalign: 4
    bss_size: 0x0
    subsegments:
      - [0x0, asm, room_m152]
      - [0x19E4, c, RoomLib_ResetAndSignalB_801019E4]
      - [0x1A3C, asm, room_m152_1A3C]
      - [0x1D38, c, RoomLib_InvokeCallbackC_80101D38]
      - [0x1D60, asm, room_m152_1D60]
      - [0x2504, c, RoomLib_ResetAndSignal_80102504]
      - [0x2560, asm, room_m152_1D60_2560]
      - [0x2570, c, RoomLib_InitFull_80102570]
      - [0x2600, asm, room_m152_1D60_2560_2600]
      - [0x2850, c, RoomLib_InvokeCallbackC_80102850]
      - [0x2878, asm, room_m152_1D60_2878]
      - [0x30F4, c, RoomLib_ResetAndSignal_801030F4]
      - [0x3150, asm, room_m152_1D60_2878_3150]
      - [0x3160, c, RoomLib_InitTimers_80103160]
      - [0x319C, asm, room_m152_1D60_2878_3150_319C]
      - [0x323C, c, RoomLib_InvokeCallbackC_8010323C]
      - [0x3264, c, RoomLib_RearmOnMatch_80103264]
      - [0x3294, asm, room_m152_1D60_2878_3264_3294]
      - [0x3528, c, RoomLib_Set4ClearSignal_80103528]
      - [0x3544, asm, room_m152_1D60_2878_3264_3544]
      - [0x3D18, c, RoomLib_Set4ClearSignal_80103D18]
      - [0x3D34, asm, room_m152_1D60_2878_3264_3544_3D34]
      - [0x4EBC, data]
  - [0x40000]
# room: m152, section3 sector 43677, scanner delta 0
# source slice: room-section3
# extract locally with: dd if=disc/extracted/PE.IMG of=original/USA/overlays/room_m152.bin bs=2048 skip=43677 count=128
