name: room_m386.bin
sha1: 0028b48e771fb9aea114d70b7a7734991886a540
options:
  basename: room_m386
  target_path: original/USA/overlays/room_m386.bin
  base_path: ../../..
  platform: psx
  compiler: GCC
  asm_path: asm/USA/overlays/room_m386
  src_path: src/overlays/room_m386
  build_path: build/USA/overlays/room_m386
  ld_script_path: linkers/USA/overlays/room_m386.ld
  undefined_funcs_auto_path: linkers/USA/overlays/undefined_funcs_auto.room_m386.txt
  symbol_addrs_path: configs/USA/overlays/sym.room_m386.txt
  undefined_syms_auto_path: linkers/USA/overlays/undefined_syms_auto.room_m386.txt
  find_file_boundaries: True
  disassemble_all: True
  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel
  generate_asm_macros_files: False
  section_order: [".rodata", ".text", ".data", ".sdata", ".sbss", ".bss"]
  subalign: 4
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: room_m386
    type: code
    start: 0x0
    vram: 0x80100000
    align: 4
    subalign: 4
    bss_size: 0x0
    subsegments:
      - [0x0, asm, room_m386]
      - [0x1CEC, c, RoomLib_InvokeCallbackC_80101CEC]
      - [0x1D14, asm, room_m386_1D14]
      - [0x24B8, c, RoomLib_ResetAndSignal_801024B8]
      - [0x2514, asm, room_m386_1D14_2514]
      - [0x2804, c, RoomLib_InvokeCallbackC_80102804]
      - [0x282C, asm, room_m386_1D14_282C]
      - [0x30A8, c, RoomLib_ResetAndSignal_801030A8]
      - [0x3104, asm, room_m386_1D14_282C_3104]
      - [0x31F0, c, RoomLib_InvokeCallbackC_801031F0]
      - [0x3218, asm, room_m386_1D14_282C_3218]
      - [0x34DC, c, RoomLib_Set4ClearSignal_801034DC]
      - [0x34F8, asm, room_m386_1D14_282C_3218_34F8]
      - [0x3500, data]
  - [0x12800]
# room: m386, section3 sector 89285, scanner delta 0
# source slice: room-section3
# extract locally with: dd if=disc/extracted/PE.IMG of=original/USA/overlays/room_m386.bin bs=2048 skip=89285 count=37
