name: room_m269.bin
sha1: 06c90576dba22ef80781421d5e9c0e802c0a339a
options:
  basename: room_m269
  target_path: original/USA/overlays/room_m269.bin
  base_path: ../../..
  platform: psx
  compiler: GCC
  asm_path: asm/USA/overlays/room_m269
  src_path: src/overlays/room_m269
  build_path: build/USA/overlays/room_m269
  ld_script_path: linkers/USA/overlays/room_m269.ld
  undefined_funcs_auto_path: linkers/USA/overlays/undefined_funcs_auto.room_m269.txt
  symbol_addrs_path: configs/USA/overlays/sym.room_m269.txt
  undefined_syms_auto_path: linkers/USA/overlays/undefined_syms_auto.room_m269.txt
  find_file_boundaries: True
  disassemble_all: True
  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel
  generate_asm_macros_files: False
  section_order: [".rodata", ".text", ".data", ".sdata", ".sbss", ".bss"]
  subalign: 4
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: room_m269
    type: code
    start: 0x0
    vram: 0x8018EFE8
    align: 4
    subalign: 4
    bss_size: 0x0
    subsegments:
      - [0x0, rodata, room_m269_header]
      - [0x78, c, func_8018F060]
      - [0x9C, c, func_8018F084]
      - [0x148, c, func_8018F130]
      - [0x150, c, RoomLib_InvokeCallbackC_8018F138]
      - [0x178, asm, room_m269_178]
      - [0x810, c, func_8018F7F8]
      - [0x818, asm, room_m269_178_818]
      - [0x31A4, c, RoomLib_SetArg1_8019218C]
      - [0x31B4, c, func_8019219C]
      - [0x31C4, c, RoomLib_SetPair_801921AC]
      - [0x31E0, data]
  - [0x42000]
# room: m269, section3 sector 68914, scanner delta 0
# source slice: room-section3
# extract locally with: dd if=disc/extracted/PE.IMG of=original/USA/overlays/room_m269.bin bs=2048 skip=68914 count=132
# text-bank: Day 4: Pier No.4 Warehouse
