name: room_m374.bin
sha1: 5c126716ed95af7ccc8ee79676ed52a9033f1a30
options:
  basename: room_m374
  target_path: original/USA/overlays/room_m374.bin
  base_path: ../../..
  platform: psx
  compiler: GCC
  asm_path: asm/USA/overlays/room_m374
  src_path: src/overlays/room_m374
  build_path: build/USA/overlays/room_m374
  ld_script_path: linkers/USA/overlays/room_m374.ld
  undefined_funcs_auto_path: linkers/USA/overlays/undefined_funcs_auto.room_m374.txt
  symbol_addrs_path: configs/USA/overlays/sym.room_m374.txt
  undefined_syms_auto_path: linkers/USA/overlays/undefined_syms_auto.room_m374.txt
  find_file_boundaries: True
  disassemble_all: True
  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel
  generate_asm_macros_files: False
  section_order: [".rodata", ".text", ".data", ".sdata", ".sbss", ".bss"]
  subalign: 4
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: room_m374
    type: code
    start: 0x0
    vram: 0x80100000
    align: 4
    subalign: 4
    bss_size: 0x0
    subsegments:
      - [0x0, asm, room_m374]
      - [0x54, c, RoomLib_PlantTable_80100054]
      - [0x80, c, RoomLib_Spawn6_80100080]
      - [0xAC, asm, room_m374_AC]
      - [0x3B74, data]
  - [0x3E800]
# room: m374, section3 sector 87379, scanner delta 0
# source slice: room-section3
# extract locally with: dd if=disc/extracted/PE.IMG of=original/USA/overlays/room_m374.bin bs=2048 skip=87379 count=125
