name: room_m118.bin
sha1: 827f762d6318105a40ca5d9ea59e4bedc46c4924
options:
  basename: room_m118
  target_path: original/USA/overlays/room_m118.bin
  base_path: ../../..
  platform: psx
  compiler: GCC
  asm_path: asm/USA/overlays/room_m118
  src_path: src/overlays/room_m118
  build_path: build/USA/overlays/room_m118
  ld_script_path: linkers/USA/overlays/room_m118.ld
  undefined_funcs_auto_path: linkers/USA/overlays/undefined_funcs_auto.room_m118.txt
  symbol_addrs_path: configs/USA/overlays/sym.room_m118.txt
  undefined_syms_auto_path: linkers/USA/overlays/undefined_syms_auto.room_m118.txt
  find_file_boundaries: True
  disassemble_all: True
  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel
  generate_asm_macros_files: False
  section_order: [".rodata", ".text", ".data", ".sdata", ".sbss", ".bss"]
  subalign: 4
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: room_m118
    type: code
    start: 0x0
    vram: 0x8018EFE8
    align: 4
    subalign: 4
    bss_size: 0x0
    subsegments:
      - [0x0, rodata, room_m118]
      - [0x14, c, func_8018EFFC]
      - [0x40, c, RoomLib_Spawn6_8018F028]
      - [0x6C, c, RoomLib_RegisterTable_8018F054]
      - [0xB4, asm, func_8018F09C]
      - [0x140, c, RoomLib_CloseTarget_8018F128]
      - [0x1C4, c, func_8018F1AC]
      - [0x1CC, c, func_8018F1B4]
      - [0x1D4, asm, func_8018F1BC]
      - [0x2E0, c, func_8018F2C8]
      - [0x2E8, asm, func_8018F2D0]
      - [0x368, asm, room_m118_6C_1C4_2E8_368]
      - [0x818, c, func_8018F800]
      - [0x90C, c, func_8018F8F4]
      - [0x914, c, func_8018F8FC]
      - [0x91C, c, func_8018F904]
      - [0x924, c, RoomLib_Set3Reset_8018F90C]
      - [0x944, asm, room_m118_6C_1C4_944]
      - [0xB08, c, func_8018FAF0]
      - [0xB6C, asm, room_m118_6C_1C4_944_B6C]
      - [0xFB8, c, func_8018FFA0]
      - [0x10AC, data]
  - [0x30000]
# room: m118, section3 sector 36528, scanner delta 0
# source slice: room-section3
# extract locally with: dd if=disc/extracted/PE.IMG of=original/USA/overlays/room_m118.bin bs=2048 skip=36528 count=96
# text-bank: Day 1 night: theater blaze aftermath
