.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.4 */

nonmatching Render_StepFade, 0x148

glabel Render_StepFade
    /* 58374 80067B74 0C80023C */  lui        $v0, %hi(D_800BCF88)
    /* 58378 80067B78 88CF428C */  lw         $v0, %lo(D_800BCF88)($v0)
    /* 5837C 80067B7C 00000000 */  nop
    /* 58380 80067B80 00044230 */  andi       $v0, $v0, 0x400
    /* 58384 80067B84 49004010 */  beqz       $v0, .L80067CAC
    /* 58388 80067B88 F0FFBD27 */   addiu     $sp, $sp, -0x10
    /* 5838C 80067B8C 0C80033C */  lui        $v1, %hi(D_800BCFFB)
    /* 58390 80067B90 FBCF6390 */  lbu        $v1, %lo(D_800BCFFB)($v1)
    /* 58394 80067B94 0C80023C */  lui        $v0, %hi(D_800BCFFA)
    /* 58398 80067B98 FACF4290 */  lbu        $v0, %lo(D_800BCFFA)($v0)
    /* 5839C 80067B9C C0190300 */  sll        $v1, $v1, 7
    /* 583A0 80067BA0 FFFF4224 */  addiu      $v0, $v0, -0x1
    /* 583A4 80067BA4 1A006200 */  div        $zero, $v1, $v0
    /* 583A8 80067BA8 02004014 */  bnez       $v0, .L80067BB4
    /* 583AC 80067BAC 00000000 */   nop
    /* 583B0 80067BB0 0D000700 */  break      7
  .L80067BB4:
    /* 583B4 80067BB4 FFFF0124 */  addiu      $at, $zero, -0x1
    /* 583B8 80067BB8 04004114 */  bne        $v0, $at, .L80067BCC
    /* 583BC 80067BBC 0080013C */   lui       $at, (0x80000000 >> 16)
    /* 583C0 80067BC0 02006114 */  bne        $v1, $at, .L80067BCC
    /* 583C4 80067BC4 00000000 */   nop
    /* 583C8 80067BC8 0D000600 */  break      6
  .L80067BCC:
    /* 583CC 80067BCC 12180000 */  mflo       $v1
    /* 583D0 80067BD0 21400000 */  addu       $t0, $zero, $zero
    /* 583D4 80067BD4 0B80053C */  lui        $a1, %hi(g_GeomState)
    /* 583D8 80067BD8 2416A58C */  lw         $a1, %lo(g_GeomState)($a1)
    /* 583DC 80067BDC 0B80043C */  lui        $a0, %hi(g_GeomState)
    /* 583E0 80067BE0 2416848C */  lw         $a0, %lo(g_GeomState)($a0)
    /* 583E4 80067BE4 1400A28C */  lw         $v0, 0x14($a1)
    /* 583E8 80067BE8 0600A994 */  lhu        $t1, 0x6($a1)
    /* 583EC 80067BEC 21208200 */  addu       $a0, $a0, $v0
    /* 583F0 80067BF0 80000224 */  addiu      $v0, $zero, 0x80
    /* 583F4 80067BF4 16002011 */  beqz       $t1, .L80067C50
    /* 583F8 80067BF8 23104300 */   subu      $v0, $v0, $v1
    /* 583FC 80067BFC 21384000 */  addu       $a3, $v0, $zero
  .L80067C00:
    /* 58400 80067C00 3000838C */  lw         $v1, 0x30($a0)
    /* 58404 80067C04 0A80023C */  lui        $v0, %hi(g_ActiveDrawSlot)
    /* 58408 80067C08 DCCD428C */  lw         $v0, %lo(g_ActiveDrawSlot)($v0)
    /* 5840C 80067C0C 26008694 */  lhu        $a2, 0x26($a0)
    /* 58410 80067C10 02004010 */  beqz       $v0, .L80067C1C
    /* 58414 80067C14 00110600 */   sll       $v0, $a2, 4
    /* 58418 80067C18 21186200 */  addu       $v1, $v1, $v0
  .L80067C1C:
    /* 5841C 80067C1C 0800C010 */  beqz       $a2, .L80067C40
    /* 58420 80067C20 21280000 */   addu      $a1, $zero, $zero
  .L80067C24:
    /* 58424 80067C24 060067A0 */  sb         $a3, 0x6($v1)
    /* 58428 80067C28 050067A0 */  sb         $a3, 0x5($v1)
    /* 5842C 80067C2C 040067A0 */  sb         $a3, 0x4($v1)
    /* 58430 80067C30 0100A524 */  addiu      $a1, $a1, 0x1
    /* 58434 80067C34 2B10A600 */  sltu       $v0, $a1, $a2
    /* 58438 80067C38 FAFF4014 */  bnez       $v0, .L80067C24
    /* 5843C 80067C3C 10006324 */   addiu     $v1, $v1, 0x10
  .L80067C40:
    /* 58440 80067C40 01000825 */  addiu      $t0, $t0, 0x1
    /* 58444 80067C44 2A100901 */  slt        $v0, $t0, $t1
    /* 58448 80067C48 EDFF4014 */  bnez       $v0, .L80067C00
    /* 5844C 80067C4C 38008424 */   addiu     $a0, $a0, 0x38
  .L80067C50:
    /* 58450 80067C50 0C80023C */  lui        $v0, %hi(D_800BCFFB)
    /* 58454 80067C54 FBCF4224 */  addiu      $v0, $v0, %lo(D_800BCFFB)
    /* 58458 80067C58 00004390 */  lbu        $v1, 0x0($v0)
    /* 5845C 80067C5C 00000000 */  nop
    /* 58460 80067C60 01006324 */  addiu      $v1, $v1, 0x1
    /* 58464 80067C64 000043A0 */  sb         $v1, 0x0($v0)
    /* 58468 80067C68 0C80023C */  lui        $v0, %hi(D_800BCFFA)
    /* 5846C 80067C6C FACF4290 */  lbu        $v0, %lo(D_800BCFFA)($v0)
    /* 58470 80067C70 FF006330 */  andi       $v1, $v1, 0xFF
    /* 58474 80067C74 2B186200 */  sltu       $v1, $v1, $v0
    /* 58478 80067C78 0D006014 */  bnez       $v1, .L80067CB0
    /* 5847C 80067C7C 21100000 */   addu      $v0, $zero, $zero
    /* 58480 80067C80 0C80023C */  lui        $v0, %hi(D_800BCF88)
    /* 58484 80067C84 88CF428C */  lw         $v0, %lo(D_800BCF88)($v0)
    /* 58488 80067C88 FFF30324 */  addiu      $v1, $zero, -0xC01
    /* 5848C 80067C8C 24104300 */  and        $v0, $v0, $v1
    /* 58490 80067C90 0B80033C */  lui        $v1, %hi(g_GeomState)
    /* 58494 80067C94 2416638C */  lw         $v1, %lo(g_GeomState)($v1)
    /* 58498 80067C98 00084234 */  ori        $v0, $v0, 0x800
    /* 5849C 80067C9C 0C80013C */  lui        $at, %hi(D_800BCF88)
    /* 584A0 80067CA0 88CF22AC */  sw         $v0, %lo(D_800BCF88)($at)
    /* 584A4 80067CA4 F01F0224 */  addiu      $v0, $zero, 0x1FF0
    /* 584A8 80067CA8 260062A4 */  sh         $v0, 0x26($v1)
  .L80067CAC:
    /* 584AC 80067CAC 21100000 */  addu       $v0, $zero, $zero
  .L80067CB0:
    /* 584B0 80067CB0 1000BD27 */  addiu      $sp, $sp, 0x10
    /* 584B4 80067CB4 0800E003 */  jr         $ra
    /* 584B8 80067CB8 00000000 */   nop
endlabel Render_StepFade
