/* MASPSX_FLAGS: --expand-div */
#define ROOMEFFECT_LINE_BURST_FUNC func_8019351C
#define ROOMEFFECT_LINE_BURST_CALLBACK func_80193180
#define ROOMEFFECT_LINE_BURST_TEMPLATE D_8018F1E0
#define ROOMEFFECT_LINE_BURST_ROTATION D_8018F1E8
#include "../room_lib/RoomEffect_LineBurstController.inc"
