#ifndef PE1_ITEM_IDS_H
#define PE1_ITEM_IDS_H

/*
 * Item type codes stored in ItemDataRecord.itemId / the equipment (E-Reg) and
 * crate (C-Reg) "value" byte. Sourced from the Deconstruction Cheats Wiki
 * (Parasite Eve, SLUS-00662). Ranges:
 *   0x01-0x2C  consumables, ammo, junk, crates, stat-transfer "+N" parameters
 *   0x2D-0x3E  more +N parameters, tool kits, keys
 *   0x3F-0x43  melee (Club)      0x44-0x94  guns
 *   0x95-0xC7  armor             0xC8-0xEB  key items / trading cards
 *   0xEC-0xFF  Parasite Energy techs (0xF9-0xFD are dummies)
 */
enum ItemId {
    ITEM_EMPTY_SLOT = 0x00,
    ITEM_AMMO_6 = 0x01,  /* "Bullets" */
    ITEM_AMMO_15 = 0x02,  /* "Bullets" */
    ITEM_AMMO_30 = 0x03,  /* "Bullets" */
    ITEM_DNA_BULLETS = 0x04,  /* "Maeda's Bullets" */
    ITEM_ROCKET = 0x05,  /* "For Rocket Launcher" */
    ITEM_MEDICINE_1 = 0x06,  /* "Restores 45 HP" */
    ITEM_MEDICINE_2 = 0x07,  /* "Restores 90 HP" */
    ITEM_MEDICINE_3 = 0x08,  /* "Restores 180 HP" */
    ITEM_MEDICINE_4 = 0x09,  /* "Restores 400 HP" */
    ITEM_FULL_RECOVER = 0x0A,  /* "Restores All HP" */
    ITEM_SUPER_JUNK = 0x0B,  /* "Helps Item" */
    ITEM_DUPER_JUNK = 0x0C,  /* "Helps Item" */
    ITEM_CURE_P = 0x0D,  /* "Cures & Prevents Poison" */
    ITEM_CURE_D = 0x0E,  /* "Cures & Prevents Darkness" */
    ITEM_CURE_C = 0x0F,  /* "Cures & Prevents Confusion" */
    ITEM_CURE_M = 0x10,  /* "Cures & Prevents Stiffness" */
    ITEM_FULL_CURE = 0x11,  /* "Cures All Negative Status" */
    ITEM_REVIVE = 0x12,  /* "Restores Life When You Die" */
    ITEM_DEFENSE_1 = 0x13,  /* "Increases Defense Power by 1" */
    ITEM_JUNK = 0x14,  /* "Broken Item" */
    ITEM_TRADING_CARD = 0x15,  /* "Normal Trading Card" */
    ITEM_TOOL = 0x16,  /* "Moves Equipped Parameter or Effect" */
    ITEM_SUPER_TOOL = 0x17,  /* "Moves Equipped Parameter or Effect" */
    ITEM_ITEM24 = 0x18,  /* "Helps Item" */
    ITEM_ITEM25 = 0x19,  /* "Helps Item" */
    ITEM_AMMO_CRATE = 0x1A,  /* "Bullet Crate" */
    ITEM_ROCKET_CRATE = 0x1B,  /* "Rocket Crate" */
    ITEM_MAEDA_CRATE = 0x1C,  /* "Maeda's Bullet Crate" */
    ITEM_OFFENSE_1 = 0x1D,  /* "Item Increases Attack Power by 1" */
    ITEM_OFFENSE_2 = 0x1E,  /* "Item Increases Attack Power by 2" */
    ITEM_OFFENSE_3 = 0x1F,  /* "Item Increases Attack Power by 3" */
    ITEM_OFFENSE_4 = 0x20,  /* "Item Increases Attack Power by 4" */
    ITEM_RANGE_1 = 0x21,  /* "Increases Attack Range by 1" */
    ITEM_RANGE_2 = 0x22,  /* "Increases Attack Range by 2" */
    ITEM_RANGE_3 = 0x23,  /* "Increases Attack Range by 3" */
    ITEM_RANGE_4 = 0x24,  /* "Increases Attack Range by 4" */
    ITEM_BULLET_CAP_1 = 0x25,  /* "Increases Bullet Capacity by 1" */
    ITEM_BULLET_CAP_2 = 0x26,  /* "Increases Bullet Capacity by 2" */
    ITEM_BULLET_CAP_3 = 0x27,  /* "Increases Bullet Capacity by 3" */
    ITEM_BULLET_CAP_4 = 0x28,  /* "Increases Bullet Capacity by 4" */
    ITEM_DEFENSE_1_29 = 0x29,  /* "Increases Defense Power by 1" */
    ITEM_DEFENSE_2 = 0x2A,  /* "Increases Defense Power by 2" */
    ITEM_DEFENSE_3 = 0x2B,  /* "Increases Defense Power by 3" */
    ITEM_DEFENSE_4 = 0x2C,  /* "Increases Defense Power by 4" */
    ITEM_CR_EVADE_1 = 0x2D,  /* "Increases Critical Evasion % by 1" */
    ITEM_CR_EVADE_2 = 0x2E,  /* "Increases Critical Evasion % by 2" */
    ITEM_CR_EVADE_3 = 0x2F,  /* "Increases Critical Evasion % by 3" */
    ITEM_CR_EVADE_4 = 0x30,  /* "Increases Critical Evasion % by 4" */
    ITEM_PE_1 = 0x31,  /* "Increases PE Defense by 1" */
    ITEM_PE_2 = 0x32,  /* "Increases PE Defense by 2" */
    ITEM_PE_3 = 0x33,  /* "Increases PE Defense by 3" */
    ITEM_PE_4 = 0x34,  /* "Increases PE Defense by 4" */
    ITEM_TOOL_KIT = 0x35,  /* "Moves Equipped Parameter or Effect" */
    ITEM_SUPER_TOOL_KIT = 0x36,  /* "Moves Equipped Parameter or Effect" */
    ITEM_MOD_PERMIT = 0x37,  /* "Permit from Baker" */
    ITEM_CHRYSLER_KEY1 = 0x38,  /* "Elevator Key to 10th Fl. CB" */
    ITEM_CHRYSLER_KEY2 = 0x39,  /* "Elevator Key to 20th Fl. CB" */
    ITEM_CHRYSLER_KEY3 = 0x3A,  /* "Elevator Key to 30th FL CB" */
    ITEM_CHRYSLER_KEY4 = 0x3B,  /* "Elevator Key to 40th FL CB" */
    ITEM_CHRYSLER_KEY5 = 0x3C,  /* "Elevator Key to 50th FL CB" */
    ITEM_CHRYSLER_KEY6 = 0x3D,  /* "Elevator Key to 60th FL CB" */
    ITEM_CHRYSLER_KEY7 = 0x3E,  /* "Elevator Key to 70th FL CB" */
    ITEM_CLUB_1 = 0x3F,  /* "Melee Weapon" */
    ITEM_CLUB_2 = 0x40,  /* "Melee Weapon" */
    ITEM_CLUB_3 = 0x41,  /* "Melee Weapon" */
    ITEM_CLUB_4 = 0x42,  /* "Melee Weapon" */
    ITEM_CLUB_5 = 0x43,  /* "Melee Weapon" */
    ITEM_M84F = 0x44,  /* "Handgun" */
    ITEM_M9 = 0x45,  /* "Handgun" */
    ITEM_M9_2 = 0x46,  /* "Handgun" */
    ITEM_M9_3 = 0x47,  /* "Handgun" */
    ITEM_M8000 = 0x48,  /* "Handgun" */
    ITEM_M96 = 0x49,  /* "Handgun" */
    ITEM_M96R = 0x4A,  /* "Handgun" */
    ITEM_P220 = 0x4B,  /* "Handgun" */
    ITEM_P220_2 = 0x4C,  /* "Handgun" */
    ITEM_P228 = 0x4D,  /* "Handgun" */
    ITEM_P226 = 0x4E,  /* "Handgun" */
    ITEM_P229 = 0x4F,  /* "Handgun" */
    ITEM_M1911A1 = 0x50,  /* "Handgun" */
    ITEM_M1911A2 = 0x51,  /* "Handgun" */
    ITEM_M1911A3 = 0x52,  /* "Handgun" */
    ITEM_M1911A4 = 0x53,  /* "Handgun" */
    ITEM_M1911A5 = 0x54,  /* "Handgun" */
    ITEM_P8 = 0x55,  /* "Handgun" */
    ITEM_USP = 0x56,  /* "Handgun" */
    ITEM_USP_2 = 0x57,  /* "Handgun" */
    ITEM_USP_3 = 0x58,  /* "Handgun" */
    ITEM_MARK_23 = 0x59,  /* "Handgun" */
    ITEM_G19 = 0x5A,  /* "Handgun" */
    ITEM_G23 = 0x5B,  /* "Handgun" */
    ITEM_G22 = 0x5C,  /* "Handgun" */
    ITEM_G20 = 0x5D,  /* "Handgun" */
    ITEM_M712 = 0x5E,  /* "Handgun" */
    ITEM_PPK = 0x5F,  /* "Handgun" */
    ITEM_AM44 = 0x60,  /* "Handgun" */
    ITEM_MAEDAS_GUN = 0x61,  /* "Handgun" */
    ITEM_PPSH41 = 0x62,  /* "Machine Gun" */
    ITEM_SP1C = 0x63,  /* "Handgun" */
    ITEM_USP_TU = 0x64,  /* "Handgun" */
    ITEM_AK_47 = 0x65,  /* "Rifle" */
    ITEM_DE50AE7 = 0x66,  /* "Handgun" */
    ITEM_DEBUGSMG = 0x67,  /* "Machine Gun" */
    ITEM_M870 = 0x68,  /* "Shotgun" */
    ITEM_M870_2 = 0x69,  /* "Shotgun" */
    ITEM_M500 = 0x6A,  /* "Shotgun" */
    ITEM_M500_2 = 0x6B,  /* "Shotgun" */
    ITEM_MAVERICK = 0x6C,  /* "Shotgun" */
    ITEM_S12 = 0x6D,  /* "Shotgun" */
    ITEM_M10B = 0x6E,  /* "Shotgun" */
    ITEM_M11 = 0x6F,  /* "Machine Gun" */
    ITEM_M10 = 0x70,  /* "Machine Gun" */
    ITEM_MP5K = 0x71,  /* "Machine Gun" */
    ITEM_MP5PDW = 0x72,  /* "Machine Gun" */
    ITEM_MP5A5 = 0x73,  /* "Machine Gun" */
    ITEM_MP5SD6 = 0x74,  /* "Machine Gun" */
    ITEM_MICRO_UZ = 0x75,  /* "Machine Gun" */
    ITEM_MINI_UZ = 0x76,  /* "Machine Gun" */
    ITEM_FULL_UZ = 0x77,  /* "Machine Gun" */
    ITEM_P90 = 0x78,  /* "Machine Gun" */
    ITEM_M16A1 = 0x79,  /* "Rifle" */
    ITEM_M16A2 = 0x7A,  /* "Rifle" */
    ITEM_SG550 = 0x7B,  /* "Rifle" */
    ITEM_SAR = 0x7C,  /* "Rifle" */
    ITEM_G3A3 = 0x7D,  /* "Rifle" */
    ITEM_TYPE64 = 0x7E,  /* "Rifle" */
    ITEM_XM177E2 = 0x7F,  /* "Rifle" */
    ITEM_PSG_1 = 0x80,  /* "Rifle" */
    ITEM_FA_MAS = 0x81,  /* "Rifle" */
    ITEM_MAG = 0x82,  /* "Rifle" */
    ITEM_M203 = 0x83,  /* "Grenade Launcher" */
    ITEM_M203_2 = 0x84,  /* "Grenade Launcher" */
    ITEM_M203_3 = 0x85,  /* "Grenade Launcher" */
    ITEM_M203_4 = 0x86,  /* "Grenade Launcher" */
    ITEM_M203_5 = 0x87,  /* "Grenade Launcher" */
    ITEM_M203_6 = 0x88,  /* "Grenade Launcher" */
    ITEM_M79 = 0x89,  /* "Grenade Launcher" */
    ITEM_M79_2 = 0x8A,  /* "Grenade Launcher" */
    ITEM_M79_3 = 0x8B,  /* "Grenade Launcher" */
    ITEM_M79_4 = 0x8C,  /* "Grenade Launcher" */
    ITEM_M79_5 = 0x8D,  /* "Grenade Launcher" */
    ITEM_M79_6 = 0x8E,  /* "Grenade Launcher" */
    ITEM_HK40 = 0x8F,  /* "Grenade Launcher" */
    ITEM_AT4 = 0x90,  /* "Rocket Launcher" */
    ITEM_AT4_1 = 0x91,  /* "Rocket Launcher" */
    ITEM_LAW80 = 0x92,  /* "Rocket Launcher" */
    ITEM_MAEDAS_GUN_93 = 0x93,  /* "Maeda's Gun With Bullets" */
    ITEM_M92F = 0x94,  /* "Handgun" */
    ITEM_DRESS = 0x95,  /* "Formal Dress" */
    ITEM_N_VEST = 0x96,  /* "Normal Armor" */
    ITEM_N_PROTECTOR = 0x97,  /* "Normal Armor" */
    ITEM_N_JACKET = 0x98,  /* "Normal Armor" */
    ITEM_N_SUIT = 0x99,  /* "Normal Armor" */
    ITEM_N_ARMOR = 0x9A,  /* "Normal Armor" */
    ITEM_KV_VEST_1 = 0x9B,  /* "Light & Durable Armor" */
    ITEM_KV_PROTECTOR_1 = 0x9C,  /* "Light & Durable Armor" */
    ITEM_KV_JACKET_1 = 0x9D,  /* "Light & Durable Armor" */
    ITEM_KV_SUIT_1 = 0x9E,  /* "Light & Durable Armor" */
    ITEM_KV_ARMOR_1 = 0x9F,  /* "Light & Durable Armor" */
    ITEM_SP_VEST_1 = 0xA0,  /* "Light & Very Durable Armor" */
    ITEM_SP_VEST_2 = 0xA1,  /* "Light & Very Durable Armor" */
    ITEM_SP_PROTECTOR = 0xA2,  /* "Light & Very Durable Armor" */
    ITEM_SP_JACKET = 0xA3,  /* "Light & Very Durable Armor" */
    ITEM_SP_SUIT_1 = 0xA4,  /* "Light & Very Durable Armor" */
    ITEM_SP_SUIT_2 = 0xA5,  /* "Light & Very Durable Armor" */
    ITEM_SP_ARMOR_1 = 0xA6,  /* "Light & Very Durable Armor" */
    ITEM_SP_ARMOR_2 = 0xA7,  /* "Light & Very Durable Armor" */
    ITEM_SV_VEST_1 = 0xA8,  /* "Pockets to Carry More Items" */
    ITEM_SV_VEST_2 = 0xA9,  /* "Pockets to Carry More Items" */
    ITEM_SV_PROTECTOR = 0xAA,  /* "Pockets to Carry More Items" */
    ITEM_SV_JACKET = 0xAB,  /* "Pockets to Carry More Items" */
    ITEM_SV_SUIT_1 = 0xAC,  /* "Pockets to Carry More Items" */
    ITEM_SV_SUIT_2 = 0xAD,  /* "Pockets to Carry More Items" */
    ITEM_SV_ARMOR_1 = 0xAE,  /* "Pockets to Carry More Items" */
    ITEM_SV_ARMOR_2 = 0xAF,  /* "Pockets to Carry More Items" */
    ITEM_CR_VEST_1 = 0xB0,  /* "Light but Tough Armor" */
    ITEM_CR_VEST_2 = 0xB1,  /* "Light but Tough Armor" */
    ITEM_CR_PROTECTOR = 0xB2,  /* "Light but Tough Armor" */
    ITEM_CR_JACKET = 0xB3,  /* "Light but Tough Armor" */
    ITEM_CR_SUIT_1 = 0xB4,  /* "Light but Tough Armor" */
    ITEM_CR_SUIT_2 = 0xB5,  /* "Light but Tough Armor" */
    ITEM_CR_ARMOR_1 = 0xB6,  /* "Light but Tough Armor" */
    ITEM_CR_ARMOR_2 = 0xB7,  /* "Light but Tough Armor" */
    ITEM_B_VEST_1 = 0xB8,  /* "Strong Against Status Attacks" */
    ITEM_B_VEST_2 = 0xB9,  /* "Strong Against Status Attacks" */
    ITEM_B_PROTECTOR = 0xBA,  /* "Strong Against Status Attacks" */
    ITEM_B_JACKET_1 = 0xBB,  /* "Strong Against Status Attacks" */
    ITEM_B_JACKET_2 = 0xBC,  /* "Strong Against Status Attacks" */
    ITEM_B_SUIT_1 = 0xBD,  /* "Strong Against Status Attacks" */
    ITEM_B_SUIT_2 = 0xBE,  /* "Strong Against Status Attacks" */
    ITEM_B_ARMOR = 0xBF,  /* "Strong Against Status Attacks" */
    ITEM_CM_VEST_1 = 0xC0,  /* "HI Defense & Strong Against S.A." */
    ITEM_CM_VEST_2 = 0xC1,  /* "HI Defense & Strong Against S.A." */
    ITEM_CM_PROTECTOR = 0xC2,  /* "HI Defense & Strong Against S.A." */
    ITEM_CM_JACKET = 0xC3,  /* "HI Defense & Strong Against S.A." */
    ITEM_CM_SUIT_1 = 0xC4,  /* "HI Defense & Strong Against S.A." */
    ITEM_CM_ARMOR_1 = 0xC5,  /* "HI Defense & Strong Against S.A." */
    ITEM_CM_ARMOR_2 = 0xC6,  /* "HI Defense & Strong Against S.A." */
    ITEM_CM_SUIT_2 = 0xC7,  /* "HI Defense & Strong Against S.A." */
    ITEM_THEATER_KEY = 0xC8,  /* "Dressing Room Key" */
    ITEM_REHEARSE_KEY = 0xC9,  /* "Rehearsal Room Key" */
    ITEM_ZOO_KEY = 0xCA,  /* "Central Park Key" */
    ITEM_NARITA = 0xCB,  /* "Good Luck Charm" */
    ITEM_MAYOKE = 0xCC,  /* "Helpful Good Luck Charm" */
    ITEM_HAMAYA = 0xCD,  /* "Special Good Luck Charm" */
    ITEM_FUSE_1 = 0xCE,  /* "Fuse" */
    ITEM_FUSE_2 = 0xCF,  /* "Fuse" */
    ITEM_FUSE_3 = 0xD0,  /* "Fuse" */
    ITEM_AUTOPSY_KEY = 0xD1,  /* "St. Francis Hospital Key" */
    ITEM_BLUE_CARDKEY = 0xD2,  /* "Blue Magnetic Cardkey" */
    ITEM_GREEN_CARDKEY = 0xD3,  /* "Green Magnetic Cardkey" */
    ITEM_PUMP_KEY = 0xD4,  /* "Pumping Station Key" */
    ITEM_KLAMP_KEY = 0xD5,  /* "Klamp Key" */
    ITEM_STORAGE_KEY = 0xD6,  /* "NYPD Weapons Storage Key" */
    ITEM_LOCKER_KEY = 0xD7,  /* "NYPD Locker Key" */
    ITEM_WEAPON_MEMO = 0xD8,  /* "Weapon Memo" */
    ITEM_MEDAL = 0xD9,  /* "Shiny Medal" */
    ITEM_ELEVATOR_KEY = 0xDA,  /* "Elevator Key" */
    ITEM_GATE_KEY = 0xDB,  /* "Subway Gate Key" */
    ITEM_WAREHOUSE_KEY = 0xDC,  /* "Port Storage Key" */
    ITEM_GSP_T_CARD = 0xDD,  /* "Gun Trading Card" */
    ITEM_P38_T_CARD = 0xDE,  /* "Gun Trading Card" */
    ITEM_BHAWK_T_CARD = 0xDF,  /* "Gun Trading Card" */
    ITEM_KASUL_T_CARD = 0xE0,  /* "Gun Trading Card" */
    ITEM_PPKS_T_CARD = 0xE1,  /* "Gun Trading Card" */
    ITEM_M1_T_CARD = 0xE2,  /* "Gun Trading Card" */
    ITEM_MK5_T_CARD = 0xE3,  /* "Gun Trading Card" */
    ITEM_MP44_T_CARD = 0xE4,  /* "Gun Trading Card" */
    ITEM_BAR_T_CARD = 0xE5,  /* "Gun Trading Card" */
    ITEM_MG42_T_CARD = 0xE6,  /* "Gun Trading Card" */
    ITEM_M29_T_CARD = 0xE7,  /* "Gun Trading Card" */
    ITEM_M73_T_CARD = 0xE8,  /* "Gun Trading Card" */
    ITEM_TYPE38_T_CARD = 0xE9,  /* "Gun Trading Card" */
    ITEM_TYPE3_T_CARD = 0xEA,  /* "Gun Trading Card" */
    ITEM_EAGLE_T_CARD = 0xEB,  /* "Gun Trading Card" */
    ITEM_HEAL_1 = 0xEC,  /* Parasite Energy tech. */
    ITEM_HEAL_2 = 0xED,  /* Parasite Energy tech. */
    ITEM_HEAL_3 = 0xEE,  /* Parasite Energy tech. */
    ITEM_DETOX = 0xEF,  /* Parasite Energy tech. */
    ITEM_MEDIC = 0xF0,  /* Parasite Energy tech. */
    ITEM_BARRIER = 0xF1,  /* Parasite Energy tech. */
    ITEM_ENERGY_SHOT = 0xF2,  /* Parasite Energy tech. */
    ITEM_SCAN = 0xF3,  /* Parasite Energy tech. */
    ITEM_SLOW = 0xF4,  /* Parasite Energy tech. */
    ITEM_HASTE = 0xF5,  /* Parasite Energy tech. */
    ITEM_CONFUSE = 0xF6,  /* Parasite Energy tech. */
    ITEM_GENE_HEAL = 0xF7,  /* Parasite Energy tech. */
    ITEM_PRERAISE = 0xF8,  /* Parasite Energy tech. */
    ITEM_MITO14 = 0xF9,  /* Parasite Energy tech dummy. */
    ITEM_MITO15 = 0xFA,  /* Parasite Energy tech dummy. */
    ITEM_MITO16 = 0xFB,  /* Parasite Energy tech dummy. */
    ITEM_MITO17 = 0xFC,  /* Parasite Energy tech dummy. */
    ITEM_MITO18 = 0xFD,  /* Parasite Energy tech dummy. */
    ITEM_FULL_RECOVER_FE = 0xFE,  /* Parasite Energy tech. */
    ITEM_LIBERATE = 0xFF,  /* Parasite Energy tech. */
};

/* Modification type codes stored in an equipment record's mods[] tail. */
enum ItemMod {
    MOD_EMPTY_SLOT = 0x00,
    MOD_RATE_OF_FIRE_2 = 0x01,
    MOD_RATE_OF_FIRE_3 = 0x02,
    MOD_RATE_OF_FIRE_5 = 0x03,
    MOD_RATE_OF_FIRE_7 = 0x04,
    MOD_RATE_OF_FIRE_10 = 0x05,
    MOD_RANDOM_RATE_OF_FIRE_1_5 = 0x06,
    MOD_BURST_SPRAY_MULTIPLE_TARGETS = 0x07,
    MOD_ATTACK_ALL_ENEMIES_W_RATE_OF_FIRE = 0x08,
    MOD_ADD_HEAT_EFFECT_TO_BULLETS = 0x09,
    MOD_ADD_FROST_EFFECT_TO_BULLETS = 0x0A,
    MOD_ADD_CYANIDE_TO_BULLETS = 0x0B,
    MOD_ADD_ACID_EFFECT_TO_BULLETS = 0x0C,
    MOD_ADD_TRANQUILIZER_TO_BULLETS = 0x0D,
    MOD_COUNTERATTACK_ENEMY = 0x0E,
    MOD_QUICKDRAW_FIRST_ATTACK = 0x0F,
    MOD_STEAL_ITEMS_BUT_HALVES_ATTACK_POWER = 0x10,
    MOD_STEAL_DURING_ATTACK = 0x11,
    MOD_CRITICAL_PERCENTAGE_INCREASES = 0x12,
    MOD_ENTER_2_COMMANDS = 0x13,
    MOD_ENTER_3_COMMANDS = 0x14,
    MOD_RESIST_POISON = 0x15,
    MOD_RESIST_STIFFNESS = 0x16,
    MOD_RESIST_DARKNESS = 0x17,
    MOD_DECREASES_ITEMS_STOLEN = 0x18,
    MOD_RESIST_CONFUSION = 0x19,
    MOD_USES_MEDICINE_WHEN_HP_IS_LOW = 0x1A,
    MOD_USE_CURES_TO_REMOVE_STATUS = 0x1B,
    MOD_INCREASES_ITEM_CAPACITY_BY_1 = 0x1C,
    MOD_INCREASES_ITEM_CAPACITY_BY_2 = 0x1D,
    MOD_INCREASES_ITEM_CAPACITY_BY_4 = 0x1E,
    MOD_INCREASES_MAX_HP = 0x1F,
};

/* Item-id category boundaries (inclusive). */
#define ITEM_FIRST_MELEE   0x3F
#define ITEM_FIRST_GUN     0x44
#define ITEM_FIRST_ARMOR   0x95
#define ITEM_FIRST_KEYITEM 0xC8
#define ITEM_FIRST_PE_TECH 0xEC

#endif /* PE1_ITEM_IDS_H */
