.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

/* Handwritten function */
nonmatching RoomLib_HandlerD, 0x548

glabel RoomLib_HandlerD
    /* 648 8018F630 D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* 64C 8018F634 2400B5AF */  sw         $s5, 0x24($sp)
    /* 650 8018F638 21A88000 */  addu       $s5, $a0, $zero
    /* 654 8018F63C 1400B1AF */  sw         $s1, 0x14($sp)
    /* 658 8018F640 0C00B126 */  addiu      $s1, $s5, 0xC
    /* 65C 8018F644 1800B2AF */  sw         $s2, 0x18($sp)
    /* 660 8018F648 2800BFAF */  sw         $ra, 0x28($sp)
    /* 664 8018F64C 2000B4AF */  sw         $s4, 0x20($sp)
    /* 668 8018F650 1C00B3AF */  sw         $s3, 0x1C($sp)
    /* 66C 8018F654 1000B0AF */  sw         $s0, 0x10($sp)
    /* 670 8018F658 1A00A292 */  lbu        $v0, 0x1A($s5)
    /* 674 8018F65C 0800B38E */  lw         $s3, 0x8($s5)
    /* 678 8018F660 46004014 */  bnez       $v0, .L8018F77C
    /* 67C 8018F664 801F123C */   lui       $s2, (0x1F800010 >> 16)
    /* 680 8018F668 F3FF033C */  lui        $v1, (0xFFF3FFFF >> 16)
    /* 684 8018F66C 01000224 */  addiu      $v0, $zero, 0x1
    /* 688 8018F670 1A00A2A2 */  sb         $v0, 0x1A($s5)
    /* 68C 8018F674 0400A0AE */  sw         $zero, 0x4($s5)
    /* 690 8018F678 9800628E */  lw         $v0, 0x98($s3)
    /* 694 8018F67C FFFF6334 */  ori        $v1, $v1, (0xFFF3FFFF & 0xFFFF)
    /* 698 8018F680 24104300 */  and        $v0, $v0, $v1
    /* 69C 8018F684 980062AE */  sw         $v0, 0x98($s3)
    /* 6A0 8018F688 1400A286 */  lh         $v0, 0x14($s5)
    /* 6A4 8018F68C 00000000 */  nop
    /* 6A8 8018F690 09004010 */  beqz       $v0, .L8018F6B8
    /* 6AC 8018F694 00000000 */   nop
    /* 6B0 8018F698 0000648E */  lw         $a0, 0x0($s3)
    /* 6B4 8018F69C 00000000 */  nop
    /* 6B8 8018F6A0 05008010 */  beqz       $a0, .L8018F6B8
    /* 6BC 8018F6A4 0040033C */   lui       $v1, (0x40000000 >> 16)
    /* 6C0 8018F6A8 0000828C */  lw         $v0, 0x0($a0)
    /* 6C4 8018F6AC 00000000 */  nop
    /* 6C8 8018F6B0 25104300 */  or         $v0, $v0, $v1
    /* 6CC 8018F6B4 000082AC */  sw         $v0, 0x0($a0)
  .L8018F6B8:
    /* 6D0 8018F6B8 2800628E */  lw         $v0, 0x28($s3)
    /* 6D4 8018F6BC 00000000 */  nop
    /* 6D8 8018F6C0 500022AE */  sw         $v0, 0x50($s1)
    /* 6DC 8018F6C4 2C00628E */  lw         $v0, 0x2C($s3)
    /* 6E0 8018F6C8 21202002 */  addu       $a0, $s1, $zero
    /* 6E4 8018F6CC 540022AE */  sw         $v0, 0x54($s1)
    /* 6E8 8018F6D0 3000628E */  lw         $v0, 0x30($s3)
    /* 6EC 8018F6D4 21284002 */  addu       $a1, $s2, $zero
    /* 6F0 8018F6D8 163F060C */  jal        func_8018FC58
    /* 6F4 8018F6DC 580022AE */   sw        $v0, 0x58($s1)
    /* 6F8 8018F6E0 50003426 */  addiu      $s4, $s1, 0x50
    /* 6FC 8018F6E4 21208002 */  addu       $a0, $s4, $zero
    /* 700 8018F6E8 40003026 */  addiu      $s0, $s1, 0x40
    /* 704 8018F6EC 207F030C */  jal        func_800DFC80
    /* 708 8018F6F0 21280002 */   addu      $a1, $s0, $zero
    /* 70C 8018F6F4 8C00248E */  lw         $a0, 0x8C($s1)
    /* 710 8018F6F8 00000000 */  nop
    /* 714 8018F6FC C0180400 */  sll        $v1, $a0, 3
    /* 718 8018F700 23186400 */  subu       $v1, $v1, $a0
    /* 71C 8018F704 00190300 */  sll        $v1, $v1, 4
    /* 720 8018F708 431D0300 */  sra        $v1, $v1, 21
    /* 724 8018F70C 21184300 */  addu       $v1, $v0, $v1
    /* 728 8018F710 48016228 */  slti       $v0, $v1, 0x148
    /* 72C 8018F714 02004010 */  beqz       $v0, .L8018F720
    /* 730 8018F718 1605023C */   lui       $v0, (0x5160000 >> 16)
    /* 734 8018F71C 48010324 */  addiu      $v1, $zero, 0x148
  .L8018F720:
    /* 738 8018F720 1A004300 */  div        $zero, $v0, $v1
    /* 73C 8018F724 02006014 */  bnez       $v1, .L8018F730
    /* 740 8018F728 00000000 */   nop
    /* 744 8018F72C 0D000700 */  break      7
  .L8018F730:
    /* 748 8018F730 FFFF0124 */  addiu      $at, $zero, -0x1
    /* 74C 8018F734 04006114 */  bne        $v1, $at, .L8018F748
    /* 750 8018F738 0080013C */   lui       $at, (0x80000000 >> 16)
    /* 754 8018F73C 02004114 */  bne        $v0, $at, .L8018F748
    /* 758 8018F740 00000000 */   nop
    /* 75C 8018F744 0D000600 */  break      6
  .L8018F748:
    /* 760 8018F748 12100000 */  mflo       $v0
    /* 764 8018F74C 21208002 */  addu       $a0, $s4, $zero
    /* 768 8018F750 21280002 */  addu       $a1, $s0, $zero
    /* 76C 8018F754 78003026 */  addiu      $s0, $s1, 0x78
    /* 770 8018F758 21300002 */  addu       $a2, $s0, $zero
    /* 774 8018F75C 00120200 */  sll        $v0, $v0, 8
    /* 778 8018F760 940022AE */  sw         $v0, 0x94($s1)
    /* 77C 8018F764 C3100200 */  sra        $v0, $v0, 3
    /* 780 8018F768 A57F030C */  jal        func_800DFE94
    /* 784 8018F76C 980022AE */   sw        $v0, 0x98($s1)
    /* 788 8018F770 21200002 */  addu       $a0, $s0, $zero
    /* 78C 8018F774 D5E5010C */  jal        func_80079754
    /* 790 8018F778 10002526 */   addiu     $a1, $s1, 0x10
  .L8018F77C:
    /* 794 8018F77C 00800534 */  ori        $a1, $zero, 0x8000
    /* 798 8018F780 680040A6 */  sh         $zero, (0x1F800068 & 0xFFFF)($s2)
    /* 79C 8018F784 9800228E */  lw         $v0, 0x98($s1)
    /* 7A0 8018F788 0980033C */  lui        $v1, %hi(D_800966EC)
    /* 7A4 8018F78C EC666324 */  addiu      $v1, $v1, %lo(D_800966EC)
    /* 7A8 8018F790 21104500 */  addu       $v0, $v0, $a1
    /* 7AC 8018F794 03140200 */  sra        $v0, $v0, 16
    /* 7B0 8018F798 00FC4224 */  addiu      $v0, $v0, -0x400
    /* 7B4 8018F79C 6A0042A6 */  sh         $v0, (0x1F80006A & 0xFFFF)($s2)
    /* 7B8 8018F7A0 FF0F4230 */  andi       $v0, $v0, 0xFFF
    /* 7BC 8018F7A4 80100200 */  sll        $v0, $v0, 2
    /* 7C0 8018F7A8 21104300 */  addu       $v0, $v0, $v1
    /* 7C4 8018F7AC 02004384 */  lh         $v1, 0x2($v0)
    /* 7C8 8018F7B0 2A0040A6 */  sh         $zero, (0x1F80002A & 0xFFFF)($s2)
    /* 7CC 8018F7B4 280043A6 */  sh         $v1, (0x1F800028 & 0xFFFF)($s2)
    /* 7D0 8018F7B8 0000428C */  lw         $v0, 0x0($v0)
    /* 7D4 8018F7BC 28004496 */  lhu        $a0, (0x1F800028 & 0xFFFF)($s2)
    /* 7D8 8018F7C0 2E0040A6 */  sh         $zero, (0x1F80002E & 0xFFFF)($s2)
    /* 7DC 8018F7C4 320040A6 */  sh         $zero, (0x1F800032 & 0xFFFF)($s2)
    /* 7E0 8018F7C8 360040A6 */  sh         $zero, (0x1F800036 & 0xFFFF)($s2)
    /* 7E4 8018F7CC 000040A6 */  sh         $zero, (0x1F800000 & 0xFFFF)($s2)
    /* 7E8 8018F7D0 020040A6 */  sh         $zero, (0x1F800002 & 0xFFFF)($s2)
    /* 7EC 8018F7D4 2C0042A6 */  sh         $v0, (0x1F80002C & 0xFFFF)($s2)
    /* 7F0 8018F7D8 2C004396 */  lhu        $v1, (0x1F80002C & 0xFFFF)($s2)
    /* 7F4 8018F7DC 00100224 */  addiu      $v0, $zero, 0x1000
    /* 7F8 8018F7E0 300042A6 */  sh         $v0, (0x1F800030 & 0xFFFF)($s2)
    /* 7FC 8018F7E4 380044A6 */  sh         $a0, (0x1F800038 & 0xFFFF)($s2)
    /* 800 8018F7E8 23180300 */  negu       $v1, $v1
    /* 804 8018F7EC 340043A6 */  sh         $v1, (0x1F800034 & 0xFFFF)($s2)
    /* 808 8018F7F0 8800228E */  lw         $v0, 0x88($s1)
    /* 80C 8018F7F4 00000000 */  nop
    /* 810 8018F7F8 03130200 */  sra        $v0, $v0, 12
    /* 814 8018F7FC 040042A6 */  sh         $v0, (0x1F800004 & 0xFFFF)($s2)
    /* 818 8018F800 28004236 */  ori        $v0, $s2, (0x1F800028 & 0xFFFF)
    /* 81C 8018F804 00004C8C */  lw         $t4, 0x0($v0)
    /* 820 8018F808 04004D8C */  lw         $t5, 0x4($v0)
    /* 824 8018F80C 0000CC48 */  ctc2       $t4, $0 /* handwritten instruction */
    /* 828 8018F810 0008CD48 */  ctc2       $t5, $1 /* handwritten instruction */
    /* 82C 8018F814 08004C8C */  lw         $t4, 0x8($v0)
    /* 830 8018F818 0C004D8C */  lw         $t5, 0xC($v0)
    /* 834 8018F81C 10004E8C */  lw         $t6, 0x10($v0)
    /* 838 8018F820 0010CC48 */  ctc2       $t4, $2 /* handwritten instruction */
    /* 83C 8018F824 0018CD48 */  ctc2       $t5, $3 /* handwritten instruction */
    /* 840 8018F828 0020CE48 */  ctc2       $t6, $4 /* handwritten instruction */
    /* 844 8018F82C 000040CA */  lwc2       $0, (0x1F800000 & 0xFFFF)($s2)
    /* 848 8018F830 040041CA */  lwc2       $1, (0x1F800004 & 0xFFFF)($s2)
    /* 84C 8018F834 00000000 */  nop
    /* 850 8018F838 00000000 */  nop
    /* 854 8018F83C 1260484A */  mvmva      1, 0, 0, 3, 0
    /* 858 8018F840 08004226 */  addiu      $v0, $s2, %lo(D_1F800008)
    /* 85C 8018F844 000059E8 */  swc2       $25, 0x0($v0)
    /* 860 8018F848 04005AE8 */  swc2       $26, 0x4($v0) /* handwritten instruction */
    /* 864 8018F84C 08005BE8 */  swc2       $27, 0x8($v0) /* handwritten instruction */
    /* 868 8018F850 0800428E */  lw         $v0, (0x1F800008 & 0xFFFF)($s2)
    /* 86C 8018F854 3000238E */  lw         $v1, 0x30($s1)
    /* 870 8018F858 00130200 */  sll        $v0, $v0, 12
    /* 874 8018F85C 21186200 */  addu       $v1, $v1, $v0
    /* 878 8018F860 300023AE */  sw         $v1, 0x30($s1)
    /* 87C 8018F864 1000428E */  lw         $v0, (0x1F800010 & 0xFFFF)($s2)
    /* 880 8018F868 3800238E */  lw         $v1, 0x38($s1)
    /* 884 8018F86C 00130200 */  sll        $v0, $v0, 12
    /* 888 8018F870 21186200 */  addu       $v1, $v1, $v0
    /* 88C 8018F874 380023AE */  sw         $v1, 0x38($s1)
    /* 890 8018F878 9800238E */  lw         $v1, 0x98($s1)
    /* 894 8018F87C 0008023C */  lui        $v0, (0x8000000 >> 16)
    /* 898 8018F880 2A104300 */  slt        $v0, $v0, $v1
    /* 89C 8018F884 02004010 */  beqz       $v0, .L8018F890
    /* 8A0 8018F888 02000224 */   addiu     $v0, $zero, 0x2
    /* 8A4 8018F88C 0300A2A2 */  sb         $v0, 0x3($s5)
  .L8018F890:
    /* 8A8 8018F890 1000428E */  lw         $v0, (0x1F800010 & 0xFFFF)($s2)
    /* 8AC 8018F894 00000000 */  nop
    /* 8B0 8018F898 0E004004 */  bltz       $v0, .L8018F8D4
    /* 8B4 8018F89C 00000000 */   nop
    /* 8B8 8018F8A0 8800248E */  lw         $a0, 0x88($s1)
    /* 8BC 8018F8A4 8C00228E */  lw         $v0, 0x8C($s1)
    /* 8C0 8018F8A8 00000000 */  nop
    /* 8C4 8018F8AC 21208200 */  addu       $a0, $a0, $v0
    /* 8C8 8018F8B0 21188500 */  addu       $v1, $a0, $a1
    /* 8CC 8018F8B4 9400228E */  lw         $v0, 0x94($s1)
    /* 8D0 8018F8B8 031C0300 */  sra        $v1, $v1, 16
    /* 8D4 8018F8BC 03130200 */  sra        $v0, $v0, 12
    /* 8D8 8018F8C0 18006200 */  mult       $v1, $v0
    /* 8DC 8018F8C4 880024AE */  sw         $a0, 0x88($s1)
    /* 8E0 8018F8C8 9800238E */  lw         $v1, 0x98($s1)
    /* 8E4 8018F8CC 413E0608 */  j          .L8018F904
    /* 8E8 8018F8D0 00000000 */   nop
  .L8018F8D4:
    /* 8EC 8018F8D4 8800238E */  lw         $v1, 0x88($s1)
    /* 8F0 8018F8D8 9400228E */  lw         $v0, 0x94($s1)
    /* 8F4 8018F8DC 21186500 */  addu       $v1, $v1, $a1
    /* 8F8 8018F8E0 031C0300 */  sra        $v1, $v1, 16
    /* 8FC 8018F8E4 03130200 */  sra        $v0, $v0, 12
    /* 900 8018F8E8 18006200 */  mult       $v1, $v0
    /* 904 8018F8EC 8800228E */  lw         $v0, 0x88($s1)
    /* 908 8018F8F0 8C00238E */  lw         $v1, 0x8C($s1)
    /* 90C 8018F8F4 00000000 */  nop
    /* 910 8018F8F8 23104300 */  subu       $v0, $v0, $v1
    /* 914 8018F8FC 9800238E */  lw         $v1, 0x98($s1)
    /* 918 8018F900 880022AE */  sw         $v0, 0x88($s1)
  .L8018F904:
    /* 91C 8018F904 12380000 */  mflo       $a3
    /* 920 8018F908 03120700 */  sra        $v0, $a3, 8
    /* 924 8018F90C 00130200 */  sll        $v0, $v0, 12
    /* 928 8018F910 21186200 */  addu       $v1, $v1, $v0
    /* 92C 8018F914 980023AE */  sw         $v1, 0x98($s1)
    /* 930 8018F918 9A002286 */  lh         $v0, 0x9A($s1)
    /* 934 8018F91C 00000000 */  nop
    /* 938 8018F920 010C4228 */  slti       $v0, $v0, 0xC01
    /* 93C 8018F924 0C004014 */  bnez       $v0, .L8018F958
    /* 940 8018F928 00800434 */   ori       $a0, $zero, 0x8000
    /* 944 8018F92C 3000228E */  lw         $v0, 0x30($s1)
    /* 948 8018F930 00000000 */  nop
    /* 94C 8018F934 0900401C */  bgtz       $v0, .L8018F95C
    /* 950 8018F938 00000000 */   nop
    /* 954 8018F93C 2120A002 */  addu       $a0, $s5, $zero
    /* 958 8018F940 180040AE */  sw         $zero, (0x1F800018 & 0xFFFF)($s2)
    /* 95C 8018F944 1C0040AE */  sw         $zero, (0x1F80001C & 0xFFFF)($s2)
    /* 960 8018F948 A63F060C */  jal        func_8018FE98
    /* 964 8018F94C 200040AE */   sw        $zero, (0x1F800020 & 0xFFFF)($s2)
    /* 968 8018F950 783E0608 */  j          .L8018F9E0
    /* 96C 8018F954 00000000 */   nop
  .L8018F958:
    /* 970 8018F958 3000228E */  lw         $v0, 0x30($s1)
  .L8018F95C:
    /* 974 8018F95C 9000238E */  lw         $v1, 0x90($s1)
    /* 978 8018F960 21104400 */  addu       $v0, $v0, $a0
    /* 97C 8018F964 03140200 */  sra        $v0, $v0, 16
    /* 980 8018F968 18004300 */  mult       $v0, $v1
    /* 984 8018F96C 020040A6 */  sh         $zero, (0x1F800002 & 0xFFFF)($s2)
    /* 988 8018F970 12380000 */  mflo       $a3
    /* 98C 8018F974 03130700 */  sra        $v0, $a3, 12
    /* 990 8018F978 000042A6 */  sh         $v0, (0x1F800000 & 0xFFFF)($s2)
    /* 994 8018F97C 3800228E */  lw         $v0, 0x38($s1)
    /* 998 8018F980 00000000 */  nop
    /* 99C 8018F984 21104400 */  addu       $v0, $v0, $a0
    /* 9A0 8018F988 03140200 */  sra        $v0, $v0, 16
    /* 9A4 8018F98C 040042A6 */  sh         $v0, (0x1F800004 & 0xFFFF)($s2)
    /* 9A8 8018F990 10002226 */  addiu      $v0, $s1, 0x10
    /* 9AC 8018F994 00004C8C */  lw         $t4, 0x0($v0)
    /* 9B0 8018F998 04004D8C */  lw         $t5, 0x4($v0)
    /* 9B4 8018F99C 0000CC48 */  ctc2       $t4, $0 /* handwritten instruction */
    /* 9B8 8018F9A0 0008CD48 */  ctc2       $t5, $1 /* handwritten instruction */
    /* 9BC 8018F9A4 08004C8C */  lw         $t4, 0x8($v0)
    /* 9C0 8018F9A8 0C004D8C */  lw         $t5, 0xC($v0)
    /* 9C4 8018F9AC 10004E8C */  lw         $t6, 0x10($v0)
    /* 9C8 8018F9B0 0010CC48 */  ctc2       $t4, $2 /* handwritten instruction */
    /* 9CC 8018F9B4 0018CD48 */  ctc2       $t5, $3 /* handwritten instruction */
    /* 9D0 8018F9B8 0020CE48 */  ctc2       $t6, $4 /* handwritten instruction */
    /* 9D4 8018F9BC 000040CA */  lwc2       $0, (0x1F800000 & 0xFFFF)($s2)
    /* 9D8 8018F9C0 040041CA */  lwc2       $1, (0x1F800004 & 0xFFFF)($s2)
    /* 9DC 8018F9C4 00000000 */  nop
    /* 9E0 8018F9C8 00000000 */  nop
    /* 9E4 8018F9CC 1260484A */  mvmva      1, 0, 0, 3, 0
    /* 9E8 8018F9D0 18004226 */  addiu      $v0, $s2, %lo(D_1F800018)
    /* 9EC 8018F9D4 000059E8 */  swc2       $25, 0x0($v0)
    /* 9F0 8018F9D8 04005AE8 */  swc2       $26, 0x4($v0) /* handwritten instruction */
    /* 9F4 8018F9DC 08005BE8 */  swc2       $27, 0x8($v0) /* handwritten instruction */
  .L8018F9E0:
    /* 9F8 8018F9E0 A6002386 */  lh         $v1, 0xA6($s1)
    /* 9FC 8018F9E4 00000000 */  nop
    /* A00 8018F9E8 08006010 */  beqz       $v1, .L8018FA0C
    /* A04 8018F9EC 00000000 */   nop
    /* A08 8018F9F0 9A002286 */  lh         $v0, 0x9A($s1)
    /* A0C 8018F9F4 00000000 */  nop
    /* A10 8018F9F8 2A106200 */  slt        $v0, $v1, $v0
    /* A14 8018F9FC 03004010 */  beqz       $v0, .L8018FA0C
    /* A18 8018FA00 00000000 */   nop
    /* A1C 8018FA04 A63F060C */  jal        func_8018FE98
    /* A20 8018FA08 2120A002 */   addu      $a0, $s5, $zero
  .L8018FA0C:
    /* A24 8018FA0C 1800428E */  lw         $v0, (0x1F800018 & 0xFFFF)($s2)
    /* A28 8018FA10 5000238E */  lw         $v1, 0x50($s1)
    /* A2C 8018FA14 00140200 */  sll        $v0, $v0, 16
    /* A30 8018FA18 21186200 */  addu       $v1, $v1, $v0
    /* A34 8018FA1C 280063AE */  sw         $v1, 0x28($s3)
    /* A38 8018FA20 2000428E */  lw         $v0, (0x1F800020 & 0xFFFF)($s2)
    /* A3C 8018FA24 5800238E */  lw         $v1, 0x58($s1)
    /* A40 8018FA28 00140200 */  sll        $v0, $v0, 16
    /* A44 8018FA2C 21186200 */  addu       $v1, $v1, $v0
    /* A48 8018FA30 2800628E */  lw         $v0, 0x28($s3)
    /* A4C 8018FA34 00800434 */  ori        $a0, $zero, 0x8000
    /* A50 8018FA38 300063AE */  sw         $v1, 0x30($s3)
    /* A54 8018FA3C 3000638E */  lw         $v1, 0x30($s3)
    /* A58 8018FA40 21104400 */  addu       $v0, $v0, $a0
    /* A5C 8018FA44 03140200 */  sra        $v0, $v0, 16
    /* A60 8018FA48 21186400 */  addu       $v1, $v1, $a0
    /* A64 8018FA4C 031C0300 */  sra        $v1, $v1, 16
    /* A68 8018FA50 FC0162AE */  sw         $v0, 0x1FC($s3)
    /* A6C 8018FA54 040263AE */  sw         $v1, 0x204($s3)
    /* A70 8018FA58 AB002292 */  lbu        $v0, 0xAB($s1)
    /* A74 8018FA5C 00000000 */  nop
    /* A78 8018FA60 09004014 */  bnez       $v0, .L8018FA88
    /* A7C 8018FA64 00000000 */   nop
    /* A80 8018FA68 1C00438E */  lw         $v1, (0x1F80001C & 0xFFFF)($s2)
    /* A84 8018FA6C 5400228E */  lw         $v0, 0x54($s1)
    /* A88 8018FA70 001C0300 */  sll        $v1, $v1, 16
    /* A8C 8018FA74 21104300 */  addu       $v0, $v0, $v1
    /* A90 8018FA78 2C0062AE */  sw         $v0, 0x2C($s3)
    /* A94 8018FA7C 21104400 */  addu       $v0, $v0, $a0
    /* A98 8018FA80 03140200 */  sra        $v0, $v0, 16
    /* A9C 8018FA84 000262AE */  sw         $v0, 0x200($s3)
  .L8018FA88:
    /* AA0 8018FA88 9C002286 */  lh         $v0, 0x9C($s1)
    /* AA4 8018FA8C 00000000 */  nop
    /* AA8 8018FA90 26004010 */  beqz       $v0, .L8018FB2C
    /* AAC 8018FA94 00000000 */   nop
    /* AB0 8018FA98 1000428E */  lw         $v0, (0x1F800010 & 0xFFFF)($s2)
    /* AB4 8018FA9C 00000000 */  nop
    /* AB8 8018FAA0 22004004 */  bltz       $v0, .L8018FB2C
    /* ABC 8018FAA4 00000000 */   nop
    /* AC0 8018FAA8 9E002286 */  lh         $v0, 0x9E($s1)
    /* AC4 8018FAAC 0400A38E */  lw         $v1, 0x4($s5)
    /* AC8 8018FAB0 00000000 */  nop
    /* ACC 8018FAB4 2B106200 */  sltu       $v0, $v1, $v0
    /* AD0 8018FAB8 1C004014 */  bnez       $v0, .L8018FB2C
    /* AD4 8018FABC 00000000 */   nop
    /* AD8 8018FAC0 A0002286 */  lh         $v0, 0xA0($s1)
    /* ADC 8018FAC4 00000000 */  nop
    /* AE0 8018FAC8 03004010 */  beqz       $v0, .L8018FAD8
    /* AE4 8018FACC 2B104300 */   sltu      $v0, $v0, $v1
    /* AE8 8018FAD0 16004014 */  bnez       $v0, .L8018FB2C
    /* AEC 8018FAD4 00000000 */   nop
  .L8018FAD8:
    /* AF0 8018FAD8 21202002 */  addu       $a0, $s1, $zero
    /* AF4 8018FADC 163F060C */  jal        func_8018FC58
    /* AF8 8018FAE0 21284002 */   addu      $a1, $s2, $zero
    /* AFC 8018FAE4 50002426 */  addiu      $a0, $s1, 0x50
    /* B00 8018FAE8 40002526 */  addiu      $a1, $s1, 0x40
    /* B04 8018FAEC 78003026 */  addiu      $s0, $s1, 0x78
    /* B08 8018FAF0 7A002296 */  lhu        $v0, 0x7A($s1)
    /* B0C 8018FAF4 21300002 */  addu       $a2, $s0, $zero
    /* B10 8018FAF8 A57F030C */  jal        func_800DFE94
    /* B14 8018FAFC 020042A6 */   sh        $v0, (0x1F800002 & 0xFFFF)($s2)
    /* B18 8018FB00 7A002586 */  lh         $a1, 0x7A($s1)
    /* B1C 8018FB04 02004496 */  lhu        $a0, (0x1F800002 & 0xFFFF)($s2)
    /* B20 8018FB08 9C002686 */  lh         $a2, 0x9C($s1)
    /* B24 8018FB0C 00240400 */  sll        $a0, $a0, 16
    /* B28 8018FB10 EE7F030C */  jal        FieldEng_TurnToward
    /* B2C 8018FB14 03240400 */   sra       $a0, $a0, 16
    /* B30 8018FB18 21200002 */  addu       $a0, $s0, $zero
    /* B34 8018FB1C 10002526 */  addiu      $a1, $s1, 0x10
    /* B38 8018FB20 FF0F4230 */  andi       $v0, $v0, 0xFFF
    /* B3C 8018FB24 D5E5010C */  jal        func_80079754
    /* B40 8018FB28 7A0022A6 */   sh        $v0, 0x7A($s1)
  .L8018FB2C:
    /* B44 8018FB2C AA002292 */  lbu        $v0, 0xAA($s1)
    /* B48 8018FB30 00000000 */  nop
    /* B4C 8018FB34 04004014 */  bnez       $v0, .L8018FB48
    /* B50 8018FB38 21206002 */   addu      $a0, $s3, $zero
    /* B54 8018FB3C 21282002 */  addu       $a1, $s1, $zero
    /* B58 8018FB40 DE3E060C */  jal        RoomLib_FxNotify
    /* B5C 8018FB44 21304002 */   addu      $a2, $s2, $zero
  .L8018FB48:
    /* B60 8018FB48 C87E030C */  jal        func_800DFB20
    /* B64 8018FB4C 2120A002 */   addu      $a0, $s5, $zero
    /* B68 8018FB50 2800BF8F */  lw         $ra, 0x28($sp)
    /* B6C 8018FB54 2400B58F */  lw         $s5, 0x24($sp)
    /* B70 8018FB58 2000B48F */  lw         $s4, 0x20($sp)
    /* B74 8018FB5C 1C00B38F */  lw         $s3, 0x1C($sp)
    /* B78 8018FB60 1800B28F */  lw         $s2, 0x18($sp)
    /* B7C 8018FB64 1400B18F */  lw         $s1, 0x14($sp)
    /* B80 8018FB68 1000B08F */  lw         $s0, 0x10($sp)
    /* B84 8018FB6C 3000BD27 */  addiu      $sp, $sp, 0x30
    /* B88 8018FB70 0800E003 */  jr         $ra
    /* B8C 8018FB74 00000000 */   nop
endlabel RoomLib_HandlerD

nonmatching RoomLib_FxNotify, 0xE0

glabel RoomLib_FxNotify
    /* B90 8018FB78 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* B94 8018FB7C 1000B0AF */  sw         $s0, 0x10($sp)
    /* B98 8018FB80 2180A000 */  addu       $s0, $a1, $zero
    /* B9C 8018FB84 1800BFAF */  sw         $ra, 0x18($sp)
    /* BA0 8018FB88 1400B1AF */  sw         $s1, 0x14($sp)
    /* BA4 8018FB8C A2000286 */  lh         $v0, 0xA2($s0)
    /* BA8 8018FB90 00000000 */  nop
    /* BAC 8018FB94 20004018 */  blez       $v0, .L8018FC18
    /* BB0 8018FB98 21888000 */   addu      $s1, $a0, $zero
    /* BB4 8018FB9C 8400038E */  lw         $v1, 0x84($s0)
    /* BB8 8018FBA0 00000000 */  nop
    /* BBC 8018FBA4 07006010 */  beqz       $v1, .L8018FBC4
    /* BC0 8018FBA8 60000426 */   addiu     $a0, $s0, 0x60
    /* BC4 8018FBAC 2800628C */  lw         $v0, 0x28($v1)
    /* BC8 8018FBB0 00000000 */  nop
    /* BCC 8018FBB4 600002AE */  sw         $v0, 0x60($s0)
    /* BD0 8018FBB8 3000628C */  lw         $v0, 0x30($v1)
    /* BD4 8018FBBC 00000000 */  nop
    /* BD8 8018FBC0 680002AE */  sw         $v0, 0x68($s0)
  .L8018FBC4:
    /* BDC 8018FBC4 E07F030C */  jal        FieldEng_VecToAngle
    /* BE0 8018FBC8 28002526 */   addiu     $a1, $s1, 0x28
    /* BE4 8018FBCC 00140200 */  sll        $v0, $v0, 16
    /* BE8 8018FBD0 3A002486 */  lh         $a0, 0x3A($s1)
    /* BEC 8018FBD4 A2000686 */  lh         $a2, 0xA2($s0)
    /* BF0 8018FBD8 EE7F030C */  jal        FieldEng_TurnToward
    /* BF4 8018FBDC 032C0200 */   sra       $a1, $v0, 16
    /* BF8 8018FBE0 FF0F4230 */  andi       $v0, $v0, 0xFFF
    /* BFC 8018FBE4 3A0022A6 */  sh         $v0, 0x3A($s1)
    /* C00 8018FBE8 A9000292 */  lbu        $v0, 0xA9($s0)
    /* C04 8018FBEC 00000000 */  nop
    /* C08 8018FBF0 13004010 */  beqz       $v0, .L8018FC40
    /* C0C 8018FBF4 FF07023C */   lui       $v0, (0x7FFFFFF >> 16)
    /* C10 8018FBF8 9800038E */  lw         $v1, 0x98($s0)
    /* C14 8018FBFC FFFF4234 */  ori        $v0, $v0, (0x7FFFFFF & 0xFFFF)
    /* C18 8018FC00 2A104300 */  slt        $v0, $v0, $v1
    /* C1C 8018FC04 0E004010 */  beqz       $v0, .L8018FC40
    /* C20 8018FC08 00000000 */   nop
    /* C24 8018FC0C A20000A6 */  sh         $zero, 0xA2($s0)
    /* C28 8018FC10 103F0608 */  j          .L8018FC40
    /* C2C 8018FC14 A40000A6 */   sh        $zero, 0xA4($s0)
  .L8018FC18:
    /* C30 8018FC18 28002426 */  addiu      $a0, $s1, 0x28
    /* C34 8018FC1C 40002526 */  addiu      $a1, $s1, 0x40
    /* C38 8018FC20 A57F030C */  jal        func_800DFE94
    /* C3C 8018FC24 38002626 */   addiu     $a2, $s1, 0x38
    /* C40 8018FC28 3A002486 */  lh         $a0, 0x3A($s1)
    /* C44 8018FC2C A4000686 */  lh         $a2, 0xA4($s0)
    /* C48 8018FC30 EE7F030C */  jal        FieldEng_TurnToward
    /* C4C 8018FC34 21288000 */   addu      $a1, $a0, $zero
    /* C50 8018FC38 FF0F4230 */  andi       $v0, $v0, 0xFFF
    /* C54 8018FC3C 3A0022A6 */  sh         $v0, 0x3A($s1)
  .L8018FC40:
    /* C58 8018FC40 1800BF8F */  lw         $ra, 0x18($sp)
    /* C5C 8018FC44 1400B18F */  lw         $s1, 0x14($sp)
    /* C60 8018FC48 1000B08F */  lw         $s0, 0x10($sp)
    /* C64 8018FC4C 2000BD27 */  addiu      $sp, $sp, 0x20
    /* C68 8018FC50 0800E003 */  jr         $ra
    /* C6C 8018FC54 00000000 */   nop
endlabel RoomLib_FxNotify

/* Handwritten function */
nonmatching func_8018FC58, 0x240

glabel func_8018FC58
    /* C70 8018FC58 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* C74 8018FC5C 1400B1AF */  sw         $s1, 0x14($sp)
    /* C78 8018FC60 21888000 */  addu       $s1, $a0, $zero
    /* C7C 8018FC64 1800BFAF */  sw         $ra, 0x18($sp)
    /* C80 8018FC68 1000B0AF */  sw         $s0, 0x10($sp)
    /* C84 8018FC6C 8000228E */  lw         $v0, 0x80($s1)
    /* C88 8018FC70 00000000 */  nop
    /* C8C 8018FC74 0A004010 */  beqz       $v0, .L8018FCA0
    /* C90 8018FC78 2180A000 */   addu      $s0, $a1, $zero
    /* C94 8018FC7C 2800428C */  lw         $v0, 0x28($v0)
    /* C98 8018FC80 8000238E */  lw         $v1, 0x80($s1)
    /* C9C 8018FC84 400022AE */  sw         $v0, 0x40($s1)
    /* CA0 8018FC88 2C00628C */  lw         $v0, 0x2C($v1)
    /* CA4 8018FC8C 8000238E */  lw         $v1, 0x80($s1)
    /* CA8 8018FC90 440022AE */  sw         $v0, 0x44($s1)
    /* CAC 8018FC94 3000628C */  lw         $v0, 0x30($v1)
    /* CB0 8018FC98 00000000 */  nop
    /* CB4 8018FC9C 480022AE */  sw         $v0, 0x48($s1)
  .L8018FCA0:
    /* CB8 8018FCA0 4C00228E */  lw         $v0, 0x4C($s1)
    /* CBC 8018FCA4 00000000 */  nop
    /* CC0 8018FCA8 3A004010 */  beqz       $v0, .L8018FD94
    /* CC4 8018FCAC 50002426 */   addiu     $a0, $s1, 0x50
    /* CC8 8018FCB0 E07F030C */  jal        FieldEng_VecToAngle
    /* CCC 8018FCB4 40002526 */   addiu     $a1, $s1, 0x40
    /* CD0 8018FCB8 FF0F4230 */  andi       $v0, $v0, 0xFFF
    /* CD4 8018FCBC 0980033C */  lui        $v1, %hi(D_800966EC)
    /* CD8 8018FCC0 EC666324 */  addiu      $v1, $v1, %lo(D_800966EC)
    /* CDC 8018FCC4 80100200 */  sll        $v0, $v0, 2
    /* CE0 8018FCC8 21104300 */  addu       $v0, $v0, $v1
    /* CE4 8018FCCC 02004384 */  lh         $v1, 0x2($v0)
    /* CE8 8018FCD0 2A0000A6 */  sh         $zero, 0x2A($s0)
    /* CEC 8018FCD4 280003A6 */  sh         $v1, 0x28($s0)
    /* CF0 8018FCD8 0000428C */  lw         $v0, 0x0($v0)
    /* CF4 8018FCDC 28000496 */  lhu        $a0, 0x28($s0)
    /* CF8 8018FCE0 2E0000A6 */  sh         $zero, 0x2E($s0)
    /* CFC 8018FCE4 320000A6 */  sh         $zero, 0x32($s0)
    /* D00 8018FCE8 360000A6 */  sh         $zero, 0x36($s0)
    /* D04 8018FCEC 000000A6 */  sh         $zero, 0x0($s0)
    /* D08 8018FCF0 020000A6 */  sh         $zero, 0x2($s0)
    /* D0C 8018FCF4 2C0002A6 */  sh         $v0, 0x2C($s0)
    /* D10 8018FCF8 2C000396 */  lhu        $v1, 0x2C($s0)
    /* D14 8018FCFC 00100224 */  addiu      $v0, $zero, 0x1000
    /* D18 8018FD00 300002A6 */  sh         $v0, 0x30($s0)
    /* D1C 8018FD04 380004A6 */  sh         $a0, 0x38($s0)
    /* D20 8018FD08 23180300 */  negu       $v1, $v1
    /* D24 8018FD0C 340003A6 */  sh         $v1, 0x34($s0)
    /* D28 8018FD10 4E002286 */  lh         $v0, 0x4E($s1)
    /* D2C 8018FD14 00000000 */  nop
    /* D30 8018FD18 040002A6 */  sh         $v0, 0x4($s0)
    /* D34 8018FD1C 28000226 */  addiu      $v0, $s0, 0x28
    /* D38 8018FD20 00004C8C */  lw         $t4, 0x0($v0)
    /* D3C 8018FD24 04004D8C */  lw         $t5, 0x4($v0)
    /* D40 8018FD28 0000CC48 */  ctc2       $t4, $0 /* handwritten instruction */
    /* D44 8018FD2C 0008CD48 */  ctc2       $t5, $1 /* handwritten instruction */
    /* D48 8018FD30 08004C8C */  lw         $t4, 0x8($v0)
    /* D4C 8018FD34 0C004D8C */  lw         $t5, 0xC($v0)
    /* D50 8018FD38 10004E8C */  lw         $t6, 0x10($v0)
    /* D54 8018FD3C 0010CC48 */  ctc2       $t4, $2 /* handwritten instruction */
    /* D58 8018FD40 0018CD48 */  ctc2       $t5, $3 /* handwritten instruction */
    /* D5C 8018FD44 0020CE48 */  ctc2       $t6, $4 /* handwritten instruction */
    /* D60 8018FD48 000000CA */  lwc2       $0, 0x0($s0)
    /* D64 8018FD4C 040001CA */  lwc2       $1, 0x4($s0)
    /* D68 8018FD50 00000000 */  nop
    /* D6C 8018FD54 00000000 */  nop
    /* D70 8018FD58 1260484A */  mvmva      1, 0, 0, 3, 0
    /* D74 8018FD5C 08000226 */  addiu      $v0, $s0, 0x8
    /* D78 8018FD60 000059E8 */  swc2       $25, 0x0($v0)
    /* D7C 8018FD64 04005AE8 */  swc2       $26, 0x4($v0) /* handwritten instruction */
    /* D80 8018FD68 08005BE8 */  swc2       $27, 0x8($v0) /* handwritten instruction */
    /* D84 8018FD6C 0800028E */  lw         $v0, 0x8($s0)
    /* D88 8018FD70 5000238E */  lw         $v1, 0x50($s1)
    /* D8C 8018FD74 00140200 */  sll        $v0, $v0, 16
    /* D90 8018FD78 21186200 */  addu       $v1, $v1, $v0
    /* D94 8018FD7C 400023AE */  sw         $v1, 0x40($s1)
    /* D98 8018FD80 1000028E */  lw         $v0, 0x10($s0)
    /* D9C 8018FD84 5800238E */  lw         $v1, 0x58($s1)
    /* DA0 8018FD88 00140200 */  sll        $v0, $v0, 16
    /* DA4 8018FD8C 21186200 */  addu       $v1, $v1, $v0
    /* DA8 8018FD90 480023AE */  sw         $v1, 0x48($s1)
  .L8018FD94:
    /* DAC 8018FD94 50002426 */  addiu      $a0, $s1, 0x50
    /* DB0 8018FD98 E07F030C */  jal        FieldEng_VecToAngle
    /* DB4 8018FD9C 40002526 */   addiu     $a1, $s1, 0x40
    /* DB8 8018FDA0 FF0F4230 */  andi       $v0, $v0, 0xFFF
    /* DBC 8018FDA4 0980033C */  lui        $v1, %hi(D_800966EC)
    /* DC0 8018FDA8 EC666324 */  addiu      $v1, $v1, %lo(D_800966EC)
    /* DC4 8018FDAC 80100200 */  sll        $v0, $v0, 2
    /* DC8 8018FDB0 21104300 */  addu       $v0, $v0, $v1
    /* DCC 8018FDB4 02004384 */  lh         $v1, 0x2($v0)
    /* DD0 8018FDB8 2A0000A6 */  sh         $zero, 0x2A($s0)
    /* DD4 8018FDBC 280003A6 */  sh         $v1, 0x28($s0)
    /* DD8 8018FDC0 0000428C */  lw         $v0, 0x0($v0)
    /* DDC 8018FDC4 28000496 */  lhu        $a0, 0x28($s0)
    /* DE0 8018FDC8 2E0000A6 */  sh         $zero, 0x2E($s0)
    /* DE4 8018FDCC 320000A6 */  sh         $zero, 0x32($s0)
    /* DE8 8018FDD0 360000A6 */  sh         $zero, 0x36($s0)
    /* DEC 8018FDD4 2C0002A6 */  sh         $v0, 0x2C($s0)
    /* DF0 8018FDD8 2C000396 */  lhu        $v1, 0x2C($s0)
    /* DF4 8018FDDC 00100224 */  addiu      $v0, $zero, 0x1000
    /* DF8 8018FDE0 300002A6 */  sh         $v0, 0x30($s0)
    /* DFC 8018FDE4 28000226 */  addiu      $v0, $s0, 0x28
    /* E00 8018FDE8 380004A6 */  sh         $a0, 0x38($s0)
    /* E04 8018FDEC 23180300 */  negu       $v1, $v1
    /* E08 8018FDF0 340003A6 */  sh         $v1, 0x34($s0)
    /* E0C 8018FDF4 00004C8C */  lw         $t4, 0x0($v0)
    /* E10 8018FDF8 04004D8C */  lw         $t5, 0x4($v0)
    /* E14 8018FDFC 0000CC48 */  ctc2       $t4, $0 /* handwritten instruction */
    /* E18 8018FE00 0008CD48 */  ctc2       $t5, $1 /* handwritten instruction */
    /* E1C 8018FE04 08004C8C */  lw         $t4, 0x8($v0)
    /* E20 8018FE08 0C004D8C */  lw         $t5, 0xC($v0)
    /* E24 8018FE0C 10004E8C */  lw         $t6, 0x10($v0)
    /* E28 8018FE10 0010CC48 */  ctc2       $t4, $2 /* handwritten instruction */
    /* E2C 8018FE14 0018CD48 */  ctc2       $t5, $3 /* handwritten instruction */
    /* E30 8018FE18 0020CE48 */  ctc2       $t6, $4 /* handwritten instruction */
    /* E34 8018FE1C 70002226 */  addiu      $v0, $s1, 0x70
    /* E38 8018FE20 000040C8 */  lwc2       $0, 0x0($v0)
    /* E3C 8018FE24 040041C8 */  lwc2       $1, 0x4($v0)
    /* E40 8018FE28 00000000 */  nop
    /* E44 8018FE2C 00000000 */  nop
    /* E48 8018FE30 1260484A */  mvmva      1, 0, 0, 3, 0
    /* E4C 8018FE34 08000226 */  addiu      $v0, $s0, 0x8
    /* E50 8018FE38 000059E8 */  swc2       $25, 0x0($v0)
    /* E54 8018FE3C 04005AE8 */  swc2       $26, 0x4($v0) /* handwritten instruction */
    /* E58 8018FE40 08005BE8 */  swc2       $27, 0x8($v0) /* handwritten instruction */
    /* E5C 8018FE44 0800028E */  lw         $v0, 0x8($s0)
    /* E60 8018FE48 4000238E */  lw         $v1, 0x40($s1)
    /* E64 8018FE4C 00140200 */  sll        $v0, $v0, 16
    /* E68 8018FE50 21186200 */  addu       $v1, $v1, $v0
    /* E6C 8018FE54 400023AE */  sw         $v1, 0x40($s1)
    /* E70 8018FE58 0C00028E */  lw         $v0, 0xC($s0)
    /* E74 8018FE5C 4400238E */  lw         $v1, 0x44($s1)
    /* E78 8018FE60 00140200 */  sll        $v0, $v0, 16
    /* E7C 8018FE64 21186200 */  addu       $v1, $v1, $v0
    /* E80 8018FE68 440023AE */  sw         $v1, 0x44($s1)
    /* E84 8018FE6C 1000028E */  lw         $v0, 0x10($s0)
    /* E88 8018FE70 4800238E */  lw         $v1, 0x48($s1)
    /* E8C 8018FE74 00140200 */  sll        $v0, $v0, 16
    /* E90 8018FE78 21186200 */  addu       $v1, $v1, $v0
    /* E94 8018FE7C 480023AE */  sw         $v1, 0x48($s1)
    /* E98 8018FE80 1800BF8F */  lw         $ra, 0x18($sp)
    /* E9C 8018FE84 1400B18F */  lw         $s1, 0x14($sp)
    /* EA0 8018FE88 1000B08F */  lw         $s0, 0x10($sp)
    /* EA4 8018FE8C 2000BD27 */  addiu      $sp, $sp, 0x20
    /* EA8 8018FE90 0800E003 */  jr         $ra
    /* EAC 8018FE94 00000000 */   nop
endlabel func_8018FC58

nonmatching func_8018FE98, 0x9C

glabel func_8018FE98
    /* EB0 8018FE98 04000524 */  addiu      $a1, $zero, 0x4
    /* EB4 8018FE9C B8008290 */  lbu        $v0, 0xB8($a0)
    /* EB8 8018FEA0 0C008624 */  addiu      $a2, $a0, 0xC
    /* EBC 8018FEA4 000085A0 */  sb         $a1, 0x0($a0)
    /* EC0 8018FEA8 0E004014 */  bnez       $v0, .L8018FEE4
    /* EC4 8018FEAC 030080A0 */   sb        $zero, 0x3($a0)
    /* EC8 8018FEB0 14008284 */  lh         $v0, 0x14($a0)
    /* ECC 8018FEB4 00000000 */  nop
    /* ED0 8018FEB8 17004010 */  beqz       $v0, .L8018FF18
    /* ED4 8018FEBC 00000000 */   nop
    /* ED8 8018FEC0 0800828C */  lw         $v0, 0x8($a0)
    /* EDC 8018FEC4 00000000 */  nop
    /* EE0 8018FEC8 0000428C */  lw         $v0, 0x0($v0)
    /* EE4 8018FECC 00000000 */  nop
    /* EE8 8018FED0 11004010 */  beqz       $v0, .L8018FF18
    /* EEC 8018FED4 00000000 */   nop
    /* EF0 8018FED8 1800428C */  lw         $v0, 0x18($v0)
    /* EF4 8018FEDC C63F0608 */  j          .L8018FF18
    /* EF8 8018FEE0 000045A0 */   sb        $a1, 0x0($v0)
  .L8018FEE4:
    /* EFC 8018FEE4 0800828C */  lw         $v0, 0x8($a0)
    /* F00 8018FEE8 00000000 */  nop
    /* F04 8018FEEC 0000428C */  lw         $v0, 0x0($v0)
    /* F08 8018FEF0 00000000 */  nop
    /* F0C 8018FEF4 08004010 */  beqz       $v0, .L8018FF18
    /* F10 8018FEF8 00000000 */   nop
    /* F14 8018FEFC 1800448C */  lw         $a0, 0x18($v0)
    /* F18 8018FF00 00000000 */  nop
    /* F1C 8018FF04 00008390 */  lbu        $v1, 0x0($a0)
    /* F20 8018FF08 01000224 */  addiu      $v0, $zero, 0x1
    /* F24 8018FF0C 02006214 */  bne        $v1, $v0, .L8018FF18
    /* F28 8018FF10 00000000 */   nop
    /* F2C 8018FF14 000085A0 */  sb         $a1, 0x0($a0)
  .L8018FF18:
    /* F30 8018FF18 0400C28C */  lw         $v0, 0x4($a2)
    /* F34 8018FF1C 00000000 */  nop
    /* F38 8018FF20 02004010 */  beqz       $v0, .L8018FF2C
    /* F3C 8018FF24 00000000 */   nop
    /* F40 8018FF28 000040AC */  sw         $zero, 0x0($v0)
  .L8018FF2C:
    /* F44 8018FF2C 0800E003 */  jr         $ra
    /* F48 8018FF30 21100000 */   addu      $v0, $zero, $zero
endlabel func_8018FE98
