/* CC1_FLAGS: -G8 */
/* MASPSX_FLAGS: -G8 */
/* Function body emitted as asm() (PSYQ GCC 2.7.2 register
 * allocation / scheduling diverges from the ROM pervasively).
 * Wrapped via maspsx's INCLUDE_ASM hack so the body is passed
 * through verbatim; bare global loads gp-rel via the .extern size
 * hints + `as -G8`. See tools/maspsx/PE1_IMPROVEMENTS.md. */
void __maspsx_include_asm_hack_func_8005A318(void);
void __maspsx_include_asm_hack_func_8005A318(void) {
	__asm__(
		"	.extern	g_InvActiveListOverride,1 # maspsx-keep\n"
		"	.extern	g_InvOverrideSlotLimit,1 # maspsx-keep\n"
		"	.extern	g_InvItemPtr,1 # maspsx-keep\n"
		"	.extern	g_InvSelectionBits,1 # maspsx-keep\n"
		"	.extern	g_InvSelectionBitWords,1 # maspsx-keep\n"
		"	.extern	g_InvSlotLimit,1 # maspsx-keep\n"
		"	.set	noreorder # maspsx-keep\n"
		"	.set	nomacro # maspsx-keep\n"
		"	.globl	Inv_TransferItemBetweenLists # maspsx-keep\n"
		"Inv_TransferItemBetweenLists: # maspsx-keep\n"
		"	addiu	$sp,$sp,-0xA0 # maspsx-keep\n"
		"	sw	$s4,0x90($sp) # maspsx-keep\n"
		"	addu	$s4,$a0,$zero # maspsx-keep\n"
		"	sw	$s1,0x84($sp) # maspsx-keep\n"
		"	addu	$s1,$a1,$zero # maspsx-keep\n"
		"	sw	$s5,0x94($sp) # maspsx-keep\n"
		"	addu	$s5,$a2,$zero # maspsx-keep\n"
		"	sw	$s3,0x8C($sp) # maspsx-keep\n"
		"	addu	$s3,$a3,$zero # maspsx-keep\n"
		"	sltiu	$v0,$s4,0x2 # maspsx-keep\n"
		"	sw	$ra,0x98($sp) # maspsx-keep\n"
		"	sw	$s2,0x88($sp) # maspsx-keep\n"
		"	beqz	$v0,.L8005A3E8 # maspsx-keep\n"
		"	sw	$s0,0x80($sp) # maspsx-keep\n"
		"	sll	$v0,$s4,2 # maspsx-keep\n"
		"	lui	$at,%hi(g_InvSavedSelectionFromStorage) # maspsx-keep\n"
		"	addu	$at,$at,$v0 # maspsx-keep\n"
		"	lw	$v0,%lo(g_InvSavedSelectionFromStorage)($at) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	beqz	$v0,.L8005A3A4 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lw	$v0,g_InvActiveListOverride # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	beqz	$v0,.L8005A3A4 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lw	$v1,g_InvOverrideSlotLimit # maspsx-keep\n"
		"	sw	$v0,g_InvItemPtr # maspsx-keep\n"
		"	lui	$v0,%hi(g_InvStorageSelectionBits) # maspsx-keep\n"
		"	addiu	$v0,$v0,%lo(g_InvStorageSelectionBits) # maspsx-keep\n"
		"	sw	$v0,g_InvSelectionBits # maspsx-keep\n"
		"	addiu	$v0,$zero,0x4 # maspsx-keep\n"
		"	sw	$v0,g_InvSelectionBitWords # maspsx-keep\n"
		"	sw	$v1,g_InvSlotLimit # maspsx-keep\n"
		"	j	.L8005A3D4 # maspsx-keep\n"
		"	sll	$v0,$s4,2 # maspsx-keep\n"
		".L8005A3A4: # maspsx-keep\n"
		"	lui	$v0,%hi(g_AyaInventoryItems) # maspsx-keep\n"
		"	addiu	$v0,$v0,%lo(g_AyaInventoryItems) # maspsx-keep\n"
		"	sw	$v0,g_InvItemPtr # maspsx-keep\n"
		"	jal	Inv_GetAyaSlotLimit # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	sw	$v0,g_InvSlotLimit # maspsx-keep\n"
		"	lui	$v0,%hi(g_AyaItemSelectionBits) # maspsx-keep\n"
		"	addiu	$v0,$v0,%lo(g_AyaItemSelectionBits) # maspsx-keep\n"
		"	sw	$v0,g_InvSelectionBits # maspsx-keep\n"
		"	addiu	$v0,$zero,0x2 # maspsx-keep\n"
		"	sw	$v0,g_InvSelectionBitWords # maspsx-keep\n"
		"	sll	$v0,$s4,2 # maspsx-keep\n"
		".L8005A3D4: # maspsx-keep\n"
		"	lui	$at,%hi(g_InvSavedSelectionIndex) # maspsx-keep\n"
		"	addu	$at,$at,$v0 # maspsx-keep\n"
		"	lw	$v1,%lo(g_InvSavedSelectionIndex)($at) # maspsx-keep\n"
		"	j	.L8005A3EC # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L8005A3E8: # maspsx-keep\n"
		"	addiu	$v1,$zero,-0x1 # maspsx-keep\n"
		".L8005A3EC: # maspsx-keep\n"
		"	bltz	$v1,.L8005A484 # maspsx-keep\n"
		"	addu	$s2,$zero,$zero # maspsx-keep\n"
		"	lw	$v0,g_InvSlotLimit # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	slt	$v0,$v1,$v0 # maspsx-keep\n"
		"	beqz	$v0,.L8005A484 # maspsx-keep\n"
		"	sll	$v1,$v1,1 # maspsx-keep\n"
		"	lw	$v0,g_InvItemPtr # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	addu	$v1,$v1,$v0 # maspsx-keep\n"
		"	lh	$v1,0x0($v1) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	addiu	$v0,$v1,-0x100 # maspsx-keep\n"
		"	sltiu	$v0,$v0,0x80 # maspsx-keep\n"
		"	beqz	$v0,.L8005A440 # maspsx-keep\n"
		"	addu	$a1,$v1,$zero # maspsx-keep\n"
		"	sll	$v1,$v1,5 # maspsx-keep\n"
		"	lui	$v0,%hi(g_EquipItemDataTable) # maspsx-keep\n"
		"	addiu	$v0,$v0,%lo(g_EquipItemDataTable) # maspsx-keep\n"
		"	j	.L8005A480 # maspsx-keep\n"
		"	addu	$v0,$v1,$v0 # maspsx-keep\n"
		".L8005A440: # maspsx-keep\n"
		"	addiu	$a0,$v1,-0x1 # maspsx-keep\n"
		"	sltiu	$v0,$a0,0xFF # maspsx-keep\n"
		"	beqz	$v0,.L8005A460 # maspsx-keep\n"
		"	addiu	$v0,$a1,-0x200 # maspsx-keep\n"
		"	jal	Item_LookupBaseData # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	j	.L8005A484 # maspsx-keep\n"
		"	addu	$s2,$v0,$zero # maspsx-keep\n"
		".L8005A460: # maspsx-keep\n"
		"	sltiu	$v0,$v0,0x9 # maspsx-keep\n"
		"	beqz	$v0,.L8005A47C # maspsx-keep\n"
		"	sll	$v1,$a1,5 # maspsx-keep\n"
		"	lui	$v0,%hi(g_KeyItemDataTable) # maspsx-keep\n"
		"	addiu	$v0,$v0,%lo(g_KeyItemDataTable) # maspsx-keep\n"
		"	j	.L8005A480 # maspsx-keep\n"
		"	addu	$v0,$v1,$v0 # maspsx-keep\n"
		".L8005A47C: # maspsx-keep\n"
		"	addu	$v0,$zero,$zero # maspsx-keep\n"
		".L8005A480: # maspsx-keep\n"
		"	addu	$s2,$v0,$zero # maspsx-keep\n"
		".L8005A484: # maspsx-keep\n"
		"	sltiu	$s0,$s4,0x1 # maspsx-keep\n"
		"	sltiu	$v0,$s0,0x2 # maspsx-keep\n"
		"	beqz	$v0,.L8005A528 # maspsx-keep\n"
		"	sll	$v0,$s0,2 # maspsx-keep\n"
		"	lui	$at,%hi(g_InvSavedSelectionFromStorage) # maspsx-keep\n"
		"	addu	$at,$at,$v0 # maspsx-keep\n"
		"	lw	$v0,%lo(g_InvSavedSelectionFromStorage)($at) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	beqz	$v0,.L8005A4E4 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lw	$v0,g_InvActiveListOverride # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	beqz	$v0,.L8005A4E4 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lw	$v1,g_InvOverrideSlotLimit # maspsx-keep\n"
		"	sw	$v0,g_InvItemPtr # maspsx-keep\n"
		"	lui	$v0,%hi(g_InvStorageSelectionBits) # maspsx-keep\n"
		"	addiu	$v0,$v0,%lo(g_InvStorageSelectionBits) # maspsx-keep\n"
		"	sw	$v0,g_InvSelectionBits # maspsx-keep\n"
		"	addiu	$v0,$zero,0x4 # maspsx-keep\n"
		"	sw	$v0,g_InvSelectionBitWords # maspsx-keep\n"
		"	sw	$v1,g_InvSlotLimit # maspsx-keep\n"
		"	j	.L8005A514 # maspsx-keep\n"
		"	sll	$v0,$s0,2 # maspsx-keep\n"
		".L8005A4E4: # maspsx-keep\n"
		"	lui	$v0,%hi(g_AyaInventoryItems) # maspsx-keep\n"
		"	addiu	$v0,$v0,%lo(g_AyaInventoryItems) # maspsx-keep\n"
		"	sw	$v0,g_InvItemPtr # maspsx-keep\n"
		"	jal	Inv_GetAyaSlotLimit # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	sw	$v0,g_InvSlotLimit # maspsx-keep\n"
		"	lui	$v0,%hi(g_AyaItemSelectionBits) # maspsx-keep\n"
		"	addiu	$v0,$v0,%lo(g_AyaItemSelectionBits) # maspsx-keep\n"
		"	sw	$v0,g_InvSelectionBits # maspsx-keep\n"
		"	addiu	$v0,$zero,0x2 # maspsx-keep\n"
		"	sw	$v0,g_InvSelectionBitWords # maspsx-keep\n"
		"	sll	$v0,$s0,2 # maspsx-keep\n"
		".L8005A514: # maspsx-keep\n"
		"	lui	$at,%hi(g_InvSavedSelectionIndex) # maspsx-keep\n"
		"	addu	$at,$at,$v0 # maspsx-keep\n"
		"	lw	$v1,%lo(g_InvSavedSelectionIndex)($at) # maspsx-keep\n"
		"	j	.L8005A52C # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L8005A528: # maspsx-keep\n"
		"	addiu	$v1,$zero,-0x1 # maspsx-keep\n"
		".L8005A52C: # maspsx-keep\n"
		"	bltz	$v1,.L8005A5C4 # maspsx-keep\n"
		"	addu	$a2,$zero,$zero # maspsx-keep\n"
		"	lw	$v0,g_InvSlotLimit # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	slt	$v0,$v1,$v0 # maspsx-keep\n"
		"	beqz	$v0,.L8005A5C4 # maspsx-keep\n"
		"	sll	$v1,$v1,1 # maspsx-keep\n"
		"	lw	$v0,g_InvItemPtr # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	addu	$v1,$v1,$v0 # maspsx-keep\n"
		"	lh	$v1,0x0($v1) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	addiu	$v0,$v1,-0x100 # maspsx-keep\n"
		"	sltiu	$v0,$v0,0x80 # maspsx-keep\n"
		"	beqz	$v0,.L8005A580 # maspsx-keep\n"
		"	addu	$a1,$v1,$zero # maspsx-keep\n"
		"	sll	$v1,$v1,5 # maspsx-keep\n"
		"	lui	$v0,%hi(g_EquipItemDataTable) # maspsx-keep\n"
		"	addiu	$v0,$v0,%lo(g_EquipItemDataTable) # maspsx-keep\n"
		"	j	.L8005A5C0 # maspsx-keep\n"
		"	addu	$v0,$v1,$v0 # maspsx-keep\n"
		".L8005A580: # maspsx-keep\n"
		"	addiu	$a0,$v1,-0x1 # maspsx-keep\n"
		"	sltiu	$v0,$a0,0xFF # maspsx-keep\n"
		"	beqz	$v0,.L8005A5A0 # maspsx-keep\n"
		"	addiu	$v0,$a1,-0x200 # maspsx-keep\n"
		"	jal	Item_LookupBaseData # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	j	.L8005A5C4 # maspsx-keep\n"
		"	addu	$a2,$v0,$zero # maspsx-keep\n"
		".L8005A5A0: # maspsx-keep\n"
		"	sltiu	$v0,$v0,0x9 # maspsx-keep\n"
		"	beqz	$v0,.L8005A5BC # maspsx-keep\n"
		"	sll	$v1,$a1,5 # maspsx-keep\n"
		"	lui	$v0,%hi(g_KeyItemDataTable) # maspsx-keep\n"
		"	addiu	$v0,$v0,%lo(g_KeyItemDataTable) # maspsx-keep\n"
		"	j	.L8005A5C0 # maspsx-keep\n"
		"	addu	$v0,$v1,$v0 # maspsx-keep\n"
		".L8005A5BC: # maspsx-keep\n"
		"	addu	$v0,$zero,$zero # maspsx-keep\n"
		".L8005A5C0: # maspsx-keep\n"
		"	addu	$a2,$v0,$zero # maspsx-keep\n"
		".L8005A5C4: # maspsx-keep\n"
		"	bltz	$s1,.L8005A710 # maspsx-keep\n"
		"	addu	$v0,$s2,$s1 # maspsx-keep\n"
		"	lbu	$a3,0x15($v0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	andi	$a0,$a3,0xE0 # maspsx-keep\n"
		"	beqz	$a0,.L8005A698 # maspsx-keep\n"
		"	addu	$v1,$zero,$zero # maspsx-keep\n"
		"	lbu	$v0,0x14($a2) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	blez	$v0,.L8005A644 # maspsx-keep\n"
		"	addu	$a1,$a0,$zero # maspsx-keep\n"
		"	addu	$a0,$v0,$zero # maspsx-keep\n"
		"	addu	$v0,$a2,$v1 # maspsx-keep\n"
		".L8005A5F8: # maspsx-keep\n"
		"	lbu	$v0,0x15($v0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	andi	$v0,$v0,0xE0 # maspsx-keep\n"
		"	beq	$a1,$v0,.L8005A61C # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	addiu	$v1,$v1,0x1 # maspsx-keep\n"
		"	slt	$v0,$v1,$a0 # maspsx-keep\n"
		"	bnez	$v0,.L8005A5F8 # maspsx-keep\n"
		"	addu	$v0,$a2,$v1 # maspsx-keep\n"
		".L8005A61C: # maspsx-keep\n"
		"	lbu	$v0,0x14($a2) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	slt	$v0,$v1,$v0 # maspsx-keep\n"
		"	beqz	$v0,.L8005A640 # maspsx-keep\n"
		"	addu	$v0,$a2,$v1 # maspsx-keep\n"
		"	sb	$a3,0x15($v0) # maspsx-keep\n"
		"	addu	$v0,$s2,$s1 # maspsx-keep\n"
		"	j	.L8005A93C # maspsx-keep\n"
		"	sb	$zero,0x15($v0) # maspsx-keep\n"
		".L8005A640: # maspsx-keep\n"
		"	lbu	$v0,0x14($a2) # maspsx-keep\n"
		".L8005A644: # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	blez	$v0,.L8005A6FC # maspsx-keep\n"
		"	addu	$a1,$zero,$zero # maspsx-keep\n"
		"	addu	$v1,$v0,$zero # maspsx-keep\n"
		"	addu	$v0,$a2,$a1 # maspsx-keep\n"
		".L8005A658: # maspsx-keep\n"
		"	lbu	$v0,0x15($v0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	andi	$v0,$v0,0x1F # maspsx-keep\n"
		"	beqz	$v0,.L8005A67C # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	addiu	$a1,$a1,0x1 # maspsx-keep\n"
		"	slt	$v0,$a1,$v1 # maspsx-keep\n"
		"	bnez	$v0,.L8005A658 # maspsx-keep\n"
		"	addu	$v0,$a2,$a1 # maspsx-keep\n"
		".L8005A67C: # maspsx-keep\n"
		"	lbu	$v0,0x14($a2) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	slt	$v0,$a1,$v0 # maspsx-keep\n"
		"	bnez	$v0,.L8005A6E8 # maspsx-keep\n"
		"	addu	$a0,$s2,$s1 # maspsx-keep\n"
		"	j	.L8005A700 # maspsx-keep\n"
		"	addiu	$a0,$zero,0x7 # maspsx-keep\n"
		".L8005A698: # maspsx-keep\n"
		"	lbu	$v0,0x14($a2) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	blez	$v0,.L8005A6FC # maspsx-keep\n"
		"	addu	$a1,$zero,$zero # maspsx-keep\n"
		"	addu	$v1,$v0,$zero # maspsx-keep\n"
		"	addu	$v0,$a2,$a1 # maspsx-keep\n"
		".L8005A6B0: # maspsx-keep\n"
		"	lbu	$v0,0x15($v0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	andi	$v0,$v0,0x1F # maspsx-keep\n"
		"	beqz	$v0,.L8005A6D4 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	addiu	$a1,$a1,0x1 # maspsx-keep\n"
		"	slt	$v0,$a1,$v1 # maspsx-keep\n"
		"	bnez	$v0,.L8005A6B0 # maspsx-keep\n"
		"	addu	$v0,$a2,$a1 # maspsx-keep\n"
		".L8005A6D4: # maspsx-keep\n"
		"	lbu	$v0,0x14($a2) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	slt	$v0,$a1,$v0 # maspsx-keep\n"
		"	beqz	$v0,.L8005A6FC # maspsx-keep\n"
		"	addu	$a0,$s2,$s1 # maspsx-keep\n"
		".L8005A6E8: # maspsx-keep\n"
		"	lbu	$v1,0x15($a0) # maspsx-keep\n"
		"	addu	$v0,$a2,$a1 # maspsx-keep\n"
		"	sb	$v1,0x15($v0) # maspsx-keep\n"
		"	j	.L8005A93C # maspsx-keep\n"
		"	sb	$zero,0x15($a0) # maspsx-keep\n"
		".L8005A6FC: # maspsx-keep\n"
		"	addiu	$a0,$zero,0x7 # maspsx-keep\n"
		".L8005A700: # maspsx-keep\n"
		"	jal	Menu_CreateNotificationDialog # maspsx-keep\n"
		"	addu	$a1,$zero,$zero # maspsx-keep\n"
		"	j	.L8005A940 # maspsx-keep\n"
		"	slti	$v0,$s3,0x3E7 # maspsx-keep\n"
		".L8005A710: # maspsx-keep\n"
		"	lh	$v0,0xE($s2) # maspsx-keep\n"
		"	lh	$v1,0xE($a2) # maspsx-keep\n"
		"	addu	$a1,$v0,$zero # maspsx-keep\n"
		"	addu	$v0,$v0,$v1 # maspsx-keep\n"
		"	slti	$v0,$v0,0x3E8 # maspsx-keep\n"
		"	beqz	$v0,.L8005A734 # maspsx-keep\n"
		"	addu	$a0,$v1,$zero # maspsx-keep\n"
		"	j	.L8005A738 # maspsx-keep\n"
		"	addu	$v0,$a1,$a0 # maspsx-keep\n"
		".L8005A734: # maspsx-keep\n"
		"	addiu	$v0,$zero,0x3E7 # maspsx-keep\n"
		".L8005A738: # maspsx-keep\n"
		"	sh	$v0,0xE($a2) # maspsx-keep\n"
		"	lh	$v0,0x10($s2) # maspsx-keep\n"
		"	lh	$v1,0x10($a2) # maspsx-keep\n"
		"	addu	$a1,$v0,$zero # maspsx-keep\n"
		"	addu	$v0,$v0,$v1 # maspsx-keep\n"
		"	slti	$v0,$v0,0x3E8 # maspsx-keep\n"
		"	beqz	$v0,.L8005A760 # maspsx-keep\n"
		"	addu	$a0,$v1,$zero # maspsx-keep\n"
		"	j	.L8005A764 # maspsx-keep\n"
		"	addu	$v0,$a1,$a0 # maspsx-keep\n"
		".L8005A760: # maspsx-keep\n"
		"	addiu	$v0,$zero,0x3E7 # maspsx-keep\n"
		".L8005A764: # maspsx-keep\n"
		"	sh	$v0,0x10($a2) # maspsx-keep\n"
		"	lh	$v0,0x12($s2) # maspsx-keep\n"
		"	lh	$v1,0x12($a2) # maspsx-keep\n"
		"	addu	$a1,$v0,$zero # maspsx-keep\n"
		"	addu	$v0,$v0,$v1 # maspsx-keep\n"
		"	slti	$v0,$v0,0x3E8 # maspsx-keep\n"
		"	beqz	$v0,.L8005A78C # maspsx-keep\n"
		"	addu	$a0,$v1,$zero # maspsx-keep\n"
		"	j	.L8005A790 # maspsx-keep\n"
		"	addu	$v0,$a1,$a0 # maspsx-keep\n"
		".L8005A78C: # maspsx-keep\n"
		"	addiu	$v0,$zero,0x3E7 # maspsx-keep\n"
		".L8005A790: # maspsx-keep\n"
		"	sh	$v0,0x12($a2) # maspsx-keep\n"
		"	lbu	$v1,0x6($s2) # maspsx-keep\n"
		"	addiu	$v0,$zero,0x9 # maspsx-keep\n"
		"	sh	$zero,0xE($s2) # maspsx-keep\n"
		"	sh	$zero,0x10($s2) # maspsx-keep\n"
		"	beq	$v1,$v0,.L8005A93C # maspsx-keep\n"
		"	sh	$zero,0x12($s2) # maspsx-keep\n"
		"	lbu	$a1,0x9($s2) # maspsx-keep\n"
		"	lhu	$a0,0xA($s2) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	sltu	$v0,$a1,$a0 # maspsx-keep\n"
		"	beqz	$v0,.L8005A93C # maspsx-keep\n"
		"	subu	$a1,$a0,$a1 # maspsx-keep\n"
		"	lbu	$v0,0x9($a2) # maspsx-keep\n"
		"	lh	$v1,0x12($a2) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	addu	$a0,$v0,$v1 # maspsx-keep\n"
		"	slti	$v0,$a0,0x3E8 # maspsx-keep\n"
		"	lhu	$v1,0xA($a2) # maspsx-keep\n"
		"	beqz	$v0,.L8005A7F8 # maspsx-keep\n"
		"	subu	$v0,$a0,$v1 # maspsx-keep\n"
		"	slt	$v0,$v0,$a1 # maspsx-keep\n"
		"	beqz	$v0,.L8005A838 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	j	.L8005A80C # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L8005A7F8: # maspsx-keep\n"
		"	addiu	$v0,$zero,0x3E7 # maspsx-keep\n"
		"	subu	$v0,$v0,$v1 # maspsx-keep\n"
		"	slt	$v0,$v0,$a1 # maspsx-keep\n"
		"	beqz	$v0,.L8005A838 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L8005A80C: # maspsx-keep\n"
		"	lbu	$v0,0x9($a2) # maspsx-keep\n"
		"	lh	$v1,0x12($a2) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	addu	$a0,$v0,$v1 # maspsx-keep\n"
		"	slti	$v0,$a0,0x3E8 # maspsx-keep\n"
		"	lhu	$v1,0xA($a2) # maspsx-keep\n"
		"	bnez	$v0,.L8005A848 # maspsx-keep\n"
		"	subu	$a0,$a0,$v1 # maspsx-keep\n"
		"	addiu	$v0,$zero,0x3E7 # maspsx-keep\n"
		"	j	.L8005A848 # maspsx-keep\n"
		"	subu	$a0,$v0,$v1 # maspsx-keep\n"
		".L8005A838: # maspsx-keep\n"
		"	lhu	$v1,0xA($s2) # maspsx-keep\n"
		"	lbu	$v0,0x9($s2) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	subu	$a0,$v1,$v0 # maspsx-keep\n"
		".L8005A848: # maspsx-keep\n"
		"	lhu	$v0,0xA($a2) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	addu	$v0,$v0,$a0 # maspsx-keep\n"
		"	sh	$v0,0xA($a2) # maspsx-keep\n"
		"	lbu	$v1,0x6($s2) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	beqz	$v1,.L8005A88C # maspsx-keep\n"
		"	sltiu	$v0,$v1,0x8 # maspsx-keep\n"
		"	beqz	$v0,.L8005A88C # maspsx-keep\n"
		"	addiu	$v0,$v1,-0x4 # maspsx-keep\n"
		"	lui	$a1,%hi(g_InvItemIconTable) # maspsx-keep\n"
		"	addiu	$a1,$a1,%lo(g_InvItemIconTable) # maspsx-keep\n"
		"	blez	$v0,.L8005A8B4 # maspsx-keep\n"
		"	addiu	$v0,$v1,-0x5 # maspsx-keep\n"
		"	sll	$v0,$v0,5 # maspsx-keep\n"
		"	j	.L8005A8B4 # maspsx-keep\n"
		"	addu	$a1,$v0,$a1 # maspsx-keep\n"
		".L8005A88C: # maspsx-keep\n"
		"	sltiu	$v0,$v1,0x13 # maspsx-keep\n"
		"	bnez	$v0,.L8005A8AC # maspsx-keep\n"
		"	addiu	$v0,$v1,-0x13 # maspsx-keep\n"
		"	sll	$v0,$v0,5 # maspsx-keep\n"
		"	lui	$v1,%hi(g_InvItemIconTable) # maspsx-keep\n"
		"	addiu	$v1,$v1,%lo(g_InvItemIconTable) # maspsx-keep\n"
		"	j	.L8005A8B4 # maspsx-keep\n"
		"	addu	$a1,$v0,$v1 # maspsx-keep\n"
		".L8005A8AC: # maspsx-keep\n"
		"	lui	$a1,%hi(g_InvDefaultItemIconEntry) # maspsx-keep\n"
		"	addiu	$a1,$a1,%lo(g_InvDefaultItemIconEntry) # maspsx-keep\n"
		".L8005A8B4: # maspsx-keep\n"
		"	lbu	$v1,0x9($s2) # maspsx-keep\n"
		"	lhu	$v0,0xA($s2) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	subu	$v0,$v0,$v1 # maspsx-keep\n"
		"	subu	$v0,$v0,$a0 # maspsx-keep\n"
		"	lhu	$v1,0xA($a1) # maspsx-keep\n"
		"	lbu	$a0,0x9($a1) # maspsx-keep\n"
		"	addu	$v1,$v1,$v0 # maspsx-keep\n"
		"	lh	$v0,0x12($a1) # maspsx-keep\n"
		"	sh	$v1,0xA($a1) # maspsx-keep\n"
		"	addu	$a0,$a0,$v0 # maspsx-keep\n"
		"	slti	$v0,$a0,0x3E8 # maspsx-keep\n"
		"	beqz	$v0,.L8005A900 # maspsx-keep\n"
		"	andi	$v1,$v1,0xFFFF # maspsx-keep\n"
		"	slt	$v0,$a0,$v1 # maspsx-keep\n"
		"	beqz	$v0,.L8005A930 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	j	.L8005A90C # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L8005A900: # maspsx-keep\n"
		"	slti	$v0,$v1,0x3E8 # maspsx-keep\n"
		"	bnez	$v0,.L8005A930 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L8005A90C: # maspsx-keep\n"
		"	lh	$v0,0x12($a1) # maspsx-keep\n"
		"	lbu	$a0,0x9($a1) # maspsx-keep\n"
		"	addu	$v1,$v0,$zero # maspsx-keep\n"
		"	addu	$v0,$a0,$v0 # maspsx-keep\n"
		"	slti	$v0,$v0,0x3E8 # maspsx-keep\n"
		"	bnez	$v0,.L8005A92C # maspsx-keep\n"
		"	addu	$v0,$v1,$a0 # maspsx-keep\n"
		"	addiu	$v0,$zero,0x3E7 # maspsx-keep\n"
		".L8005A92C: # maspsx-keep\n"
		"	sh	$v0,0xA($a1) # maspsx-keep\n"
		".L8005A930: # maspsx-keep\n"
		"	lbu	$v0,0x9($s2) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	sh	$v0,0xA($s2) # maspsx-keep\n"
		".L8005A93C: # maspsx-keep\n"
		"	slti	$v0,$s3,0x3E7 # maspsx-keep\n"
		".L8005A940: # maspsx-keep\n"
		"	beqz	$v0,.L8005AB88 # maspsx-keep\n"
		"	andi	$v0,$s5,0x1 # maspsx-keep\n"
		"	beqz	$v0,.L8005A954 # maspsx-keep\n"
		"	addiu	$s3,$zero,0xC # maspsx-keep\n"
		"	addiu	$s3,$zero,0xD # maspsx-keep\n"
		".L8005A954: # maspsx-keep\n"
		"	andi	$v0,$s5,0x2 # maspsx-keep\n"
		"	beqz	$v0,.L8005A9C0 # maspsx-keep\n"
		"	addu	$s1,$zero,$zero # maspsx-keep\n"
		"	lui	$s0,%hi(g_WayneStorageItems) # maspsx-keep\n"
		"	addiu	$s0,$s0,%lo(g_WayneStorageItems) # maspsx-keep\n"
		".L8005A968: # maspsx-keep\n"
		"	lh	$a0,0x0($s0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	beqz	$a0,.L8005A990 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	jal	Item_LookupBaseData # maspsx-keep\n"
		"	addiu	$a0,$a0,-0x1 # maspsx-keep\n"
		"	lbu	$v0,0x6($v0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	beq	$v0,$s3,.L8005A9A4 # maspsx-keep\n"
		"	slti	$v0,$s1,0x64 # maspsx-keep\n"
		".L8005A990: # maspsx-keep\n"
		"	addiu	$s1,$s1,0x1 # maspsx-keep\n"
		"	slti	$v0,$s1,0x64 # maspsx-keep\n"
		"	bnez	$v0,.L8005A968 # maspsx-keep\n"
		"	addiu	$s0,$s0,0x2 # maspsx-keep\n"
		"	slti	$v0,$s1,0x64 # maspsx-keep\n"
		".L8005A9A4: # maspsx-keep\n"
		"	beqz	$v0,.L8005AB88 # maspsx-keep\n"
		"	sll	$v0,$s1,1 # maspsx-keep\n"
		"	lui	$at,%hi(g_WayneStorageItems) # maspsx-keep\n"
		"	addu	$at,$at,$v0 # maspsx-keep\n"
		"	sh	$zero,%lo(g_WayneStorageItems)($at) # maspsx-keep\n"
		"	j	.L8005AB8C # maspsx-keep\n"
		"	andi	$v0,$s5,0x1 # maspsx-keep\n"
		".L8005A9C0: # maspsx-keep\n"
		"	lui	$v0,%hi(g_AyaInventoryItems) # maspsx-keep\n"
		"	addiu	$v0,$v0,%lo(g_AyaInventoryItems) # maspsx-keep\n"
		"	sw	$v0,g_InvItemPtr # maspsx-keep\n"
		"	jal	Inv_GetAyaSlotLimit # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lui	$v1,%hi(g_AyaItemSelectionBits) # maspsx-keep\n"
		"	addiu	$v1,$v1,%lo(g_AyaItemSelectionBits) # maspsx-keep\n"
		"	sw	$v1,g_InvSelectionBits # maspsx-keep\n"
		"	addiu	$v1,$zero,0x2 # maspsx-keep\n"
		"	sw	$v0,g_InvSlotLimit # maspsx-keep\n"
		"	sw	$v1,g_InvSelectionBitWords # maspsx-keep\n"
		"	blez	$v0,.L8005AB8C # maspsx-keep\n"
		"	andi	$v0,$s5,0x1 # maspsx-keep\n"
		".L8005A9F4: # maspsx-keep\n"
		"	bltz	$s1,.L8005AA88 # maspsx-keep\n"
		"	addu	$v0,$zero,$zero # maspsx-keep\n"
		"	lw	$v0,g_InvSlotLimit # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	slt	$v0,$s1,$v0 # maspsx-keep\n"
		"	beqz	$v0,.L8005AA84 # maspsx-keep\n"
		"	sll	$v1,$s1,1 # maspsx-keep\n"
		"	lw	$v0,g_InvItemPtr # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	addu	$v1,$v1,$v0 # maspsx-keep\n"
		"	lh	$v1,0x0($v1) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	addiu	$v0,$v1,-0x100 # maspsx-keep\n"
		"	sltiu	$v0,$v0,0x80 # maspsx-keep\n"
		"	beqz	$v0,.L8005AA48 # maspsx-keep\n"
		"	addu	$a1,$v1,$zero # maspsx-keep\n"
		"	sll	$v1,$v1,5 # maspsx-keep\n"
		"	lui	$v0,%hi(g_EquipItemDataTable) # maspsx-keep\n"
		"	addiu	$v0,$v0,%lo(g_EquipItemDataTable) # maspsx-keep\n"
		"	j	.L8005AA88 # maspsx-keep\n"
		"	addu	$v0,$v1,$v0 # maspsx-keep\n"
		".L8005AA48: # maspsx-keep\n"
		"	addiu	$a0,$v1,-0x1 # maspsx-keep\n"
		"	sltiu	$v0,$a0,0xFF # maspsx-keep\n"
		"	beqz	$v0,.L8005AA68 # maspsx-keep\n"
		"	addiu	$v0,$a1,-0x200 # maspsx-keep\n"
		"	jal	Item_LookupBaseData # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	j	.L8005AA88 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L8005AA68: # maspsx-keep\n"
		"	sltiu	$v0,$v0,0x9 # maspsx-keep\n"
		"	beqz	$v0,.L8005AA84 # maspsx-keep\n"
		"	sll	$v1,$a1,5 # maspsx-keep\n"
		"	lui	$v0,%hi(g_KeyItemDataTable) # maspsx-keep\n"
		"	addiu	$v0,$v0,%lo(g_KeyItemDataTable) # maspsx-keep\n"
		"	j	.L8005AA88 # maspsx-keep\n"
		"	addu	$v0,$v1,$v0 # maspsx-keep\n"
		".L8005AA84: # maspsx-keep\n"
		"	addu	$v0,$zero,$zero # maspsx-keep\n"
		".L8005AA88: # maspsx-keep\n"
		"	beqz	$v0,.L8005AA9C # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lbu	$v0,0x6($v0) # maspsx-keep\n"
		"	j	.L8005AAA0 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L8005AA9C: # maspsx-keep\n"
		"	addu	$v0,$zero,$zero # maspsx-keep\n"
		".L8005AAA0: # maspsx-keep\n"
		"	beq	$v0,$s3,.L8005AABC # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lw	$v0,g_InvSlotLimit # maspsx-keep\n"
		"	addiu	$s1,$s1,0x1 # maspsx-keep\n"
		"	slt	$v0,$s1,$v0 # maspsx-keep\n"
		"	bnez	$v0,.L8005A9F4 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L8005AABC: # maspsx-keep\n"
		"	lw	$v0,g_InvSlotLimit # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	slt	$v0,$s1,$v0 # maspsx-keep\n"
		"	beqz	$v0,.L8005AB8C # maspsx-keep\n"
		"	andi	$v0,$s5,0x1 # maspsx-keep\n"
		"	lw	$v1,g_InvItemPtr # maspsx-keep\n"
		"	lui	$v0,%hi(g_AyaInventoryItems) # maspsx-keep\n"
		"	addiu	$v0,$v0,%lo(g_AyaInventoryItems) # maspsx-keep\n"
		"	bne	$v1,$v0,.L8005AB00 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lui	$v0,%hi(g_AyaEquippedArmorSlot) # maspsx-keep\n"
		"	lb	$v0,%lo(g_AyaEquippedArmorSlot)($v0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	bne	$v0,$s1,.L8005AB00 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	jal	Inv_GetActiveSlotCount # maspsx-keep\n"
		"	addiu	$a0,$sp,0x10 # maspsx-keep\n"
		".L8005AB00: # maspsx-keep\n"
		"	lw	$v0,g_InvItemPtr # maspsx-keep\n"
		"	sll	$v1,$s1,1 # maspsx-keep\n"
		"	addu	$v1,$v1,$v0 # maspsx-keep\n"
		"	lh	$a0,0x0($v1) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	slti	$v0,$a0,0x100 # maspsx-keep\n"
		"	bnez	$v0,.L8005AB34 # maspsx-keep\n"
		"	sh	$zero,0x0($v1) # maspsx-keep\n"
		"	addiu	$v0,$a0,-0x100 # maspsx-keep\n"
		"	sll	$v0,$v0,5 # maspsx-keep\n"
		"	lui	$at,%hi(g_InvItemSlotArray) # maspsx-keep\n"
		"	addu	$at,$at,$v0 # maspsx-keep\n"
		"	sb	$zero,%lo(g_InvItemSlotArray)($at) # maspsx-keep\n"
		".L8005AB34: # maspsx-keep\n"
		"	lw	$v1,g_InvItemPtr # maspsx-keep\n"
		"	lui	$v0,%hi(g_AyaInventoryItems) # maspsx-keep\n"
		"	addiu	$v0,$v0,%lo(g_AyaInventoryItems) # maspsx-keep\n"
		"	bne	$v1,$v0,.L8005AB8C # maspsx-keep\n"
		"	andi	$v0,$s5,0x1 # maspsx-keep\n"
		"	lui	$v0,%hi(g_AyaEquippedArmorSlot) # maspsx-keep\n"
		"	lb	$v0,%lo(g_AyaEquippedArmorSlot)($v0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	bne	$v0,$s1,.L8005AB8C # maspsx-keep\n"
		"	andi	$v0,$s5,0x1 # maspsx-keep\n"
		"	lw	$a0,0x10($sp) # maspsx-keep\n"
		"	addiu	$v0,$zero,-0x1 # maspsx-keep\n"
		"	lui	$at,%hi(g_AyaEquippedArmorSlot) # maspsx-keep\n"
		"	sb	$v0,%lo(g_AyaEquippedArmorSlot)($at) # maspsx-keep\n"
		"	jal	Inv_CheckFreeSlotCapacity # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	jal	Inv_CompactActiveListSlots # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	addiu	$a0,$zero,0x3 # maspsx-keep\n"
		"	jal	Inv_SetActiveList # maspsx-keep\n"
		"	addu	$a1,$zero,$zero # maspsx-keep\n"
		".L8005AB88: # maspsx-keep\n"
		"	andi	$v0,$s5,0x1 # maspsx-keep\n"
		".L8005AB8C: # maspsx-keep\n"
		"	bnez	$v0,.L8005AFD4 # maspsx-keep\n"
		"	sltiu	$v0,$s4,0x2 # maspsx-keep\n"
		"	beqz	$v0,.L8005AC30 # maspsx-keep\n"
		"	sll	$v0,$s4,2 # maspsx-keep\n"
		"	lui	$at,%hi(g_InvSavedSelectionFromStorage) # maspsx-keep\n"
		"	addu	$at,$at,$v0 # maspsx-keep\n"
		"	lw	$v0,%lo(g_InvSavedSelectionFromStorage)($at) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	beqz	$v0,.L8005ABEC # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lw	$v0,g_InvActiveListOverride # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	beqz	$v0,.L8005ABEC # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lw	$v1,g_InvOverrideSlotLimit # maspsx-keep\n"
		"	sw	$v0,g_InvItemPtr # maspsx-keep\n"
		"	lui	$v0,%hi(g_InvStorageSelectionBits) # maspsx-keep\n"
		"	addiu	$v0,$v0,%lo(g_InvStorageSelectionBits) # maspsx-keep\n"
		"	sw	$v0,g_InvSelectionBits # maspsx-keep\n"
		"	addiu	$v0,$zero,0x4 # maspsx-keep\n"
		"	sw	$v0,g_InvSelectionBitWords # maspsx-keep\n"
		"	sw	$v1,g_InvSlotLimit # maspsx-keep\n"
		"	j	.L8005AC1C # maspsx-keep\n"
		"	sll	$v0,$s4,2 # maspsx-keep\n"
		".L8005ABEC: # maspsx-keep\n"
		"	lui	$v0,%hi(g_AyaInventoryItems) # maspsx-keep\n"
		"	addiu	$v0,$v0,%lo(g_AyaInventoryItems) # maspsx-keep\n"
		"	sw	$v0,g_InvItemPtr # maspsx-keep\n"
		"	jal	Inv_GetAyaSlotLimit # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	sw	$v0,g_InvSlotLimit # maspsx-keep\n"
		"	lui	$v0,%hi(g_AyaItemSelectionBits) # maspsx-keep\n"
		"	addiu	$v0,$v0,%lo(g_AyaItemSelectionBits) # maspsx-keep\n"
		"	sw	$v0,g_InvSelectionBits # maspsx-keep\n"
		"	addiu	$v0,$zero,0x2 # maspsx-keep\n"
		"	sw	$v0,g_InvSelectionBitWords # maspsx-keep\n"
		"	sll	$v0,$s4,2 # maspsx-keep\n"
		".L8005AC1C: # maspsx-keep\n"
		"	lui	$at,%hi(g_InvSavedSelectionIndex) # maspsx-keep\n"
		"	addu	$at,$at,$v0 # maspsx-keep\n"
		"	lw	$s1,%lo(g_InvSavedSelectionIndex)($at) # maspsx-keep\n"
		"	j	.L8005AC34 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L8005AC30: # maspsx-keep\n"
		"	addiu	$s1,$zero,-0x1 # maspsx-keep\n"
		".L8005AC34: # maspsx-keep\n"
		"	lbu	$v1,0x6($s2) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	beqz	$v1,.L8005AC68 # maspsx-keep\n"
		"	sltiu	$v0,$v1,0x8 # maspsx-keep\n"
		"	beqz	$v0,.L8005AC68 # maspsx-keep\n"
		"	addiu	$v0,$v1,-0x4 # maspsx-keep\n"
		"	lui	$a1,%hi(g_InvItemIconTable) # maspsx-keep\n"
		"	addiu	$a1,$a1,%lo(g_InvItemIconTable) # maspsx-keep\n"
		"	blez	$v0,.L8005AC90 # maspsx-keep\n"
		"	addiu	$v0,$v1,-0x5 # maspsx-keep\n"
		"	sll	$v0,$v0,5 # maspsx-keep\n"
		"	j	.L8005AC90 # maspsx-keep\n"
		"	addu	$a1,$v0,$a1 # maspsx-keep\n"
		".L8005AC68: # maspsx-keep\n"
		"	sltiu	$v0,$v1,0x13 # maspsx-keep\n"
		"	bnez	$v0,.L8005AC88 # maspsx-keep\n"
		"	addiu	$v0,$v1,-0x13 # maspsx-keep\n"
		"	sll	$v0,$v0,5 # maspsx-keep\n"
		"	lui	$v1,%hi(g_InvItemIconTable) # maspsx-keep\n"
		"	addiu	$v1,$v1,%lo(g_InvItemIconTable) # maspsx-keep\n"
		"	j	.L8005AC90 # maspsx-keep\n"
		"	addu	$a1,$v0,$v1 # maspsx-keep\n"
		".L8005AC88: # maspsx-keep\n"
		"	lui	$a1,%hi(g_InvDefaultItemIconEntry) # maspsx-keep\n"
		"	addiu	$a1,$a1,%lo(g_InvDefaultItemIconEntry) # maspsx-keep\n"
		".L8005AC90: # maspsx-keep\n"
		"	lhu	$v1,0xA($a1) # maspsx-keep\n"
		"	lhu	$v0,0xA($s2) # maspsx-keep\n"
		"	lbu	$a0,0x9($a1) # maspsx-keep\n"
		"	addu	$v1,$v1,$v0 # maspsx-keep\n"
		"	lh	$v0,0x12($a1) # maspsx-keep\n"
		"	sh	$v1,0xA($a1) # maspsx-keep\n"
		"	addu	$a0,$a0,$v0 # maspsx-keep\n"
		"	slti	$v0,$a0,0x3E8 # maspsx-keep\n"
		"	beqz	$v0,.L8005ACCC # maspsx-keep\n"
		"	andi	$v1,$v1,0xFFFF # maspsx-keep\n"
		"	slt	$v0,$a0,$v1 # maspsx-keep\n"
		"	beqz	$v0,.L8005ACFC # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	j	.L8005ACD8 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L8005ACCC: # maspsx-keep\n"
		"	slti	$v0,$v1,0x3E8 # maspsx-keep\n"
		"	bnez	$v0,.L8005ACFC # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L8005ACD8: # maspsx-keep\n"
		"	lh	$v0,0x12($a1) # maspsx-keep\n"
		"	lbu	$a0,0x9($a1) # maspsx-keep\n"
		"	addu	$v1,$v0,$zero # maspsx-keep\n"
		"	addu	$v0,$a0,$v0 # maspsx-keep\n"
		"	slti	$v0,$v0,0x3E8 # maspsx-keep\n"
		"	bnez	$v0,.L8005ACF8 # maspsx-keep\n"
		"	addu	$v0,$v1,$a0 # maspsx-keep\n"
		"	addiu	$v0,$zero,0x3E7 # maspsx-keep\n"
		".L8005ACF8: # maspsx-keep\n"
		"	sh	$v0,0xA($a1) # maspsx-keep\n"
		".L8005ACFC: # maspsx-keep\n"
		"	lw	$v1,g_InvItemPtr # maspsx-keep\n"
		"	lui	$v0,%hi(g_AyaInventoryItems) # maspsx-keep\n"
		"	addiu	$v0,$v0,%lo(g_AyaInventoryItems) # maspsx-keep\n"
		"	bne	$v1,$v0,.L8005AD2C # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lui	$v0,%hi(g_AyaEquippedArmorSlot) # maspsx-keep\n"
		"	lb	$v0,%lo(g_AyaEquippedArmorSlot)($v0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	bne	$v0,$s1,.L8005AD2C # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	jal	Inv_GetActiveSlotCount # maspsx-keep\n"
		"	addiu	$a0,$sp,0x10 # maspsx-keep\n"
		".L8005AD2C: # maspsx-keep\n"
		"	lw	$v0,g_InvItemPtr # maspsx-keep\n"
		"	sll	$v1,$s1,1 # maspsx-keep\n"
		"	addu	$v1,$v1,$v0 # maspsx-keep\n"
		"	lh	$a0,0x0($v1) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	slti	$v0,$a0,0x100 # maspsx-keep\n"
		"	bnez	$v0,.L8005AD60 # maspsx-keep\n"
		"	sh	$zero,0x0($v1) # maspsx-keep\n"
		"	addiu	$v0,$a0,-0x100 # maspsx-keep\n"
		"	sll	$v0,$v0,5 # maspsx-keep\n"
		"	lui	$at,%hi(g_InvItemSlotArray) # maspsx-keep\n"
		"	addu	$at,$at,$v0 # maspsx-keep\n"
		"	sb	$zero,%lo(g_InvItemSlotArray)($at) # maspsx-keep\n"
		".L8005AD60: # maspsx-keep\n"
		"	lw	$v0,g_InvItemPtr # maspsx-keep\n"
		"	lui	$s0,%hi(g_AyaInventoryItems) # maspsx-keep\n"
		"	addiu	$s0,$s0,%lo(g_AyaInventoryItems) # maspsx-keep\n"
		"	bne	$v0,$s0,.L8005AFD4 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lui	$v0,%hi(g_AyaEquippedArmorSlot) # maspsx-keep\n"
		"	lb	$v0,%lo(g_AyaEquippedArmorSlot)($v0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	bne	$v0,$s1,.L8005ADB0 # maspsx-keep\n"
		"	addiu	$v0,$zero,-0x1 # maspsx-keep\n"
		"	lw	$a0,0x10($sp) # maspsx-keep\n"
		"	lui	$at,%hi(g_AyaEquippedArmorSlot) # maspsx-keep\n"
		"	sb	$v0,%lo(g_AyaEquippedArmorSlot)($at) # maspsx-keep\n"
		"	jal	Inv_CheckFreeSlotCapacity # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	jal	Inv_CompactActiveListSlots # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	addiu	$a0,$zero,0x3 # maspsx-keep\n"
		"	jal	Inv_SetActiveList # maspsx-keep\n"
		"	addu	$a1,$zero,$zero # maspsx-keep\n"
		".L8005ADB0: # maspsx-keep\n"
		"	lw	$v1,g_InvItemPtr # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	bne	$v1,$s0,.L8005AFD4 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lui	$v0,%hi(g_AyaEquippedWeaponSlot) # maspsx-keep\n"
		"	lb	$v0,%lo(g_AyaEquippedWeaponSlot)($v0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	bne	$v0,$s1,.L8005AED0 # maspsx-keep\n"
		"	addu	$s0,$v1,$zero # maspsx-keep\n"
		"	addiu	$s2,$zero,0x8 # maspsx-keep\n"
		"	lw	$v0,g_InvSlotLimit # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	sll	$v0,$v0,1 # maspsx-keep\n"
		"	addu	$v0,$s0,$v0 # maspsx-keep\n"
		"	sltu	$v0,$s0,$v0 # maspsx-keep\n"
		"	beqz	$v0,.L8005AEBC # maspsx-keep\n"
		"	addiu	$s1,$s0,-0x2 # maspsx-keep\n"
		".L8005ADF4: # maspsx-keep\n"
		"	beq	$s0,$s1,.L8005AE78 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lh	$v1,0x0($s0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	addiu	$v0,$v1,-0x100 # maspsx-keep\n"
		"	sltiu	$v0,$v0,0x80 # maspsx-keep\n"
		"	beqz	$v0,.L8005AE28 # maspsx-keep\n"
		"	addu	$a1,$v1,$zero # maspsx-keep\n"
		"	sll	$v1,$v1,5 # maspsx-keep\n"
		"	lui	$v0,%hi(g_EquipItemDataTable) # maspsx-keep\n"
		"	addiu	$v0,$v0,%lo(g_EquipItemDataTable) # maspsx-keep\n"
		"	j	.L8005AE68 # maspsx-keep\n"
		"	addu	$v0,$v1,$v0 # maspsx-keep\n"
		".L8005AE28: # maspsx-keep\n"
		"	addiu	$a0,$v1,-0x1 # maspsx-keep\n"
		"	sltiu	$v0,$a0,0xFF # maspsx-keep\n"
		"	beqz	$v0,.L8005AE48 # maspsx-keep\n"
		"	addiu	$v0,$a1,-0x200 # maspsx-keep\n"
		"	jal	Item_LookupBaseData # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	j	.L8005AE68 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L8005AE48: # maspsx-keep\n"
		"	sltiu	$v0,$v0,0x9 # maspsx-keep\n"
		"	beqz	$v0,.L8005AE64 # maspsx-keep\n"
		"	sll	$v1,$a1,5 # maspsx-keep\n"
		"	lui	$v0,%hi(g_KeyItemDataTable) # maspsx-keep\n"
		"	addiu	$v0,$v0,%lo(g_KeyItemDataTable) # maspsx-keep\n"
		"	j	.L8005AE68 # maspsx-keep\n"
		"	addu	$v0,$v1,$v0 # maspsx-keep\n"
		".L8005AE64: # maspsx-keep\n"
		"	addu	$v0,$zero,$zero # maspsx-keep\n"
		".L8005AE68: # maspsx-keep\n"
		"	lbu	$v0,0x6($v0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	beq	$v0,$s2,.L8005AE98 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L8005AE78: # maspsx-keep\n"
		"	addiu	$s0,$s0,0x2 # maspsx-keep\n"
		"	lw	$v1,g_InvSlotLimit # maspsx-keep\n"
		"	lw	$v0,g_InvItemPtr # maspsx-keep\n"
		"	sll	$v1,$v1,1 # maspsx-keep\n"
		"	addu	$v0,$v0,$v1 # maspsx-keep\n"
		"	sltu	$v0,$s0,$v0 # maspsx-keep\n"
		"	bnez	$v0,.L8005ADF4 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L8005AE98: # maspsx-keep\n"
		"	lw	$v0,g_InvSlotLimit # maspsx-keep\n"
		"	lw	$v1,g_InvItemPtr # maspsx-keep\n"
		"	sll	$v0,$v0,1 # maspsx-keep\n"
		"	addu	$v0,$v1,$v0 # maspsx-keep\n"
		"	sltu	$v0,$s0,$v0 # maspsx-keep\n"
		"	beqz	$v0,.L8005AEBC # maspsx-keep\n"
		"	subu	$v0,$s0,$v1 # maspsx-keep\n"
		"	j	.L8005AEC0 # maspsx-keep\n"
		"	sra	$v0,$v0,1 # maspsx-keep\n"
		".L8005AEBC: # maspsx-keep\n"
		"	addiu	$v0,$zero,-0x1 # maspsx-keep\n"
		".L8005AEC0: # maspsx-keep\n"
		"	lui	$at,%hi(g_AyaEquippedWeaponSlot) # maspsx-keep\n"
		"	sb	$v0,%lo(g_AyaEquippedWeaponSlot)($at) # maspsx-keep\n"
		"	j	.L8005AFCC # maspsx-keep\n"
		"	addiu	$a0,$zero,0x2 # maspsx-keep\n"
		".L8005AED0: # maspsx-keep\n"
		"	lui	$v0,%hi(g_AyaEquippedArmorSlot) # maspsx-keep\n"
		"	lb	$v0,%lo(g_AyaEquippedArmorSlot)($v0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	bne	$v0,$s1,.L8005AFD4 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lw	$v1,g_InvSlotLimit # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	blez	$v1,.L8005AFBC # maspsx-keep\n"
		"	addu	$s1,$zero,$zero # maspsx-keep\n"
		".L8005AEF4: # maspsx-keep\n"
		"	bltz	$s1,.L8005AF78 # maspsx-keep\n"
		"	slt	$v0,$s1,$v1 # maspsx-keep\n"
		"	beqz	$v0,.L8005AF78 # maspsx-keep\n"
		"	sll	$v1,$s1,1 # maspsx-keep\n"
		"	lw	$v0,g_InvItemPtr # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	addu	$v1,$v1,$v0 # maspsx-keep\n"
		"	lh	$v1,0x0($v1) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	addiu	$v0,$v1,-0x100 # maspsx-keep\n"
		"	sltiu	$v0,$v0,0x80 # maspsx-keep\n"
		"	beqz	$v0,.L8005AF3C # maspsx-keep\n"
		"	addu	$a1,$v1,$zero # maspsx-keep\n"
		"	sll	$v1,$v1,5 # maspsx-keep\n"
		"	lui	$v0,%hi(g_EquipItemDataTable) # maspsx-keep\n"
		"	addiu	$v0,$v0,%lo(g_EquipItemDataTable) # maspsx-keep\n"
		"	j	.L8005AF7C # maspsx-keep\n"
		"	addu	$v0,$v1,$v0 # maspsx-keep\n"
		".L8005AF3C: # maspsx-keep\n"
		"	addiu	$a0,$v1,-0x1 # maspsx-keep\n"
		"	sltiu	$v0,$a0,0xFF # maspsx-keep\n"
		"	beqz	$v0,.L8005AF5C # maspsx-keep\n"
		"	addiu	$v0,$a1,-0x200 # maspsx-keep\n"
		"	jal	Item_LookupBaseData # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	j	.L8005AF7C # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L8005AF5C: # maspsx-keep\n"
		"	sltiu	$v0,$v0,0x9 # maspsx-keep\n"
		"	beqz	$v0,.L8005AF78 # maspsx-keep\n"
		"	sll	$v1,$a1,5 # maspsx-keep\n"
		"	lui	$v0,%hi(g_KeyItemDataTable) # maspsx-keep\n"
		"	addiu	$v0,$v0,%lo(g_KeyItemDataTable) # maspsx-keep\n"
		"	j	.L8005AF7C # maspsx-keep\n"
		"	addu	$v0,$v1,$v0 # maspsx-keep\n"
		".L8005AF78: # maspsx-keep\n"
		"	addu	$v0,$zero,$zero # maspsx-keep\n"
		".L8005AF7C: # maspsx-keep\n"
		"	beqz	$v0,.L8005AF94 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lbu	$v1,0x6($v0) # maspsx-keep\n"
		"	addiu	$v0,$zero,0x9 # maspsx-keep\n"
		"	beq	$v1,$v0,.L8005AFA8 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L8005AF94: # maspsx-keep\n"
		"	lw	$v1,g_InvSlotLimit # maspsx-keep\n"
		"	addiu	$s1,$s1,0x1 # maspsx-keep\n"
		"	slt	$v0,$s1,$v1 # maspsx-keep\n"
		"	bnez	$v0,.L8005AEF4 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L8005AFA8: # maspsx-keep\n"
		"	lw	$v0,g_InvSlotLimit # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	slt	$v0,$s1,$v0 # maspsx-keep\n"
		"	bnez	$v0,.L8005AFC0 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L8005AFBC: # maspsx-keep\n"
		"	addiu	$s1,$zero,-0x1 # maspsx-keep\n"
		".L8005AFC0: # maspsx-keep\n"
		"	lui	$at,%hi(g_AyaEquippedArmorSlot) # maspsx-keep\n"
		"	sb	$s1,%lo(g_AyaEquippedArmorSlot)($at) # maspsx-keep\n"
		"	addiu	$a0,$zero,0x3 # maspsx-keep\n"
		".L8005AFCC: # maspsx-keep\n"
		"	jal	Inv_SetActiveList # maspsx-keep\n"
		"	addu	$a1,$zero,$zero # maspsx-keep\n"
		".L8005AFD4: # maspsx-keep\n"
		"	lw	$ra,0x98($sp) # maspsx-keep\n"
		"	lw	$s5,0x94($sp) # maspsx-keep\n"
		"	lw	$s4,0x90($sp) # maspsx-keep\n"
		"	lw	$s3,0x8C($sp) # maspsx-keep\n"
		"	lw	$s2,0x88($sp) # maspsx-keep\n"
		"	lw	$s1,0x84($sp) # maspsx-keep\n"
		"	lw	$s0,0x80($sp) # maspsx-keep\n"
		"	addiu	$sp,$sp,0xA0 # maspsx-keep\n"
		"	jr	$ra # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	.set	macro # maspsx-keep\n"
		"	.set	reorder # maspsx-keep\n"
	);
}
