/* ASSEMBLER: GNU */
/*
 * PSY-Q LIBGTE MTX_003: CompMatrix. Assembler source: a leaf that packs the
 * matrix columns by hand, issues mvmva directly, and adds the translation with
 * the trapping add instruction that GCC never emits. All 88 words are
 * identical to CompMatrix in PSY-Q 3.5 mtx_00.o.
 */
#include "pe1/psyq_asm.h"

PSYQ_ASM_OBJECT(LIBGTE, MTX_003)

PSYQ_ASM_FUNCTION(CompMatrix,
    "    lw      $t0, 0x0($a0)\n"
    "    lw      $t1, 0x4($a0)\n"
    "    lw      $t2, 0x8($a0)\n"
    "    lw      $t3, 0xC($a0)\n"
    "    lw      $t4, 0x10($a0)\n"
    "    ctc2    $t0, $0\n"
    "    ctc2    $t1, $1\n"
    "    ctc2    $t2, $2\n"
    "    ctc2    $t3, $3\n"
    "    ctc2    $t4, $4\n"
    "    lhu     $t0, 0x0($a1)\n"
    "    lw      $t1, 0x4($a1)\n"
    "    lw      $t2, 0xC($a1)\n"
    "    lui     $at, 0xffff\n"
    "    and     $t1, $t1, $at\n"
    "    or      $t0, $t0, $t1\n"
    "    mtc2    $t0, $0\n"
    "    mtc2    $t2, $1\n"
    "    nop\n"
    "    mvmva   1, 0, 0, 3, 0\n"
    "    lhu     $t0, 0x2($a1)\n"
    "    lw      $t1, 0x8($a1)\n"
    "    lh      $t2, 0xE($a1)\n"
    "    sll     $t1, $t1, 16\n"
    "    or      $t0, $t0, $t1\n"
    "    mfc2    $t3, $9\n"
    "    mfc2    $t4, $10\n"
    "    mfc2    $t5, $11\n"
    "    mtc2    $t0, $0\n"
    "    mtc2    $t2, $1\n"
    "    nop\n"
    "    mvmva   1, 0, 0, 3, 0\n"
    "    lhu     $t0, 0x4($a1)\n"
    "    lw      $t1, 0x8($a1)\n"
    "    lw      $t2, 0x10($a1)\n"
    "    lui     $at, 0xffff\n"
    "    and     $t1, $t1, $at\n"
    "    or      $t0, $t0, $t1\n"
    "    mfc2    $t6, $9\n"
    "    mfc2    $t7, $10\n"
    "    mfc2    $t8, $11\n"
    "    mtc2    $t0, $0\n"
    "    mtc2    $t2, $1\n"
    "    nop\n"
    "    mvmva   1, 0, 0, 3, 0\n"
    "    andi    $t3, $t3, 0xFFFF\n"
    "    sll     $t6, $t6, 16\n"
    "    or      $t6, $t6, $t3\n"
    "    sw      $t6, 0x0($a2)\n"
    "    andi    $t5, $t5, 0xFFFF\n"
    "    sll     $t8, $t8, 16\n"
    "    or      $t8, $t8, $t5\n"
    "    sw      $t8, 0xC($a2)\n"
    "    mfc2    $t0, $9\n"
    "    mfc2    $t1, $10\n"
    "    swc2    $11, 0x10($a2)\n"
    "    lhu     $t5, 0x14($a1)\n"
    "    lw      $t6, 0x18($a1)\n"
    "    lw      $t2, 0x1C($a1)\n"
    "    sll     $t6, $t6, 16\n"
    "    or      $t5, $t5, $t6\n"
    "    mtc2    $t5, $0\n"
    "    mtc2    $t2, $1\n"
    "    nop\n"
    "    mvmva   1, 0, 0, 3, 0\n"
    "    sll     $t4, $t4, 16\n"
    "    andi    $t0, $t0, 0xFFFF\n"
    "    or      $t0, $t0, $t4\n"
    "    sw      $t0, 0x4($a2)\n"
    "    andi    $t7, $t7, 0xFFFF\n"
    "    sll     $t1, $t1, 16\n"
    "    or      $t1, $t1, $t7\n"
    "    sw      $t1, 0x8($a2)\n"
    "    mfc2    $t0, $25\n"
    "    mfc2    $t1, $26\n"
    "    mfc2    $t2, $27\n"
    "    lw      $t3, 0x14($a0)\n"
    "    lw      $t4, 0x18($a0)\n"
    "    lw      $t5, 0x1C($a0)\n"
    "    add     $t0, $t0, $t3\n"
    "    add     $t1, $t1, $t4\n"
    "    add     $t2, $t2, $t5\n"
    "    sw      $t0, 0x14($a2)\n"
    "    sw      $t1, 0x18($a2)\n"
    "    sw      $t2, 0x1C($a2)\n"
    "    addu    $v0, $a2, $zero\n"
    "    jr      $ra\n"
    "    nop\n");
