.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */


glabel St_InstallDmaHandler
    /* 6A934 8007A134 0A80013C */  lui        $at, %hi(D_800A3450)
    /* 6A938 8007A138 50343FAC */  sw         $ra, %lo(D_800A3450)($at)
    /* 6A93C 8007A13C C5C9010C */  jal        EnterCriticalSection
    /* 6A940 8007A140 00000000 */   nop
    /* 6A944 8007A144 56000924 */  addiu      $t1, $zero, 0x56
    /* 6A948 8007A148 B0000A24 */  addiu      $t2, $zero, 0xB0
    /* 6A94C 8007A14C 09F84001 */  jalr       $t2
    /* 6A950 8007A150 00000000 */   nop
    /* 6A954 8007A154 1800428C */  lw         $v0, 0x18($v0)
    /* 6A958 8007A158 00000000 */  nop
    /* 6A95C 8007A15C 28004224 */  addiu      $v0, $v0, 0x28
    /* 6A960 8007A160 21784000 */  addu       $t7, $v0, $zero
    /* 6A964 8007A164 08800A3C */  lui        $t2, %hi(St_DmaCompleteCallback)
    /* 6A968 8007A168 E0A14A25 */  addiu      $t2, $t2, %lo(St_DmaCompleteCallback)
    /* 6A96C 8007A16C 0880093C */  lui        $t1, %hi(D_8007A1F8)
    /* 6A970 8007A170 F8A12925 */  addiu      $t1, $t1, %lo(D_8007A1F8)
  .L8007A174:
    /* 6A974 8007A174 0000438D */  lw         $v1, 0x0($t2)
    /* 6A978 8007A178 00004B8C */  lw         $t3, 0x0($v0)
    /* 6A97C 8007A17C 04004A25 */  addiu      $t2, $t2, 0x4
    /* 6A980 8007A180 0E006B14 */  bne        $v1, $t3, .L8007A1BC
    /* 6A984 8007A184 04004224 */   addiu     $v0, $v0, 0x4
    /* 6A988 8007A188 FAFF4915 */  bne        $t2, $t1, .L8007A174
    /* 6A98C 8007A18C 00000000 */   nop
    /* 6A990 8007A190 2110E001 */  addu       $v0, $t7, $zero
    /* 6A994 8007A194 08800A3C */  lui        $t2, %hi(D_8007A1F8)
    /* 6A998 8007A198 F8A14A25 */  addiu      $t2, $t2, %lo(D_8007A1F8)
    /* 6A99C 8007A19C 0880093C */  lui        $t1, %hi(D_8007A210)
    /* 6A9A0 8007A1A0 10A22925 */  addiu      $t1, $t1, %lo(D_8007A210)
  .L8007A1A4:
    /* 6A9A4 8007A1A4 0000438D */  lw         $v1, 0x0($t2)
    /* 6A9A8 8007A1A8 00000000 */  nop
    /* 6A9AC 8007A1AC 000043AC */  sw         $v1, 0x0($v0)
    /* 6A9B0 8007A1B0 04004A25 */  addiu      $t2, $t2, 0x4
    /* 6A9B4 8007A1B4 FBFF4915 */  bne        $t2, $t1, .L8007A1A4
    /* 6A9B8 8007A1B8 04004224 */   addiu     $v0, $v0, 0x4
  .L8007A1BC:
    /* 6A9BC 8007A1BC B1C9010C */  jal        FlushCache
    /* 6A9C0 8007A1C0 00000000 */   nop
    /* 6A9C4 8007A1C4 C9C9010C */  jal        ExitCriticalSection
    /* 6A9C8 8007A1C8 00000000 */   nop
    /* 6A9CC 8007A1CC 0A801F3C */  lui        $ra, %hi(D_800A3450)
    /* 6A9D0 8007A1D0 5034FF8F */  lw         $ra, %lo(D_800A3450)($ra)
    /* 6A9D4 8007A1D4 00000000 */  nop
    /* 6A9D8 8007A1D8 0800E003 */  jr         $ra
    /* 6A9DC 8007A1DC 00000000 */   nop
endlabel St_InstallDmaHandler
