/* ASSEMBLER: GNU */
/*
 * PSY-Q LIBGTE MSC02: InvSquareRoot (Gte_VectorOp), VectorNormalS
 * (Gte_NormalizeVecS32toS16), VectorNormal (Gte_NormalizeVec), VectorNormalSS,
 * the private normalizer at text_100 (Gte_MatrixOp) and MatrixNormal
 * (Gte_BuildOrthoBasis). Assembler source: the public entries pass the vector
 * to the private routine in t0..t2 and receive it back there, save ra in a3
 * instead of a stack frame, and VectorNormalS branches into the middle of
 * VectorNormalSS. PSY-Q 3.5 msc02.o has the same routines, register protocol
 * and local labels (RshiftI, CNTISQ, RTNISQRT, VectorNormalS_entry, ...);
 * 4.0 reordered some delay slots.
 */
#include "pe1/psyq_asm.h"

PSYQ_ASM_OBJECT(LIBGTE, MSC02)

PSYQ_ASM_FUNCTION(Gte_VectorOp,
    "    mtc2    $a0, $30\n"
    "    nop\n"
    "    nop\n"
    "    mfc2    $v0, $31\n"
    "    addiu   $at, $zero, 0x20\n"
    "    beq     $v0, $at, .LRTNISQRT\n"
    "    nop\n"
    "    beqz    $v0, .LRTNISQRT\n"
    "    nop\n"
    "    andi    $t0, $v0, 0x1\n"
    "    addiu   $at, $zero, -0x2\n"
    "    and     $t2, $v0, $at\n"
    "    addiu   $t1, $zero, 0x1F\n"
    "    sub     $t1, $t1, $t2\n"
    "    sra     $t1, $t1, 1\n"
    "    addi    $t3, $t2, -0x18\n"
    "    bltz    $t3, .LRshiftI\n"
    "    nop\n"
    "    sllv    $t4, $a0, $t3\n"
    "    b       .LCNTISQ\n"
    ".LRshiftI:\n"
    "    addiu   $t3, $zero, 0x18\n"
    "    sub     $t3, $t3, $t2\n"
    "    srav    $t4, $a0, $t3\n"
    ".LCNTISQ:\n"
    "    addi    $t4, $t4, -0x40\n"
    "    sll     $t4, $t4, 1\n"
    "    lui     $t5, %hi(D_80096250)\n"
    "    addu    $t5, $t5, $t4\n"
    "    lh      $t5, %lo(D_80096250)($t5)\n"
    "    sw      $t1, 0x0($a2)\n"
    "    sw      $t5, 0x0($a1)\n"
    "    addiu   $v0, $zero, 0x1\n"
    "    jr      $ra\n"
    "    nop\n"
    ".LRTNISQRT:\n"
    "    jr      $ra\n"
    "    addiu   $v0, $zero, -0x1\n");

PSYQ_ASM_FUNCTION(Gte_NormalizeVecS32toS16,
    "    lw      $t0, 0x0($a0)\n"
    "    lw      $t1, 0x4($a0)\n"
    "    lw      $t2, 0x8($a0)\n"
    "    b       .LVectorNormalS_entry\n"
    "    nop\n");

PSYQ_ASM_FUNCTION(Gte_NormalizeVec,
    "    lw      $t0, 0x0($a0)\n"
    "    lw      $t1, 0x4($a0)\n"
    "    lw      $t2, 0x8($a0)\n"
    "    addu    $a3, $ra, $zero\n"
    "    jal     Gte_MatrixOp\n"
    "    nop\n"
    "    sw      $t0, 0x0($a1)\n"
    "    sw      $t1, 0x4($a1)\n"
    "    sw      $t2, 0x8($a1)\n"
    "    addu    $ra, $a3, $zero\n"
    "    jr      $ra\n"
    "    nop\n");

PSYQ_ASM_FUNCTION(VectorNormalSS,
    "    lh      $t0, 0x0($a0)\n"
    "    lh      $t1, 0x2($a0)\n"
    "    lh      $t2, 0x4($a0)\n"
    ".LVectorNormalS_entry:\n"
    "    addu    $a3, $ra, $zero\n"
    "    jal     Gte_MatrixOp\n"
    "    nop\n"
    "    sh      $t0, 0x0($a1)\n"
    "    sh      $t1, 0x2($a1)\n"
    "    sh      $t2, 0x4($a1)\n"
    "    addu    $ra, $a3, $zero\n"
    "    jr      $ra\n"
    "    nop\n");

PSYQ_ASM_FUNCTION(Gte_MatrixOp,
    "    mtc2    $t0, $9\n"
    "    mtc2    $t1, $10\n"
    "    mtc2    $t2, $11\n"
    "    nop\n"
    "    sqr     0\n"
    "    mfc2    $t3, $25\n"
    "    mfc2    $t4, $26\n"
    "    mfc2    $t5, $27\n"
    "    add     $t3, $t3, $t4\n"
    "    add     $v0, $t3, $t5\n"
    "    mtc2    $v0, $30\n"
    "    nop\n"
    "    nop\n"
    "    mfc2    $v1, $31\n"
    "    addiu   $at, $zero, -0x2\n"
    "    and     $v1, $v1, $at\n"
    "    addiu   $t6, $zero, 0x1F\n"
    "    sub     $t6, $t6, $v1\n"
    "    sra     $t6, $t6, 1\n"
    "    addi    $t3, $v1, -0x18\n"
    "    bltz    $t3, .LRshiftI_VN\n"
    "    nop\n"
    "    b       .LCNTISQ_VN\n"
    "    sllv    $t4, $v0, $t3\n"
    ".LRshiftI_VN:\n"
    "    addiu   $t3, $zero, 0x18\n"
    "    sub     $t3, $t3, $v1\n"
    "    srav    $t4, $v0, $t3\n"
    ".LCNTISQ_VN:\n"
    "    addi    $t4, $t4, -0x40\n"
    "    sll     $t4, $t4, 1\n"
    "    lui     $t5, %hi(D_80096250)\n"
    "    addu    $t5, $t5, $t4\n"
    "    lh      $t5, %lo(D_80096250)($t5)\n"
    "    nop\n"
    "    mtc2    $t5, $8\n"
    "    mtc2    $t0, $9\n"
    "    mtc2    $t1, $10\n"
    "    mtc2    $t2, $11\n"
    "    nop\n"
    "    nop\n"
    "    gpf     0\n"
    "    mfc2    $t0, $25\n"
    "    mfc2    $t1, $26\n"
    "    mfc2    $t2, $27\n"
    "    srav    $t0, $t0, $t6\n"
    "    srav    $t1, $t1, $t6\n"
    "    srav    $t2, $t2, $t6\n"
    "    jr      $ra\n"
    "    nop\n");

PSYQ_ASM_FUNCTION(Gte_BuildOrthoBasis,
    "    lh      $t0, 0x0($a0)\n"
    "    lh      $t1, 0x2($a0)\n"
    "    lh      $t2, 0x4($a0)\n"
    "    lh      $t3, 0x6($a0)\n"
    "    lh      $t4, 0x8($a0)\n"
    "    lh      $t5, 0xA($a0)\n"
    "    cfc2    $v0, $0\n"
    "    cfc2    $v1, $2\n"
    "    cfc2    $a2, $4\n"
    "    ctc2    $t0, $0\n"
    "    ctc2    $t1, $2\n"
    "    ctc2    $t2, $4\n"
    "    mtc2    $t5, $11\n"
    "    mtc2    $t3, $9\n"
    "    mtc2    $t4, $10\n"
    "    nop\n"
    "    op      1\n"
    "    mfc2    $t7, $25\n"
    "    mfc2    $t8, $26\n"
    "    mfc2    $t9, $27\n"
    "    ctc2    $t3, $0\n"
    "    ctc2    $t4, $2\n"
    "    ctc2    $t5, $4\n"
    "    nop\n"
    "    op      1\n"
    "    mtc2    $t3, $0\n"
    "    mtc2    $t4, $1\n"
    "    mtc2    $t5, $2\n"
    "    mfc2    $t0, $25\n"
    "    mfc2    $t1, $26\n"
    "    mfc2    $t2, $27\n"
    "    ctc2    $v0, $0\n"
    "    ctc2    $v1, $2\n"
    "    ctc2    $a2, $4\n"
    "    addu    $a3, $ra, $zero\n"
    "    jal     Gte_MatrixOp\n"
    "    nop\n"
    "    sh      $t0, 0x0($a1)\n"
    "    sh      $t1, 0x2($a1)\n"
    "    sh      $t2, 0x4($a1)\n"
    "    mfc2    $t0, $0\n"
    "    mfc2    $t1, $1\n"
    "    mfc2    $t2, $2\n"
    "    jal     Gte_MatrixOp\n"
    "    nop\n"
    "    sh      $t0, 0x6($a1)\n"
    "    sh      $t1, 0x8($a1)\n"
    "    sh      $t2, 0xA($a1)\n"
    "    addu    $t0, $t7, $zero\n"
    "    addu    $t1, $t8, $zero\n"
    "    jal     Gte_MatrixOp\n"
    "    addu    $t2, $t9, $zero\n"
    "    sh      $t0, 0xC($a1)\n"
    "    sh      $t1, 0xE($a1)\n"
    "    sh      $t2, 0x10($a1)\n"
    "    addu    $ra, $a3, $zero\n"
    "    jr      $ra\n"
    "    nop\n");
