.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

/* Handwritten function */

glabel MulRotMatrix
    /* 68EE4 800786E4 0000888C */  lw         $t0, 0x0($a0)
    /* 68EE8 800786E8 0400898C */  lw         $t1, 0x4($a0)
    /* 68EEC 800786EC 0C008A8C */  lw         $t2, 0xC($a0)
    /* 68EF0 800786F0 FFFF0831 */  andi       $t0, $t0, 0xFFFF
    /* 68EF4 800786F4 FFFF013C */  lui        $at, (0xFFFF0000 >> 16)
    /* 68EF8 800786F8 24482101 */  and        $t1, $t1, $at
    /* 68EFC 800786FC 25400901 */  or         $t0, $t0, $t1
    /* 68F00 80078700 00008848 */  mtc2       $t0, $0 /* handwritten instruction */
    /* 68F04 80078704 00088A48 */  mtc2       $t2, $1 /* handwritten instruction */
    /* 68F08 80078708 00000000 */  nop
    /* 68F0C 8007870C 1260484A */  mvmva      1, 0, 0, 3, 0
    /* 68F10 80078710 02008894 */  lhu        $t0, 0x2($a0)
    /* 68F14 80078714 0800898C */  lw         $t1, 0x8($a0)
    /* 68F18 80078718 0E008A84 */  lh         $t2, 0xE($a0)
    /* 68F1C 8007871C 004C0900 */  sll        $t1, $t1, 16
    /* 68F20 80078720 25400901 */  or         $t0, $t0, $t1
    /* 68F24 80078724 00480B48 */  mfc2       $t3, $9 /* handwritten instruction */
    /* 68F28 80078728 00500C48 */  mfc2       $t4, $10 /* handwritten instruction */
    /* 68F2C 8007872C 00580D48 */  mfc2       $t5, $11 /* handwritten instruction */
    /* 68F30 80078730 00008848 */  mtc2       $t0, $0 /* handwritten instruction */
    /* 68F34 80078734 00088A48 */  mtc2       $t2, $1 /* handwritten instruction */
    /* 68F38 80078738 00000000 */  nop
    /* 68F3C 8007873C 1260484A */  mvmva      1, 0, 0, 3, 0
    /* 68F40 80078740 04008894 */  lhu        $t0, 0x4($a0)
    /* 68F44 80078744 0800898C */  lw         $t1, 0x8($a0)
    /* 68F48 80078748 10008A8C */  lw         $t2, 0x10($a0)
    /* 68F4C 8007874C FFFF013C */  lui        $at, (0xFFFF0000 >> 16)
    /* 68F50 80078750 24482101 */  and        $t1, $t1, $at
    /* 68F54 80078754 25400901 */  or         $t0, $t0, $t1
    /* 68F58 80078758 00480E48 */  mfc2       $t6, $9 /* handwritten instruction */
    /* 68F5C 8007875C 00500F48 */  mfc2       $t7, $10 /* handwritten instruction */
    /* 68F60 80078760 00581848 */  mfc2       $t8, $11 /* handwritten instruction */
    /* 68F64 80078764 00008848 */  mtc2       $t0, $0 /* handwritten instruction */
    /* 68F68 80078768 00088A48 */  mtc2       $t2, $1 /* handwritten instruction */
    /* 68F6C 8007876C 00000000 */  nop
    /* 68F70 80078770 1260484A */  mvmva      1, 0, 0, 3, 0
    /* 68F74 80078774 FFFF6B31 */  andi       $t3, $t3, 0xFFFF
    /* 68F78 80078778 00740E00 */  sll        $t6, $t6, 16
    /* 68F7C 8007877C 2570CB01 */  or         $t6, $t6, $t3
    /* 68F80 80078780 00008EAC */  sw         $t6, 0x0($a0)
    /* 68F84 80078784 FFFFAD31 */  andi       $t5, $t5, 0xFFFF
    /* 68F88 80078788 00C41800 */  sll        $t8, $t8, 16
    /* 68F8C 8007878C 25C00D03 */  or         $t8, $t8, $t5
    /* 68F90 80078790 0C0098AC */  sw         $t8, 0xC($a0)
    /* 68F94 80078794 00480848 */  mfc2       $t0, $9 /* handwritten instruction */
    /* 68F98 80078798 00500948 */  mfc2       $t1, $10 /* handwritten instruction */
    /* 68F9C 8007879C FFFF0831 */  andi       $t0, $t0, 0xFFFF
    /* 68FA0 800787A0 00640C00 */  sll        $t4, $t4, 16
    /* 68FA4 800787A4 25400C01 */  or         $t0, $t0, $t4
    /* 68FA8 800787A8 040088AC */  sw         $t0, 0x4($a0)
    /* 68FAC 800787AC FFFFEF31 */  andi       $t7, $t7, 0xFFFF
    /* 68FB0 800787B0 004C0900 */  sll        $t1, $t1, 16
    /* 68FB4 800787B4 25482F01 */  or         $t1, $t1, $t7
    /* 68FB8 800787B8 080089AC */  sw         $t1, 0x8($a0)
    /* 68FBC 800787BC 10008BE8 */  swc2       $11, 0x10($a0)
    /* 68FC0 800787C0 21108000 */  addu       $v0, $a0, $zero
    /* 68FC4 800787C4 0800E003 */  jr         $ra
    /* 68FC8 800787C8 00000000 */   nop
endlabel MulRotMatrix
    /* 68FCC 800787CC 00000000 */  nop
    /* 68FD0 800787D0 00000000 */  nop
