/* ASSEMBLER: GNU */
/*
 * PSY-Q LIBGTE MTX_006: PushMatrix (Gte_PushMatrix) and PopMatrix
 * (Gte_PopMatrix). Assembler source: the matrix-stack pointer MSP and stack
 * MSTACK are object statics, ra is parked in SAVERA around the overflow
 * printf, and the counter steps with trapping addi. PSY-Q 3.5 mtx_00.o has
 * the same routines with the local labels CONTpush and CONTpop; its assembler
 * filled the branch delay slots that 4.0 leaves as NOPs.
 */
#include "pe1/psyq_asm.h"

PSYQ_ASM_OBJECT(LIBGTE, MTX_006)

PSYQ_ASM_FUNCTION(Gte_PushMatrix,
    "    lui     $t6, %hi(D_800963E8)\n"
    "    lw      $t6, %lo(D_800963E8)($t6)\n"
    "    nop\n"
    "    slti    $at, $t6, 0x280\n"
    "    bnez    $at, .LCONTpush\n"
    "    nop\n"
    "    lui     $at, %hi(D_800963DC)\n"
    "    sw      $ra, %lo(D_800963DC)($at)\n"
    "    lui     $a0, %hi(D_8009666C)\n"
    "    jal     printf\n"
    "    addiu   $a0, $a0, %lo(D_8009666C)\n"
    "    lui     $ra, %hi(D_800963DC)\n"
    "    lw      $ra, %lo(D_800963DC)($ra)\n"
    "    nop\n"
    "    jr      $ra\n"
    "    nop\n"
    ".LCONTpush:\n"
    "    lui     $t7, %hi(D_800963EC)\n"
    "    addiu   $t7, $t7, %lo(D_800963EC)\n"
    "    addu    $t7, $t7, $t6\n"
    "    cfc2    $t0, $0\n"
    "    cfc2    $t1, $1\n"
    "    sw      $t0, 0x0($t7)\n"
    "    sw      $t1, 0x4($t7)\n"
    "    cfc2    $t0, $2\n"
    "    cfc2    $t1, $3\n"
    "    sw      $t0, 0x8($t7)\n"
    "    sw      $t1, 0xC($t7)\n"
    "    cfc2    $t0, $4\n"
    "    nop\n"
    "    sw      $t0, 0x10($t7)\n"
    "    cfc2    $t0, $5\n"
    "    cfc2    $t1, $6\n"
    "    cfc2    $t2, $7\n"
    "    sw      $t0, 0x14($t7)\n"
    "    sw      $t1, 0x18($t7)\n"
    "    sw      $t2, 0x1C($t7)\n"
    "    addi    $t6, $t6, 0x20\n"
    "    lui     $at, %hi(D_800963E8)\n"
    "    sw      $t6, %lo(D_800963E8)($at)\n"
    "    jr      $ra\n"
    "    nop\n");

PSYQ_ASM_FUNCTION(Gte_PopMatrix,
    "    lui     $t6, %hi(D_800963E8)\n"
    "    lw      $t6, %lo(D_800963E8)($t6)\n"
    "    nop\n"
    "    bgtz    $t6, .LCONTpop\n"
    "    nop\n"
    "    lui     $at, %hi(D_800963DC)\n"
    "    sw      $ra, %lo(D_800963DC)($at)\n"
    "    lui     $a0, %hi(D_8009669D)\n"
    "    jal     printf\n"
    "    addiu   $a0, $a0, %lo(D_8009669D)\n"
    "    lui     $ra, %hi(D_800963DC)\n"
    "    lw      $ra, %lo(D_800963DC)($ra)\n"
    "    nop\n"
    "    jr      $ra\n"
    "    nop\n"
    ".LCONTpop:\n"
    "    addi    $t6, $t6, -0x20\n"
    "    lui     $at, %hi(D_800963E8)\n"
    "    sw      $t6, %lo(D_800963E8)($at)\n"
    "    lui     $t7, %hi(D_800963EC)\n"
    "    addiu   $t7, $t7, %lo(D_800963EC)\n"
    "    addu    $t7, $t7, $t6\n"
    "    lw      $t0, 0x0($t7)\n"
    "    lw      $t1, 0x4($t7)\n"
    "    ctc2    $t0, $0\n"
    "    ctc2    $t1, $1\n"
    "    lw      $t0, 0x8($t7)\n"
    "    lw      $t1, 0xC($t7)\n"
    "    ctc2    $t0, $2\n"
    "    ctc2    $t1, $3\n"
    "    lw      $t0, 0x10($t7)\n"
    "    nop\n"
    "    ctc2    $t0, $4\n"
    "    nop\n"
    "    lw      $t0, 0x14($t7)\n"
    "    lw      $t1, 0x18($t7)\n"
    "    lw      $t2, 0x1C($t7)\n"
    "    ctc2    $t0, $5\n"
    "    ctc2    $t1, $6\n"
    "    ctc2    $t2, $7\n"
    "    jr      $ra\n"
    "    nop\n");
