/* ASSEMBLER: GNU */
#include "pe1/gte_types.h"
#include "pe1/psyq_nop.h"
extern u32 D_800966EC[];

/* Q12 rotation with retail wrap/rounding order. Pins, empty HI/LO and
 * scheduling constraints, and individual NOPs are tracked matching debt.
 * See proposals/PsyqRotationMatrix for the constraint rationale and evidence.
 */
GteMatrix *RotMatrixYXZ(GteShortVector *angles, GteMatrix *matrix) {
    register GteMatrix *result;
    unsigned long long product;
    unsigned low;
    register s32 cx asm("$8");
    register s32 cy asm("$9");
    register s32 cz asm("$10");
    register s32 sx asm("$11");
    register s32 sy asm("$12");
    register s32 sz asm("$13");
    register s32 value asm("$14");
    register s32 angle asm("$15");
    register s32 temp asm("$24");
    register s32 word asm("$25");
    /* Decode packed sine/cosine for each signed angle. */
    angle = angles->x;
    result = matrix;
    word = (u32)angle & 0xFFF;
    if (angle >= 0)
        goto positive_x;
    angle = 0U - (u32)angle;
    if (angle < 0)
        asm volatile("" : : : "15");
    else
        angle &= 0xfff;
    asm volatile("" : : : "24");

    temp = ((u32)angle) << 2;
    word = *(u32 *)((char *)D_800966EC + temp);
    PE1_NOP_MEMORY_DEP("r", word);
    value = ((u32)word) << 16;
    value = (s32)value >> 16;
    sx = 0U - (u32)value;
    cx = (s32)word >> 16;
    goto x_ready;
positive_x:;
    temp = ((u32)word) << 2;
    word = *(u32 *)((char *)D_800966EC + temp);
    PE1_NOP_MEMORY_DEP("r", word);
    temp = ((u32)word) << 16;
    sx = (s32)temp >> 16;
    value = 0U - (u32)sx;
    cx = (s32)word >> 16;
    asm volatile("" : "=r"(cx) : "0"(cx));
x_ready:;
    angle = angles->y;
    PE1_NOP_MEMORY_DEP("r", angle);
    word = (u32)angle & 0xFFF;
    if (angle >= 0)
        goto positive_y;
    angle = 0U - (u32)angle;
    if (angle < 0)
        asm volatile("" : : : "15");
    else
        angle &= 0xfff;
    asm volatile("" : : : "24");

    temp = ((u32)angle) << 2;
    word = *(u32 *)((char *)D_800966EC + temp);
    PE1_NOP_MEMORY_DEP("r", word);
    temp = ((u32)word) << 16;
    temp = (s32)temp >> 16;
    sy = 0U - (u32)temp;
    cy = (s32)word >> 16;
    goto y_ready;
positive_y:;
    temp = ((u32)word) << 2;
    word = *(u32 *)((char *)D_800966EC + temp);
    PE1_NOP_MEMORY_DEP("r", word);
    temp = ((u32)word) << 16;
    sy = (s32)temp >> 16;
    cy = (s32)word >> 16;
    asm volatile("" : "=r"(cy) : "0"(cy));
y_ready:;
    product = (unsigned long long)(u32)sy * (u32)cx;
    asm volatile("" : : "x"(product) : "memory");
    angle = angles->z;
    matrix->m[1][2] = value;
    asm volatile("" : "=l"(low) : "x"(product));
    temp = low;
    asm volatile("" : "=r"(temp) : "0"(temp));
    value = (s32)temp >> 12;
    PE1_NOP_MEMORY_DEP("r", value);
    product = (unsigned long long)(u32)cy * (u32)cx;
    asm volatile("" : : "x"(product) : "memory");
    matrix->m[0][2] = value;
    word = (u32)angle & 0xFFF;
    if (angle >= 0)
        goto positive_z;
    asm volatile("" : "=l"(low) : "x"(product));
    temp = low;
    asm volatile("" : "=r"(temp) : "0"(temp));
    value = (s32)temp >> 12;
    matrix->m[2][2] = value;
    angle = 0U - (u32)angle;
    asm volatile("" : "=r"(angle) : "0"(angle));
    if (angle < 0)
        asm volatile("" : : : "15");
    else
        angle &= 0xfff;
    asm volatile("" : : : "24");

    temp = ((u32)angle) << 2;
    asm volatile("" : "=r"(temp) : "0"(temp));
    word = *(u32 *)((char *)D_800966EC + temp);
    PE1_NOP_MEMORY_DEP("r", word);
    temp = ((u32)word) << 16;
    asm volatile("" : "=r"(temp) : "0"(temp));
    temp = (s32)temp >> 16;
    asm volatile("" : "=r"(temp) : "0"(temp));
    sz = 0U - (u32)temp;
    cz = (s32)word >> 16;
    goto z_ready;
positive_z:;
    asm volatile("" : "=l"(low) : "x"(product));
    angle = low;
    asm volatile("" : "=r"(angle) : "0"(angle));
    value = (s32)angle >> 12;
    matrix->m[2][2] = value;
    asm volatile("" : : "m"(matrix->m[2][2]) : "memory");
    temp = ((u32)word) << 2;
    asm volatile("" : "=r"(temp) : "0"(temp));
    word = *(u32 *)((char *)D_800966EC + temp);
    PE1_NOP_MEMORY_DEP("r", word);
    temp = ((u32)word) << 16;
    asm volatile("" : "=r"(temp) : "0"(temp));
    sz = (s32)temp >> 16;
    cz = (s32)word >> 16;
    asm volatile("" : "=r"(cz) : "0"(cz));
z_ready:;
    product = (unsigned long long)(u32)sz * (u32)cx;
    asm volatile("" : : "x"(product) : "memory");
    PE1_NOP_MEMORY_DEP("x", product);
    PE1_NOP_MEMORY_DEP("x", product);
    asm volatile("" : "=l"(low) : "x"(product));
    angle = low;
    asm volatile("" : "=r"(angle) : "0"(angle));
    value = (s32)angle >> 12;
    matrix->m[1][0] = value;
    asm volatile("" : : "m"(matrix->m[1][0]) : "memory");
    product = (unsigned long long)(u32)cz * (u32)cx;
    asm volatile("" : : "x"(product) : "memory");
    PE1_NOP_MEMORY_DEP("x", product);
    PE1_NOP_MEMORY_DEP("x", product);
    asm volatile("" : "=l"(low) : "x"(product));
    angle = low;
    asm volatile("" : "=r"(angle) : "0"(angle));
    value = (s32)angle >> 12;
    PE1_NOP_MEMORY_DEP("r", value);
    product = (unsigned long long)(u32)sy * (u32)sx;
    asm volatile("" : : "x"(product) : "memory");
    matrix->m[1][1] = value;
    PE1_NOP_MEMORY_DEP("x", product);
    asm volatile("" : "=l"(low) : "x"(product));
    angle = low;
    asm volatile("" : "=r"(angle) : "0"(angle));
    temp = (s32)angle >> 12;
    asm volatile("" : "=r"(temp) : "0"(temp));
    PE1_NOP_MEMORY_DEP("r", temp);
    product = (unsigned long long)(u32)temp * (u32)sz;
    asm volatile("" : : "x"(product) : "memory");
    PE1_NOP_MEMORY_DEP("x", product);
    PE1_NOP_MEMORY_DEP("x", product);
    asm volatile("" : "=l"(low) : "x"(product));
    angle = low;
    asm volatile("" : "=r"(angle) : "0"(angle));
    value = (s32)angle >> 12;
    PE1_NOP_MEMORY_DEP("r", value);
    product = (unsigned long long)(u32)cy * (u32)cz;
    asm volatile("" : : "x"(product) : "memory");
    PE1_NOP_MEMORY_DEP("x", product);
    PE1_NOP_MEMORY_DEP("x", product);
    asm volatile("" : "=l"(low) : "x"(product));
    angle = low;
    asm volatile("" : "=r"(angle) : "0"(angle));
    word = (s32)angle >> 12;
    angle = (u32)word + value;
    asm volatile("" : "=r"(angle) : "0"(angle));
    product = (unsigned long long)(u32)cy * (u32)sz;
    asm volatile("" : : "x"(product) : "memory");
    matrix->m[0][0] = angle;
    PE1_NOP_MEMORY_DEP("x", product);
    asm volatile("" : "=l"(low) : "x"(product));
    value = low;
    asm volatile("" : "=r"(value) : "0"(value));
    word = (s32)value >> 12;
    angle = 0U - (u32)word;
    asm volatile("" : "=r"(angle) : "0"(angle));
    product = (unsigned long long)(u32)temp * (u32)cz;
    asm volatile("" : : "x"(product) : "memory");
    PE1_NOP_MEMORY_DEP("x", product);
    PE1_NOP_MEMORY_DEP("x", product);
    asm volatile("" : "=l"(low) : "x"(product));
    value = low;
    asm volatile("" : "=r"(value) : "0"(value));
    word = (s32)value >> 12;
    value = (u32)angle + word;
    asm volatile("" : "=r"(value) : "0"(value));
    product = (unsigned long long)(u32)cy * (u32)sx;
    asm volatile("" : : "x"(product) : "memory");
    matrix->m[0][1] = value;
    PE1_NOP_MEMORY_DEP("x", product);
    asm volatile("" : "=l"(low) : "x"(product));
    angle = low;
    asm volatile("" : "=r"(angle) : "0"(angle));
    temp = (s32)angle >> 12;
    asm volatile("" : "=r"(temp) : "0"(temp));
    PE1_NOP_MEMORY_DEP("r", temp);
    product = (unsigned long long)(u32)temp * (u32)cz;
    asm volatile("" : : "x"(product) : "memory");
    PE1_NOP_MEMORY_DEP("x", product);
    PE1_NOP_MEMORY_DEP("x", product);
    asm volatile("" : "=l"(low) : "x"(product));
    angle = low;
    asm volatile("" : "=r"(angle) : "0"(angle));
    value = (s32)angle >> 12;
    asm volatile("" : "=r"(value) : "0"(value));
    PE1_NOP_MEMORY_DEP("r", value);
    product = (unsigned long long)(u32)sy * (u32)sz;
    asm volatile("" : : "x"(product) : "memory");
    PE1_NOP_MEMORY_DEP("x", product);
    PE1_NOP_MEMORY_DEP("x", product);
    asm volatile("" : "=l"(low) : "x"(product));
    angle = low;
    asm volatile("" : "=r"(angle) : "0"(angle));
    word = (s32)angle >> 12;
    angle = (u32)word + value;
    asm volatile("" : "=r"(angle) : "0"(angle));
    product = (unsigned long long)(u32)sy * (u32)cz;
    asm volatile("" : : "x"(product) : "memory");
    matrix->m[2][1] = angle;
    PE1_NOP_MEMORY_DEP("x", product);
    asm volatile("" : "=l"(low) : "x"(product));
    value = low;
    asm volatile("" : "=r"(value) : "0"(value));
    word = (s32)value >> 12;
    angle = 0U - (u32)word;
    asm volatile("" : "=r"(angle) : "0"(angle));
    product = (unsigned long long)(u32)temp * (u32)sz;
    asm volatile("" : : "x"(product) : "memory");
    PE1_NOP_MEMORY_DEP("x", product);
    PE1_NOP_MEMORY_DEP("x", product);
    asm volatile("" : "=l"(low) : "x"(product));
    value = low;
    asm volatile("" : "=r"(value) : "0"(value));
    word = (s32)value >> 12;
    value = (u32)angle + word;
    asm volatile("" : "=r"(value) : "0"(value));
    matrix->m[2][0] = value;
    PE1_NOP_MEMORY_DEP("r", value);
    return result;
}
