#define ROOMLIB_UPDATE_TIMED_RENDER_NAME func_801939C8
#define ROOMLIB_UPDATE_TIMED_RENDER_SEED D_8018F210
#define ROOMLIB_UPDATE_TIMED_RENDER_TABLE D_80193FE4
#include "../room_lib/RoomLib_UpdateTimedRender.inc"
