#define ROOMLIB_UPDATE_TIMED_RENDER_NAME func_80192CE0
#define ROOMLIB_UPDATE_TIMED_RENDER_SEED D_8018F1CC
#define ROOMLIB_UPDATE_TIMED_RENDER_TABLE D_801932A0
#include "../room_lib/RoomLib_UpdateTimedRender.inc"
