#define ROOMLIB_DRAW_GROUND_SPRITE_NAME func_801900C8
#define ROOMLIB_DRAW_GROUND_SPRITE_DEPTH D_80195722
#define ROOMLIB_DRAW_GROUND_SPRITE_FLOOR D_800942EC
#include "../room_lib/RoomLib_DrawGroundSprite.inc"
