#define ROOMLIB_DRAW_GROUND_SPRITE_NAME func_8018FF1C
#define ROOMLIB_DRAW_GROUND_SPRITE_DEPTH D_801921CA
#define ROOMLIB_DRAW_GROUND_SPRITE_FLOOR D_800942EC
#include "../room_lib/RoomLib_DrawGroundSprite.inc"
