/* MASPSX_FLAGS: --expand-div */
/* Font glyph streaming: consume the pending-glyph flag, load the alternate
 * glyph sector and step the incremental font load. Contiguous functions;
 * --expand-div serves the glyph loader's divide only. */
#include "common.h"
#include "pe1/cdrom.h"

extern struct { char _[0x98]; } D_800B0DD8;
extern u16 D_80093176[];
extern u8 *D_800B0E6C;
extern u8 D_80091A20;
extern u8 D_80091A1C;
extern u8 D_80091A1D;
extern u8 D_80091A1E;
extern volatile u8 D_80091A1F;
extern u32 D_80091A24;
extern u8 D_8009ECD8[];
extern u8 D_8009EE24[];
extern u8 *D_80091A28;

int rand(void);
void srand(unsigned int seed);
void Render_LoadFontGlyph(int glyph);

int func_80038D48(void) {
    u32 *state = &D_80091A24;

    if (*state != 0) {
        *state = 0;
        return 0;
    }

    return 0xFF;
}

static inline int find_slot(u8 *table)
{
    int found = 0;
    int k;
    u8 *groups = table + 1;
    u8 *slots;
    u8 *entry;
    unsigned int count_offset;

    /* Retain the separate loop-bound reload generated by stock GCC. */
    count_offset = 3;
    for (k = 0; k < table[count_offset]; k++) {
        entry = groups + k;
        if (entry[3] == 2) {
            found = k;
            k = groups[2];
        }
    }
    slots = groups + 0x1B;
    for (k = 0; k < groups[0x1B]; k++) {
        entry = slots + k;
        if (entry[1] == (found & 255)) {
            return k;
        }
    }
    return 255;
}

u8 Render_LoadFontGlyphAlt(void)
{
    u16 *range;
    u8 *state;
    int read_status;
    int poll_status;
    u8 i;
    int forced_slot;
    s16 unique_count;
    int glyph;
    s16 limit;
    u8 duplicate;
    u8 j;

retry_read:
    state = (u8 *)&D_800B0DD8;
    range = D_80093176;
    do {
        read_status = CdRom_ReadSectorsFromLba(*(int *)state + range[0],
                                             *(void **)(state + 0x94),
                                             range[1] - range[0]);
    } while (read_status == -1);

    for (;;) {
        poll_status = CdRom_PollReady();
        if (poll_status == 0) {
            break;
        }
        if (poll_status == -1) {
            goto retry_read;
        }
    }

    D_8009ECD8[0] = D_800B0E6C[0];
    if (D_80091A20 == 0 && D_80091A24 == 0) {
        do {
            D_80091A24 = rand() % 0x7FFF;
        } while (D_80091A24 == 0);
    }

    /* The identical arms retain the stock compiler's branch-delay scheduling. */
    if (D_80091A20) {
        srand(D_80091A24);
    } else {
        srand(D_80091A24);
    }

    unique_count = 0;
    forced_slot = 0;
    for (i = 0; (u8)i < 0x45; i++) {
        if (((u8)i + 2) % 10 == 0) {
            D_8009EE24[(u8)i] = forced_slot;
            forced_slot++;
            continue;
        }

        if ((u8)i + 2 < 10) {
            limit = 0x68;
        } else if ((u8)i + 2 < 20) {
            limit = 0x6D;
        } else {
            limit = 0x71;
        }

        if (D_8009ECD8[0] - 1 < limit) {
            limit = D_8009ECD8[0];
            limit = limit - 1;
        }

        glyph = (rand() % (limit - 7)) + 7;
        D_8009EE24[(u8)i] = glyph;

        if (unique_count < D_8009ECD8[0] - 9) {
            do {
                duplicate = 1;
                for (j = 0; j < i; j++) {
                    if (D_8009EE24[j] == D_8009EE24[(u8)i]) {
                        D_8009EE24[(u8)i] = (rand() % (limit - 7)) + 7;
                        duplicate = 0;
                    }
                }
            } while (duplicate == 0);
        }
        unique_count++;
    }

    Render_LoadFontGlyph(D_8009EE24[0]);

    D_80091A1C = 1;
    D_80091A1D = 2;
    D_80091A1E = D_8009EE24[0];
    D_80091A28 = D_8009ECD8;

    D_80091A1F = find_slot(D_8009ECD8);
    {
        u8 *result = D_80091A28;
        /* This assembler-backed flag is ordinary RAM. The unqualified byte
         * view preserves the lookup's stock-GCC integer promotion. */
        return *(result + *(result + *(u8 *)&D_80091A1F + 0x1D) + 4);
    }
}

extern u8 D_80091A1D;
extern u8 D_80091A1E;
extern u8 D_80091A1F;
extern u8 D_80091A1F_rd[] __asm__("D_80091A1F");
extern u8 *D_80091A28;
extern u8 D_8009EE22[];

u8 Render_StepFontLoad(void) {
    u8 state;
    u8 next;
    register u8 code asm("$4");
    u8 *hdr;
    u8 *p;
    u8 *q;
    u8 *t;
    s32 slot;
    register s32 digit asm("$3");
    s32 i;
    s32 count;
    register s32 found asm("$7");
    u8 *statep;
    int stack_pad[3];

    statep = &D_80091A1D;
    state = *statep;
    if (state < 3U) {
        *statep = 1;
        return 0xFFU;
    }

    next = state - 1;
    *statep = next;
    code = D_8009EE22[next];
    D_80091A1E = code;
    Render_LoadFontGlyph(code);

    digit = (u8)(D_80091A1D % 10) != 0;
    found = 0;
    i = 0;
    asm("" : "=r"(digit), "=r"(i), "=r"(found)
        : "0"(digit), "1"(i), "2"(found));

    hdr = D_80091A28;
    count = hdr[3];
    p = hdr + 1;
    if (count > 0) {
        digit &= 0xFF;
        do {
            q = p + i;
            if (q[3] == digit) {
                found = i;
                i = p[2];
            }
            i++;
        } while (i < count);
        i = 0;
    }

    {
        s32 count2;
        register s32 wanted asm("$4");
        u8 *p2;
        slot = p[0x1B];
        p2 = p + 0x1B;
        if (slot > 0) {
            wanted = found & 0xFF;
            count2 = slot;
            do {
                q = p2 + i;
                if (q[1] == wanted) {
                    slot = i;
                    goto store;
                }
                i++;
            } while (i < count2);
        }
    }
    slot = 0xFF;

store:
        D_80091A1F = slot;
    __asm__ volatile("" : : : "memory");
    t = D_80091A28;
    return *(t + *(t + D_80091A1F_rd[0] + 0x1D) + 4);
}
