/* MASPSX_FLAGS: --expand-div */
/* Font glyph selection (0x80038BC0..0x8003999C): the glyph table lookups, the
 * selection state flags, the shuffled code list and its incremental load, and
 * stepping the selection through the cached glyph slots. All of it reads and
 * writes g_FontSelectionState (main_tu_evidence G0313). */
#include "common.h"
#include "pe1/font.h"
#include "pe1/cdrom.h"
#include "pe1/psyq_libc.h"

/* The slot-search tails store the selected byte and reload it through a
 * byte-array view of its own symbol after a memory barrier, as retail does. */
extern u8 D_80091A1F_rd[] __asm__("D_80091A1F");
/* The next-glyph search stores the selected byte through a 16-byte record
 * view of its symbol. */
extern struct { char _[16]; } D_80091A1F_o __asm__("D_80091A1F");

unsigned char Render_DrawTextDigit(FontGlyphTable *table, unsigned char mode)
{
    unsigned char selected;
    int code;
    int i, count;
    FontGlyphGroups *groups;
    FontGlyphSlots *slots;
    /* Matching debt: retail reserves 16 stack bytes without accessing them.
     * The original locals are unknown; this preserves that frame on GCC 2.7.2. */
    int stack_pad[2];

    if (!table) table = g_FontSelectionState.table;
    switch (mode) {
    case 0: code = 3; break;
    case 1: code = (unsigned char)((unsigned)g_FontSelectionState.codeIndex % 10) != 0; break;
    case 2: code = 2; break;
    default: code = 4; break;
    }
    selected = 0;
    i = 0;
    count = table->groups.count;
    groups = &table->groups;
    if (count > 0) {
        int limit;
        code &= 255;
        limit = count;
        do {
            if (groups->codes[i] == code) {
                selected = i;
                i = groups->count;
            }
            ++i;
        } while (i < limit);
    }
    slots = (FontGlyphSlots *)(groups + 1);
    for (i = 0; i < slots->count; ++i) {
        if (slots->indices[i] == selected) return i;
    }
    return 255;
}

/* Code of the glyph cached in slot `index`. */
int func_80038CE4(int index)
{
    FontGlyphTable *table = g_FontSelectionState.table;

    return table->groups.codes[table->slots.indices[(u8)index]];
}

int Menu_IsEquipSlotActive(void) {
    return g_FontSelectionState.active != 0;
}

int Menu_ConsumeEquipSlotFlag(void) {
    u8 *ptr;

    ptr = &g_FontSelectionState.loadFailed;
    if (*ptr != 0) {
        *ptr = 0;
        return 0;
    }

    return 0xFF;
}

int func_80038D48(void) {
    u32 *state = &g_FontSelectionState.seed;

    if (*state != 0) {
        *state = 0;
        return 0;
    }

    return 0xFF;
}

static inline int find_slot(u8 *table)
{
    int found = 0;
    int k;
    u8 *groups = table + 1;
    u8 *slots;
    u8 *entry;
    unsigned int count_offset;

    /* Retain the separate loop-bound reload generated by stock GCC. */
    count_offset = 3;
    for (k = 0; k < table[count_offset]; k++) {
        entry = groups + k;
        if (entry[3] == 2) {
            found = k;
            k = groups[2];
        }
    }
    slots = groups + 0x1B;
    for (k = 0; k < groups[0x1B]; k++) {
        entry = slots + k;
        if (entry[1] == (found & 255)) {
            return k;
        }
    }
    return 255;
}

u8 Render_LoadFontGlyphAlt(void)
{
    u16 *range;
    FontGlyphLoadState *state;
    int read_status;
    int poll_status;
    u8 i;
    int forced_slot;
    s16 unique_count;
    int glyph;
    s16 limit;
    u8 duplicate;
    u8 j;

retry_read:
    state = &D_800B0DD8;
    range = D_80093176;
    do {
        read_status = CdRom_ReadSectorsFromLba(state->baseLba + range[0],
                                             state->buffer,
                                             range[1] - range[0]);
    } while (read_status == -1);

    for (;;) {
        poll_status = CdRom_PollReady();
        if (poll_status == 0) {
            break;
        }
        if (poll_status == -1) {
            goto retry_read;
        }
    }

    D_8009ECD8.codeCount = D_800B0E6C[0];
    if (g_FontSelectionState.loadFailed == 0 && g_FontSelectionState.seed == 0) {
        do {
            g_FontSelectionState.seed = rand() % 0x7FFF;
        } while (g_FontSelectionState.seed == 0);
    }

    /* The identical arms retain the stock compiler's branch-delay scheduling. */
    if (g_FontSelectionState.loadFailed) {
        srand(g_FontSelectionState.seed);
    } else {
        srand(g_FontSelectionState.seed);
    }

    unique_count = 0;
    forced_slot = 0;
    for (i = 0; (u8)i < 0x45; i++) {
        if (((u8)i + 2) % 10 == 0) {
            (D_8009EE22 + 2)[(u8)i] = forced_slot;
            forced_slot++;
            continue;
        }

        if ((u8)i + 2 < 10) {
            limit = 0x68;
        } else if ((u8)i + 2 < 20) {
            limit = 0x6D;
        } else {
            limit = 0x71;
        }

        if (D_8009ECD8.codeCount - 1 < limit) {
            limit = D_8009ECD8.codeCount;
            limit = limit - 1;
        }

        glyph = (rand() % (limit - 7)) + 7;
        (D_8009EE22 + 2)[(u8)i] = glyph;

        if (unique_count < D_8009ECD8.codeCount - 9) {
            do {
                duplicate = 1;
                for (j = 0; j < i; j++) {
                    if ((D_8009EE22 + 2)[j] == (D_8009EE22 + 2)[(u8)i]) {
                        (D_8009EE22 + 2)[(u8)i] = (rand() % (limit - 7)) + 7;
                        duplicate = 0;
                    }
                }
            } while (duplicate == 0);
        }
        unique_count++;
    }

    Render_LoadFontGlyph((D_8009EE22 + 2)[0]);

    g_FontSelectionState.active = 1;
    g_FontSelectionState.codeIndex = 2;
    g_FontSelectionState.code = (D_8009EE22 + 2)[0];
    g_FontSelectionState.table = &D_8009ECD8;

    D_80091A1F = find_slot((u8 *)&D_8009ECD8);
    {
        u8 *result = (u8 *)g_FontSelectionState.table;
        /* This assembler-backed flag is ordinary RAM. The unqualified byte
         * view preserves the lookup's stock-GCC integer promotion. */
        return *(result + *(result + *(u8 *)&D_80091A1F + 0x1D) + 4);
    }
}


u8 Render_StepFontLoad(void) {
    u8 state;
    u8 next;
    u8 code;
    FontGlyphTable *table;
    FontGlyphGroups *groups;
    FontGlyphTable *result;
    s32 slot;
    u16 digit;
    s32 i;
    s32 count;
    s32 found;
    u8 *statep;
    int stack_pad[3];

    statep = &D_80091A1D;
    state = *statep;
    if (state < 3U) {
        *statep = 1;
        return 0xFFU;
    }

    next = state - 1;
    *statep = next;
    code = D_8009EE22[next];
    g_FontSelectionState.code = code;
    Render_LoadFontGlyph(code);

    digit = (u8)(D_80091A1D % 10) != 0;
    asm("" : "=r"(digit) : "0"(digit));
    found = 0;
    i = 0;

    table = g_FontSelectionState.table;
    count = table->groups.count;
    groups = &table->groups;
    if (count > 0) {
        digit &= 0xFF;
        do {
            if (groups->codes[i] == digit) {
                found = i;
                i = groups->count;
            }
            i++;
        } while (i < count);
        i = 0;
    }

    {
        s32 count2;
        s32 wanted;
        FontGlyphSlots *slots;
        slot = ((FontGlyphSlots *)(groups + 1))->count;
        slots = (FontGlyphSlots *)(groups + 1);
        if (slot > 0) {
            wanted = found & 0xFF;
            count2 = slot;
            do {
                if (slots->indices[i] == wanted) {
                    slot = i;
                    goto store;
                }
                i++;
            } while (i < count2);
        }
    }
    slot = 0xFF;

store:
        g_FontSelectionState.selected = slot;
    __asm__ volatile("" : : : "memory");
    result = g_FontSelectionState.table;
    return result->groups.codes[result->slots.indices[D_80091A1F_rd[0]]];
}

int Menu_GetEquipSlotStateOrIndex(void) {
    if (g_FontSelectionState.active == 0) {
        return 1;
    }

    return g_FontSelectionState.codeIndex;
}

u8 Render_FindFontGlyphSlot(void) {
    u8 temp_v0;
    u8 temp_a0;
    FontGlyphTable *table;
    FontGlyphGroups *groups;
    FontGlyphSlots *slots;
    s32 i;
    s32 found;
    s32 slot;
    FontGlyphTable *result;

    if (g_FontSelectionState.codeIndex >= 0x46U) {
        g_FontSelectionState.loadFailed = 1;
        return 0xFFU;
    }
    temp_v0 = g_FontSelectionState.codeIndex + 1;
    g_FontSelectionState.codeIndex = temp_v0;
    temp_a0 = D_8009EE22[temp_v0];
    g_FontSelectionState.loadFailed = 0;
    g_FontSelectionState.code = temp_a0;
    Render_LoadFontGlyph(temp_a0);
    found = 0;
    table = g_FontSelectionState.table;
    groups = &table->groups;
    for (i = 0; i < table->groups.count; i++) {
        if (groups->codes[i] == 2) {
            found = i;
            i = groups->count;
        }
    }
    slots = (FontGlyphSlots *)(groups + 1);
    for (i = 0; i < ((FontGlyphSlots *)(groups + 1))->count; i++) {
        if (slots->indices[i] == (found & 0xFF)) {
            slot = i;
            goto store;
        }
    }
    slot = 0xFF;
store:
    *(u8 *)&D_80091A1F_o = slot;
    __asm__ volatile("" : : : "memory");
    result = g_FontSelectionState.table;
    return result->groups.codes[result->slots.indices[g_FontSelectionState.selected]];
}

static inline int findSlot(int useDecimalGroup)
{
    unsigned char code;
    int i, count;
    int found;
    FontGlyphGroups *groups;
    FontGlyphSlots *slots;
    FontGlyphTable *table;

    code = useDecimalGroup ? (unsigned char)((unsigned)g_FontSelectionState.codeIndex % 10) != 0 : 3;
    found = 0;
    table = g_FontSelectionState.table;
    i = 0;
    count = table->groups.count;
    groups = &table->groups;
    for (; i < count; ++i) {
        if (groups->codes[i] == (unsigned char)code) {
            found = i;
            i = groups->count;
        }
    }
    slots = (FontGlyphSlots *)(groups + 1);
    for (i = 0; i < slots->count; ++i) {
        if (slots->indices[i] == (unsigned char)found)
            return i;
    }
    return 255;
}

unsigned char Render_SetFontGlyphByCode(unsigned char code)
{
    int selected;
    if ((int)code - 2 >= 69) {
        g_FontSelectionState.loadFailed = 1;
        return 255;
    }
    if (code < 2) {
        g_FontSelectionState.codeIndex = 1;
        return 255;
    }
    g_FontSelectionState.codeIndex = code;
    code = D_8009EE22[code];
    g_FontSelectionState.code = code;
    Render_LoadFontGlyph(code);
    if (g_FontSelectionState.loadFailed == 1)
        selected = findSlot(1);
    else
        selected = findSlot(0);
    D_80091A1F = selected;
    /* Keep retail's store and reload of the selected byte. */
    asm volatile("" : "=m"(D_80091A1F) : "0"(D_80091A1F));
    {
        FontGlyphTable *table = g_FontSelectionState.table;
        int index = D_80091A1F;
        g_FontSelectionState.loadFailed = 0;
        return table->groups.codes[table->slots.indices[index]];
    }
}

unsigned char Render_GetOrLoadFontGlyph(unsigned char action)
{
    unsigned char code, group;
    int i;
    FontGlyphSlots *slots;
    FontGlyphTable *table = g_FontSelectionState.table;
    code = table->groups.codes[table->slots.indices[g_FontSelectionState.selected]];
    if (code < 2 || code == 24 || code == 31 || code == 38 ||
        code == 45 || code == 52 || code == 59) {
        if (action == 20)
            return Render_FindFontGlyphSlot();
    }
    if (code == 2 && action == 22)
        return Render_StepFontLoad();
    slots = &g_FontSelectionState.table->slots;
    switch (action) {
    case 20:
        group = slots->groupKeys[g_FontSelectionState.selected];
        for (i = g_FontSelectionState.selected - 1; i >= 0; --i) {
            if (slots->groupKeys[i] == group) {
                g_FontSelectionState.selected = i;
                i = 0;
            }
        }
        break;
    case 21:
        --g_FontSelectionState.selected;
        break;
    case 22:
        group = slots->groupKeys[g_FontSelectionState.selected];
        for (i = g_FontSelectionState.selected + 1; i < slots->count; ++i) {
            if (slots->groupKeys[i] == group) {
                g_FontSelectionState.selected = i;
                i = slots->count;
            }
        }
        break;
    case 23:
        ++g_FontSelectionState.selected;
        break;
    }
    {
        FontGlyphTable *last = g_FontSelectionState.table;
        return last->groups.codes[last->slots.indices[g_FontSelectionState.selected]];
    }
}

int Menu_FindSelectedEquipSlotItem(void) {
    FontGlyphTable *table;
    FontGlyphGroups *groups;
    FontGlyphSlots *slots;
    FontGlyphTable *result;
    int i;
    int found;
    int slot;

    found = 0;
    table = g_FontSelectionState.table;
    groups = &table->groups;
    for (i = 0; i < table->groups.count; i++) {
        if (groups->codes[i] == 3) {
            found = i;
            i = groups->count;
        }
    }
    slots = (FontGlyphSlots *)(groups + 1);
    for (i = 0; i < ((FontGlyphSlots *)(groups + 1))->count; i++) {
        if (slots->indices[i] == (found & 0xFF)) {
            slot = i;
            goto store;
        }
    }
    slot = 0xFF;
store:
    g_FontSelectionState.selected = slot;
    __asm__ volatile("" : : : "memory");
    result = g_FontSelectionState.table;
    return result->groups.codes[result->slots.indices[D_80091A1F_rd[0]]];
}

int Menu_ResetEquipSlotState(void) {
    g_FontSelectionState.selected = 0xFF;
    g_FontSelectionState.active = 0;
    g_FontSelectionState.code = 0;
    g_FontSelectionState.table = 0;
    return 0;
}
