.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.4 */

nonmatching Menu_DrawExpReviewPanel, 0x210

glabel Menu_DrawExpReviewPanel
    /* 3C170 8004B970 7802838F */  lw         $v1, %gp_rel(D_8009CFE8)($gp)
    /* 3C174 8004B974 7C02828F */  lw         $v0, %gp_rel(D_8009CFEC)($gp)
    /* 3C178 8004B978 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 3C17C 8004B97C 1C00BFAF */  sw         $ra, 0x1C($sp)
    /* 3C180 8004B980 1800B2AF */  sw         $s2, 0x18($sp)
    /* 3C184 8004B984 1400B1AF */  sw         $s1, 0x14($sp)
    /* 3C188 8004B988 2A886200 */  slt        $s1, $v1, $v0
    /* 3C18C 8004B98C 03002016 */  bnez       $s1, .L8004B99C
    /* 3C190 8004B990 1000B0AF */   sw        $s0, 0x10($sp)
    /* 3C194 8004B994 D949010C */  jal        Akao_FlushBgmVolumeFade
    /* 3C198 8004B998 00000000 */   nop
  .L8004B99C:
    /* 3C19C 8004B99C FE76010C */  jal        Aya_GetLevelExpTable
    /* 3C1A0 8004B9A0 00000000 */   nop
    /* 3C1A4 8004B9A4 7802848F */  lw         $a0, %gp_rel(D_8009CFE8)($gp)
    /* 3C1A8 8004B9A8 2A6E010C */  jal        Stat_BinarySearch
    /* 3C1AC 8004B9AC 21284000 */   addu      $a1, $v0, $zero
    /* 3C1B0 8004B9B0 21804000 */  addu       $s0, $v0, $zero
    /* 3C1B4 8004B9B4 6200022A */  slti       $v0, $s0, 0x62
    /* 3C1B8 8004B9B8 09004010 */  beqz       $v0, .L8004B9E0
    /* 3C1BC 8004B9BC 21900000 */   addu      $s2, $zero, $zero
    /* 3C1C0 8004B9C0 FE76010C */  jal        Aya_GetLevelExpTable
    /* 3C1C4 8004B9C4 00000000 */   nop
    /* 3C1C8 8004B9C8 80181000 */  sll        $v1, $s0, 2
    /* 3C1CC 8004B9CC 21186200 */  addu       $v1, $v1, $v0
    /* 3C1D0 8004B9D0 0400638C */  lw         $v1, 0x4($v1)
    /* 3C1D4 8004B9D4 7802828F */  lw         $v0, %gp_rel(D_8009CFE8)($gp)
    /* 3C1D8 8004B9D8 792E0108 */  j          .L8004B9E4
    /* 3C1DC 8004B9DC 23906200 */   subu      $s2, $v1, $v0
  .L8004B9E0:
    /* 3C1E0 8004B9E0 7802828F */  lw         $v0, %gp_rel(D_8009CFE8)($gp)
  .L8004B9E4:
    /* 3C1E4 8004B9E4 8002838F */  lw         $v1, %gp_rel(D_8009CFF0)($gp)
    /* 3C1E8 8004B9E8 21105100 */  addu       $v0, $v0, $s1
    /* 3C1EC 8004B9EC 2A187000 */  slt        $v1, $v1, $s0
    /* 3C1F0 8004B9F0 780282AF */  sw         $v0, %gp_rel(D_8009CFE8)($gp)
    /* 3C1F4 8004B9F4 0A006010 */  beqz       $v1, .L8004BA20
    /* 3C1F8 8004B9F8 01000424 */   addiu     $a0, $zero, 0x1
    /* 3C1FC 8004B9FC 3C000224 */  addiu      $v0, $zero, 0x3C
    /* 3C200 8004BA00 800290AF */  sw         $s0, %gp_rel(D_8009CFF0)($gp)
    /* 3C204 8004BA04 080282AF */  sw         $v0, %gp_rel(D_8009CF78)($gp)
    /* 3C208 8004BA08 8D8A010C */  jal        MenuWidget_FindByModeAndSelectedBase
    /* 3C20C 8004BA0C 16000524 */   addiu     $a1, $zero, 0x16
    /* 3C210 8004BA10 03004014 */  bnez       $v0, .L8004BA20
    /* 3C214 8004BA14 00000000 */   nop
    /* 3C218 8004BA18 202F010C */  jal        Menu_CreateLevelUpBanner
    /* 3C21C 8004BA1C 00000000 */   nop
  .L8004BA20:
    /* 3C220 8004BA20 0802828F */  lw         $v0, %gp_rel(D_8009CF78)($gp)
    /* 3C224 8004BA24 00000000 */  nop
    /* 3C228 8004BA28 09004010 */  beqz       $v0, .L8004BA50
    /* 3C22C 8004BA2C FFFF4224 */   addiu     $v0, $v0, -0x1
    /* 3C230 8004BA30 080282AF */  sw         $v0, %gp_rel(D_8009CF78)($gp)
    /* 3C234 8004BA34 06004014 */  bnez       $v0, .L8004BA50
    /* 3C238 8004BA38 00000000 */   nop
    /* 3C23C 8004BA3C 01000424 */  addiu      $a0, $zero, 0x1
    /* 3C240 8004BA40 8D8A010C */  jal        MenuWidget_FindByModeAndSelectedBase
    /* 3C244 8004BA44 16000524 */   addiu     $a1, $zero, 0x16
    /* 3C248 8004BA48 C78B010C */  jal        MenuWidget_DestroyNode
    /* 3C24C 8004BA4C 21204000 */   addu      $a0, $v0, $zero
  .L8004BA50:
    /* 3C250 8004BA50 04000424 */  addiu      $a0, $zero, 0x4
    /* 3C254 8004BA54 297A010C */  jal        Draw_OffsetCursor
    /* 3C258 8004BA58 04000524 */   addiu     $a1, $zero, 0x4
    /* 3C25C 8004BA5C 317A010C */  jal        Draw_StatePush
    /* 3C260 8004BA60 00000000 */   nop
    /* 3C264 8004BA64 1377010C */  jal        Str_LookupTable4
    /* 3C268 8004BA68 09000424 */   addiu     $a0, $zero, 0x9
    /* 3C26C 8004BA6C 9F7C010C */  jal        Draw_PrintRawText
    /* 3C270 8004BA70 21204000 */   addu      $a0, $v0, $zero
    /* 3C274 8004BA74 50000424 */  addiu      $a0, $zero, 0x50
    /* 3C278 8004BA78 297A010C */  jal        Draw_OffsetCursor
    /* 3C27C 8004BA7C 21280000 */   addu      $a1, $zero, $zero
    /* 3C280 8004BA80 0F00023C */  lui        $v0, (0xF423F >> 16)
    /* 3C284 8004BA84 3F424234 */  ori        $v0, $v0, (0xF423F & 0xFFFF)
    /* 3C288 8004BA88 0F00043C */  lui        $a0, (0xF423F >> 16)
    /* 3C28C 8004BA8C 7802838F */  lw         $v1, %gp_rel(D_8009CFE8)($gp)
    /* 3C290 8004BA90 00000000 */  nop
    /* 3C294 8004BA94 2A104300 */  slt        $v0, $v0, $v1
    /* 3C298 8004BA98 02004014 */  bnez       $v0, .L8004BAA4
    /* 3C29C 8004BA9C 3F428434 */   ori       $a0, $a0, (0xF423F & 0xFFFF)
    /* 3C2A0 8004BAA0 21206000 */  addu       $a0, $v1, $zero
  .L8004BAA4:
    /* 3C2A4 8004BAA4 4A81010C */  jal        Draw_PrintNumberWidth6
    /* 3C2A8 8004BAA8 00000000 */   nop
    /* 3C2AC 8004BAAC 02000424 */  addiu      $a0, $zero, 0x2
    /* 3C2B0 8004BAB0 297A010C */  jal        Draw_OffsetCursor
    /* 3C2B4 8004BAB4 02000524 */   addiu     $a1, $zero, 0x2
    /* 3C2B8 8004BAB8 D97A010C */  jal        Draw_AllocSprite
    /* 3C2BC 8004BABC 8A000424 */   addiu     $a0, $zero, 0x8A
    /* 3C2C0 8004BAC0 457A010C */  jal        Draw_StatePop
    /* 3C2C4 8004BAC4 00000000 */   nop
    /* 3C2C8 8004BAC8 21200000 */  addu       $a0, $zero, $zero
    /* 3C2CC 8004BACC 297A010C */  jal        Draw_OffsetCursor
    /* 3C2D0 8004BAD0 0E000524 */   addiu     $a1, $zero, 0xE
    /* 3C2D4 8004BAD4 317A010C */  jal        Draw_StatePush
    /* 3C2D8 8004BAD8 00000000 */   nop
    /* 3C2DC 8004BADC 1377010C */  jal        Str_LookupTable4
    /* 3C2E0 8004BAE0 0A000424 */   addiu     $a0, $zero, 0xA
    /* 3C2E4 8004BAE4 9F7C010C */  jal        Draw_PrintRawText
    /* 3C2E8 8004BAE8 21204000 */   addu      $a0, $v0, $zero
    /* 3C2EC 8004BAEC 50000424 */  addiu      $a0, $zero, 0x50
    /* 3C2F0 8004BAF0 297A010C */  jal        Draw_OffsetCursor
    /* 3C2F4 8004BAF4 21280000 */   addu      $a1, $zero, $zero
    /* 3C2F8 8004BAF8 4A81010C */  jal        Draw_PrintNumberWidth6
    /* 3C2FC 8004BAFC 21204002 */   addu      $a0, $s2, $zero
    /* 3C300 8004BB00 02000424 */  addiu      $a0, $zero, 0x2
    /* 3C304 8004BB04 297A010C */  jal        Draw_OffsetCursor
    /* 3C308 8004BB08 02000524 */   addiu     $a1, $zero, 0x2
    /* 3C30C 8004BB0C D97A010C */  jal        Draw_AllocSprite
    /* 3C310 8004BB10 8A000424 */   addiu     $a0, $zero, 0x8A
    /* 3C314 8004BB14 457A010C */  jal        Draw_StatePop
    /* 3C318 8004BB18 00000000 */   nop
    /* 3C31C 8004BB1C 21200000 */  addu       $a0, $zero, $zero
    /* 3C320 8004BB20 297A010C */  jal        Draw_OffsetCursor
    /* 3C324 8004BB24 14000524 */   addiu     $a1, $zero, 0x14
    /* 3C328 8004BB28 317A010C */  jal        Draw_StatePush
    /* 3C32C 8004BB2C 00000000 */   nop
    /* 3C330 8004BB30 1377010C */  jal        Str_LookupTable4
    /* 3C334 8004BB34 0C000424 */   addiu     $a0, $zero, 0xC
    /* 3C338 8004BB38 9F7C010C */  jal        Draw_PrintRawText
    /* 3C33C 8004BB3C 21204000 */   addu      $a0, $v0, $zero
    /* 3C340 8004BB40 74000424 */  addiu      $a0, $zero, 0x74
    /* 3C344 8004BB44 297A010C */  jal        Draw_OffsetCursor
    /* 3C348 8004BB48 21280000 */   addu      $a1, $zero, $zero
    /* 3C34C 8004BB4C B35F010C */  jal        Menu_GetBattleCount
    /* 3C350 8004BB50 00000000 */   nop
    /* 3C354 8004BB54 7E81010C */  jal        Draw_PrintNumberWidth2
    /* 3C358 8004BB58 21204000 */   addu      $a0, $v0, $zero
    /* 3C35C 8004BB5C 457A010C */  jal        Draw_StatePop
    /* 3C360 8004BB60 00000000 */   nop
    /* 3C364 8004BB64 1C00BF8F */  lw         $ra, 0x1C($sp)
    /* 3C368 8004BB68 1800B28F */  lw         $s2, 0x18($sp)
    /* 3C36C 8004BB6C 1400B18F */  lw         $s1, 0x14($sp)
    /* 3C370 8004BB70 1000B08F */  lw         $s0, 0x10($sp)
    /* 3C374 8004BB74 2000BD27 */  addiu      $sp, $sp, 0x20
    /* 3C378 8004BB78 0800E003 */  jr         $ra
    /* 3C37C 8004BB7C 00000000 */   nop
endlabel Menu_DrawExpReviewPanel
