.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.4 */

nonmatching Menu_CreateNotificationDialog, 0x15C

glabel Menu_CreateNotificationDialog
    /* 3D450 8004CC50 D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* 3D454 8004CC54 2400B5AF */  sw         $s5, 0x24($sp)
    /* 3D458 8004CC58 21A88000 */  addu       $s5, $a0, $zero
    /* 3D45C 8004CC5C 2000B4AF */  sw         $s4, 0x20($sp)
    /* 3D460 8004CC60 21A0A000 */  addu       $s4, $a1, $zero
    /* 3D464 8004CC64 01000424 */  addiu      $a0, $zero, 0x1
    /* 3D468 8004CC68 28000524 */  addiu      $a1, $zero, 0x28
    /* 3D46C 8004CC6C 2800BFAF */  sw         $ra, 0x28($sp)
    /* 3D470 8004CC70 1C00B3AF */  sw         $s3, 0x1C($sp)
    /* 3D474 8004CC74 1800B2AF */  sw         $s2, 0x18($sp)
    /* 3D478 8004CC78 1400B1AF */  sw         $s1, 0x14($sp)
    /* 3D47C 8004CC7C 8D8A010C */  jal        MenuWidget_FindByModeAndSelectedBase
    /* 3D480 8004CC80 1000B0AF */   sw        $s0, 0x10($sp)
    /* 3D484 8004CC84 2B980200 */  sltu       $s3, $zero, $v0
    /* 3D488 8004CC88 02006012 */  beqz       $s3, .L8004CC94
    /* 3D48C 8004CC8C 28001024 */   addiu     $s0, $zero, 0x28
    /* 3D490 8004CC90 3D001024 */  addiu      $s0, $zero, 0x3D
  .L8004CC94:
    /* 3D494 8004CC94 318B010C */  jal        MenuWidget_GetCurrentNode
    /* 3D498 8004CC98 00000000 */   nop
    /* 3D49C 8004CC9C 21200002 */  addu       $a0, $s0, $zero
    /* 3D4A0 8004CCA0 21284000 */  addu       $a1, $v0, $zero
    /* 3D4A4 8004CCA4 21300000 */  addu       $a2, $zero, $zero
    /* 3D4A8 8004CCA8 4B8B010C */  jal        MenuWidget_CreateSimpleNode
    /* 3D4AC 8004CCAC 01000724 */   addiu     $a3, $zero, 0x1
    /* 3D4B0 8004CCB0 21200002 */  addu       $a0, $s0, $zero
    /* 3D4B4 8004CCB4 21884000 */  addu       $s1, $v0, $zero
    /* 3D4B8 8004CCB8 21282002 */  addu       $a1, $s1, $zero
    /* 3D4BC 8004CCBC 8B8C010C */  jal        MenuWidget_CreateNode
    /* 3D4C0 8004CCC0 21302002 */   addu      $a2, $s1, $zero
    /* 3D4C4 8004CCC4 21904000 */  addu       $s2, $v0, $zero
    /* 3D4C8 8004CCC8 21204002 */  addu       $a0, $s2, $zero
    /* 3D4CC 8004CCCC 0580023C */  lui        $v0, %hi(Menu_DrawNotificationText)
    /* 3D4D0 8004CCD0 D4CD4224 */  addiu      $v0, $v0, %lo(Menu_DrawNotificationText)
    /* 3D4D4 8004CCD4 300022AE */  sw         $v0, 0x30($s1)
    /* 3D4D8 8004CCD8 0580023C */  lui        $v0, %hi(Menu_HandleDeferredCallbackInput)
    /* 3D4DC 8004CCDC 30D04224 */  addiu      $v0, $v0, %lo(Menu_HandleDeferredCallbackInput)
    /* 3D4E0 8004CCE0 2C0022AE */  sw         $v0, 0x2C($s1)
    /* 3D4E4 8004CCE4 0580023C */  lui        $v0, %hi(Menu_DrawNotificationDialogContent)
    /* 3D4E8 8004CCE8 A8FF4224 */  addiu      $v0, $v0, %lo(Menu_DrawNotificationDialogContent)
    /* 3D4EC 8004CCEC 2E8B010C */  jal        MenuWidget_SetCurrentNode
    /* 3D4F0 8004CCF0 300042AE */   sw        $v0, 0x30($s2)
    /* 3D4F4 8004CCF4 0934010C */  jal        Menu_SetDeferredCallback
    /* 3D4F8 8004CCF8 21200000 */   addu      $a0, $zero, $zero
    /* 3D4FC 8004CCFC 1377010C */  jal        Str_LookupTable4
    /* 3D500 8004CD00 2120A002 */   addu      $a0, $s5, $zero
    /* 3D504 8004CD04 80211300 */  sll        $a0, $s3, 6
    /* 3D508 8004CD08 0A80033C */  lui        $v1, %hi(D_800A1A20)
    /* 3D50C 8004CD0C 201A6324 */  addiu      $v1, $v1, %lo(D_800A1A20)
    /* 3D510 8004CD10 21808300 */  addu       $s0, $a0, $v1
    /* 3D514 8004CD14 21200002 */  addu       $a0, $s0, $zero
    /* 3D518 8004CD18 F34A010C */  jal        Util_CopyFFTerminatedBytes
    /* 3D51C 8004CD1C 21284000 */   addu      $a1, $v0, $zero
    /* 3D520 8004CD20 06008012 */  beqz       $s4, .L8004CD3C
    /* 3D524 8004CD24 00000000 */   nop
    /* 3D528 8004CD28 1377010C */  jal        Str_LookupTable4
    /* 3D52C 8004CD2C 21208002 */   addu      $a0, $s4, $zero
    /* 3D530 8004CD30 21200002 */  addu       $a0, $s0, $zero
    /* 3D534 8004CD34 024B010C */  jal        Util_AppendFFTerminatedBytes
    /* 3D538 8004CD38 21284000 */   addu      $a1, $v0, $zero
  .L8004CD3C:
    /* 3D53C 8004CD3C 687C010C */  jal        Draw_MeasureTextWidth
    /* 3D540 8004CD40 21200002 */   addu      $a0, $s0, $zero
    /* 3D544 8004CD44 64004228 */  slti       $v0, $v0, 0x64
    /* 3D548 8004CD48 04004014 */  bnez       $v0, .L8004CD5C
    /* 3D54C 8004CD4C 64000324 */   addiu     $v1, $zero, 0x64
    /* 3D550 8004CD50 687C010C */  jal        Draw_MeasureTextWidth
    /* 3D554 8004CD54 21200002 */   addu      $a0, $s0, $zero
    /* 3D558 8004CD58 21184000 */  addu       $v1, $v0, $zero
  .L8004CD5C:
    /* 3D55C 8004CD5C 14006224 */  addiu      $v0, $v1, 0x14
    /* 3D560 8004CD60 340022AE */  sw         $v0, 0x34($s1)
    /* 3D564 8004CD64 2C010224 */  addiu      $v0, $zero, 0x12C
    /* 3D568 8004CD68 23104300 */  subu       $v0, $v0, $v1
    /* 3D56C 8004CD6C 3400238E */  lw         $v1, 0x34($s1)
    /* 3D570 8004CD70 43100200 */  sra        $v0, $v0, 1
    /* 3D574 8004CD74 180022AE */  sw         $v0, 0x18($s1)
    /* 3D578 8004CD78 BCFF6324 */  addiu      $v1, $v1, -0x44
    /* 3D57C 8004CD7C A277010C */  jal        Queue_Init
    /* 3D580 8004CD80 180043AE */   sw        $v1, 0x18($s2)
    /* 3D584 8004CD84 2800BF8F */  lw         $ra, 0x28($sp)
    /* 3D588 8004CD88 2400B58F */  lw         $s5, 0x24($sp)
    /* 3D58C 8004CD8C 2000B48F */  lw         $s4, 0x20($sp)
    /* 3D590 8004CD90 1C00B38F */  lw         $s3, 0x1C($sp)
    /* 3D594 8004CD94 1800B28F */  lw         $s2, 0x18($sp)
    /* 3D598 8004CD98 1400B18F */  lw         $s1, 0x14($sp)
    /* 3D59C 8004CD9C 1000B08F */  lw         $s0, 0x10($sp)
    /* 3D5A0 8004CDA0 3000BD27 */  addiu      $sp, $sp, 0x30
    /* 3D5A4 8004CDA4 0800E003 */  jr         $ra
    /* 3D5A8 8004CDA8 00000000 */   nop
endlabel Menu_CreateNotificationDialog
