.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.4 */

nonmatching Menu_StatSlotInputHandler, 0x18C

glabel Menu_StatSlotInputHandler
    /* 399C8 800491C8 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 399CC 800491CC 1400B1AF */  sw         $s1, 0x14($sp)
    /* 399D0 800491D0 2188A000 */  addu       $s1, $a1, $zero
    /* 399D4 800491D4 21280000 */  addu       $a1, $zero, $zero
    /* 399D8 800491D8 1800BFAF */  sw         $ra, 0x18($sp)
    /* 399DC 800491DC 888A010C */  jal        MenuWidget_GetChild
    /* 399E0 800491E0 1000B0AF */   sw        $s0, 0x10($sp)
    /* 399E4 800491E4 21804000 */  addu       $s0, $v0, $zero
    /* 399E8 800491E8 00402232 */  andi       $v0, $s1, 0x4000
    /* 399EC 800491EC 3F004010 */  beqz       $v0, .L800492EC
    /* 399F0 800491F0 02000424 */   addiu     $a0, $zero, 0x2
    /* 399F4 800491F4 10000524 */  addiu      $a1, $zero, 0x10
    /* 399F8 800491F8 FFFF0224 */  addiu      $v0, $zero, -0x1
    /* 399FC 800491FC 8D8A010C */  jal        MenuWidget_FindByModeAndSelectedBase
    /* 39A00 80049200 440002AE */   sw        $v0, 0x44($s0)
    /* 39A04 80049204 21804000 */  addu       $s0, $v0, $zero
    /* 39A08 80049208 21200002 */  addu       $a0, $s0, $zero
    /* 39A0C 8004920C 440000AE */  sw         $zero, 0x44($s0)
    /* 39A10 80049210 4C8F010C */  jal        MenuWidget_ClampScroll
    /* 39A14 80049214 480000AE */   sw        $zero, 0x48($s0)
    /* 39A18 80049218 2E8B010C */  jal        MenuWidget_SetCurrentNode
    /* 39A1C 8004921C 21200002 */   addu      $a0, $s0, $zero
    /* 39A20 80049220 01000424 */  addiu      $a0, $zero, 0x1
    /* 39A24 80049224 8D8A010C */  jal        MenuWidget_FindByModeAndSelectedBase
    /* 39A28 80049228 0F000524 */   addiu     $a1, $zero, 0xF
    /* 39A2C 8004922C 21804000 */  addu       $s0, $v0, $zero
    /* 39A30 80049230 01000424 */  addiu      $a0, $zero, 0x1
    /* 39A34 80049234 8D8A010C */  jal        MenuWidget_FindByModeAndSelectedBase
    /* 39A38 80049238 0D000524 */   addiu     $a1, $zero, 0xD
    /* 39A3C 8004923C 21204000 */  addu       $a0, $v0, $zero
    /* 39A40 80049240 888A010C */  jal        MenuWidget_GetChild
    /* 39A44 80049244 21280000 */   addu      $a1, $zero, $zero
    /* 39A48 80049248 21184000 */  addu       $v1, $v0, $zero
    /* 39A4C 8004924C C001828F */  lw         $v0, %gp_rel(D_8009CF30)($gp)
    /* 39A50 80049250 1800058E */  lw         $a1, 0x18($s0)
    /* 39A54 80049254 06004014 */  bnez       $v0, .L80049270
    /* 39A58 80049258 B0000224 */   addiu     $v0, $zero, 0xB0
    /* 39A5C 8004925C 8000628C */  lw         $v0, 0x80($v1)
    /* 39A60 80049260 00000000 */  nop
    /* 39A64 80049264 02004014 */  bnez       $v0, .L80049270
    /* 39A68 80049268 A2000224 */   addiu     $v0, $zero, 0xA2
    /* 39A6C 8004926C 9C000224 */  addiu      $v0, $zero, 0x9C
  .L80049270:
    /* 39A70 80049270 23884500 */  subu       $s1, $v0, $a1
    /* 39A74 80049274 21200002 */  addu       $a0, $s0, $zero
    /* 39A78 80049278 21282002 */  addu       $a1, $s1, $zero
    /* 39A7C 8004927C 568C010C */  jal        MenuWidget_OffsetPosition
    /* 39A80 80049280 21300000 */   addu      $a2, $zero, $zero
    /* 39A84 80049284 668C010C */  jal        MenuWidget_ClearCursorY
    /* 39A88 80049288 21200002 */   addu      $a0, $s0, $zero
    /* 39A8C 8004928C 01000424 */  addiu      $a0, $zero, 0x1
    /* 39A90 80049290 8D8A010C */  jal        MenuWidget_FindByModeAndSelectedBase
    /* 39A94 80049294 0B000524 */   addiu     $a1, $zero, 0xB
    /* 39A98 80049298 21804000 */  addu       $s0, $v0, $zero
    /* 39A9C 8004929C 21200002 */  addu       $a0, $s0, $zero
    /* 39AA0 800492A0 21282002 */  addu       $a1, $s1, $zero
    /* 39AA4 800492A4 568C010C */  jal        MenuWidget_OffsetPosition
    /* 39AA8 800492A8 21300000 */   addu      $a2, $zero, $zero
    /* 39AAC 800492AC 668C010C */  jal        MenuWidget_ClearCursorY
    /* 39AB0 800492B0 21200002 */   addu      $a0, $s0, $zero
    /* 39AB4 800492B4 01000424 */  addiu      $a0, $zero, 0x1
    /* 39AB8 800492B8 8D8A010C */  jal        MenuWidget_FindByModeAndSelectedBase
    /* 39ABC 800492BC 2F000524 */   addiu     $a1, $zero, 0x2F
    /* 39AC0 800492C0 21804000 */  addu       $s0, $v0, $zero
    /* 39AC4 800492C4 21200002 */  addu       $a0, $s0, $zero
    /* 39AC8 800492C8 21282002 */  addu       $a1, $s1, $zero
    /* 39ACC 800492CC 568C010C */  jal        MenuWidget_OffsetPosition
    /* 39AD0 800492D0 21300000 */   addu      $a2, $zero, $zero
    /* 39AD4 800492D4 668C010C */  jal        MenuWidget_ClearCursorY
    /* 39AD8 800492D8 21200002 */   addu      $a0, $s0, $zero
    /* 39ADC 800492DC 9F49010C */  jal        Menu_PlayMoveSound
    /* 39AE0 800492E0 00000000 */   nop
    /* 39AE4 800492E4 CF240108 */  j          .L8004933C
    /* 39AE8 800492E8 01000224 */   addiu     $v0, $zero, 0x1
  .L800492EC:
    /* 39AEC 800492EC 0100023C */  lui        $v0, (0x10000 >> 16)
    /* 39AF0 800492F0 24102202 */  and        $v0, $s1, $v0
    /* 39AF4 800492F4 0A004010 */  beqz       $v0, .L80049320
    /* 39AF8 800492F8 40002232 */   andi      $v0, $s1, 0x40
    /* 39AFC 800492FC 0A8D010C */  jal        MenuWidget_GridCellIndex
    /* 39B00 80049300 21200002 */   addu      $a0, $s0, $zero
    /* 39B04 80049304 21200002 */  addu       $a0, $s0, $zero
    /* 39B08 80049308 5C29010C */  jal        Menu_OpenBonusPointSpendDialog
    /* 39B0C 8004930C 05004524 */   addiu     $a1, $v0, 0x5
    /* 39B10 80049310 7B49010C */  jal        Menu_PlayConfirmSound
    /* 39B14 80049314 00000000 */   nop
    /* 39B18 80049318 CF240108 */  j          .L8004933C
    /* 39B1C 8004931C 01000224 */   addiu     $v0, $zero, 0x1
  .L80049320:
    /* 39B20 80049320 06004010 */  beqz       $v0, .L8004933C
    /* 39B24 80049324 01000224 */   addiu     $v0, $zero, 0x1
    /* 39B28 80049328 2C24010C */  jal        func_800490B0
    /* 39B2C 8004932C 00000000 */   nop
    /* 39B30 80049330 8D49010C */  jal        Menu_PlayCancelSound
    /* 39B34 80049334 00000000 */   nop
    /* 39B38 80049338 01000224 */  addiu      $v0, $zero, 0x1
  .L8004933C:
    /* 39B3C 8004933C 1800BF8F */  lw         $ra, 0x18($sp)
    /* 39B40 80049340 1400B18F */  lw         $s1, 0x14($sp)
    /* 39B44 80049344 1000B08F */  lw         $s0, 0x10($sp)
    /* 39B48 80049348 2000BD27 */  addiu      $sp, $sp, 0x20
    /* 39B4C 8004934C 0800E003 */  jr         $ra
    /* 39B50 80049350 00000000 */   nop
endlabel Menu_StatSlotInputHandler
