.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.4 */

nonmatching Menu_InventoryPageNavHandler, 0x2E4

glabel Menu_InventoryPageNavHandler
    /* 3F758 8004EF58 D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* 3F75C 8004EF5C 1C00B3AF */  sw         $s3, 0x1C($sp)
    /* 3F760 8004EF60 21988000 */  addu       $s3, $a0, $zero
    /* 3F764 8004EF64 2000B4AF */  sw         $s4, 0x20($sp)
    /* 3F768 8004EF68 21A0A000 */  addu       $s4, $a1, $zero
    /* 3F76C 8004EF6C 21280000 */  addu       $a1, $zero, $zero
    /* 3F770 8004EF70 2800BFAF */  sw         $ra, 0x28($sp)
    /* 3F774 8004EF74 2400B5AF */  sw         $s5, 0x24($sp)
    /* 3F778 8004EF78 1800B2AF */  sw         $s2, 0x18($sp)
    /* 3F77C 8004EF7C 1400B1AF */  sw         $s1, 0x14($sp)
    /* 3F780 8004EF80 888A010C */  jal        MenuWidget_GetChild
    /* 3F784 8004EF84 1000B0AF */   sw        $s0, 0x10($sp)
    /* 3F788 8004EF88 0100023C */  lui        $v0, (0x14000 >> 16)
    /* 3F78C 8004EF8C 00404234 */  ori        $v0, $v0, (0x14000 & 0xFFFF)
    /* 3F790 8004EF90 24108202 */  and        $v0, $s4, $v0
    /* 3F794 8004EF94 5B004010 */  beqz       $v0, .L8004F104
    /* 3F798 8004EF98 40008232 */   andi      $v0, $s4, 0x40
    /* 3F79C 8004EF9C A250010C */  jal        Inv_GetPackedListCount
    /* 3F7A0 8004EFA0 00000000 */   nop
    /* 3F7A4 8004EFA4 54004010 */  beqz       $v0, .L8004F0F8
    /* 3F7A8 8004EFA8 02000424 */   addiu     $a0, $zero, 0x2
    /* 3F7AC 8004EFAC 8D8A010C */  jal        MenuWidget_FindByModeAndSelectedBase
    /* 3F7B0 8004EFB0 07000524 */   addiu     $a1, $zero, 0x7
    /* 3F7B4 8004EFB4 21884000 */  addu       $s1, $v0, $zero
    /* 3F7B8 8004EFB8 37002016 */  bnez       $s1, .L8004F098
    /* 3F7BC 8004EFBC 2BA81100 */   sltu      $s5, $zero, $s1
    /* 3F7C0 8004EFC0 01000424 */  addiu      $a0, $zero, 0x1
    /* 3F7C4 8004EFC4 8D8A010C */  jal        MenuWidget_FindByModeAndSelectedBase
    /* 3F7C8 8004EFC8 0D000524 */   addiu     $a1, $zero, 0xD
    /* 3F7CC 8004EFCC 21204000 */  addu       $a0, $v0, $zero
    /* 3F7D0 8004EFD0 888A010C */  jal        MenuWidget_GetChild
    /* 3F7D4 8004EFD4 21280000 */   addu      $a1, $zero, $zero
    /* 3F7D8 8004EFD8 21884000 */  addu       $s1, $v0, $zero
    /* 3F7DC 8004EFDC 01000424 */  addiu      $a0, $zero, 0x1
    /* 3F7E0 8004EFE0 8D8A010C */  jal        MenuWidget_FindByModeAndSelectedBase
    /* 3F7E4 8004EFE4 0F000524 */   addiu     $a1, $zero, 0xF
    /* 3F7E8 8004EFE8 21804000 */  addu       $s0, $v0, $zero
    /* 3F7EC 8004EFEC 01000424 */  addiu      $a0, $zero, 0x1
    /* 3F7F0 8004EFF0 8D8A010C */  jal        MenuWidget_FindByModeAndSelectedBase
    /* 3F7F4 8004EFF4 0D000524 */   addiu     $a1, $zero, 0xD
    /* 3F7F8 8004EFF8 21204000 */  addu       $a0, $v0, $zero
    /* 3F7FC 8004EFFC 888A010C */  jal        MenuWidget_GetChild
    /* 3F800 8004F000 21280000 */   addu      $a1, $zero, $zero
    /* 3F804 8004F004 21184000 */  addu       $v1, $v0, $zero
    /* 3F808 8004F008 C001828F */  lw         $v0, %gp_rel(D_8009CF30)($gp)
    /* 3F80C 8004F00C 1800058E */  lw         $a1, 0x18($s0)
    /* 3F810 8004F010 06004014 */  bnez       $v0, .L8004F02C
    /* 3F814 8004F014 B0000224 */   addiu     $v0, $zero, 0xB0
    /* 3F818 8004F018 8000628C */  lw         $v0, 0x80($v1)
    /* 3F81C 8004F01C 00000000 */  nop
    /* 3F820 8004F020 02004014 */  bnez       $v0, .L8004F02C
    /* 3F824 8004F024 A2000224 */   addiu     $v0, $zero, 0xA2
    /* 3F828 8004F028 9C000224 */  addiu      $v0, $zero, 0x9C
  .L8004F02C:
    /* 3F82C 8004F02C 23904500 */  subu       $s2, $v0, $a1
    /* 3F830 8004F030 21200002 */  addu       $a0, $s0, $zero
    /* 3F834 8004F034 21284002 */  addu       $a1, $s2, $zero
    /* 3F838 8004F038 568C010C */  jal        MenuWidget_OffsetPosition
    /* 3F83C 8004F03C 21300000 */   addu      $a2, $zero, $zero
    /* 3F840 8004F040 668C010C */  jal        MenuWidget_ClearCursorY
    /* 3F844 8004F044 21200002 */   addu      $a0, $s0, $zero
    /* 3F848 8004F048 01000424 */  addiu      $a0, $zero, 0x1
    /* 3F84C 8004F04C 8D8A010C */  jal        MenuWidget_FindByModeAndSelectedBase
    /* 3F850 8004F050 0B000524 */   addiu     $a1, $zero, 0xB
    /* 3F854 8004F054 21804000 */  addu       $s0, $v0, $zero
    /* 3F858 8004F058 21200002 */  addu       $a0, $s0, $zero
    /* 3F85C 8004F05C 21284002 */  addu       $a1, $s2, $zero
    /* 3F860 8004F060 568C010C */  jal        MenuWidget_OffsetPosition
    /* 3F864 8004F064 21300000 */   addu      $a2, $zero, $zero
    /* 3F868 8004F068 668C010C */  jal        MenuWidget_ClearCursorY
    /* 3F86C 8004F06C 21200002 */   addu      $a0, $s0, $zero
    /* 3F870 8004F070 01000424 */  addiu      $a0, $zero, 0x1
    /* 3F874 8004F074 8D8A010C */  jal        MenuWidget_FindByModeAndSelectedBase
    /* 3F878 8004F078 2F000524 */   addiu     $a1, $zero, 0x2F
    /* 3F87C 8004F07C 21804000 */  addu       $s0, $v0, $zero
    /* 3F880 8004F080 21200002 */  addu       $a0, $s0, $zero
    /* 3F884 8004F084 21284002 */  addu       $a1, $s2, $zero
    /* 3F888 8004F088 568C010C */  jal        MenuWidget_OffsetPosition
    /* 3F88C 8004F08C 21300000 */   addu      $a2, $zero, $zero
    /* 3F890 8004F090 668C010C */  jal        MenuWidget_ClearCursorY
    /* 3F894 8004F094 21200002 */   addu      $a0, $s0, $zero
  .L8004F098:
    /* 3F898 8004F098 21202002 */  addu       $a0, $s1, $zero
    /* 3F89C 8004F09C 440020AE */  sw         $zero, 0x44($s1)
    /* 3F8A0 8004F0A0 4C8F010C */  jal        MenuWidget_ClampScroll
    /* 3F8A4 8004F0A4 480020AE */   sw        $zero, 0x48($s1)
    /* 3F8A8 8004F0A8 2E8B010C */  jal        MenuWidget_SetCurrentNode
    /* 3F8AC 8004F0AC 21202002 */   addu      $a0, $s1, $zero
    /* 3F8B0 8004F0B0 0D00A012 */  beqz       $s5, .L8004F0E8
    /* 3F8B4 8004F0B4 35000424 */   addiu     $a0, $zero, 0x35
    /* 3F8B8 8004F0B8 21280000 */  addu       $a1, $zero, $zero
    /* 3F8BC 8004F0BC 21300000 */  addu       $a2, $zero, $zero
    /* 3F8C0 8004F0C0 4B8B010C */  jal        MenuWidget_CreateSimpleNode
    /* 3F8C4 8004F0C4 21380000 */   addu      $a3, $zero, $zero
    /* 3F8C8 8004F0C8 21984000 */  addu       $s3, $v0, $zero
    /* 3F8CC 8004F0CC 35000424 */  addiu      $a0, $zero, 0x35
    /* 3F8D0 8004F0D0 21286002 */  addu       $a1, $s3, $zero
    /* 3F8D4 8004F0D4 8B8C010C */  jal        MenuWidget_CreateNode
    /* 3F8D8 8004F0D8 21306002 */   addu      $a2, $s3, $zero
    /* 3F8DC 8004F0DC 0580033C */  lui        $v1, %hi(Menu_SetupSkillSubmenu)
    /* 3F8E0 8004F0E0 10FA6324 */  addiu      $v1, $v1, %lo(Menu_SetupSkillSubmenu)
    /* 3F8E4 8004F0E4 300043AC */  sw         $v1, 0x30($v0)
  .L8004F0E8:
    /* 3F8E8 8004F0E8 7B49010C */  jal        Menu_PlayConfirmSound
    /* 3F8EC 8004F0EC 00000000 */   nop
    /* 3F8F0 8004F0F0 413C0108 */  j          .L8004F104
    /* 3F8F4 8004F0F4 40008232 */   andi      $v0, $s4, 0x40
  .L8004F0F8:
    /* 3F8F8 8004F0F8 B149010C */  jal        Menu_PlayErrorSound
    /* 3F8FC 8004F0FC 00000000 */   nop
    /* 3F900 8004F100 40008232 */  andi       $v0, $s4, 0x40
  .L8004F104:
    /* 3F904 8004F104 43004010 */  beqz       $v0, .L8004F214
    /* 3F908 8004F108 01000224 */   addiu     $v0, $zero, 0x1
    /* 3F90C 8004F10C C78B010C */  jal        MenuWidget_DestroyNode
    /* 3F910 8004F110 21206002 */   addu      $a0, $s3, $zero
    /* 3F914 8004F114 01000424 */  addiu      $a0, $zero, 0x1
    /* 3F918 8004F118 8D8A010C */  jal        MenuWidget_FindByModeAndSelectedBase
    /* 3F91C 8004F11C 05000524 */   addiu     $a1, $zero, 0x5
    /* 3F920 8004F120 0F004010 */  beqz       $v0, .L8004F160
    /* 3F924 8004F124 00000000 */   nop
    /* 3F928 8004F128 CF8B010C */  jal        MenuWidget_NavScrollTo
    /* 3F92C 8004F12C 05000424 */   addiu     $a0, $zero, 0x5
    /* 3F930 8004F130 CF8B010C */  jal        MenuWidget_NavScrollTo
    /* 3F934 8004F134 06000424 */   addiu     $a0, $zero, 0x6
    /* 3F938 8004F138 CF8B010C */  jal        MenuWidget_NavScrollTo
    /* 3F93C 8004F13C 07000424 */   addiu     $a0, $zero, 0x7
    /* 3F940 8004F140 CF8B010C */  jal        MenuWidget_NavScrollTo
    /* 3F944 8004F144 35000424 */   addiu     $a0, $zero, 0x35
    /* 3F948 8004F148 3E030424 */  addiu      $a0, $zero, 0x33E
    /* 3F94C 8004F14C FFFF0524 */  addiu      $a1, $zero, -0x1
    /* 3F950 8004F150 4622010C */  jal        Menu_StepInventoryRoot
    /* 3F954 8004F154 FFFF0624 */   addiu     $a2, $zero, -0x1
    /* 3F958 8004F158 823C0108 */  j          .L8004F208
    /* 3F95C 8004F15C 00000000 */   nop
  .L8004F160:
    /* 3F960 8004F160 CF8B010C */  jal        MenuWidget_NavScrollTo
    /* 3F964 8004F164 0F000424 */   addiu     $a0, $zero, 0xF
    /* 3F968 8004F168 CF8B010C */  jal        MenuWidget_NavScrollTo
    /* 3F96C 8004F16C 0B000424 */   addiu     $a0, $zero, 0xB
    /* 3F970 8004F170 CF8B010C */  jal        MenuWidget_NavScrollTo
    /* 3F974 8004F174 0D000424 */   addiu     $a0, $zero, 0xD
    /* 3F978 8004F178 CF8B010C */  jal        MenuWidget_NavScrollTo
    /* 3F97C 8004F17C 18000424 */   addiu     $a0, $zero, 0x18
    /* 3F980 8004F180 CF8B010C */  jal        MenuWidget_NavScrollTo
    /* 3F984 8004F184 30000424 */   addiu     $a0, $zero, 0x30
    /* 3F988 8004F188 9C01828F */  lw         $v0, %gp_rel(g_MenuEquipMode)($gp)
    /* 3F98C 8004F18C 00000000 */  nop
    /* 3F990 8004F190 07004010 */  beqz       $v0, .L8004F1B0
    /* 3F994 8004F194 02000424 */   addiu     $a0, $zero, 0x2
    /* 3F998 8004F198 8D8A010C */  jal        MenuWidget_FindByModeAndSelectedBase
    /* 3F99C 8004F19C 32000524 */   addiu     $a1, $zero, 0x32
    /* 3F9A0 8004F1A0 2E8B010C */  jal        MenuWidget_SetCurrentNode
    /* 3F9A4 8004F1A4 21204000 */   addu      $a0, $v0, $zero
    /* 3F9A8 8004F1A8 7A3C0108 */  j          .L8004F1E8
    /* 3F9AC 8004F1AC 00000000 */   nop
  .L8004F1B0:
    /* 3F9B0 8004F1B0 318B010C */  jal        MenuWidget_GetCurrentNode
    /* 3F9B4 8004F1B4 00000000 */   nop
    /* 3F9B8 8004F1B8 06004010 */  beqz       $v0, .L8004F1D4
    /* 3F9BC 8004F1BC 00000000 */   nop
    /* 3F9C0 8004F1C0 318B010C */  jal        MenuWidget_GetCurrentNode
    /* 3F9C4 8004F1C4 00000000 */   nop
    /* 3F9C8 8004F1C8 0400448C */  lw         $a0, 0x4($v0)
    /* 3F9CC 8004F1CC 668C010C */  jal        MenuWidget_ClearCursorY
    /* 3F9D0 8004F1D0 00000000 */   nop
  .L8004F1D4:
    /* 3F9D4 8004F1D4 01000424 */  addiu      $a0, $zero, 0x1
    /* 3F9D8 8004F1D8 8D8A010C */  jal        MenuWidget_FindByModeAndSelectedBase
    /* 3F9DC 8004F1DC 1B000524 */   addiu     $a1, $zero, 0x1B
    /* 3F9E0 8004F1E0 668C010C */  jal        MenuWidget_ClearCursorY
    /* 3F9E4 8004F1E4 21204000 */   addu      $a0, $v0, $zero
  .L8004F1E8:
    /* 3F9E8 8004F1E8 C40180AF */  sw         $zero, %gp_rel(D_8009CF34)($gp)
    /* 3F9EC 8004F1EC CF8B010C */  jal        MenuWidget_NavScrollTo
    /* 3F9F0 8004F1F0 2F000424 */   addiu     $a0, $zero, 0x2F
    /* 3F9F4 8004F1F4 9C01848F */  lw         $a0, %gp_rel(g_MenuEquipMode)($gp)
    /* 3F9F8 8004F1F8 AC0180AF */  sw         $zero, %gp_rel(D_8009CF1C)($gp)
    /* 3F9FC 8004F1FC C00180AF */  sw         $zero, %gp_rel(D_8009CF30)($gp)
    /* 3FA00 8004F200 C139010C */  jal        Menu_OpenEquipScreen
    /* 3FA04 8004F204 FFFF8424 */   addiu     $a0, $a0, -0x1
  .L8004F208:
    /* 3FA08 8004F208 8D49010C */  jal        Menu_PlayCancelSound
    /* 3FA0C 8004F20C 00000000 */   nop
    /* 3FA10 8004F210 01000224 */  addiu      $v0, $zero, 0x1
  .L8004F214:
    /* 3FA14 8004F214 2800BF8F */  lw         $ra, 0x28($sp)
    /* 3FA18 8004F218 2400B58F */  lw         $s5, 0x24($sp)
    /* 3FA1C 8004F21C 2000B48F */  lw         $s4, 0x20($sp)
    /* 3FA20 8004F220 1C00B38F */  lw         $s3, 0x1C($sp)
    /* 3FA24 8004F224 1800B28F */  lw         $s2, 0x18($sp)
    /* 3FA28 8004F228 1400B18F */  lw         $s1, 0x14($sp)
    /* 3FA2C 8004F22C 1000B08F */  lw         $s0, 0x10($sp)
    /* 3FA30 8004F230 3000BD27 */  addiu      $sp, $sp, 0x30
    /* 3FA34 8004F234 0800E003 */  jr         $ra
    /* 3FA38 8004F238 00000000 */   nop
endlabel Menu_InventoryPageNavHandler
