.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.4 */

nonmatching Save_InitMetadataState, 0x24C

glabel Save_InitMetadataState
    /* 4DEF4 8005D6F4 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 4DEF8 8005D6F8 1000B0AF */  sw         $s0, 0x10($sp)
    /* 4DEFC 8005D6FC 0C80103C */  lui        $s0, %hi(g_SaveRuntimeState)
    /* 4DF00 8005D700 E00D1026 */  addiu      $s0, $s0, %lo(g_SaveRuntimeState)
    /* 4DF04 8005D704 21200002 */  addu       $a0, $s0, $zero
    /* 4DF08 8005D708 1400BFAF */  sw         $ra, 0x14($sp)
    /* 4DF0C 8005D70C 89C6010C */  jal        bzero
    /* 4DF10 8005D710 E4120524 */   addiu     $a1, $zero, 0x12E4
    /* 4DF14 8005D714 10000226 */  addiu      $v0, $s0, 0x10
    /* 4DF18 8005D718 21204000 */  addu       $a0, $v0, $zero
    /* 4DF1C 8005D71C 01000224 */  addiu      $v0, $zero, 0x1
    /* 4DF20 8005D720 A80482AF */  sw         $v0, %gp_rel(g_SaveMetadataWindowIndex)($gp)
    /* 4DF24 8005D724 08000224 */  addiu      $v0, $zero, 0x8
    /* 4DF28 8005D728 18001026 */  addiu      $s0, $s0, 0x18
    /* 4DF2C 8005D72C 2B809000 */  sltu       $s0, $a0, $s0
    /* 4DF30 8005D730 580380AF */  sw         $zero, %gp_rel(g_SaveMetadataSourceRecord)($gp)
    /* 4DF34 8005D734 500384AF */  sw         $a0, %gp_rel(g_SaveMetadataCursor)($gp)
    /* 4DF38 8005D738 540382AF */  sw         $v0, %gp_rel(g_SaveMetadataWindowLength)($gp)
    /* 4DF3C 8005D73C 0A000012 */  beqz       $s0, .L8005D768
    /* 4DF40 8005D740 00000000 */   nop
    /* 4DF44 8005D744 FF000524 */  addiu      $a1, $zero, 0xFF
  .L8005D748:
    /* 4DF48 8005D748 000085A0 */  sb         $a1, 0x0($a0)
    /* 4DF4C 8005D74C 5003828F */  lw         $v0, %gp_rel(g_SaveMetadataCursor)($gp)
    /* 4DF50 8005D750 5403838F */  lw         $v1, %gp_rel(g_SaveMetadataWindowLength)($gp)
    /* 4DF54 8005D754 01008424 */  addiu      $a0, $a0, 0x1
    /* 4DF58 8005D758 21104300 */  addu       $v0, $v0, $v1
    /* 4DF5C 8005D75C 2B108200 */  sltu       $v0, $a0, $v0
    /* 4DF60 8005D760 F9FF4014 */  bnez       $v0, .L8005D748
    /* 4DF64 8005D764 00000000 */   nop
  .L8005D768:
    /* 4DF68 8005D768 5803828F */  lw         $v0, %gp_rel(g_SaveMetadataSourceRecord)($gp)
    /* 4DF6C 8005D76C 5003908F */  lw         $s0, %gp_rel(g_SaveMetadataCursor)($gp)
    /* 4DF70 8005D770 06004010 */  beqz       $v0, .L8005D78C
    /* 4DF74 8005D774 00000000 */   nop
    /* 4DF78 8005D778 04004490 */  lbu        $a0, 0x4($v0)
    /* 4DF7C 8005D77C 2777010C */  jal        Str_LookupTable8
    /* 4DF80 8005D780 FFFF8424 */   addiu     $a0, $a0, -0x1
    /* 4DF84 8005D784 E6750108 */  j          .L8005D798
    /* 4DF88 8005D788 21280002 */   addu      $a1, $s0, $zero
  .L8005D78C:
    /* 4DF8C 8005D78C 1377010C */  jal        Str_LookupTable4
    /* 4DF90 8005D790 1E000424 */   addiu     $a0, $zero, 0x1E
    /* 4DF94 8005D794 21280002 */  addu       $a1, $s0, $zero
  .L8005D798:
    /* 4DF98 8005D798 21204000 */  addu       $a0, $v0, $zero
    /* 4DF9C 8005D79C 00008390 */  lbu        $v1, 0x0($a0)
    /* 4DFA0 8005D7A0 01008424 */  addiu      $a0, $a0, 0x1
    /* 4DFA4 8005D7A4 FF000224 */  addiu      $v0, $zero, 0xFF
    /* 4DFA8 8005D7A8 0000A3A0 */  sb         $v1, 0x0($a1)
    /* 4DFAC 8005D7AC FF006330 */  andi       $v1, $v1, 0xFF
    /* 4DFB0 8005D7B0 07006210 */  beq        $v1, $v0, .L8005D7D0
    /* 4DFB4 8005D7B4 0100A524 */   addiu     $a1, $a1, 0x1
    /* 4DFB8 8005D7B8 FF000324 */  addiu      $v1, $zero, 0xFF
  .L8005D7BC:
    /* 4DFBC 8005D7BC 00008290 */  lbu        $v0, 0x0($a0)
    /* 4DFC0 8005D7C0 01008424 */  addiu      $a0, $a0, 0x1
    /* 4DFC4 8005D7C4 0000A2A0 */  sb         $v0, 0x0($a1)
    /* 4DFC8 8005D7C8 FCFF4314 */  bne        $v0, $v1, .L8005D7BC
    /* 4DFCC 8005D7CC 0100A524 */   addiu     $a1, $a1, 0x1
  .L8005D7D0:
    /* 4DFD0 8005D7D0 0C80023C */  lui        $v0, %hi(D_800C0DF0)
    /* 4DFD4 8005D7D4 F00D4224 */  addiu      $v0, $v0, %lo(D_800C0DF0)
    /* 4DFD8 8005D7D8 21204000 */  addu       $a0, $v0, $zero
    /* 4DFDC 8005D7DC 01000224 */  addiu      $v0, $zero, 0x1
    /* 4DFE0 8005D7E0 A80482AF */  sw         $v0, %gp_rel(g_SaveMetadataWindowIndex)($gp)
    /* 4DFE4 8005D7E4 08000224 */  addiu      $v0, $zero, 0x8
    /* 4DFE8 8005D7E8 540382AF */  sw         $v0, %gp_rel(g_SaveMetadataWindowLength)($gp)
    /* 4DFEC 8005D7EC 08008224 */  addiu      $v0, $a0, 0x8
    /* 4DFF0 8005D7F0 2B108200 */  sltu       $v0, $a0, $v0
    /* 4DFF4 8005D7F4 580380AF */  sw         $zero, %gp_rel(g_SaveMetadataSourceRecord)($gp)
    /* 4DFF8 8005D7F8 500384AF */  sw         $a0, %gp_rel(g_SaveMetadataCursor)($gp)
    /* 4DFFC 8005D7FC 0A004010 */  beqz       $v0, .L8005D828
    /* 4E000 8005D800 00000000 */   nop
    /* 4E004 8005D804 FF000524 */  addiu      $a1, $zero, 0xFF
  .L8005D808:
    /* 4E008 8005D808 000085A0 */  sb         $a1, 0x0($a0)
    /* 4E00C 8005D80C 5003828F */  lw         $v0, %gp_rel(g_SaveMetadataCursor)($gp)
    /* 4E010 8005D810 5403838F */  lw         $v1, %gp_rel(g_SaveMetadataWindowLength)($gp)
    /* 4E014 8005D814 01008424 */  addiu      $a0, $a0, 0x1
    /* 4E018 8005D818 21104300 */  addu       $v0, $v0, $v1
    /* 4E01C 8005D81C 2B108200 */  sltu       $v0, $a0, $v0
    /* 4E020 8005D820 F9FF4014 */  bnez       $v0, .L8005D808
    /* 4E024 8005D824 00000000 */   nop
  .L8005D828:
    /* 4E028 8005D828 5803828F */  lw         $v0, %gp_rel(g_SaveMetadataSourceRecord)($gp)
    /* 4E02C 8005D82C 5003908F */  lw         $s0, %gp_rel(g_SaveMetadataCursor)($gp)
    /* 4E030 8005D830 06004010 */  beqz       $v0, .L8005D84C
    /* 4E034 8005D834 00000000 */   nop
    /* 4E038 8005D838 04004490 */  lbu        $a0, 0x4($v0)
    /* 4E03C 8005D83C 2777010C */  jal        Str_LookupTable8
    /* 4E040 8005D840 FFFF8424 */   addiu     $a0, $a0, -0x1
    /* 4E044 8005D844 16760108 */  j          .L8005D858
    /* 4E048 8005D848 21280002 */   addu      $a1, $s0, $zero
  .L8005D84C:
    /* 4E04C 8005D84C 1377010C */  jal        Str_LookupTable4
    /* 4E050 8005D850 1E000424 */   addiu     $a0, $zero, 0x1E
    /* 4E054 8005D854 21280002 */  addu       $a1, $s0, $zero
  .L8005D858:
    /* 4E058 8005D858 21204000 */  addu       $a0, $v0, $zero
    /* 4E05C 8005D85C 00008390 */  lbu        $v1, 0x0($a0)
    /* 4E060 8005D860 01008424 */  addiu      $a0, $a0, 0x1
    /* 4E064 8005D864 FF000224 */  addiu      $v0, $zero, 0xFF
    /* 4E068 8005D868 0000A3A0 */  sb         $v1, 0x0($a1)
    /* 4E06C 8005D86C FF006330 */  andi       $v1, $v1, 0xFF
    /* 4E070 8005D870 07006210 */  beq        $v1, $v0, .L8005D890
    /* 4E074 8005D874 0100A524 */   addiu     $a1, $a1, 0x1
    /* 4E078 8005D878 FF000324 */  addiu      $v1, $zero, 0xFF
  .L8005D87C:
    /* 4E07C 8005D87C 00008290 */  lbu        $v0, 0x0($a0)
    /* 4E080 8005D880 01008424 */  addiu      $a0, $a0, 0x1
    /* 4E084 8005D884 0000A2A0 */  sb         $v0, 0x0($a1)
    /* 4E088 8005D888 FCFF4314 */  bne        $v0, $v1, .L8005D87C
    /* 4E08C 8005D88C 0100A524 */   addiu     $a1, $a1, 0x1
  .L8005D890:
    /* 4E090 8005D890 1377010C */  jal        Str_LookupTable4
    /* 4E094 8005D894 1E000424 */   addiu     $a0, $zero, 0x1E
    /* 4E098 8005D898 6549010C */  jal        Menu_CopyPromptCodes
    /* 4E09C 8005D89C 21204000 */   addu      $a0, $v0, $zero
    /* 4E0A0 8005D8A0 2973010C */  jal        Inv_InitNewGameInventory
    /* 4E0A4 8005D8A4 00000000 */   nop
    /* 4E0A8 8005D8A8 4000033C */  lui        $v1, (0x404040 >> 16)
    /* 4E0AC 8005D8AC 40406334 */  ori        $v1, $v1, (0x404040 & 0xFFFF)
    /* 4E0B0 8005D8B0 4000043C */  lui        $a0, (0x404040 >> 16)
    /* 4E0B4 8005D8B4 03020224 */  addiu      $v0, $zero, 0x203
    /* 4E0B8 8005D8B8 0C80013C */  lui        $at, %hi(D_800C1F80)
    /* 4E0BC 8005D8BC 801F22A4 */  sh         $v0, %lo(D_800C1F80)($at)
    /* 4E0C0 8005D8C0 0C80013C */  lui        $at, %hi(g_SavedDrawBlendColor)
    /* 4E0C4 8005D8C4 440E23AC */  sw         $v1, %lo(g_SavedDrawBlendColor)($at)
    /* 4E0C8 8005D8C8 2B85010C */  jal        Draw_BlendColor
    /* 4E0CC 8005D8CC 40408434 */   ori       $a0, $a0, (0x404040 & 0xFFFF)
    /* 4E0D0 8005D8D0 0A80013C */  lui        $at, %hi(D_800A76A4)
    /* 4E0D4 8005D8D4 A47620AC */  sw         $zero, %lo(D_800A76A4)($at)
    /* 4E0D8 8005D8D8 0A80013C */  lui        $at, %hi(D_800A76B0)
    /* 4E0DC 8005D8DC B07620AC */  sw         $zero, %lo(D_800A76B0)($at)
    /* 4E0E0 8005D8E0 0A80013C */  lui        $at, %hi(D_800A76BC)
    /* 4E0E4 8005D8E4 BC7620AC */  sw         $zero, %lo(D_800A76BC)($at)
    /* 4E0E8 8005D8E8 0A80013C */  lui        $at, %hi(D_800A76C8)
    /* 4E0EC 8005D8EC C87620AC */  sw         $zero, %lo(D_800A76C8)($at)
    /* 4E0F0 8005D8F0 217A010C */  jal        Draw_GetBaseY
    /* 4E0F4 8005D8F4 00000000 */   nop
    /* 4E0F8 8005D8F8 21200000 */  addu       $a0, $zero, $zero
    /* 4E0FC 8005D8FC 08000524 */  addiu      $a1, $zero, 0x8
    /* 4E100 8005D900 147A010C */  jal        Draw_SetBaseOffsetPosition
    /* 4E104 8005D904 2328A200 */   subu      $a1, $a1, $v0
    /* 4E108 8005D908 7492010C */  jal        MenuWidget_SetColumnLayoutMode
    /* 4E10C 8005D90C 21200000 */   addu      $a0, $zero, $zero
    /* 4E110 8005D910 E449010C */  jal        Menu_SetActionSubmenuSelection
    /* 4E114 8005D914 01000424 */   addiu     $a0, $zero, 0x1
    /* 4E118 8005D918 FF000224 */  addiu      $v0, $zero, 0xFF
    /* 4E11C 8005D91C 0C80013C */  lui        $at, %hi(D_800C20A4)
    /* 4E120 8005D920 A42022A0 */  sb         $v0, %lo(D_800C20A4)($at)
    /* 4E124 8005D924 0C80013C */  lui        $at, %hi(D_800C20B4)
    /* 4E128 8005D928 B42022A0 */  sb         $v0, %lo(D_800C20B4)($at)
    /* 4E12C 8005D92C 1400BF8F */  lw         $ra, 0x14($sp)
    /* 4E130 8005D930 1000B08F */  lw         $s0, 0x10($sp)
    /* 4E134 8005D934 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 4E138 8005D938 0800E003 */  jr         $ra
    /* 4E13C 8005D93C 00000000 */   nop
endlabel Save_InitMetadataState
