#define ROOMLIB_DRAW_GROUND_SPRITE_NAME func_8018FEF0
#define ROOMLIB_DRAW_GROUND_SPRITE_DEPTH D_8019218A
#define ROOMLIB_DRAW_GROUND_SPRITE_FLOOR D_800942EC
#include "../room_lib/RoomLib_DrawGroundSprite.inc"
