#include "common.h"

#define ROOMEFFECT_ORBIT_FLARE_FUNC func_801902F0
#define ROOMEFFECT_ORBIT_FLARE_ROTATION D_8018EFFC
#define ROOMEFFECT_ORBIT_FLARE_SPIN D_8018F004
#define ROOMEFFECT_ORBIT_FLARE_CALLBACK func_801900E8
#include "../room_lib/RoomEffect_OrbitFlareController.inc"
