#define ROOMLIB_UPDATE_DAMPED_PARTICLE_NAME func_8019253C
#define ROOMLIB_DAMPED_PARTICLE_SEED D_8018F1CC
#define ROOMLIB_DAMPED_PARTICLE_TABLE D_80194098
#include "../room_lib/RoomLib_UpdateDampedParticle.inc"
