/* MASPSX_FLAGS: --expand-div */
#define ROOMEFFECT_LINE_BURST_FUNC func_80190028
#define ROOMEFFECT_LINE_BURST_CALLBACK func_8018FC8C
#define ROOMEFFECT_LINE_BURST_TEMPLATE D_8018F008
#define ROOMEFFECT_LINE_BURST_ROTATION D_8018F010
#include "../room_lib/RoomEffect_LineBurstController.inc"
