.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */


glabel puts
    /* 6445C 80073C5C B0000A24 */  addiu      $t2, $zero, 0xB0
    /* 64460 80073C60 08004001 */  jr         $t2
    /* 64464 80073C64 3F000924 */   addiu     $t1, $zero, 0x3F
endlabel puts
    /* 64468 80073C68 00000000 */  nop
    /* 6446C 80073C6C 00000000 */  nop
    /* 64470 80073C70 00000000 */  nop
