/* MASPSX_FLAGS: --expand-div */
#define D_800BCFA4 g_GeomVramPacketDst
#define ROOMEFFECT_BEAM_SPARK_FUNC func_80190F94
#define ROOMEFFECT_BEAM_SPARK_CALLBACK func_80190BF8
#define ROOMEFFECT_BEAM_SPARK_ROTATION D_8018F048
#define ROOMEFFECT_BEAM_SPARK_MODEL_ROTATION D_8018EFFC
#define ROOMEFFECT_BEAM_SPARK_ASSET D_80192C30
#include "../room_lib/RoomEffect_BeamSparkController.inc"
