/* MASPSX_FLAGS: --expand-div */
#define ROOMEFFECT_LINE_BURST_FUNC func_80190444
#define ROOMEFFECT_LINE_BURST_CALLBACK func_801900A8
#define ROOMEFFECT_LINE_BURST_TEMPLATE D_8018F000
#define ROOMEFFECT_LINE_BURST_ROTATION D_8018F008
#include "../room_lib/RoomEffect_LineBurstController.inc"
