/* CC1_FLAGS: -g3 */

/* Function body emitted as asm() (PSYQ GCC 2.7.2 register
 * allocation / scheduling diverges from the ROM pervasively).
 * Wrapped via maspsx's INCLUDE_ASM hack so the body is passed
 * through verbatim; bare global loads gp-rel via the .extern size
 * hints + `as -G8`. See tools/maspsx/PE1_IMPROVEMENTS.md. */
void __maspsx_include_asm_hack_MemCard_UpdateSaveState(void);
void __maspsx_include_asm_hack_MemCard_UpdateSaveState(void) {
	__asm__(
		".extern	jtbl_80010F6C # maspsx-keep\n"
		"	.set	noreorder # maspsx-keep\n"
		"	.set	nomacro # maspsx-keep\n"
		"	.globl	MemCard_UpdateSaveState # maspsx-keep\n"
		"MemCard_UpdateSaveState: # maspsx-keep\n"
		"	addiu	$sp,$sp,-0x78 # maspsx-keep\n"
		"	sw	$s2,0x68($sp) # maspsx-keep\n"
		"	addu	$s2,$a0,$zero # maspsx-keep\n"
		"	sll	$v0,$s2,5 # maspsx-keep\n"
		"	addu	$v0,$v0,$s2 # maspsx-keep\n"
		"	sll	$v0,$v0,2 # maspsx-keep\n"
		"	subu	$v0,$v0,$s2 # maspsx-keep\n"
		"	sll	$v0,$v0,3 # maspsx-keep\n"
		"	lui	$v1,%hi(g_MemCardPortStates) # maspsx-keep\n"
		"	addiu	$v1,$v1,%lo(g_MemCardPortStates) # maspsx-keep\n"
		"	sw	$s0,0x60($sp) # maspsx-keep\n"
		"	addu	$s0,$v0,$v1 # maspsx-keep\n"
		"	sw	$ra,0x70($sp) # maspsx-keep\n"
		"	sw	$s3,0x6C($sp) # maspsx-keep\n"
		"	sw	$s1,0x64($sp) # maspsx-keep\n"
		"	lbu	$v1,0x1($s0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	sltiu	$v0,$v1,0x10 # maspsx-keep\n"
		"	beqz	$v0,.L80042000 # maspsx-keep\n"
		"	sll	$v0,$v1,2 # maspsx-keep\n"
		"	lui	$at,%hi(jtbl_80010F6C) # maspsx-keep\n"
		"	addu	$at,$at,$v0 # maspsx-keep\n"
		"	lw	$v0,%lo(jtbl_80010F6C)($at) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	jr	$v0 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L80041170: # maspsx-keep\n"
		"	lbu	$a0,0x0($s0) # maspsx-keep\n"
		"	addiu	$v0,$zero,0x1 # maspsx-keep\n"
		"	bne	$a0,$v0,.L80041FF8 # maspsx-keep\n"
		"	sll	$v0,$s2,5 # maspsx-keep\n"
		"	addu	$v0,$v0,$s2 # maspsx-keep\n"
		"	sll	$v0,$v0,2 # maspsx-keep\n"
		"	subu	$v0,$v0,$s2 # maspsx-keep\n"
		"	sll	$v0,$v0,3 # maspsx-keep\n"
		"	lui	$at,%hi(D_800A0EDC) # maspsx-keep\n"
		"	addu	$at,$at,$v0 # maspsx-keep\n"
		"	lbu	$v1,%lo(D_800A0EDC)($at) # maspsx-keep\n"
		"	addiu	$v0,$zero,0x4 # maspsx-keep\n"
		"	bne	$v1,$v0,.L80042000 # maspsx-keep\n"
		"	sltiu	$v0,$s2,0x1 # maspsx-keep\n"
		"	negu	$v0,$v0 # maspsx-keep\n"
		"	andi	$v0,$v0,0x418 # maspsx-keep\n"
		"	lui	$at,%hi(D_800A0EDC) # maspsx-keep\n"
		"	addu	$at,$at,$v0 # maspsx-keep\n"
		"	lbu	$v0,%lo(D_800A0EDC)($at) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	beqz	$v0,.L800411D0 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	bne	$v0,$v1,.L80042000 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L800411D0: # maspsx-keep\n"
		"	lui	$at,%hi(g_McOpPending) # maspsx-keep\n"
		"	sw	$a0,%lo(g_McOpPending)($at) # maspsx-keep\n"
		"	lbu	$v0,0xB($s0) # maspsx-keep\n"
		"	j	.L80042000 # maspsx-keep\n"
		"	sb	$v0,0x1($s0) # maspsx-keep\n"
		".L800411E4: # maspsx-keep\n"
		"	lbu	$v1,0x0($s0) # maspsx-keep\n"
		"	addiu	$v0,$zero,0x5 # maspsx-keep\n"
		"	bne	$v1,$v0,.L80041260 # maspsx-keep\n"
		"	addiu	$v0,$zero,-0x1 # maspsx-keep\n"
		"	sll	$v0,$s2,5 # maspsx-keep\n"
		"	addu	$v0,$v0,$s2 # maspsx-keep\n"
		"	sll	$v0,$v0,2 # maspsx-keep\n"
		"	subu	$v0,$v0,$s2 # maspsx-keep\n"
		"	sll	$v0,$v0,3 # maspsx-keep\n"
		"	lui	$at,%hi(D_800A0EDC) # maspsx-keep\n"
		"	addu	$at,$at,$v0 # maspsx-keep\n"
		"	lbu	$v1,%lo(D_800A0EDC)($at) # maspsx-keep\n"
		"	addiu	$v0,$zero,0x4 # maspsx-keep\n"
		"	bne	$v1,$v0,.L80042000 # maspsx-keep\n"
		"	sltiu	$v0,$s2,0x1 # maspsx-keep\n"
		"	negu	$v0,$v0 # maspsx-keep\n"
		"	andi	$v0,$v0,0x418 # maspsx-keep\n"
		"	lui	$at,%hi(D_800A0EDC) # maspsx-keep\n"
		"	addu	$at,$at,$v0 # maspsx-keep\n"
		"	lbu	$v0,%lo(D_800A0EDC)($at) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	beqz	$v0,.L80041248 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	bne	$v0,$v1,.L80042000 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L80041248: # maspsx-keep\n"
		"	addiu	$v0,$zero,0x1 # maspsx-keep\n"
		"	lui	$at,%hi(g_McOpPending) # maspsx-keep\n"
		"	sw	$v0,%lo(g_McOpPending)($at) # maspsx-keep\n"
		"	addiu	$v0,$zero,0xE # maspsx-keep\n"
		"	j	.L80042000 # maspsx-keep\n"
		"	sb	$v0,0x1($s0) # maspsx-keep\n"
		".L80041260: # maspsx-keep\n"
		"	lui	$at,%hi(g_MemCardSavePollTimeout) # maspsx-keep\n"
		"	sw	$v0,%lo(g_MemCardSavePollTimeout)($at) # maspsx-keep\n"
		"	j	.L80042000 # maspsx-keep\n"
		"	sb	$zero,0x1($s0) # maspsx-keep\n"
		".L80041270: # maspsx-keep\n"
		"	addiu	$a0,$sp,0x18 # maspsx-keep\n"
		"	lui	$a1,%hi(D_80010F60) # maspsx-keep\n"
		"	addiu	$a1,$a1,%lo(D_80010F60) # maspsx-keep\n"
		"	jal	Square_Vsprintf # maspsx-keep\n"
		"	addu	$a2,$s2,$zero # maspsx-keep\n"
		"	jal	format # maspsx-keep\n"
		"	addiu	$a0,$sp,0x18 # maspsx-keep\n"
		"	beqz	$v0,.L80041298 # maspsx-keep\n"
		"	addiu	$v1,$zero,-0x1 # maspsx-keep\n"
		"	addiu	$v1,$zero,0xC # maspsx-keep\n"
		".L80041298: # maspsx-keep\n"
		"	lui	$at,%hi(g_MemCardSavePollTimeout) # maspsx-keep\n"
		"	sw	$v1,%lo(g_MemCardSavePollTimeout)($at) # maspsx-keep\n"
		"	lbu	$v0,0x0($s0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	andi	$v0,$v0,0xFB # maspsx-keep\n"
		"	sb	$v0,0x0($s0) # maspsx-keep\n"
		"	lui	$at,%hi(g_McOpPending) # maspsx-keep\n"
		"	sw	$zero,%lo(g_McOpPending)($at) # maspsx-keep\n"
		"	j	.L80042000 # maspsx-keep\n"
		"	sb	$zero,0x1($s0) # maspsx-keep\n"
		".L800412C0: # maspsx-keep\n"
		"	lbu	$v1,0x0($s0) # maspsx-keep\n"
		"	addiu	$v0,$zero,0x1 # maspsx-keep\n"
		"	bne	$v1,$v0,.L80041FF8 # maspsx-keep\n"
		"	addiu	$a2,$zero,0x2 # maspsx-keep\n"
		"	addiu	$a0,$zero,0xE # maspsx-keep\n"
		"	addiu	$a1,$s0,0x3B8 # maspsx-keep\n"
		"	lui	$v1,%hi(D_80092230) # maspsx-keep\n"
		"	lw	$v1,%lo(D_80092230)($v1) # maspsx-keep\n"
		"	addiu	$v0,$s2,0x30 # maspsx-keep\n"
		"	sb	$v0,0x2($v1) # maspsx-keep\n"
		"	sb	$zero,0x2($s0) # maspsx-keep\n"
		"	sb	$zero,0x3($s0) # maspsx-keep\n"
		"	sb	$zero,0x6($s0) # maspsx-keep\n"
		"	sb	$zero,0x4($s0) # maspsx-keep\n"
		"	sb	$zero,0x7($s0) # maspsx-keep\n"
		"	sb	$zero,0xA($s0) # maspsx-keep\n"
		".L80041300: # maspsx-keep\n"
		"	sb	$a2,0x1C($a1) # maspsx-keep\n"
		"	addiu	$a0,$a0,-0x1 # maspsx-keep\n"
		"	bgez	$a0,.L80041300 # maspsx-keep\n"
		"	addiu	$a1,$a1,-0x44 # maspsx-keep\n"
		"	lui	$a0,%hi(D_80092230) # maspsx-keep\n"
		"	lw	$a0,%lo(D_80092230)($a0) # maspsx-keep\n"
		"	addiu	$s1,$sp,0x20 # maspsx-keep\n"
		"	jal	Scene_CreateEntityNode # maspsx-keep\n"
		"	addu	$a1,$s1,$zero # maspsx-keep\n"
		"	beqz	$v0,.L8004140C # maspsx-keep\n"
		"	addu	$a0,$s1,$zero # maspsx-keep\n"
		"	lui	$a1,%hi(g_MemCardFilenameFormatPtr) # maspsx-keep\n"
		"	lw	$a1,%lo(g_MemCardFilenameFormatPtr)($a1) # maspsx-keep\n"
		"	addiu	$a2,$zero,0xC # maspsx-keep\n"
		"	jal	strncmp # maspsx-keep\n"
		"	addiu	$a1,$a1,0x6 # maspsx-keep\n"
		"	bnez	$v0,.L80041384 # maspsx-keep\n"
		"	addiu	$s3,$zero,0x1 # maspsx-keep\n"
		"	lbu	$v0,0x33($sp) # maspsx-keep\n"
		"	addiu	$a0,$zero,0x1 # maspsx-keep\n"
		"	sll	$v1,$v0,4 # maspsx-keep\n"
		"	addu	$v1,$v1,$v0 # maspsx-keep\n"
		"	sll	$v1,$v1,2 # maspsx-keep\n"
		"	addiu	$v1,$v1,-0x1128 # maspsx-keep\n"
		"	addu	$v1,$s0,$v1 # maspsx-keep\n"
		"	sb	$a0,0x0($v1) # maspsx-keep\n"
		"	sb	$zero,0x1($v1) # maspsx-keep\n"
		"	lbu	$v0,0x32($sp) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	xori	$v0,$v0,0x30 # maspsx-keep\n"
		"	sltu	$v0,$zero,$v0 # maspsx-keep\n"
		"	sb	$v0,0x29($v1) # maspsx-keep\n"
		"	sb	$a0,0x4($s0) # maspsx-keep\n"
		".L80041384: # maspsx-keep\n"
		"	lw	$v0,0x38($sp) # maspsx-keep\n"
		"	lbu	$v1,0xA($s0) # maspsx-keep\n"
		"	sra	$v0,$v0,13 # maspsx-keep\n"
		"	addu	$v1,$v1,$v0 # maspsx-keep\n"
		"	sb	$v1,0xA($s0) # maspsx-keep\n"
		"	jal	nextfile # maspsx-keep\n"
		"	addu	$a0,$s1,$zero # maspsx-keep\n"
		"	beqz	$v0,.L80041404 # maspsx-keep\n"
		"	addu	$a0,$s1,$zero # maspsx-keep\n"
		"	lui	$a1,%hi(g_MemCardFilenameFormatPtr) # maspsx-keep\n"
		"	lw	$a1,%lo(g_MemCardFilenameFormatPtr)($a1) # maspsx-keep\n"
		"	addiu	$a2,$zero,0xC # maspsx-keep\n"
		"	jal	strncmp # maspsx-keep\n"
		"	addiu	$a1,$a1,0x6 # maspsx-keep\n"
		"	bnez	$v0,.L80041384 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lbu	$v0,0x33($sp) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	sll	$v1,$v0,4 # maspsx-keep\n"
		"	addu	$v1,$v1,$v0 # maspsx-keep\n"
		"	sll	$v1,$v1,2 # maspsx-keep\n"
		"	addiu	$v1,$v1,-0x1128 # maspsx-keep\n"
		"	addu	$v1,$s0,$v1 # maspsx-keep\n"
		"	sb	$s3,0x0($v1) # maspsx-keep\n"
		"	sb	$zero,0x1($v1) # maspsx-keep\n"
		"	lbu	$v0,0x32($sp) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	xori	$v0,$v0,0x30 # maspsx-keep\n"
		"	sltu	$v0,$zero,$v0 # maspsx-keep\n"
		"	sb	$v0,0x29($v1) # maspsx-keep\n"
		"	j	.L80041384 # maspsx-keep\n"
		"	sb	$s3,0x4($s0) # maspsx-keep\n"
		".L80041404: # maspsx-keep\n"
		"	j	.L8004141C # maspsx-keep\n"
		"	sh	$zero,0x16($s0) # maspsx-keep\n"
		".L8004140C: # maspsx-keep\n"
		"	lhu	$v0,0x16($s0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	addiu	$v0,$v0,-0x1 # maspsx-keep\n"
		"	sh	$v0,0x16($s0) # maspsx-keep\n"
		".L8004141C: # maspsx-keep\n"
		"	lh	$v0,0x16($s0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	bgtz	$v0,.L80042000 # maspsx-keep\n"
		"	addu	$a0,$zero,$zero # maspsx-keep\n"
		"	lbu	$a1,0xA($s0) # maspsx-keep\n"
		"	addiu	$a3,$zero,0x2 # maspsx-keep\n"
		"	addiu	$a2,$zero,0x1 # maspsx-keep\n"
		"	addu	$v1,$s0,$zero # maspsx-keep\n"
		".L8004143C: # maspsx-keep\n"
		"	lbu	$v0,0x1C($v1) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	bne	$v0,$a3,.L80041454 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	j	.L80041458 # maspsx-keep\n"
		"	sb	$a2,0x1D($v1) # maspsx-keep\n"
		".L80041454: # maspsx-keep\n"
		"	addiu	$a1,$a1,-0x1 # maspsx-keep\n"
		".L80041458: # maspsx-keep\n"
		"	addiu	$a0,$a0,0x1 # maspsx-keep\n"
		"	slti	$v0,$a0,0xF # maspsx-keep\n"
		"	bnez	$v0,.L8004143C # maspsx-keep\n"
		"	addiu	$v1,$v1,0x44 # maspsx-keep\n"
		"	addiu	$a0,$zero,0xE # maspsx-keep\n"
		"	addiu	$a3,$zero,0x2 # maspsx-keep\n"
		"	addiu	$a2,$zero,0x3 # maspsx-keep\n"
		"	addiu	$v1,$s0,0x3B8 # maspsx-keep\n"
		".L80041478: # maspsx-keep\n"
		"	beqz	$a1,.L800414A4 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lbu	$v0,0x1C($v1) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	bne	$v0,$a3,.L80041498 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	sb	$a2,0x1C($v1) # maspsx-keep\n"
		"	addiu	$a1,$a1,-0x1 # maspsx-keep\n"
		".L80041498: # maspsx-keep\n"
		"	addiu	$a0,$a0,-0x1 # maspsx-keep\n"
		"	bgez	$a0,.L80041478 # maspsx-keep\n"
		"	addiu	$v1,$v1,-0x44 # maspsx-keep\n"
		".L800414A4: # maspsx-keep\n"
		"	addiu	$v1,$zero,0xF # maspsx-keep\n"
		"	sb	$v1,0x2($s0) # maspsx-keep\n"
		"	lui	$v0,%hi(g_MemCardReadContext) # maspsx-keep\n"
		"	lw	$v0,%lo(g_MemCardReadContext)($v0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	bnez	$v0,.L800414D4 # maspsx-keep\n"
		"	addu	$a0,$zero,$zero # maspsx-keep\n"
		"	sb	$v1,0x1($s0) # maspsx-keep\n"
		"	lui	$at,%hi(g_McOpPending) # maspsx-keep\n"
		"	sw	$zero,%lo(g_McOpPending)($at) # maspsx-keep\n"
		"	j	.L80042000 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L800414D4: # maspsx-keep\n"
		"	addiu	$a2,$zero,0x1 # maspsx-keep\n"
		"	sll	$v0,$s2,5 # maspsx-keep\n"
		"	addu	$v0,$v0,$s2 # maspsx-keep\n"
		"	sll	$v0,$v0,2 # maspsx-keep\n"
		"	subu	$v0,$v0,$s2 # maspsx-keep\n"
		"	sll	$v0,$v0,3 # maspsx-keep\n"
		"	lui	$v1,%hi(g_MemCardPortStates) # maspsx-keep\n"
		"	addiu	$v1,$v1,%lo(g_MemCardPortStates) # maspsx-keep\n"
		"	addu	$a1,$v0,$v1 # maspsx-keep\n"
		"	addu	$v1,$a1,$zero # maspsx-keep\n"
		".L800414FC: # maspsx-keep\n"
		"	lbu	$v0,0x1C($v1) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	beq	$v0,$a2,.L80041520 # maspsx-keep\n"
		"	slti	$v0,$a0,0xF # maspsx-keep\n"
		"	addiu	$a0,$a0,0x1 # maspsx-keep\n"
		"	slti	$v0,$a0,0xF # maspsx-keep\n"
		"	bnez	$v0,.L800414FC # maspsx-keep\n"
		"	addiu	$v1,$v1,0x44 # maspsx-keep\n"
		"	slti	$v0,$a0,0xF # maspsx-keep\n"
		".L80041520: # maspsx-keep\n"
		"	bnez	$v0,.L8004154C # maspsx-keep\n"
		"	addu	$s1,$zero,$zero # maspsx-keep\n"
		"	lbu	$v0,0xA($a1) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	sltiu	$v0,$v0,0xF # maspsx-keep\n"
		"	beqz	$v0,.L80041550 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	jal	MemCard_GetDialogMode # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	beqz	$v0,.L80041550 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L8004154C: # maspsx-keep\n"
		"	addiu	$s1,$zero,0x1 # maspsx-keep\n"
		".L80041550: # maspsx-keep\n"
		"	beqz	$s1,.L80041598 # maspsx-keep\n"
		"	addiu	$v0,$zero,0x3 # maspsx-keep\n"
		"	sb	$v0,0x1($s0) # maspsx-keep\n"
		"	addiu	$v0,$zero,0xA # maspsx-keep\n"
		"	jal	MenuWidget_RestoreSavedCurrentNode # maspsx-keep\n"
		"	sh	$v0,0x16($s0) # maspsx-keep\n"
		"	lui	$v1,(0xC9484E2B >> 16) # maspsx-keep\n"
		"	ori	$v1,$v1,0x4E2B # maspsx-keep\n"
		"	lui	$v0,%hi(g_MemCardPortStates) # maspsx-keep\n"
		"	addiu	$v0,$v0,%lo(g_MemCardPortStates) # maspsx-keep\n"
		"	subu	$v0,$s0,$v0 # maspsx-keep\n"
		"	mult	$v0,$v1 # maspsx-keep\n"
		"	lbu	$a1,0x2($s0) # maspsx-keep\n"
		"	mflo	$t0 # maspsx-keep\n"
		"	jal	Menu_CreateSaveSlotListView # maspsx-keep\n"
		"	sra	$a0,$t0,3 # maspsx-keep\n"
		"	j	.L80042000 # maspsx-keep\n"
		"	sb	$v0,0x5($s0) # maspsx-keep\n"
		".L80041598: # maspsx-keep\n"
		"	jal	MenuWidget_RestoreSavedCurrentNode # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	jal	Menu_ShowMemCardErrorDialog # maspsx-keep\n"
		"	addu	$a0,$s2,$zero # maspsx-keep\n"
		"	j	.L800417AC # maspsx-keep\n"
		"	addiu	$v0,$zero,0xC # maspsx-keep\n"
		".L800415B0: # maspsx-keep\n"
		"	lbu	$v1,0x0($s0) # maspsx-keep\n"
		"	addiu	$v0,$zero,0x1 # maspsx-keep\n"
		"	bne	$v1,$v0,.L80041FF8 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lbu	$v0,0x2($s0) # maspsx-keep\n"
		"	lbu	$a0,0x6($s0) # maspsx-keep\n"
		"	sll	$v1,$v0,1 # maspsx-keep\n"
		"	slt	$v0,$a0,$v1 # maspsx-keep\n"
		"	beqz	$v0,.L80041684 # maspsx-keep\n"
		"	addu	$a1,$v1,$zero # maspsx-keep\n"
		"	lbu	$a2,0x5($s0) # maspsx-keep\n"
		"	andi	$v1,$a0,0x1 # maspsx-keep\n"
		".L800415E0: # maspsx-keep\n"
		"	sll	$v1,$v1,1 # maspsx-keep\n"
		"	addiu	$v1,$v1,-0x1 # maspsx-keep\n"
		"	andi	$v0,$a0,0xFF # maspsx-keep\n"
		"	addiu	$v0,$v0,0x1 # maspsx-keep\n"
		"	sra	$v0,$v0,1 # maspsx-keep\n"
		"	mult	$v1,$v0 # maspsx-keep\n"
		"	mflo	$t0 # maspsx-keep\n"
		"	addu	$v1,$a2,$t0 # maspsx-keep\n"
		"	sltiu	$v0,$v1,0xF # maspsx-keep\n"
		"	beqz	$v0,.L80041628 # maspsx-keep\n"
		"	sll	$v0,$v1,4 # maspsx-keep\n"
		"	addu	$v0,$v0,$v1 # maspsx-keep\n"
		"	sll	$v0,$v0,2 # maspsx-keep\n"
		"	addu	$v0,$s0,$v0 # maspsx-keep\n"
		"	lbu	$v0,0x1D($v0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	beqz	$v0,.L80041644 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L80041628: # maspsx-keep\n"
		"	addiu	$v0,$a0,0x1 # maspsx-keep\n"
		"	sb	$v0,0x6($s0) # maspsx-keep\n"
		"	addu	$a0,$v0,$zero # maspsx-keep\n"
		"	andi	$v0,$a0,0xFF # maspsx-keep\n"
		"	slt	$v0,$v0,$a1 # maspsx-keep\n"
		"	bnez	$v0,.L800415E0 # maspsx-keep\n"
		"	andi	$v1,$a0,0x1 # maspsx-keep\n"
		".L80041644: # maspsx-keep\n"
		"	lbu	$v1,0x6($s0) # maspsx-keep\n"
		"	lbu	$v0,0x2($s0) # maspsx-keep\n"
		"	andi	$a0,$v1,0xFF # maspsx-keep\n"
		"	sll	$v0,$v0,1 # maspsx-keep\n"
		"	slt	$v0,$a0,$v0 # maspsx-keep\n"
		"	beqz	$v0,.L80041684 # maspsx-keep\n"
		"	andi	$v1,$v1,0x1 # maspsx-keep\n"
		"	sll	$v1,$v1,1 # maspsx-keep\n"
		"	addiu	$v1,$v1,-0x1 # maspsx-keep\n"
		"	addiu	$v0,$a0,0x1 # maspsx-keep\n"
		"	sra	$v0,$v0,1 # maspsx-keep\n"
		"	mult	$v1,$v0 # maspsx-keep\n"
		"	lbu	$v0,0x5($s0) # maspsx-keep\n"
		"	mflo	$t0 # maspsx-keep\n"
		"	j	.L80041688 # maspsx-keep\n"
		"	addu	$v0,$v0,$t0 # maspsx-keep\n"
		".L80041684: # maspsx-keep\n"
		"	addiu	$v0,$zero,0xFF # maspsx-keep\n"
		".L80041688: # maspsx-keep\n"
		"	sb	$v0,0x3($s0) # maspsx-keep\n"
		"	andi	$v1,$v0,0xFF # maspsx-keep\n"
		"	addiu	$v0,$zero,0xFF # maspsx-keep\n"
		"	beq	$v1,$v0,.L800417A8 # maspsx-keep\n"
		"	sll	$v0,$v1,4 # maspsx-keep\n"
		"	lui	$a0,%hi(g_MemCardFilenameBuf) # maspsx-keep\n"
		"	addiu	$a0,$a0,%lo(g_MemCardFilenameBuf) # maspsx-keep\n"
		"	lui	$a2,%hi(g_MemCardPortStates) # maspsx-keep\n"
		"	addiu	$a2,$a2,%lo(g_MemCardPortStates) # maspsx-keep\n"
		"	sltu	$a2,$a2,$s0 # maspsx-keep\n"
		"	addu	$v0,$v0,$v1 # maspsx-keep\n"
		"	sll	$v0,$v0,2 # maspsx-keep\n"
		"	addu	$v0,$s0,$v0 # maspsx-keep\n"
		"	lui	$a1,%hi(g_MemCardFilenameFormatPtr) # maspsx-keep\n"
		"	lw	$a1,%lo(g_MemCardFilenameFormatPtr)($a1) # maspsx-keep\n"
		"	lbu	$a3,0x45($v0) # maspsx-keep\n"
		"	addiu	$v0,$v1,0x41 # maspsx-keep\n"
		"	sw	$v0,0x10($sp) # maspsx-keep\n"
		"	jal	Square_Vsprintf # maspsx-keep\n"
		"	addiu	$a3,$a3,0x30 # maspsx-keep\n"
		"	lui	$a0,%hi(g_MemCardFilenameBuf) # maspsx-keep\n"
		"	addiu	$a0,$a0,%lo(g_MemCardFilenameBuf) # maspsx-keep\n"
		"	jal	open # maspsx-keep\n"
		"	addiu	$a1,$zero,0x1 # maspsx-keep\n"
		"	bltz	$v0,.L80041754 # maspsx-keep\n"
		"	sw	$v0,0xC($s0) # maspsx-keep\n"
		"	addiu	$v0,$zero,0x8 # maspsx-keep\n"
		"	sb	$v0,0x1($s0) # maspsx-keep\n"
		"	sll	$v0,$s2,7 # maspsx-keep\n"
		"	lui	$v1,%hi(D_800A1720) # maspsx-keep\n"
		"	addiu	$v1,$v1,%lo(D_800A1720) # maspsx-keep\n"
		"	addu	$v0,$v0,$v1 # maspsx-keep\n"
		"	lbu	$v1,0x3($s0) # maspsx-keep\n"
		"	sw	$v0,0x18($s0) # maspsx-keep\n"
		"	addiu	$v0,$zero,0x80 # maspsx-keep\n"
		"	sh	$v0,0x14($s0) # maspsx-keep\n"
		"	addiu	$v0,$zero,0x1E # maspsx-keep\n"
		"	sh	$v0,0x16($s0) # maspsx-keep\n"
		"	sll	$v0,$v1,4 # maspsx-keep\n"
		"	addu	$v0,$v0,$v1 # maspsx-keep\n"
		"	sll	$v0,$v0,2 # maspsx-keep\n"
		"	addu	$v0,$s0,$v0 # maspsx-keep\n"
		"	lbu	$v1,0x1C($v0) # maspsx-keep\n"
		"	addiu	$v0,$zero,0x1 # maspsx-keep\n"
		"	bne	$v1,$v0,.L80042000 # maspsx-keep\n"
		"	addiu	$a1,$zero,0x100 # maspsx-keep\n"
		"	lw	$a0,0xC($s0) # maspsx-keep\n"
		"	jal	lseek # maspsx-keep\n"
		"	addu	$a2,$zero,$zero # maspsx-keep\n"
		"	j	.L80042000 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L80041754: # maspsx-keep\n"
		"	lhu	$v0,0x16($s0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	addiu	$v1,$v0,-0x1 # maspsx-keep\n"
		"	sll	$v0,$v0,16 # maspsx-keep\n"
		"	bgtz	$v0,.L80042000 # maspsx-keep\n"
		"	sh	$v1,0x16($s0) # maspsx-keep\n"
		"	lbu	$v0,0x0($s0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	andi	$v0,$v0,0x1 # maspsx-keep\n"
		"	beqz	$v0,.L80041FF8 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	jal	MemCard_AbortActiveOperation # maspsx-keep\n"
		"	addu	$a0,$s0,$zero # maspsx-keep\n"
		"	lbu	$v1,0x7($s0) # maspsx-keep\n"
		"	addiu	$v0,$zero,0x1 # maspsx-keep\n"
		"	beq	$v1,$v0,.L80041FBC # maspsx-keep\n"
		"	addiu	$v0,$zero,0x2 # maspsx-keep\n"
		".L80041798: # maspsx-keep\n"
		"	bne	$v1,$v0,.L80041FDC # maspsx-keep\n"
		"	addiu	$v0,$zero,0xC # maspsx-keep\n"
		"	j	.L80041FD0 # maspsx-keep\n"
		"	addiu	$a0,$zero,0x3E # maspsx-keep\n"
		".L800417A8: # maspsx-keep\n"
		"	addiu	$v0,$zero,0xC # maspsx-keep\n"
		".L800417AC: # maspsx-keep\n"
		"	sb	$v0,0x1($s0) # maspsx-keep\n"
		"	lui	$at,%hi(g_McOpPending) # maspsx-keep\n"
		"	sw	$zero,%lo(g_McOpPending)($at) # maspsx-keep\n"
		"	j	.L80042000 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L800417C0: # maspsx-keep\n"
		"	lbu	$s1,0x0($s0) # maspsx-keep\n"
		"	addiu	$v0,$zero,0x1 # maspsx-keep\n"
		"	bne	$s1,$v0,.L80041FF8 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lui	$a0,%hi(g_MemCardFilenameBuf) # maspsx-keep\n"
		"	addiu	$a0,$a0,%lo(g_MemCardFilenameBuf) # maspsx-keep\n"
		"	lui	$a2,%hi(g_MemCardPortStates) # maspsx-keep\n"
		"	addiu	$a2,$a2,%lo(g_MemCardPortStates) # maspsx-keep\n"
		"	lbu	$v1,0x3($s0) # maspsx-keep\n"
		"	sltu	$a2,$a2,$s0 # maspsx-keep\n"
		"	sll	$v0,$v1,4 # maspsx-keep\n"
		"	addu	$v0,$v0,$v1 # maspsx-keep\n"
		"	sll	$v0,$v0,2 # maspsx-keep\n"
		"	lui	$v1,%hi(g_SaveTitleStyleFlag) # maspsx-keep\n"
		"	lw	$v1,%lo(g_SaveTitleStyleFlag)($v1) # maspsx-keep\n"
		"	addu	$v0,$s0,$v0 # maspsx-keep\n"
		"	sb	$v1,0x45($v0) # maspsx-keep\n"
		"	lbu	$v1,0x3($s0) # maspsx-keep\n"
		"	lui	$a1,%hi(g_MemCardFilenameFormatPtr) # maspsx-keep\n"
		"	lw	$a1,%lo(g_MemCardFilenameFormatPtr)($a1) # maspsx-keep\n"
		"	sll	$v0,$v1,4 # maspsx-keep\n"
		"	addu	$v0,$v0,$v1 # maspsx-keep\n"
		"	sll	$v0,$v0,2 # maspsx-keep\n"
		"	addu	$v0,$s0,$v0 # maspsx-keep\n"
		"	lbu	$a3,0x45($v0) # maspsx-keep\n"
		"	addiu	$v1,$v1,0x41 # maspsx-keep\n"
		"	sw	$v1,0x10($sp) # maspsx-keep\n"
		"	jal	Square_Vsprintf # maspsx-keep\n"
		"	addiu	$a3,$a3,0x30 # maspsx-keep\n"
		"	lui	$a0,%hi(g_MemCardFilenameBuf) # maspsx-keep\n"
		"	addiu	$a0,$a0,%lo(g_MemCardFilenameBuf) # maspsx-keep\n"
		"	lui	$a1,(0x10200 >> 16) # maspsx-keep\n"
		"	jal	open # maspsx-keep\n"
		"	ori	$a1,$a1,0x200 # maspsx-keep\n"
		"	bltz	$v0,.L80041868 # maspsx-keep\n"
		"	sw	$v0,0xC($s0) # maspsx-keep\n"
		"	jal	close # maspsx-keep\n"
		"	addu	$a0,$v0,$zero # maspsx-keep\n"
		"	addiu	$v0,$zero,-0x1 # maspsx-keep\n"
		"	sw	$v0,0xC($s0) # maspsx-keep\n"
		"	j	.L80041F0C # maspsx-keep\n"
		"	addiu	$v0,$zero,0x6 # maspsx-keep\n"
		".L80041868: # maspsx-keep\n"
		"	lhu	$v0,0x16($s0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	addiu	$v1,$v0,-0x1 # maspsx-keep\n"
		"	sll	$v0,$v0,16 # maspsx-keep\n"
		"	bgtz	$v0,.L80042000 # maspsx-keep\n"
		"	sh	$v1,0x16($s0) # maspsx-keep\n"
		"	lbu	$v0,0x0($s0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	andi	$v0,$v0,0x1 # maspsx-keep\n"
		"	beqz	$v0,.L80041FF8 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	jal	MemCard_AbortActiveOperation # maspsx-keep\n"
		"	addu	$a0,$s0,$zero # maspsx-keep\n"
		"	lbu	$v1,0x7($s0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	beq	$v1,$s1,.L80041FBC # maspsx-keep\n"
		"	addiu	$v0,$zero,0x2 # maspsx-keep\n"
		"	j	.L80041798 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L800418B4: # maspsx-keep\n"
		"	lbu	$s1,0x0($s0) # maspsx-keep\n"
		"	addiu	$v0,$zero,0x1 # maspsx-keep\n"
		"	bne	$s1,$v0,.L80041FF8 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lui	$a0,%hi(g_MemCardFilenameBuf) # maspsx-keep\n"
		"	addiu	$a0,$a0,%lo(g_MemCardFilenameBuf) # maspsx-keep\n"
		"	lui	$a2,%hi(g_MemCardPortStates) # maspsx-keep\n"
		"	addiu	$a2,$a2,%lo(g_MemCardPortStates) # maspsx-keep\n"
		"	sltu	$a2,$a2,$s0 # maspsx-keep\n"
		"	lbu	$v1,0x3($s0) # maspsx-keep\n"
		"	lui	$a1,%hi(g_MemCardFilenameFormatPtr) # maspsx-keep\n"
		"	lw	$a1,%lo(g_MemCardFilenameFormatPtr)($a1) # maspsx-keep\n"
		"	sll	$v0,$v1,4 # maspsx-keep\n"
		"	addu	$v0,$v0,$v1 # maspsx-keep\n"
		"	sll	$v0,$v0,2 # maspsx-keep\n"
		"	addu	$v0,$s0,$v0 # maspsx-keep\n"
		"	lbu	$a3,0x45($v0) # maspsx-keep\n"
		"	addiu	$v1,$v1,0x41 # maspsx-keep\n"
		"	sw	$v1,0x10($sp) # maspsx-keep\n"
		"	jal	Square_Vsprintf # maspsx-keep\n"
		"	addiu	$a3,$a3,0x30 # maspsx-keep\n"
		"	lui	$a0,%hi(g_MemCardFilenameBuf) # maspsx-keep\n"
		"	addiu	$a0,$a0,%lo(g_MemCardFilenameBuf) # maspsx-keep\n"
		"	jal	open # maspsx-keep\n"
		"	addiu	$a1,$zero,0x1 # maspsx-keep\n"
		"	bltz	$v0,.L80041934 # maspsx-keep\n"
		"	sw	$v0,0xC($s0) # maspsx-keep\n"
		"	addiu	$v0,$zero,0x1E # maspsx-keep\n"
		"	sh	$v0,0x16($s0) # maspsx-keep\n"
		"	addiu	$v0,$zero,0x7 # maspsx-keep\n"
		"	j	.L80042000 # maspsx-keep\n"
		"	sb	$v0,0x1($s0) # maspsx-keep\n"
		".L80041934: # maspsx-keep\n"
		"	lhu	$v0,0x16($s0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	addiu	$v1,$v0,-0x1 # maspsx-keep\n"
		"	sll	$v0,$v0,16 # maspsx-keep\n"
		"	bgtz	$v0,.L80042000 # maspsx-keep\n"
		"	sh	$v1,0x16($s0) # maspsx-keep\n"
		"	lbu	$v0,0x0($s0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	andi	$v0,$v0,0x1 # maspsx-keep\n"
		"	beqz	$v0,.L80041FF8 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	jal	MemCard_AbortActiveOperation # maspsx-keep\n"
		"	addu	$a0,$s0,$zero # maspsx-keep\n"
		"	lbu	$v1,0x7($s0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	beq	$v1,$s1,.L80041FBC # maspsx-keep\n"
		"	addiu	$v0,$zero,0x2 # maspsx-keep\n"
		"	j	.L80041798 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L80041980: # maspsx-keep\n"
		"	lbu	$s1,0x0($s0) # maspsx-keep\n"
		"	addiu	$v0,$zero,0x1 # maspsx-keep\n"
		"	bne	$s1,$v0,.L80041FF8 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lui	$a0,%hi(g_MemCardFilenameBuf) # maspsx-keep\n"
		"	addiu	$a0,$a0,%lo(g_MemCardFilenameBuf) # maspsx-keep\n"
		"	lui	$a2,%hi(g_MemCardPortStates) # maspsx-keep\n"
		"	addiu	$a2,$a2,%lo(g_MemCardPortStates) # maspsx-keep\n"
		"	sltu	$a2,$a2,$s0 # maspsx-keep\n"
		"	lbu	$v1,0x3($s0) # maspsx-keep\n"
		"	lui	$a1,%hi(g_MemCardFilenameFormatPtr) # maspsx-keep\n"
		"	lw	$a1,%lo(g_MemCardFilenameFormatPtr)($a1) # maspsx-keep\n"
		"	sll	$v0,$v1,4 # maspsx-keep\n"
		"	addu	$v0,$v0,$v1 # maspsx-keep\n"
		"	sll	$v0,$v0,2 # maspsx-keep\n"
		"	addu	$v0,$s0,$v0 # maspsx-keep\n"
		"	lbu	$a3,0x45($v0) # maspsx-keep\n"
		"	addiu	$v1,$v1,0x41 # maspsx-keep\n"
		"	sw	$v1,0x10($sp) # maspsx-keep\n"
		"	jal	Square_Vsprintf # maspsx-keep\n"
		"	addiu	$a3,$a3,0x30 # maspsx-keep\n"
		"	lui	$a0,%hi(g_MemCardFilenameBuf) # maspsx-keep\n"
		"	addiu	$a0,$a0,%lo(g_MemCardFilenameBuf) # maspsx-keep\n"
		"	jal	open # maspsx-keep\n"
		"	addiu	$a1,$zero,0x2 # maspsx-keep\n"
		"	bltz	$v0,.L80041A0C # maspsx-keep\n"
		"	sw	$v0,0xC($s0) # maspsx-keep\n"
		"	addiu	$v0,$zero,0x9 # maspsx-keep\n"
		"	sb	$v0,0x1($s0) # maspsx-keep\n"
		"	lui	$v0,%hi(g_MemCardFileBuffer) # maspsx-keep\n"
		"	addiu	$v0,$v0,%lo(g_MemCardFileBuffer) # maspsx-keep\n"
		"	sw	$v0,0x18($s0) # maspsx-keep\n"
		"	addiu	$v0,$zero,0x1E # maspsx-keep\n"
		"	j	.L80042000 # maspsx-keep\n"
		"	sh	$v0,0x16($s0) # maspsx-keep\n"
		".L80041A0C: # maspsx-keep\n"
		"	lhu	$v0,0x16($s0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	addiu	$v1,$v0,-0x1 # maspsx-keep\n"
		"	sll	$v0,$v0,16 # maspsx-keep\n"
		"	bgtz	$v0,.L80042000 # maspsx-keep\n"
		"	sh	$v1,0x16($s0) # maspsx-keep\n"
		"	lbu	$v0,0x0($s0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	andi	$v0,$v0,0x1 # maspsx-keep\n"
		"	beqz	$v0,.L80041FF8 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	jal	MemCard_AbortActiveOperation # maspsx-keep\n"
		"	addu	$a0,$s0,$zero # maspsx-keep\n"
		"	lbu	$v1,0x7($s0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	beq	$v1,$s1,.L80041FBC # maspsx-keep\n"
		"	addiu	$v0,$zero,0x2 # maspsx-keep\n"
		"	j	.L80041798 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L80041A58: # maspsx-keep\n"
		"	lbu	$s1,0x0($s0) # maspsx-keep\n"
		"	addiu	$v0,$zero,0x1 # maspsx-keep\n"
		"	bne	$s1,$v0,.L80041FF8 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lh	$v0,0x14($s0) # maspsx-keep\n"
		"	lhu	$a2,0x14($s0) # maspsx-keep\n"
		"	slti	$v0,$v0,0x81 # maspsx-keep\n"
		"	bnez	$v0,.L80041A80 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	addiu	$a2,$zero,0x80 # maspsx-keep\n"
		".L80041A80: # maspsx-keep\n"
		"	sll	$a2,$a2,16 # maspsx-keep\n"
		"	lw	$a0,0xC($s0) # maspsx-keep\n"
		"	lw	$a1,0x18($s0) # maspsx-keep\n"
		"	jal	read # maspsx-keep\n"
		"	sra	$a2,$a2,16 # maspsx-keep\n"
		"	addu	$a0,$v0,$zero # maspsx-keep\n"
		"	blez	$a0,.L80041ACC # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lw	$v0,0x18($s0) # maspsx-keep\n"
		"	lhu	$v1,0x14($s0) # maspsx-keep\n"
		"	addu	$v0,$v0,$a0 # maspsx-keep\n"
		"	subu	$v1,$v1,$a0 # maspsx-keep\n"
		"	sh	$v1,0x14($s0) # maspsx-keep\n"
		"	sll	$v1,$v1,16 # maspsx-keep\n"
		"	bgtz	$v1,.L80042000 # maspsx-keep\n"
		"	sw	$v0,0x18($s0) # maspsx-keep\n"
		"	addiu	$v0,$zero,0xA # maspsx-keep\n"
		"	j	.L80042000 # maspsx-keep\n"
		"	sb	$v0,0x1($s0) # maspsx-keep\n"
		".L80041ACC: # maspsx-keep\n"
		"	lhu	$v0,0x16($s0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	addiu	$v1,$v0,-0x1 # maspsx-keep\n"
		"	sll	$v0,$v0,16 # maspsx-keep\n"
		"	bgtz	$v0,.L80042000 # maspsx-keep\n"
		"	sh	$v1,0x16($s0) # maspsx-keep\n"
		"	lbu	$v0,0x0($s0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	andi	$v0,$v0,0x1 # maspsx-keep\n"
		"	beqz	$v0,.L80041FF8 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	jal	MemCard_AbortActiveOperation # maspsx-keep\n"
		"	addu	$a0,$s0,$zero # maspsx-keep\n"
		"	lbu	$v1,0x7($s0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	beq	$v1,$s1,.L80041FBC # maspsx-keep\n"
		"	addiu	$v0,$zero,0x2 # maspsx-keep\n"
		"	j	.L80041798 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L80041B18: # maspsx-keep\n"
		"	lbu	$s1,0x0($s0) # maspsx-keep\n"
		"	addiu	$v0,$zero,0x1 # maspsx-keep\n"
		"	bne	$s1,$v0,.L80041FF8 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lh	$v0,0x14($s0) # maspsx-keep\n"
		"	lhu	$a2,0x14($s0) # maspsx-keep\n"
		"	slti	$v0,$v0,0x401 # maspsx-keep\n"
		"	bnez	$v0,.L80041B40 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	addiu	$a2,$zero,0x400 # maspsx-keep\n"
		".L80041B40: # maspsx-keep\n"
		"	sll	$a2,$a2,16 # maspsx-keep\n"
		"	lw	$a0,0xC($s0) # maspsx-keep\n"
		"	lw	$a1,0x18($s0) # maspsx-keep\n"
		"	jal	read # maspsx-keep\n"
		"	sra	$a2,$a2,16 # maspsx-keep\n"
		"	addu	$a0,$v0,$zero # maspsx-keep\n"
		"	blez	$a0,.L80041BC0 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lw	$v0,0x18($s0) # maspsx-keep\n"
		"	lhu	$v1,0x14($s0) # maspsx-keep\n"
		"	addu	$v0,$v0,$a0 # maspsx-keep\n"
		"	subu	$v1,$v1,$a0 # maspsx-keep\n"
		"	sh	$v1,0x14($s0) # maspsx-keep\n"
		"	sll	$v1,$v1,16 # maspsx-keep\n"
		"	bgtz	$v1,.L80042000 # maspsx-keep\n"
		"	sw	$v0,0x18($s0) # maspsx-keep\n"
		"	lw	$a0,0xC($s0) # maspsx-keep\n"
		"	jal	close # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	addiu	$v0,$zero,-0x1 # maspsx-keep\n"
		"	sw	$v0,0xC($s0) # maspsx-keep\n"
		"	addiu	$v0,$zero,0xC # maspsx-keep\n"
		"	sb	$v0,0x1($s0) # maspsx-keep\n"
		"	sb	$zero,0x7($s0) # maspsx-keep\n"
		"	lui	$at,%hi(g_MemCardActiveState) # maspsx-keep\n"
		"	sw	$zero,%lo(g_MemCardActiveState)($at) # maspsx-keep\n"
		"	lui	$at,%hi(g_McOpPending) # maspsx-keep\n"
		"	sw	$zero,%lo(g_McOpPending)($at) # maspsx-keep\n"
		"	jal	Save_LoadCardFileIntoRuntime # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	j	.L80042000 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L80041BC0: # maspsx-keep\n"
		"	lhu	$v0,0x16($s0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	addiu	$v1,$v0,-0x1 # maspsx-keep\n"
		"	sll	$v0,$v0,16 # maspsx-keep\n"
		"	bgtz	$v0,.L80042000 # maspsx-keep\n"
		"	sh	$v1,0x16($s0) # maspsx-keep\n"
		"	lbu	$v0,0x0($s0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	andi	$v0,$v0,0x1 # maspsx-keep\n"
		"	beqz	$v0,.L80041FF8 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	jal	MemCard_AbortActiveOperation # maspsx-keep\n"
		"	addu	$a0,$s0,$zero # maspsx-keep\n"
		"	lbu	$v1,0x7($s0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	beq	$v1,$s1,.L80041FBC # maspsx-keep\n"
		"	addiu	$v0,$zero,0x2 # maspsx-keep\n"
		"	j	.L80041798 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L80041C0C: # maspsx-keep\n"
		"	lbu	$s1,0x0($s0) # maspsx-keep\n"
		"	addiu	$v0,$zero,0x1 # maspsx-keep\n"
		"	bne	$s1,$v0,.L80041FF8 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lh	$v0,0x14($s0) # maspsx-keep\n"
		"	lhu	$a2,0x14($s0) # maspsx-keep\n"
		"	slti	$v0,$v0,0x401 # maspsx-keep\n"
		"	bnez	$v0,.L80041C34 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	addiu	$a2,$zero,0x400 # maspsx-keep\n"
		".L80041C34: # maspsx-keep\n"
		"	sll	$a2,$a2,16 # maspsx-keep\n"
		"	lw	$a0,0xC($s0) # maspsx-keep\n"
		"	lw	$a1,0x18($s0) # maspsx-keep\n"
		"	jal	write # maspsx-keep\n"
		"	sra	$a2,$a2,16 # maspsx-keep\n"
		"	addu	$a0,$v0,$zero # maspsx-keep\n"
		"	blez	$a0,.L80041CB8 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lw	$v0,0x18($s0) # maspsx-keep\n"
		"	lhu	$v1,0x14($s0) # maspsx-keep\n"
		"	addu	$v0,$v0,$a0 # maspsx-keep\n"
		"	subu	$v1,$v1,$a0 # maspsx-keep\n"
		"	sh	$v1,0x14($s0) # maspsx-keep\n"
		"	sll	$v1,$v1,16 # maspsx-keep\n"
		"	bgtz	$v1,.L80042000 # maspsx-keep\n"
		"	sw	$v0,0x18($s0) # maspsx-keep\n"
		"	lw	$a0,0xC($s0) # maspsx-keep\n"
		"	jal	close # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	addiu	$v0,$zero,-0x1 # maspsx-keep\n"
		"	sw	$v0,0xC($s0) # maspsx-keep\n"
		"	addiu	$v0,$zero,0x3 # maspsx-keep\n"
		"	sb	$v0,0x1($s0) # maspsx-keep\n"
		"	sb	$zero,0x7($s0) # maspsx-keep\n"
		"	lui	$at,%hi(g_MemCardActiveState) # maspsx-keep\n"
		"	sw	$zero,%lo(g_MemCardActiveState)($at) # maspsx-keep\n"
		"	jal	Menu_DestroyMemCardProgressWidget # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	addiu	$a0,$zero,0x53 # maspsx-keep\n"
		"	jal	Menu_CreateNotificationDialog # maspsx-keep\n"
		"	addu	$a1,$zero,$zero # maspsx-keep\n"
		"	j	.L80042000 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L80041CB8: # maspsx-keep\n"
		"	lhu	$v0,0x16($s0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	addiu	$v1,$v0,-0x1 # maspsx-keep\n"
		"	sll	$v0,$v0,16 # maspsx-keep\n"
		"	bgtz	$v0,.L80042000 # maspsx-keep\n"
		"	sh	$v1,0x16($s0) # maspsx-keep\n"
		"	lbu	$v0,0x0($s0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	andi	$v0,$v0,0x1 # maspsx-keep\n"
		"	beqz	$v0,.L80041FF8 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	jal	MemCard_AbortActiveOperation # maspsx-keep\n"
		"	addu	$a0,$s0,$zero # maspsx-keep\n"
		"	lbu	$v1,0x7($s0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	beq	$v1,$s1,.L80041FBC # maspsx-keep\n"
		"	addiu	$v0,$zero,0x2 # maspsx-keep\n"
		"	j	.L80041798 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L80041D04: # maspsx-keep\n"
		"	lbu	$s1,0x0($s0) # maspsx-keep\n"
		"	addiu	$v0,$zero,0x1 # maspsx-keep\n"
		"	bne	$s1,$v0,.L80041FF8 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lw	$a0,0xC($s0) # maspsx-keep\n"
		"	jal	close # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	addiu	$v0,$zero,-0x1 # maspsx-keep\n"
		"	lbu	$v1,0x3($s0) # maspsx-keep\n"
		"	sll	$a0,$s2,7 # maspsx-keep\n"
		"	sw	$v0,0xC($s0) # maspsx-keep\n"
		"	sll	$v0,$v1,4 # maspsx-keep\n"
		"	addu	$v0,$v0,$v1 # maspsx-keep\n"
		"	sll	$v0,$v0,2 # maspsx-keep\n"
		"	addu	$a2,$v0,$s0 # maspsx-keep\n"
		"	addiu	$a2,$a2,0x1C # maspsx-keep\n"
		"	lui	$v0,%hi(D_800A1720) # maspsx-keep\n"
		"	addiu	$v0,$v0,%lo(D_800A1720) # maspsx-keep\n"
		"	lbu	$v1,0x0($a2) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	bne	$v1,$s1,.L80041DF0 # maspsx-keep\n"
		"	addu	$a3,$a0,$v0 # maspsx-keep\n"
		"	lhu	$v0,0x28($a3) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	sh	$v0,0x24($a2) # maspsx-keep\n"
		"	lhu	$v0,0x26($a3) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	sh	$v0,0x26($a2) # maspsx-keep\n"
		"	lbu	$v0,0x2A($a3) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	sb	$v0,0x28($a2) # maspsx-keep\n"
		"	lw	$v0,0x8($a3) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	sw	$v0,0xC($a2) # maspsx-keep\n"
		"	lw	$v0,0xC($a3) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	sw	$v0,0x10($a2) # maspsx-keep\n"
		"	lw	$v0,0x64($a3) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	sw	$v0,0x20($a2) # maspsx-keep\n"
		"	lbu	$v0,0x2B($a3) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	sb	$v0,0x2A($a2) # maspsx-keep\n"
		"	lhu	$v0,0x5C($a3) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	sh	$v0,0x2C($a2) # maspsx-keep\n"
		"	lhu	$v0,0x5E($a3) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	sh	$v0,0x2E($a2) # maspsx-keep\n"
		"	lw	$v0,0x0($a3) # maspsx-keep\n"
		"	lw	$v1,0x4($a3) # maspsx-keep\n"
		"	sw	$v0,0x4($a2) # maspsx-keep\n"
		"	sw	$v1,0x8($a2) # maspsx-keep\n"
		"	lw	$v0,0x10($a3) # maspsx-keep\n"
		"	lw	$v1,0x14($a3) # maspsx-keep\n"
		"	lw	$a0,0x18($a3) # maspsx-keep\n"
		"	sw	$v0,0x14($a2) # maspsx-keep\n"
		"	sw	$v1,0x18($a2) # maspsx-keep\n"
		"	sw	$a0,0x1C($a2) # maspsx-keep\n"
		".L80041DF0: # maspsx-keep\n"
		"	addiu	$v0,$zero,0x1 # maspsx-keep\n"
		"	sb	$v0,0x1($a2) # maspsx-keep\n"
		"	lbu	$v0,0x6($s0) # maspsx-keep\n"
		"	lbu	$v1,0x2($s0) # maspsx-keep\n"
		"	addiu	$v0,$v0,0x1 # maspsx-keep\n"
		"	sb	$v0,0x6($s0) # maspsx-keep\n"
		"	andi	$v0,$v0,0xFF # maspsx-keep\n"
		"	sll	$v1,$v1,1 # maspsx-keep\n"
		"	slt	$v0,$v0,$v1 # maspsx-keep\n"
		"	beqz	$v0,.L80041E20 # maspsx-keep\n"
		"	addiu	$a0,$zero,0xC # maspsx-keep\n"
		"	addiu	$a0,$zero,0x3 # maspsx-keep\n"
		".L80041E20: # maspsx-keep\n"
		"	andi	$v1,$a0,0xFF # maspsx-keep\n"
		"	addiu	$v0,$zero,0xC # maspsx-keep\n"
		"	bne	$v1,$v0,.L80042000 # maspsx-keep\n"
		"	sb	$a0,0x1($s0) # maspsx-keep\n"
		"	lui	$at,%hi(g_McOpPending) # maspsx-keep\n"
		"	sw	$zero,%lo(g_McOpPending)($at) # maspsx-keep\n"
		"	j	.L80042000 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L80041E40: # maspsx-keep\n"
		"	lbu	$s3,0x0($s0) # maspsx-keep\n"
		"	addiu	$v0,$zero,0x1 # maspsx-keep\n"
		"	bne	$s3,$v0,.L80041FF8 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lui	$a0,%hi(g_MemCardFilenameBuf) # maspsx-keep\n"
		"	addiu	$a0,$a0,%lo(g_MemCardFilenameBuf) # maspsx-keep\n"
		"	lui	$v0,%hi(g_MemCardPortStates) # maspsx-keep\n"
		"	addiu	$v0,$v0,%lo(g_MemCardPortStates) # maspsx-keep\n"
		"	sltu	$s2,$v0,$s0 # maspsx-keep\n"
		"	addu	$a2,$s2,$zero # maspsx-keep\n"
		"	lbu	$v1,0x3($s0) # maspsx-keep\n"
		"	lui	$a1,%hi(g_MemCardFilenameFormatPtr) # maspsx-keep\n"
		"	lw	$a1,%lo(g_MemCardFilenameFormatPtr)($a1) # maspsx-keep\n"
		"	sll	$v0,$v1,4 # maspsx-keep\n"
		"	addu	$v0,$v0,$v1 # maspsx-keep\n"
		"	sll	$v0,$v0,2 # maspsx-keep\n"
		"	addu	$v0,$s0,$v0 # maspsx-keep\n"
		"	lbu	$a3,0x45($v0) # maspsx-keep\n"
		"	addiu	$v1,$v1,0x41 # maspsx-keep\n"
		"	sw	$v1,0x10($sp) # maspsx-keep\n"
		"	jal	Square_Vsprintf # maspsx-keep\n"
		"	addiu	$a3,$a3,0x30 # maspsx-keep\n"
		"	lui	$s1,%hi(g_MemCardFilenameBuf) # maspsx-keep\n"
		"	addiu	$s1,$s1,%lo(g_MemCardFilenameBuf) # maspsx-keep\n"
		"	addu	$a0,$s1,$zero # maspsx-keep\n"
		"	jal	open # maspsx-keep\n"
		"	addiu	$a1,$zero,0x1 # maspsx-keep\n"
		"	bltz	$v0,.L80041F68 # maspsx-keep\n"
		"	sw	$v0,0xC($s0) # maspsx-keep\n"
		"	jal	close # maspsx-keep\n"
		"	addu	$a0,$v0,$zero # maspsx-keep\n"
		"	addu	$a0,$s1,$zero # maspsx-keep\n"
		"	addu	$a2,$s2,$zero # maspsx-keep\n"
		"	lui	$a1,%hi(g_MemCardFilenameFormatPtr) # maspsx-keep\n"
		"	lw	$a1,%lo(g_MemCardFilenameFormatPtr)($a1) # maspsx-keep\n"
		"	lbu	$v1,0x3($s0) # maspsx-keep\n"
		"	addiu	$v0,$zero,-0x1 # maspsx-keep\n"
		"	sw	$v0,0xC($s0) # maspsx-keep\n"
		"	sll	$v0,$v1,4 # maspsx-keep\n"
		"	addu	$v0,$v0,$v1 # maspsx-keep\n"
		"	sll	$v0,$v0,2 # maspsx-keep\n"
		"	addu	$v0,$s0,$v0 # maspsx-keep\n"
		"	lbu	$a3,0x45($v0) # maspsx-keep\n"
		"	addiu	$v1,$v1,0x41 # maspsx-keep\n"
		"	sw	$v1,0x10($sp) # maspsx-keep\n"
		"	jal	Square_Vsprintf # maspsx-keep\n"
		"	addiu	$a3,$a3,0x30 # maspsx-keep\n"
		"	jal	erase # maspsx-keep\n"
		"	addu	$a0,$s1,$zero # maspsx-keep\n"
		"	beqz	$v0,.L80041F1C # maspsx-keep\n"
		"	addiu	$v0,$zero,0x4 # maspsx-keep\n"
		".L80041F0C: # maspsx-keep\n"
		"	sb	$v0,0x1($s0) # maspsx-keep\n"
		"	addiu	$v0,$zero,0xA # maspsx-keep\n"
		"	j	.L80042000 # maspsx-keep\n"
		"	sh	$v0,0x16($s0) # maspsx-keep\n"
		".L80041F1C: # maspsx-keep\n"
		"	lhu	$v0,0x16($s0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	addiu	$v1,$v0,-0x1 # maspsx-keep\n"
		"	sll	$v0,$v0,16 # maspsx-keep\n"
		"	bgtz	$v0,.L80042000 # maspsx-keep\n"
		"	sh	$v1,0x16($s0) # maspsx-keep\n"
		"	lbu	$v0,0x0($s0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	andi	$v0,$v0,0x1 # maspsx-keep\n"
		"	beqz	$v0,.L80041FF8 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	jal	MemCard_AbortActiveOperation # maspsx-keep\n"
		"	addu	$a0,$s0,$zero # maspsx-keep\n"
		"	lbu	$v1,0x7($s0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	beq	$v1,$s3,.L80041FBC # maspsx-keep\n"
		"	addiu	$v0,$zero,0x2 # maspsx-keep\n"
		"	j	.L80041798 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L80041F68: # maspsx-keep\n"
		"	lhu	$v0,0x16($s0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	addiu	$v1,$v0,-0x1 # maspsx-keep\n"
		"	sll	$v0,$v0,16 # maspsx-keep\n"
		"	bgtz	$v0,.L80042000 # maspsx-keep\n"
		"	sh	$v1,0x16($s0) # maspsx-keep\n"
		"	lbu	$v0,0x0($s0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	andi	$v0,$v0,0x1 # maspsx-keep\n"
		"	beqz	$v0,.L80041FF8 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	jal	MemCard_AbortActiveOperation # maspsx-keep\n"
		"	addu	$a0,$s0,$zero # maspsx-keep\n"
		"	lbu	$v1,0x7($s0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	beq	$v1,$s3,.L80041FBC # maspsx-keep\n"
		"	addiu	$v0,$zero,0x2 # maspsx-keep\n"
		"	beq	$v1,$v0,.L80041FD0 # maspsx-keep\n"
		"	addiu	$a0,$zero,0x3E # maspsx-keep\n"
		"	j	.L80041FDC # maspsx-keep\n"
		"	addiu	$v0,$zero,0xC # maspsx-keep\n"
		".L80041FBC: # maspsx-keep\n"
		"	addiu	$a0,$zero,0x3D # maspsx-keep\n"
		"	jal	Menu_CreateTwoLineDialog # maspsx-keep\n"
		"	addiu	$a1,$zero,0x3F # maspsx-keep\n"
		"	j	.L80041FDC # maspsx-keep\n"
		"	addiu	$v0,$zero,0xC # maspsx-keep\n"
		".L80041FD0: # maspsx-keep\n"
		"	jal	Menu_CreateNotificationDialog # maspsx-keep\n"
		"	addu	$a1,$zero,$zero # maspsx-keep\n"
		"	addiu	$v0,$zero,0xC # maspsx-keep\n"
		".L80041FDC: # maspsx-keep\n"
		"	sb	$zero,0x7($s0) # maspsx-keep\n"
		"	j	.L80042000 # maspsx-keep\n"
		"	sb	$v0,0x1($s0) # maspsx-keep\n"
		".L80041FE8: # maspsx-keep\n"
		"	lbu	$v1,0x0($s0) # maspsx-keep\n"
		"	addiu	$v0,$zero,0x1 # maspsx-keep\n"
		"	beq	$v1,$v0,.L80042000 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L80041FF8: # maspsx-keep\n"
		"	jal	MemCard_AbortActiveOperation # maspsx-keep\n"
		"	addu	$a0,$s0,$zero # maspsx-keep\n"
		".L80042000: # maspsx-keep\n"
		".L80042000: # maspsx-keep\n"
		"	lw	$ra,0x70($sp) # maspsx-keep\n"
		"	lw	$s3,0x6C($sp) # maspsx-keep\n"
		"	lw	$s2,0x68($sp) # maspsx-keep\n"
		"	lw	$s1,0x64($sp) # maspsx-keep\n"
		"	lw	$s0,0x60($sp) # maspsx-keep\n"
		"	addiu	$sp,$sp,0x78 # maspsx-keep\n"
		"	jr	$ra # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	.set	macro # maspsx-keep\n"
		"	.set	reorder # maspsx-keep\n"
	);
}
