/* CC1_FLAGS: -G8 -g3 */
/* MASPSX_FLAGS: -G8 --use-comm-section */
/* Function body emitted as asm() (PSYQ GCC 2.7.2 register
 * allocation / scheduling diverges from the ROM pervasively).
 * Wrapped via maspsx's INCLUDE_ASM hack so the body is passed
 * through verbatim; bare global loads gp-rel via the .extern size
 * hints + `as -G8`. See tools/maspsx/PE1_IMPROVEMENTS.md. */
void __maspsx_include_asm_hack_MenuInput_DispatchQueuedEvents(void);
void __maspsx_include_asm_hack_MenuInput_DispatchQueuedEvents(void) {
	__asm__(
		"	.extern	g_MenuInputPollingPaused,1 # maspsx-keep\n"
		"	.extern	g_MenuEventQueueHead,1 # maspsx-keep\n"
		"	.extern	g_MenuEventQueueTail,1 # maspsx-keep\n"
		"	.extern	g_MenuEventQueueFreeList,1 # maspsx-keep\n"
		"	.set	noreorder # maspsx-keep\n"
		"	.set	nomacro # maspsx-keep\n"
		"	.globl	MenuInput_DispatchQueuedEvents # maspsx-keep\n"
		"MenuInput_DispatchQueuedEvents: # maspsx-keep\n"
		"	addiu	$sp,$sp,-0x30 # maspsx-keep\n"
		"	sw	$ra,0x2C($sp) # maspsx-keep\n"
		"	sw	$s2,0x28($sp) # maspsx-keep\n"
		"	sw	$s1,0x24($sp) # maspsx-keep\n"
		"	jal	MenuWidget_GetCurrentNode # maspsx-keep\n"
		"	sw	$s0,0x20($sp) # maspsx-keep\n"
		"	lw	$v1,g_MenuInputPollingPaused # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	bnez	$v1,.L8005E340 # maspsx-keep\n"
		"	addu	$s0,$v0,$zero # maspsx-keep\n"
		"	lw	$a0,0x28($s0) # maspsx-keep\n"
		"	jal	MenuInput_EnqueueStatusChanges # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L8005E340: # maspsx-keep\n"
		"	lw	$v0,g_MenuEventQueueHead # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	beqz	$v0,.L8005E3F8 # maspsx-keep\n"
		"	addiu	$a3,$sp,0x10 # maspsx-keep\n"
		"	addu	$a2,$v0,$zero # maspsx-keep\n"
		"	lw	$v0,0x4($a2) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	bnez	$v0,.L8005E388 # maspsx-keep\n"
		"	addu	$v1,$zero,$zero # maspsx-keep\n"
		".L8005E364: # maspsx-keep\n"
		"	addu	$v1,$a2,$zero # maspsx-keep\n"
		"	lw	$a2,0x0($a2) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	beqz	$a2,.L8005E3EC # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lw	$v0,0x4($a2) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	beqz	$v0,.L8005E364 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L8005E388: # maspsx-keep\n"
		"	beqz	$a2,.L8005E3EC # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	beqz	$v1,.L8005E3A4 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lw	$v0,0x0($a2) # maspsx-keep\n"
		"	j	.L8005E3B0 # maspsx-keep\n"
		"	sw	$v0,0x0($v1) # maspsx-keep\n"
		".L8005E3A4: # maspsx-keep\n"
		"	lw	$v0,0x0($a2) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	sw	$v0,g_MenuEventQueueHead # maspsx-keep\n"
		".L8005E3B0: # maspsx-keep\n"
		"	lw	$v0,g_MenuEventQueueTail # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	bne	$a2,$v0,.L8005E3C4 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	sw	$v1,g_MenuEventQueueTail # maspsx-keep\n"
		".L8005E3C4: # maspsx-keep\n"
		"	lw	$v0,g_MenuEventQueueFreeList # maspsx-keep\n"
		"	sw	$a2,g_MenuEventQueueFreeList # maspsx-keep\n"
		"	sw	$v0,0x0($a2) # maspsx-keep\n"
		"	lw	$v0,0x0($a2) # maspsx-keep\n"
		"	lw	$v1,0x4($a2) # maspsx-keep\n"
		"	lw	$a0,0x8($a2) # maspsx-keep\n"
		"	sw	$v0,0x0($a3) # maspsx-keep\n"
		"	sw	$v1,0x4($a3) # maspsx-keep\n"
		"	j	.L8005E400 # maspsx-keep\n"
		"	sw	$a0,0x8($a3) # maspsx-keep\n"
		".L8005E3EC: # maspsx-keep\n"
		"	sw	$zero,0x4($a3) # maspsx-keep\n"
		"	j	.L8005E400 # maspsx-keep\n"
		"	sw	$zero,0x8($a3) # maspsx-keep\n"
		".L8005E3F8: # maspsx-keep\n"
		"	sw	$zero,0x14($sp) # maspsx-keep\n"
		"	sw	$zero,0x18($sp) # maspsx-keep\n"
		".L8005E400: # maspsx-keep\n"
		"	lw	$v1,0x14($sp) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	blez	$v1,.L8005E4C8 # maspsx-keep\n"
		"	slti	$v0,$v1,0x3 # maspsx-keep\n"
		"	bnez	$v0,.L8005E428 # maspsx-keep\n"
		"	addiu	$v0,$zero,0x4 # maspsx-keep\n"
		"	beq	$v1,$v0,.L8005E478 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	j	.L8005E4C8 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L8005E428: # maspsx-keep\n"
		"	beqz	$s0,.L8005E4C8 # maspsx-keep\n"
		"	addiu	$s2,$zero,0x2 # maspsx-keep\n"
		"	lui	$s1,(0x20000 >> 16) # maspsx-keep\n"
		".L8005E434: # maspsx-keep\n"
		"	lw	$v0,0x14($sp) # maspsx-keep\n"
		"	lw	$a1,0x18($sp) # maspsx-keep\n"
		"	bne	$v0,$s2,.L8005E448 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	or	$a1,$a1,$s1 # maspsx-keep\n"
		".L8005E448: # maspsx-keep\n"
		"	lw	$v0,0x2C($s0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	jalr	$v0 # maspsx-keep\n"
		"	addu	$a0,$s0,$zero # maspsx-keep\n"
		"	bnez	$v0,.L8005E4C8 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lw	$s0,0x4($s0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	beqz	$s0,.L8005E4C8 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	j	.L8005E434 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L8005E478: # maspsx-keep\n"
		"	lw	$v0,0x18($sp) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	andi	$v0,$v0,0x20 # maspsx-keep\n"
		"	beqz	$v0,.L8005E4C8 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	jal	MenuWidget_GetCurrentNode # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	addu	$s0,$v0,$zero # maspsx-keep\n"
		"	beqz	$s0,.L8005E4C8 # maspsx-keep\n"
		"	addu	$a0,$s0,$zero # maspsx-keep\n"
		".L8005E4A0: # maspsx-keep\n"
		"	lw	$v0,0x2C($s0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	jalr	$v0 # maspsx-keep\n"
		"	lui	$a1,(0x10000 >> 16) # maspsx-keep\n"
		"	bnez	$v0,.L8005E4C8 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lw	$s0,0x4($s0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	bnez	$s0,.L8005E4A0 # maspsx-keep\n"
		"	addu	$a0,$s0,$zero # maspsx-keep\n"
		".L8005E4C8: # maspsx-keep\n"
		"	lw	$ra,0x2C($sp) # maspsx-keep\n"
		"	lw	$s2,0x28($sp) # maspsx-keep\n"
		"	lw	$s1,0x24($sp) # maspsx-keep\n"
		"	lw	$s0,0x20($sp) # maspsx-keep\n"
		"	addiu	$sp,$sp,0x30 # maspsx-keep\n"
		"	jr	$ra # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	.set	macro # maspsx-keep\n"
		"	.set	reorder # maspsx-keep\n"
	);
}
