/* CC1_FLAGS: -G8 -g3 */
/* MASPSX_FLAGS: -G8 --use-comm-section */
/* Function body emitted as asm() (PSYQ GCC 2.7.2 register
 * allocation / scheduling diverges from the ROM pervasively).
 * Wrapped via maspsx's INCLUDE_ASM hack so the body is passed
 * through verbatim; bare global loads gp-rel via the .extern size
 * hints + `as -G8`. See tools/maspsx/PE1_IMPROVEMENTS.md. */
void __maspsx_include_asm_hack_MenuInput_EnqueueStatusChanges(void);
void __maspsx_include_asm_hack_MenuInput_EnqueueStatusChanges(void) {
	__asm__(
		"	.extern	g_MenuInputActive,1 # maspsx-keep\n"
		"	.extern	g_MenuInputHeldStatusMask,1 # maspsx-keep\n"
		"	.extern	g_MenuEventQueueFreeList,1 # maspsx-keep\n"
		"	.extern	g_MenuEventQueueTail,1 # maspsx-keep\n"
		"	.extern	g_MenuEventQueueHead,1 # maspsx-keep\n"
		"	.extern	D_8009D0F8,1 # maspsx-keep\n"
		"	.extern	g_MenuDrawPhase,1 # maspsx-keep\n"
		"	.set	noreorder # maspsx-keep\n"
		"	.set	nomacro # maspsx-keep\n"
		"	.globl	MenuInput_EnqueueStatusChanges # maspsx-keep\n"
		"MenuInput_EnqueueStatusChanges: # maspsx-keep\n"
		"	addiu	$sp,$sp,-0x30 # maspsx-keep\n"
		"	sw	$s5,0x24($sp) # maspsx-keep\n"
		"	addu	$s5,$a0,$zero # maspsx-keep\n"
		"	sw	$s3,0x1C($sp) # maspsx-keep\n"
		"	addu	$s3,$zero,$zero # maspsx-keep\n"
		"	sw	$ra,0x28($sp) # maspsx-keep\n"
		"	sw	$s4,0x20($sp) # maspsx-keep\n"
		"	sw	$s2,0x18($sp) # maspsx-keep\n"
		"	sw	$s1,0x14($sp) # maspsx-keep\n"
		"	jal	Draw_RemapStatusFlags # maspsx-keep\n"
		"	sw	$s0,0x10($sp) # maspsx-keep\n"
		"	lw	$v1,g_MenuInputActive # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	beqz	$v1,.L8005E2D8 # maspsx-keep\n"
		"	addu	$s2,$v0,$zero # maspsx-keep\n"
		"	lw	$v1,g_MenuInputHeldStatusMask # maspsx-keep\n"
		"	nor	$v0,$zero,$s2 # maspsx-keep\n"
		"	and	$s1,$v0,$v1 # maspsx-keep\n"
		"	beqz	$s1,.L8005E1D4 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lw	$s0,g_MenuEventQueueFreeList # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	beqz	$s0,.L8005E1D4 # maspsx-keep\n"
		"	addiu	$s4,$zero,0x4 # maspsx-keep\n"
		"	lw	$v0,0x0($s0) # maspsx-keep\n"
		"	lw	$v1,g_MenuEventQueueTail # maspsx-keep\n"
		"	sw	$zero,0x0($s0) # maspsx-keep\n"
		"	sw	$v0,g_MenuEventQueueFreeList # maspsx-keep\n"
		"	beqz	$v1,.L8005E1AC # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	j	.L8005E1C8 # maspsx-keep\n"
		"	sw	$s0,0x0($v1) # maspsx-keep\n"
		".L8005E1AC: # maspsx-keep\n"
		"	lw	$v0,g_MenuEventQueueHead # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	beqz	$v0,.L8005E1C4 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	jal	BoundsCheck_AssertStub # maspsx-keep\n"
		"	addiu	$a0,$zero,0x1F # maspsx-keep\n"
		".L8005E1C4: # maspsx-keep\n"
		"	sw	$s0,g_MenuEventQueueHead # maspsx-keep\n"
		".L8005E1C8: # maspsx-keep\n"
		"	sw	$s0,g_MenuEventQueueTail # maspsx-keep\n"
		"	sw	$s4,0x4($s0) # maspsx-keep\n"
		"	sw	$s1,0x8($s0) # maspsx-keep\n"
		".L8005E1D4: # maspsx-keep\n"
		"	lw	$v0,g_MenuInputHeldStatusMask # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	beq	$v0,$s2,.L8005E1E8 # maspsx-keep\n"
		"	addiu	$v0,$zero,0x10 # maspsx-keep\n"
		"	sw	$v0,D_8009D0F8 # maspsx-keep\n"
		".L8005E1E8: # maspsx-keep\n"
		"	lw	$v0,D_8009D0F8 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	addiu	$v1,$v0,-0x2 # maspsx-keep\n"
		"	sw	$v1,D_8009D0F8 # maspsx-keep\n"
		"	bgez	$v1,.L8005E224 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	beqz	$s5,.L8005E210 # maspsx-keep\n"
		"	slti	$v0,$v1,-0x5A # maspsx-keep\n"
		"	bnez	$v0,.L8005E21C # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L8005E210: # maspsx-keep\n"
		"	andi	$v0,$v1,0x3 # maspsx-keep\n"
		"	bnez	$v0,.L8005E224 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L8005E21C: # maspsx-keep\n"
		"	sw	$zero,g_MenuInputHeldStatusMask # maspsx-keep\n"
		"	addiu	$s3,$zero,0x1 # maspsx-keep\n"
		".L8005E224: # maspsx-keep\n"
		"	lw	$v0,D_8009D0F8 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	slti	$v0,$v0,-0x12B # maspsx-keep\n"
		"	bnez	$v0,.L8005E23C # maspsx-keep\n"
		"	addiu	$v1,$zero,0x8 # maspsx-keep\n"
		"	addiu	$v1,$zero,0x1 # maspsx-keep\n"
		".L8005E23C: # maspsx-keep\n"
		"	lw	$v0,g_MenuInputHeldStatusMask # maspsx-keep\n"
		"	sw	$v1,g_MenuDrawPhase # maspsx-keep\n"
		"	nor	$v0,$zero,$v0 # maspsx-keep\n"
		"	and	$s1,$s2,$v0 # maspsx-keep\n"
		"	beqz	$s1,.L8005E2CC # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	beqz	$s3,.L8005E274 # maspsx-keep\n"
		"	addiu	$v0,$zero,0x1 # maspsx-keep\n"
		"	andi	$v0,$s1,0x40 # maspsx-keep\n"
		"	bnez	$v0,.L8005E2CC # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	beqz	$s3,.L8005E274 # maspsx-keep\n"
		"	addiu	$v0,$zero,0x1 # maspsx-keep\n"
		"	addiu	$v0,$zero,0x2 # maspsx-keep\n"
		".L8005E274: # maspsx-keep\n"
		"	lw	$s0,g_MenuEventQueueFreeList # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	beqz	$s0,.L8005E2CC # maspsx-keep\n"
		"	addu	$s3,$v0,$zero # maspsx-keep\n"
		"	lw	$v0,0x0($s0) # maspsx-keep\n"
		"	lw	$v1,g_MenuEventQueueTail # maspsx-keep\n"
		"	sw	$zero,0x0($s0) # maspsx-keep\n"
		"	sw	$v0,g_MenuEventQueueFreeList # maspsx-keep\n"
		"	beqz	$v1,.L8005E2A4 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	j	.L8005E2C0 # maspsx-keep\n"
		"	sw	$s0,0x0($v1) # maspsx-keep\n"
		".L8005E2A4: # maspsx-keep\n"
		"	lw	$v0,g_MenuEventQueueHead # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	beqz	$v0,.L8005E2BC # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	jal	BoundsCheck_AssertStub # maspsx-keep\n"
		"	addiu	$a0,$zero,0x1F # maspsx-keep\n"
		".L8005E2BC: # maspsx-keep\n"
		"	sw	$s0,g_MenuEventQueueHead # maspsx-keep\n"
		".L8005E2C0: # maspsx-keep\n"
		"	sw	$s0,g_MenuEventQueueTail # maspsx-keep\n"
		"	sw	$s3,0x4($s0) # maspsx-keep\n"
		"	sw	$s1,0x8($s0) # maspsx-keep\n"
		".L8005E2CC: # maspsx-keep\n"
		"	sw	$s2,g_MenuInputHeldStatusMask # maspsx-keep\n"
		"	j	.L8005E2E4 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L8005E2D8: # maspsx-keep\n"
		"	bnez	$s2,.L8005E2E4 # maspsx-keep\n"
		"	addiu	$v0,$zero,0x1 # maspsx-keep\n"
		"	sw	$v0,g_MenuInputActive # maspsx-keep\n"
		".L8005E2E4: # maspsx-keep\n"
		"	lw	$ra,0x28($sp) # maspsx-keep\n"
		"	lw	$s5,0x24($sp) # maspsx-keep\n"
		"	lw	$s4,0x20($sp) # maspsx-keep\n"
		"	lw	$s3,0x1C($sp) # maspsx-keep\n"
		"	lw	$s2,0x18($sp) # maspsx-keep\n"
		"	lw	$s1,0x14($sp) # maspsx-keep\n"
		"	lw	$s0,0x10($sp) # maspsx-keep\n"
		"	addiu	$sp,$sp,0x30 # maspsx-keep\n"
		"	jr	$ra # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	.set	macro # maspsx-keep\n"
		"	.set	reorder # maspsx-keep\n"
	);
}
