/* CC1_FLAGS: -G8 */
/* MASPSX_FLAGS: -G8 */
/* Function body emitted as asm() (PSYQ GCC 2.7.2 register
 * allocation / scheduling diverges from the ROM pervasively).
 * Wrapped via maspsx's INCLUDE_ASM hack so the body is passed
 * through verbatim; bare global loads gp-rel via the .extern size
 * hints + `as -G8`. See tools/maspsx/PE1_IMPROVEMENTS.md. */
asm(".globl Menu_DrawContextHelpText");
asm("Menu_DrawContextHelpText = func_8004C608");
void __maspsx_include_asm_hack_func_8004C608(void);
void __maspsx_include_asm_hack_func_8004C608(void) {
	__asm__(
		"	.extern	g_MenuItemContextFlag,1 # maspsx-keep\n"
		"	.extern	g_InvItemUsableFlag,1 # maspsx-keep\n"
		"	.extern	g_InvSelectedItemIndex,1 # maspsx-keep\n"
		"	.extern	g_MenuLayoutLocked,1 # maspsx-keep\n"
		"	.extern	g_MenuSelectionLocked,1 # maspsx-keep\n"
		"	.extern	g_MenuActionItemData,1 # maspsx-keep\n"
		"	.extern	g_McDialogMode,1 # maspsx-keep\n"
		"	.extern	g_MenuMemCardConfirmPending,1 # maspsx-keep\n"
		"	.extern	g_MenuEquipMode,1 # maspsx-keep\n"
		".extern	jtbl_8001104C # maspsx-keep\n"
		"	.set	noreorder # maspsx-keep\n"
		"	.set	nomacro # maspsx-keep\n"
		"	.globl	func_8004C608 # maspsx-keep\n"
		"func_8004C608: # maspsx-keep\n"
		"	addiu	$sp,$sp,-0x20 # maspsx-keep\n"
		"	sw	$s0,0x10($sp) # maspsx-keep\n"
		"	addu	$s0,$a0,$zero # maspsx-keep\n"
		"	sw	$s1,0x14($sp) # maspsx-keep\n"
		"	addu	$s1,$zero,$zero # maspsx-keep\n"
		"	sw	$ra,0x1C($sp) # maspsx-keep\n"
		"	jal	MenuWidget_GetCurrentNode # maspsx-keep\n"
		"	sw	$s2,0x18($sp) # maspsx-keep\n"
		"	jal	Draw_StatePush # maspsx-keep\n"
		"	addu	$s2,$v0,$zero # maspsx-keep\n"
		"	lw	$a0,0x34($s0) # maspsx-keep\n"
		"	addiu	$a1,$zero,0x1 # maspsx-keep\n"
		"	jal	Draw_OffsetCursor # maspsx-keep\n"
		"	addiu	$a0,$a0,-0x27 # maspsx-keep\n"
		"	jal	GameTime_GetCounterSeconds # maspsx-keep\n"
		"	addiu	$a0,$zero,0x2 # maspsx-keep\n"
		"	addu	$a0,$v0,$zero # maspsx-keep\n"
		"	jal	Draw_PrintTimeValue # maspsx-keep\n"
		"	addiu	$a1,$zero,0x1 # maspsx-keep\n"
		"	addiu	$a0,$zero,-0x21 # maspsx-keep\n"
		"	jal	Draw_OffsetCursor # maspsx-keep\n"
		"	addu	$a1,$zero,$zero # maspsx-keep\n"
		"	jal	Draw_AllocSprite # maspsx-keep\n"
		"	addiu	$a0,$zero,0x8C # maspsx-keep\n"
		"	jal	Draw_StatePop # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	beqz	$s2,.L8004CC10 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lw	$a1,0x24($s2) # maspsx-keep\n"
		"	jal	MenuWidget_FindByModeAndSelectedBase # maspsx-keep\n"
		"	addiu	$a0,$zero,0x2 # maspsx-keep\n"
		"	jal	MenuWidget_GridCellIndex # maspsx-keep\n"
		"	addu	$a0,$v0,$zero # maspsx-keep\n"
		"	lw	$v1,0x24($s2) # maspsx-keep\n"
		"	addu	$s0,$v0,$zero # maspsx-keep\n"
		"	sltiu	$v0,$v1,0x3D # maspsx-keep\n"
		"	beqz	$v0,.L8004CC10 # maspsx-keep\n"
		"	sll	$v0,$v1,2 # maspsx-keep\n"
		"	lui	$at,%hi(jtbl_8001104C) # maspsx-keep\n"
		"	addu	$at,$at,$v0 # maspsx-keep\n"
		"	lw	$v0,%lo(jtbl_8001104C)($at) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	jr	$v0 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L8004C6B8: # maspsx-keep\n"
		"	jal	Menu_GetBattleEquipMode # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	beqz	$v0,.L8004C6D4 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lw	$v0,g_MenuItemContextFlag # maspsx-keep\n"
		"	j	.L8004C6E0 # maspsx-keep\n"
		"	andi	$v1,$v0,0x1F # maspsx-keep\n"
		".L8004C6D4: # maspsx-keep\n"
		"	lw	$v0,g_MenuItemContextFlag # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	andi	$v1,$v0,0x1EF # maspsx-keep\n"
		".L8004C6E0: # maspsx-keep\n"
		"	addiu	$a0,$zero,-0x1 # maspsx-keep\n"
		".L8004C6E4: # maspsx-keep\n"
		"	bltz	$s0,.L8004C700 # maspsx-keep\n"
		"	andi	$v0,$v1,0x1 # maspsx-keep\n"
		"	subu	$s0,$s0,$v0 # maspsx-keep\n"
		"	addiu	$a0,$a0,0x1 # maspsx-keep\n"
		"	slti	$v0,$a0,0x9 # maspsx-keep\n"
		"	bnez	$v0,.L8004C6E4 # maspsx-keep\n"
		"	sra	$v1,$v1,1 # maspsx-keep\n"
		".L8004C700: # maspsx-keep\n"
		"	j	.L8004CC04 # maspsx-keep\n"
		"	addiu	$a0,$a0,0x28 # maspsx-keep\n"
		".L8004C708: # maspsx-keep\n"
		"	bltz	$s0,.L8004CC10 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lw	$v0,g_InvItemUsableFlag # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	beqz	$v0,.L8004C730 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lui	$a0,%hi(g_AyaEquippedWeaponSlot) # maspsx-keep\n"
		"	lb	$a0,%lo(g_AyaEquippedWeaponSlot)($a0) # maspsx-keep\n"
		"	j	.L8004C738 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L8004C730: # maspsx-keep\n"
		"	lui	$a0,%hi(g_AyaEquippedArmorSlot) # maspsx-keep\n"
		"	lb	$a0,%lo(g_AyaEquippedArmorSlot)($a0) # maspsx-keep\n"
		".L8004C738: # maspsx-keep\n"
		"	jal	Inv_LookupActiveListData # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	beqz	$v0,.L8004CC10 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lbu	$a0,0x4($v0) # maspsx-keep\n"
		"	jal	Str_LookupTableC # maspsx-keep\n"
		"	addiu	$a0,$a0,-0x1 # maspsx-keep\n"
		"	j	.L8004CC10 # maspsx-keep\n"
		"	addu	$s1,$v0,$zero # maspsx-keep\n"
		".L8004C75C: # maspsx-keep\n"
		"	lw	$a0,g_InvSelectedItemIndex # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	bgez	$a0,.L8004C7DC # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	jal	Inv_LookupActiveListData # maspsx-keep\n"
		"	addu	$a0,$s0,$zero # maspsx-keep\n"
		"	beqz	$v0,.L8004CC10 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lbu	$a0,0x4($v0) # maspsx-keep\n"
		"	jal	Str_LookupTableC # maspsx-keep\n"
		"	addiu	$a0,$a0,-0x1 # maspsx-keep\n"
		"	j	.L8004CC10 # maspsx-keep\n"
		"	addu	$s1,$v0,$zero # maspsx-keep\n"
		".L8004C790: # maspsx-keep\n"
		"	lw	$a0,g_InvSelectedItemIndex # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	bgez	$a0,.L8004C7DC # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	jal	Inv_GetWayneListItemByIndex # maspsx-keep\n"
		"	addu	$a0,$s0,$zero # maspsx-keep\n"
		"	jal	Inv_LookupActiveListData # maspsx-keep\n"
		"	addu	$a0,$v0,$zero # maspsx-keep\n"
		"	beqz	$v0,.L8004CC10 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lbu	$a0,0x4($v0) # maspsx-keep\n"
		"	jal	Str_LookupTableC # maspsx-keep\n"
		"	addiu	$a0,$a0,-0x1 # maspsx-keep\n"
		"	j	.L8004CC10 # maspsx-keep\n"
		"	addu	$s1,$v0,$zero # maspsx-keep\n"
		".L8004C7CC: # maspsx-keep\n"
		"	lw	$a0,g_InvSelectedItemIndex # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	bltz	$a0,.L8004C82C # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L8004C7DC: # maspsx-keep\n"
		"	jal	Inv_GetActiveListItemType # maspsx-keep\n"
		"	addu	$s0,$zero,$zero # maspsx-keep\n"
		"	slti	$v0,$v0,0x13 # maspsx-keep\n"
		"	bnez	$v0,.L8004C808 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lw	$a0,g_InvSelectedItemIndex # maspsx-keep\n"
		"	jal	Inv_GetActiveListItemType # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	slti	$v0,$v0,0x16 # maspsx-keep\n"
		"	bnez	$v0,.L8004C80C # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L8004C808: # maspsx-keep\n"
		"	addiu	$s0,$zero,0x1 # maspsx-keep\n"
		".L8004C80C: # maspsx-keep\n"
		"	jal	Str_LookupTable4 # maspsx-keep\n"
		"	ori	$a0,$s0,0xE # maspsx-keep\n"
		"	addu	$s1,$v0,$zero # maspsx-keep\n"
		"	lui	$a0,(0x408040 >> 16) # maspsx-keep\n"
		"	jal	Draw_SetColor # maspsx-keep\n"
		"	ori	$a0,$a0,0x8040 # maspsx-keep\n"
		"	j	.L8004CC10 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L8004C82C: # maspsx-keep\n"
		"	jal	Inv_LookupItemData # maspsx-keep\n"
		"	addu	$a0,$s0,$zero # maspsx-keep\n"
		"	beqz	$v0,.L8004CC10 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lbu	$a0,0x4($v0) # maspsx-keep\n"
		"	jal	Str_LookupTableC # maspsx-keep\n"
		"	addiu	$a0,$a0,-0x1 # maspsx-keep\n"
		"	j	.L8004CC10 # maspsx-keep\n"
		"	addu	$s1,$v0,$zero # maspsx-keep\n"
		".L8004C850: # maspsx-keep\n"
		"	lw	$v0,g_MenuLayoutLocked # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	beqz	$v0,.L8004C870 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	jal	Inv_RestoreSelection # maspsx-keep\n"
		"	addiu	$a0,$zero,0x1 # maspsx-keep\n"
		"	j	.L8004C87C # maspsx-keep\n"
		"	addu	$s0,$v0,$zero # maspsx-keep\n"
		".L8004C870: # maspsx-keep\n"
		"	jal	Inv_GetPackedListItem # maspsx-keep\n"
		"	addu	$a0,$s0,$zero # maspsx-keep\n"
		"	addu	$s0,$v0,$zero # maspsx-keep\n"
		".L8004C87C: # maspsx-keep\n"
		"	jal	Inv_LookupActiveListData # maspsx-keep\n"
		"	addu	$a0,$s0,$zero # maspsx-keep\n"
		"	beqz	$v0,.L8004CC10 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lbu	$a0,0x4($v0) # maspsx-keep\n"
		"	jal	Str_LookupTableC # maspsx-keep\n"
		"	addiu	$a0,$a0,-0x1 # maspsx-keep\n"
		"	j	.L8004CC10 # maspsx-keep\n"
		"	addu	$s1,$v0,$zero # maspsx-keep\n"
		".L8004C8A0: # maspsx-keep\n"
		"	jal	Inv_GetPackedListCount # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	slt	$v0,$s0,$v0 # maspsx-keep\n"
		"	beqz	$v0,.L8004CC10 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	jal	Inv_GetPackedListItem # maspsx-keep\n"
		"	addu	$a0,$s0,$zero # maspsx-keep\n"
		"	jal	Str_LookupTableC # maspsx-keep\n"
		"	addiu	$a0,$v0,0xEB # maspsx-keep\n"
		"	j	.L8004CC10 # maspsx-keep\n"
		"	addu	$s1,$v0,$zero # maspsx-keep\n"
		".L8004C8CC: # maspsx-keep\n"
		"	j	.L8004CC04 # maspsx-keep\n"
		"	addiu	$a0,$s0,0x4F # maspsx-keep\n"
		".L8004C8D4: # maspsx-keep\n"
		"	lw	$v0,g_MenuSelectionLocked # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	beqz	$v0,.L8004C8FC # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	jal	Menu_GetBattleCountEntry # maspsx-keep\n"
		"	addu	$a0,$s0,$zero # maspsx-keep\n"
		"	jal	Str_LookupTableC # maspsx-keep\n"
		"	addiu	$a0,$v0,-0x1 # maspsx-keep\n"
		"	j	.L8004CC10 # maspsx-keep\n"
		"	addu	$s1,$v0,$zero # maspsx-keep\n"
		".L8004C8FC: # maspsx-keep\n"
		"	jal	Inv_GetPackedListItem # maspsx-keep\n"
		"	addu	$a0,$s0,$zero # maspsx-keep\n"
		"	jal	Inv_LookupActiveListData # maspsx-keep\n"
		"	addu	$a0,$v0,$zero # maspsx-keep\n"
		"	beqz	$v0,.L8004CC10 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lbu	$a0,0x4($v0) # maspsx-keep\n"
		"	jal	Str_LookupTableC # maspsx-keep\n"
		"	addiu	$a0,$a0,-0x1 # maspsx-keep\n"
		"	j	.L8004CC10 # maspsx-keep\n"
		"	addu	$s1,$v0,$zero # maspsx-keep\n"
		".L8004C928: # maspsx-keep\n"
		"	jal	Inv_SelectActiveList # maspsx-keep\n"
		"	addu	$a0,$zero,$zero # maspsx-keep\n"
		"	jal	Inv_LookupActiveListData # maspsx-keep\n"
		"	addu	$a0,$s0,$zero # maspsx-keep\n"
		"	beqz	$v0,.L8004CC10 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lbu	$a0,0x4($v0) # maspsx-keep\n"
		"	jal	Str_LookupTableC # maspsx-keep\n"
		"	addiu	$a0,$a0,-0x1 # maspsx-keep\n"
		"	j	.L8004CC10 # maspsx-keep\n"
		"	addu	$s1,$v0,$zero # maspsx-keep\n"
		".L8004C954: # maspsx-keep\n"
		"	lw	$v0,g_MenuActionItemData # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	addu	$v0,$v0,$s0 # maspsx-keep\n"
		"	lbu	$v0,0x15($v0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	andi	$a1,$v0,0x1F # maspsx-keep\n"
		"	beqz	$a1,.L8004CC10 # maspsx-keep\n"
		"	addiu	$v0,$zero,0x1 # maspsx-keep\n"
		"	lw	$v1,g_InvItemUsableFlag # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	subu	$v0,$v0,$v1 # maspsx-keep\n"
		"	sll	$a0,$v0,2 # maspsx-keep\n"
		"	addu	$a0,$a0,$v0 # maspsx-keep\n"
		"	sll	$a0,$a0,2 # maspsx-keep\n"
		"	addu	$a0,$a1,$a0 # maspsx-keep\n"
		"	j	.L8004CC04 # maspsx-keep\n"
		"	addiu	$a0,$a0,-0x1 # maspsx-keep\n"
		".L8004C998: # maspsx-keep\n"
		"	jal	Inv_RestoreSelection # maspsx-keep\n"
		"	addiu	$a0,$zero,0x1 # maspsx-keep\n"
		"	jal	Inv_LookupActiveListData # maspsx-keep\n"
		"	addu	$a0,$v0,$zero # maspsx-keep\n"
		"	addu	$v0,$v0,$s0 # maspsx-keep\n"
		"	lbu	$v0,0x15($v0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	andi	$a1,$v0,0x1F # maspsx-keep\n"
		"	beqz	$a1,.L8004CC10 # maspsx-keep\n"
		"	addiu	$v0,$zero,0x1 # maspsx-keep\n"
		"	lw	$v1,g_InvItemUsableFlag # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	subu	$v0,$v0,$v1 # maspsx-keep\n"
		"	sll	$a0,$v0,2 # maspsx-keep\n"
		"	addu	$a0,$a0,$v0 # maspsx-keep\n"
		"	sll	$a0,$a0,2 # maspsx-keep\n"
		"	addu	$a0,$a1,$a0 # maspsx-keep\n"
		"	j	.L8004CC04 # maspsx-keep\n"
		"	addiu	$a0,$a0,-0x1 # maspsx-keep\n"
		".L8004C9E4: # maspsx-keep\n"
		"	jal	Str_LookupTable4 # maspsx-keep\n"
		"	addiu	$a0,$zero,0x27 # maspsx-keep\n"
		"	j	.L8004CC10 # maspsx-keep\n"
		"	addu	$s1,$v0,$zero # maspsx-keep\n"
		".L8004C9F4: # maspsx-keep\n"
		"	j	.L8004CC04 # maspsx-keep\n"
		"	addiu	$a0,$zero,0x52 # maspsx-keep\n"
		".L8004C9FC: # maspsx-keep\n"
		"	lw	$v0,g_InvItemUsableFlag # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	sll	$a0,$v0,1 # maspsx-keep\n"
		"	addu	$a0,$a0,$v0 # maspsx-keep\n"
		"	j	.L8004CC00 # maspsx-keep\n"
		"	addiu	$a0,$a0,-0x56 # maspsx-keep\n"
		".L8004CA14: # maspsx-keep\n"
		"	slti	$v0,$s0,0x4 # maspsx-keep\n"
		"	bnez	$v0,.L8004CC04 # maspsx-keep\n"
		"	addiu	$a0,$s0,0x31 # maspsx-keep\n"
		"	j	.L8004CC10 # maspsx-keep\n"
		"	addu	$s1,$zero,$zero # maspsx-keep\n"
		".L8004CA28: # maspsx-keep\n"
		"	j	.L8004CC04 # maspsx-keep\n"
		"	addiu	$a0,$s0,0x3A # maspsx-keep\n"
		".L8004CA30: # maspsx-keep\n"
		"	j	.L8004CC04 # maspsx-keep\n"
		"	addiu	$a0,$s0,0x3D # maspsx-keep\n"
		".L8004CA38: # maspsx-keep\n"
		"	jal	MemCard_PollTransferDelay # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	beqz	$v0,.L8004CA74 # maspsx-keep\n"
		"	addiu	$a0,$zero,0x6 # maspsx-keep\n"
		"	jal	Draw_OffsetCursor # maspsx-keep\n"
		"	addiu	$a1,$zero,0x5 # maspsx-keep\n"
		"	jal	Draw_PrintTextById # maspsx-keep\n"
		"	addiu	$a0,$zero,0x4C # maspsx-keep\n"
		"	addu	$a0,$zero,$zero # maspsx-keep\n"
		"	jal	Draw_OffsetCursor # maspsx-keep\n"
		"	addiu	$a1,$zero,0x10 # maspsx-keep\n"
		"	jal	Draw_PrintTextById # maspsx-keep\n"
		"	addiu	$a0,$zero,0x4D # maspsx-keep\n"
		"	j	.L8004CC10 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L8004CA74: # maspsx-keep\n"
		"	addu	$s0,$zero,$zero # maspsx-keep\n"
		"	jal	MemCard_IsPortPresent # maspsx-keep\n"
		"	addu	$a0,$zero,$zero # maspsx-keep\n"
		"	bnez	$v0,.L8004CA98 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	jal	MemCard_IsPortPresent # maspsx-keep\n"
		"	addiu	$a0,$zero,0x1 # maspsx-keep\n"
		"	beqz	$v0,.L8004CA9C # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L8004CA98: # maspsx-keep\n"
		"	addiu	$s0,$zero,0x1 # maspsx-keep\n"
		".L8004CA9C: # maspsx-keep\n"
		"	jal	Str_LookupTable4 # maspsx-keep\n"
		"	ori	$a0,$s0,0x4E # maspsx-keep\n"
		"	j	.L8004CC10 # maspsx-keep\n"
		"	addu	$s1,$v0,$zero # maspsx-keep\n"
		".L8004CAAC: # maspsx-keep\n"
		"	lw	$v0,g_McDialogMode # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	beqz	$v0,.L8004CB14 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lw	$v0,g_MenuMemCardConfirmPending # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	beqz	$v0,.L8004CB04 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	jal	Draw_SetTextDimmed # maspsx-keep\n"
		"	addu	$a0,$zero,$zero # maspsx-keep\n"
		"	addiu	$a0,$zero,0x6 # maspsx-keep\n"
		"	jal	Draw_OffsetCursor # maspsx-keep\n"
		"	addiu	$a1,$zero,0x5 # maspsx-keep\n"
		"	jal	Draw_PrintTextById # maspsx-keep\n"
		"	addiu	$a0,$zero,0x58 # maspsx-keep\n"
		"	addu	$a0,$zero,$zero # maspsx-keep\n"
		"	jal	Draw_OffsetCursor # maspsx-keep\n"
		"	addiu	$a1,$zero,0x10 # maspsx-keep\n"
		"	jal	Draw_PrintTextById # maspsx-keep\n"
		"	addiu	$a0,$zero,0x59 # maspsx-keep\n"
		"	j	.L8004CC10 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L8004CB04: # maspsx-keep\n"
		"	jal	Str_LookupTable4 # maspsx-keep\n"
		"	addiu	$a0,$zero,0x5C # maspsx-keep\n"
		"	j	.L8004CC10 # maspsx-keep\n"
		"	addu	$s1,$v0,$zero # maspsx-keep\n"
		".L8004CB14: # maspsx-keep\n"
		"	jal	Save_GetTitleStyleFlag # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	beqz	$v0,.L8004CB28 # maspsx-keep\n"
		"	addiu	$a0,$zero,0x5B # maspsx-keep\n"
		"	addiu	$a0,$zero,0x57 # maspsx-keep\n"
		".L8004CB28: # maspsx-keep\n"
		"	jal	Str_LookupTable4 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	j	.L8004CC10 # maspsx-keep\n"
		"	addu	$s1,$v0,$zero # maspsx-keep\n"
		".L8004CB38: # maspsx-keep\n"
		"	jal	Draw_SetTextDimmed # maspsx-keep\n"
		"	addu	$a0,$zero,$zero # maspsx-keep\n"
		"	addiu	$a0,$zero,0x6 # maspsx-keep\n"
		"	jal	Draw_OffsetCursor # maspsx-keep\n"
		"	addiu	$a1,$zero,0x5 # maspsx-keep\n"
		"	jal	Draw_PrintTextById # maspsx-keep\n"
		"	addiu	$a0,$zero,0x50 # maspsx-keep\n"
		"	addu	$a0,$zero,$zero # maspsx-keep\n"
		"	jal	Draw_OffsetCursor # maspsx-keep\n"
		"	addiu	$a1,$zero,0x10 # maspsx-keep\n"
		"	jal	Draw_PrintTextById # maspsx-keep\n"
		"	addiu	$a0,$zero,0x51 # maspsx-keep\n"
		"	j	.L8004CC10 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L8004CB70: # maspsx-keep\n"
		"	j	.L8004CC04 # maspsx-keep\n"
		"	addiu	$a0,$s0,0x3F # maspsx-keep\n"
		".L8004CB78: # maspsx-keep\n"
		"	j	.L8004CC04 # maspsx-keep\n"
		"	addiu	$a0,$s0,0x38 # maspsx-keep\n"
		".L8004CB80: # maspsx-keep\n"
		"	j	.L8004CC04 # maspsx-keep\n"
		"	addiu	$a0,$s0,0x42 # maspsx-keep\n"
		".L8004CB88: # maspsx-keep\n"
		"	lui	$a0,%hi(D_8009234C) # maspsx-keep\n"
		"	addiu	$a0,$a0,%lo(D_8009234C) # maspsx-keep\n"
		"	lw	$v1,g_MenuEquipMode # maspsx-keep\n"
		"	addiu	$v0,$zero,0x1 # maspsx-keep\n"
		"	bne	$v1,$v0,.L8004CBB0 # maspsx-keep\n"
		"	addu	$v0,$s0,$a0 # maspsx-keep\n"
		"	addiu	$v0,$zero,0x2 # maspsx-keep\n"
		"	bne	$s0,$v0,.L8004CBB0 # maspsx-keep\n"
		"	addu	$v0,$s0,$a0 # maspsx-keep\n"
		"	addiu	$v0,$a0,0x4 # maspsx-keep\n"
		".L8004CBB0: # maspsx-keep\n"
		"	lbu	$a0,0x0($v0) # maspsx-keep\n"
		"	j	.L8004CC04 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L8004CBBC: # maspsx-keep\n"
		"	jal	Draw_SetTextDimmed # maspsx-keep\n"
		"	addu	$a0,$zero,$zero # maspsx-keep\n"
		"	j	.L8004CC04 # maspsx-keep\n"
		"	addiu	$a0,$zero,0x44 # maspsx-keep\n"
		".L8004CBCC: # maspsx-keep\n"
		"	j	.L8004CC04 # maspsx-keep\n"
		"	addiu	$a0,$s0,0x35 # maspsx-keep\n"
		".L8004CBD4: # maspsx-keep\n"
		"	lw	$v1,g_MenuEquipMode # maspsx-keep\n"
		"	addiu	$v0,$zero,0x2 # maspsx-keep\n"
		"	bne	$v1,$v0,.L8004CC04 # maspsx-keep\n"
		"	addiu	$a0,$s0,0x4B # maspsx-keep\n"
		"	j	.L8004CC04 # maspsx-keep\n"
		"	addiu	$a0,$s0,0x4D # maspsx-keep\n"
		".L8004CBEC: # maspsx-keep\n"
		"	lw	$v0,g_InvItemUsableFlag # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	sll	$a0,$v0,1 # maspsx-keep\n"
		"	addu	$a0,$a0,$v0 # maspsx-keep\n"
		"	addiu	$a0,$a0,-0x48 # maspsx-keep\n"
		".L8004CC00: # maspsx-keep\n"
		"	subu	$a0,$s0,$a0 # maspsx-keep\n"
		".L8004CC04: # maspsx-keep\n"
		"	jal	Str_LookupTable10 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	addu	$s1,$v0,$zero # maspsx-keep\n"
		".L8004CC10: # maspsx-keep\n"
		".L8004CC10: # maspsx-keep\n"
		"	beqz	$s1,.L8004CC34 # maspsx-keep\n"
		"	addiu	$a0,$zero,0x6 # maspsx-keep\n"
		"	jal	Draw_OffsetCursor # maspsx-keep\n"
		"	addiu	$a1,$zero,0x5 # maspsx-keep\n"
		"	jal	Draw_PrintRawText # maspsx-keep\n"
		"	addu	$a0,$s1,$zero # maspsx-keep\n"
		"	lui	$a0,(0x808080 >> 16) # maspsx-keep\n"
		"	jal	Draw_SetColor # maspsx-keep\n"
		"	ori	$a0,$a0,0x8080 # maspsx-keep\n"
		".L8004CC34: # maspsx-keep\n"
		"	lw	$ra,0x1C($sp) # maspsx-keep\n"
		"	lw	$s2,0x18($sp) # maspsx-keep\n"
		"	lw	$s1,0x14($sp) # maspsx-keep\n"
		"	lw	$s0,0x10($sp) # maspsx-keep\n"
		"	addiu	$sp,$sp,0x20 # maspsx-keep\n"
		"	jr	$ra # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	.set	macro # maspsx-keep\n"
		"	.set	reorder # maspsx-keep\n"
	);
}
