/* MASPSX_FLAGS: --expand-div */
#define ROOMEFFECT_LINE_BURST_FUNC func_80192898
#define ROOMEFFECT_LINE_BURST_CALLBACK func_801924FC
#define ROOMEFFECT_LINE_BURST_TEMPLATE D_8018F1D0
#define ROOMEFFECT_LINE_BURST_ROTATION D_8018F1D8
#include "../room_lib/RoomEffect_LineBurstController.inc"
