/* CC1_FLAGS: -G8 -g3 */
/* MASPSX_FLAGS: --use-comm-section -G8 */
#include "include_asm.h"

typedef unsigned char u8;

extern int g_BattleEntitySlotInUse[][0x37];
u8 D_8009D2A0;
u8 g_EntityInstanceCounter;

void Battle_SaveAyaState(void);
void Save_ResetGlobalFlags(void);

/* Function body emitted as asm() (PSYQ GCC 2.7.2 register
 * allocation / scheduling diverges from the ROM pervasively).
 * Wrapped via maspsx's INCLUDE_ASM hack so the body is passed
 * through verbatim; bare global loads gp-rel via the .extern size
 * hints + `as -G8`. See tools/maspsx/PE1_IMPROVEMENTS.md. */
void __maspsx_include_asm_hack_func_8002B29C(void);

void Save_InitSystem(void) {
    u8 i;

    Battle_SaveAyaState();

    for (i = 0; i < 7; i++) {
        g_BattleEntitySlotInUse[i][0] = 0;
    }

    D_8009D2A0 = 0;
    g_EntityInstanceCounter = 0;
    Save_ResetGlobalFlags();
}

INCLUDE_ASM("asm/USA/main/nonmatchings/main/battle3", Battle_ResetEnemyStats);

INCLUDE_ASM("asm/USA/main/nonmatchings/main/battle3", Battle_SetupPlayerPalette);

INCLUDE_ASM("asm/USA/main/nonmatchings/main/battle3", Battle_StartEncounter);

INCLUDE_ASM("asm/USA/main/nonmatchings/main/battle3", Battle_Update);

INCLUDE_ASM("asm/USA/main/nonmatchings/main/battle3", Battle_StepVictory);

INCLUDE_ASM("asm/USA/main/nonmatchings/main/battle3", Battle_StepLevelUp);

void __maspsx_include_asm_hack_func_8002B29C(void) {
	__asm__(
		"	.extern	g_BattlePhaseStep,1 # maspsx-keep\n"
		"	.extern	g_BattleVictoryStepTimer,1 # maspsx-keep\n"
		"	.extern	g_BattleModeState,1 # maspsx-keep\n"
		".extern	jtbl_80010910 # maspsx-keep\n"
		"	.set	noreorder # maspsx-keep\n"
		"	.set	nomacro # maspsx-keep\n"
		"	.globl	Battle_StepPostBattle # maspsx-keep\n"
		"Battle_StepPostBattle: # maspsx-keep\n"
		"	lbu	$v1,g_BattlePhaseStep # maspsx-keep\n"
		"	addiu	$sp,$sp,-0x38 # maspsx-keep\n"
		"	sw	$ra,0x30($sp) # maspsx-keep\n"
		"	sw	$s1,0x2C($sp) # maspsx-keep\n"
		"	sltiu	$v0,$v1,0x6 # maspsx-keep\n"
		"	beqz	$v0,.L8002B900 # maspsx-keep\n"
		"	sw	$s0,0x28($sp) # maspsx-keep\n"
		"	sll	$v0,$v1,2 # maspsx-keep\n"
		"	lui	$at,%hi(jtbl_80010910) # maspsx-keep\n"
		"	addu	$at,$at,$v0 # maspsx-keep\n"
		"	lw	$v0,%lo(jtbl_80010910)($at) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	jr	$v0 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L8002B2D4: # maspsx-keep\n"
		"	lui	$a0,%hi(g_PlayerEntity) # maspsx-keep\n"
		"	lw	$a0,%lo(g_PlayerEntity)($a0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lbu	$v1,0xE($a0) # maspsx-keep\n"
		"	addiu	$v0,$zero,0x13 # maspsx-keep\n"
		"	beq	$v1,$v0,.L8002B300 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	jal	Entity_SetActionMode # maspsx-keep\n"
		"	addiu	$a1,$zero,0x13 # maspsx-keep\n"
		"	lui	$a0,%hi(g_PlayerEntity) # maspsx-keep\n"
		"	lw	$a0,%lo(g_PlayerEntity)($a0) # maspsx-keep\n"
		".L8002B300: # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lbu	$v1,0xF($a0) # maspsx-keep\n"
		"	lhu	$v0,0x16($a0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	bne	$v1,$v0,.L8002B434 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lui	$s0,%hi(g_FieldActorListHead) # maspsx-keep\n"
		"	lw	$s0,%lo(g_FieldActorListHead)($s0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	beqz	$s0,.L8002B400 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L8002B32C: # maspsx-keep\n"
		"	lui	$v0,%hi(g_PlayerEntity) # maspsx-keep\n"
		"	lw	$v0,%lo(g_PlayerEntity)($v0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	beq	$s0,$v0,.L8002B3F0 # maspsx-keep\n"
		"	addiu	$v0,$zero,0x1 # maspsx-keep\n"
		"	lw	$a0,0x0($s0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lb	$v1,0x5($a0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	beq	$v1,$v0,.L8002B3F0 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	bnez	$a0,.L8002B374 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lw	$v0,0x98($s0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	andi	$v0,$v0,0x40 # maspsx-keep\n"
		"	bnez	$v0,.L8002B3F0 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L8002B374: # maspsx-keep\n"
		"	lhu	$v0,0x250($s0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	ori	$v0,$v0,0x2 # maspsx-keep\n"
		"	sh	$v0,0x250($s0) # maspsx-keep\n"
		"	lw	$v0,0x98($s0) # maspsx-keep\n"
		"	lw	$v1,0x0($s0) # maspsx-keep\n"
		"	ori	$v0,$v0,0x1000 # maspsx-keep\n"
		"	beqz	$v1,.L8002B3E4 # maspsx-keep\n"
		"	sw	$v0,0x98($s0) # maspsx-keep\n"
		"	lbu	$a1,0x6($v1) # maspsx-keep\n"
		"	addu	$a0,$s0,$zero # maspsx-keep\n"
		"	sll	$a1,$a1,24 # maspsx-keep\n"
		"	sra	$a1,$a1,24 # maspsx-keep\n"
		"	jal	Entity_SetActionMode # maspsx-keep\n"
		"	andi	$a1,$a1,0xFFFF # maspsx-keep\n"
		"	lw	$v1,0x98($s0) # maspsx-keep\n"
		"	lui	$v0,(0x40000000 >> 16) # maspsx-keep\n"
		"	and	$v0,$v1,$v0 # maspsx-keep\n"
		"	beqz	$v0,.L8002B3E4 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lw	$v0,0x0($s0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lbu	$v0,0xAF($v0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	bnez	$v0,.L8002B3E4 # maspsx-keep\n"
		"	ori	$v0,$v1,0x10 # maspsx-keep\n"
		"	sw	$v0,0x98($s0) # maspsx-keep\n"
		"	sw	$zero,0x0($s0) # maspsx-keep\n"
		".L8002B3E4: # maspsx-keep\n"
		"	sw	$zero,0x68($s0) # maspsx-keep\n"
		"	sw	$zero,0x6C($s0) # maspsx-keep\n"
		"	sw	$zero,0x70($s0) # maspsx-keep\n"
		".L8002B3F0: # maspsx-keep\n"
		"	lw	$s0,0x4($s0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	bnez	$s0,.L8002B32C # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L8002B400: # maspsx-keep\n"
		"	jal	Battle_ResetEnemyStats # maspsx-keep\n"
		"	addu	$a0,$zero,$zero # maspsx-keep\n"
		"	lui	$a0,%hi(g_PlayerEntity) # maspsx-keep\n"
		"	lw	$a0,%lo(g_PlayerEntity)($a0) # maspsx-keep\n"
		"	addiu	$v0,$zero,0x46 # maspsx-keep\n"
		"	sb	$v0,g_BattleVictoryStepTimer # maspsx-keep\n"
		"	lbu	$v0,g_BattlePhaseStep # maspsx-keep\n"
		"	lw	$v1,0x98($a0) # maspsx-keep\n"
		"	addiu	$v0,$v0,0x1 # maspsx-keep\n"
		"	sb	$v0,g_BattlePhaseStep # maspsx-keep\n"
		"	ori	$v1,$v1,0x100 # maspsx-keep\n"
		"	j	.L8002B900 # maspsx-keep\n"
		"	sw	$v1,0x98($a0) # maspsx-keep\n"
		".L8002B434: # maspsx-keep\n"
		"	lw	$v0,0x98($a0) # maspsx-keep\n"
		"	addiu	$v1,$zero,-0x101 # maspsx-keep\n"
		"	and	$v0,$v0,$v1 # maspsx-keep\n"
		"	j	.L8002B900 # maspsx-keep\n"
		"	sw	$v0,0x98($a0) # maspsx-keep\n"
		".L8002B448: # maspsx-keep\n"
		"	lbu	$v1,g_BattleVictoryStepTimer # maspsx-keep\n"
		"	addiu	$v0,$zero,0x3C # maspsx-keep\n"
		"	bne	$v1,$v0,.L8002B4EC # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	jal	Render_StartFadeIn # maspsx-keep\n"
		"	addiu	$a0,$zero,0x3C # maspsx-keep\n"
		"	addu	$a0,$zero,$zero # maspsx-keep\n"
		"	addiu	$a1,$zero,0x3C # maspsx-keep\n"
		"	jal	Akao_Cmd_C1_WithSlot # maspsx-keep\n"
		"	addu	$a2,$zero,$zero # maspsx-keep\n"
		"	lui	$s0,%hi(g_FieldActorListHead) # maspsx-keep\n"
		"	lw	$s0,%lo(g_FieldActorListHead)($s0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	beqz	$s0,.L8002B568 # maspsx-keep\n"
		"	addiu	$s1,$zero,0x1 # maspsx-keep\n"
		".L8002B484: # maspsx-keep\n"
		"	lui	$v0,%hi(g_PlayerEntity) # maspsx-keep\n"
		"	lw	$v0,%lo(g_PlayerEntity)($v0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	beq	$s0,$v0,.L8002B4D4 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lw	$v1,0x0($s0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lb	$v0,0x5($v1) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	beq	$v0,$s1,.L8002B4D4 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	bnez	$v1,.L8002B4CC # maspsx-keep\n"
		"	addiu	$a0,$s0,0x1B4 # maspsx-keep\n"
		"	lw	$v0,0x98($s0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	andi	$v0,$v0,0x40 # maspsx-keep\n"
		"	bnez	$v0,.L8002B4D4 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L8002B4CC: # maspsx-keep\n"
		"	jal	Anim_SetInterpRate # maspsx-keep\n"
		"	addiu	$a1,$zero,0x3C # maspsx-keep\n"
		".L8002B4D4: # maspsx-keep\n"
		"	lw	$s0,0x4($s0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	beqz	$s0,.L8002B568 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	j	.L8002B484 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L8002B4EC: # maspsx-keep\n"
		"	lui	$s0,%hi(g_FieldActorListHead) # maspsx-keep\n"
		"	lw	$s0,%lo(g_FieldActorListHead)($s0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	beqz	$s0,.L8002B568 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lui	$v1,%hi(g_PlayerEntity) # maspsx-keep\n"
		"	lw	$v1,%lo(g_PlayerEntity)($v1) # maspsx-keep\n"
		".L8002B508: # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	beq	$s0,$v1,.L8002B558 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lw	$v0,0x0($s0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	bnez	$v0,.L8002B538 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lw	$v0,0x98($s0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	andi	$v0,$v0,0x40 # maspsx-keep\n"
		"	bnez	$v0,.L8002B558 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L8002B538: # maspsx-keep\n"
		"	lbu	$v0,0x252($s0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	bnez	$v0,.L8002B558 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lw	$v0,0x98($s0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	ori	$v0,$v0,0x10 # maspsx-keep\n"
		"	sw	$v0,0x98($s0) # maspsx-keep\n"
		".L8002B558: # maspsx-keep\n"
		"	lw	$s0,0x4($s0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	bnez	$s0,.L8002B508 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L8002B568: # maspsx-keep\n"
		"	lbu	$v0,g_BattleVictoryStepTimer # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	bnez	$v0,.L8002B8DC # maspsx-keep\n"
		"	addiu	$v0,$v0,-0x1 # maspsx-keep\n"
		"	jal	Pm_StopAllBoth # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	addu	$a0,$zero,$zero # maspsx-keep\n"
		"	jal	Akao_Cmd_21 # maspsx-keep\n"
		"	addiu	$a1,$zero,0xFF # maspsx-keep\n"
		"	lbu	$v0,g_BattlePhaseStep # maspsx-keep\n"
		"	addiu	$v1,$zero,0x1E # maspsx-keep\n"
		"	sb	$v1,g_BattleVictoryStepTimer # maspsx-keep\n"
		"	j	.L8002B830 # maspsx-keep\n"
		"	addiu	$v0,$v0,0x1 # maspsx-keep\n"
		".L8002B5A0: # maspsx-keep\n"
		"	addiu	$a0,$zero,0x78 # maspsx-keep\n"
		"	addiu	$a1,$zero,0x7A # maspsx-keep\n"
		"	lbu	$v0,g_BattleVictoryStepTimer # maspsx-keep\n"
		"	lui	$v1,%hi(g_ActiveDrawSlot) # maspsx-keep\n"
		"	lw	$v1,%lo(g_ActiveDrawSlot)($v1) # maspsx-keep\n"
		"	sll	$v0,$v0,2 # maspsx-keep\n"
		"	subu	$a0,$a0,$v0 # maspsx-keep\n"
		"	sll	$v0,$v1,2 # maspsx-keep\n"
		"	addu	$v0,$v0,$v1 # maspsx-keep\n"
		"	sll	$v0,$v0,3 # maspsx-keep\n"
		"	lui	$at,%hi(D_800BE9F4) # maspsx-keep\n"
		"	addu	$at,$at,$v0 # maspsx-keep\n"
		"	sb	$a0,%lo(D_800BE9F4)($at) # maspsx-keep\n"
		"	lui	$v1,%hi(g_ActiveDrawSlot) # maspsx-keep\n"
		"	lw	$v1,%lo(g_ActiveDrawSlot)($v1) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	sll	$v0,$v1,2 # maspsx-keep\n"
		"	addu	$v0,$v0,$v1 # maspsx-keep\n"
		"	sll	$v0,$v0,3 # maspsx-keep\n"
		"	lui	$at,%hi(D_800BE9F5) # maspsx-keep\n"
		"	addu	$at,$at,$v0 # maspsx-keep\n"
		"	sb	$a0,%lo(D_800BE9F5)($at) # maspsx-keep\n"
		"	lui	$v1,%hi(g_ActiveDrawSlot) # maspsx-keep\n"
		"	lw	$v1,%lo(g_ActiveDrawSlot)($v1) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	sll	$v0,$v1,2 # maspsx-keep\n"
		"	addu	$v0,$v0,$v1 # maspsx-keep\n"
		"	sll	$v0,$v0,3 # maspsx-keep\n"
		"	lui	$v1,%hi(g_BattleHpBarPrimBuf) # maspsx-keep\n"
		"	addiu	$v1,$v1,%lo(g_BattleHpBarPrimBuf) # maspsx-keep\n"
		"	lui	$at,%hi(D_800BE9F6) # maspsx-keep\n"
		"	addu	$at,$at,$v0 # maspsx-keep\n"
		"	sb	$a0,%lo(D_800BE9F6)($at) # maspsx-keep\n"
		"	lui	$a0,%hi(g_ActiveDrawSlot) # maspsx-keep\n"
		"	lw	$a0,%lo(g_ActiveDrawSlot)($a0) # maspsx-keep\n"
		"	lbu	$t0,g_BattleVictoryStepTimer # maspsx-keep\n"
		"	sll	$v0,$a0,2 # maspsx-keep\n"
		"	addu	$v0,$v0,$a0 # maspsx-keep\n"
		"	sll	$v0,$v0,3 # maspsx-keep\n"
		"	addu	$v0,$v0,$v1 # maspsx-keep\n"
		"	andi	$a2,$t0,0xFF # maspsx-keep\n"
		"	sll	$a3,$a2,2 # maspsx-keep\n"
		"	addiu	$a0,$zero,0x64 # maspsx-keep\n"
		"	subu	$a0,$a0,$a3 # maspsx-keep\n"
		"	sll	$v1,$a2,3 # maspsx-keep\n"
		"	addiu	$v1,$v1,0xDC # maspsx-keep\n"
		"	subu	$v1,$v1,$a3 # maspsx-keep\n"
		"	sh	$a0,0x8($v0) # maspsx-keep\n"
		"	sh	$a0,0x18($v0) # maspsx-keep\n"
		"	addiu	$a0,$zero,0x7C # maspsx-keep\n"
		"	sh	$a1,0xA($v0) # maspsx-keep\n"
		"	sh	$v1,0x10($v0) # maspsx-keep\n"
		"	sh	$a1,0x12($v0) # maspsx-keep\n"
		"	sh	$a0,0x1A($v0) # maspsx-keep\n"
		"	sh	$v1,0x20($v0) # maspsx-keep\n"
		"	beqz	$a2,.L8002B694 # maspsx-keep\n"
		"	sh	$a0,0x22($v0) # maspsx-keep\n"
		"	addiu	$v0,$t0,-0x1 # maspsx-keep\n"
		"	sb	$v0,g_BattleVictoryStepTimer # maspsx-keep\n"
		"	j	.L8002B900 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L8002B694: # maspsx-keep\n"
		"	lbu	$v0,g_BattlePhaseStep # maspsx-keep\n"
		"	addiu	$v1,$zero,0x50 # maspsx-keep\n"
		"	sb	$v1,g_BattleVictoryStepTimer # maspsx-keep\n"
		"	j	.L8002B830 # maspsx-keep\n"
		"	addiu	$v0,$v0,0x1 # maspsx-keep\n"
		".L8002B6A8: # maspsx-keep\n"
		"	lbu	$a0,g_BattleVictoryStepTimer # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	sltiu	$v0,$a0,0x1A # maspsx-keep\n"
		"	bnez	$v0,.L8002B730 # maspsx-keep\n"
		"	addiu	$a0,$a0,-0x10 # maspsx-keep\n"
		"	jal	rcos # maspsx-keep\n"
		"	sll	$a0,$a0,4 # maspsx-keep\n"
		"	sll	$v1,$v0,1 # maspsx-keep\n"
		"	addu	$v1,$v1,$v0 # maspsx-keep\n"
		"	sll	$v1,$v1,2 # maspsx-keep\n"
		"	subu	$v1,$v1,$v0 # maspsx-keep\n"
		"	srl	$v1,$v1,11 # maspsx-keep\n"
		"	lui	$a1,%hi(g_BattleHpBarPrimBuf) # maspsx-keep\n"
		"	addiu	$a1,$a1,%lo(g_BattleHpBarPrimBuf) # maspsx-keep\n"
		"	addiu	$a2,$zero,0x64 # maspsx-keep\n"
		"	lui	$a0,%hi(g_ActiveDrawSlot) # maspsx-keep\n"
		"	lw	$a0,%lo(g_ActiveDrawSlot)($a0) # maspsx-keep\n"
		"	andi	$v1,$v1,0xFF # maspsx-keep\n"
		"	sll	$v0,$a0,2 # maspsx-keep\n"
		"	addu	$v0,$v0,$a0 # maspsx-keep\n"
		"	sll	$v0,$v0,3 # maspsx-keep\n"
		"	addu	$v0,$v0,$a1 # maspsx-keep\n"
		"	addiu	$a0,$zero,0x7A # maspsx-keep\n"
		"	subu	$a0,$a0,$v1 # maspsx-keep\n"
		"	addiu	$a1,$zero,0xDC # maspsx-keep\n"
		"	addiu	$v1,$zero,0x7C # maspsx-keep\n"
		"	sh	$a2,0x8($v0) # maspsx-keep\n"
		"	sh	$a0,0xA($v0) # maspsx-keep\n"
		"	sh	$a1,0x10($v0) # maspsx-keep\n"
		"	sh	$a0,0x12($v0) # maspsx-keep\n"
		"	sh	$a2,0x18($v0) # maspsx-keep\n"
		"	sh	$v1,0x1A($v0) # maspsx-keep\n"
		"	j	.L8002B778 # maspsx-keep\n"
		"	sh	$a1,0x20($v0) # maspsx-keep\n"
		".L8002B730: # maspsx-keep\n"
		"	lui	$v1,%hi(g_ActiveDrawSlot) # maspsx-keep\n"
		"	lw	$v1,%lo(g_ActiveDrawSlot)($v1) # maspsx-keep\n"
		"	lui	$a0,%hi(g_BattleHpBarPrimBuf) # maspsx-keep\n"
		"	addiu	$a0,$a0,%lo(g_BattleHpBarPrimBuf) # maspsx-keep\n"
		"	sll	$v0,$v1,2 # maspsx-keep\n"
		"	addu	$v0,$v0,$v1 # maspsx-keep\n"
		"	sll	$v0,$v0,3 # maspsx-keep\n"
		"	addu	$v0,$v0,$a0 # maspsx-keep\n"
		"	addiu	$v1,$zero,0x64 # maspsx-keep\n"
		"	addiu	$a0,$zero,0xDC # maspsx-keep\n"
		"	sh	$v1,0x8($v0) # maspsx-keep\n"
		"	sh	$v1,0xA($v0) # maspsx-keep\n"
		"	sh	$v1,0x12($v0) # maspsx-keep\n"
		"	sh	$v1,0x18($v0) # maspsx-keep\n"
		"	addiu	$v1,$zero,0x7C # maspsx-keep\n"
		"	sh	$a0,0x10($v0) # maspsx-keep\n"
		"	sh	$v1,0x1A($v0) # maspsx-keep\n"
		"	sh	$a0,0x20($v0) # maspsx-keep\n"
		".L8002B778: # maspsx-keep\n"
		"	sh	$v1,0x22($v0) # maspsx-keep\n"
		"	lbu	$v0,g_BattleVictoryStepTimer # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	bnez	$v0,.L8002B8DC # maspsx-keep\n"
		"	addiu	$v0,$v0,-0x1 # maspsx-keep\n"
		"	lui	$a0,%hi(g_PlayerEntity) # maspsx-keep\n"
		"	lw	$a0,%lo(g_PlayerEntity)($a0) # maspsx-keep\n"
		"	addiu	$a1,$zero,0x3C # maspsx-keep\n"
		"	jal	Anim_SetInterpRate # maspsx-keep\n"
		"	addiu	$a0,$a0,0x1B4 # maspsx-keep\n"
		"	lui	$v1,%hi(g_PlayerEntity) # maspsx-keep\n"
		"	lw	$v1,%lo(g_PlayerEntity)($v1) # maspsx-keep\n"
		"	lui	$a0,%hi(g_PlayerBattleEntity) # maspsx-keep\n"
		"	addiu	$a0,$a0,%lo(g_PlayerBattleEntity) # maspsx-keep\n"
		"	lhu	$v0,0x250($v1) # maspsx-keep\n"
		"	addiu	$a1,$zero,0x3C # maspsx-keep\n"
		"	ori	$v0,$v0,0x2 # maspsx-keep\n"
		"	jal	Anim_SetInterpRate # maspsx-keep\n"
		"	sh	$v0,0x250($v1) # maspsx-keep\n"
		"	lbu	$v1,g_BattlePhaseStep # maspsx-keep\n"
		"	addiu	$v0,$zero,0x3C # maspsx-keep\n"
		"	sb	$v0,g_BattleVictoryStepTimer # maspsx-keep\n"
		"	lui	$v0,%hi(D_800B0D88) # maspsx-keep\n"
		"	lhu	$v0,%lo(D_800B0D88)($v0) # maspsx-keep\n"
		"	addiu	$v1,$v1,0x1 # maspsx-keep\n"
		"	ori	$v0,$v0,0x2 # maspsx-keep\n"
		"	lui	$at,%hi(D_800B0D88) # maspsx-keep\n"
		"	sh	$v0,%lo(D_800B0D88)($at) # maspsx-keep\n"
		"	sb	$v1,g_BattlePhaseStep # maspsx-keep\n"
		"	j	.L8002B900 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L8002B7F4: # maspsx-keep\n"
		"	lui	$v0,%hi(g_PlayerEntity) # maspsx-keep\n"
		"	lw	$v0,%lo(g_PlayerEntity)($v0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lbu	$v0,0x252($v0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	bnez	$v0,.L8002B83C # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lui	$v0,%hi(g_BattleEndOverrideFlag) # maspsx-keep\n"
		"	lbu	$v0,%lo(g_BattleEndOverrideFlag)($v0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	bnez	$v0,.L8002B83C # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lbu	$v0,g_BattlePhaseStep # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	addiu	$v0,$v0,0x1 # maspsx-keep\n"
		".L8002B830: # maspsx-keep\n"
		"	sb	$v0,g_BattlePhaseStep # maspsx-keep\n"
		"	j	.L8002B900 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L8002B83C: # maspsx-keep\n"
		"	lui	$a3,%hi(g_BattleHpBarPrimBuf) # maspsx-keep\n"
		"	addiu	$a3,$a3,%lo(g_BattleHpBarPrimBuf) # maspsx-keep\n"
		"	addiu	$a2,$zero,0xDC # maspsx-keep\n"
		"	lbu	$a1,g_BattleVictoryStepTimer # maspsx-keep\n"
		"	lui	$v1,%hi(g_ActiveDrawSlot) # maspsx-keep\n"
		"	lw	$v1,%lo(g_ActiveDrawSlot)($v1) # maspsx-keep\n"
		"	sll	$a1,$a1,1 # maspsx-keep\n"
		"	sll	$v0,$v1,2 # maspsx-keep\n"
		"	addu	$v0,$v0,$v1 # maspsx-keep\n"
		"	sll	$v0,$v0,3 # maspsx-keep\n"
		"	addu	$v0,$v0,$a3 # maspsx-keep\n"
		"	sb	$a1,0x4($v0) # maspsx-keep\n"
		"	lui	$a0,%hi(g_ActiveDrawSlot) # maspsx-keep\n"
		"	lw	$a0,%lo(g_ActiveDrawSlot)($a0) # maspsx-keep\n"
		"	addiu	$v1,$zero,0x64 # maspsx-keep\n"
		"	sh	$v1,0x8($v0) # maspsx-keep\n"
		"	sh	$v1,0xA($v0) # maspsx-keep\n"
		"	sh	$v1,0x12($v0) # maspsx-keep\n"
		"	sh	$v1,0x18($v0) # maspsx-keep\n"
		"	addiu	$v1,$zero,0x7C # maspsx-keep\n"
		"	sh	$a2,0x10($v0) # maspsx-keep\n"
		"	sh	$v1,0x1A($v0) # maspsx-keep\n"
		"	sh	$a2,0x20($v0) # maspsx-keep\n"
		"	sh	$v1,0x22($v0) # maspsx-keep\n"
		"	sll	$v0,$a0,2 # maspsx-keep\n"
		"	addu	$v0,$v0,$a0 # maspsx-keep\n"
		"	sll	$v0,$v0,3 # maspsx-keep\n"
		"	addu	$v0,$v0,$a3 # maspsx-keep\n"
		"	sb	$a1,0x5($v0) # maspsx-keep\n"
		"	lui	$v1,%hi(g_ActiveDrawSlot) # maspsx-keep\n"
		"	lw	$v1,%lo(g_ActiveDrawSlot)($v1) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	sll	$v0,$v1,2 # maspsx-keep\n"
		"	addu	$v0,$v0,$v1 # maspsx-keep\n"
		"	sll	$v0,$v0,3 # maspsx-keep\n"
		"	addu	$v0,$v0,$a3 # maspsx-keep\n"
		"	sb	$a1,0x6($v0) # maspsx-keep\n"
		"	lbu	$v0,g_BattleVictoryStepTimer # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	addiu	$v0,$v0,-0x1 # maspsx-keep\n"
		".L8002B8DC: # maspsx-keep\n"
		"	sb	$v0,g_BattleVictoryStepTimer # maspsx-keep\n"
		"	j	.L8002B900 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L8002B8E8: # maspsx-keep\n"
		"	jal	Battle_SetupPlayerPalette # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	addiu	$v0,$zero,-0x1 # maspsx-keep\n"
		"	sw	$v0,g_BattleModeState # maspsx-keep\n"
		"	jal	Sys_Shutdown # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L8002B900: # maspsx-keep\n"
		"	lui	$a1,%hi(g_ActiveDrawSlot) # maspsx-keep\n"
		"	lw	$a1,%lo(g_ActiveDrawSlot)($a1) # maspsx-keep\n"
		"	lui	$v0,%hi(g_BattleHpBarPrimBuf) # maspsx-keep\n"
		"	addiu	$v0,$v0,%lo(g_BattleHpBarPrimBuf) # maspsx-keep\n"
		"	sll	$v1,$a1,2 # maspsx-keep\n"
		"	addu	$a1,$v1,$a1 # maspsx-keep\n"
		"	sll	$a1,$a1,3 # maspsx-keep\n"
		"	lui	$at,%hi(g_OtBufferTable) # maspsx-keep\n"
		"	addu	$at,$at,$v1 # maspsx-keep\n"
		"	lw	$a0,%lo(g_OtBufferTable)($at) # maspsx-keep\n"
		"	addu	$a1,$a1,$v0 # maspsx-keep\n"
		"	jal	AddPrim # maspsx-keep\n"
		"	addiu	$a0,$a0,0x10 # maspsx-keep\n"
		"	lw	$ra,0x30($sp) # maspsx-keep\n"
		"	lw	$s1,0x2C($sp) # maspsx-keep\n"
		"	lw	$s0,0x28($sp) # maspsx-keep\n"
		"	addiu	$sp,$sp,0x38 # maspsx-keep\n"
		"	jr	$ra # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	.set	macro # maspsx-keep\n"
		"	.set	reorder # maspsx-keep\n"
	);
}
