#include "common.h"

/* MASPSX_FLAGS: --expand-div */
extern struct { char _[0x98]; } D_800B0DD8;
extern u16 D_80093176[];
extern u8 *D_800B0E6C;
extern u8 D_80091A20;
extern u8 D_80091A1C;
extern u8 D_80091A1D;
extern u8 D_80091A1E;
extern volatile u8 D_80091A1F;
extern u32 D_80091A24;
extern u8 D_8009ECD8[];
extern volatile u8 D_8009EE24[];
extern u8 *D_80091A28;

int CdRom_ReadSectorsFromLba(int lba, void *dst, int sectors);
int CdRom_PollReady(void);
int rand(void);
void srand(unsigned int seed);
void Render_LoadFontGlyph(int glyph);

static inline int find_slot(u8 *table)
{
    int found = 0;
    int k;
    u8 *groups = table + 1;
    u8 *slots;
    u8 *entry;
    unsigned int count_offset;

    /* Retain the separate loop-bound reload generated by stock GCC. */
    count_offset = 3;
    for (k = 0; k < table[count_offset]; k++) {
        entry = groups + k;
        if (entry[3] == 2) {
            found = k;
            k = groups[2];
        }
    }
    slots = groups + 0x1B;
    for (k = 0; k < groups[0x1B]; k++) {
        entry = slots + k;
        if (entry[1] == (found & 255)) {
            return k;
        }
    }
    return 255;
}

u8 Render_LoadFontGlyphAlt(void)
{
    u16 *range;
    u8 *state;
    int read_status;
    int poll_status;
    u8 i;
    int forced_slot;
    s16 unique_count;
    int glyph;
    s16 limit;
    u8 duplicate;
    u8 j;

retry_read:
    state = (u8 *)&D_800B0DD8;
    range = D_80093176;
    do {
        read_status = CdRom_ReadSectorsFromLba(*(int *)state + range[0],
                                             *(void **)(state + 0x94),
                                             range[1] - range[0]);
    } while (read_status == -1);

    for (;;) {
        poll_status = CdRom_PollReady();
        if (poll_status == 0) {
            break;
        }
        if (poll_status == -1) {
            goto retry_read;
        }
    }

    D_8009ECD8[0] = D_800B0E6C[0];
    if (D_80091A20 == 0 && D_80091A24 == 0) {
        do {
            D_80091A24 = rand() % 0x7FFF;
        } while (D_80091A24 == 0);
    }

    /* The identical arms retain the stock compiler's branch-delay scheduling. */
    if (D_80091A20) {
        srand(D_80091A24);
    } else {
        srand(D_80091A24);
    }

    unique_count = 0;
    forced_slot = 0;
    for (i = 0; (u8)i < 0x45; i++) {
        if (((u8)i + 2) % 10 == 0) {
            D_8009EE24[(u8)i] = forced_slot;
            forced_slot++;
            continue;
        }

        if ((u8)i + 2 < 10) {
            limit = 0x68;
        } else if ((u8)i + 2 < 20) {
            limit = 0x6D;
        } else {
            limit = 0x71;
        }

        if (D_8009ECD8[0] - 1 < limit) {
            limit = D_8009ECD8[0];
            limit = limit - 1;
        }

        glyph = (rand() % (limit - 7)) + 7;
        D_8009EE24[(u8)i] = glyph;

        if (unique_count < D_8009ECD8[0] - 9) {
            do {
                duplicate = 1;
                for (j = 0; j < i; j++) {
                    if (D_8009EE24[j] == D_8009EE24[(u8)i]) {
                        D_8009EE24[(u8)i] = (rand() % (limit - 7)) + 7;
                        duplicate = 0;
                    }
                }
            } while (duplicate == 0);
        }
        unique_count++;
    }

    Render_LoadFontGlyph(D_8009EE24[0]);

    D_80091A1C = 1;
    D_80091A1D = 2;
    D_80091A1E = D_8009EE24[0];
    D_80091A28 = D_8009ECD8;

    D_80091A1F = find_slot(D_8009ECD8);
    {
        u8 *result = D_80091A28;
        /* This assembler-backed flag is ordinary RAM. The unqualified byte
         * view preserves the lookup's stock-GCC integer promotion. */
        return *(result + *(result + *(u8 *)&D_80091A1F + 0x1D) + 4);
    }
}
