/* MASPSX_FLAGS: --expand-div */
#define ROOMEFFECT_LINE_BURST_FUNC func_8019389C
#define ROOMEFFECT_LINE_BURST_CALLBACK func_80193500
#define ROOMEFFECT_LINE_BURST_TEMPLATE D_8018F1D8
#define ROOMEFFECT_LINE_BURST_ROTATION D_8018F1E0
#include "../room_lib/RoomEffect_LineBurstController.inc"
