/* MASPSX_FLAGS: --expand-div */
#define ROOMEFFECT_LINE_BURST_FUNC func_801939EC
#define ROOMEFFECT_LINE_BURST_CALLBACK func_80193650
#define ROOMEFFECT_LINE_BURST_TEMPLATE D_8018F208
#define ROOMEFFECT_LINE_BURST_ROTATION D_8018F210
#include "../room_lib/RoomEffect_LineBurstController.inc"
