#include "common.h"
#include "pe1/gte.h"

#define ROOMEFFECT_MODEL_BURST_FUNC func_80194EF4
#define ROOMEFFECT_MODEL_BURST_CALLBACK func_80194C54
#define ROOMEFFECT_MODEL_BURST_ROTATION D_8018F1D4
#define ROOMEFFECT_MODEL_BURST_SHADE D_8018F1E0
#define ROOMEFFECT_MODEL_BURST_COLOR_TABLE D_801957BC
#define ROOMEFFECT_MODEL_BURST_ASSET D_80195B70
#define ROOMEFFECT_MODEL_BURST_LAYER D_80195B74
#define ROOMEFFECT_MODEL_BURST_ANCHOR D_80195B68
#define ROOMEFFECT_MODEL_BURST_SLOT 5
#include "../room_lib/RoomEffect_ModelBurstController.inc"
