/* CC1_FLAGS: -G8 */
/* MASPSX_FLAGS: -G8 */
/* Function body emitted as asm() (PSYQ GCC 2.7.2 register
 * allocation / scheduling diverges from the ROM pervasively).
 * Wrapped via maspsx's INCLUDE_ASM hack so the body is passed
 * through verbatim; bare global loads gp-rel via the .extern size
 * hints + `as -G8`. See tools/maspsx/PE1_IMPROVEMENTS.md. */
void __maspsx_include_asm_hack_func_800133E8(void);
void __maspsx_include_asm_hack_func_800133E8(void) {
	__asm__(
		"	.extern	g_TaskNodePool,1 # maspsx-keep\n"
		"	.extern	g_SceneDataTable0,1 # maspsx-keep\n"
		"	.set	noreorder # maspsx-keep\n"
		"	.set	nomacro # maspsx-keep\n"
		"	.globl	Task_WaitAnimRange # maspsx-keep\n"
		"Task_WaitAnimRange: # maspsx-keep\n"
		"	lui	$a0,%hi(g_CurrentEntity) # maspsx-keep\n"
		"	lw	$a0,%lo(g_CurrentEntity)($a0) # maspsx-keep\n"
		"	lw	$v0,g_TaskNodePool # maspsx-keep\n"
		"	lw	$a1,0x14($a0) # maspsx-keep\n"
		"	lhu	$a2,0x12($a0) # maspsx-keep\n"
		"	addiu	$v1,$zero,0x1 # maspsx-keep\n"
		"	sw	$v1,0x10($v0) # maspsx-keep\n"
		"	sra	$v0,$a1,16 # maspsx-keep\n"
		"	beq	$v0,$a2,.L800134F4 # maspsx-keep\n"
		"	sll	$a2,$a2,16 # maspsx-keep\n"
		"	lw	$v0,0x1C($a0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	addu	$a0,$a1,$v0 # maspsx-keep\n"
		"	slt	$v0,$a1,$a2 # maspsx-keep\n"
		"	beqz	$v0,.L80013430 # maspsx-keep\n"
		"	slt	$v0,$a2,$a0 # maspsx-keep\n"
		"	bnez	$v0,.L8001350C # maspsx-keep\n"
		"	addu	$v0,$zero,$zero # maspsx-keep\n"
		".L80013430: # maspsx-keep\n"
		"	slt	$v0,$a2,$a1 # maspsx-keep\n"
		"	beqz	$v0,.L80013444 # maspsx-keep\n"
		"	slt	$v0,$a0,$a2 # maspsx-keep\n"
		"	bnez	$v0,.L8001350C # maspsx-keep\n"
		"	addu	$v0,$zero,$zero # maspsx-keep\n"
		".L80013444: # maspsx-keep\n"
		"	lui	$v0,%hi(g_CurrentEntity) # maspsx-keep\n"
		"	lw	$v0,%lo(g_CurrentEntity)($v0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lbu	$a1,0xF($v0) # maspsx-keep\n"
		"	sra	$v1,$a0,16 # maspsx-keep\n"
		"	slt	$v0,$a1,$v1 # maspsx-keep\n"
		"	beqz	$v0,.L800134A0 # maspsx-keep\n"
		"	addiu	$v0,$a1,0x1 # maspsx-keep\n"
		"	div	$zero,$v1,$v0 # maspsx-keep\n"
		"	bnez	$v0,.L80013474 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	break	7,0 # maspsx-keep\n"
		".L80013474: # maspsx-keep\n"
		"	addiu	$at,$zero,-0x1 # maspsx-keep\n"
		"	bne	$v0,$at,.L8001348C # maspsx-keep\n"
		"	lui	$at,(0x80000000 >> 16) # maspsx-keep\n"
		"	bne	$v1,$at,.L8001348C # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	break	6,0 # maspsx-keep\n"
		".L8001348C: # maspsx-keep\n"
		"	mfhi	$v1 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	sll	$a0,$v1,16 # maspsx-keep\n"
		"	j	.L800134EC # maspsx-keep\n"
		"	slt	$v0,$a2,$a0 # maspsx-keep\n"
		".L800134A0: # maspsx-keep\n"
		"	bgez	$a0,.L800134FC # maspsx-keep\n"
		"	sll	$a1,$a1,16 # maspsx-keep\n"
		"	div	$zero,$v1,$v0 # maspsx-keep\n"
		"	bnez	$v0,.L800134B8 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	break	7,0 # maspsx-keep\n"
		".L800134B8: # maspsx-keep\n"
		"	addiu	$at,$zero,-0x1 # maspsx-keep\n"
		"	bne	$v0,$at,.L800134D0 # maspsx-keep\n"
		"	lui	$at,(0x80000000 >> 16) # maspsx-keep\n"
		"	bne	$v1,$at,.L800134D0 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	break	6,0 # maspsx-keep\n"
		".L800134D0: # maspsx-keep\n"
		"	mfhi	$v1 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	addu	$v0,$v0,$v1 # maspsx-keep\n"
		"	sll	$a0,$v0,16 # maspsx-keep\n"
		"	slt	$v0,$a1,$a2 # maspsx-keep\n"
		"	bnez	$v0,.L800134FC # maspsx-keep\n"
		"	slt	$v0,$a0,$a2 # maspsx-keep\n"
		".L800134EC: # maspsx-keep\n"
		"	beqz	$v0,.L800134FC # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L800134F4: # maspsx-keep\n"
		"	j	.L8001350C # maspsx-keep\n"
		"	addu	$v0,$zero,$zero # maspsx-keep\n"
		".L800134FC: # maspsx-keep\n"
		"	lw	$v1,g_SceneDataTable0 # maspsx-keep\n"
		"	addu	$v0,$zero,$zero # maspsx-keep\n"
		"	addiu	$v1,$v1,-0x8 # maspsx-keep\n"
		"	sw	$v1,g_SceneDataTable0 # maspsx-keep\n"
		".L8001350C: # maspsx-keep\n"
		"	jr	$ra # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	.set	macro # maspsx-keep\n"
		"	.set	reorder # maspsx-keep\n"
	);
}
