#include "common.h"
#include "pe1/room_fx.h"

#define ROOMLIB_DRAW_THREE_PARTICLES_FUNC func_8018FA00
#define ROOMLIB_DRAW_THREE_PARTICLES_TABLE D_8019356C
#define ROOMLIB_DRAW_THREE_PARTICLES_PACKET D_80193638
#define ROOMLIB_DRAW_THREE_PARTICLES_PRIMARY_ALPHA D_80193642
#define ROOMLIB_DRAW_THREE_PARTICLES_FLOOR_ALPHA D_80193632
#define ROOMLIB_DRAW_THREE_PARTICLES_FLOOR_HEIGHT D_800942EC
#include "../room_lib/RoomLib_DrawThreeTransformParticles.inc"
