.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

nonmatching func_80190248, 0x88

glabel func_80190248
    /* 1260 80190248 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 1264 8019024C 1000B0AF */  sw         $s0, 0x10($sp)
    /* 1268 80190250 1400BFAF */  sw         $ra, 0x14($sp)
    /* 126C 80190254 DE7E030C */  jal        func_800DFB78
    /* 1270 80190258 21808000 */   addu      $s0, $a0, $zero
    /* 1274 8019025C 21184000 */  addu       $v1, $v0, $zero
    /* 1278 80190260 01000224 */  addiu      $v0, $zero, 0x1
    /* 127C 80190264 12006210 */  beq        $v1, $v0, .L801902B0
    /* 1280 80190268 02006228 */   slti      $v0, $v1, 0x2
    /* 1284 8019026C 12004010 */  beqz       $v0, .L801902B8
    /* 1288 80190270 00000000 */   nop
    /* 128C 80190274 11006014 */  bnez       $v1, .L801902BC
    /* 1290 80190278 21100000 */   addu      $v0, $zero, $zero
    /* 1294 8019027C 0800028E */  lw         $v0, 0x8($s0)
    /* 1298 80190280 00000000 */  nop
    /* 129C 80190284 0E004290 */  lbu        $v0, 0xE($v0)
    /* 12A0 80190288 00000000 */  nop
    /* 12A4 8019028C 0200422C */  sltiu      $v0, $v0, 0x2
    /* 12A8 80190290 0A004014 */  bnez       $v0, .L801902BC
    /* 12AC 80190294 21100000 */   addu      $v0, $zero, $zero
    /* 12B0 80190298 0C00028E */  lw         $v0, 0xC($s0)
    /* 12B4 8019029C 00000000 */  nop
    /* 12B8 801902A0 09F84000 */  jalr       $v0
    /* 12BC 801902A4 21200002 */   addu      $a0, $s0, $zero
    /* 12C0 801902A8 AF400608 */  j          .L801902BC
    /* 12C4 801902AC 21100000 */   addu      $v0, $zero, $zero
  .L801902B0:
    /* 12C8 801902B0 6242060C */  jal        RoomLib_ResetAndSignalB_80190988
    /* 12CC 801902B4 21200002 */   addu      $a0, $s0, $zero
  .L801902B8:
    /* 12D0 801902B8 21100000 */  addu       $v0, $zero, $zero
  .L801902BC:
    /* 12D4 801902BC 1400BF8F */  lw         $ra, 0x14($sp)
    /* 12D8 801902C0 1000B08F */  lw         $s0, 0x10($sp)
    /* 12DC 801902C4 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 12E0 801902C8 0800E003 */  jr         $ra
    /* 12E4 801902CC 00000000 */   nop
endlabel func_80190248
