/* CC1_FLAGS: -g3 */

/* Function body emitted as asm() (PSYQ GCC 2.7.2 register
 * allocation / scheduling diverges from the ROM pervasively).
 * Wrapped via maspsx's INCLUDE_ASM hack so the body is passed
 * through verbatim; bare global loads gp-rel via the .extern size
 * hints + `as -G8`. See tools/maspsx/PE1_IMPROVEMENTS.md. */
void __maspsx_include_asm_hack_Save_BuildCardFile(void);
void __maspsx_include_asm_hack_Save_BuildCardFile(void) {
	__asm__(
		"	.set	noreorder # maspsx-keep\n"
		"	.set	nomacro # maspsx-keep\n"
		"	.globl	Save_BuildCardFile # maspsx-keep\n"
		"Save_BuildCardFile: # maspsx-keep\n"
		"	addiu	$sp,$sp,-0x28 # maspsx-keep\n"
		"	sw	$s1,0x1C($sp) # maspsx-keep\n"
		"	addu	$s1,$a0,$zero # maspsx-keep\n"
		"	sw	$ra,0x24($sp) # maspsx-keep\n"
		"	sw	$s2,0x20($sp) # maspsx-keep\n"
		"	jal	Str_ResolveDataPtr # maspsx-keep\n"
		"	sw	$s0,0x18($sp) # maspsx-keep\n"
		"	lui	$s0,%hi(g_MemCardIconHeader) # maspsx-keep\n"
		"	addiu	$s0,$s0,%lo(g_MemCardIconHeader) # maspsx-keep\n"
		"	addu	$a0,$s0,$zero # maspsx-keep\n"
		"	addiu	$a1,$zero,0x100 # maspsx-keep\n"
		"	addiu	$v1,$zero,0x2000 # maspsx-keep\n"
		"	lui	$at,%hi(D_800A5D50) # maspsx-keep\n"
		"	sw	$v1,%lo(D_800A5D50)($at) # maspsx-keep\n"
		"	jal	bzero # maspsx-keep\n"
		"	addu	$s2,$v0,$zero # maspsx-keep\n"
		"	lui	$v1,%hi(D_80010F48) # maspsx-keep\n"
		"	lhu	$v1,%lo(D_80010F48)($v1) # maspsx-keep\n"
		"	addiu	$v0,$zero,0x11 # maspsx-keep\n"
		"	lui	$at,%hi(D_800B886A) # maspsx-keep\n"
		"	sb	$v0,%lo(D_800B886A)($at) # maspsx-keep\n"
		"	addiu	$v0,$zero,0x1 # maspsx-keep\n"
		"	lui	$at,%hi(D_800B886B) # maspsx-keep\n"
		"	sb	$v0,%lo(D_800B886B)($at) # maspsx-keep\n"
		"	sh	$v1,0x0($s0) # maspsx-keep\n"
		"	lbu	$a0,0x18($s1) # maspsx-keep\n"
		"	lui	$a1,%hi(g_SavePlayTimeMinutes) # maspsx-keep\n"
		"	lw	$a1,%lo(g_SavePlayTimeMinutes)($a1) # maspsx-keep\n"
		"	jal	Save_FormatTitle # maspsx-keep\n"
		"	addiu	$a0,$a0,-0x40 # maspsx-keep\n"
		"	addiu	$a0,$s0,0x4 # maspsx-keep\n"
		"	jal	strcpy # maspsx-keep\n"
		"	addu	$a1,$v0,$zero # maspsx-keep\n"
		"	lui	$a1,%hi(D_800B88C8) # maspsx-keep\n"
		"	addiu	$a1,$a1,%lo(D_800B88C8) # maspsx-keep\n"
		"	lwl	$v0,0x17($s2) # maspsx-keep\n"
		"	lwr	$v0,0x14($s2) # maspsx-keep\n"
		"	lwl	$v1,0x1B($s2) # maspsx-keep\n"
		"	lwr	$v1,0x18($s2) # maspsx-keep\n"
		"	lwl	$a0,0x1F($s2) # maspsx-keep\n"
		"	lwr	$a0,0x1C($s2) # maspsx-keep\n"
		"	swl	$v0,0x3($a1) # maspsx-keep\n"
		"	swr	$v0,0x0($a1) # maspsx-keep\n"
		"	swl	$v1,0x7($a1) # maspsx-keep\n"
		"	swr	$v1,0x4($a1) # maspsx-keep\n"
		"	swl	$a0,0xB($a1) # maspsx-keep\n"
		"	swr	$a0,0x8($a1) # maspsx-keep\n"
		"	lwl	$v0,0x23($s2) # maspsx-keep\n"
		"	lwr	$v0,0x20($s2) # maspsx-keep\n"
		"	lwl	$v1,0x27($s2) # maspsx-keep\n"
		"	lwr	$v1,0x24($s2) # maspsx-keep\n"
		"	lwl	$a0,0x2B($s2) # maspsx-keep\n"
		"	lwr	$a0,0x28($s2) # maspsx-keep\n"
		"	swl	$v0,0xF($a1) # maspsx-keep\n"
		"	swr	$v0,0xC($a1) # maspsx-keep\n"
		"	swl	$v1,0x13($a1) # maspsx-keep\n"
		"	swr	$v1,0x10($a1) # maspsx-keep\n"
		"	swl	$a0,0x17($a1) # maspsx-keep\n"
		"	swr	$a0,0x14($a1) # maspsx-keep\n"
		"	lwl	$v0,0x2F($s2) # maspsx-keep\n"
		"	lwr	$v0,0x2C($s2) # maspsx-keep\n"
		"	lwl	$v1,0x33($s2) # maspsx-keep\n"
		"	lwr	$v1,0x30($s2) # maspsx-keep\n"
		"	swl	$v0,0x1B($a1) # maspsx-keep\n"
		"	swr	$v0,0x18($a1) # maspsx-keep\n"
		"	swl	$v1,0x1F($a1) # maspsx-keep\n"
		"	swr	$v1,0x1C($a1) # maspsx-keep\n"
		"	addiu	$s0,$s0,0x80 # maspsx-keep\n"
		"	addiu	$a2,$s2,0x40 # maspsx-keep\n"
		"	or	$v0,$a2,$s0 # maspsx-keep\n"
		"	andi	$v0,$v0,0x3 # maspsx-keep\n"
		"	beqz	$v0,.L80040CF8 # maspsx-keep\n"
		"	addiu	$a3,$s2,0xC0 # maspsx-keep\n"
		".L80040CA4: # maspsx-keep\n"
		"	lwl	$v0,0x3($a2) # maspsx-keep\n"
		"	lwr	$v0,0x0($a2) # maspsx-keep\n"
		"	lwl	$v1,0x7($a2) # maspsx-keep\n"
		"	lwr	$v1,0x4($a2) # maspsx-keep\n"
		"	lwl	$a0,0xB($a2) # maspsx-keep\n"
		"	lwr	$a0,0x8($a2) # maspsx-keep\n"
		"	lwl	$a1,0xF($a2) # maspsx-keep\n"
		"	lwr	$a1,0xC($a2) # maspsx-keep\n"
		"	swl	$v0,0x3($s0) # maspsx-keep\n"
		"	swr	$v0,0x0($s0) # maspsx-keep\n"
		"	swl	$v1,0x7($s0) # maspsx-keep\n"
		"	swr	$v1,0x4($s0) # maspsx-keep\n"
		"	swl	$a0,0xB($s0) # maspsx-keep\n"
		"	swr	$a0,0x8($s0) # maspsx-keep\n"
		"	swl	$a1,0xF($s0) # maspsx-keep\n"
		"	swr	$a1,0xC($s0) # maspsx-keep\n"
		"	addiu	$a2,$a2,0x10 # maspsx-keep\n"
		"	bne	$a2,$a3,.L80040CA4 # maspsx-keep\n"
		"	addiu	$s0,$s0,0x10 # maspsx-keep\n"
		"	j	.L80040D24 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L80040CF8: # maspsx-keep\n"
		"	lw	$v0,0x0($a2) # maspsx-keep\n"
		"	lw	$v1,0x4($a2) # maspsx-keep\n"
		"	lw	$a0,0x8($a2) # maspsx-keep\n"
		"	lw	$a1,0xC($a2) # maspsx-keep\n"
		"	sw	$v0,0x0($s0) # maspsx-keep\n"
		"	sw	$v1,0x4($s0) # maspsx-keep\n"
		"	sw	$a0,0x8($s0) # maspsx-keep\n"
		"	sw	$a1,0xC($s0) # maspsx-keep\n"
		"	addiu	$a2,$a2,0x10 # maspsx-keep\n"
		"	bne	$a2,$a3,.L80040CF8 # maspsx-keep\n"
		"	addiu	$s0,$s0,0x10 # maspsx-keep\n"
		".L80040D24: # maspsx-keep\n"
		"	lui	$s0,%hi(g_MemCardFileBuffer) # maspsx-keep\n"
		"	addiu	$s0,$s0,%lo(g_MemCardFileBuffer) # maspsx-keep\n"
		"	addu	$a0,$s0,$zero # maspsx-keep\n"
		"	jal	bzero # maspsx-keep\n"
		"	addiu	$a1,$zero,0x2000 # maspsx-keep\n"
		"	lui	$at,%hi(g_SaveIoCursor) # maspsx-keep\n"
		"	sw	$s0,%lo(g_SaveIoCursor)($at) # maspsx-keep\n"
		"	lui	$a2,%hi(g_MemCardIconHeader) # maspsx-keep\n"
		"	addiu	$a2,$a2,%lo(g_MemCardIconHeader) # maspsx-keep\n"
		"	or	$v0,$a2,$s0 # maspsx-keep\n"
		"	andi	$v0,$v0,0x3 # maspsx-keep\n"
		"	beqz	$v0,.L80040DAC # maspsx-keep\n"
		"	addiu	$a3,$a2,0x100 # maspsx-keep\n"
		".L80040D58: # maspsx-keep\n"
		"	lwl	$v0,0x3($a2) # maspsx-keep\n"
		"	lwr	$v0,0x0($a2) # maspsx-keep\n"
		"	lwl	$v1,0x7($a2) # maspsx-keep\n"
		"	lwr	$v1,0x4($a2) # maspsx-keep\n"
		"	lwl	$a0,0xB($a2) # maspsx-keep\n"
		"	lwr	$a0,0x8($a2) # maspsx-keep\n"
		"	lwl	$a1,0xF($a2) # maspsx-keep\n"
		"	lwr	$a1,0xC($a2) # maspsx-keep\n"
		"	swl	$v0,0x3($s0) # maspsx-keep\n"
		"	swr	$v0,0x0($s0) # maspsx-keep\n"
		"	swl	$v1,0x7($s0) # maspsx-keep\n"
		"	swr	$v1,0x4($s0) # maspsx-keep\n"
		"	swl	$a0,0xB($s0) # maspsx-keep\n"
		"	swr	$a0,0x8($s0) # maspsx-keep\n"
		"	swl	$a1,0xF($s0) # maspsx-keep\n"
		"	swr	$a1,0xC($s0) # maspsx-keep\n"
		"	addiu	$a2,$a2,0x10 # maspsx-keep\n"
		"	bne	$a2,$a3,.L80040D58 # maspsx-keep\n"
		"	addiu	$s0,$s0,0x10 # maspsx-keep\n"
		"	j	.L80040DD8 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L80040DAC: # maspsx-keep\n"
		"	lw	$v0,0x0($a2) # maspsx-keep\n"
		"	lw	$v1,0x4($a2) # maspsx-keep\n"
		"	lw	$a0,0x8($a2) # maspsx-keep\n"
		"	lw	$a1,0xC($a2) # maspsx-keep\n"
		"	sw	$v0,0x0($s0) # maspsx-keep\n"
		"	sw	$v1,0x4($s0) # maspsx-keep\n"
		"	sw	$a0,0x8($s0) # maspsx-keep\n"
		"	sw	$a1,0xC($s0) # maspsx-keep\n"
		"	addiu	$a2,$a2,0x10 # maspsx-keep\n"
		"	bne	$a2,$a3,.L80040DAC # maspsx-keep\n"
		"	addiu	$s0,$s0,0x10 # maspsx-keep\n"
		".L80040DD8: # maspsx-keep\n"
		"	lui	$v0,%hi(g_SaveIoCursor) # maspsx-keep\n"
		"	lw	$v0,%lo(g_SaveIoCursor)($v0) # maspsx-keep\n"
		"	lui	$a2,%hi(g_SaveRuntimeState) # maspsx-keep\n"
		"	addiu	$a2,$a2,%lo(g_SaveRuntimeState) # maspsx-keep\n"
		"	addiu	$v0,$v0,0x100 # maspsx-keep\n"
		"	addu	$a3,$v0,$zero # maspsx-keep\n"
		"	or	$v0,$a3,$a2 # maspsx-keep\n"
		"	andi	$v0,$v0,0x3 # maspsx-keep\n"
		"	lui	$at,%hi(g_SaveIoCursor) # maspsx-keep\n"
		"	sw	$a3,%lo(g_SaveIoCursor)($at) # maspsx-keep\n"
		"	beqz	$v0,.L80040E5C # maspsx-keep\n"
		"	addiu	$t0,$a2,0x12E0 # maspsx-keep\n"
		".L80040E08: # maspsx-keep\n"
		"	lwl	$v0,0x3($a2) # maspsx-keep\n"
		"	lwr	$v0,0x0($a2) # maspsx-keep\n"
		"	lwl	$v1,0x7($a2) # maspsx-keep\n"
		"	lwr	$v1,0x4($a2) # maspsx-keep\n"
		"	lwl	$a0,0xB($a2) # maspsx-keep\n"
		"	lwr	$a0,0x8($a2) # maspsx-keep\n"
		"	lwl	$a1,0xF($a2) # maspsx-keep\n"
		"	lwr	$a1,0xC($a2) # maspsx-keep\n"
		"	swl	$v0,0x3($a3) # maspsx-keep\n"
		"	swr	$v0,0x0($a3) # maspsx-keep\n"
		"	swl	$v1,0x7($a3) # maspsx-keep\n"
		"	swr	$v1,0x4($a3) # maspsx-keep\n"
		"	swl	$a0,0xB($a3) # maspsx-keep\n"
		"	swr	$a0,0x8($a3) # maspsx-keep\n"
		"	swl	$a1,0xF($a3) # maspsx-keep\n"
		"	swr	$a1,0xC($a3) # maspsx-keep\n"
		"	addiu	$a2,$a2,0x10 # maspsx-keep\n"
		"	bne	$a2,$t0,.L80040E08 # maspsx-keep\n"
		"	addiu	$a3,$a3,0x10 # maspsx-keep\n"
		"	j	.L80040E88 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L80040E5C: # maspsx-keep\n"
		"	lw	$v0,0x0($a2) # maspsx-keep\n"
		"	lw	$v1,0x4($a2) # maspsx-keep\n"
		"	lw	$a0,0x8($a2) # maspsx-keep\n"
		"	lw	$a1,0xC($a2) # maspsx-keep\n"
		"	sw	$v0,0x0($a3) # maspsx-keep\n"
		"	sw	$v1,0x4($a3) # maspsx-keep\n"
		"	sw	$a0,0x8($a3) # maspsx-keep\n"
		"	sw	$a1,0xC($a3) # maspsx-keep\n"
		"	addiu	$a2,$a2,0x10 # maspsx-keep\n"
		"	bne	$a2,$t0,.L80040E5C # maspsx-keep\n"
		"	addiu	$a3,$a3,0x10 # maspsx-keep\n"
		".L80040E88: # maspsx-keep\n"
		"	lwl	$v0,0x3($a2) # maspsx-keep\n"
		"	lwr	$v0,0x0($a2) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	swl	$v0,0x3($a3) # maspsx-keep\n"
		"	swr	$v0,0x0($a3) # maspsx-keep\n"
		"	lui	$v0,%hi(g_SaveIoCursor) # maspsx-keep\n"
		"	lw	$v0,%lo(g_SaveIoCursor)($v0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	addiu	$v0,$v0,0x12E4 # maspsx-keep\n"
		"	lui	$at,%hi(g_SaveIoCursor) # maspsx-keep\n"
		"	sw	$v0,%lo(g_SaveIoCursor)($at) # maspsx-keep\n"
		"	jal	Save_SerializeTail # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lui	$a2,%hi(g_MemCardFileBuffer) # maspsx-keep\n"
		"	addiu	$a2,$a2,%lo(g_MemCardFileBuffer) # maspsx-keep\n"
		"	ori	$v1,$zero,0xFFFF # maspsx-keep\n"
		"	addu	$a1,$zero,$zero # maspsx-keep\n"
		"	andi	$v0,$a1,0xFFFF # maspsx-keep\n"
		".L80040ED0: # maspsx-keep\n"
		"	addu	$v0,$a2,$v0 # maspsx-keep\n"
		"	lbu	$v0,0x0($v0) # maspsx-keep\n"
		"	addu	$a0,$zero,$zero # maspsx-keep\n"
		"	sll	$v0,$v0,8 # maspsx-keep\n"
		"	xor	$v1,$v1,$v0 # maspsx-keep\n"
		"	andi	$v0,$v1,0x8000 # maspsx-keep\n"
		".L80040EE8: # maspsx-keep\n"
		"	beqz	$v0,.L80040EF8 # maspsx-keep\n"
		"	sll	$v0,$v1,1 # maspsx-keep\n"
		"	j	.L80040EFC # maspsx-keep\n"
		"	xori	$v1,$v0,0x1021 # maspsx-keep\n"
		".L80040EF8: # maspsx-keep\n"
		"	sll	$v1,$v1,1 # maspsx-keep\n"
		".L80040EFC: # maspsx-keep\n"
		"	addiu	$a0,$a0,0x1 # maspsx-keep\n"
		"	andi	$v0,$a0,0xFFFF # maspsx-keep\n"
		"	sltiu	$v0,$v0,0x8 # maspsx-keep\n"
		"	bnez	$v0,.L80040EE8 # maspsx-keep\n"
		"	andi	$v0,$v1,0x8000 # maspsx-keep\n"
		"	addiu	$a1,$a1,0x1 # maspsx-keep\n"
		"	andi	$v0,$a1,0xFFFF # maspsx-keep\n"
		"	sltiu	$v0,$v0,0x2000 # maspsx-keep\n"
		"	bnez	$v0,.L80040ED0 # maspsx-keep\n"
		"	andi	$v0,$a1,0xFFFF # maspsx-keep\n"
		"	nor	$v0,$zero,$v1 # maspsx-keep\n"
		"	lui	$v1,%hi(g_SaveIoCursor) # maspsx-keep\n"
		"	lw	$v1,%lo(g_SaveIoCursor)($v1) # maspsx-keep\n"
		"	andi	$v0,$v0,0xFFFF # maspsx-keep\n"
		"	sw	$v0,0x10($sp) # maspsx-keep\n"
		"	lwl	$v0,0x13($sp) # maspsx-keep\n"
		"	lwr	$v0,0x10($sp) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	swl	$v0,0x3($v1) # maspsx-keep\n"
		"	swr	$v0,0x0($v1) # maspsx-keep\n"
		"	lui	$v1,%hi(g_SaveIoCursor) # maspsx-keep\n"
		"	lw	$v1,%lo(g_SaveIoCursor)($v1) # maspsx-keep\n"
		"	addu	$v0,$zero,$zero # maspsx-keep\n"
		"	addiu	$v1,$v1,0x4 # maspsx-keep\n"
		"	lui	$at,%hi(g_SaveIoCursor) # maspsx-keep\n"
		"	sw	$v1,%lo(g_SaveIoCursor)($at) # maspsx-keep\n"
		"	lw	$ra,0x24($sp) # maspsx-keep\n"
		"	lw	$s2,0x20($sp) # maspsx-keep\n"
		"	lw	$s1,0x1C($sp) # maspsx-keep\n"
		"	lw	$s0,0x18($sp) # maspsx-keep\n"
		"	addiu	$sp,$sp,0x28 # maspsx-keep\n"
		"	jr	$ra # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	.set	macro # maspsx-keep\n"
		"	.set	reorder # maspsx-keep\n"
	);
}
