/* CC1_FLAGS: -g3 */

/* Function body emitted as asm() (PSYQ GCC 2.7.2 register
 * allocation / scheduling diverges from the ROM pervasively).
 * Wrapped via maspsx's INCLUDE_ASM hack so the body is passed
 * through verbatim; bare global loads gp-rel via the .extern size
 * hints + `as -G8`. See tools/maspsx/PE1_IMPROVEMENTS.md. */
void __maspsx_include_asm_hack_Save_StartWriteSlot(void);
void __maspsx_include_asm_hack_Save_StartWriteSlot(void) {
	__asm__(
		"	.set	noreorder # maspsx-keep\n"
		"	.set	nomacro # maspsx-keep\n"
		"	.globl	Save_StartWriteSlot # maspsx-keep\n"
		"Save_StartWriteSlot: # maspsx-keep\n"
		"	addiu	$sp,$sp,-0x30 # maspsx-keep\n"
		"	sw	$s0,0x18($sp) # maspsx-keep\n"
		"	sll	$v0,$a0,5 # maspsx-keep\n"
		"	addu	$v0,$v0,$a0 # maspsx-keep\n"
		"	sll	$v0,$v0,2 # maspsx-keep\n"
		"	subu	$v0,$v0,$a0 # maspsx-keep\n"
		"	sll	$v0,$v0,3 # maspsx-keep\n"
		"	lui	$v1,%hi(g_MemCardPortStates) # maspsx-keep\n"
		"	addiu	$v1,$v1,%lo(g_MemCardPortStates) # maspsx-keep\n"
		"	sw	$s1,0x1C($sp) # maspsx-keep\n"
		"	addu	$s1,$v0,$v1 # maspsx-keep\n"
		"	sw	$ra,0x28($sp) # maspsx-keep\n"
		"	sw	$s3,0x24($sp) # maspsx-keep\n"
		"	sw	$s2,0x20($sp) # maspsx-keep\n"
		"	lbu	$s2,0x0($s1) # maspsx-keep\n"
		"	addiu	$v0,$zero,0x1 # maspsx-keep\n"
		"	bne	$s2,$v0,.L80042150 # maspsx-keep\n"
		"	addu	$s0,$a1,$zero # maspsx-keep\n"
		"	sll	$v0,$s0,4 # maspsx-keep\n"
		"	addu	$v0,$v0,$s0 # maspsx-keep\n"
		"	sll	$v0,$v0,2 # maspsx-keep\n"
		"	addiu	$v0,$v0,0x1C # maspsx-keep\n"
		"	jal	MemCard_CloseAll # maspsx-keep\n"
		"	addu	$s3,$s1,$v0 # maspsx-keep\n"
		"	jal	func_8005C25C # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lbu	$v0,0x0($s3) # maspsx-keep\n"
		"	lbu	$v1,0xA($s1) # maspsx-keep\n"
		"	bne	$v0,$s2,.L8004209C # maspsx-keep\n"
		"	addiu	$v0,$v1,0x1 # maspsx-keep\n"
		"	addu	$v0,$v1,$zero # maspsx-keep\n"
		".L8004209C: # maspsx-keep\n"
		"	lui	$a0,%hi(g_MemCardFilenameBuf) # maspsx-keep\n"
		"	addiu	$a0,$a0,%lo(g_MemCardFilenameBuf) # maspsx-keep\n"
		"	sb	$s0,0x3($s1) # maspsx-keep\n"
		"	andi	$v1,$s0,0xFF # maspsx-keep\n"
		"	sb	$v0,0xA($s1) # maspsx-keep\n"
		"	sll	$v0,$v1,4 # maspsx-keep\n"
		"	addu	$v0,$v0,$v1 # maspsx-keep\n"
		"	sll	$v0,$v0,2 # maspsx-keep\n"
		"	addu	$v0,$s1,$v0 # maspsx-keep\n"
		"	addiu	$v1,$v1,0x41 # maspsx-keep\n"
		"	lui	$a2,%hi(g_MemCardPortStates) # maspsx-keep\n"
		"	addiu	$a2,$a2,%lo(g_MemCardPortStates) # maspsx-keep\n"
		"	lbu	$a3,0x45($v0) # maspsx-keep\n"
		"	lui	$a1,%hi(g_MemCardFilenameFormatPtr) # maspsx-keep\n"
		"	lw	$a1,%lo(g_MemCardFilenameFormatPtr)($a1) # maspsx-keep\n"
		"	sltu	$a2,$a2,$s1 # maspsx-keep\n"
		"	sw	$v1,0x10($sp) # maspsx-keep\n"
		"	jal	Square_Vsprintf # maspsx-keep\n"
		"	addiu	$a3,$a3,0x30 # maspsx-keep\n"
		"	lui	$a0,%hi(g_MemCardFilenameBuf) # maspsx-keep\n"
		"	addiu	$a0,$a0,%lo(g_MemCardFilenameBuf) # maspsx-keep\n"
		"	jal	Save_BuildCardFile # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	addiu	$a0,$zero,0x1 # maspsx-keep\n"
		"	addiu	$v0,$zero,0x2000 # maspsx-keep\n"
		"	sb	$s0,0x5($s1) # maspsx-keep\n"
		"	sb	$zero,0x6($s1) # maspsx-keep\n"
		"	sb	$zero,0x1($s3) # maspsx-keep\n"
		"	sh	$v0,0x14($s1) # maspsx-keep\n"
		"	addiu	$v0,$zero,0xA # maspsx-keep\n"
		"	sh	$v0,0x16($s1) # maspsx-keep\n"
		"	addiu	$v0,$zero,0x2000 # maspsx-keep\n"
		"	sb	$a0,0x1($s1) # maspsx-keep\n"
		"	sb	$a0,0x7($s1) # maspsx-keep\n"
		"	lui	$at,%hi(g_MemCardActiveState) # maspsx-keep\n"
		"	sw	$s1,%lo(g_MemCardActiveState)($at) # maspsx-keep\n"
		"	lui	$at,%hi(g_MemCardActiveBytesRemaining) # maspsx-keep\n"
		"	sw	$v0,%lo(g_MemCardActiveBytesRemaining)($at) # maspsx-keep\n"
		"	lbu	$v1,0x0($s3) # maspsx-keep\n"
		"	addiu	$v0,$zero,0x1 # maspsx-keep\n"
		"	bne	$v1,$v0,.L80042148 # maspsx-keep\n"
		"	addiu	$a1,$zero,0x4 # maspsx-keep\n"
		"	addiu	$a1,$zero,0xB # maspsx-keep\n"
		".L80042148: # maspsx-keep\n"
		"	sb	$a1,0xB($s1) # maspsx-keep\n"
		"	sb	$a0,0x0($s3) # maspsx-keep\n"
		".L80042150: # maspsx-keep\n"
		"	lw	$ra,0x28($sp) # maspsx-keep\n"
		"	lw	$s3,0x24($sp) # maspsx-keep\n"
		"	lw	$s2,0x20($sp) # maspsx-keep\n"
		"	lw	$s1,0x1C($sp) # maspsx-keep\n"
		"	lw	$s0,0x18($sp) # maspsx-keep\n"
		"	addiu	$sp,$sp,0x30 # maspsx-keep\n"
		"	jr	$ra # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	.set	macro # maspsx-keep\n"
		"	.set	reorder # maspsx-keep\n"
	);
}
