.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.4 */

nonmatching SeqOp_NoteOnWithPitchSlide, 0x134

glabel SeqOp_NoteOnWithPitchSlide
    /* 81620 80090E20 E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 81624 80090E24 21308000 */  addu       $a2, $a0, $zero
    /* 81628 80090E28 1000BFAF */  sw         $ra, 0x10($sp)
    /* 8162C 80090E2C 0000C28C */  lw         $v0, 0x0($a2)
    /* 81630 80090E30 00000000 */  nop
    /* 81634 80090E34 01004324 */  addiu      $v1, $v0, 0x1
    /* 81638 80090E38 0000C3AC */  sw         $v1, 0x0($a2)
    /* 8163C 80090E3C 00004290 */  lbu        $v0, 0x0($v0)
    /* 81640 80090E40 00000000 */  nop
    /* 81644 80090E44 03004014 */  bnez       $v0, .L80090E54
    /* 81648 80090E48 6000C2A4 */   sh        $v0, 0x60($a2)
    /* 8164C 80090E4C 00010224 */  addiu      $v0, $zero, 0x100
    /* 81650 80090E50 6000C2A4 */  sh         $v0, 0x60($a2)
  .L80090E54:
    /* 81654 80090E54 0000C38C */  lw         $v1, 0x0($a2)
    /* 81658 80090E58 5E00C494 */  lhu        $a0, 0x5E($a2)
    /* 8165C 80090E5C 01006224 */  addiu      $v0, $v1, 0x1
    /* 81660 80090E60 00FF8430 */  andi       $a0, $a0, 0xFF00
    /* 81664 80090E64 0000C2AC */  sw         $v0, 0x0($a2)
    /* 81668 80090E68 00006290 */  lbu        $v0, 0x0($v1)
    /* 8166C 80090E6C 6000C394 */  lhu        $v1, 0x60($a2)
    /* 81670 80090E70 00160200 */  sll        $v0, $v0, 24
    /* 81674 80090E74 03140200 */  sra        $v0, $v0, 16
    /* 81678 80090E78 23104400 */  subu       $v0, $v0, $a0
    /* 8167C 80090E7C 1A004300 */  div        $zero, $v0, $v1
    /* 81680 80090E80 02006014 */  bnez       $v1, .L80090E8C
    /* 81684 80090E84 00000000 */   nop
    /* 81688 80090E88 0D000700 */  break      7
  .L80090E8C:
    /* 8168C 80090E8C FFFF0124 */  addiu      $at, $zero, -0x1
    /* 81690 80090E90 04006114 */  bne        $v1, $at, .L80090EA4
    /* 81694 80090E94 0080013C */   lui       $at, (0x80000000 >> 16)
    /* 81698 80090E98 02004114 */  bne        $v0, $at, .L80090EA4
    /* 8169C 80090E9C 00000000 */   nop
    /* 816A0 80090EA0 0D000600 */  break      6
  .L80090EA4:
    /* 816A4 80090EA4 12100000 */  mflo       $v0
    /* 816A8 80090EA8 3800C38C */  lw         $v1, 0x38($a2)
    /* 816AC 80090EAC 5E00C4A4 */  sh         $a0, 0x5E($a2)
    /* 816B0 80090EB0 00086330 */  andi       $v1, $v1, 0x800
    /* 816B4 80090EB4 21006014 */  bnez       $v1, .L80090F3C
    /* 816B8 80090EB8 D600C2A4 */   sh        $v0, 0xD6($a2)
    /* 816BC 80090EBC 21380000 */  addu       $a3, $zero, $zero
    /* 816C0 80090EC0 01000424 */  addiu      $a0, $zero, 0x1
    /* 816C4 80090EC4 0A80023C */  lui        $v0, %hi(g_AkaoCurTrack)
    /* 816C8 80090EC8 C8D2428C */  lw         $v0, %lo(g_AkaoCurTrack)($v0)
    /* 816CC 80090ECC FF00083C */  lui        $t0, (0xFFFFFF >> 16)
    /* 816D0 80090ED0 0400438C */  lw         $v1, 0x4($v0)
    /* 816D4 80090ED4 3000428C */  lw         $v0, 0x30($v0)
    /* 816D8 80090ED8 FFFF0835 */  ori        $t0, $t0, (0xFFFFFF & 0xFFFF)
    /* 816DC 80090EDC 25186200 */  or         $v1, $v1, $v0
  .L80090EE0:
    /* 816E0 80090EE0 24106400 */  and        $v0, $v1, $a0
    /* 816E4 80090EE4 06004010 */  beqz       $v0, .L80090F00
    /* 816E8 80090EE8 FF00023C */   lui       $v0, (0xFFFFFF >> 16)
    /* 816EC 80090EEC 40200400 */  sll        $a0, $a0, 1
    /* 816F0 80090EF0 24108800 */  and        $v0, $a0, $t0
    /* 816F4 80090EF4 FAFF4014 */  bnez       $v0, .L80090EE0
    /* 816F8 80090EF8 0100E724 */   addiu     $a3, $a3, 0x1
    /* 816FC 80090EFC FF00023C */  lui        $v0, (0xFFFFFF >> 16)
  .L80090F00:
    /* 81700 80090F00 FFFF4234 */  ori        $v0, $v0, (0xFFFFFF & 0xFFFF)
    /* 81704 80090F04 24108200 */  and        $v0, $a0, $v0
    /* 81708 80090F08 0C004010 */  beqz       $v0, .L80090F3C
    /* 8170C 80090F0C 00000000 */   nop
    /* 81710 80090F10 0A80023C */  lui        $v0, %hi(g_AkaoCurTrack)
    /* 81714 80090F14 C8D2428C */  lw         $v0, %lo(g_AkaoCurTrack)($v0)
    /* 81718 80090F18 00000000 */  nop
    /* 8171C 80090F1C 3000438C */  lw         $v1, 0x30($v0)
    /* 81720 80090F20 00000000 */  nop
    /* 81724 80090F24 25186400 */  or         $v1, $v1, $a0
    /* 81728 80090F28 300043AC */  sw         $v1, 0x30($v0)
    /* 8172C 80090F2C 3800C28C */  lw         $v0, 0x38($a2)
    /* 81730 80090F30 5C00C7A4 */  sh         $a3, 0x5C($a2)
    /* 81734 80090F34 00084234 */  ori        $v0, $v0, 0x800
    /* 81738 80090F38 3800C2AC */  sw         $v0, 0x38($a2)
  .L80090F3C:
    /* 8173C 80090F3C E840020C */  jal        SeqOp_SetTrack38Mask
    /* 81740 80090F40 2120C000 */   addu      $a0, $a2, $zero
    /* 81744 80090F44 1000BF8F */  lw         $ra, 0x10($sp)
    /* 81748 80090F48 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 8174C 80090F4C 0800E003 */  jr         $ra
    /* 81750 80090F50 00000000 */   nop
endlabel SeqOp_NoteOnWithPitchSlide
