.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.4 */

nonmatching Spu_UploadStreamBlockB, 0x110

glabel Spu_UploadStreamBlockB
    /* 77DFC 800875FC D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* 77E00 80087600 2400B5AF */  sw         $s5, 0x24($sp)
    /* 77E04 80087604 21A88000 */  addu       $s5, $a0, $zero
    /* 77E08 80087608 1000B0AF */  sw         $s0, 0x10($sp)
    /* 77E0C 8008760C 2180A000 */  addu       $s0, $a1, $zero
    /* 77E10 80087610 FEFF0224 */  addiu      $v0, $zero, -0x2
    /* 77E14 80087614 2410A202 */  and        $v0, $s5, $v0
    /* 77E18 80087618 2800BFAF */  sw         $ra, 0x28($sp)
    /* 77E1C 8008761C 2000B4AF */  sw         $s4, 0x20($sp)
    /* 77E20 80087620 1C00B3AF */  sw         $s3, 0x1C($sp)
    /* 77E24 80087624 1800B2AF */  sw         $s2, 0x18($sp)
    /* 77E28 80087628 03004010 */  beqz       $v0, .L80087638
    /* 77E2C 8008762C 1400B1AF */   sw        $s1, 0x14($sp)
    /* 77E30 80087630 B91D0208 */  j          .L800876E4
    /* 77E34 80087634 01000224 */   addiu     $v0, $zero, 0x1
  .L80087638:
    /* 77E38 80087638 2114020C */  jal        Spu_ValidateSampleHeader
    /* 77E3C 8008763C 21200002 */   addu      $a0, $s0, $zero
    /* 77E40 80087640 28004014 */  bnez       $v0, .L800876E4
    /* 77E44 80087644 FFFF0224 */   addiu     $v0, $zero, -0x1
    /* 77E48 80087648 14001026 */  addiu      $s0, $s0, 0x14
    /* 77E4C 8008764C 0000128E */  lw         $s2, 0x0($s0)
    /* 77E50 80087650 04001026 */  addiu      $s0, $s0, 0x4
    /* 77E54 80087654 0000028E */  lw         $v0, 0x0($s0)
    /* 77E58 80087658 04001026 */  addiu      $s0, $s0, 0x4
    /* 77E5C 8008765C 0000138E */  lw         $s3, 0x0($s0)
    /* 77E60 80087660 00000000 */  nop
    /* 77E64 80087664 03006016 */  bnez       $s3, .L80087674
    /* 77E68 80087668 23986202 */   subu      $s3, $s3, $v0
    /* 77E6C 8008766C 00011324 */  addiu      $s3, $zero, 0x100
    /* 77E70 80087670 23986202 */  subu       $s3, $s3, $v0
  .L80087674:
    /* 77E74 80087674 24001126 */  addiu      $s1, $s0, 0x24
    /* 77E78 80087678 80111300 */  sll        $v0, $s3, 6
    /* 77E7C 8008767C 21802202 */  addu       $s0, $s1, $v0
    /* 77E80 80087680 0600033C */  lui        $v1, (0x68000 >> 16)
    /* 77E84 80087684 00806334 */  ori        $v1, $v1, (0x68000 & 0xFFFF)
    /* 77E88 80087688 40131500 */  sll        $v0, $s5, 13
    /* 77E8C 8008768C 21A04300 */  addu       $s4, $v0, $v1
    /* 77E90 80087690 AD17020C */  jal        Spu_WriteRegChecked
    /* 77E94 80087694 21208002 */   addu      $a0, $s4, $zero
    /* 77E98 80087698 21200002 */  addu       $a0, $s0, $zero
    /* 77E9C 8008769C 3D14020C */  jal        Spu_UploadWithPrepare
    /* 77EA0 800876A0 21284002 */   addu      $a1, $s2, $zero
    /* 77EA4 800876A4 21202002 */  addu       $a0, $s1, $zero
    /* 77EA8 800876A8 21288002 */  addu       $a1, $s4, $zero
    /* 77EAC 800876AC 0B28020C */  jal        Spu_RebaseStreamAddrs
    /* 77EB0 800876B0 21306002 */   addu      $a2, $s3, $zero
    /* 77EB4 800876B4 80A21500 */  sll        $s4, $s5, 10
    /* 77EB8 800876B8 0B80023C */  lui        $v0, %hi(D_800B4900)
    /* 77EBC 800876BC 00494224 */  addiu      $v0, $v0, %lo(D_800B4900)
    /* 77EC0 800876C0 21208202 */  addu       $a0, $s4, $v0
    /* 77EC4 800876C4 00911300 */  sll        $s2, $s3, 4
  .L800876C8:
    /* 77EC8 800876C8 FFFF5226 */  addiu      $s2, $s2, -0x1
    /* 77ECC 800876CC 0000228E */  lw         $v0, 0x0($s1)
    /* 77ED0 800876D0 04003126 */  addiu      $s1, $s1, 0x4
    /* 77ED4 800876D4 000082AC */  sw         $v0, 0x0($a0)
    /* 77ED8 800876D8 FBFF4016 */  bnez       $s2, .L800876C8
    /* 77EDC 800876DC 04008424 */   addiu     $a0, $a0, 0x4
    /* 77EE0 800876E0 21100000 */  addu       $v0, $zero, $zero
  .L800876E4:
    /* 77EE4 800876E4 2800BF8F */  lw         $ra, 0x28($sp)
    /* 77EE8 800876E8 2400B58F */  lw         $s5, 0x24($sp)
    /* 77EEC 800876EC 2000B48F */  lw         $s4, 0x20($sp)
    /* 77EF0 800876F0 1C00B38F */  lw         $s3, 0x1C($sp)
    /* 77EF4 800876F4 1800B28F */  lw         $s2, 0x18($sp)
    /* 77EF8 800876F8 1400B18F */  lw         $s1, 0x14($sp)
    /* 77EFC 800876FC 1000B08F */  lw         $s0, 0x10($sp)
    /* 77F00 80087700 3000BD27 */  addiu      $sp, $sp, 0x30
    /* 77F04 80087704 0800E003 */  jr         $ra
    /* 77F08 80087708 00000000 */   nop
endlabel Spu_UploadStreamBlockB
