#include "common.h"
#include "pe1/room_fx.h"

#define ROOMLIB_DRAW_THREE_PARTICLES_FUNC func_8018F828
#define ROOMLIB_DRAW_THREE_PARTICLES_TABLE D_80190078
#define ROOMLIB_DRAW_THREE_PARTICLES_PACKET D_80190098
#define ROOMLIB_DRAW_THREE_PARTICLES_PRIMARY_ALPHA D_801900A2
#define ROOMLIB_DRAW_THREE_PARTICLES_FLOOR_ALPHA D_80190092
#define ROOMLIB_DRAW_THREE_PARTICLES_FLOOR_HEIGHT D_800942EC
#include "../room_lib/RoomLib_DrawThreeTransformParticles.inc"
