#define ROOMEFFECT_LIFTED_SPARK_FUNC func_801955A0
#define ROOMEFFECT_LIFTED_SPARK_ROTATION D_8018F1D4
#define ROOMEFFECT_LIFTED_SPARK_COLOR_TABLE D_80195F78
#include "../room_lib/RoomEffect_LiftedSparkCallback.inc"
