#include "common.h"
#include "pe1/room_fx.h"

#define ROOMLIB_DRAW_THREE_PARTICLES_FUNC func_8018FA38
#define ROOMLIB_DRAW_THREE_PARTICLES_TABLE D_801946C0
#define ROOMLIB_DRAW_THREE_PARTICLES_PACKET D_80194868
#define ROOMLIB_DRAW_THREE_PARTICLES_PRIMARY_ALPHA D_80194872
#define ROOMLIB_DRAW_THREE_PARTICLES_FLOOR_ALPHA D_80194862
#define ROOMLIB_DRAW_THREE_PARTICLES_FLOOR_HEIGHT g_FrameCount16
#include "../room_lib/RoomLib_DrawThreeTransformParticles.inc"
