.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.4 */

nonmatching CdRom_InitDsReadSystem, 0x144

glabel CdRom_InitDsReadSystem
    /* 6F414 8007EC14 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 6F418 8007EC18 1800BFAF */  sw         $ra, 0x18($sp)
    /* 6F41C 8007EC1C 1400B1AF */  sw         $s1, 0x14($sp)
    /* 6F420 8007EC20 5002020C */  jal        CdRom_IsDsReadSystemEnabled
    /* 6F424 8007EC24 1000B0AF */   sw        $s0, 0x10($sp)
    /* 6F428 8007EC28 46004014 */  bnez       $v0, .L8007ED44
    /* 6F42C 8007EC2C 21100000 */   addu      $v0, $zero, $zero
    /* 6F430 8007EC30 21180000 */  addu       $v1, $zero, $zero
    /* 6F434 8007EC34 0C80023C */  lui        $v0, %hi(D_800B8AB0)
    /* 6F438 8007EC38 B08A4224 */  addiu      $v0, $v0, %lo(D_800B8AB0)
    /* 6F43C 8007EC3C 000040AC */  sw         $zero, 0x0($v0)
    /* 6F440 8007EC40 040040AC */  sw         $zero, 0x4($v0)
    /* 6F444 8007EC44 080040AC */  sw         $zero, 0x8($v0)
    /* 6F448 8007EC48 0A80023C */  lui        $v0, %hi(D_800A3510)
    /* 6F44C 8007EC4C 10354224 */  addiu      $v0, $v0, %lo(D_800A3510)
    /* 6F450 8007EC50 200040AC */  sw         $zero, 0x20($v0)
    /* 6F454 8007EC54 100040AC */  sw         $zero, 0x10($v0)
    /* 6F458 8007EC58 000040AC */  sw         $zero, 0x0($v0)
    /* 6F45C 8007EC5C 240040A0 */  sb         $zero, 0x24($v0)
    /* 6F460 8007EC60 140040A0 */  sb         $zero, 0x14($v0)
    /* 6F464 8007EC64 040040A0 */  sb         $zero, 0x4($v0)
  .L8007EC68:
    /* 6F468 8007EC68 0A80013C */  lui        $at, %hi(D_800A3515)
    /* 6F46C 8007EC6C 21082300 */  addu       $at, $at, $v1
    /* 6F470 8007EC70 153520A0 */  sb         $zero, %lo(D_800A3515)($at)
    /* 6F474 8007EC74 0A80013C */  lui        $at, %hi(D_800A3525)
    /* 6F478 8007EC78 21082300 */  addu       $at, $at, $v1
    /* 6F47C 8007EC7C 253520A0 */  sb         $zero, %lo(D_800A3525)($at)
    /* 6F480 8007EC80 0A80013C */  lui        $at, %hi(D_800A3535)
    /* 6F484 8007EC84 21082300 */  addu       $at, $at, $v1
    /* 6F488 8007EC88 353520A0 */  sb         $zero, %lo(D_800A3535)($at)
    /* 6F48C 8007EC8C 01006324 */  addiu      $v1, $v1, 0x1
    /* 6F490 8007EC90 08006228 */  slti       $v0, $v1, 0x8
    /* 6F494 8007EC94 F4FF4014 */  bnez       $v0, .L8007EC68
    /* 6F498 8007EC98 21880000 */   addu      $s1, $zero, $zero
    /* 6F49C 8007EC9C 0A80103C */  lui        $s0, %hi(D_800A3540)
    /* 6F4A0 8007ECA0 40351026 */  addiu      $s0, $s0, %lo(D_800A3540)
  .L8007ECA4:
    /* 6F4A4 8007ECA4 65F9010C */  jal        CQ_clear_queue
    /* 6F4A8 8007ECA8 21200002 */   addu      $a0, $s0, $zero
    /* 6F4AC 8007ECAC 01003126 */  addiu      $s1, $s1, 0x1
    /* 6F4B0 8007ECB0 0800222A */  slti       $v0, $s1, 0x8
    /* 6F4B4 8007ECB4 FBFF4014 */  bnez       $v0, .L8007ECA4
    /* 6F4B8 8007ECB8 18001026 */   addiu     $s0, $s0, 0x18
    /* 6F4BC 8007ECBC 07000324 */  addiu      $v1, $zero, 0x7
    /* 6F4C0 8007ECC0 70000224 */  addiu      $v0, $zero, 0x70
    /* 6F4C4 8007ECC4 0A80013C */  lui        $at, %hi(D_800A3604)
    /* 6F4C8 8007ECC8 043620AC */  sw         $zero, %lo(D_800A3604)($at)
    /* 6F4CC 8007ECCC 0A80013C */  lui        $at, %hi(D_800A3600)
    /* 6F4D0 8007ECD0 003620AC */  sw         $zero, %lo(D_800A3600)($at)
    /* 6F4D4 8007ECD4 0A80013C */  lui        $at, %hi(g_CdPendingReadCount)
    /* 6F4D8 8007ECD8 083620AC */  sw         $zero, %lo(g_CdPendingReadCount)($at)
  .L8007ECDC:
    /* 6F4DC 8007ECDC 0A80013C */  lui        $at, %hi(D_800A3610)
    /* 6F4E0 8007ECE0 21082200 */  addu       $at, $at, $v0
    /* 6F4E4 8007ECE4 103620AC */  sw         $zero, %lo(D_800A3610)($at)
    /* 6F4E8 8007ECE8 FFFF6324 */  addiu      $v1, $v1, -0x1
    /* 6F4EC 8007ECEC FBFF6104 */  bgez       $v1, .L8007ECDC
    /* 6F4F0 8007ECF0 F0FF4224 */   addiu     $v0, $v0, -0x10
    /* 6F4F4 8007ECF4 0A80013C */  lui        $at, %hi(D_800A3690)
    /* 6F4F8 8007ECF8 65FE010C */  jal        CdRom_InitDsCallbacks
    /* 6F4FC 8007ECFC 903620AC */   sw        $zero, %lo(D_800A3690)($at)
    /* 6F500 8007ED00 0880043C */  lui        $a0, %hi(Render_StepParticleNode)
    /* 6F504 8007ED04 F3FE010C */  jal        CdRom_SetSyncCallback
    /* 6F508 8007ED08 64E98424 */   addiu     $a0, $a0, %lo(Render_StepParticleNode)
    /* 6F50C 8007ED0C 0880043C */  lui        $a0, %hi(Render_PlayParticleEffect)
    /* 6F510 8007ED10 F6FE010C */  jal        CdRom_SetReadyCallback
    /* 6F514 8007ED14 8CF88424 */   addiu     $a0, $a0, %lo(Render_PlayParticleEffect)
    /* 6F518 8007ED18 0880043C */  lui        $a0, %hi(CdRom_DispatchDsReadyCallback)
    /* 6F51C 8007ED1C F9FE010C */  jal        CdRom_SetDispatchCallback
    /* 6F520 8007ED20 60F98424 */   addiu     $a0, $a0, %lo(CdRom_DispatchDsReadyCallback)
    /* 6F524 8007ED24 0880043C */  lui        $a0, %hi(CdRom_PollPendingDsRead)
    /* 6F528 8007ED28 F0FE010C */  jal        CdRom_SetPollCallback
    /* 6F52C 8007ED2C E8F78424 */   addiu     $a0, $a0, %lo(CdRom_PollPendingDsRead)
    /* 6F530 8007ED30 AF08020C */  jal        DS_read_cbready
    /* 6F534 8007ED34 00000000 */   nop
    /* 6F538 8007ED38 9707020C */  jal        DsReadCallback
    /* 6F53C 8007ED3C 21200000 */   addu      $a0, $zero, $zero
    /* 6F540 8007ED40 01000224 */  addiu      $v0, $zero, 0x1
  .L8007ED44:
    /* 6F544 8007ED44 1800BF8F */  lw         $ra, 0x18($sp)
    /* 6F548 8007ED48 1400B18F */  lw         $s1, 0x14($sp)
    /* 6F54C 8007ED4C 1000B08F */  lw         $s0, 0x10($sp)
    /* 6F550 8007ED50 0800E003 */  jr         $ra
    /* 6F554 8007ED54 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel CdRom_InitDsReadSystem
