.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.4 */

nonmatching CdRom_StartRead, 0x130

glabel CdRom_StartRead
    /* 71634 80080E34 C8FFBD27 */  addiu      $sp, $sp, -0x38
    /* 71638 80080E38 2800B2AF */  sw         $s2, 0x28($sp)
    /* 7163C 80080E3C 21908000 */  addu       $s2, $a0, $zero
    /* 71640 80080E40 3000B4AF */  sw         $s4, 0x30($sp)
    /* 71644 80080E44 21A0A000 */  addu       $s4, $a1, $zero
    /* 71648 80080E48 2C00B3AF */  sw         $s3, 0x2C($sp)
    /* 7164C 80080E4C 2198C000 */  addu       $s3, $a2, $zero
    /* 71650 80080E50 2400B1AF */  sw         $s1, 0x24($sp)
    /* 71654 80080E54 2000B0AF */  sw         $s0, 0x20($sp)
    /* 71658 80080E58 0A80103C */  lui        $s0, %hi(D_8009B6CC)
    /* 7165C 80080E5C CCB61026 */  addiu      $s0, $s0, %lo(D_8009B6CC)
    /* 71660 80080E60 3400BFAF */  sw         $ra, 0x34($sp)
    /* 71664 80080E64 0000038E */  lw         $v1, 0x0($s0)
    /* 71668 80080E68 01000224 */  addiu      $v0, $zero, 0x1
    /* 7166C 80080E6C 05006210 */  beq        $v1, $v0, .L80080E84
    /* 71670 80080E70 2188E000 */   addu      $s1, $a3, $zero
    /* 71674 80080E74 AB08020C */  jal        DsRead_IsBusy
    /* 71678 80080E78 00000000 */   nop
    /* 7167C 80080E7C 03004010 */  beqz       $v0, .L80080E8C
    /* 71680 80080E80 00020224 */   addiu     $v0, $zero, 0x200
  .L80080E84:
    /* 71684 80080E84 D1030208 */  j          .L80080F44
    /* 71688 80080E88 21100000 */   addu      $v0, $zero, $zero
  .L80080E8C:
    /* 7168C 80080E8C E0FF02AE */  sw         $v0, -0x20($s0)
    /* 71690 80080E90 E4FF13AE */  sw         $s3, -0x1C($s0)
    /* 71694 80080E94 0A004016 */  bnez       $s2, .L80080EC0
    /* 71698 80080E98 E8FF14AE */   sw        $s4, -0x18($s0)
    /* 7169C 80080E9C 3703020C */  jal        CdRom_GetCurrentPos
    /* 716A0 80080EA0 21200000 */   addu      $a0, $zero, $zero
    /* 716A4 80080EA4 03004388 */  lwl        $v1, 0x3($v0)
    /* 716A8 80080EA8 00004398 */  lwr        $v1, 0x0($v0)
    /* 716AC 80080EAC 00000000 */  nop
    /* 716B0 80080EB0 1B00A3AB */  swl        $v1, 0x1B($sp)
    /* 716B4 80080EB4 1800A3BB */  swr        $v1, 0x18($sp)
    /* 716B8 80080EB8 B6030208 */  j          .L80080ED8
    /* 716BC 80080EBC 20003136 */   ori       $s1, $s1, 0x20
  .L80080EC0:
    /* 716C0 80080EC0 0300428A */  lwl        $v0, 0x3($s2)
    /* 716C4 80080EC4 0000429A */  lwr        $v0, 0x0($s2)
    /* 716C8 80080EC8 00000000 */  nop
    /* 716CC 80080ECC 1B00A2AB */  swl        $v0, 0x1B($sp)
    /* 716D0 80080ED0 1800A2BB */  swr        $v0, 0x18($sp)
    /* 716D4 80080ED4 20003136 */  ori        $s1, $s1, 0x20
  .L80080ED8:
    /* 716D8 80080ED8 FFFF0224 */  addiu      $v0, $zero, -0x1
    /* 716DC 80080EDC 1000A2AF */  sw         $v0, 0x10($sp)
    /* 716E0 80080EE0 FF002432 */  andi       $a0, $s1, 0xFF
    /* 716E4 80080EE4 1800A527 */  addiu      $a1, $sp, 0x18
    /* 716E8 80080EE8 0880073C */  lui        $a3, %hi(CdRom_SetMode2Callback)
    /* 716EC 80080EEC 640FE724 */  addiu      $a3, $a3, %lo(CdRom_SetMode2Callback)
    /* 716F0 80080EF0 32FC010C */  jal        Render_BuildParticleFrame
    /* 716F4 80080EF4 06000624 */   addiu     $a2, $zero, 0x6
    /* 716F8 80080EF8 21884000 */  addu       $s1, $v0, $zero
    /* 716FC 80080EFC 11002012 */  beqz       $s1, .L80080F44
    /* 71700 80080F00 21100000 */   addu      $v0, $zero, $zero
    /* 71704 80080F04 91CE010C */  jal        VSync
    /* 71708 80080F08 FFFF0424 */   addiu     $a0, $zero, -0x1
    /* 7170C 80080F0C 0A80103C */  lui        $s0, %hi(D_8009B6C4)
    /* 71710 80080F10 C4B61026 */  addiu      $s0, $s0, %lo(D_8009B6C4)
    /* 71714 80080F14 F4FF038E */  lw         $v1, -0xC($s0)
    /* 71718 80080F18 00000000 */  nop
    /* 7171C 80080F1C 01006330 */  andi       $v1, $v1, 0x1
    /* 71720 80080F20 05006010 */  beqz       $v1, .L80080F38
    /* 71724 80080F24 000002AE */   sw        $v0, 0x0($s0)
    /* 71728 80080F28 0880043C */  lui        $a0, %hi(Render_StepParticleCallback)
    /* 7172C 80080F2C 3C09020C */  jal        DsDataCallback
    /* 71730 80080F30 10118424 */   addiu     $a0, $a0, %lo(Render_StepParticleCallback)
    /* 71734 80080F34 FCFF02AE */  sw         $v0, -0x4($s0)
  .L80080F38:
    /* 71738 80080F38 01000224 */  addiu      $v0, $zero, 0x1
    /* 7173C 80080F3C 080002AE */  sw         $v0, 0x8($s0)
    /* 71740 80080F40 21102002 */  addu       $v0, $s1, $zero
  .L80080F44:
    /* 71744 80080F44 3400BF8F */  lw         $ra, 0x34($sp)
    /* 71748 80080F48 3000B48F */  lw         $s4, 0x30($sp)
    /* 7174C 80080F4C 2C00B38F */  lw         $s3, 0x2C($sp)
    /* 71750 80080F50 2800B28F */  lw         $s2, 0x28($sp)
    /* 71754 80080F54 2400B18F */  lw         $s1, 0x24($sp)
    /* 71758 80080F58 2000B08F */  lw         $s0, 0x20($sp)
    /* 7175C 80080F5C 0800E003 */  jr         $ra
    /* 71760 80080F60 3800BD27 */   addiu     $sp, $sp, 0x38
endlabel CdRom_StartRead
