/* CC1_FLAGS: -g3 */

/* Function body emitted as asm() (PSYQ GCC 2.7.2 register
 * allocation / scheduling diverges from the ROM pervasively).
 * Wrapped via maspsx's INCLUDE_ASM hack so the body is passed
 * through verbatim; bare global loads gp-rel via the .extern size
 * hints + `as -G8`. See tools/maspsx/PE1_IMPROVEMENTS.md. */
void __maspsx_include_asm_hack_DS_cachefile(void);
void __maspsx_include_asm_hack_DS_cachefile(void) {
	__asm__(
		"	.set	noreorder # maspsx-keep\n"
		"	.set	nomacro # maspsx-keep\n"
		"	.globl	DS_cachefile # maspsx-keep\n"
		"DS_cachefile: # maspsx-keep\n"
		"	lui	$v0,%hi(D_8009B6DC) # maspsx-keep\n"
		"	lw	$v0,%lo(D_8009B6DC)($v0) # maspsx-keep\n"
		"	addiu	$sp,$sp,-0x40 # maspsx-keep\n"
		"	sw	$s6,0x38($sp) # maspsx-keep\n"
		"	addu	$s6,$a0,$zero # maspsx-keep\n"
		"	sw	$ra,0x3C($sp) # maspsx-keep\n"
		"	sw	$s5,0x34($sp) # maspsx-keep\n"
		"	sw	$s4,0x30($sp) # maspsx-keep\n"
		"	sw	$s3,0x2C($sp) # maspsx-keep\n"
		"	sw	$s2,0x28($sp) # maspsx-keep\n"
		"	sw	$s1,0x24($sp) # maspsx-keep\n"
		"	beq	$s6,$v0,.L80081CEC # maspsx-keep\n"
		"	sw	$s0,0x20($sp) # maspsx-keep\n"
		"	addiu	$a0,$zero,0x1 # maspsx-keep\n"
		"	sll	$v0,$s6,1 # maspsx-keep\n"
		"	addu	$v0,$v0,$s6 # maspsx-keep\n"
		"	sll	$v0,$v0,2 # maspsx-keep\n"
		"	subu	$v0,$v0,$s6 # maspsx-keep\n"
		"	sll	$v0,$v0,2 # maspsx-keep\n"
		"	lui	$a1,%hi(D_800A3C8C) # maspsx-keep\n"
		"	addu	$a1,$a1,$v0 # maspsx-keep\n"
		"	lw	$a1,%lo(D_800A3C8C)($a1) # maspsx-keep\n"
		"	lui	$s0,%hi(g_DsStreamContext) # maspsx-keep\n"
		"	addiu	$s0,$s0,%lo(g_DsStreamContext) # maspsx-keep\n"
		"	jal	ds_read # maspsx-keep\n"
		"	addu	$a2,$s0,$zero # maspsx-keep\n"
		"	addiu	$v1,$zero,0x1 # maspsx-keep\n"
		"	beq	$v0,$v1,.L80081B18 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lui	$v0,%hi(g_CdReadCallback) # maspsx-keep\n"
		"	lw	$v0,%lo(g_CdReadCallback)($v0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	blez	$v0,.L80081CF0 # maspsx-keep\n"
		"	addiu	$v0,$zero,-0x1 # maspsx-keep\n"
		"	lui	$a0,%hi(D_80011FD8) # maspsx-keep\n"
		"	jal	puts # maspsx-keep\n"
		"	addiu	$a0,$a0,%lo(D_80011FD8) # maspsx-keep\n"
		"	j	.L80081CF0 # maspsx-keep\n"
		"	addiu	$v0,$zero,-0x1 # maspsx-keep\n"
		".L80081B18: # maspsx-keep\n"
		"	lui	$v0,%hi(g_CdReadCallback) # maspsx-keep\n"
		"	lw	$v0,%lo(g_CdReadCallback)($v0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	slti	$v0,$v0,0x2 # maspsx-keep\n"
		"	bnez	$v0,.L80081B40 # maspsx-keep\n"
		"	addiu	$v0,$s0,0x800 # maspsx-keep\n"
		"	lui	$a0,%hi(D_80011FF8) # maspsx-keep\n"
		"	jal	puts # maspsx-keep\n"
		"	addiu	$a0,$a0,%lo(D_80011FF8) # maspsx-keep\n"
		"	addiu	$v0,$s0,0x800 # maspsx-keep\n"
		".L80081B40: # maspsx-keep\n"
		"	sltu	$v0,$s0,$v0 # maspsx-keep\n"
		"	beqz	$v0,.L80081C9C # maspsx-keep\n"
		"	addu	$s2,$zero,$zero # maspsx-keep\n"
		"	lui	$s5,%hi(D_800A36B0) # maspsx-keep\n"
		"	addiu	$s5,$s5,%lo(D_800A36B0) # maspsx-keep\n"
		"	addiu	$s3,$s5,0x8 # maspsx-keep\n"
		"	addu	$s1,$zero,$zero # maspsx-keep\n"
		"	addu	$s4,$s5,$zero # maspsx-keep\n"
		".L80081B60: # maspsx-keep\n"
		"	lbu	$v0,0x0($s0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	beqz	$v0,.L80081C9C # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lwl	$v0,0x5($s0) # maspsx-keep\n"
		"	lwr	$v0,0x2($s0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	swl	$v0,0x1B($sp) # maspsx-keep\n"
		"	swr	$v0,0x18($sp) # maspsx-keep\n"
		"	lw	$a0,0x18($sp) # maspsx-keep\n"
		"	jal	CdIntToPos # maspsx-keep\n"
		"	addu	$a1,$s4,$zero # maspsx-keep\n"
		"	addiu	$v0,$s5,0x4 # maspsx-keep\n"
		"	addu	$v0,$s1,$v0 # maspsx-keep\n"
		"	lwl	$v1,0xD($s0) # maspsx-keep\n"
		"	lwr	$v1,0xA($s0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	swl	$v1,0x3($v0) # maspsx-keep\n"
		"	swr	$v1,0x0($v0) # maspsx-keep\n"
		"	beqz	$s2,.L80081BC4 # maspsx-keep\n"
		"	addiu	$v0,$zero,0x1 # maspsx-keep\n"
		"	beq	$s2,$v0,.L80081BD4 # maspsx-keep\n"
		"	addu	$a0,$s3,$zero # maspsx-keep\n"
		"	j	.L80081BF0 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L80081BC4: # maspsx-keep\n"
		"	lui	$v0,%hi(D_80012014) # maspsx-keep\n"
		"	lhu	$v0,%lo(D_80012014)($v0) # maspsx-keep\n"
		"	j	.L80081C0C # maspsx-keep\n"
		"	sh	$v0,0x8($s5) # maspsx-keep\n"
		".L80081BD4: # maspsx-keep\n"
		"	lui	$v0,%hi(D_80012018) # maspsx-keep\n"
		"	lh	$v0,%lo(D_80012018)($v0) # maspsx-keep\n"
		"	lui	$v1,%hi(D_8001201A) # maspsx-keep\n"
		"	lb	$v1,%lo(D_8001201A)($v1) # maspsx-keep\n"
		"	sh	$v0,0x20($s5) # maspsx-keep\n"
		"	j	.L80081C0C # maspsx-keep\n"
		"	sb	$v1,0x22($s5) # maspsx-keep\n"
		".L80081BF0: # maspsx-keep\n"
		"	lbu	$a2,0x20($s0) # maspsx-keep\n"
		"	jal	memcpy # maspsx-keep\n"
		"	addiu	$a1,$s0,0x21 # maspsx-keep\n"
		"	lbu	$v0,0x20($s0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	addu	$v0,$s3,$v0 # maspsx-keep\n"
		"	sb	$zero,0x0($v0) # maspsx-keep\n"
		".L80081C0C: # maspsx-keep\n"
		"	lui	$v0,%hi(g_CdReadCallback) # maspsx-keep\n"
		"	lw	$v0,%lo(g_CdReadCallback)($v0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	slti	$v0,$v0,0x2 # maspsx-keep\n"
		"	bnez	$v0,.L80081C68 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lui	$a1,%hi(D_800A36B0) # maspsx-keep\n"
		"	addu	$a1,$a1,$s1 # maspsx-keep\n"
		"	lbu	$a1,%lo(D_800A36B0)($a1) # maspsx-keep\n"
		"	lui	$a2,%hi(D_800A36B1) # maspsx-keep\n"
		"	addu	$a2,$a2,$s1 # maspsx-keep\n"
		"	lbu	$a2,%lo(D_800A36B1)($a2) # maspsx-keep\n"
		"	lui	$a3,%hi(D_800A36B2) # maspsx-keep\n"
		"	addu	$a3,$a3,$s1 # maspsx-keep\n"
		"	lbu	$a3,%lo(D_800A36B2)($a3) # maspsx-keep\n"
		"	lui	$v0,%hi(D_800A36B4) # maspsx-keep\n"
		"	addu	$v0,$v0,$s1 # maspsx-keep\n"
		"	lw	$v0,%lo(D_800A36B4)($v0) # maspsx-keep\n"
		"	lui	$a0,%hi(D_8001201C) # maspsx-keep\n"
		"	addiu	$a0,$a0,%lo(D_8001201C) # maspsx-keep\n"
		"	sw	$s3,0x14($sp) # maspsx-keep\n"
		"	jal	printf # maspsx-keep\n"
		"	sw	$v0,0x10($sp) # maspsx-keep\n"
		".L80081C68: # maspsx-keep\n"
		"	addiu	$s3,$s3,0x18 # maspsx-keep\n"
		"	addiu	$s1,$s1,0x18 # maspsx-keep\n"
		"	lbu	$v0,0x0($s0) # maspsx-keep\n"
		"	addiu	$s2,$s2,0x1 # maspsx-keep\n"
		"	addu	$s0,$s0,$v0 # maspsx-keep\n"
		"	slti	$v0,$s2,0x40 # maspsx-keep\n"
		"	beqz	$v0,.L80081C9C # maspsx-keep\n"
		"	addiu	$s4,$s4,0x18 # maspsx-keep\n"
		"	lui	$v0,%hi(g_MemCardCounterIrqQueueNode) # maspsx-keep\n"
		"	addiu	$v0,$v0,%lo(g_MemCardCounterIrqQueueNode) # maspsx-keep\n"
		"	sltu	$v0,$s0,$v0 # maspsx-keep\n"
		"	bnez	$v0,.L80081B60 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L80081C9C: # maspsx-keep\n"
		"	lui	$at,%hi(D_8009B6DC) # maspsx-keep\n"
		"	sw	$s6,%lo(D_8009B6DC)($at) # maspsx-keep\n"
		"	slti	$v0,$s2,0x40 # maspsx-keep\n"
		"	beqz	$v0,.L80081CC4 # maspsx-keep\n"
		"	sll	$v0,$s2,1 # maspsx-keep\n"
		"	addu	$v0,$v0,$s2 # maspsx-keep\n"
		"	sll	$v0,$v0,3 # maspsx-keep\n"
		"	lui	$at,%hi(g_DsFileCacheNames) # maspsx-keep\n"
		"	addu	$at,$at,$v0 # maspsx-keep\n"
		"	sb	$zero,%lo(g_DsFileCacheNames)($at) # maspsx-keep\n"
		".L80081CC4: # maspsx-keep\n"
		"	lui	$v0,%hi(g_CdReadCallback) # maspsx-keep\n"
		"	lw	$v0,%lo(g_CdReadCallback)($v0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	slti	$v0,$v0,0x2 # maspsx-keep\n"
		"	bnez	$v0,.L80081CF0 # maspsx-keep\n"
		"	addiu	$v0,$zero,0x1 # maspsx-keep\n"
		"	lui	$a0,%hi(D_80012038) # maspsx-keep\n"
		"	addiu	$a0,$a0,%lo(D_80012038) # maspsx-keep\n"
		"	jal	printf # maspsx-keep\n"
		"	addu	$a1,$s2,$zero # maspsx-keep\n"
		".L80081CEC: # maspsx-keep\n"
		"	addiu	$v0,$zero,0x1 # maspsx-keep\n"
		".L80081CF0: # maspsx-keep\n"
		"	lw	$ra,0x3C($sp) # maspsx-keep\n"
		"	lw	$s6,0x38($sp) # maspsx-keep\n"
		"	lw	$s5,0x34($sp) # maspsx-keep\n"
		"	lw	$s4,0x30($sp) # maspsx-keep\n"
		"	lw	$s3,0x2C($sp) # maspsx-keep\n"
		"	lw	$s2,0x28($sp) # maspsx-keep\n"
		"	lw	$s1,0x24($sp) # maspsx-keep\n"
		"	lw	$s0,0x20($sp) # maspsx-keep\n"
		"	jr	$ra # maspsx-keep\n"
		"	addiu	$sp,$sp,0x40 # maspsx-keep\n"
		"	.set	macro # maspsx-keep\n"
		"	.set	reorder # maspsx-keep\n"
	);
}
