/* CC1_FLAGS: -g3 */

/* Function body emitted as asm() (PSYQ GCC 2.7.2 register
 * allocation / scheduling diverges from the ROM pervasively).
 * Wrapped via maspsx's INCLUDE_ASM hack so the body is passed
 * through verbatim; bare global loads gp-rel via the .extern size
 * hints + `as -G8`. See tools/maspsx/PE1_IMPROVEMENTS.md. */
void __maspsx_include_asm_hack_DS_newmedia(void);
void __maspsx_include_asm_hack_DS_newmedia(void) {
	__asm__(
		"	.set	noreorder # maspsx-keep\n"
		"	.set	nomacro # maspsx-keep\n"
		"	.globl	DS_newmedia # maspsx-keep\n"
		"DS_newmedia: # maspsx-keep\n"
		"	addiu	$sp,$sp,-0x40 # maspsx-keep\n"
		"	addiu	$a0,$zero,0x1 # maspsx-keep\n"
		"	addiu	$a1,$zero,0x10 # maspsx-keep\n"
		"	sw	$s0,0x20($sp) # maspsx-keep\n"
		"	lui	$s0,%hi(g_DsStreamContext) # maspsx-keep\n"
		"	addiu	$s0,$s0,%lo(g_DsStreamContext) # maspsx-keep\n"
		"	addu	$a2,$s0,$zero # maspsx-keep\n"
		"	sw	$ra,0x3C($sp) # maspsx-keep\n"
		"	sw	$s6,0x38($sp) # maspsx-keep\n"
		"	sw	$s5,0x34($sp) # maspsx-keep\n"
		"	sw	$s4,0x30($sp) # maspsx-keep\n"
		"	sw	$s3,0x2C($sp) # maspsx-keep\n"
		"	sw	$s2,0x28($sp) # maspsx-keep\n"
		"	jal	ds_read # maspsx-keep\n"
		"	sw	$s1,0x24($sp) # maspsx-keep\n"
		"	addu	$s1,$v0,$zero # maspsx-keep\n"
		"	addiu	$v0,$zero,0x1 # maspsx-keep\n"
		"	beq	$s1,$v0,.L80081788 # maspsx-keep\n"
		"	addiu	$a0,$s0,0x1 # maspsx-keep\n"
		"	lui	$v0,%hi(g_CdReadCallback) # maspsx-keep\n"
		"	lw	$v0,%lo(g_CdReadCallback)($v0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	blez	$v0,.L800819B0 # maspsx-keep\n"
		"	addu	$v0,$zero,$zero # maspsx-keep\n"
		"	lui	$a0,%hi(D_80011EF8) # maspsx-keep\n"
		"	jal	puts # maspsx-keep\n"
		"	addiu	$a0,$a0,%lo(D_80011EF8) # maspsx-keep\n"
		"	j	.L800819B0 # maspsx-keep\n"
		"	addu	$v0,$zero,$zero # maspsx-keep\n"
		".L80081788: # maspsx-keep\n"
		"	lui	$a1,%hi(D_80011F24) # maspsx-keep\n"
		"	addiu	$a1,$a1,%lo(D_80011F24) # maspsx-keep\n"
		"	jal	strncmp # maspsx-keep\n"
		"	addiu	$a2,$zero,0x5 # maspsx-keep\n"
		"	beqz	$v0,.L800817C8 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lui	$v0,%hi(g_CdReadCallback) # maspsx-keep\n"
		"	lw	$v0,%lo(g_CdReadCallback)($v0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	blez	$v0,.L800819B0 # maspsx-keep\n"
		"	addu	$v0,$zero,$zero # maspsx-keep\n"
		"	lui	$a0,%hi(D_80011F2C) # maspsx-keep\n"
		"	jal	puts # maspsx-keep\n"
		"	addiu	$a0,$a0,%lo(D_80011F2C) # maspsx-keep\n"
		"	j	.L800819B0 # maspsx-keep\n"
		"	addu	$v0,$zero,$zero # maspsx-keep\n"
		".L800817C8: # maspsx-keep\n"
		"	lwl	$v0,0x8F($s0) # maspsx-keep\n"
		"	lwr	$v0,0x8C($s0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	swl	$v0,0x1B($sp) # maspsx-keep\n"
		"	swr	$v0,0x18($sp) # maspsx-keep\n"
		"	addiu	$a0,$zero,0x1 # maspsx-keep\n"
		"	lw	$a1,0x18($sp) # maspsx-keep\n"
		"	jal	ds_read # maspsx-keep\n"
		"	addu	$a2,$s0,$zero # maspsx-keep\n"
		"	beq	$v0,$s1,.L80081820 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lui	$v0,%hi(g_CdReadCallback) # maspsx-keep\n"
		"	lw	$v0,%lo(g_CdReadCallback)($v0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	blez	$v0,.L800819B0 # maspsx-keep\n"
		"	addu	$v0,$zero,$zero # maspsx-keep\n"
		"	lw	$a1,0x18($sp) # maspsx-keep\n"
		"	lui	$a0,%hi(D_80011F5C) # maspsx-keep\n"
		"	jal	printf # maspsx-keep\n"
		"	addiu	$a0,$a0,%lo(D_80011F5C) # maspsx-keep\n"
		"	j	.L800819B0 # maspsx-keep\n"
		"	addu	$v0,$zero,$zero # maspsx-keep\n"
		".L80081820: # maspsx-keep\n"
		"	lui	$v0,%hi(g_CdReadCallback) # maspsx-keep\n"
		"	lw	$v0,%lo(g_CdReadCallback)($v0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	slti	$v0,$v0,0x2 # maspsx-keep\n"
		"	bnez	$v0,.L80081844 # maspsx-keep\n"
		"	addu	$s1,$s0,$zero # maspsx-keep\n"
		"	lui	$a0,%hi(D_80011F80) # maspsx-keep\n"
		"	jal	puts # maspsx-keep\n"
		"	addiu	$a0,$a0,%lo(D_80011F80) # maspsx-keep\n"
		".L80081844: # maspsx-keep\n"
		"	addiu	$v1,$s1,0x800 # maspsx-keep\n"
		"	sltu	$v0,$s1,$v1 # maspsx-keep\n"
		"	beqz	$v0,.L80081958 # maspsx-keep\n"
		"	addu	$a3,$zero,$zero # maspsx-keep\n"
		"	lui	$s4,%hi(D_800A3CB8) # maspsx-keep\n"
		"	addiu	$s4,$s4,%lo(D_800A3CB8) # maspsx-keep\n"
		"	addiu	$s6,$s4,0x4 # maspsx-keep\n"
		"	addu	$s5,$v1,$zero # maspsx-keep\n"
		".L80081864: # maspsx-keep\n"
		"	lbu	$v0,0x0($s1) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	beqz	$v0,.L80081958 # maspsx-keep\n"
		"	sll	$v0,$a3,1 # maspsx-keep\n"
		"	addu	$v0,$v0,$a3 # maspsx-keep\n"
		"	sll	$v0,$v0,2 # maspsx-keep\n"
		"	subu	$v0,$v0,$a3 # maspsx-keep\n"
		"	sll	$s0,$v0,2 # maspsx-keep\n"
		"	addu	$v0,$s0,$s4 # maspsx-keep\n"
		"	lwl	$v1,0x5($s1) # maspsx-keep\n"
		"	lwr	$v1,0x2($s1) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	swl	$v1,0x3($v0) # maspsx-keep\n"
		"	swr	$v1,0x0($v0) # maspsx-keep\n"
		"	addu	$s2,$s0,$s6 # maspsx-keep\n"
		"	addu	$a0,$s2,$zero # maspsx-keep\n"
		"	lbu	$v0,0x6($s1) # maspsx-keep\n"
		"	addiu	$s3,$a3,0x1 # maspsx-keep\n"
		"	lui	$at,%hi(D_800A3CB0) # maspsx-keep\n"
		"	addu	$at,$at,$s0 # maspsx-keep\n"
		"	sw	$s3,%lo(D_800A3CB0)($at) # maspsx-keep\n"
		"	lui	$at,%hi(g_DsDirEntryTable) # maspsx-keep\n"
		"	addu	$at,$at,$s0 # maspsx-keep\n"
		"	sw	$v0,%lo(g_DsDirEntryTable)($at) # maspsx-keep\n"
		"	lbu	$a2,0x0($s1) # maspsx-keep\n"
		"	jal	memcpy # maspsx-keep\n"
		"	addiu	$a1,$s1,0x8 # maspsx-keep\n"
		"	lbu	$v0,0x0($s1) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	addu	$v0,$s2,$v0 # maspsx-keep\n"
		"	sb	$zero,0x0($v0) # maspsx-keep\n"
		"	lbu	$v1,0x0($s1) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	andi	$v0,$v1,0x1 # maspsx-keep\n"
		"	addiu	$v0,$v0,0x8 # maspsx-keep\n"
		"	addu	$v1,$v1,$v0 # maspsx-keep\n"
		"	lui	$v0,%hi(g_CdReadCallback) # maspsx-keep\n"
		"	lw	$v0,%lo(g_CdReadCallback)($v0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	slti	$v0,$v0,0x2 # maspsx-keep\n"
		"	bnez	$v0,.L80081940 # maspsx-keep\n"
		"	addu	$s1,$s1,$v1 # maspsx-keep\n"
		"	lui	$a1,%hi(D_800A3CB8) # maspsx-keep\n"
		"	addu	$a1,$a1,$s0 # maspsx-keep\n"
		"	lw	$a1,%lo(D_800A3CB8)($a1) # maspsx-keep\n"
		"	lui	$a2,%hi(D_800A3CB0) # maspsx-keep\n"
		"	addu	$a2,$a2,$s0 # maspsx-keep\n"
		"	lw	$a2,%lo(D_800A3CB0)($a2) # maspsx-keep\n"
		"	lui	$a3,%hi(g_DsDirEntryTable) # maspsx-keep\n"
		"	addu	$a3,$a3,$s0 # maspsx-keep\n"
		"	lw	$a3,%lo(g_DsDirEntryTable)($a3) # maspsx-keep\n"
		"	lui	$a0,%hi(D_80011FA0) # maspsx-keep\n"
		"	addiu	$a0,$a0,%lo(D_80011FA0) # maspsx-keep\n"
		"	jal	printf # maspsx-keep\n"
		"	sw	$s2,0x10($sp) # maspsx-keep\n"
		".L80081940: # maspsx-keep\n"
		"	addu	$a3,$s3,$zero # maspsx-keep\n"
		"	slti	$v0,$a3,0x80 # maspsx-keep\n"
		"	beqz	$v0,.L80081980 # maspsx-keep\n"
		"	sltu	$v0,$s1,$s5 # maspsx-keep\n"
		"	bnez	$v0,.L80081864 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L80081958: # maspsx-keep\n"
		"	slti	$v0,$a3,0x80 # maspsx-keep\n"
		"	beqz	$v0,.L80081980 # maspsx-keep\n"
		"	sll	$v0,$a3,1 # maspsx-keep\n"
		"	addu	$v0,$v0,$a3 # maspsx-keep\n"
		"	sll	$v0,$v0,2 # maspsx-keep\n"
		"	subu	$v0,$v0,$a3 # maspsx-keep\n"
		"	sll	$v0,$v0,2 # maspsx-keep\n"
		"	lui	$at,%hi(g_DsDirEntryTable) # maspsx-keep\n"
		"	addu	$at,$at,$v0 # maspsx-keep\n"
		"	sw	$zero,%lo(g_DsDirEntryTable)($at) # maspsx-keep\n"
		".L80081980: # maspsx-keep\n"
		"	lui	$v0,%hi(g_CdReadCallback) # maspsx-keep\n"
		"	lw	$v0,%lo(g_CdReadCallback)($v0) # maspsx-keep\n"
		"	lui	$at,%hi(D_8009B6DC) # maspsx-keep\n"
		"	sw	$zero,%lo(D_8009B6DC)($at) # maspsx-keep\n"
		"	slti	$v0,$v0,0x2 # maspsx-keep\n"
		"	bnez	$v0,.L800819B0 # maspsx-keep\n"
		"	addiu	$v0,$zero,0x1 # maspsx-keep\n"
		"	lui	$a0,%hi(D_80011FB4) # maspsx-keep\n"
		"	addiu	$a0,$a0,%lo(D_80011FB4) # maspsx-keep\n"
		"	jal	printf # maspsx-keep\n"
		"	addu	$a1,$a3,$zero # maspsx-keep\n"
		"	addiu	$v0,$zero,0x1 # maspsx-keep\n"
		".L800819B0: # maspsx-keep\n"
		"	lw	$ra,0x3C($sp) # maspsx-keep\n"
		"	lw	$s6,0x38($sp) # maspsx-keep\n"
		"	lw	$s5,0x34($sp) # maspsx-keep\n"
		"	lw	$s4,0x30($sp) # maspsx-keep\n"
		"	lw	$s3,0x2C($sp) # maspsx-keep\n"
		"	lw	$s2,0x28($sp) # maspsx-keep\n"
		"	lw	$s1,0x24($sp) # maspsx-keep\n"
		"	lw	$s0,0x20($sp) # maspsx-keep\n"
		"	jr	$ra # maspsx-keep\n"
		"	addiu	$sp,$sp,0x40 # maspsx-keep\n"
		"	.set	macro # maspsx-keep\n"
		"	.set	reorder # maspsx-keep\n"
	);
}
