/* CC1_FLAGS: -g3 */

/* Function body emitted as asm() (PSYQ GCC 2.7.2 register
 * allocation / scheduling diverges from the ROM pervasively).
 * Wrapped via maspsx's INCLUDE_ASM hack so the body is passed
 * through verbatim; bare global loads gp-rel via the .extern size
 * hints + `as -G8`. See tools/maspsx/PE1_IMPROVEMENTS.md. */
void __maspsx_include_asm_hack_getintr(void);
void __maspsx_include_asm_hack_getintr(void) {
	__asm__(
		".extern	jtbl_80011B8C # maspsx-keep\n"
		"	.set	noreorder # maspsx-keep\n"
		"	.set	nomacro # maspsx-keep\n"
		"	.globl	getintr # maspsx-keep\n"
		"getintr: # maspsx-keep\n"
		"	addiu	$sp,$sp,-0x30 # maspsx-keep\n"
		"	lui	$v1,%hi(g_CdRegIndexBase) # maspsx-keep\n"
		"	lw	$v1,%lo(g_CdRegIndexBase)($v1) # maspsx-keep\n"
		"	addiu	$v0,$zero,0x1 # maspsx-keep\n"
		"	sw	$ra,0x28($sp) # maspsx-keep\n"
		"	sw	$s1,0x24($sp) # maspsx-keep\n"
		"	sw	$s0,0x20($sp) # maspsx-keep\n"
		"	sb	$v0,0x0($v1) # maspsx-keep\n"
		"	lui	$a0,%hi(g_CdRegResponse) # maspsx-keep\n"
		"	lw	$a0,%lo(g_CdRegResponse)($a0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lbu	$v0,0x0($a0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	andi	$v0,$v0,0x7 # maspsx-keep\n"
		"	sb	$v0,0x10($sp) # maspsx-keep\n"
		"	lbu	$v0,0x10($sp) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	beqz	$v0,.L8007AFF8 # maspsx-keep\n"
		"	addu	$s1,$zero,$zero # maspsx-keep\n"
		"	j	.L8007AB18 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L8007AB08: # maspsx-keep\n"
		"	lbu	$v0,0x0($a0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	andi	$v0,$v0,0x7 # maspsx-keep\n"
		"	sb	$v0,0x10($sp) # maspsx-keep\n"
		".L8007AB18: # maspsx-keep\n"
		"	lbu	$v0,0x0($a0) # maspsx-keep\n"
		"	lbu	$v1,0x10($sp) # maspsx-keep\n"
		"	andi	$v0,$v0,0x7 # maspsx-keep\n"
		"	bne	$v1,$v0,.L8007AB08 # maspsx-keep\n"
		"	addu	$s0,$zero,$zero # maspsx-keep\n"
		"	addiu	$a0,$sp,0x18 # maspsx-keep\n"
		".L8007AB30: # maspsx-keep\n"
		"	lui	$v0,%hi(g_CdRegIndexBase) # maspsx-keep\n"
		"	lw	$v0,%lo(g_CdRegIndexBase)($v0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lbu	$v0,0x0($v0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	andi	$v0,$v0,0x20 # maspsx-keep\n"
		"	beqz	$v0,.L8007AB74 # maspsx-keep\n"
		"	addu	$v1,$a0,$s0 # maspsx-keep\n"
		"	lui	$v0,%hi(g_CdRegPort1) # maspsx-keep\n"
		"	lw	$v0,%lo(g_CdRegPort1)($v0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lbu	$v0,0x0($v0) # maspsx-keep\n"
		"	addiu	$s0,$s0,0x1 # maspsx-keep\n"
		"	sb	$v0,0x0($v1) # maspsx-keep\n"
		"	slti	$v0,$s0,0x8 # maspsx-keep\n"
		"	bnez	$v0,.L8007AB30 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L8007AB74: # maspsx-keep\n"
		"	slti	$v0,$s0,0x8 # maspsx-keep\n"
		"	beqz	$v0,.L8007AB9C # maspsx-keep\n"
		"	addu	$v1,$s0,$zero # maspsx-keep\n"
		"	addiu	$a0,$sp,0x18 # maspsx-keep\n"
		"	addu	$v0,$a0,$v1 # maspsx-keep\n"
		".L8007AB88: # maspsx-keep\n"
		"	sb	$zero,0x0($v0) # maspsx-keep\n"
		"	addiu	$v1,$v1,0x1 # maspsx-keep\n"
		"	slti	$v0,$v1,0x8 # maspsx-keep\n"
		"	bnez	$v0,.L8007AB88 # maspsx-keep\n"
		"	addu	$v0,$a0,$v1 # maspsx-keep\n"
		".L8007AB9C: # maspsx-keep\n"
		"	lui	$v1,%hi(g_CdRegIndexBase) # maspsx-keep\n"
		"	lw	$v1,%lo(g_CdRegIndexBase)($v1) # maspsx-keep\n"
		"	addiu	$v0,$zero,0x1 # maspsx-keep\n"
		"	sb	$v0,0x0($v1) # maspsx-keep\n"
		"	lui	$v0,%hi(g_CdRegResponse) # maspsx-keep\n"
		"	lw	$v0,%lo(g_CdRegResponse)($v0) # maspsx-keep\n"
		"	addiu	$v1,$zero,0x7 # maspsx-keep\n"
		"	sb	$v1,0x0($v0) # maspsx-keep\n"
		"	lui	$v0,%hi(g_CdRegDataWrite) # maspsx-keep\n"
		"	lw	$v0,%lo(g_CdRegDataWrite)($v0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	sb	$v1,0x0($v0) # maspsx-keep\n"
		"	lbu	$v1,0x10($sp) # maspsx-keep\n"
		"	addiu	$v0,$zero,0x3 # maspsx-keep\n"
		"	bne	$v1,$v0,.L8007AC04 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lui	$v0,%hi(g_CdLastCom) # maspsx-keep\n"
		"	lbu	$v0,%lo(g_CdLastCom)($v0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	sll	$v0,$v0,2 # maspsx-keep\n"
		"	lui	$at,%hi(D_8009B17C) # maspsx-keep\n"
		"	addu	$at,$at,$v0 # maspsx-keep\n"
		"	lw	$v0,%lo(D_8009B17C)($at) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	beqz	$v0,.L8007AC68 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L8007AC04: # maspsx-keep\n"
		"	lui	$v0,%hi(g_CdStatus) # maspsx-keep\n"
		"	lw	$v0,%lo(g_CdStatus)($v0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	andi	$v0,$v0,0x10 # maspsx-keep\n"
		"	bnez	$v0,.L8007AC48 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lbu	$v0,0x18($sp) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	andi	$v0,$v0,0x10 # maspsx-keep\n"
		"	beqz	$v0,.L8007AC48 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lui	$v0,%hi(D_8009AFCC) # maspsx-keep\n"
		"	lw	$v0,%lo(D_8009AFCC)($v0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	addiu	$v0,$v0,0x1 # maspsx-keep\n"
		"	lui	$at,%hi(D_8009AFCC) # maspsx-keep\n"
		"	sw	$v0,%lo(D_8009AFCC)($at) # maspsx-keep\n"
		".L8007AC48: # maspsx-keep\n"
		"	lbu	$v0,0x18($sp) # maspsx-keep\n"
		"	lbu	$v1,0x19($sp) # maspsx-keep\n"
		"	andi	$v0,$v0,0xFF # maspsx-keep\n"
		"	andi	$s1,$v0,0x1D # maspsx-keep\n"
		"	lui	$at,%hi(g_CdStatus) # maspsx-keep\n"
		"	sw	$v0,%lo(g_CdStatus)($at) # maspsx-keep\n"
		"	lui	$at,%hi(g_CdResultByte) # maspsx-keep\n"
		"	sw	$v1,%lo(g_CdResultByte)($at) # maspsx-keep\n"
		".L8007AC68: # maspsx-keep\n"
		"	lbu	$v1,0x10($sp) # maspsx-keep\n"
		"	addiu	$v0,$zero,0x5 # maspsx-keep\n"
		"	bne	$v1,$v0,.L8007ACE0 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lui	$v0,%hi(g_CdReadCallback) # maspsx-keep\n"
		"	lw	$v0,%lo(g_CdReadCallback)($v0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	blez	$v0,.L8007ACE0 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lui	$a0,%hi(D_80011B44) # maspsx-keep\n"
		"	jal	printf # maspsx-keep\n"
		"	addiu	$a0,$a0,%lo(D_80011B44) # maspsx-keep\n"
		"	lui	$v0,%hi(g_CdReadCallback) # maspsx-keep\n"
		"	lw	$v0,%lo(g_CdReadCallback)($v0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	blez	$v0,.L8007ACE0 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lui	$v0,%hi(g_CdLastCom) # maspsx-keep\n"
		"	lbu	$v0,%lo(g_CdLastCom)($v0) # maspsx-keep\n"
		"	lui	$a2,%hi(g_CdStatus) # maspsx-keep\n"
		"	lw	$a2,%lo(g_CdStatus)($a2) # maspsx-keep\n"
		"	lui	$a3,%hi(g_CdResultByte) # maspsx-keep\n"
		"	lw	$a3,%lo(g_CdResultByte)($a3) # maspsx-keep\n"
		"	sll	$v0,$v0,2 # maspsx-keep\n"
		"	lui	$a1,%hi(g_CdCmdNameTable) # maspsx-keep\n"
		"	addu	$a1,$a1,$v0 # maspsx-keep\n"
		"	lw	$a1,%lo(g_CdCmdNameTable)($a1) # maspsx-keep\n"
		"	lui	$a0,%hi(D_80011B50) # maspsx-keep\n"
		"	jal	printf # maspsx-keep\n"
		"	addiu	$a0,$a0,%lo(D_80011B50) # maspsx-keep\n"
		".L8007ACE0: # maspsx-keep\n"
		"	lbu	$v0,0x10($sp) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	addiu	$v1,$v0,-0x1 # maspsx-keep\n"
		"	sltiu	$v0,$v1,0x5 # maspsx-keep\n"
		"	beqz	$v0,.L8007AFDC # maspsx-keep\n"
		"	sll	$v0,$v1,2 # maspsx-keep\n"
		"	lui	$at,%hi(jtbl_80011B8C) # maspsx-keep\n"
		"	addu	$at,$at,$v0 # maspsx-keep\n"
		"	lw	$v0,%lo(jtbl_80011B8C)($at) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	jr	$v0 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L8007AD10: # maspsx-keep\n"
		"	beqz	$s1,.L8007AD5C # maspsx-keep\n"
		"	addiu	$v0,$zero,0x5 # maspsx-keep\n"
		"	lui	$v1,%hi(D_8009B294) # maspsx-keep\n"
		"	addiu	$v1,$v1,%lo(D_8009B294) # maspsx-keep\n"
		"	sb	$v0,0x0($v1) # maspsx-keep\n"
		"	lui	$v1,%hi(g_CdResultBuffer) # maspsx-keep\n"
		"	addiu	$v1,$v1,%lo(g_CdResultBuffer) # maspsx-keep\n"
		"	beqz	$v1,.L8007AE54 # maspsx-keep\n"
		"	addiu	$a1,$sp,0x18 # maspsx-keep\n"
		"	addiu	$a0,$zero,0x7 # maspsx-keep\n"
		"	addiu	$a2,$zero,-0x1 # maspsx-keep\n"
		".L8007AD3C: # maspsx-keep\n"
		"	lbu	$v0,0x0($a1) # maspsx-keep\n"
		"	addiu	$a1,$a1,0x1 # maspsx-keep\n"
		"	addiu	$a0,$a0,-0x1 # maspsx-keep\n"
		"	sb	$v0,0x0($v1) # maspsx-keep\n"
		"	bne	$a0,$a2,.L8007AD3C # maspsx-keep\n"
		"	addiu	$v1,$v1,0x1 # maspsx-keep\n"
		"	j	.L8007AFFC # maspsx-keep\n"
		"	addiu	$v0,$zero,0x2 # maspsx-keep\n"
		".L8007AD5C: # maspsx-keep\n"
		"	lui	$v0,%hi(g_CdLastCom) # maspsx-keep\n"
		"	lbu	$v0,%lo(g_CdLastCom)($v0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	sll	$v0,$v0,2 # maspsx-keep\n"
		"	lui	$at,%hi(D_8009B07C) # maspsx-keep\n"
		"	addu	$at,$at,$v0 # maspsx-keep\n"
		"	lw	$v0,%lo(D_8009B07C)($at) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	beqz	$v0,.L8007ADC8 # maspsx-keep\n"
		"	addiu	$v0,$zero,0x3 # maspsx-keep\n"
		"	lui	$v1,%hi(D_8009B294) # maspsx-keep\n"
		"	addiu	$v1,$v1,%lo(D_8009B294) # maspsx-keep\n"
		"	sb	$v0,0x0($v1) # maspsx-keep\n"
		"	lui	$v1,%hi(g_CdResultBuffer) # maspsx-keep\n"
		"	addiu	$v1,$v1,%lo(g_CdResultBuffer) # maspsx-keep\n"
		"	beqz	$v1,.L8007ADC0 # maspsx-keep\n"
		"	addiu	$a1,$sp,0x18 # maspsx-keep\n"
		"	addiu	$a0,$zero,0x7 # maspsx-keep\n"
		"	addiu	$a2,$zero,-0x1 # maspsx-keep\n"
		".L8007ADA8: # maspsx-keep\n"
		"	lbu	$v0,0x0($a1) # maspsx-keep\n"
		"	addiu	$a1,$a1,0x1 # maspsx-keep\n"
		"	addiu	$a0,$a0,-0x1 # maspsx-keep\n"
		"	sb	$v0,0x0($v1) # maspsx-keep\n"
		"	bne	$a0,$a2,.L8007ADA8 # maspsx-keep\n"
		"	addiu	$v1,$v1,0x1 # maspsx-keep\n"
		".L8007ADC0: # maspsx-keep\n"
		"	j	.L8007AFFC # maspsx-keep\n"
		"	addiu	$v0,$zero,0x1 # maspsx-keep\n"
		".L8007ADC8: # maspsx-keep\n"
		"	lui	$v1,%hi(D_8009B294) # maspsx-keep\n"
		"	addiu	$v1,$v1,%lo(D_8009B294) # maspsx-keep\n"
		"	addiu	$v0,$zero,0x2 # maspsx-keep\n"
		"	sb	$v0,0x0($v1) # maspsx-keep\n"
		"	lui	$v1,%hi(g_CdResultBuffer) # maspsx-keep\n"
		"	addiu	$v1,$v1,%lo(g_CdResultBuffer) # maspsx-keep\n"
		"	beqz	$v1,.L8007AE54 # maspsx-keep\n"
		"	addiu	$a1,$sp,0x18 # maspsx-keep\n"
		"	addiu	$a0,$zero,0x7 # maspsx-keep\n"
		"	addiu	$a2,$zero,-0x1 # maspsx-keep\n"
		".L8007ADF0: # maspsx-keep\n"
		"	lbu	$v0,0x0($a1) # maspsx-keep\n"
		"	addiu	$a1,$a1,0x1 # maspsx-keep\n"
		"	addiu	$a0,$a0,-0x1 # maspsx-keep\n"
		"	sb	$v0,0x0($v1) # maspsx-keep\n"
		"	bne	$a0,$a2,.L8007ADF0 # maspsx-keep\n"
		"	addiu	$v1,$v1,0x1 # maspsx-keep\n"
		"	j	.L8007AFFC # maspsx-keep\n"
		"	addiu	$v0,$zero,0x2 # maspsx-keep\n"
		".L8007AE10: # maspsx-keep\n"
		"	beqz	$s1,.L8007AE1C # maspsx-keep\n"
		"	addiu	$v0,$zero,0x2 # maspsx-keep\n"
		"	addiu	$v0,$zero,0x5 # maspsx-keep\n"
		".L8007AE1C: # maspsx-keep\n"
		"	lui	$at,%hi(D_8009B294) # maspsx-keep\n"
		"	sb	$v0,%lo(D_8009B294)($at) # maspsx-keep\n"
		"	lui	$v1,%hi(g_CdResultBuffer) # maspsx-keep\n"
		"	addiu	$v1,$v1,%lo(g_CdResultBuffer) # maspsx-keep\n"
		"	beqz	$v1,.L8007AE54 # maspsx-keep\n"
		"	addiu	$a1,$sp,0x18 # maspsx-keep\n"
		"	addiu	$a0,$zero,0x7 # maspsx-keep\n"
		"	addiu	$a2,$zero,-0x1 # maspsx-keep\n"
		".L8007AE3C: # maspsx-keep\n"
		"	lbu	$v0,0x0($a1) # maspsx-keep\n"
		"	addiu	$a1,$a1,0x1 # maspsx-keep\n"
		"	addiu	$a0,$a0,-0x1 # maspsx-keep\n"
		"	sb	$v0,0x0($v1) # maspsx-keep\n"
		"	bne	$a0,$a2,.L8007AE3C # maspsx-keep\n"
		"	addiu	$v1,$v1,0x1 # maspsx-keep\n"
		".L8007AE54: # maspsx-keep\n"
		"	j	.L8007AFFC # maspsx-keep\n"
		"	addiu	$v0,$zero,0x2 # maspsx-keep\n"
		".L8007AE5C: # maspsx-keep\n"
		"	beqz	$s1,.L8007AE70 # maspsx-keep\n"
		"	addiu	$v0,$zero,0x1 # maspsx-keep\n"
		"	bne	$s0,$v0,.L8007AE70 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	addu	$s1,$zero,$zero # maspsx-keep\n"
		".L8007AE70: # maspsx-keep\n"
		"	beqz	$s1,.L8007AE7C # maspsx-keep\n"
		"	addiu	$v1,$zero,0x1 # maspsx-keep\n"
		"	addiu	$v1,$zero,0x5 # maspsx-keep\n"
		".L8007AE7C: # maspsx-keep\n"
		"	lui	$v0,%hi(D_8009B294) # maspsx-keep\n"
		"	addiu	$v0,$v0,%lo(D_8009B294) # maspsx-keep\n"
		"	sb	$v1,0x1($v0) # maspsx-keep\n"
		"	lui	$v1,%hi(g_CdReadyResult) # maspsx-keep\n"
		"	addiu	$v1,$v1,%lo(g_CdReadyResult) # maspsx-keep\n"
		"	beqz	$v1,.L8007AEB8 # maspsx-keep\n"
		"	addiu	$a1,$sp,0x18 # maspsx-keep\n"
		"	addiu	$a0,$zero,0x7 # maspsx-keep\n"
		"	addiu	$a2,$zero,-0x1 # maspsx-keep\n"
		".L8007AEA0: # maspsx-keep\n"
		"	lbu	$v0,0x0($a1) # maspsx-keep\n"
		"	addiu	$a1,$a1,0x1 # maspsx-keep\n"
		"	addiu	$a0,$a0,-0x1 # maspsx-keep\n"
		"	sb	$v0,0x0($v1) # maspsx-keep\n"
		"	bne	$a0,$a2,.L8007AEA0 # maspsx-keep\n"
		"	addiu	$v1,$v1,0x1 # maspsx-keep\n"
		".L8007AEB8: # maspsx-keep\n"
		"	lui	$v0,%hi(g_CdRegIndexBase) # maspsx-keep\n"
		"	lw	$v0,%lo(g_CdRegIndexBase)($v0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	sb	$zero,0x0($v0) # maspsx-keep\n"
		"	lui	$v1,%hi(g_CdRegResponse) # maspsx-keep\n"
		"	lw	$v1,%lo(g_CdRegResponse)($v1) # maspsx-keep\n"
		"	addiu	$v0,$zero,0x4 # maspsx-keep\n"
		"	j	.L8007AFFC # maspsx-keep\n"
		"	sb	$zero,0x0($v1) # maspsx-keep\n"
		".L8007AEDC: # maspsx-keep\n"
		"	lui	$a0,%hi(g_CdIntrResultBuffer) # maspsx-keep\n"
		"	addiu	$a0,$a0,%lo(g_CdIntrResultBuffer) # maspsx-keep\n"
		"	lui	$v0,%hi(D_8009B294) # maspsx-keep\n"
		"	addiu	$v0,$v0,%lo(D_8009B294) # maspsx-keep\n"
		"	addiu	$v1,$zero,0x4 # maspsx-keep\n"
		"	sb	$v1,0x2($v0) # maspsx-keep\n"
		"	lbu	$v1,0x2($v0) # maspsx-keep\n"
		"	addiu	$a1,$sp,0x18 # maspsx-keep\n"
		"	sb	$v1,0x1($v0) # maspsx-keep\n"
		"	beqz	$a0,.L8007AF24 # maspsx-keep\n"
		"	addiu	$v1,$zero,0x7 # maspsx-keep\n"
		"	addiu	$a2,$zero,-0x1 # maspsx-keep\n"
		".L8007AF0C: # maspsx-keep\n"
		"	lbu	$v0,0x0($a1) # maspsx-keep\n"
		"	addiu	$a1,$a1,0x1 # maspsx-keep\n"
		"	addiu	$v1,$v1,-0x1 # maspsx-keep\n"
		"	sb	$v0,0x0($a0) # maspsx-keep\n"
		"	bne	$v1,$a2,.L8007AF0C # maspsx-keep\n"
		"	addiu	$a0,$a0,0x1 # maspsx-keep\n"
		".L8007AF24: # maspsx-keep\n"
		"	lui	$v1,%hi(g_CdReadyResult) # maspsx-keep\n"
		"	addiu	$v1,$v1,%lo(g_CdReadyResult) # maspsx-keep\n"
		"	beqz	$v1,.L8007AF54 # maspsx-keep\n"
		"	addiu	$a1,$sp,0x18 # maspsx-keep\n"
		"	addiu	$a0,$zero,0x7 # maspsx-keep\n"
		"	addiu	$a2,$zero,-0x1 # maspsx-keep\n"
		".L8007AF3C: # maspsx-keep\n"
		"	lbu	$v0,0x0($a1) # maspsx-keep\n"
		"	addiu	$a1,$a1,0x1 # maspsx-keep\n"
		"	addiu	$a0,$a0,-0x1 # maspsx-keep\n"
		"	sb	$v0,0x0($v1) # maspsx-keep\n"
		"	bne	$a0,$a2,.L8007AF3C # maspsx-keep\n"
		"	addiu	$v1,$v1,0x1 # maspsx-keep\n"
		".L8007AF54: # maspsx-keep\n"
		"	j	.L8007AFFC # maspsx-keep\n"
		"	addiu	$v0,$zero,0x4 # maspsx-keep\n"
		".L8007AF5C: # maspsx-keep\n"
		"	lui	$a0,%hi(g_CdResultBuffer) # maspsx-keep\n"
		"	addiu	$a0,$a0,%lo(g_CdResultBuffer) # maspsx-keep\n"
		"	lui	$v0,%hi(D_8009B294) # maspsx-keep\n"
		"	addiu	$v0,$v0,%lo(D_8009B294) # maspsx-keep\n"
		"	addiu	$v1,$zero,0x5 # maspsx-keep\n"
		"	sb	$v1,0x1($v0) # maspsx-keep\n"
		"	lbu	$v1,0x1($v0) # maspsx-keep\n"
		"	addiu	$a1,$sp,0x18 # maspsx-keep\n"
		"	sb	$v1,0x0($v0) # maspsx-keep\n"
		"	beqz	$a0,.L8007AFA4 # maspsx-keep\n"
		"	addiu	$v1,$zero,0x7 # maspsx-keep\n"
		"	addiu	$a2,$zero,-0x1 # maspsx-keep\n"
		".L8007AF8C: # maspsx-keep\n"
		"	lbu	$v0,0x0($a1) # maspsx-keep\n"
		"	addiu	$a1,$a1,0x1 # maspsx-keep\n"
		"	addiu	$v1,$v1,-0x1 # maspsx-keep\n"
		"	sb	$v0,0x0($a0) # maspsx-keep\n"
		"	bne	$v1,$a2,.L8007AF8C # maspsx-keep\n"
		"	addiu	$a0,$a0,0x1 # maspsx-keep\n"
		".L8007AFA4: # maspsx-keep\n"
		"	lui	$v1,%hi(g_CdReadyResult) # maspsx-keep\n"
		"	addiu	$v1,$v1,%lo(g_CdReadyResult) # maspsx-keep\n"
		"	beqz	$v1,.L8007AFD4 # maspsx-keep\n"
		"	addiu	$a1,$sp,0x18 # maspsx-keep\n"
		"	addiu	$a0,$zero,0x7 # maspsx-keep\n"
		"	addiu	$a2,$zero,-0x1 # maspsx-keep\n"
		".L8007AFBC: # maspsx-keep\n"
		"	lbu	$v0,0x0($a1) # maspsx-keep\n"
		"	addiu	$a1,$a1,0x1 # maspsx-keep\n"
		"	addiu	$a0,$a0,-0x1 # maspsx-keep\n"
		"	sb	$v0,0x0($v1) # maspsx-keep\n"
		"	bne	$a0,$a2,.L8007AFBC # maspsx-keep\n"
		"	addiu	$v1,$v1,0x1 # maspsx-keep\n"
		".L8007AFD4: # maspsx-keep\n"
		"	j	.L8007AFFC # maspsx-keep\n"
		"	addiu	$v0,$zero,0x6 # maspsx-keep\n"
		".L8007AFDC: # maspsx-keep\n"
		"	lui	$a0,%hi(D_80011B6C) # maspsx-keep\n"
		"	jal	puts # maspsx-keep\n"
		"	addiu	$a0,$a0,%lo(D_80011B6C) # maspsx-keep\n"
		"	lbu	$a1,0x10($sp) # maspsx-keep\n"
		"	lui	$a0,%hi(D_80011B80) # maspsx-keep\n"
		"	jal	printf # maspsx-keep\n"
		"	addiu	$a0,$a0,%lo(D_80011B80) # maspsx-keep\n"
		".L8007AFF8: # maspsx-keep\n"
		"	addu	$v0,$zero,$zero # maspsx-keep\n"
		".L8007AFFC: # maspsx-keep\n"
		"	lw	$ra,0x28($sp) # maspsx-keep\n"
		"	lw	$s1,0x24($sp) # maspsx-keep\n"
		"	lw	$s0,0x20($sp) # maspsx-keep\n"
		"	jr	$ra # maspsx-keep\n"
		"	addiu	$sp,$sp,0x30 # maspsx-keep\n"
		"	.set	macro # maspsx-keep\n"
		"	.set	reorder # maspsx-keep\n"
	);
}
