#define ROOMLIB_UPDATE_TIMED_RENDER_NAME func_801941F4
#define ROOMLIB_UPDATE_TIMED_RENDER_SEED D_8018F21C
#define ROOMLIB_UPDATE_TIMED_RENDER_TABLE D_80195668
#include "../room_lib/RoomLib_UpdateTimedRender.inc"
