/* CC1_FLAGS: -G8 */
/* MASPSX_FLAGS: -G8 --use-comm-section */
/* Function body emitted as asm() (PSYQ GCC 2.7.2 register
 * allocation / scheduling diverges from the ROM pervasively).
 * Wrapped via maspsx's INCLUDE_ASM hack so the body is passed
 * through verbatim; bare global loads gp-rel via the .extern size
 * hints + `as -G8`. See tools/maspsx/PE1_IMPROVEMENTS.md. */
void __maspsx_include_asm_hack_Field_HandleStateTransition(void);
void __maspsx_include_asm_hack_Field_HandleStateTransition(void) {
	__asm__(
		"	.extern	g_BattleControlFlags,1 # maspsx-keep\n"
		"	.extern	g_FieldPadBits,1 # maspsx-keep\n"
		"	.extern	g_SceneFlagBits,1 # maspsx-keep\n"
		"	.extern	g_FieldRenderFlags,1 # maspsx-keep\n"
		"	.extern	D_8009D2D4,1 # maspsx-keep\n"
		"	.extern	D_8009D2A8,1 # maspsx-keep\n"
		"	.set	noreorder # maspsx-keep\n"
		"	.set	nomacro # maspsx-keep\n"
		"	.globl	Field_HandleStateTransition # maspsx-keep\n"
		"Field_HandleStateTransition: # maspsx-keep\n"
		"	addiu	$sp,$sp,-0x18 # maspsx-keep\n"
		"	sw	$ra,0x10($sp) # maspsx-keep\n"
		"	jal	CardObj_GetModeClass # maspsx-keep\n"
		"	addu	$a0,$zero,$zero # maspsx-keep\n"
		"	bnez	$v0,.L8003EB60 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lui	$v1,%hi(g_GameStateFlags) # maspsx-keep\n"
		"	lw	$v1,%lo(g_GameStateFlags)($v1) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	andi	$v0,$v1,0x4001 # maspsx-keep\n"
		"	bnez	$v0,.L8003EB58 # maspsx-keep\n"
		"	ori	$v0,$v1,0x4000 # maspsx-keep\n"
		"	addiu	$v0,$zero,0x4 # maspsx-keep\n"
		"	sw	$v0,g_BattleControlFlags # maspsx-keep\n"
		"	sw	$v0,g_FieldPadBits # maspsx-keep\n"
		"	ori	$v0,$v1,0x4000 # maspsx-keep\n"
		"	sw	$zero,g_SceneFlagBits # maspsx-keep\n"
		"	lui	$at,%hi(g_GameStateFlags) # maspsx-keep\n"
		"	sw	$v0,%lo(g_GameStateFlags)($at) # maspsx-keep\n"
		"	j	.L8003F064 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L8003EB58: # maspsx-keep\n"
		"	lui	$at,%hi(g_GameStateFlags) # maspsx-keep\n"
		"	sw	$v0,%lo(g_GameStateFlags)($at) # maspsx-keep\n"
		".L8003EB60: # maspsx-keep\n"
		"	lui	$v0,%hi(g_AnalogStickState) # maspsx-keep\n"
		"	lhu	$v0,%lo(g_AnalogStickState)($v0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	andi	$v1,$v0,0xF000 # maspsx-keep\n"
		"	addiu	$v0,$zero,0x4000 # maspsx-keep\n"
		"	beq	$v1,$v0,.L8003EB84 # maspsx-keep\n"
		"	addiu	$v0,$zero,0x7000 # maspsx-keep\n"
		"	bne	$v1,$v0,.L8003F058 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L8003EB84: # maspsx-keep\n"
		"	lui	$v0,%hi(g_GameStateFlags) # maspsx-keep\n"
		"	lw	$v0,%lo(g_GameStateFlags)($v0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	andi	$v0,$v0,0x4000 # maspsx-keep\n"
		"	beqz	$v0,.L8003EC50 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	jal	CardObj_GetModeClass # maspsx-keep\n"
		"	addu	$a0,$zero,$zero # maspsx-keep\n"
		"	addu	$v1,$v0,$zero # maspsx-keep\n"
		"	addiu	$v0,$zero,0x2 # maspsx-keep\n"
		"	beq	$v1,$v0,.L8003EC38 # maspsx-keep\n"
		"	addiu	$v0,$zero,0x1 # maspsx-keep\n"
		"	bne	$v1,$v0,.L8003EBD8 # maspsx-keep\n"
		"	addiu	$v0,$zero,0x6 # maspsx-keep\n"
		"	addu	$a0,$zero,$zero # maspsx-keep\n"
		"	lui	$a1,%hi(D_8009D1C0) # maspsx-keep\n"
		"	addiu	$a1,$a1,%lo(D_8009D1C0) # maspsx-keep\n"
		"	jal	CardObj_SetCommandPayload # maspsx-keep\n"
		"	addiu	$a2,$zero,0x2 # maspsx-keep\n"
		"	j	.L8003EC50 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L8003EBD8: # maspsx-keep\n"
		"	bne	$v1,$v0,.L8003EC50 # maspsx-keep\n"
		"	addu	$a0,$zero,$zero # maspsx-keep\n"
		"	addiu	$a1,$zero,0x2 # maspsx-keep\n"
		"	jal	CardObj_GetField # maspsx-keep\n"
		"	addu	$a2,$zero,$zero # maspsx-keep\n"
		"	beqz	$v0,.L8003EC50 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lui	$v0,%hi(g_GameStateFlags) # maspsx-keep\n"
		"	lw	$v0,%lo(g_GameStateFlags)($v0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	andi	$v0,$v0,0x8000 # maspsx-keep\n"
		"	bnez	$v0,.L8003EC28 # maspsx-keep\n"
		"	addu	$a0,$zero,$zero # maspsx-keep\n"
		"	addiu	$a1,$zero,0x1 # maspsx-keep\n"
		"	jal	CardObj_StartCommandWithBytes # maspsx-keep\n"
		"	addu	$a2,$zero,$zero # maspsx-keep\n"
		"	lui	$v0,%hi(g_GameStateFlags) # maspsx-keep\n"
		"	lw	$v0,%lo(g_GameStateFlags)($v0) # maspsx-keep\n"
		"	j	.L8003EC48 # maspsx-keep\n"
		"	ori	$v0,$v0,0x8000 # maspsx-keep\n"
		".L8003EC28: # maspsx-keep\n"
		"	lui	$a1,%hi(D_800921F8) # maspsx-keep\n"
		"	addiu	$a1,$a1,%lo(D_800921F8) # maspsx-keep\n"
		"	jal	CardObj_StartCommand4D # maspsx-keep\n"
		"	addu	$a0,$zero,$zero # maspsx-keep\n"
		".L8003EC38: # maspsx-keep\n"
		"	lui	$v0,%hi(g_GameStateFlags) # maspsx-keep\n"
		"	lw	$v0,%lo(g_GameStateFlags)($v0) # maspsx-keep\n"
		"	addiu	$v1,$zero,-0x4001 # maspsx-keep\n"
		"	and	$v0,$v0,$v1 # maspsx-keep\n"
		".L8003EC48: # maspsx-keep\n"
		"	lui	$at,%hi(g_GameStateFlags) # maspsx-keep\n"
		"	sw	$v0,%lo(g_GameStateFlags)($at) # maspsx-keep\n"
		".L8003EC50: # maspsx-keep\n"
		"	lui	$a0,%hi(D_800BE9A2) # maspsx-keep\n"
		"	lhu	$a0,%lo(D_800BE9A2)($a0) # maspsx-keep\n"
		"	addiu	$v0,$zero,-0x6001 # maspsx-keep\n"
		"	nor	$v1,$zero,$a0 # maspsx-keep\n"
		"	and	$v1,$v1,$v0 # maspsx-keep\n"
		"	lw	$v0,g_FieldPadBits # maspsx-keep\n"
		"	nor	$a0,$zero,$a0 # maspsx-keep\n"
		"	sw	$v0,g_FieldRenderFlags # maspsx-keep\n"
		"	andi	$v0,$a0,0x2000 # maspsx-keep\n"
		"	beqz	$v0,.L8003EC80 # maspsx-keep\n"
		"	addu	$a1,$v1,$zero # maspsx-keep\n"
		"	ori	$a1,$v1,0x4000 # maspsx-keep\n"
		".L8003EC80: # maspsx-keep\n"
		"	andi	$v0,$a0,0x4000 # maspsx-keep\n"
		"	beqz	$v0,.L8003EC90 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	ori	$a1,$a1,0x2000 # maspsx-keep\n"
		".L8003EC90: # maspsx-keep\n"
		"	sw	$zero,g_FieldPadBits # maspsx-keep\n"
		"	addu	$a2,$zero,$zero # maspsx-keep\n"
		"	andi	$t0,$a1,0xFFFF # maspsx-keep\n"
		"	lui	$t2,%hi(g_FieldRenderFlagTable) # maspsx-keep\n"
		"	addiu	$t2,$t2,%lo(g_FieldRenderFlagTable) # maspsx-keep\n"
		"	addiu	$t1,$zero,0x1 # maspsx-keep\n"
		"	lui	$a3,%hi(D_800A7770) # maspsx-keep\n"
		"	addiu	$a3,$a3,%lo(D_800A7770) # maspsx-keep\n"
		"	andi	$v1,$a2,0xFFFF # maspsx-keep\n"
		".L8003ECB4: # maspsx-keep\n"
		"	sll	$a1,$v1,2 # maspsx-keep\n"
		"	addu	$v0,$a1,$t2 # maspsx-keep\n"
		"	lw	$v0,0x0($v0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	and	$v0,$t0,$v0 # maspsx-keep\n"
		"	beqz	$v0,.L8003ECF0 # maspsx-keep\n"
		"	sllv	$a0,$t1,$v1 # maspsx-keep\n"
		"	addu	$a1,$a1,$a3 # maspsx-keep\n"
		"	lw	$v0,g_FieldPadBits # maspsx-keep\n"
		"	lw	$v1,0x0($a1) # maspsx-keep\n"
		"	or	$v0,$v0,$a0 # maspsx-keep\n"
		"	addiu	$v1,$v1,0x1 # maspsx-keep\n"
		"	sw	$v0,g_FieldPadBits # maspsx-keep\n"
		"	j	.L8003ECF8 # maspsx-keep\n"
		"	sw	$v1,0x0($a1) # maspsx-keep\n"
		".L8003ECF0: # maspsx-keep\n"
		"	addu	$v0,$a1,$a3 # maspsx-keep\n"
		"	sw	$zero,0x0($v0) # maspsx-keep\n"
		".L8003ECF8: # maspsx-keep\n"
		"	addiu	$a2,$a2,0x1 # maspsx-keep\n"
		"	andi	$v0,$a2,0xFFFF # maspsx-keep\n"
		"	sltiu	$v0,$v0,0x20 # maspsx-keep\n"
		"	bnez	$v0,.L8003ECB4 # maspsx-keep\n"
		"	andi	$v1,$a2,0xFFFF # maspsx-keep\n"
		"	lui	$a2,%hi(g_GameStateFlags) # maspsx-keep\n"
		"	lw	$a2,%lo(g_GameStateFlags)($a2) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	andi	$v0,$a2,0x1 # maspsx-keep\n"
		"	beqz	$v0,.L8003EDC0 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lw	$a0,g_FieldPadBits # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	bgez	$a0,.L8003EDB0 # maspsx-keep\n"
		"	lui	$v1,(0x7000007E >> 16) # maspsx-keep\n"
		"	lw	$v0,D_8009D2D4 # maspsx-keep\n"
		"	ori	$v1,$v1,0x7E # maspsx-keep\n"
		"	xor	$v0,$a0,$v0 # maspsx-keep\n"
		"	and	$v0,$v0,$a0 # maspsx-keep\n"
		"	and	$a0,$v0,$v1 # maspsx-keep\n"
		"	beqz	$a0,.L8003EDB4 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lw	$a1,D_8009D2A8 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	sll	$v0,$a1,2 # maspsx-keep\n"
		"	lui	$at,%hi(D_80092200) # maspsx-keep\n"
		"	addu	$at,$at,$v0 # maspsx-keep\n"
		"	lw	$v1,%lo(D_80092200)($at) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	and	$v0,$a0,$v1 # maspsx-keep\n"
		"	bne	$v0,$v1,.L8003EDB0 # maspsx-keep\n"
		"	addiu	$v1,$a1,0x1 # maspsx-keep\n"
		"	sw	$v1,D_8009D2A8 # maspsx-keep\n"
		"	addiu	$v0,$zero,0x9 # maspsx-keep\n"
		"	bne	$v1,$v0,.L8003EDB4 # maspsx-keep\n"
		"	lui	$v1,(0xAA108448 >> 16) # maspsx-keep\n"
		"	ori	$v1,$v1,0x8448 # maspsx-keep\n"
		"	lui	$v0,(0x12000 >> 16) # maspsx-keep\n"
		"	ori	$v0,$v0,0x2000 # maspsx-keep\n"
		"	or	$v0,$a2,$v0 # maspsx-keep\n"
		"	lui	$at,%hi(g_SceneDispatchToken) # maspsx-keep\n"
		"	sw	$v1,%lo(g_SceneDispatchToken)($at) # maspsx-keep\n"
		"	lui	$at,%hi(g_GameStateFlags) # maspsx-keep\n"
		"	sw	$v0,%lo(g_GameStateFlags)($at) # maspsx-keep\n"
		"	j	.L8003EDB4 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L8003EDB0: # maspsx-keep\n"
		"	sw	$zero,D_8009D2A8 # maspsx-keep\n"
		".L8003EDB4: # maspsx-keep\n"
		"	lw	$v0,g_FieldPadBits # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	sw	$v0,D_8009D2D4 # maspsx-keep\n"
		".L8003EDC0: # maspsx-keep\n"
		"	lui	$a0,%hi(g_GameState) # maspsx-keep\n"
		"	lw	$a0,%lo(g_GameState)($a0) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	andi	$v0,$a0,0x400 # maspsx-keep\n"
		"	beqz	$v0,.L8003EDE8 # maspsx-keep\n"
		"	lui	$v1,(0x40FFDC7F >> 16) # maspsx-keep\n"
		"	lw	$v0,g_FieldPadBits # maspsx-keep\n"
		"	ori	$v1,$v1,0xDC7F # maspsx-keep\n"
		"	and	$v0,$v0,$v1 # maspsx-keep\n"
		"	sw	$v0,g_FieldPadBits # maspsx-keep\n"
		".L8003EDE8: # maspsx-keep\n"
		"	andi	$v0,$a0,0x200 # maspsx-keep\n"
		"	beqz	$v0,.L8003EE24 # maspsx-keep\n"
		"	lui	$v1,(0x60FFDB04 >> 16) # maspsx-keep\n"
		"	lw	$v0,g_FieldPadBits # maspsx-keep\n"
		"	ori	$v1,$v1,0xDB04 # maspsx-keep\n"
		"	and	$a0,$v0,$v1 # maspsx-keep\n"
		"	lui	$v1,%hi(D_800B0DBF) # maspsx-keep\n"
		"	lb	$v1,%lo(D_800B0DBF)($v1) # maspsx-keep\n"
		"	addiu	$v0,$zero,0x1 # maspsx-keep\n"
		"	sw	$a0,g_FieldPadBits # maspsx-keep\n"
		"	beq	$v1,$v0,.L8003EE24 # maspsx-keep\n"
		"	lui	$v0,(0xDFFFFCFF >> 16) # maspsx-keep\n"
		"	ori	$v0,$v0,0xFCFF # maspsx-keep\n"
		"	and	$v0,$a0,$v0 # maspsx-keep\n"
		"	sw	$v0,g_FieldPadBits # maspsx-keep\n"
		".L8003EE24: # maspsx-keep\n"
		"	lui	$v0,(0x10000080 >> 16) # maspsx-keep\n"
		"	lw	$v1,g_FieldPadBits # maspsx-keep\n"
		"	ori	$v0,$v0,0x80 # maspsx-keep\n"
		"	and	$v0,$v1,$v0 # maspsx-keep\n"
		"	beqz	$v0,.L8003EE48 # maspsx-keep\n"
		"	lui	$v0,(0x7FFFFFFF >> 16) # maspsx-keep\n"
		"	ori	$v0,$v0,0xFFFF # maspsx-keep\n"
		"	and	$v0,$v1,$v0 # maspsx-keep\n"
		"	sw	$v0,g_FieldPadBits # maspsx-keep\n"
		".L8003EE48: # maspsx-keep\n"
		"	lui	$v0,(0x40000401 >> 16) # maspsx-keep\n"
		"	lw	$a0,g_FieldPadBits # maspsx-keep\n"
		"	ori	$v0,$v0,0x401 # maspsx-keep\n"
		"	and	$v0,$a0,$v0 # maspsx-keep\n"
		"	beqz	$v0,.L8003EE78 # maspsx-keep\n"
		"	lui	$v0,(0xEFFFFF7F >> 16) # maspsx-keep\n"
		"	ori	$v0,$v0,0xFF7F # maspsx-keep\n"
		"	lui	$v1,(0x7FFFFFFF >> 16) # maspsx-keep\n"
		"	ori	$v1,$v1,0xFFFF # maspsx-keep\n"
		"	and	$v0,$a0,$v0 # maspsx-keep\n"
		"	and	$v0,$v0,$v1 # maspsx-keep\n"
		"	sw	$v0,g_FieldPadBits # maspsx-keep\n"
		".L8003EE78: # maspsx-keep\n"
		"	lui	$v0,(0x20000300 >> 16) # maspsx-keep\n"
		"	lw	$a1,g_FieldPadBits # maspsx-keep\n"
		"	ori	$v0,$v0,0x300 # maspsx-keep\n"
		"	and	$v0,$a1,$v0 # maspsx-keep\n"
		"	beqz	$v0,.L8003EEB4 # maspsx-keep\n"
		"	lui	$v0,(0xBFFFFBFE >> 16) # maspsx-keep\n"
		"	ori	$v0,$v0,0xFBFE # maspsx-keep\n"
		"	lui	$a0,(0xEFFFFF7F >> 16) # maspsx-keep\n"
		"	ori	$a0,$a0,0xFF7F # maspsx-keep\n"
		"	lui	$v1,(0x7FFFFFFF >> 16) # maspsx-keep\n"
		"	ori	$v1,$v1,0xFFFF # maspsx-keep\n"
		"	and	$v0,$a1,$v0 # maspsx-keep\n"
		"	and	$v0,$v0,$a0 # maspsx-keep\n"
		"	and	$v0,$v0,$v1 # maspsx-keep\n"
		"	sw	$v0,g_FieldPadBits # maspsx-keep\n"
		".L8003EEB4: # maspsx-keep\n"
		"	lui	$v0,%hi(g_AnalogStickState) # maspsx-keep\n"
		"	lhu	$v0,%lo(g_AnalogStickState)($v0) # maspsx-keep\n"
		"	addiu	$v1,$zero,0x7000 # maspsx-keep\n"
		"	andi	$v0,$v0,0xF000 # maspsx-keep\n"
		"	bne	$v0,$v1,.L8003F030 # maspsx-keep\n"
		"	addiu	$a0,$zero,0x1 # maspsx-keep\n"
		"	lw	$v0,g_FieldPadBits # maspsx-keep\n"
		"	addiu	$v1,$zero,-0x7A # maspsx-keep\n"
		"	and	$v0,$v0,$v1 # maspsx-keep\n"
		"	sw	$v0,g_FieldPadBits # maspsx-keep\n"
		"	jal	MenuWidget_FindByModeAndSelectedBase # maspsx-keep\n"
		"	addu	$a1,$zero,$zero # maspsx-keep\n"
		"	beqz	$v0,.L8003EF68 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lui	$v1,%hi(g_AnalogStickX) # maspsx-keep\n"
		"	lbu	$v1,%lo(g_AnalogStickX)($v1) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	sltiu	$v0,$v1,0x14 # maspsx-keep\n"
		"	beqz	$v0,.L8003EF10 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lw	$v0,g_FieldPadBits # maspsx-keep\n"
		"	j	.L8003EF28 # maspsx-keep\n"
		"	ori	$v0,$v0,0x8 # maspsx-keep\n"
		".L8003EF10: # maspsx-keep\n"
		"	sltiu	$v0,$v1,0xE7 # maspsx-keep\n"
		"	bnez	$v0,.L8003EF2C # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lw	$v0,g_FieldPadBits # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	ori	$v0,$v0,0x20 # maspsx-keep\n"
		".L8003EF28: # maspsx-keep\n"
		"	sw	$v0,g_FieldPadBits # maspsx-keep\n"
		".L8003EF2C: # maspsx-keep\n"
		"	lui	$v1,%hi(g_AnalogStickY) # maspsx-keep\n"
		"	lbu	$v1,%lo(g_AnalogStickY)($v1) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	sltiu	$v0,$v1,0x14 # maspsx-keep\n"
		"	beqz	$v0,.L8003EF50 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lw	$v0,g_FieldPadBits # maspsx-keep\n"
		"	j	.L8003F02C # maspsx-keep\n"
		"	ori	$v0,$v0,0x40 # maspsx-keep\n"
		".L8003EF50: # maspsx-keep\n"
		"	sltiu	$v0,$v1,0xE7 # maspsx-keep\n"
		"	bnez	$v0,.L8003F030 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lw	$v0,g_FieldPadBits # maspsx-keep\n"
		"	j	.L8003F02C # maspsx-keep\n"
		"	ori	$v0,$v0,0x10 # maspsx-keep\n"
		".L8003EF68: # maspsx-keep\n"
		"	lui	$v1,%hi(g_AnalogStickX) # maspsx-keep\n"
		"	lbu	$v1,%lo(g_AnalogStickX)($v1) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	sltiu	$v0,$v1,0x5A # maspsx-keep\n"
		"	beqz	$v0,.L8003EFA4 # maspsx-keep\n"
		"	sltiu	$v0,$v1,0xA1 # maspsx-keep\n"
		"	lw	$a0,g_FieldPadBits # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	ori	$v0,$a0,0x8 # maspsx-keep\n"
		"	sw	$v0,g_FieldPadBits # maspsx-keep\n"
		"	sltiu	$v0,$v1,0x14 # maspsx-keep\n"
		"	beqz	$v0,.L8003EFCC # maspsx-keep\n"
		"	ori	$v0,$a0,0x9 # maspsx-keep\n"
		"	j	.L8003EFC8 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L8003EFA4: # maspsx-keep\n"
		"	bnez	$v0,.L8003EFCC # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lw	$a0,g_FieldPadBits # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	ori	$v0,$a0,0x20 # maspsx-keep\n"
		"	sw	$v0,g_FieldPadBits # maspsx-keep\n"
		"	sltiu	$v0,$v1,0xE7 # maspsx-keep\n"
		"	bnez	$v0,.L8003EFCC # maspsx-keep\n"
		"	ori	$v0,$a0,0x21 # maspsx-keep\n"
		".L8003EFC8: # maspsx-keep\n"
		"	sw	$v0,g_FieldPadBits # maspsx-keep\n"
		".L8003EFCC: # maspsx-keep\n"
		"	lui	$v1,%hi(g_AnalogStickY) # maspsx-keep\n"
		"	lbu	$v1,%lo(g_AnalogStickY)($v1) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	sltiu	$v0,$v1,0x5A # maspsx-keep\n"
		"	beqz	$v0,.L8003F008 # maspsx-keep\n"
		"	sltiu	$v0,$v1,0xA1 # maspsx-keep\n"
		"	lw	$a0,g_FieldPadBits # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	ori	$v0,$a0,0x40 # maspsx-keep\n"
		"	sw	$v0,g_FieldPadBits # maspsx-keep\n"
		"	sltiu	$v0,$v1,0x14 # maspsx-keep\n"
		"	beqz	$v0,.L8003F030 # maspsx-keep\n"
		"	ori	$v0,$a0,0x41 # maspsx-keep\n"
		"	j	.L8003F02C # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L8003F008: # maspsx-keep\n"
		"	bnez	$v0,.L8003F030 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lw	$a0,g_FieldPadBits # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	ori	$v0,$a0,0x10 # maspsx-keep\n"
		"	sw	$v0,g_FieldPadBits # maspsx-keep\n"
		"	sltiu	$v0,$v1,0xE7 # maspsx-keep\n"
		"	bnez	$v0,.L8003F030 # maspsx-keep\n"
		"	ori	$v0,$a0,0x11 # maspsx-keep\n"
		".L8003F02C: # maspsx-keep\n"
		"	sw	$v0,g_FieldPadBits # maspsx-keep\n"
		".L8003F030: # maspsx-keep\n"
		"	lw	$v0,g_FieldPadBits # maspsx-keep\n"
		"	lw	$a0,g_FieldRenderFlags # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	xor	$v1,$v0,$a0 # maspsx-keep\n"
		"	and	$v0,$v1,$v0 # maspsx-keep\n"
		"	and	$v1,$v1,$a0 # maspsx-keep\n"
		"	sw	$v0,g_BattleControlFlags # maspsx-keep\n"
		"	sw	$v1,g_SceneFlagBits # maspsx-keep\n"
		"	j	.L8003F064 # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		".L8003F058: # maspsx-keep\n"
		"	sw	$zero,g_FieldPadBits # maspsx-keep\n"
		"	sw	$zero,g_BattleControlFlags # maspsx-keep\n"
		"	sw	$zero,g_SceneFlagBits # maspsx-keep\n"
		".L8003F064: # maspsx-keep\n"
		"	lw	$ra,0x10($sp) # maspsx-keep\n"
		"	addiu	$sp,$sp,0x18 # maspsx-keep\n"
		"	jr	$ra # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	.set	macro # maspsx-keep\n"
		"	.set	reorder # maspsx-keep\n"
	);
}
