#include "common.h"
#include "pe1/room_fx.h"

#define ROOMLIB_DRAW_THREE_PARTICLES_FUNC func_8018FA40
#define ROOMLIB_DRAW_THREE_PARTICLES_TABLE D_80195394
#define ROOMLIB_DRAW_THREE_PARTICLES_PACKET D_801955D0
#define ROOMLIB_DRAW_THREE_PARTICLES_PRIMARY_ALPHA D_801955DA
#define ROOMLIB_DRAW_THREE_PARTICLES_FLOOR_ALPHA D_801955CA
#define ROOMLIB_DRAW_THREE_PARTICLES_FLOOR_HEIGHT g_FrameCount16
#include "../room_lib/RoomLib_DrawThreeTransformParticles.inc"
