#define ROOMLIB_UPDATE_TIMED_RENDER_NAME func_80194E38
#define ROOMLIB_UPDATE_TIMED_RENDER_SEED D_8018F20C
#define ROOMLIB_UPDATE_TIMED_RENDER_TABLE D_80195544
#include "../room_lib/RoomLib_UpdateTimedRender.inc"
