#include "common.h"

#define ROOMEFFECT_DROP_FIELD_DRAW_FUNC RoomEffect_DropFieldDraw_80191FB0
#define ROOMEFFECT_DROP_FIELD_DRAW_SPIN D_8018F01C
#define ROOMEFFECT_DROP_FIELD_DRAW_SHADOW_SPIN D_8018F00C
#define ROOMEFFECT_DROP_FIELD_DRAW_SHADOW_SCALE D_8018F054
#define ROOMEFFECT_DROP_FIELD_DRAW_SPRITE D_801974C0
#include "../room_lib/RoomEffect_DropFieldDraw.inc"
