/* CC1_FLAGS: -G8 */
/* MASPSX_FLAGS: -G8 --use-comm-section */
/* Function body emitted as asm() (PSYQ GCC 2.7.2 register
 * allocation / scheduling diverges from the ROM pervasively).
 * Wrapped via maspsx's INCLUDE_ASM hack so the body is passed
 * through verbatim; bare global loads gp-rel via the .extern size
 * hints + `as -G8`. See tools/maspsx/PE1_IMPROVEMENTS.md. */
void __maspsx_include_asm_hack_Aya_SetTotalExp(void);
void __maspsx_include_asm_hack_Aya_SetTotalExp(void) {
	__asm__(
		"	.extern	g_MenuPendingTotalExp,1 # maspsx-keep\n"
		"	.extern	g_MenuExpAllocTarget,1 # maspsx-keep\n"
		"	.extern	g_MenuExpReviewMaxLevel,1 # maspsx-keep\n"
		"	.extern	g_MenuSelectionLocked,1 # maspsx-keep\n"
		"	.extern	g_MenuLevelDisplayValue,1 # maspsx-keep\n"
		"	.extern	g_MenuHpMaxDisplayValue,1 # maspsx-keep\n"
		"	.extern	g_MenuBonusPointDisplayTarget,1 # maspsx-keep\n"
		"	.extern	g_BonusPointDisplayValue,1 # maspsx-keep\n"
		"	.extern	g_MenuLevelDisplayTarget,1 # maspsx-keep\n"
		"	.extern	g_MenuHpMaxDisplayTarget,1 # maspsx-keep\n"
		"	.extern	g_BonusPointBarAnimStep,1 # maspsx-keep\n"
		"	.set	noreorder # maspsx-keep\n"
		"	.set	nomacro # maspsx-keep\n"
		"	.globl	Aya_SetTotalExp # maspsx-keep\n"
		"Aya_SetTotalExp: # maspsx-keep\n"
		"	addiu	$sp,$sp,-0x38 # maspsx-keep\n"
		"	sw	$s0,0x20($sp) # maspsx-keep\n"
		"	addu	$s0,$a0,$zero # maspsx-keep\n"
		"	sw	$s1,0x24($sp) # maspsx-keep\n"
		"	addu	$s1,$a1,$zero # maspsx-keep\n"
		"	sw	$s4,0x30($sp) # maspsx-keep\n"
		"	addu	$s4,$a2,$zero # maspsx-keep\n"
		"	addu	$a0,$zero,$zero # maspsx-keep\n"
		"	sw	$ra,0x34($sp) # maspsx-keep\n"
		"	sw	$s3,0x2C($sp) # maspsx-keep\n"
		"	jal	Menu_SetBattleEquipMode # maspsx-keep\n"
		"	sw	$s2,0x28($sp) # maspsx-keep\n"
		"	jal	BattleCmd_SyncActiveAmmo # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lui	$s2,%hi(g_AyaSaveTotalExp) # maspsx-keep\n"
		"	addiu	$s2,$s2,%lo(g_AyaSaveTotalExp) # maspsx-keep\n"
		"	lw	$v0,0x0($s2) # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	sw	$v0,g_MenuPendingTotalExp # maspsx-keep\n"
		"	addu	$v0,$v0,$s0 # maspsx-keep\n"
		"	sw	$v0,g_MenuExpAllocTarget # maspsx-keep\n"
		"	jal	Aya_GetLevelExpTable # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lw	$a0,g_MenuPendingTotalExp # maspsx-keep\n"
		"	jal	Stat_BinarySearch # maspsx-keep\n"
		"	addu	$a1,$v0,$zero # maspsx-keep\n"
		"	sw	$v0,g_MenuExpReviewMaxLevel # maspsx-keep\n"
		"	addiu	$v0,$zero,0x1 # maspsx-keep\n"
		"	sw	$v0,g_MenuSelectionLocked # maspsx-keep\n"
		"	lui	$v0,%hi(g_AyaPeBonusPool) # maspsx-keep\n"
		"	lhu	$v0,%lo(g_AyaPeBonusPool)($v0) # maspsx-keep\n"
		"	lui	$a0,%hi(g_AyaSaveLevel) # maspsx-keep\n"
		"	lbu	$a0,%lo(g_AyaSaveLevel)($a0) # maspsx-keep\n"
		"	lui	$a1,%hi(g_AyaHpMax) # maspsx-keep\n"
		"	lhu	$a1,%lo(g_AyaHpMax)($a1) # maspsx-keep\n"
		"	lui	$v1,%hi(g_AyaBonusPoints) # maspsx-keep\n"
		"	lw	$v1,%lo(g_AyaBonusPoints)($v1) # maspsx-keep\n"
		"	addu	$v0,$v0,$s1 # maspsx-keep\n"
		"	lui	$at,%hi(g_AyaPeBonusPool) # maspsx-keep\n"
		"	sh	$v0,%lo(g_AyaPeBonusPool)($at) # maspsx-keep\n"
		"	sw	$a0,g_MenuLevelDisplayValue # maspsx-keep\n"
		"	sw	$a1,g_MenuHpMaxDisplayValue # maspsx-keep\n"
		"	sw	$v1,g_MenuBonusPointDisplayTarget # maspsx-keep\n"
		"	sw	$v1,g_BonusPointDisplayValue # maspsx-keep\n"
		"	jal	Aya_GetLevelExpTable # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lw	$a0,g_MenuExpAllocTarget # maspsx-keep\n"
		"	jal	Stat_BinarySearch # maspsx-keep\n"
		"	addu	$a1,$v0,$zero # maspsx-keep\n"
		"	lw	$v1,g_MenuLevelDisplayValue # maspsx-keep\n"
		"	sw	$v0,g_MenuLevelDisplayTarget # maspsx-keep\n"
		"	slt	$v1,$v1,$v0 # maspsx-keep\n"
		"	beqz	$v1,.L8004B818 # maspsx-keep\n"
		"	lui	$v0,(0x1869F >> 16) # maspsx-keep\n"
		"	ori	$v0,$v0,0x869F # maspsx-keep\n"
		"	lui	$a1,(0x1869F >> 16) # maspsx-keep\n"
		"	lui	$a0,%hi(g_AyaPeBonusPool) # maspsx-keep\n"
		"	lhu	$a0,%lo(g_AyaPeBonusPool)($a0) # maspsx-keep\n"
		"	lw	$v1,g_MenuBonusPointDisplayTarget # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	addu	$v1,$v1,$a0 # maspsx-keep\n"
		"	slt	$v0,$v0,$v1 # maspsx-keep\n"
		"	bnez	$v0,.L8004B810 # maspsx-keep\n"
		"	ori	$a1,$a1,0x869F # maspsx-keep\n"
		"	addu	$a1,$v1,$zero # maspsx-keep\n"
		".L8004B810: # maspsx-keep\n"
		"	sw	$a1,g_MenuBonusPointDisplayTarget # maspsx-keep\n"
		"	sh	$zero,0x1E($s2) # maspsx-keep\n"
		".L8004B818: # maspsx-keep\n"
		"	lui	$s3,%hi(g_AyaStatAgility) # maspsx-keep\n"
		"	addiu	$s3,$s3,%lo(g_AyaStatAgility) # maspsx-keep\n"
		"	addu	$s1,$zero,$zero # maspsx-keep\n"
		"	lui	$s2,%hi(g_BonusPointStatDeltas) # maspsx-keep\n"
		"	addiu	$s2,$s2,%lo(g_BonusPointStatDeltas) # maspsx-keep\n"
		".L8004B82C: # maspsx-keep\n"
		"	lh	$a1,0x0($s3) # maspsx-keep\n"
		"	addiu	$s3,$s3,0x2 # maspsx-keep\n"
		"	addu	$a0,$s1,$zero # maspsx-keep\n"
		"	sll	$s0,$s1,2 # maspsx-keep\n"
		"	lui	$a2,%hi(g_BonusPointStatQueryResults) # maspsx-keep\n"
		"	addiu	$a2,$a2,%lo(g_BonusPointStatQueryResults) # maspsx-keep\n"
		"	addu	$a2,$s0,$a2 # maspsx-keep\n"
		"	addu	$a3,$zero,$zero # maspsx-keep\n"
		"	addiu	$s1,$s1,0x1 # maspsx-keep\n"
		"	jal	Stat_QueryLevelAndSubLevel # maspsx-keep\n"
		"	sw	$a1,0x0($s2) # maspsx-keep\n"
		"	lw	$v1,g_MenuLevelDisplayTarget # maspsx-keep\n"
		"	lw	$v0,g_MenuLevelDisplayValue # maspsx-keep\n"
		"	lui	$a1,%hi(g_BonusPointStatMultipliers) # maspsx-keep\n"
		"	addiu	$a1,$a1,%lo(g_BonusPointStatMultipliers) # maspsx-keep\n"
		"	subu	$v1,$v1,$v0 # maspsx-keep\n"
		"	sll	$v0,$v1,2 # maspsx-keep\n"
		"	addu	$v0,$v0,$v1 # maspsx-keep\n"
		"	sll	$v0,$v0,1 # maspsx-keep\n"
		"	lui	$at,%hi(g_BonusPointStatMultipliers) # maspsx-keep\n"
		"	addu	$at,$at,$s0 # maspsx-keep\n"
		"	sw	$v0,%lo(g_BonusPointStatMultipliers)($at) # maspsx-keep\n"
		"	slti	$v0,$s1,0x7 # maspsx-keep\n"
		"	bnez	$v0,.L8004B82C # maspsx-keep\n"
		"	addiu	$s2,$s2,0x4 # maspsx-keep\n"
		"	addu	$a0,$zero,$zero # maspsx-keep\n"
		"	addiu	$a2,$sp,0x10 # maspsx-keep\n"
		"	lui	$v0,%hi(g_BonusPointStatDeltas) # maspsx-keep\n"
		"	lw	$v0,%lo(g_BonusPointStatDeltas)($v0) # maspsx-keep\n"
		"	lw	$a1,0x0($a1) # maspsx-keep\n"
		"	addu	$a3,$zero,$zero # maspsx-keep\n"
		"	jal	Stat_QueryLevelAndSubLevel # maspsx-keep\n"
		"	addu	$a1,$v0,$a1 # maspsx-keep\n"
		"	lw	$a0,0x10($sp) # maspsx-keep\n"
		"	jal	Battle_GetScaledMaxHP # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	sw	$v0,g_MenuHpMaxDisplayTarget # maspsx-keep\n"
		"	addiu	$v0,$zero,0x2 # maspsx-keep\n"
		"	sw	$v0,g_BonusPointBarAnimStep # maspsx-keep\n"
		"	jal	Inv_LoadWayneItemsAsOverride # maspsx-keep\n"
		"	addu	$a0,$s4,$zero # maspsx-keep\n"
		"	jal	Menu_CreateExpReviewView # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	jal	Akao_SetBgmVolumeFade # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	jal	Menu_ResetInputState # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	lw	$ra,0x34($sp) # maspsx-keep\n"
		"	lw	$s4,0x30($sp) # maspsx-keep\n"
		"	lw	$s3,0x2C($sp) # maspsx-keep\n"
		"	lw	$s2,0x28($sp) # maspsx-keep\n"
		"	lw	$s1,0x24($sp) # maspsx-keep\n"
		"	lw	$s0,0x20($sp) # maspsx-keep\n"
		"	addiu	$sp,$sp,0x38 # maspsx-keep\n"
		"	jr	$ra # maspsx-keep\n"
		"	nop # maspsx-keep\n"
		"	.set	macro # maspsx-keep\n"
		"	.set	reorder # maspsx-keep\n"
	);
}
